CONTRIBUTING.md, README.md
~ deleted an unnecessary "'s" in README.md
~ fixes #132
=> Guidlines for contributing in CONTRIBUTING.md

composer.json
=> Composerify

includes/forms/template.php
- - -
The purpose of this pull request is primarily to address some pain points I recently encountered while working with the Give plugin on a client project. They wanted to update the text in places, and I found that difficult to do in some cases.
- - -
- Added a Wordpress filter to allow developers to modify the 'Select Payment Method' legend text.
- Modified existing Wordpress filter controlling submit button text so that it passes `$form_id` to hooks. This allows developers to access form options when generating submit button text. In my case this was necessary to output default donation amount, e.g. "Donate $5.00 Now".
=> Extensibility improvements

includes/forms/functions.php
Use the `give_shortcode_button_condition` hook to hide the Give shortcut button on Give Form editors, etc.
=> Show the shortcode button/dropdown conditionally

includes/admin/shortcodes/shortcode-give-form.php, includes/forms/template.php, includes/shortcodes.php
Ok, the shortcode "show_content" attribute now accepts three values:
- none
- above
- below
=> The previous pull-request was a little unfinished/borked (sorry) This should do it.

includes/emails/template.php
For issue #338 
Also adds get_header() and get_footer() to wrap this page in the basic template of the site.
=> Add no-cache headings to the Email Receipt page.

includes/install.php
The `$wp_roles->roles` array is multidimensional, so checking for the presence of the `give_manager` role by using `in_array()` will always return false, and the plugin will re-initialize roles and capabilities on every admin page load (including admin-ajax calls). It's slowing down one of my clients' sites by about a second per page load. Use `array_key_exists()` instead and get faster admin load times!
=> Fix check in give_install_roles_on_network

assets/css/give-admin.css, assets/scss/admin/shortcodes.scss, includes/admin/shortcodes/class-shortcode-button.php
This changes the load sequence of the "mce_external_plugins" filter so it is triggered correctly when the SiteOrigin Widgets Bundle plugin is active.
Fixes #405
=> #405 : SiteOrigin Widgets Bundle plugin compat

includes/forms/template.php
$form_id wasn't being added to the far attribute for card number, name, and cvc fields, causing the label/form field relationship to be invalid. See also #379, which added the form IDs but appears to have missed a few.
=> Correct for/id relationship in credit card fields

includes/payments/class-donators-gravatars.php
Use of constructor methods with same name as class is deprecated.
=> Rename constructor method to __contruct

includes/admin/system-info.php, readme.txt
=> Added additional checks to the "System Info" settings tab #506

includes/admin/payments/view-order-details.php
Encode donor email address before passing to url as parameter to remove any bug.
Related to https://github.com/WordImpress/Give/issues/717
=> Fix view all donation for this donor link

includes/admin/payments/actions.php, includes/class-give-customer.php
Increase/decrease user lifetime donation stat when user increase/decrease donation amount from payment detail page in wp backend.
Releated to https://github.com/WordImpress/Give/issues/714
=> Fix user lifetime donation stat 

includes/admin/customers/customer-actions.php, includes/admin/payments/actions.php, includes/admin/reporting/pdf-reports.php, includes/admin/upgrades/upgrade-functions.php, includes/emails/actions.php
This pull request is unifying different permission error messages:
Source:
Note: permission error messages fired by current_user_can() when the user has no capability to do something.
=> Permission Error Messages

includes/admin/class-give-settings.php, includes/admin/shortcodes/abstract-shortcode-generator.php, includes/admin/shortcodes/shortcode-give-form.php, includes/admin/shortcodes/shortcode-give-goal.php, includes/admin/system-info.php, includes/class-give-gravatars.php, includes/gateways/offline-donations.php, tests/unit-tests/tests-login-register.php
More i18n Improvments:
1. Use `__()` in two more strings, making them translatable to other languages.
2. use sprintf() to show the `%s` placeholder. Not in all languages the tag-list is in the end. This why we should use placeholders. Translation editor will decide where to place the placeholder.
=> i18n Improvments

includes/admin/customers/customers.php, includes/admin/reporting/tools.php, includes/admin/welcome.php, includes/scripts.php
I missed those strings... #471
=> i18n: don't esc strings with html code

includes/payments/functions.php
We can only pass three params to [`remove_filter`](https://codex.wordpress.org/Function_Reference/remove_filter) function
=> Do not pass more then three params to remove_filter

assets/scss/admin/settings.scss, includes/admin/class-give-settings.php, includes/admin/reporting/reports.php
You added `give-hide-heading` to hide `<H1>` titles in the admin (#820). We should use the default WordPress class for screen readers.
For more info, read this: https://make.wordpress.org/accessibility/2015/02/09/hiding-text-for-screen-readers-with-wordpress-core/
=> a11y: use WordPress default screen-reader class

.travis.yml, includes/class-give-db.php, includes/class-give-donate-form.php, includes/forms/template.php, phpunit.xml, tests/bin/install.sh, tests/bin/travis.sh, tests/unit-tests/tests-give.php, tests/unit-tests/tests-install.php
In this PR I have refactored our `travis.yml` file so that it now tests PHP 5.2 
As well, we are now excluding directories that should not be tested in `phpunit.xml` 
The `install.sh` and `travis.sh` are now run from the tests directory
There are also doc block updates and a new `installed()` method (which was breaking the tests) is now added to `Give_DB`
=> Unit test fixes and resolved travis-ci issues

includes/admin/dashboard-widgets.php
Regarding #837 
I found out that the total is calculating correctly, but it IS caching the request for 1 hour see: https://github.com/WordImpress/Give/blob/master/includes/payments/class-payment-stats.php#L178-L181
After revisiting this widget, I created https://github.com/WordImpress/Give/issues/839 so we can focus on improving it in the future.
=> Fixed incorrect formatting in dashboard widget #837

templates/shortcode-login.php, templates/shortcode-register.php
Remove unneeded title attribute.
=> a11y in give shortcode

includes/admin/payments/view-order-details.php
=> Transaction Details > Donation Details Metabox (Responsiveness)

includes/forms/template.php
The irony is not lost on me that the commit text has a typo in it.
=> Fix typo: "login" is a noun or adjective. "log in" is the verb.

give.php, includes/admin/class-addon-activation-banner.php, includes/admin/class-i18n-module.php, readme.txt, tests/unit-tests/tests-give.php
I added the new class `Give_i18n_Banner` with support for WP.org GlotPress #1021 
I also updated the styles for the Add-on activation banner #1081 
I switched to several different languages like Spanish and French and tested the banner. I also switched to an author user to ensure the banner did not display improperly.
New i18n banner:
Improved Add-on activation style:
- New feature (non-breaking change which adds functionality)
- UX improvements #1081
=> New i18n banner and Add-on activation banner improvements

tests/unit-tests/tests-scripts.php
The test checks whether the `give_is_admin_page()` function exist, to include the `includes/admin/admin-pages.php` file.
> if ( ! function_exists( 'give_is_admin_page' ) ) {
> 	  include GIVE_PLUGIN_DIR . 'includes/admin/admin-pages.php';
> }
But this if statement will always return false because `give_is_admin_page()` function is in the `includes/admin/admin-pages.php` file.
=> Test: remove unneeded test check

includes/admin/EDD_SL_Plugin_Updater.php, tests/unit-tests/tests-scripts.php
Replace `global $pagenow` with `$screen = get_current_screen()`
Issue #1017 
Non-breaking change which fixes an issue.
=> Issue/1017 - STOP USING `global $pagenow`

tests/unit-tests/tests-logging.php, tests/unit-tests/tests-post-types.php
Replace `global $wp_post_types;` with `$wp_post_types = get_post_types();`
Issue #1097 
Non-breaking change which fixes an issue.
=> Issue/1097 - STOP USING `global $wp_post_types`

tests/unit-tests/tests-logging.php
Replace `global $wp_taxonomies;` with `$wp_taxonomies = get_taxonomies();`
Issue #1099  
Non-breaking change which fixes an issue.
=> Issue/1099 - STOP USING `global $wp_taxonomies`

tests/unit-tests/tests-post-types.php
Replace `global $wp_post_statuses;` with `$wp_post_statuses = get_post_stati();`
Issue #1101 
Non-breaking change which fixes an issue.
=> Issue/1101 - STOP USING `global $wp_post_statuses`

includes/admin/class-admin-notices.php, includes/admin/customers/class-customer-table.php, includes/admin/dashboard-widgets.php, includes/admin/payments/actions.php, includes/admin/reporting/class-donor-reports-table.php, includes/admin/welcome.php
In some place the `admin_url()` function was used not as it should be, for example the `$path` parameter was outside of the function or has a leading `/` character. Or in one case we used only the path, without the `admin_url()` function.
Any way, this PR fixes those issues.
=> Fix admin_url() function usage

includes/class-give-email-access.php
The filter did something wrong to the text... it's not translatable. This PR fixes the issue and makes the string translatable and filterable.
=> i18n: Fix wrong use to translation string function

includes/gateways/paypal-standard.php, templates/payment-processing.php
This PR fixes #1152 by only checking the `invoice` variable if the transaction type is set to "Standard Transaction":
As well, I did a thorough review of the PayPal Standard gateway code an added some inline doc clarity and decoupled some of the nested conditionals.
I have processed multiple live PayPal Standard transactions in both "Donation" and "Standard Transaction" mode. 
- I checked the IPN history and verified that for "Standard" transactions the `invoice` var is sent
- I verified when a payment is made it completes properly once the IPN is received regardless of the transaction type in use. 
=> Fix PayPal Standard Failing for Donation Transactions - Issue/1152

license.txt
It's standard practice to include the license.txt file. This most often opens with Copyright text if any, then GPL content. 
This was emulated off both the WooCommerce and EDD license.txt files.
=> Add license.txt

templates/shortcode-profile-editor.php
=> Re issues/997

includes/payments/functions.php
We can pass the first param of `give_get_payment_status`  as an object which can be an instance of `WP_Post` or `Give_Payment`, so if param is an instance of `Give_Payment` there are not need to recreate of an object.
By visiting some page like donations list where `give_get_payment_status` function is using.
perfomance improvment
=> refactor give_get_payment_status

includes/admin/settings/class-settings-cmb2-backward-compatibility.php
This will update cmb2 backward compatibility to work better with WP verison `4.7`. This will fix #1166.
=> Update cmb2 backword competibility to WP version 4.7

includes/admin/forms/metabox.php
The `cmb2_meta_boxes` filter is mostly for back-compatibility and it is recommended to use the action and the API to add boxes/fields. I have updated to use the `cmb2_init` and to loop through the metaboxes and register them with `new_cmb2_box`. This is untested, but should work exactly the same, but be more resilient as it does not depend on [others using the filter correctly](https://wordpress.org/support/topic/fatal-error-upon-activation-24/).
=> Update to use `cmb2_init` action and `new_cmb2_box` function.

includes/admin/give-metabox-functions.php
undefined index: options in give-metabox-functions.php on line 616
notice will be generated when viewing form edit page
if only
* offline payment gateways enable globally,
* offline payment gateway disable for current form.
=> Fix notice

includes/admin/forms/dashboard-columns.php
I think, I miss to test direct donation link for a specific form. This will fix bug generated when working on #1368. For example links in `Donations` column pointing to wrong url.
=> Update url in form table to show donation logs for specific form

includes/admin/settings/class-settings-cmb2-backward-compatibility.php
There are new updates for filter and action in WordPress 4.7 https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/
That why I added the new filter and action support in cmb2 backward compatibility.
We are facing some issues in add-ons with cmb2 backward compatibility
https://github.com/WordImpress/Give-Email-Reports/issues/21
https://github.com/WordImpress/Give-Constant-Contact/issues/22
This PR will fix those issues.
=> Fix version comperision

includes/admin/settings/class-settings-display.php
Updated "Term and Conditions" to "Terms and Conditions"
=> Typo in Terms and Conditions Settings page.

includes/admin/settings/class-settings-general.php
Changed the reCAPTCHA link to a shortlink so we can change it on the fly if Google happens to change their URLs or the new "Invisible" reCAPTCHA ever gets launched officially.
This is the new link: http://docs.givewp.com/recaptcha
=> Change reCAPTCHA to shortlink for easier redirect in the future

includes/admin/forms/class-metabox-form-data.php
Because it conflicted with the Settings Terms shortlink
=> Changing the Forms Terms shortlink 

includes/admin/reporting/class-sales-logs-list-table.php
=> Show unnamed title

includes/admin/settings/class-settings-cmb2-backward-compatibility.php
In PHP 7 you can not create function or class name directly from array value.
For example` $field['func']['function'][0]->$field['func']['function'][1]( $field_obj, $saved_value, '', '', $field_type_obj )`
This can because of fatal error or notices.
=> Fix cmb2 compability issue with php7

includes/scripts.php
I reviewed the issue #1535 and related Github/WP.org forum posts and determined removing hyphens `icomoon.eot?-ngjl88` => `icomoon.eot?ngjl88`. 
This should resolve the problem as people have confirmed.
=> Removed hyphens flagging mod_security regex #1535

includes/admin/class-give-settings.php, includes/admin/forms/class-metabox-form-data.php, includes/admin/give-metabox-functions.php, includes/forms/template.php
1. oEmbeds and Shortcode support 
As described in #1545 - we were outputting a notification for the Goal Complete message which closes the form from accepting further donations. This is pretty weak functionality. Likely, people would want to use this to output a shortcode, embed a video, etc. 
2. WYSIWYGs now support `default` arg. 
I noticed that we were passing some default text in and the current field wasn't supporting that so I fixed it here: https://github.com/WordImpress/Give/pull/1549/commits/91e6923438553e0613eccf2a9bd477cd9713560a#diff-f3d5982e056a4167c9ee02f2c77d6031R392 
Also reformatted the code to WP coding standards.
**Video Embed w/ YouTube:**
**Shortcode Usage:**
**Default content WYSIWYG support:**
- Enhancement
=> Use `the_content` to output Goal complete message #1545

includes/admin/class-admin-settings.php, includes/admin/forms/class-metabox-form-data.php, includes/scripts.php
This PR will resolve #1566 
Note: You can see implementation here:
https://github.com/WordImpress/Give-Settings-API-Example/tree/feature/colorpicker
https://github.com/WordImpress/Give-Settings-API-Example/blob/feature/colorpicker/includes/class-setting-api-fields.php#L136#L144
=> Add colorpicker setting field

includes/forms/functions.php
Fixes #1578 
1. If the upgrade routine not run ensured that forms are still publicly accessible.
2. If the upgrade routine has not run AND form is set to logged in only, that the setting is unchanged
=> Updated give_logged_in_only to return enabled if metakey missing

includes/admin/upgrades/upgrade-functions.php, includes/scripts.php
I have added an exception for the `_give_customize_offline_donations` within the 1.8 upgrade routine to fix #1579 
As well, the upgrade routine can now be ran anywhere within wp-admin and won't throw a JS error due to not being able to access the `give_vars` variable from outside Give admin pages. This fixes #1580 
1. Fresh install, pre-form upgrade within 1.8
2. Verified upgrade JS window appears.
3. Verified offline donations field is set properly
=> Fixes for #1579 and #1580

includes/admin/settings/class-settings-gateways.php, includes/gateways/paypal-standard.php
I have added an option within _WP-Admin > Donations > Gateways > PayPal Standard_ to add the Billing Details fieldset. When enabled this field passes all data to PayPal. I checked to ensure fields are passed properly between donation and standard mode. The only field that wasn't passing was Zipcode, which I have fixed. 
Fixes #1573 
With billing fields enabled/disable - or the option not set in the db yet.
Fields passed properly to paypal in both donation and standard transaction mode:
- New feature (non-breaking change which adds functionality)
=> New option to toggle billing details and corresponding logic #1573

includes/admin/give-metabox-functions.php
Give now supports `desc` along with `description` via the `give_get_field_description()` function. 
Fixesd #1668
=> Added additional conditional check for $field[‘desc’] #1668

includes/misc-functions.php, tests/unit-tests/tests-misc-functions.php
=> Fix: add missing fx give_get_currency_name

includes/misc-functions.php, tests/unit-tests/tests-misc-functions.php
@DevinWalker I think it will be good to have wrapper function around WordPress post meta related functions. It will help us to provide backward compatibility easily in future.
Added New functions
=> Add post type meta data related functions

includes/admin/reporting/pdf-reports.php
This PR is for #1692 
This issue has been tested in 4 different use cases for reports generation in PDF:
1. with both Categories and Tags disabled
2. with Categories disabled and Tags enabled
3. with Categories enabled and Tags disabled
4. with both Categories and Tags enabled
=> Fixed - Issue #1692

give.php
There were spaces instead of tabs, and the code didn't line up with the rest of the code in the function.
I converted spaces to tabs to adhere to proper WordPress coding standards.
No need to test. This was just a small coding style change.
Coding style change.
- [ x ] My code is tested. (N/A)
- [ x ] My code follows the WordPress code style.
- [ x ] My code follows has proper inline documentation. (N/A)
=> Tabs, not spaces

templates/shortcode-goal.php
Fire `give_goal_amount_funded_percentage_output` filter early to control all `$progress` output.
For more info check this: https://github.com/WordImpress/Give-Fee-Recovery/issues/53#issuecomment-304024290
=> Change give_goal_amount_funded_percentage_output filter position

includes/admin/welcome.php, includes/api/class-give-api.php, includes/deprecated/deprecated-functions.php, includes/misc-functions.php
1. Using renamed function within deprecated function
2. Providing the `replacement` param within `_give_deprecated_function()`
=> Code updates to PR #1730

includes/ajax-functions.php, includes/deprecated/deprecated-filters.php, includes/deprecated/deprecated-functions.php, includes/forms/template.php
=> Fix/ecommerce terminology: Rename give_checkout_button_purchase function

templates/shortcode-goal.php
Following filter do not have `$form_id` as an argument, so the developer can feel difficult to customize it.
https://github.com/WordImpress/Give/blob/master/templates/shortcode-goal.php#L50
https://github.com/WordImpress/Give/blob/master/templates/shortcode-goal.php#L51
=> Refactor: goal template and add extra params to filters

includes/payments/class-give-payment.php
This PR will update `"give_give_update_payment_meta_{$meta_key}"` --> `"give_update_payment_meta_{$meta_key}"`
=> Fix: typo in filter name

includes/login-register.php, tests/unit-tests/tests-login-register.php
Fixed incomplete PHPunit tests for login and register functions.
=> Fixed login and register phpunit tests

give.php, includes/actions.php, includes/admin/upgrades/upgrade-functions.php, includes/emails/class-give-email-tags.php, includes/install.php, tests/unit-tests/tests-give.php
I refactored how Give is initialized so that we're loading it at the proper point of time when WP is ready. 
- `$instance` is now `protected static $_instance` 
- New `private function init_hooks()`
- Additional hooks added for `before_give_init` and `give_loaded`
- Fixed issues with using `@Give` within `install.php` 
**Note:** A lot of the code is inspired by WooCommerce's method of loading which is quite clean and efficient. If you take a look at their main file, you'll see what I mean.
Manually and PHPunit tests.
- Code optimization
=> Issue/1772 - Give initialization improvement and resolving install issue

includes/admin/class-i18n-module.php
1. Added `init` method to properly get user's locale (it was loading before WP was ready prior).
2. Removed unnecessary arg method
Manually
- i18n improvement for 4.7+ `get_users_locale()` function
=> i18n Banner Displays Per User's Locale

includes/admin/payments/class-payments-table.php
This PR is for #1824 and related to #1199 
A issue arised when there is no `$form_id` present, then the `$form_id set to `null` created issue which is solved and tested.
=> Hotfix for Issue 1824

includes/emails/template.php
fix #1929 
- Give 1.8.12 branch
- Latest WordPress
- Preview all email tags.
Set Preview for `{user_email}` and  `{billing_address}`.
For `{user_email}` default User email address.
For `{billing_address}` set blank value for preview.
=> Fix issue 1929

includes/class-give-db.php, includes/class-give-donor.php
1. Load cached instance of Give_DB_Donors
2. Add empty param check in Give_DB
=> Performance

includes/admin/upgrades/class-give-updates.php
Replace:
* `Donations <span class="update-plugins count-%1$d"><span class="plugin-count">%1$d</span></span>`
With:
* `Donations %s`
Moving the HTML tags outside of the translation string.
=> i18n: Avoid using HTML tags in translation strings

includes/class-give-cli-commands.php, includes/install.php, includes/payments/class-give-payment.php
The default value for `decimal_separator` is now set during `register_activation_hook`.
Related #2035
=> GH#2035 Added default decimal separator

includes/admin/reports/class-give-graph.php
See #2053 
Added a regex to add thousands separator to the amounts along the Y-axis in the Reports > Income graph.
=> GH#2053 Fixes thousands separator in reports

templates/shortcode-receipt.php
This PR fixes issue #1396 
As discussed with @ravinderk on call and as @mathetos [comment](https://github.com/WordImpress/Give/issues/1396#issuecomment-273643033), I have made changes for the offline donation only, these changes will add the heading "Your Donation is Almost Complete!" and below of it the Instruction for the offline donation would be shown.
Let me know if any changes are required.
- Tested by creating donation through offline payment and other test payment gateway.
- Tested through Donation history page.
- Tested the filter used inside this PR.
- Changes for offline donation in Donation Receipt page.
- Added filters to allow the developer or third-party plugins modify the content.
=> Changed the layout of the donation receipt for offline payment. #1396

includes/class-give-roles.php
This PR fixes issue #2022 
- Tested the "Give Accountant" role with activated WooCommerce and without activated, in both cases, the user with "Give accountant" role can access the admin dashboard.
- Tested other user role (Give Worker, Give Manager ) to check if, it works as expected or not.
- Tested It by creating sample order ( in WooCommerce ) and donation ( in Give ).
Added woocoommerce filter to allow the access to the wp-admin for the user who holds 'Give Accountant' user role.
=> Allow admin dashboard to 'Give Accoutant' user role even though WooCommerce is active.

assets/js/admin/admin-scripts.js, includes/admin/payments/class-payments-table.php
PR for comment: https://github.com/WordImpress/Give/issues/2100#issuecomment-332620642
Remove the give-message parameter from url once user click on the remove notices button
Mannualy Tested
=> Remove give-message parameter #2100

assets/scss/admin/system-info.scss, includes/admin/tools/views/html-admin-page-system-info.php
The notice is now gone and it looks like it does in #2141 without the white box.
Resolves #2141 
- Manually
See issue
- UX improvement
=> Issue 2141 - Adjusted the download "System Settings" notice to prevent it moving

includes/admin/tools/export/class-batch-export-donors.php
Per #2170, there is a filter for columns, but not for column data.
I have been working adding custom data to the CSV export; this allows that to happen.
One line change that adds `apply_filters` to the set_donor_data() method in the `Give_Batch_Donors_Export` class.
(CC: @topher1kenobe & @tannerm )
=> Filter to the set_donor_data() method

includes/misc-functions.php
Currently, `give_update_meta` has string param type so it gives us an incorrect param type when we pass an array into it. 
- Pass mixed param instead of the string.
=> Fix php-doc for give_update_meta

includes/admin/reports/class-forms-report.php
This PR will fix multiple form tag on form detail report page which is not as W3C standard as well as it cause alignment issue in the top navigation.
1) Issue: multiple form tag issue:
2) Alignment issue: 
3) Fix: Alignment issue fixed after pre
venting main form tag:
- Prevent main form tag to show in Form detail report page.
=> Fix multiple form tag on form detail report page

includes/admin/admin-actions.php, includes/admin/donors/donor-actions.php
This PR will fix #2181 
- Manually Tested.
- Show success message on Donor update information.
=> Fix Display Notice on saving Donor Info #2181

includes/formatting.php
Some currencies use a comma instead of a dot as the decimal symbol in their number of the amount, therefore it was not possible for us to sanitize the amount currency wise. (#2258 )
This PR solve this issue and allow us to pass currency.
the old way of use: 
```
give_sanitize_amount( 'amount', 'decimal_points', 'trim_zero' );
```
after this PR: 
```
give_sanitize_amount( 'amount', array(
array(  'number_decimals'=>2, 'trim_zeros' => false, 'currency'=>'EUR' )
) );
```
same for `give_maybe_sanitize_amount()` function.
Please check from your end and let me know if there are any changes needed.
- Tested it manually 
Bug fix (non-breaking change which fixes an issue) 
\cc @DevinWalker @ravinderk
=> give_sanitize_amount and give_maybe_sanitize_amount allows to sanitize amount based on currency's setting 

includes/admin/class-blank-slate.php
PR for issues #2263 
Test the layout with the donation in it and also after deleting all the donation within it and with the Add-on as well 
=> Issues 2263

includes/payments/class-payment-stats.php
This PR will close #2314 
Added new filter to modify the give donations earnings.
@ravinderk could you please check,
=> Added filter when getting the earnings.

includes/formatting.php, includes/forms/template.php
This PR will fix #2197
Donation amount was not showing/sanitizing in form based currency format.
@ravinderk please check and do not merge, I will add more commit related to this if I get while working.
Manually.
=> Passing form's currency while format the amount.

includes/admin/donors/donors.php, includes/deprecated/deprecated-functions.php, includes/payments/functions.php, templates/shortcode-receipt.php, tests/unit-tests/tests-payments.php
This PR will fix #2317 
Filtering the amount when getting payment amount through `give_payment_amount`.
- RanUnit test
- By applying filter manually.
=> Add filter when getting payment amount through give_payment_amount() function.

templates/shortcode-goal.php
1. Filter goal and income args
2. Don't output currency decimals by default - Resolves https://github.com/WordImpress/Give/issues/2372
- Manually
- UX update
- New filters
=> Goals without decimals and added filters: issue/2372

tests/unit-tests/tests-misc-functions.php
The data provider for currencies had a todo note about adding more currencies. This pull request provides all the available currencies from `give_get_currencies()`
For speed, I filtered the tests down to just test_give_get_currency_name. All tests passing at present time.
- [*] My code is tested.
- [*] My code follows the WordPress code style.
- [*] My code follows has proper inline documentation.
=> Complete the available currencies for the test data providers

includes/admin/admin-pages.php
=> Add Page Status #2353

assets/scss/admin/forms.scss
Previous to this PR you could remove the first row of a multi-level form.  This would cause the PHP notices within #2451 
Admins should use "Set" configuration if they don't want levels. You shouldn't be able to remove _all_ rows within the repeater. This hides the remove row button with CSS for just the _first_ level. 
Resolves #2451
- Manually
- UX bug fix
=> Hide first multi-level repeatable row's delete button

includes/admin/emails/class-new-donor-register-email.php
**Fix issue:** Email is missing default content in 2.0+
=> #2581  [Give 2.0] WordPress Default Admin Email Goes Blank

includes/admin/emails/class-email-notifications.php
fix #2606 
- Manually tested Global and Per-Form test Email
- Remove `give_action` from query args after sent test email
=> Fix: Issue #2606

includes/login-register.php, includes/shortcodes.php, templates/shortcode-login.php
Resolved issue where the `login-redirect` attribute was never being set. We're using the `/donation-history/` page as the default redirect when this attr is absent. If it's set then the shortcode now respects that. Resolves https://github.com/WordImpress/Give/issues/2622
- Manually
- Bug fix
=> Properly allow `login-redirect` attribute to override variable #2622

includes/admin/tools/views/html-admin-page-system-info.php, includes/class-give-db-logs.php, includes/donors/class-give-donors-query.php, includes/payments/class-payments-query.php, tests/unit-tests/tests-donor-query.php
This PR fixes #2677 #2533 
- In Windows OS integer number should not exceed the limits of PHP_INT_MAX 
- We can face this issue in the Windows/Apache local environment only. because most of the servers are running on the Linux OS.
- I guess none of the donation websites would have 999999999999999 number of donations/donors, so decreasing the value to 99999999999 should not affect anything. 
Manually.
=> Issue/2677|2533 - MySQL error after updating on Email Preview

includes/payments/functions.php
Removes price level displaying when the level text is blank in various places in wp-admin and the frontend. - Resolves #2700 
- UX
=> Issue/2700 - Don't use fallback in give_get_price_option_name() to simplify UX

includes/class-give-db-donor-meta.php, includes/class-give-db-form-meta.php, includes/class-give-db-logs-meta.php, includes/class-give-db-meta.php, includes/class-give-db-payment-meta.php, includes/class-give-db.php
This PR resolves #2692 
I've tested this issue as per the below steps which ensures that custom meta tables are created:
1. Install Give 1.8.19
2. Create couple of donations
3. Install Give 2.0 and run upgrade routine
4. Donor missing scenario generated
5. Install Give 2.0.1 - Run Upgrade Routine - Everything Fixed.
**Video Link:** https://drive.google.com/open?id=1MKqR7JO0R51yctZ-ttpl9_SCqkUuzkbo
=> Issue #2692 - Fix Table Creation Issue when utf8mb4

includes/process-donation.php
=> Remove variable that is globally accessible #2663

includes/install.php
This PR is related to issue on fresh installs with release 2.0.1
I've tested this manually.
1. Activated Give Plugin with this branch containing fix.
2. Meta Tables are created as expected.
3. No Upgrade notice displayed on fresh install.
4. Display Upgrade notice when tested on existing install with Give 1.8.19
=> Fix - Displays Upgrade Notice on Fresh Installs

includes/admin/shortcodes/abstract-shortcode-generator.php, includes/ajax-functions.php, includes/misc-functions.php
Problem was we were using `get_posts()` which doesn't working in 2.0+ because we moved the form meta to it's own table.
Resolves #2728 
- Manually
=> Issue/2728 - Resolve query issue with Donation Form Goal option in shortcode builder

assets/js/frontend/give.js
This PR resolves #2091 
I've tested this PR in the following browser, after completing the donation and then clicking the back button of the browser.
- Chrome
- Firefox
- Safari
**Chrome**
**Firefox**
**Safari**
=> Issue #2091 - Reset Form Fields on clicking browser back button

includes/payments/functions.php
Related #2653 
If the donation option is "set" and a "Custom Amount Text" is set then it will only display in front-end(current behaviour) and will not be appended in the receipt and email.
Tested manually
=> fix(payments): Remove custom amount label from set donation {donation} tag #2653

includes/admin/class-blank-slate.php
Strings were missing in translations. Text domain for three strings were set to 'wbpr' in stead of 'give'.
=> Wrong text domain

assets/js/frontend/give-donations.js
Swapped out deprecated jquery method for `.on()`
Resolves #2818
=> fix(jquery-deprecated): remove .load() use .on('load') #2818

includes/forms/template.php
This PR is to support https://github.com/WordImpress/Give-Recurring-Donations/issues/280
I've tested this PR manually with https://github.com/WordImpress/Give-Recurring-Donations/issues/280
@ravinderk Let me know, if i need to change the name of the action hooks
=> feat(form): add action hooks before & after final donation total

assets/src/css/admin/settings.scss, assets/src/js/admin/admin-settings.js, includes/admin/class-admin-settings.php, includes/admin/class-give-settings.php, includes/admin/settings/class-settings-gateways.php, includes/forms/template.php
Closes #2429 
Under **_Donation > Settings > Payment Gateways > Enabled Gateways_**, input fields are added to set custom checkout labels on the front end.
=> feat(admin): Not able to tell differences between payment gateways due to same labels #2429

give.php
PR to fix #2784 
Change the hook that used to load the text domain to make it Compatibility with Other Add-on ( Polylang )
Manually Tested See the video for more information 
Video Link: https://screencast-o-matic.com/watch/cFn0X2oWeM
=> fix(compat): Change hook that load give text domain #2784

assets/src/css/admin/goals.scss, includes/admin/forms/dashboard-columns.php, includes/forms/functions.php
Closes #2338
When a goal is achieved, the goal column in the forms listing page will display 'Goal achieved'
Goal column displays a message 'Goal achieved' if the goal is achieved. 
To make this work in the best possible way, I have slightly modified the built in function `give_goal_progress_stats( $form )` in the following way:
Earlier the above function only accepted 1 argument, which is the form ID and it returned goal stats with **currency symbols**, which made it difficult to perform mathematical operations on the return value.. Now the modification takes another argument called `$raw_values` which has a default value set to `false`. If set to `true`, the function will **also** return stats without currency symbols.
Here is the …
=> feat(admin-form): Add label for donation goal in dashboard #2338

includes/admin/forms/dashboard-columns.php, includes/forms/functions.php
Closes #2835 
Percentage values under the goal column on the admin page showed incorrect values. This was because percentage wasn't calculated in the first place.
=> bug(downloads): Percentage value is not computed correctly in the admin page goal column #2835

blocks/components/blank-slate/index.js, blocks/components/blank-slate/style.scss, blocks/donation-form/edit/block.js, blocks/donation-form/edit/inspector.js
- props.focus replaced with props.isSelected to be in sync with new Gutenberg change
- Various InspectorControls are moved from **wp.blocks.InspectorControls** to **wp.components** code updated to reflect the same
- Wrapper div with props.className added to target style for GiveBlock(s)
- Gutenberg 2.2.0 conflicting image styling causing BlankSlate component Logo/Icon to display 100% width fixed
Manually
N/A
Fixes
=> Fix deprecated & styling

includes/admin/dashboard-widgets.php
Resolved incorrect stat for "This Year". 
Closes #2847 
- Manually
- Bug fix
=> fix(dashboard-widget): incorrect stat for this year #2847

includes/admin/tools/views/html-admin-page-exports.php
Closes #2864 
If the exclude from export list is empty, then the message and empty container will be hidden.
=> fix(bug): Only show message about options if options are available #2864

assets/src/js/admin/admin-settings.js
Fixes https://github.com/WordImpress/Give/issues/2429#issuecomment-370315441
The previous code of default gateway select dropdown wasn't deleted which caused the JS error.
=> bug(admin-settings): Fix JS error due to redundant code #2429

includes/class-give-cli-commands.php
Closes #2845 
Added 1 WP-CLI command with 2 configurations:
`wp give test-mode --enabled`
`wp give test-mode --disabled`
Enabling test mode will set:
1. **Test Mode** to `enabled`
2. **Enabled Gateways** to `Test Donation`
3. **Default Gateway** to `Test Donation`
=> feat(cli): add command to activate test environment for donation #2845

includes/admin/shortcodes/abstract-shortcode-generator.php
Closes #2728 
Fixed the 'No forms found' error caused by using get_posts()
=> fix(admin-shortcode): Shortcode generator issue with inserting Donation Form goal #2728

composer.json, composer.lock
Closes #2896 
`composer.lock` is being version controlled from this point on so that all developers work on the exact same versions of dependencies.
Also, version of WPCS is set to `"*"`, so that the latest version is downloaded.
=> build(composer): commit composer.lock file #2896

includes/admin/admin-actions.php, includes/admin/tools/import/class-give-import-donations.php
PR to fix #2879 
**Notes: Not able to regenerate the issues that are mention in the description of the issue but fix another two issues that are being mentioned in https://github.com/WordImpress/Give/issues/2879#issuecomment-371649510**
Mannualy by uploading Donation from CSV and then check all the donation and the donation form that they are created properly or not.
Please see the video, To check on how I have tested this out.
Video Link: https://screencast-o-matic.com/watch/cFeQixDDpF
=> fix(admin-tool): Disable cache at the time of Importing Donation from CSV #2879

webpack.config.js
Closes #2907 
This fix bundles SVG images to only the `dist/images` folder.
=> build(webpack): Bundle SVG files inside correct folder #2907

includes/payments/class-give-payment.php
This PR is related to https://github.com/WordImpress/Give-Recurring-Donations/issues/429
I have noticed that on saving payment donation amount for the donor is incremented. But, donation count ( _purchase count_ ) is not incremented which affects unit tests. So, I have added an increment of donation count for a donor to make it work properly and test it with unit tests as well as by performing actual donation.
=> test(recurring): update donation count with amount for donor

includes/import-functions.php
PR to fix #2921 
This issue was coming because `_give_payment_customer_id ` key is being replaced with `_give_payment_donor_id` and that change was not being made in this functions
CSV Link: https://docs.google.com/spreadsheets/d/18AFqxipUgvkeDJ0uozzRCgJqKxH0WffVR7CzaUFpDmA/edit?usp=sharing
Video Link: https://screencast-o-matic.com/watch/cFe2iOD3O9
=> fix(admin-tool): fix duplicate issues when importing donation from CSV #2921

includes/admin/tools/import/class-give-import-donations.php
PR to fix #2163 
Tested by importing the CSV with passing underscore in meta column key and then check that is not being auto map to **Import as Meta**
Video Link: https://screencast-o-matic.com/watch/cFeIqnDrE4
=> fix(admin-tool): Fix auto mapping of import as meta column #2163

includes/process-donation.php
Closes #2862 
Created a new function `give_donation_form_validate_name_fields()` which will check if the _First_ and _Last_ name fields contain email address or not. 
This has been tested manually in _logged-in_ and _guest_ mode.
https://www.useloom.com/share/a4f23a91aba74c0d83f2f8ccc85fec41
=> feat(form): disallow email address as first name #2862

templates/shortcode-goal.php
Closes #2638 
Donation forms which were over-funded showed 100% as the maximum progress value. Now it shows the actual value.
If the user wants to limit the progress value for 100%, then they have to use the following filter:
```php
function limit_donation_exceed_to_100( $progress, $form_id, $form ) {
$goal_format         = give_get_meta( $form_id, '_give_goal_format', true );
$income              = $form->get_earnings();
$goal                = $form->goal;
$donations_goal      = give_get_meta( $form_id, '_give_number_of_donation_goal', true );
$donations_completed = give_get_form_sales_stats( $form_id );
return 'donation' === $goal_format ? (
$donations_completed >= $donations_goal ? 100 : $progress
) : (
$income >= $goal ? 100 : $progress
);
};
add_filter( …
```
=> fix(form): display actual goal progress even after goal is met #2638

includes/forms/template.php
Closes #2800 
If a goal-based form achieves its goal and closes it, then the Thank you message will be shown along with the Form title.
This has been tested with the shortcode of a form as well as on the donation form's singular page.
=> fix(shortcode): display form title even if form is closed #2800

includes/admin/class-addon-activation-banner.php, includes/admin/plugins.php
=> refactor(activation-banner): show activated add-on in tab view.

includes/admin/emails/class-email-setting-field.php
PR to fix #2657 
Manually tested by Making Donation
=> feat(admin-email): add Email Recipients section to donor emails 2657

includes/admin/plugins.php
PR to fix #2953 
Manually tested by adding multiple Give and another third party Add 
=> fix(admin-plugins): Add check for author name #2953

includes/admin/class-addon-activation-banner.php
Closes #2962 
Figured out the issue with the build process
**Cause**:
`replace()` is a string function, the reason why the console says `replace()` is not a function is because it is being performed on an object.
Check this line no: [131](https://github.com/WordImpress/Give/blob/release/2.1/includes/admin/class-addon-activation-banner.php#L131) and line [136](https://github.com/WordImpress/Give/blob/release/2.1/includes/admin/class-addon-activation-banner.php#L136)
I don't think we should be translating it using `__()` because gettext won't be able to interpret what is inside the variable that is being passed.
Tested this manually
=> build: resolve issue when running "npm run build" #2962

includes/class-give-donate-form.php
PR to fix #2930 
Manually test by disabling the JS 
=> fix(donation): update minimum amount for amount method #2930

blocks/donation-form-grid/class-give-donation-form-grid-block.php, includes/api/class-give-api-v2.php
Closes #2960 
Corrected the name of the function from `give_donation_grid_shortcode` to `give_form_grid_shortcode`.
Manually tested by adding **Give Donation Form Grid** block.
=> fix(gutenberg): ensure Give Form Grid block can be inserted #2960

includes/admin/admin-filters.php
PR to fix #2999 
Manually tested by importing Core Setting on fresh instances 
=> fix(admin-tool): getting PHP notices when importing Give core Settings #2999

assets/src/js/frontend/give-misc.js
Closes #3019 
Checks if the variable is undefined before resetting the form
This has been tested manually.
=> fix(form): getting js error when get back to page with form grid shortcode #3019

assets/src/css/admin/goals.scss, includes/admin/forms/class-metabox-form-data.php, includes/admin/forms/dashboard-columns.php, includes/admin/upgrades/upgrade-functions.php, includes/class-give-donate-form.php, includes/forms/functions.php, includes/payments/class-give-payment.php, includes/shortcodes.php, tests/unit-tests/tests-donate-form-class.php
This PR resolves #2250 and resolves #3027
I've tested this PR with following scenarios:
- updated form meta to `closed` when form goal is achieved.
- updated form meta to `open` when form goal is updated with which goal is not achieved.
- tested form grid shortcode with `open` and `closed` status and without status
=> feat(form): allow forms to be queried based on close status #2250

includes/payments/class-payments-query.php
Nest loop breaks parent loop by set unexpected post id. This is known issue in WP Core (https://core.trac.wordpress.org/ticket/18408).
The Form Grid shortcode breaks because Currency Switcher was using `Give_Payment_Query` which internally uses `WP_Query`. Since we have a lot of filters and action in the core, we cannot prevent users to use multiple loops but we can prevent breaking their parent loop if they are using `Give_Payment_Query`.
For Ref:
https://github.com/WordImpress/Give-Currency-Switcher/issues/100
Manually by reverting this https://github.com/WordImpress/Give-Currency-Switcher/issues/100 fix.
=> fix(donations): prevent nested loop from producing unexpected results

includes/admin/upgrades/views/upgrades.php, includes/class-give-translation.php
This PR fix #3013 
It needs @mathetos reply on https://github.com/WordImpress/Give/issues/3013#issuecomment-381117062 to complete this PR
- Manually
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> fix(translation): improved error message for better translation.

includes/admin/admin-pages.php
PR to fix #3015 
Manual tested 
=> refactor(admin-tool): reorder Admin tool tabs #3015

includes/admin/forms/class-metabox-form-data.php
This PR resolves #2963 
I've tested that the field title is updated to `Min/Max. Amount`.
**Before**
**After**
=> fix(admin-form): max / min slider appears broken and field title needs updating #2963

includes/admin/tools/export/class-give-export-donations.php, includes/admin/tools/export/give-export-donations-exporter.php
PR to fix #3043 
Manually tested by enabling and disabling the **Sequential Ordering** and then exporting the donation 
=> fix(admin-tool): export donation history should have donation number #3043

includes/admin/tools/views/html-admin-page-system-info.php
This PR fix #2998 
Fixed old SSL check API instead of integrating new API, please review the changes and let me know.
Note: `wp_remote_get` and `wp_remote_post` both fn returns error in their response. 
- Manually.
=> fix(admin-tool): PHP notices on system info page

assets/src/js/admin/admin-forms.js
This PR fix #3068 
- Tested it by saving different-different Goal Format.
- Enabling/Disabling Goal for the donation form.
=> fix(admin-form): hide donor option if goal is disabled.

includes/install.php
This PR resolves #3079 
I've tested this PR with the fresh install and confirmed the default settings by checking the DB.
=> fix(admin-settings): load default company field settings on fresh install #3079

includes/admin/abstract-admin-settings-page.php
- Fixing usage of `in_array` to use strict comparison with true for third arg.
- Wrapped output in `wp_kses_post` to sanitize HTML being delivered to user.
- Fixed comparison using (==) and changed to strict comparison (===).
```
FILE: ./content/plugins/give/includes/admin/abstract-admin-settings-page.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AND 2 WARNINGS AFFECTING 5 LINES
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | ERROR   | Class file names should be based on the class name with "class-" prepended. …
```
=> Fixing phpcs errors and warnings for abstract admin settings page.

includes/admin/tools/data/class-give-tools-delete-import-donors.php
Verifying the key within `$_REQUEST` exists before proceeding to use it. Adding sanitizing and unslashing to the variable.
** Still needs to have a nonce for the form submission and will be following up with another PR later for that.
```
FILE: ./content/plugins/give/includes/admin/tools/data/class-give-tools-delete-import-donors.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 4 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | ERROR   | Class file names should be based on …
```
=> Fixing verification and sanitization in tools-delete-import-donors

includes/admin/tools/data/class-give-tools-delete-test-donors.php
Adding escaping to output for `wp_die()`.
```
FILE: ./content/plugins/give/includes/admin/tools/data/class-give-tools-delete-test-donors.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 5 ERRORS AND 5 WARNINGS AFFECTING 9 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | ERROR   | [ ] Class file names should be based on the class name with "class-" prepended. Expected class-give-tools-delete-donors.php, but found
|         |     class-give-tools-delete-test-donors.php.
173 | WARNING | [ ] Detected usage of …
```
=> Fixing escaping in tools-delete-test-donors functionality.

includes/admin/tools/export/class-core-settings-export.php, includes/formatting.php
Adding escaping to output for `wp_die()`.
Adding `wp_unslash` to `give_clean` function.
```
FILE: ./content/plugins/give/includes/admin/tools/export/class-core-settings-export.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 7 ERRORS AND 2 WARNINGS AFFECTING 3 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | ERROR   | Class file names should be based on the class name with "class-" prepended. Expected class-give-core-settings-export.php, but found class-core-settings-export.php.
57 | WARNING | Detected access of …
```
=> Fixing escaping and adding wp_unslash to the give_clean function

includes/admin/add-ons.php
- Wrapped output in `wp_kses_post()` and `esc_html` where appropriate to sanitize HTML being delivered to user.
- Changing condition checks to be yoda conditionals
- Adding functionality to run `vip_safe_wp_remote_get()` if the function exists.
```
FILE: ./content/plugins/give/includes/admin/add-ons.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 6 ERRORS AND 1 WARNING AFFECTING 6 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
28 | ERROR   | [ ] All output should be run through an escaping function (see the Security sections in …
```
=> Phpcs add-ons.php

includes/admin/class-blank-slate.php
Fixing placeholder PHPCS errors and warnings for translators comments.
```
FILE: ./content/plugins/give/includes/admin/class-blank-slate.php
FOUND 5 ERRORS AND 3 WARNINGS AFFECTING 5 LINES
1 | ERROR   | [ ] Class file names should be based on the class name with "class-" prepended. Expected class-give-blank-slate.php, but found class-blank-slate.php.
153 | ERROR   | [x] No space before closing parenthesis is prohibited
263 | WARNING | [ ] A gettext call containing placeholders was found, but was not accompanied by a "translators:" comment on the line above to clarify the meaning of the …
```
=> PHPCS: Class blank slate fixes.

includes/admin/admin-pages.php
Fixing PHPCS warnings and errors for tabs vs spaces
Verifying all usages of the $_GET superglobal.
```
FILE: ./content/plugins/give/includes/admin/admin-pages.php
---------------------------------------------------------------------------------------------------
FOUND 28 ERRORS AND 26 WARNINGS AFFECTING 26 LINES
---------------------------------------------------------------------------------------------------
125 | WARNING | [ ] Detected access of super global var $_GET, probably needs manual inspection.
125 | WARNING | [ ] Processing form data without nonce verification.
125 | WARNING | [ ] Silencing errors is discouraged
125 | WARNING | [ ] Detected access of super global var $_GET, probably needs manual inspection.
125 | WARNING | [ ] Processing form data without nonce verification. …
```
=> PHPCS: Fixing PHPCS warnings and errors, tabs vs spaces. 

includes/admin/abstract-admin-settings-page.php, includes/admin/admin-filters.php
Fixing strict comparison (`!==`).
Adding spacing for PHPCS.
Adding newline at end of file.
Spot checking all access to $_POST superglobal.
Verifying existence of key in $_POST superglobal before proceeding.
```
FILE: ./content/plugins/give/includes/admin/admin-filters.php
FOUND 22 ERRORS AND 6 WARNINGS AFFECTING 15 LINES
30 | ERROR   | [ ] Function name "__give_sanitize_number_decimals_setting_field" is invalid; only PHP magic methods should be prefixed with a double underscore
34 | WARNING | [ ] Detected access of super global var $_POST, probably needs manual inspection.
34 | ERROR …
```
=> PHPCS: fixes for admin filters

assets/src/js/admin/admin-scripts.js, includes/class-give-scripts.php
Closes #3063 
Added GiveModal popup error while trying to edit donor name fields.
By trying to edit the donor fields.
=> fix(admin-donor): Add popup while trying to edit donor fields

assets/src/js/admin/admin-scripts.js
Closes #3123 
Replaced confirm popup with Give Modal popup.
Tested by deleting a donor note.
=> fix(admin-donation): delete donation note popup should open using modal api #3123

includes/admin/settings/class-settings-email.php
**This is not related to any issue.**
This PR adds a new filter to disable the save button on a specific tab & section of the admin settings page.
This is tested in the upcoming Recurring Donation [feature](https://github.com/WordImpress/Give-Recurring-Donations/issues/11).
=> refactor(admin-setting): Add filter to disable save button

includes/admin/tools/export/give-export-donations-exporter.php
Not connected to any issues 
Manually tested by exporting donation with PHP version 5.3 to PHP version 7.1
=> fix(admin-tools): export donation history generates js console error

includes/forms/template.php, tests/unit-tests/tests-templates.php
This PR fix #3122 
- Tested it by creating donations.
- Tested it by changing the donation form settings.
=> refactor(form): hide min/max field if custom amount is disabled. 

includes/class-give-gravatars.php
Fixing PHPCS escaping errors and warnings.
```
FILE: ./content/plugins/give/includes/class-give-gravatars.php
FOUND 15 ERRORS AFFECTING 11 LINES
249 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'apply_filters'.
|       | (WordPress.XSS.EscapeOutput.OutputNotEscaped)
251 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'apply_filters'.
|       | (WordPress.XSS.EscapeOutput.OutputNotEscaped)
294 | ERROR | All …
```
=> PHPCS: Fixing escaping errors and warnings.

includes/admin/tools/logs/class-update-logs-list-table.php
Fixing output escaping and alignment issues for PHPCS.
```
FILE: ./content/plugins/give/includes/admin/tools/logs/class-update-logs-list-table.php
FOUND 9 ERRORS AND 3 WARNINGS AFFECTING 10 LINES
1 | ERROR   | [ ] Class file names should be based on the class name with "class-" prepended. Expected class-give-update-log-table.php, but found
|         |     class-update-logs-list-table.php.
51 | ERROR   | [x] Expected 1 space between comma and "// Does this table support ajax?
|         |     "; 0 found
123 | ERROR   | [ ] All output should be run through an escaping function (see the …
```
=> PHPCS Adding escaping to output and fixing alignment.

includes/admin/tools/views/html-admin-page-data.php
Fixing output escaping and alignment issues for PHPCS.
```
FILE: ./content/plugins/give/includes/admin/tools/views/html-admin-page-data.php
FOUND 6 ERRORS AND 1 WARNING AFFECTING 6 LINES
63 | ERROR   | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'Give'.
70 | ERROR   | [ ] All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'Give'.
71 | WARNING | [x] Array double arrow not aligned correctly; expected 1 space(s) between "'name'" …
```
=> PHPCS: Fixing escaping for html-admin-page-data

assets/src/css/admin/forms.scss, includes/admin/forms/class-metabox-form-data.php, includes/admin/give-metabox-functions.php
Closes #3135 
Removed the range slider and implemented the new UI as per the requirements
=>  fix(admin-form): Make Range-slider more practical when setting the minimum amount #3135

includes/admin/tools/views/html-admin-page-exports.php
PR to fix #2964 
Mannaul tested by exporting the donor CSV by selecting the Donation Form and without selecting the Donation Form
=> fix(github): fix merging issues of Github

includes/admin/shortcodes/shortcode-give-donation-grid.php, includes/shortcodes.php, templates/shortcode-form-grid.php
PR to fix #3019 
**Notes: Update of documentation is remaining https://givewp.com/documentation/core/shortcodes/give_form_grid/**
Mannul tested checking the video to know more in how I have tested this issues 
Video Link: https://screencast-o-matic.com/watch/cFhV3Dbq8e
=> fix(shortcode): fix form gird redirect issues

includes/forms/template.php
This PR fix #3029
- Manually by changing the give currency setting.
=> fix(form): don't show formatted value for min and max amount.

assets/src/js/frontend/give-donations.js, includes/forms/template.php
This PR fix #3122
- Tested it by making the donation,
- Tested it with currency-switcher.
=> fix(form): validate the min/max amount only if custom amount enabled.

assets/src/js/frontend/give-donations.js
This PR fix #3122 
- Tested it with changing a thousand separators and decimal separator.
- Tested it with the custom amount and creating donations.
=> fix(form): do not unformat the min/max amount using JS functions.

assets/src/js/admin/admin-scripts.js, includes/admin/give-metabox-functions.php
This pr will resolve #3161 
Manually by edit admin form settings.
=> fix(admin-form): prevent js notice when edit price type setting field #3161

includes/class-give-donate-form.php
PR to fix #3159 
Manually  tested update the Give from Give Core 2.0.6 to 2.1
=> fix(donation): not able to make donation via custom amount #3159

assets/src/css/admin/settings.scss
Closes #3164 
Reduced the z-index of the sub navigation.
=> fix(admin-setting): prevent setting menu to appear on top of modal #3164

includes/admin/upgrades/class-give-updates.php, includes/admin/upgrades/views/db-upgrades-complete-metabox.php, includes/admin/upgrades/views/upgrades.php, includes/class-give-donate-form.php
This pr will fix #3163 
Tested by running DB upgrades on the small database.
=> fix(db-update): prevent blank screen when updating 2.0.6 to 2.1.0 #3163

includes/admin/upgrades/class-give-updates.php
This will fix #3155 
Manually by visiting WordPress updates listing page
=> fix(admin-plugins): update notice shouldn't display when actively updating add-ons #3155

includes/class-give-donate-form.php
This will fix #3159
This is a quick fix and not related to any issue.
Donation was not possible because of the following error:
`Error: This form has a maximum donation amount of $0`
By making a successful donation.
=> fix(donation): Fix get_maximum_price() function

includes/admin/plugins.php
Closes #2789 and related to https://github.com/WordImpress/Give/issues/2789#issuecomment-386689458
This feature was failing because the comparison was made between version `2.1.0` and `2.1`, where `2.1.0` was written in the `readme.txt` file and `2.1` was calculated programmatically.
```php
version_compare( '2.1.0', '2.1', '=' );
```
evaluates to `false` 
This has been fixed.
I tested this in the same way as it was done [here](https://github.com/WordImpress/Give/pull/3033)
=> feat(admin-plugins): display inline notification before updating #2789

includes/admin/class-addon-activation-banner.php, includes/admin/plugins.php
PR to fix #3153 
Manually tested by activating the Give Add-on one by one and multi add-on at once 
Video Link: https://screencast-o-matic.com/watch/cFhj6abtAP
=> fix(admin-plugins): display activation banner immediately upon activation refresh #3153

includes/api/class-give-api.php
This PR will resolve #3191
Manually by run stat API request for single form and earning type.
=> fix(give-api): Make Earnings and Donations Types Respect Daterange as intended #3191

includes/admin/shortcodes/abstract-shortcode-generator.php
Closes #3207 
Related #2729 
Fixes the plugin conflict between Give Core and Beaver Builder.
I have replaced `WP_Query` with `get_posts()` and set `suppress_filters` parameter to `true`. This way the Donation Form Goal shortcode also works.
By activating Give Core and Beaver Builder side by side.
https://www.useloom.com/share/8b71fb474e894298b9a6afc67f49bd56
=> fix(compat): beaver builder conflict preventing from seeing page builder element on backend. #3207

assets/src/js/frontend/give-ajax.js, includes/forms/template.php, includes/gateways/actions.php
This PR is created to support Stripe Elements issue https://github.com/WordImpress/Give-Stripe/issues/178
I've tested this PR with donation forms having CC fields created by Stripe Elements and Google/Apple Pay Buttons created by Payment Request API.
I've also tested it with 5 donation forms on a single page with 2 same donation forms to be used twice on the single page.
=> feat(form): ensure w3c validations for donation forms #3139

includes/admin/tools/export/class-batch-export-donors.php
PR to fix #3222 
Tested by manually exportin donor and donation in PHP version 5.3, 5.4 and 7.0
=> fix(admin-tool): getting PHP notices when exporting donor in lower PHP version #3222

includes/class-give-cli-commands.php
Closes #1390 
Added a new Give CLI command which pulls the latest code to the current branch of all the Give addons and Give Core. The remote `origin` is used.
By default:
- `wp give addon-update` will update all the addons including Give Core.
- To update only a single addon, the associative argument `name` should be used. For example:
`wp give addon-update --name="Give-Stripe"`
- To update all the addons except a selected few, the `exclude` associative argument should be used.
`wp give addon-update --exclude="Give-Stripe, Give-Recurring-Donations, Give-Gift-Aid"`
I have ran this command and updated a few repos which were not in sync with origin.
This is how it looks updating in a terminal (no audio):
[![asciicast](https://asciinema.org/a/wFpAL69IF69S2FegmXGOKRAXe.png)](https://asciinema. …
=> feat(cli): update add-ons from GitHub #1390

assets/src/js/frontend/give-donations.js
=> fix(donation): do not parse decimal separator value to integer.

includes/class-give-cli-commands.php
PR to fix PHP notices in lower PHP version 
Manually tested by running CLI command
<details>
[22-May-2018 05:48:53 UTC] PHP Parse error:  syntax error, unexpected '(' in /app/public/wp-content/plugins/Give/includes/class-give-cli-commands.php on line 1197
[22-May-2018 05:48:53 UTC] PHP Stack trace:
[22-May-2018 05:48:53 UTC] PHP   1. {main}() /usr/local/bin/wp:0
[22-May-2018 05:48:53 UTC] PHP   2. include() /usr/local/bin/wp:4
[22-May-2018 05:48:53 UTC] PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:8
[22-May-2018 05:48:53 UTC] PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/php/wp-cli.php:23
[22-May-2018 05:48:53 UTC] PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/bin/wp/php/bootstrap.php:75
[22-May-2018 05:48:53 UTC] PHP   6. …
=> fix(cli): update code to support lower PHP version

assets/src/js/admin/admin-scripts.js
Closes #3244 
Replace native confirm dialog with Give Modal JS
By re-sending receipt from within the payment details page.
=>  fix(admin-donation): reset email receipt donation button popup should open using modal api #3244

includes/process-donation.php
This PR resolves #3035 
I've fixed the issue with Latin characters so that it won't strict those users from donating their donations.
I've performed a successful donation with Chinese letters.
=> fix(donation): prevent WP users from being created if donation fails #3035

includes/admin/plugins.php, includes/admin/settings/class-settings-license.php
Closes #3254 
In this PR, it checks if at least 1 Give addon is active. If no Give addon is active, then the License page is removed.
By enabling/disabling Give addons.
=> fix(admin-setting): Disable license tab if not addon is active

assets/src/js/frontend/give-misc.js
This PR fix #3278 
- Tested it by creating dimiss notices and removing them.
- Tested it with https://github.com/WordImpress/Give-Currency-Switcher/issues/128 
=> fix(donation): dismiss button should work when rendering Give notice using the JS.

assets/src/css/admin/settings.scss
Closes #3274 
Fixes overlapping of Give footer on WooCommerce Storefront notice.
By reloading the page after running `npm run dev`
=> fix(admin-form): Give's bottom text overlapping on the Give's banner when storefront theme is activated. #3274

includes/admin/shortcodes/shortcode-give-totals.php
PR to fix #3060 
Tested by entering the shortcode by Goal amount 
=> fix(admin-shortcode): Total goal attribute should be required field for [give_totals] #3060

assets/src/css/plugins/_settings.scss, includes/admin/shortcodes/admin-shortcodes.js, includes/admin/shortcodes/class-shortcode-button.php, includes/class-give-scripts.php, webpack.config.js
Closes #3282 
This PR replaces the native alert dialog with GiveModalWarning.
By adding a form in a shortcode without choosing a form.
=> fix(shortcode): select donation form alert must be open using modal api #3244 #3282 #3286

includes/admin/forms/dashboard-columns.php
Fix #3249 
- By saving the donation without custom amount enabled.
- By tweaking the give currency setting.
- By creating donation on the front-end.
=> fix(admin-form): set donation amount as minimum amount if it is less then minimum amount.

give.php, includes/actions.php, includes/class-give-readme-parser.php
This pr will resolve #3217
I tested this pr by updating multiple licensed Give addon.
Testing video: https://drive.google.com/file/d/1Jrdy9wQdiQirzid0CncdGmO9RyiSoECL/view?
usp=sharing
Snippet link: https://givewp.slack.com/files/U1DDJMUTV/FAWLZ3GSD/give_pull_3268.php
=> fix(install): verify addon Give dependency before update #3217

assets/src/js/admin/admin-scripts.js
Closes #3296 
This PR disables/enables the radio button when you toggle the checkboxes.
Manually tested by enabling/disabling the checkboxes.
=> fix(admin-setting): immediately disable default column radio button if payment gateway unchecked #3296

assets/src/css/frontend/modal.scss, includes/forms/template.php, includes/shortcodes.php
Closes #3293 
This PR will only display the payment select fields only if there are more than 1 gateways enabled.
I have tested this on the Form Grid page and individual Form page and tried all Display options.
=> fix(form-grid): resolve error where Payment Method shows with only one gateway enabled. #3293

assets/src/js/frontend/give-misc.js
Closes #3301 #3308 
This PR hides the Donation Amount label when the modal popup is closed if the form's display option is set to Button.
=> fix(form): hide donation amount label on modal close

includes/actions.php, includes/process-donation.php, includes/shortcodes.php
PR to fix #3291 
Have tested by adding two donation form of the same type but the language is diff and runs on the same page with two diff language s
Video Link: https://screencast-o-matic.com/watch/cF1V1QbLWa
=> fix(shortcode): give_totals should output the correct donation total #3291

includes/admin/shortcodes/admin-shortcodes.js
PR to fix #3282 https://github.com/WordImpress/Give/issues/3060#issuecomment-394301653
=> fix(shortcode): select donation form alert must be open using modal api #3282 #3060

assets/src/css/admin/settings.scss, includes/admin/upgrades/views/upgrades.php
Closes #3328 
This PR fixes the admin footer on the Give Update page.
By refreshing page after running `npm run dev`
=> style(admin): admin footer notice overlapping on update page #3328

includes/admin/upgrades/upgrade-functions.php, includes/class-give-roles.php
Closes #3261 
This PR runs an upgrade script to add the user capability `view_give_payments` to the user role `give_manager`.
I tested this by running the upgrader.
=> fix(user-role): Give manager should be able to view donation details #3261

includes/admin/tools/export/give-export-donations-exporter.php
PR to fix https://github.com/WordImpress/Give-Tributes/issues/209
Tested by exporting donation with Tribute Add-on Activated 
=> fix(admin-tools): fix PHP notices when export donation

assets/src/css/frontend/forms.scss
Closes #3340 
Added a Load More button with an animatable loader inside the button.
Tested using the following snippet
```html
<button class="give-button-with-loader">
<span class="give-btl-spinner"></span>
<span class="give-button-inner-text">BUTTON TEXT</span>
</button>
```
```js
$(document).ready( function() {
$( '.give-button-with-loader' ).on( 'click', function() {
$( this ).addClass( 'give-active' );
});
});
```
https://www.useloom.com/share/6fc7c8f208f0464c9f1b3fc1cdde4ed7
=> feat(donor-wall): add Load More button

includes/admin/settings/class-settings-license.php
=> fix(admin-setting): License tab is not showing when addon is network enabled #3349

includes/admin/tools/export/give-export-donations-functions.php, includes/ajax-functions.php
PR to fix #3303 
Tested by exporting donation by selecting the cat and tag and then exporting the donation 
Video Link: https://screencast-o-matic.com/watch/cF1l1eFfAa
=> fix(admin-tool): All Forms dropdown on the Donation Export only uses first ten forms #3303

includes/admin/plugins.php
PR to fix #2278 
Tested in multisite and normal sites 
=> fix(admin-plugins): add Give menu in plugin menu section for multi sites

includes/forms/template.php, includes/gateways/offline-donations.php
PR to fix #2937 
Tested using the shortcode in the offline donation instruction 
a. `give_the_term_content`: filter form terms content
b. `give_the_offline_instructions_content`: filter form offline donation instruction
Video Link: https://screencast-o-matic.com/watch/cF1I1xFh9i
=> fix(form): Add shortcode support to Offline Donations Instructions output #2937

includes/admin/shortcodes/shortcode-give-receipt.php
This pr will resolve #3361 
**Note:**
Company name field can be enabled only for specific form, show we cannot show & hide conditionally from shortcode builder that why I set it to display by default.
=> feat(shortcode): Add Company attribute to give_receipt shortcode #3361

includes/forms/template.php
Closes #3358 
This PR fixes the `create an account` field. It makes it full row if only registration is enabled.
By selecting `registration` from `registration` options in a donation form.
=> fix(form): show "Create an account" in full row if only registration enabled #3358

assets/src/css/frontend/forms.scss
Closes #3215 
This PR hides the multilevel dropdown which is displayed above the button when the display option is set to `button`
Tested as per the tasks laid out in the issue.
=> fix(form): Make dropdown display inside the modal with Button Mode #3215

assets/src/css/frontend/forms.scss, includes/class-notices.php
Closes #3006 
This PR fixes the overlapping of modal over front-end error notices when the form display option is set to `modal` 
CC: @samsmith89 
1. Payment Gateway: Authorize.net CC
2. CC number: `4000 0000 0000 0002`
3. CVC number: `901`
4. Form display options: `modal` and `button`
The above settings will generate a transaction failure which will throw a front-end error notice.
https://www.useloom.com/share/e75c465bcb564ce59114100df1d7c9c9
=> fix(donation): Modal and Button display modes improperly showing payment errors #3006

includes/forms/template.php
This PR is related to the https://github.com/WordImpress/Give-Snippet-Library/issues/72
When changing particular form's currency using 'give_currency' filter, currency symbol of the level text wasn't changing according to the changed currency, to fix it we have to pass the form's currency when filtering the currency amount.
- Tested it by radio, dropdown & button view.
- Tested it with and without 'give_currency' filter.
=> fix(donation-forms): format the level text according to the form's currency.

assets/src/js/admin/admin-export.js, assets/src/js/admin/admin-forms.js, assets/src/js/admin/admin-importer.js, assets/src/js/admin/admin-scripts.js, assets/src/js/admin/admin-settings.js, assets/src/js/admin/admin-widgets.js, includes/admin/shortcodes/admin-shortcodes.js
Closes #3353 
Fixes plugin incompatibility with BeTheme's Muffin Builder. The issue was caused by the usage of `jQuery.noConflict()` which was unnecessarily used in Give plugin since we are already using IIFE pattern in many of Give's JS files and also scoping `$` within the function using the following methods:
```JS
jQuery(document).ready( function( $ ) {
});
```
**OR**
```JS
jQuery( function( $ ) {
});
```
By using Muffin Builder and checking the console for any errors.
Also tested Give Shortcode button, Give settings and Form Meta settings.
https://www.useloom.com/share/6c6185d5a7034315acbea25c4747a854
=> compat(muffin-builder): ensure compatibility with BeTheme's MuffinBuilder #3353

includes/process-donation.php
This PR fix #3401 
- Tested it by changing the currency through `give_currency` filter.
=> fix(donation-form): use form's currency when processing the donation.

assets/src/css/frontend/theme-compatibility.scss
Fixes #3403  by customizing the following styling issues:
* `.give-amount-top` customized to fit on one line
* Floating labels aligned properly
Confirmed in-browser
Amount *BEFORE*
Amount *AFTER*
Floating Labels Properly lined up:
SImple CSS tweaks
=> fix(compat): Add Enfold compatibility 

includes/admin/emails/filters.php, includes/admin/shortcodes/class-shortcode-button.php
Closes #3422 
This PR removes the **Give Shortcode** button from the Email Settings Page.
By visiting any of the Email Notifications Settings pages.
**As you can see, the Give Shortcode button no longer exists.**
=> fix(emails): Remove Give shortcode button from Emails Settings Page

includes/admin/forms/class-metabox-form-data.php, includes/admin/settings/class-settings-display.php
PR to fix #3421 
Tested by making a donation with donor comment and without donor comment 
=> fix(donation): approved comment mail are getting send when making new donation from Give Core 2.2 #3421

includes/admin/shortcodes/shortcode-give-donation-grid.php, includes/shortcodes.php
Closes #3206 
This PR adds the attribute `exclude` to the `give_form_grid` shortcode. IDs of forms added to this attribute will be excluded from the query.
This has been tested on the form grid page by passing IDs of a few donation forms.
=> feat(shortcode): Add ability to NOT include forms to the form grid by id #3206

assets/src/js/admin/admin-scripts.js, includes/admin/emails/abstract-email-notification.php, includes/admin/emails/class-email-access-email.php, includes/admin/settings/class-settings-email.php, includes/admin/settings/class-settings-general.php, includes/emails/class-give-email-tags.php, includes/emails/functions.php, includes/gateways/offline-donations.php
Closes #3070 
This PR adds a feature to add **admin email** address and **offline mailing address** in a common place. This makes it easier to export Give Settings from one URL and import it to a different URL without the need to manually change the admin email address, site URL, site name and the offline mailing address. More details can be found in the video below. 
1. `{admin_email}`
2. `{offline_mailing_address}`
3. `{site_url}`
By sending and previewing emails.
https://www.useloom.com/share/d9756dd20a874037bd9a15c8fa17c78c
=> feat(admin-email): improve management of contact info in emails #3070

assets/src/css/admin/give-admin.scss, assets/src/css/admin/tooltip.scss, assets/src/js/admin/admin-scripts.js, assets/src/js/admin/admin.js, assets/src/js/admin/button.js, assets/src/js/admin/shortcode-button.js, includes/admin/forms/dashboard-columns.php, includes/admin/forms/metabox.php, includes/class-give-scripts.php, package-lock.json, package.json
Closes #2602 
This PR replaces the old shortcode display with a shortcode button which on clicking will copy the shortcode.
By clicking the shortcode button on both the donations listing page and on the form meta page.
=> feat(admin-form): copy form shortcode to clipboard via button #2602

assets/src/css/frontend/forms.scss, includes/forms/template.php
Closes #3423 
This issue was caused because the height of parent of the floated children was collapsed. This has been fixed by adding another parent container and adding the clearfix CSS fix.
By making a failed login attempt and trying to reenter login details.
https://www.useloom.com/share/1cdcb9214d7e450694c7f97126e7c04e
=> fix(donation): don't block login form after first failed login #3423

includes/admin/tools/data/class-give-tools-reset-stats.php
Closes #3145 
This PR adds a feature to delete the form categories and tags when an admin wants to delete and reset Give. 
By deleting and resetting Give, all the form categories and tags have been deleted from the database.
=> fix(admin-tool): deleting all data doesn't remove form categories or tags #3145

includes/admin/donors/donor-actions.php, includes/admin/donors/donors.php
PR to fix #3413 
Tested by updating Donor Company Name from Donor admin page
Video Link: https://screencast-o-matic.com/watch/cFiXXmFaWU
=> fix(admin-donation): ensure users can edit company name #3413

includes/admin/class-addon-activation-banner.php, includes/admin/plugins.php
Closes #3439 
This PR fixes [this](https://github.com/WordImpress/Give/issues/3439#issue-338819095) and [this](https://github.com/WordImpress/Give/issues/3439#issuecomment-404040449)
By forcing an activation error and triggering deactivation survey.
=> fix(admin-plugins): fix UI for plugin activation banner #3439

includes/admin/donors/donors.php
This PR resolves #3468 
I've tested this PR with a fresh install after ensuring that there are no title prefixes set and able to reproduce the error and then fixed it. Also, checked it after adding title prefixes to make sure it is working fine.
=> fix(admin-donor): gettting PHP notices when viewing donor details page from dashboard #3468

includes/emails/class-give-email-tags.php, includes/misc-functions.php
This PR will fix #2790 
- Manually tested
- Run Unit test
=> fix(admin-email): format address elements in the correct order

assets/src/css/frontend/modal.scss
Closes #3465 
Increased the max-width of the modal.
Tested with `Modal` and `Button` display options.
=> fix(form): 2.2 ensure name title prefix field doesn't wrap to new line on button display #3465

includes/admin/class-admin-settings.php, includes/admin/forms/class-metabox-form-data.php, includes/admin/give-metabox-functions.php
This PR resolves #3466 
I've tested this PR with empty and default values and newly added values of title prefixes. Also, checked that on focusing the chosen field shows default values.
=> fix(admin-form): 2.2 ensure name title prefixes can be removed once saved #3466

includes/actions.php, includes/class-give-license-handler.php
Resolves #1851 - removed `give_validate_license_when_site_migrated` which was causing CRON jobs on migrated sites to run excessively hammering our server.
=> refactor: removed give_validate_license_when_site_migrated 

assets/src/css/admin/forms.scss, includes/admin/class-admin-settings.php, includes/admin/forms/class-metabox-form-data.php, includes/admin/give-metabox-functions.php, includes/admin/settings/class-settings-display.php, includes/misc-functions.php
This PR will fix #3225
**Note: term label setting in admin and form is `textarea` but they look like text input because there row set to `1`.**
Adding HTML in global admin and form term label setting.
Admin setting
Form setting
Frontend
=> Need HTML for Terms&Cond Agreement Label for GDPR #3225

includes/currency-functions.php
This PR will fix #3367 
https://www.npmjs.com/package/currency-formatter
@DevinWalker and @ravinderk 
I have used npm package `currency-formatter` ( https://www.npmjs.com/package/currency-formatter ) JSON file for reference of each currency settings. Few of the currency which I not found in that JSON file was added through my research.
**Below are these currency:**
1) BYN:  Used same formating like BYR as its same. ( https://www.xe.com/currencyconverter/convert/?Amount=1&From=USD&To=BYN )
2) GGP: Its Currency symbol is Pound. So I have used same formatting of GBP
3) IMP: Its Currency symbol is Pound. So I have used same formatting of GBP
4) JEP: Its Currency symbol is Pound. So I have used same formatting of GBP
5) SSP: Its Currency symbol is Pound. So I have used same formatting of GBP …
=> fix(admin-setting): add all of the missing currencies from WooCommerce plugin

assets/src/js/admin/admin-scripts.js, includes/admin/payments/class-payments-table.php, includes/admin/payments/view-payment-details.php, includes/class-give-scripts.php, includes/misc-functions.php
Close #3502 
Added support for locale `en_GB`. By default the format will be `mm/dd/yy`. As more such requests come, we can conditionally support more requests.
By switching from locale `en_US` to `en_GB` and back.
=> fix(i18n): format dates to WordPress `date_format` #3502

includes/admin/payments/view-payment-details.php
This PR will fix #2985 
- Show email address as @ravinderk suggested on issue
- Manually tested
- Bug fix (non-breaking change which fixes an issue
=> fix(admin-donation): show proper email in donor detail metabox on donation detail page

includes/admin/emails/abstract-email-notification.php, includes/emails/class-give-email-tags.php
Close #3516 
This PR modifies a function to accept an additional parameter `is_admin` which if set to `true`, and if the Email notification's `has_recipient_field` is also set to `true`, then the email tag will only be displayed for that particular Email Notification.
By creating email tags using the old method and the new method:
```php
function give_register_custom_tag_1() {
give_add_email_tag(
'custom_tag_1',
__( 'Creating a tag using the old method', 'give-pdf-receipts' ),
'custom_tag_1_cb',
'donor'
);
}
add_action( 'give_add_email_tags', 'give_register_custom_tag_1' );
```
```php
function give_register_custom_tag_2() {
give_add_email_tag(
array(
'tag'      => 'custom_tag_2',
'desc'     => __( 'Creating a tag using the new method', 'give-pdf-receipts' ),
'func'     => …
```
=> fix(emails): extend emails functionality to support admin context #3516

includes/forms/widget.php
Closes #3245 
In this PR, I have passed form ID to the widget's  `give_before_forms_widget` and `give_after_forms_widget` action hooks.
Tested by using the action hooks.
=> fix(widget): pass widget arguments to action hook #3245

includes/admin/emails/abstract-email-notification.php
Related #3516 
This is a quick fix to unset email tags if the email context is set to `all`
Tested by observing the list of tags displayed in the Email Notifications.
=> fix(emails): Fix loop to unset email tags

assets/src/css/frontend/_grid.scss, assets/src/css/frontend/give-frontend.scss, includes/donors/class-give-donor-wall.php, templates/shortcode-donor-wall.php
Closes #3504 
In this PR, `flex` has been used as a fallback for Grid to support form grid on IE 11 browser.
Although IE does not fully support flex model layout, all the flex CSS properties I have used in this PR are supported by IE 11.
=> fix(shortcode): provide grid fallback styles for `[give_form_grid]` #3504

includes/admin/give-metabox-functions.php
This PR will resolve #3549 
This pr will fix the issue: https://github.com/WordImpress/Give-PDF-Receipts/issues/148
=> refactor(form-setting): render textarea setting field inside div instead of p #3549

includes/admin/reports/graphing.php
Add `give_reports_graph_additional_stats` action to specific form reports.
I added an action hook in my theme’s functions.php to insert another row into the table, and it worked exactly as expected.
- New feature: in that it’s a non-breaking change which adds functionality
- Bugfix: in that it adds feature parity between default reports view and specific form report view
=> add give_reports_graph_additional_stats to individual form stats

assets/src/js/admin/admin-scripts.js, includes/admin/tools/views/html-admin-page-data.php, includes/ajax-functions.php
Closes #1970
All form dropdowns will now fetch 30 forms by default. If the input field is kept empty then the select field will be reset to its original state.
By testing the select fields mentioned in the issue.
https://www.useloom.com/share/9cae9025da144c0dbea9942ccfb049eb
=> fix(admin-tools): all donation forms should be listed on Export screen #1970

assets/src/js/frontend/give-misc.js
PR to fix #2230 
Tested by enabling the **Floating Labels** and also disabling the **Floating Labels**
=> fix(form): exclude honeypot field from floating labels js #2230

includes/donors/class-give-donor-wall.php
Closes #3581 
As discussed over [here](https://github.com/WordImpress/Give/issues/3581#issuecomment-411297665), the default value of `only_comments` have been set to `false` 
By testing the shortcode `[give_donor_wall form_id="584"]` which displays the donor wall.
=> fix(shortcode): ensure the donors are showing on the donor wall when they submit a donation #3581

includes/admin/payments/actions.php
Closes #3606 
Fixes the date format by using WordPress' date format.
By cross-checking the donation listing and donation details page.
=> fix(admin-donation): ensure updating offline donations from pending to complete doesn't break date #3606

includes/admin/tools/data/class-give-tools-recount-form-stats.php, includes/admin/tools/data/class-give-tools-recount-income.php
PR to fix #3611 
Tested by **recalculating total donation income amount** from the drop down option 
Video Link: https://screencast-o-matic.com/watch/cFjFbRqbYL
=> fix(admin-tools): fix PHP notices when recalculating total donation income amount #3611

includes/admin/payments/view-payment-details.php
PR to fix #3617 
Video Link: https://screencast-o-matic.com/watch/cFjYhvqFAb
=> fix(donation): donation level not show correctly on donation detail page #3617

includes/admin/payments/actions.php, includes/payments/class-give-payment.php
This is a quick fix related to issue #3606 
This PR sets the correct format of data before inserting it into database.
Related: https://github.com/WordImpress/Give/issues/3606#issuecomment-417214966
By checking the debug log.
=> fix(admin-donation): Set correct date format for database

includes/forms/functions.php
Closes #3641 
This PR deletes the form meta when the form is deleted permanently from the trash.
Tested by moving forms to trash and then deleting from trash.
=> fix(admin-form): delete form meta when we delete the donation form #3641

includes/admin/tools/data/class-give-tools-reset-stats.php
Closes #3638 
This PR removes the redundant data from the following tables:
By making 3 donations, and deleting all data as explained in the video linked in the issue. I've cross-checked it with the data in the database.
=> fix(db): delete row from give meta table when donation are being deleted #3638

includes/admin/emails/class-new-donation-email.php, includes/admin/emails/class-new-offline-donation-email.php
Closes #3653 
This PR makes the global email content of New Donation and Offline New Donation as the starting point content for per form New Donation and Offline Donation Content. 
Edited content of global New Donation and Offline New Donation and tested this by checking preview, Sending Test Email from the form itself and by making a donation.
=> fix: use the customized global email content as a starting point for per-form emails #3653

includes/admin/admin-filters.php, includes/admin/payments/view-payment-details.php, includes/formatting.php
This pr will resolve #3602 #3672
=> fix: allow 8 number of decimal position for bitcoin #3602

assets/src/css/admin/payment-history.scss
This PR resolves #3692 
I've tested this PR and is no longer having the long transaction id getting outside of meta box.
=> Long transaction id in donation detail page goes outside the metabox #3692

assets/src/js/admin/admin-scripts.js
PR to fix #3674 #3680 
Tested by searching for the donation form via Ajax
Video Link: https://screencast-o-matic.com/watch/cFQF6aqL7r
=> fix: allow selection of more than the first 30 forms in the Export tool #3674

includes/admin/tools/import/class-give-import-donations.php
Closes #3699 
Updated the output the messages as mentioned in the issue.
Tested by importing data to empty database as well as non-empty database (for duplicate entry messages)
=> fix: Clarify language of Dry Run messages #3699

assets/src/js/admin/admin-export.js, includes/admin/tools/export/class-give-export-donations.php
Closes #3649 
Adds a button which checks/unchecks all checkboxes inside Importer Tool.
Testing by confirming the acceptance criteria mentioned in the issue.
=> feat: add button to toggle fields in exporter #3649

includes/admin/emails/abstract-email-notification.php, includes/emails/class-give-email-tags.php
Closes #3655 
This PR adds a new email template tag called `{donor_comment}` under the `donor` context. This email tag can be used to send the donor comment in emails which are sent to the donor.
- Tested Email Preview
- Tested Send Test Email
- Tested Donation with a Donor Comment
- Tested Donation with an empty donor comment
=> feat: create template tag to pass the donor comment to email templates #3655

includes/admin/plugins.php
Closes #3700 
This PR fixes the count in the Advanced Plugin Give page.
It will now look for authors both `WordImpress` & `GiveWP`.
Tested by adding/deleting Give addons.
=> fix: Update check for give author as both WordImpress and GiveWP

includes/admin/payments/class-payments-table.php, includes/admin/payments/view-payment-details.php, includes/admin/tools/export/class-give-export-donations.php, includes/admin/tools/views/html-admin-page-exports.php
Closes #3675 
This PR sets `autocomplete="off"` to all the datepicker fields in Give.
=> fix: Set all Give date fields autocomplete to off

includes/admin/tools/export/class-batch-export-donors.php, includes/admin/tools/export/export-functions.php, includes/admin/tools/views/html-admin-page-exports.php
This PR resolves #3709 
I've tested this PR by processing a donation with new donor email and then exporting the same details with the phone number as the custom field.
**Snippet PR:** https://github.com/impress-org/give-snippet-library/pull/86
**Note:** I've noticed that exporting donor CSV is not displaying address properly. So, I've fixed that issue as well in this PR.
**1. Added custom field on export donor screen**
**2. Added custom field with its data stored in exported CSV**
=> feat: include custom columns in donor export CSV #3709

assets/src/css/admin/settings.scss, includes/admin/settings/class-settings-gateways.php
Added notice to display on gateways page to gateways category page.
Resolves #3660 
- Notice displays properly in Safari, Firefox, Chrome
- Notice looks good on small layouts
- Notice does not display when any payment gateway add-on is activated
- Notice displays when only default gateways are active
- New feature
=> feat: add notice on Payment Gateways settings screen about availability of other Gateways

includes/post-types.php
Removes the "Quick Edit" link from the `give_forms` CPT. Leaves others intact throughout WP.
- Manually
- Feature removal
=> fix: remove the "Quick Edit" field from give_forms CPT

assets/src/css/admin/shortcodes.scss, includes/admin/shortcodes/class-shortcode-button.php
This PR will fix #3739 
https://www.useloom.com/share/e77136638d7d47d48aab0c357b35cb27
=> fix: do not display shortcode generator above form content

includes/forms/functions.php
This PR resolves #3641 
I've tested this PR with the following scenarios:
=> fix: delete form meta when we delete the donation form #3641

includes/filters.php
This PR will fix #3768
- Manually tested
- Bug fix (non-breaking change which fixes an issue) 
- Pass Donor comment if enabled to Akismet API
=> fix: pass donor comment content to Akismet api request when doing spam validation #3768

includes/class-give-html-elements.php
Adds a filter to modify `WP_Query` args for `Give()->html->forms_dropdown`.
Added a filter in a custom plugin to modify the `$form_args` to add a `meta_query` key. Tested in local WordPress install.
=> feat: add filter for forms dropdown args

includes/admin/tools/data/class-give-tools-reset-stats.php, uninstall.php
This PR resolves #3638 
I've tested this PR with the Acceptance Criteria mentioned in the issue and confirmed that the below-mentioned tables are emptied/deleted properly when respective actions are taken.
- wp_give_donors
- wp_give_donormeta
- wp_give_comments
- wp_give_commentmeta
- wp_give_logs
- wp_give_logmeta
- wp_give_formmeta
- wp_give_donationmeta
- wp_give_sequential_ordering
- wp_give_sessions
Also, Give related data from posts and taxonomy tables are also deleted properly and I've checked that subscription related Give tables are deleted when the recurring add-on is uninstalled/tool used. But, there is some sort of improvement required in the code.
=> fix: ensure `Delete All Data` actually deletes all data #3638

includes/admin/upgrades/upgrade-functions.php
This Pr will resolve #3797
I  tested this pr with the database in which we have donors <= 900
=> fix: rewrite database upgrade v201_add_missing_donors callback to prevent memory exhausted issue #3797

assets/src/css/frontend/_components.donor.scss, templates/shortcode-donor-wall.php
Resolves #3799.
Previously `str_pos()` was being used to truncate the excerpt, which is
problematic because the function looks forward for the next occurrence
in the haystack and may result in a `false` value if a space cannot be
found at the end of a comment.
This issue was resolved by using `strr_pos()` to look backwards from an
offset position to ensure that a comment is always truncated at the
space closest to the max character limit.
Manually tested:
Bug fix
=> fix: ensure all comments are truncated near limit

includes/emails/class-give-emails.php
- Adds a filter to disable the entire email message from being subject to the horrors of wpautop.
- A fix for #3788
- Filter has been added. Added `add_filter('give_email_disable_wpautop', '__return_true');` to a plugin, and the e-mail returns as it was input without any random p tags. 
- Added a filter to the class-give-emails.php
- Bug fix (non-breaking change which fixes an issue) 
- New feature (non-breaking change which adds functionality)
=> Added a filter to optionally disable wpautop on the e-mail message

includes/admin/settings/class-settings-general.php
Added proper placeholder text for chosen dropdowns within Settings > General for pages.
Resolves #3833 
- Manually
- Bug fix
=> fix: add placeholder text for the page chosen dropdowns

includes/currency-functions.php
This PR will fix https://github.com/impress-org/give/issues/3840
=> fix: remove apostrophe as a thousand separator for Taiwan New Dollars

includes/admin/tools/export/class-batch-export-forms.php
This PR will fix https://github.com/impress-org/give/issues/3847
=> fix: remove usage of PHP 5.4+ shorthand bracket array declarations

includes/class-give-email-access.php, includes/forms/functions.php
This PR resolves #3886 
I've tested this PR when the access token is expired and then processed a new donation to try to reproduce the issue and it is working fine now without any errors.
=> fix: unable to process donation when email access token expires #3886

includes/misc-functions.php
This PR is related to https://github.com/impress-org/give-gift-aid/issues/131
I've tested this PR by downloading declaration forms from various locations and is working fine.
=> fix: admin users to be allowed to download all the gift aid declaration forms

includes/currency-functions.php
This PR resolves #3893
I've tested it with Stripe checkout and it passes the donation amount properly now.
=> fix: update russian ruble currency formatting #3893

assets/src/css/admin/blank-slate.scss, assets/src/css/frontend/fonts.scss, blocks/components/blank-slate/index.js, blocks/components/blank-slate/style.scss, blocks/components/no-form/index.js, blocks/components/select-form/index.js, blocks/donation-form-grid/class-give-donation-form-grid-block.php, blocks/donation-form-grid/edit/block.js, blocks/donation-form/class-give-donation-form-block.php, blocks/donation-form/data/attributes.js, blocks/donation-form/edit/scss/controls.scss, blocks/donation-form/style.scss, blocks/donor-wall/class-give-donor-wall.php, blocks/utils/index.js, includes/forms/template.php, templates/shortcode-donor-wall.php
Resolves #3887 by fixing styling conflicts and improving block usability.
Work in progress... see acceptance criteria for current status.
=> fix: improve block styling and usability #3887

assets/src/css/frontend/theme-compatibility.scss, includes/template-functions.php, templates/global/wrapper-end.php, templates/global/wrapper-start.php
Added a custom wrapper for the Twenty Nineteen theme along with some very basic styles for buttons.
- Manually
- Bug fix
=> fix: ensure new WP Twenty Nineteen theme has proper wrapping #3900

includes/currency-functions.php
This PR resolves #3903 
This PR is to verify and fix the default currency formatting for all the listed currencies against the link as mentioned on the issue. Please check Acceptance Criteria for more information.
**Note:** There are lots of currencies which are not mentioned in the link https://documentation.progress.com/output/rb/doc/index.html#page/rb/currency-formats.html. So, I kept those currencies formatting as it is.
=> fix: verify the default currency formatting for all the currencies #3903

includes/payments/class-payments-query.php
This PR will fix https://github.com/impress-org/give/issues/3927
Visuals: 
https://www.useloom.com/share/db65c0ed776e4e90b5e0756989eb8999
=> fix: query added for search by first name + last name

includes/forms/template.php
1. Changes text back to `Make this an anonymous donation.` for the checkbox label
2. Changes text for tooltip conditionally depending on whether comments are enabled or not.
Resolves #3911 
- Manually
=> refactor: change text for anonymous checkbox label and tooltip depending on whether comments are enabled or not

includes/misc-functions.php
Change `posts_per_page` to `number` which `Give_Payments_Query()` expects within its API. 
Resolves #2973 
- Manually using recreated steps from issue.
- Bug fix
=> fix: ensure all forms get calculated properly and not just limited to 20 with posts_per_page

phpcs.ruleset.xml
This PR will fix https://github.com/impress-org/give/issues/2797
Manually Tested with Local server.
https://www.useloom.com/share/a9880f07787541269ecf5b52ac743f91
=> test: warn developer if text domain is misspelled

includes/admin/tools/logs/class-api-requests-logs-list-table.php
This PR will fix https://github.com/impress-org/give/issues/3924
=> fix: log count is not correct when search for API log related to specific WP User

includes/admin/tools/import/class-give-import-core-settings.php
Uses the fix outlined here: https://core.trac.wordpress.org/ticket/45615#comment:27 to resolved #3907 
Temporarily adds another filter to allow json uploads fro WP 5.0+ compatibility.
Tested uploading .json file types through the settings import screen and then ensured it's not allowed by default through media uploads.
- Bug fix
=> fix: allow json uploads for settings import screen only on WP 5.0+ 

includes/class-give-db-meta.php, includes/payments/class-give-payment.php, includes/payments/class-payments-query.php
This pr will resolve #3359 
This has been tested by edit, delete and insert donations.
=> perf: store donation meta data results under correct cache key #3359

includes/class-give-scripts.php
This PR resolves #2655 
I've just rearranged the variables and use the existing function instead of calling twice as per the discussion with Kevin on status call.
=> fix: use consistent key for currency decimals #2655

includes/admin/upgrades/upgrade-functions.php, includes/install.php
This PR will fix #3978 
All `sale` type log will be deleted (log + metadata)  after running the upgrade.
**Note: I added manual update because log table was introduced in `2.0.0` and automatic update can create an issue on prior `2.0.0`.**
=> refactor: remove "donations" log #3978

assets/src/css/admin/settings.scss, includes/admin/emails/abstract-email-notification.php, includes/emails/class-give-email-tags.php, includes/misc-functions.php, tests/unit-tests/tests-email-tags.php
This PR resolves #779 
I've tested this PR by processing the recurring donation and checking the email tags as per the issue description and acceptance criteria.
**Note:** Merge Pr https://github.com/impress-org/give/pull/3984 for `{subscriptions_link}` email tag
Email Tag ( Email access email tag is not shown in the list however it will work as backward compatibility)
=> feat: add template tag that takes donors to their subscriptions #779

assets/src/js/frontend/give-donations.js, assets/src/js/plugins/give-api/form.js, includes/forms/template.php
There are two changes of note in this PR to resolve #3889:
**Change 1**
In this PR I ensure that `.give-default-level` CSS class **remains** on the _default level_ selected in the admin interface:
Previously, this class was switched to the level the user selected. The problem with this is that the naming implied it was meant for only the default level and shouldn't have been changed. For instance, if I wanted to add special styling to the default level I would think I could use this class. However, previous to this PR that wasn't the case.
To resolve this I've added a new CSS class `.give-selected-level`. In this PR this CSS class is switched to the selected level.
**Note: The downside of this PR is that we're most likely going to break some existing custom styles for themes using the …
=> fix: improve focus behavior in multi-level forms #3889

assets/src/css/admin/goals.scss, assets/src/js/frontend/give-misc.js, blocks/donation-form/class-give-donation-form-block.php, blocks/donation-form/data/attributes.js, blocks/donation-form/edit/inspector.js, blocks/donor-wall/edit/inspector.js, includes/forms/template.php
The form title will not appear in these cases because it is already displayed on page:
- Modal does NOT display the form title for **form widgets**
- Modal does NOT display the form title for **modal shortcodes**
The form title will display for these cases because it has not been displayed yet:
- Modal DOES display form title for **form grid**
- Modal DOES display form title for **button mode shortcodes**
- Bug fix
=> fix: ensure the form title displays properly for widgets

includes/admin/class-give-html-elements.php
This PR resolves #3995 
I've tested this PR as per the acceptance criteria on the issue.
=> fix: "state" text appearing twice on donor detail screen #3995

assets/src/js/admin/admin-scripts.js, includes/admin/donors/class-donor-table.php, includes/admin/forms/dashboard-columns.php, includes/admin/payments/actions.php, includes/admin/payments/class-payments-table.php, includes/admin/payments/view-payment-details.php, includes/admin/tools/export/class-batch-export-donors.php, includes/admin/tools/export/give-export-donations-exporter.php, includes/donors/class-give-donors-query.php
This pr will resolve #4000 
https://www.useloom.com/share/21c6e1cbafe747a7afb8ca772c2f62a7
=> fix: support date formats with translated strings #4000

includes/class-give-donor.php
This pr will resolve #3994 
You will see mentioned SQL query when you visit a single donation form page.
=> fix: stop loading donor notes when create Give_donor object #3994

includes/admin/class-give-html-elements.php, includes/admin/donors/donors.php, includes/admin/payments/view-payment-details.php, includes/ajax-functions.php
This PR will fix #4028 
By checking  `Give_HTML_Element::select` output with various param.
=> fix: ensure do not set default autocomplete on every dropdown fields #4028

assets/src/js/admin/admin-scripts.js, give.php, includes/admin/class-give-html-elements.php, includes/admin/donors/class-donor-table.php, includes/admin/donors/donors.php, includes/admin/forms/dashboard-columns.php, includes/admin/payments/actions.php, includes/admin/payments/class-payments-table.php, includes/admin/payments/view-payment-details.php, includes/admin/tools/export/class-batch-export-donors.php, includes/admin/tools/export/class-batch-export.php, includes/admin/tools/export/give-export-donations-exporter.php, includes/ajax-functions.php, includes/class-give-background-updater.php, includes/class-give-donate-form.php, includes/deprecated/deprecated-functions.php, includes/donors/class-give-donors-query.php, includes/forms/template.php, includes/misc-functions.php, includes/payments/class-give-payment.php, includes/process-donation.php, readme.txt, tests/unit-tests/tests-donate-form-class.php
- Release `2.4.2` merging into master for push to WP.org
- PhpUnit tests
- Manual tests
- Bug fixes
=> Merge 2.4.2 for release

includes/misc-functions.php
Fixes #4041 by removing an incorrect use of `preg_match()` which was causing an error. I could not see any scenario in which the return value of `preg_match()` which is `0`, `1`, or `false` would make sense when used within `strpos()`.
- Visited System Info screen in Local by Flywheel and confirmed the default case renders correctly.
- Confirmed the System Info also copies without errors included in the content.
Bug fix
=> fix: prevent warning in System Info host detection #4041

includes/emails/class-give-email-tags.php
This PR will resolve #4044 
Tested with PHP7.3.
[x] Visit admin pages without any notice.
[x] I am able to process donation without any issue.
=> fix: resolve PHP warning on PHP 7.3 in email-tags file #4044

includes/admin/payments/class-payments-table.php
This pr will resolve #4088 
https://www.loom.com/share/407a6df7dc504b8598df6b0890a026a7
=> fix: display donations made in 2019 when the site date format is set to d/m/Y #4088

includes/admin/tools/import/class-give-import-core-settings.php
this Pr will resolve #4097 
importing and exporting string
=> fix: resolve importer failing on setting JSON import #4097

README.md, includes/admin/donors/donor-actions.php, includes/admin/forms/class-give-form-duplicator.php, includes/admin/tools/export/export-actions.php, includes/admin/tools/export/pdf-reports.php, includes/api/class-give-api.php, includes/formatting.php, includes/forms/functions.php, includes/gateways/actions.php, includes/gateways/manual.php, includes/process-donation.php
Fixes #4129 to remove the word "nonce" from appearing. This word is considered vulgar in the UK. Additionally, we have formatted these error messages in four different ways. This consolidates them all into one consistent string format to make the job of translating easier for translators. 
Visual confirmation.
Various strings updated. *NOTE:* `npm run dev` was NOT run, so the `POT` files will be generated later.
=> fix: update Nonce verification error message

includes/api/class-give-api.php
This Pr will resolve #4138 
Manually by doing rest API query with a specific donation which has nonempty `_give_payment_meta`.
https://www.loom.com/share/4a23207bdfe146bba94e0e1d187027ba
=> fix: prevent PHP notice when do rest api query #4138

includes/shortcodes.php
This PR will fix #4056
Added multiple categories and tags to the donation form and query them with a combination of comma-separated slug and id (backward compatibility).
=> feat: filter Donation Form Grid block by category #4056

includes/currencies-list.php
This PR resolves #4086
I've tested this PR as per the acceptance criteria on the issue description
=> fix: change Swiss Franc symbol to CHF instead of Fr. #4086

includes/admin/class-addon-activation-banner.php
This Pr will fix #4167 
I perform activation and deactivation on a few add-ons and I was not able to reproduce this issue.
=> fix: activating an add-on should display it immediately in activation banner not on refresh #4167

give.php, includes/gateways/stripe/class-give-stripe.php
Only displays the Stripe + Recurring version notice check if Stripe is active and less than version `2.2.0`.
Resolves #4169 
- Manually
=> fix: only show nag when Stripe Premium is lower than 2.2.0

assets/src/css/admin/stripe-admin.scss, give.php
This PR resolves #4175 
I've tested this PR as per the acceptance criteria on the issue. Also, worked on a fatal error which can be caused in future Stripe versions which is fixed within this PR.
=> fix: the stripe connect banner has appearance issues and the temporary disabling of it no longer works #4175

assets/src/css/admin/forms.scss
This pr will resolve #4075 
@mehul0810 Button placement looks good but because or CSS button shadow is hidden, i tried to fix but did not find a proper solution. Let know if you can fix it
=> fix: the "empty trash" button needs to be relocated on the "trash" status for donation forms #4075

blocks/donation-form-grid/edit/inspector.js, blocks/donation-form/edit/inspector.js, blocks/donor-wall/edit/inspector.js
Replaced deprecated calls to `wp.editor` with `wp.blockEditor`
Installed Give and Gutenberg plugin 6.1.1
Created a donation form
Created a new page and add Give Form block
Checked console for any deprecated notices or errors
N/A
This fix required changes to the Give Donation Form, Donation Form Grid, and Donor Wall blocks js files only.
=> fix: remove deprecated notice for gutenberg block #4151

includes/class-give-license-handler.php
This Pr will resolve #4197 
This is tested by opening the license setting page and all license data refreshed without issue.
=> fix: do license validation queries on $api_url #4197

includes/admin/class-admin-settings.php
This PR will resolve #4195
This code tested with code snippet mentioned in the issue description.
=> fix: exit early from fn if we are on give setting page #4195

includes/admin/donors/donor-functions.php, includes/admin/donors/donors.php
New empty option allows admins to remove the title prefix from their name.
Resolves #4211 
- Manually
=> fix: allow title to be set to blank to remove it entirely #4211

includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php, includes/gateways/stripe/includes/give-stripe-helpers.php, includes/gateways/stripe/includes/payment-methods/class-give-stripe-card.php
This PR resolves #4203 
I've tested this PR on local as well LIVE demo site on Pantheon but unable to receive any email from Stripe end. However, as per the description I'm sure that the email from Stripe is no longer sent out with default admin settings as per the screenshot below.
**Note:** There is no Stripe email sent out from Stripe Premium add-on as of now so no need to do any changes there.
=> fix: don't override Stripe email notification settings #4203

give.php, includes/plugin-compatibility.php
TCPDF defines `K_TCPDF_CALLS_IN_HTML` as false by default as a security precaution. Because Tickera uses GiveWP's composer autoloaded TCPDF version (same version they use) the constant is set to false. Therefore, we will set it to true so the QR code feature works as expected.
Resolves #3880 
- manually
- plugin compatibility
=> fix: add constant for TCPDF to function properly with ticketa

includes/admin/add-ons/actions.php
This will resolve #4217 
I uploaded and activate add-ons mentioned in `Acceptance Criteria` from Give plugin uploader.
=> fix: prevent "this plugin does not have a valid header" #4217

includes/gateways/stripe/class-give-stripe.php
This PR resolves the fatal error issue when Stripe is not enabled payment gateway in GiveWP core and recurring `1.9.3` is used.
**Please check the testing video:** https://www.loom.com/share/e65239b333124cd195e219a61afdcf70
=> fix: avoid fatal error with recurring donation using GiveWP core patch

give.php, includes/gateways/stripe/class-give-stripe.php, readme.txt
This PR resolves the issue which arises when any customer is using GiveWP core `2.5.6` and has not installed recurring donations.
**Please check the testing video:** https://www.loom.com/share/1a99b1614a7e4290817ef83cd3ab6073
=> fix: avoid errors when recurring addon is not installed with Give 2.5.6

give.php, includes/admin/upgrades/upgrade-functions.php, readme.txt
This PR resolves #4260 
I've tested this PR as per the acceptance criteria on the issue description and also check the testing video https://www.loom.com/share/787bf1bdf025405390b0311f89e4d562
=> fix: Show Stripe credit card form after upgrade when Stripe Checkout is not enabled #4260

assets/src/css/admin/stripe-admin.scss, includes/gateways/stripe/includes/admin/admin-actions.php
I added styles to the Stripe Connect Banner presented to the user before they set up Stripe.
I have tested this on Chrome, Safari, and Firefox at many screen sizes.
=> Added styling to the Stripe connect banner

includes/gateways/stripe/class-give-stripe.php
This PR resolves #4272 
Find the below-detailed testing scenario, I've handled for Give + Recurring when Stripe gateway is disabled:
> When a customer have Give 2.5.4 or lower and Recurring 1.9.3 or lower, then updating to Give 2.5.8 which usually resulted in a fatal error and then on additional refresh deactivates the recurring add-on to get rid of a fatal error.
- I've improved this scenario. So, now when customer upgrades to Give 2.5.8 having Recurring 1.9.3 or lower, then the recurring add-on is not deactivated and there will be no fatal error. Donations will also process smoothly. But, still, we have a notice in place to let customer update recurring to 1.9.4+ to ensure that any edge case doesn't affect …
=> fix: prevent fatal error on upgrade #4272

includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
Removed a space from URL to Stripe Webhooks documentation that was causing the user to see a blank page.
Navigated to the `documentation` link under Settings > Payment Gateways > Stripe > Stripe Webhooks
=> fix: remove space in link to Stripe webhooks documentation #4266

includes/misc-functions.php
This PR resolves #4284 
I've tested this PR as per the acceptance criteria on the issue description
**Before:**
**After:**
=> fix: include receipt_link_url in plain text emails #4284

includes/gateways/stripe/includes/give-stripe-helpers.php, includes/gateways/stripe/includes/payment-methods/class-give-stripe-checkout.php
This PR resolves #4290 
I've tested this PR with the Norwegian language for which an issue came up for legacy checkout in the past.
=> fix: avoid locale issue with multiple languages same as legacy checkout #4290

includes/forms/functions.php
Instead of build a url, I recommend just update the query arguments using `add_query_arg` and `remove_query_arg`. Your current way don't works with wordpress installed in a subdirectory.
Bug fix: redirect correctly when the wordpress is installed in a subdirectory
=> Fix give_send_back_to_checkout redirect

includes/emails/actions.php
This PR will resolve #4185 
Tested locally
=> fix: ensure that empty donation receipt emails are not triggered 

assets/src/css/admin/forms.scss
This Pr will resolve styling issue mentioned in https://github.com/impress-org/givewp/pull/4306#discussion_r350648893
Tested with WP 5.2 and 5.3
**WP 5.2**
=> fix: remove extra height from input field

assets/src/css/admin/forms.scss, assets/src/js/admin/button.js, includes/admin/forms/dashboard-columns.php
- surround shortcode button text with span of class "give-shortcode-button-text"
- create new style rule w/ media query in admin/forms.scss to hide button text at certain resolutions (prevents overlapping)
- update button icon style to inherit button text color
Tested locally with, and checked that the button text is hidden at appropriate breakpoints. Also tested button icon color by testing different WP admin color palettes, and the icon color matches button text color.
[Button w text shown](https://drive.google.com/file/d/1OqRR6MGRxvXpSJB8H0IEEVaYT8e6bYmS/view?usp=sharing
)[Button w text hidden](https://drive.google.com/file/d/1l3W7CdLiUvuFpmpIrkI2j2e8wIK_f8uZ/view?usp=sharing)
[Button at smaller with, w text shown](https://drive.google.com/file/d/1B_-MN7dVV4nqJCSEORaiHfUFqJhLItbN/view?u …
=> fix: improve shortcode button styles

assets/src/js/frontend/give-donations.js, includes/forms/template.php
Resolves #4316 
Alters includes/form/template.php such that the "state" input's require attribute matches the field label's require indicator. Instead of using separate logic for each, they now both rely on a shared variable (based on existing logic for label indicator). 
Tested by checking demoing code against multiple different "base countries" as found in GiveWP settings. State fields now behave correctly, both for countries with required and optional state fields. Also tested with various payment gateways, behaves as expected.
Rather than touching logic of the $require_state variable, which might impact code in unforeseen ways, I opted to create new $validate_state variable that uses logic previously written for the field indicator to show whether the field is required/needs to be …
=> fix: base state indicator display and field requirement on same logic

includes/user-functions.php
Resolves #3253 
Removed duplicate code from give_get_donor_address() to instead rely on the Give_Donor class method get_donor_address. give_get_donor_address now uses creates a new Give_Donor class based on the donor_id passed to it (keeping existing logic for checking if now id is passed, and using get_current_user instead). Then returns the result of get_donor_address called on the new Donor object.
There is no existing unit test for give_get_donor_address, but I ran the unit test for Give_Donor::get_donor_address() and passed. I checked the return values of each on a local site and found them to behave identically and as expected.
n/a
=> refactor: remove duplicate code for retrieving donor address

tests/unit-tests/tests-misc-functions.php
Resolve #3232 
Added new test for give_verify_minimum_price() to tests-misc-functions.php. The test checks that both 'minimum' and 'maximum' prices can be verified, by setting up a sample multilevel donation form, then writing to the $_POST object to check how the function handles different donation levels.
Tested by running phpunit tests. First tested by itself, then tested alongside all phpunit tests, to ensure that directly writing to $_POST had no adverse impact on other tests. 
n/a
=> feature: add test for give verify minimum price

assets/src/js/admin/reports/components/routes/index.js, assets/src/js/admin/reports/pages/overview-page/index.js
Resolves #4342 
Added an OverviewPage component (found in reports/pages/overview-page/index.js) to be ultimately used to contain all presentational components of the Overview page. Added this new OverviewPage component to appropriate route in Router.
Served locally and tested in browser without logging errors.
New overview page component loaded with Grid as child component
=> feature: add overview page component 4342

includes/class-give-donate-form.php
Modified setup_donation_form to return ID if setup is successful. This method is called by Give_Donate_Form->create(), which now returns an ID when creation is successful.
Ran PHPUnit tests, which passed. Also searched the codebase for references to Give_Donate_Form->create() and found only one reference, in give_import_get_form_data_from_csv(). Tested csv import functionality locally, and the does not appear to be any conflicts.
n/a
=> fix: modify setup_donation_form to return ID

assets/src/js/admin/reports/components/chart/index.js, assets/src/js/admin/reports/components/chart/utils/index.js, assets/src/js/admin/reports/pages/overview-page/index.js, includes/reports/class-reports-admin.php
Resolves #4331 
Added a flexible chart component for building charts using ChartJS. Accepts **type, aspectRatio and data** props.
**NOTE: ** Implementation of a proper legend for Charts should be explored in another PR, as this functionality might best be suited in a separate component.
Tested locally in browser and does not log errors.
=> feature: add flexible chart component 4331

assets/src/css/frontend/forms.scss, assets/src/js/frontend/give-misc.js, includes/forms/template.php
This PR will resolve #4352.
**Note: This solution can possibly break button style on the website when donation form display style setting to `Button` but the feature will not break. Check the video for the explanation.**
https://www.loom.com/share/0e99c2865bb94b3295b5a28d3bbc827c## Screenshots (jpeg or gifs if applicable):
Dom element location Change
=> fix: when clicking modal popup button don't hide "donate now" button

assets/src/js/admin/reports/components/card/index.js, assets/src/js/admin/reports/components/card/style.scss
Resolves #4358 
Refactored Card styles into style.scss file, and addressed issue with padding so that content is not padded, but title is. Also destructure Card component props, defined prop types and added default props.
Tested locally and throws no errors in browser console.
=> fix: style card to pad title not content

blocks/donation-form/style.scss
Resolves #4354 by adjusting styles that were conflicting with the default Gutenberg editor.
- Manually
- Style bug fix
=> style: fix block styles so they don't conflict with default gutes #4354

assets/src/js/admin/reports/components/tab/index.js, assets/src/js/admin/reports/components/tabs/index.js, includes/admin/admin-pages.php, includes/admin/reports/reports.php, includes/admin/views/html-admin-settings.php, includes/reports/class-reports-admin.php
Resolves #4372 
Added link to legacy reports page on new reports page, and a link to new reports page that appears on the legacy reports page. Also removed legacy reports page from the admin menu, and renamed the new reports page from 'Reports v3' to 'Reports'. For now, the new reports page uses 'give-reports-v3' as a slug, while the legacy reports page uses just 'give-reports'. The transition should be handled in a seperate issue because it has more to do with modifying existing routing logic than simply adding links to the pages.
Tested locally and throws no errors in browser or in PHPUnit tests.
=> feature: add link to legacy reports page

give.php, includes/class-give-license-handler.php, includes/class-give-session.php, includes/currency-functions.php, includes/emails/class-give-emails.php, includes/misc-functions.php, includes/payments/class-give-payment.php
This Pr will resolve #2572 
`give_doing_it_wrong ` and `_give_deprecated_function` serve different purpose. we can use `_give_deprecated_function` when deprecating a function while we can use `give_doing_it_wrong` when deprecating function parameter or suggestion for the developer when doing something wrong.
I refactored `give_doing_it_wrong ` to accept only two parameters `function name` and `message`. I deprecated the `version` because that can we part of `message`. Because it is a silent deprecation of the third parameter, so it will not throw any notice or warning when passing.
This PR tested by calling deprecated functions.
=> refactor: improve `give_doing_it_wrong()` function

blocks/donation-form-grid/data/options.js, includes/admin/shortcodes/shortcode-give-donation-grid.php
Resolves #4392 
Fixes issue with Donation Form Grid shortcode sorting by 'name' rather than 'title' when user chooses to sort forms by 'Form Name'. To resolve the issue, I updated the value associated with the 'Form Name' option to be 'title' in both the block editor inspector and the shortcode generator. This value is used to build a WP_Query when rendering theDonation Form Grid shortcode. **To avoid surprises to users: currently, this fix does not impact existing shortcodes, or blocks already added. To enable the fix, they need to regenerate the shortcode, or manually set the block to sort by Form Name. _Open to suggestions on this!_**
Tested block editor and shortcode generator by creating forms titled 'Test A', 'Test B', and 'Test C', then renaming the form's slugs to 'California', …
=> fix: sort form grid by title when Form Name is selected

blocks/donation-form-grid/edit/block.js, blocks/donation-form/edit/block.js, blocks/donor-wall/edit/block.js
Resolves #4402 
Replaces calls to deprecated wp.components.serverSideRender with wp.serverSideRender.
Tested locally and throws no errors in browser console, including deprecation warnings.
n/a
=> fix: replace wp.components with wp.serverSideRender

assets/src/js/admin/reports/app/pages/overview-page/index.js, src/API/API.php, src/API/Endpoints/Reports/FormPerformance.php, src/API/Endpoints/Reports/PaymentStatuses.php
Resolves #4399 
Adds 'form-performance' endpoint to the Reports API. The endpoint uses existing logic from the Give Payment Stats class to return information about the top performing forms.
Tested locally without errors in the browser console. Passed PHPUnit tests.
n/a
=> feature: add form performance report endpoint

includes/forms/template.php
This PR will resolve #4395
Output donation form with there shortcode where first contain `Button` style and other `All fields`.
Testing Video: https://www.loom.com/share/20686165b3114723baf25586b860f23c
=> Bug: Multiple Donate buttons appearing when a button mode form also appears on the page

assets/src/js/admin/reports/app/pages/overview-page/index.js, assets/src/js/admin/reports/components/donor-item/index.js, assets/src/js/admin/reports/components/rest-list/index.js, src/API/API.php, src/API/Endpoints/Reports/TopDonors.php
Resolves #4410 
This PR adds a higher order RESTList component that handles interaction with the Reports API endpoints, fetching data on page load and when the PeriodSelector is changed. For demonstrative purposes, the PR also introduces the 'top-donors' endpoint which returns dummy data for a donors list.
Tested locally and throws no errors in browser. Passed PHPUnit tests.
n/a
=> feature: add RESTList HOC

assets/src/js/admin/reports/app/pages/overview-page/index.js, assets/src/js/admin/reports/components/donation-item/utils/index.js, assets/src/js/admin/reports/components/donor-item/index.js, assets/src/js/admin/reports/components/donor-item/style.scss, assets/src/js/admin/reports/components/rest-list/index.js, package-lock.json, package.json, src/API/API.php, src/API/Endpoints/Reports/RecentDonations.php, src/API/Endpoints/Reports/TopDonors.php
Resolves #4416 
This PR adds the 'recent-donations' endpoint to the Reports API. The endpoint returns data on recent donations for a given period, gathered using the existing Give_Payments_Query and Give_Payment classes. The data is returned in the correct shape to be used in a RESTList component, populated by DonationItem components.
This has been tested locally and throws no errors in the browser console. Passed all PHPUnit tests.
=> feature: add recent donations endpoint

assets/src/js/admin/reports/components/donor-item/index.js, src/API/Endpoints/Reports/TopDonors.php
Resolves #4428 
This PR resolves issues raised by @ravinderk regarding the implementation of the top donors endpoint. Notably, it localizes the default donor name string, implements the _n() function in place of a ternary operator to handle plural localization, and remove an array_push call.
This has been tested locally and throws no errors in the browser. Passed PHPUnit tests.
=> fix: resolve top donors endpoint issues

src/API/API.php, src/API/Endpoints/Reports/AverageDonation.php, src/API/Endpoints/Reports/Endpoint.php, src/API/Endpoints/Reports/Income.php
Resolves #4425 
This PR adds the 'average donation' endpoint which calculates average donation over time and returns a data object appropriate shaped to be used in the RESTMiniChart component. The endpoint calculates average donation for the entire given period, as well as the trend in average donation from the previous period. 
Tested locally and throws no errors in browser console. Passed PHPUnit tests.
=> feature: add average donation report endpoint

assets/src/js/admin/reports/app/pages/overview-page/index.js, src/API/API.php, src/API/Endpoints/Reports/Refunds.php
Resolves #4426 
This PR adds the 'refunds' endpoint to the Reports API. It returns data reflecting the number of refunds given over the selected period of time. It also calculated the total number of refunds, and trend in refund count for the selected period of time.
Tested locally and throws no errors in the browser console. Passed PHPUnit tests.
=> feature: add refunds report endpoint

package-lock.json, package.json
Resolves #4474 
This PR updates the stylelint dependency to v11, which correctly defines the unicode-bom, resolving the error that previously prevented commits of scss files.
Tested locally by attempting to commit a changed scss file.
=> fix: require the correct version of stylelint to prevent unicode-bom rule error

includes/forms/functions.php
In `forms/template.php`, the price level text is usually run through the `give_form_level_text` filter. In `forms/functions.php`, this was missing, which meant that customization of the level text didn't work in the donation detail view. So I added the missing `apply_filters` call
I've made a dummy filter function like this:
```php
function my_form_level_text($price_text, $form_id, $price) {
return 'XXX';
}
add_filter('give_form_level_text', 'my_form_level_text', 10, 3);
```
Then I visited the donation detail page (`/?donation_id=1234`) and checked that `XXX` was rendered in the details table
Makes Give more easily customizable (or rather: It allows me to customize without changing Give Core)
=> Add missing customization hook

src/API/Endpoints/Reports/Endpoint.php, src/API/Endpoints/Reports/FormPerformance.php, src/API/Endpoints/Reports/Income.php
Resolves #4497 
This PR improves the Reports experience by presenting fresh data for recent periods, by avoid caching for periods under a week.
Tested locally and throws no errors in browser console. Passed PHPUnit tests.
=> fix: avoid retrieving cached data for recent periods

assets/src/js/frontend/give-stripe.js, includes/gateways/stripe/includes/give-stripe-helpers.php, includes/gateways/stripe/includes/give-stripe-scripts.php
This PR resolves https://github.com/impress-org/give-stripe/issues/433
I've tested this PR with the following scenarios:
**Video Link:** https://www.loom.com/share/33c65901d98e4b68a0e77811520c74de
@DevinWalker I need your help to process Apple Pay recurring donations and then try updating the payment method. Please pull below PR as well before testing:
- https://github.com/impress-org/give-stripe/pull/434
- https://github.com/impress-org/give-recurring/pull/925
=> fix: allow G pay and Apple pay ability to update payment information without error #433

src/Views/Admin/DashboardWidgets/Reports.php, src/Views/Admin/Pages/Reports.php
Resolves #4538 
This PR introduces a check in the get_all_time_start() fn to ensure that donations have been found before attempting to retrieve the date of the earliest donation.
Tested locally and throws no errors in the browser console. Passed PHPUnit tests. No PHP notices appeared in debugging.
=> fix: add donation check to get all time start

assets/src/js/frontend/give-stripe-checkout.js, assets/src/js/frontend/give-stripe.js
This PR will resolves #4467 
I have tested this PR with the below-mentioned scenarios:
**Check another PR for Stripe Google/Apple Pay scenario:** https://github.com/impress-org/give-stripe/pull/435
*Before*
*After*
=> fix: Stripe payments don't work in form grid if grid [modal + has a closed form] #4467

includes/gateways/stripe/includes/class-give-stripe-payment-intent.php, includes/gateways/stripe/includes/payment-methods/class-give-stripe-card.php
This PR is related to a Stripe Payment Intent issue which was not getting caught 😞 
But, after the call with @Benunc today, and checking some of the customer's site (staging as well as production), we were able to find out that the issue happens when there is JS conflict on the customer website. So, the JS conflict is restricting our JS to generate payment method ID and due to which the error happens.
1. While processing a donation, if payment intent is throwing an error then we are sending the donor to the donation form with the error message instead of sending the donor to the donation confirmation page with `pending` status.
2. When a donor clicks on the "Donate" button and somehow the payment method ID is not generated then we are immediately sending the donor to the donation form …
=> fix: resolve stripe payment intent error

src/API/Endpoints/Reports/AverageDonation.php
Resolves #4537 
This PR resolves the bug found by @rickalday, where figures with more than 3 decimal places are not properly handled by give_format_amount() or give_currency_filter() when the thousands separator is set to period. Because the get_average_donation() function often results in a number with many decimal places, the solution introduced in this PR is to round calculated average donations to the 2nd decimal place.
Tested locally and throws no console errors in the browser. Passed PHPUnit tests.
=> fix: round avg donations to the 2nd decimal place

includes/gateways/stripe/includes/class-give-stripe-checkout-session.php
This PR resolve #4566 
This issue can be reproduced for donor processing recurring donations using Stripe Checkout 2.0 without Stripe Premium active.
Please check the acceptance criteria on the issue description.
=> fix: Error in form when using Stripe Checkout and Recurring Donations. #4566

blocks/donation-form/style.scss
This Pr will resolve #4577 
Locally by visiting the post edit screen.
=> fix: prevent shifting Gutenberg block menus

assets/src/js/frontend/give-donations.js, includes/forms/template.php
This resolves the issue with the title field displaying incorrectly. The fix was removing the `required` class that was output regardless.
Note: this was an issue with both floating and non-floating labels. Essentially, a fix for all configurations.
- Manually
=> Fix title field required label displaying incorrectly

src/Controller/Form.php, src/Helpers/Form/Utils.php
This PR will resolve #4585.
As per scope we only have to test that on the single donation, whether or not form page form style changes on the basis of the selected form template. I find out that it works as expected.
Single donation form page with `Sequoia` and `Legacy` form template.
=> feat: render selected form template on single donation page

src/API/Endpoints/Reports/Endpoint.php
This PR resolves issue #4592. In the original issue, a Fatal Error was thrown when accessing a site through wp-cli with Give installed because get_report_shema() received too few arguments. In this PR, the $request parameter is no longer expected by the get_report_schema() fn, solving the issue.
Tested locally, passed PHPUnit tests. Functional when using wp-cli.
=> fix: prevent Reports related issue when using wp-cli

assets/src/css/admin/stripe-admin.scss, assets/src/js/admin/stripe-admin.js, includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
This PR resolves #4561 
I've tested this PR by connecting and disconnecting the Square account and refreshing the page multiple times after connected to see that the popup is displayed once.
=> feat: add stripe connect modal notice after connecting #4561

includes/gateways/stripe/includes/payment-methods/class-give-stripe-card.php
This PR resolves #4605 
- https://github.com/impress-org/givewp/blob/develop/includes/gateways/stripe/includes/payment-methods/class-give-stripe-card.php#L279
I have tested this PR by processing donation via Credit Card.
=> fix: donation forms using Stripe do not redirect to success page #4605

assets/src/js/frontend/give-stripe-sepa.js, assets/src/js/frontend/give-stripe.js
This PR will resolve most of the issues related to payment intent.
**Video Link:** https://www.loom.com/share/5f40b529f8b74149b3de17c56712890a
**Related PR:** https://github.com/impress-org/give-stripe/pull/436
- https://github.com/impress-org/givewp/blob/develop/assets/src/js/frontend/give-stripe.js#L50
Test processing donations on the affected sites. I've tested it on the hopeforSD staging site where I can replicate the issue.
=> fix: resolve payment intent issue

src/Views/Form/Themes/Sequoia/assets/css/form.scss
Resolves #4609 
This PR resolves a visual bug pointed out in issue #4609, where the Sequoia form wrapper width did not match the width of forms in the Figma design.
This PR also corrects other margins that had been incorrectly adjusted to fit within the wrong wrapper width. Now, margins match the Figma designs pixel for pixel and the form wrapper width is correct.
This PR only impacts the css of the Sequoia form template, found in Sequoia's assets directory.
Check that each step accurately reflects the spacings/margins found in the Figma designs. See Figma designs for reference: https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/Form-Themes?node-id=1882%3A44&viewport=-259%2C1586%2C0.5
=> fix: increase Sequoia form wrapper width

includes/admin/forms/class-metabox-form-data.php, includes/admin/give-metabox-functions.php, includes/admin/import-functions.php, includes/admin/tools/export/give-export-donations-exporter.php, includes/forms/template.php
This PR will resolve #4579.
As per previous experience, we found that we can set default value to common value which will help admin to quickly set up it.
Default Form settings.
Form settings default value (mentioned in issue `Acceptance Criteria` section )
=> feat: enable form setting for quick setup

src/Form/Theme.php, src/Form/Theme/LegacyFormSettingCompatibility.php, src/Helpers/Form/Theme/Theme.php, src/Views/Form/Themes/Legacy/Legacy.php, src/Views/Form/Themes/Sequoia/Actions.php, src/Views/Form/Themes/Sequoia/Sequoia.php
This PR will resolve #4608 
This pr affect form setting saving functionality. As you know we move a few form display related settings to `Legacy` form template but these settings play a critical role in form rendering. That why we must need this setting.
As per the solution, I created a class `Give\Form\Theme\LegacyFormSettingCompatibility` which is accessible by any form template by `getLegacySettingHandler` function. This class responsible to store default setting values (depends upon form template setup) when update forms settings.
A developer can also map their settings to legacy form settings which means legacy form setting will change when value change for that specific form setting otherwise a default value will store.
We choose the default settings as per the `Sequoia` form …
=> feat: handle form setting which moved to Legacy form template

src/Helpers/Form/Utils.php, src/Views/Form/Themes/Sequoia/Actions.php
As per design Sequoia form template requirement, we want o to impose zero number for decimal on the frontend. Following PR resolve issue by returning zero on filter hook of helper function which developers use in there an add-on to access number of decimal admin setting.
Change in PR will apply only to the frontend (because of template code loads in the frontend only) donation form only if it has a `Sequoia` form template or we are processing donation with this form or any ajax request on frontend related to this form.
To test this PR, you can review a number of decimals apply to the amount in `Choose Amount` section on the donation form or amount on the receipt.
You can also test above mentioned item with `Fee Recovery` add-on.
=> feature: do not render decimal places on 'choose amount' screen of Sequoia template

src/Views/Form/Themes/Sequoia/assets/css/form.scss, src/Views/Form/Themes/Sequoia/assets/js/form.js
Resolves #4600 
This PR improved the submit button loading state by replacing the existing loading animation with a more modern, SVG rendered, in-button loader.
Previously, when the submit button was clicked, the button text would be replaced by "Please Wait", with a GIF spinner appearing next to the button. This PR replaces the GIF spinner with a modern looking SVG spinner that appears over the button (replacing the "Please Wait" text).
The solution affects the Sequoia form assets (css and js) as it introduces the `sequoia-loader` css class, and defines specific styles for the sequoia loader within the submit wrapper. It also adds frontend scripting to override the existing Give loader, and prevent the "Please Wait" text from appearing.
Test the payment information screen of the Sequoia …
=> feature: improved submit button loader

src/TemplateSkinManager.php, src/Views/Form/defaultFormDonationProcessing.php, src/Views/Form/defaultFormReceiptTemplate.php, src/Views/Form/defaultFormTemplate.php, src/Views/Form/defaultRedirectHandlerTemplate.php, src/Views/IframeView.php
This patch does not fix any issue but renders provide a convenient way to generate a donation form view template and prevent code repetition. To solve it we added class `Give\TemplateSkinManager` with which you have set the necessary things on view and then render it.
This will require refactoring of existing default form template views.
You can review donation form view like donation form view, receipt view, donation confirmation view, etc.
=> feat: add form template view skin generator

assets/src/js/plugins/form-template/parent-page.js, assets/src/js/plugins/form-template/utils.js, src/Controller/Form.php, src/Views/Form/Templates/Sequoia/assets/js/form.js
This patch adds logic to automatically redirect the donor to the third step of the Sequoia form template when a donor gets an error during donation processing.
Since this change is related to the `Sequoia` form template that's why this patch will only affect redirects for this theme. I add `showDonationProcessingError` query parameter to detect donor checkout redirect on donation error. 
I tested this patch by manually calling `give_send_back_to_checkout` after ajax validation which redirects donor to donation form view. I also test this with Paypal standard by returning from Paypal standard checkout page without completing the donation.
=> feat: redirect donor `Add Your Information` section if any error occurred during donation processing

assets/src/js/admin/stripe-admin.js, assets/src/js/frontend/give-stripe-becs.js, includes/gateways/stripe/class-give-stripe.php, includes/gateways/stripe/includes/admin/admin-actions.php, includes/gateways/stripe/includes/admin/admin-helpers.php, includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php, includes/gateways/stripe/includes/give-stripe-helpers.php, includes/gateways/stripe/includes/give-stripe-scripts.php, includes/gateways/stripe/includes/payment-methods/class-give-stripe-becs.php, webpack.config.js
This PR resolves #4590 
This PR adds a feature to accept donation via Stripe BECS Direct Debit for Australia
I have tested this feature by processing donation with manual API Keys with a Stripe account enabled for BECS Direct Debit.
**Admin Settings**
**List of Payment Gateways in admin**
**Update Payment Method Screen for Recurring Donations**
**Donation Form Screen**
**Details stored under Donation Notes**
=> feat: add support for becs direct debit payments for australia #4590

assets/src/css/admin/forms.scss, package-lock.json
In the wp-admin, many text inputs inherit this style from the wp-admin core styles:
```
.meta-box-sortables input {
vertical-align: middle;
}
```
There's often no issue, but with `.give-money-field` inputs (like the "donation amount" field in the Donation Form post type editor metabox), this creates an alignment issue with the money field's input and the currency symbol element that immediately precedes it.
**Changes:** By setting this input's `vertical-align` to `baseline`, we override that core style on this class of field specifically, which gets the input and its preceding currency symbol more pleasingly aligned
- Text inputs of class `.give-money-field` in the wp-admin
- Example: "donation amount" field in the Donation Form post type editor metabox
- "Donation amount" field on …
=> fix: fix alignment of admin .give-money-field inputs and their preceding currency symbols

includes/admin/forms/class-metabox-form-data.php, src/FormAPI/Fields.php, src/FormAPI/Form/Group.php, src/FormAPI/Group.php
This patch will add a `Group` type field and fix logic to save the `group` type form template setting.
This PR will affect the form template saving logic.
you can add a `group` type setting for form template which contains few fields. Save setting and review if it reflects in group settings or not.
```
[
'id'            =>  'custom_setting',
'name'          =>  'Custom Setting',
'type'          => 'group',
'options'       => array(
'add_button'    => __( 'Add Level', 'give' ),
'header_title'  => __( 'Donation Level', 'give' ),
'remove_button' => '<span class="dashicons dashicons-no"></span>',
),
// Fields array works the same, except id's only need to be unique for this group.
// Prefix is not needed.
'fields'        => array(
array(
'name'       => __( 'Text', 'give' ),
'id'         => …
```
=> fix: save group type form template setting correctly.

includes/admin/reports/graphing.php
Resolves #4644 
This PR introduces a patch for an issue first found in GiveWP 2.6.3. When a user attempted to filter data by time period on the legacy reports page, they were redirected to the new reports dashboard. This PR resolves this issue by adding the "legacy=true" URL parameter to the redirect performed in the give_parse_report_datas() function.
This PR affects the legacy reports graphing logic, by ensuring that when filtering from the legacy reports page, the redirect is flagged with the "legacy=true" URL parameter.
Try filtering by time periods on the legacy reports page. Are you redirected to the new reports dashboard? Are you presented with data from the expected time period?
=> fix: prevent redirect to new reports dashboard on legacy filtering

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4616 
This PR introduces frontend logic to the Sequoia template to ensure that transitions in height appear smooth, and iframe resizing does not appear choppy.
While researching the solution, it became apparent that iframe-resizer as a library would struggle to handle animation/transitions in height of the iframe's body element. With this in mind, the solution presented here simply compares the height of the current step to the next step, and if the height of the next step is greater, instantly increases the body min-height to accommodate the transition that accompanies the change in step height. If the next step is shorter, the body height is only adjusted after the transition is completed (200 milliseconds).
This PR only touches the Sequoia frontend assets, specifically …
=> fix: prevent choppy iframe resizing

src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4648 
This PR resolves a long standing bug with the Sequoia template where the initial step would load with a large blank space beneath it (before the "Donate Now" button. This PR also introduces some other improvements to how the Sequoia template handles animating between steps (specifically around how the navigator/header area animates in/impacts other form elements).
The impacts of this PR are limited to the Sequoia template assets.
Try loading the Sequoia form template on the frontend, dos a large blank space appear beneath the initial step? Does the form animate from step to step smoothly, without quick jumps when the navigator/header section first appears? Does the navigator/header section slide in/out smoothly?
=> fix: prevent blank space beneath initial step of Sequoia template

assets/src/js/frontend/give.js, assets/src/js/plugins/give-api/api.js, assets/src/js/plugins/give-api/share.js, src/Views/Form/Templates/Sequoia/optionConfig.php, src/Views/Form/Templates/Sequoia/views/receipt.php
Resolves #4658 
This PR introduces functionality to the social sharing links found in the Sequoia template, and a new "Twitter Message" option for the template.
Now, when a user clicks share to Facebook, or share to Twitter, a new window opens prompting them to actually share the donation page to social media. The Twitter sharing link can have a custom message, which is set using the "Twitter Message" template option. 
This PR impacts the Sequoia receipt view, and Sequoia template option config file.
Can you enable/disable the social sharing section from template options? Are you able to update the default tweet from the template options panel? Does the share to facebook link open in a new window as expected, preloaded with a link to the page you made the donation on? Does the share to to …
=> feature: Sequoia social sharing links now prompt users to share

src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4666 
This PR improves the Sequoia form template so that validation error notices now appear at the top of the form. This PR resolves this issue as it appeared in the choose amount step and the payment information step.
The PR also introduces interactivity for error notices, so that when a notice is clicked you are directed to the relevant step of the form to make changes.
This PR affects Sequoia form template assets. Specifically it touches some css, and introduces a MutationObserver to the frontend logic.
When you input an invalid amount, does the error notice appear at the top of the choose amount screen? When you attempt to submit a donation with an invalid amount, does the submit loader disappear and error notices appear at the top of the payment information screen? When …
=> fix: form validation notices now appear above content

includes/class-give-cache.php
Resolves #4546
This patch allows to cache the donation page. I also added a filter `give_can_cache_page` which others can use to set up there own logic for Give default pages.
It will affect Give core page caching login in `Give_Cache`.
Confirm in the source that WP Rocket's comment is present in the footer and you can process donation without any issue as a guest, email accessed do not, and logged-in donor.
=> fix: allow to cache donation form page

src/Form/LoadTemplate.php
Resolves: #4673 
As s side effect new receipt view was loading when view old recept but as per discussion with @DevinWalker we decided to show a receipt in legacy style for styling consistency. As per logic, a donor can see receipt either on the donation confirmation page or on the history page.
To restrict the new receipt view to a donation confirmation page, I added logic to compare the referer.
It will affect `wp_ajax_get_receipt` handler `LoadTemplate::handleReceiptAjax`.
Check receipt style on the donation confirmation page and history page.
=> fix: show old receipt in legacy style  for styling consistency

src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4685 
This PR resolves an issue that caused amounts without labels to display tooltips in the Sequoia form template. Previously, when a user added an amount without a label, a tooltip would appearing over the amount button that simply displayed the amount again (eg: When a $25 level button was hovered, the tooltip also ready $25). The issue is caused by the way that GiveWP core renders multilevel amount donation forms, where a donation level left blank would simply render with the donation amount. 
This behavior makes sense in the context of legacy forms, but with Sequoia we are hacking the frontend to display the level's amount, and this "label" as a tooltip. With this in mind, I reached for a frontend solution that would be unique to Sequoia, that doesn't touch core logic, …
=> fix: Sequoia no longer shows tooltips for unlabeled amounts

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4686 
Previously, when the company field was enabled, it did not include any icon. This made it visually different from other fields in the row, and made it so that the company input was not vertically aligned with other inputs in the form (eg the name input). 
To resolve this issue, I used the setupInputIcon funciton to add a building icon to the company field.
This PR only affects Sequoia template frontend assets, specifically JS.
Enable the company field for a form using the Sequoia form template. Does the company field show a small building icon before the input?
=> fix: company field now includes a building icon

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves: #4684 
Pervasively, when only one gateway was enabled, the gateway would not appear in the Sequoia form template. Now, when only one gateway is enabled, it is rendered by itself, and not as part of any radio selection.
The solve this problem I made sure that the moveFieldsUnderPaymentGateway function was only called when multiple gateways are enabled, so that it would not be moved into the radio selection (which is set to display none when only a single gateway is enabled). 
This fix only impacts Sequoia template frontend assets, specifically JS.
Try enabling multiple payment gateways, then test enabling only one payment gateway. Do gateways appear as expected? When only one is enabled, does it load by itself rather than in a radio selection interface?
=> feature: when a single gateway is enabled, Sequoia renders that gateway without radio selectors

src/Views/Form/Templates/Sequoia/assets/css/form.scss
Resolves #4674 
Previously, when a form weas setup without an image or goal, the advance button had too great a top margin. This PR resolves this error, but introducing a sibling selector rule, so that when the advance button immediately follows a description, it has a smaller top margin. This purely css solution was decided on because it required the smallest change to the codebase, and touched the least number of files. It is also the most performant for server and client.
This PR only impacts the Sequoia assets, specifically the CSS file.
Try enabling or disabling goals and featured image, as well as image in the template options area. Does the advance button's top spacing seem appropriate in all these different contexts?
=> fix: Sequoia template now displays proper spacing above the advance button when goal/image are disabled

includes/admin/settings/class-settings-display.php, includes/forms/functions.php
Resolves #4598 
This PR prevents the global floating labels option from impacting non-legacy forms. Previously, when the global floating labels option was enabled, it interfered with styling non-legacy forms as it would output additional classes to form elements. The solution proposed here uses the `isLegacyForm` helper function to modify the `give_is_float_labels_enabled` function, checking if the form is a legacy form, and returning `disabled` if not.
This PR touches main functions file, and the global display options configuration.
Try enabling and disabling the global floating labels options. Does it impact forms using the Sequoia template? Do floating labels still work as expected in forms using legacy templates?
=> fix: global floating labels option no longer impacts non-legacy forms

includes/admin/emails/class-email-notification-util.php, wpml-config.xml
The emails sent to donors cannot be translated using WPML even after registering them in the `wpml-config.xml` file.
Only one change needed in PHP `/includes/admin/emails/class-email-notification-util.php` and some settings in `wpml-config.xml` file
Add the emails sent to donors, for example, Donations -> Settings -> Emails -> Donor Emails and try to translate is using WPML.
=> WPML: Registring the emails sent to donors for translation

includes/admin/add-ons/actions.php, includes/admin/upgrades/upgrade-functions.php, includes/class-give-license-handler.php
Resolves #4669 
You can see a list of unexpected behaviors here: https://github.com/impress-org/givewp/issues/4669#issuecomment-622260708
To resolve the issue we will do following things when activating bundle plan license key:
1. Remove a single addon license key if part of the bundle plan.
2. Remove the existing bundle plan license key. Admin can only activate one bundle plan key.
Note: an automatic upgrade also added and it will only remove single addon license keys if part of an active bundle license key.
This patch adds logic to remove single license keys and bundle plan license keys when activating the bundle plan license key. Similar logic will run on when updating the core.
Activate multiple bundle plan license key from low to high add-on count when any of must-have add-on …
=> resolve unexpected behaviour created by orphaned license keys 

src/Views/Form/Templates/Sequoia/Sequoia.php, src/Views/Form/Templates/Sequoia/assets/css/feerecovery.scss, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4712
This PR introduces frontend styles for fee recovery donation inputs as they appear in the Sequoia form template.
This PR affects the Sequoia styles, and Sequoia template class. It introduces the feerecovery.scss file.
Test frontend appearance of the fee recovery donation inputs, using different option configurations in the Fee Recovery panel. Do they appear as expected? Does the input handle long custom fee recovery copy gracefully?
=> Feature: fee recovery inputs are now styled in Sequoia template

includes/payments/functions.php
Resolves: https://givewp.slack.com/archives/C0FAGC83C/p1588794766128000
In `epic/form-template` branch test start falling because `date` param was not found in the donation session.  A valid donation session must have a few required values (as mentioned in screenshot 2).
We insert `donation_id` to donation session when donation creates but we are not validating that donation session. That means even if the donation is not processed from frontend a donation session will be set up with minimum `donation_id` param which is not correct.
To resolve this issue, this pr adds a validate donation session before adding `donation_id` to the donation session.
**Screenshot 1**
**Screenshot 2**
This patch will add a condition block in the `give_insert_payment` function.
Confirm if we can process …
=> Stop adding donation id to invalid or empty donation session

includes/misc-functions.php, templates/shortcode-donor-wall.php
Resolves #4721 
Previously we are not printing localize dates on the donor wall. This pr will upgrade `give_get_formatted_date` to return localize date.
Added the fourth param to `give_get_formatted_date` function to check if whether or not return localize date.
```
function spark_change_language( $locale ){
return 'ug_CN';
}
add_filter( 'locale', 'spark_change_language' );
```
Use above code snippet to set locale dynamically and review the date printed on the donor wall.
=> print localize date on donor wall

src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/css/receipt.scss, src/Views/Form/Templates/Sequoia/views/receipt.php
Resolves #4657
_This PR includes backend compatibility work by @ravinderk and front end styling by @henryholtgeerts. It requires PDF receipts addon running off of this branch (until it is merged): https://github.com/impress-org/give-pdf-receipts/tree/issue/fix-pdf-receipt-template-rendering-220._
Previously, when the PDF receipts addon was active, the PDF receipt link was rendered in the receipt area as just another receipt detail row. This PR ensures that in the Sequoia template the PDF receipt link is rendered as a large button, styled to match Figma designs.
This PR affects Sequoia assets and the Sequoia receipt view.
With PDF receipts enabled and using the correct branch, process a new donation. Are you shown a PDF receipt link as expected? Does the link work correctly? Can the link …
=> feature: Sequoia PDF receipt download button is now compatable with PDF receipt addon

src/Views/Form/Templates/Sequoia/Sequoia.php, src/Views/Form/Templates/Sequoia/assets/css/ffm.scss, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4719 
This PR introduces styling and frontend functionality for inputs rendered by the form fields manager addon. Previously, these inputs were not styled and used default browser styles. Now, through a combination of css, pseudo elements and javascript, the inputs are consistent with other inputs native to the Sequoia form template. 
Because Form Field Manager outputs fields in a non-standard way (nesting inputs within labels) some frontend logic was introduced to listen for changes to these inputs, and add "selected" or "checked" classes to the corresponding label. Ultimately, modifying the means by which FFM renders inputs was beyond the scope of this PR, so a javascript solution was utilized. 
Early on it was suggested that Sequoia should introduce a new "separate step" …
=> feature: Form Field Manager inputs are styled in Sequoia form template

src/Views/Form/Templates/Sequoia/Sequoia.php, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4727
This PR introduces styling for login/registration fields within the Sequoia form template checkout process, as they appear to users who are not logged in. Previously, when a user was not logged in they were shown login/registration fields are were not styled consistently with the Sequoia form template. Through a combination of css and js, these fields are now styled correctly, regardless of what registration fields setting the site admin has selected.
Initially, it was suggested that these fields should be rebuilt to match designs presented in the Figma boards for the Sequoia template. Upon further investigation and discussion, it was decided that a more time effective approach would be to simply style the existing fields and use javascript to minimally impact markup.
This …
=> fix: login fields are now styled in Sequoia template

includes/admin/class-give-welcome.php
Resolves #4746 
Update add-ons tab link to `https://givewp.com/addons/?utm_source=welcome-screen&utm_medium=getting-started`
=> add-ons tab of the welcome screen link givewp.com/addons

includes/gateways/manual.php, includes/gateways/paypal-standard.php
Resolves #4753 
This PR prevents gateway help content from appearing inside Legacy forms when the PayPal gateway is selected. It also addresses a related bug whereby help content appeared in Legacy forms when the test/manual gateway was selected.
Previously, these gateways relied on helper methods to determine if the current form is using the Legacy form tempalte. With the introduction of the FormUtils helper facade, these methods became unsupported. This PR replaces these unsupported methods with calls to the new FormUtils helper class, enabling gateways to properly check if the current form is using the Legacy form template. 
This PR affects the manual and paypal-standard files in the gateways directory. These files include a handful of global functions related to each gateway's …
=> fix: paypal help content no longer appears in legacy forms

src/Views/Form/Templates/Sequoia/Sequoia.php, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/css/recurring.scss
Resolves #4732
This PR introduces styling to that makes inputs and copy associated with the Gift Aid addon consistent within the Sequoia form template.
Because Gift Aid copy/fields are placed within payment gateways, it was necessary to move toward making input styles for the Sequoia form template more generic (previously, an additional stylesheet would be introduced for each addon). For this reason, the PR lightly touches some existing styles relating to other addons (only where greater specification was necessary). 
This PR affects the Sequoia assets folder, and the Sequoia template class.
Setup the Gift Aid addon (involves setting your currency to Pounds Sterling and base location to UK), then enable Gift Aid for your form. Try several different Payment Gateways. Does the Gift Aid …
=> Gift Aid addon is styled in Sequoia form template

includes/gateways/stripe/includes/admin/admin-helpers.php, includes/gateways/stripe/includes/class-give-stripe-gateway.php, includes/gateways/stripe/includes/deprecated/deprecated-functions.php, includes/gateways/stripe/includes/give-stripe-helpers.php
This PR resolves https://github.com/impress-org/give-recurring/issues/948 and supports PR https://github.com/impress-org/give-recurring/pull/949
We deprecated a function which is no longer in use `give_stripe_is_checkout_enabled`
=> fix: unable to process recurring donations via onpage stripe credit card fields #948

assets/src/js/frontend/give-stripe-becs.js, includes/gateways/stripe/includes/give-stripe-helpers.php, includes/gateways/stripe/includes/payment-methods/class-give-stripe-becs.php
This PR is related to the correction for #4742 
- includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
- includes/gateways/stripe/includes/give-stripe-helpers.php
- includes/gateways/stripe/includes/payment-methods/class-give-stripe-becs.php
- assets/src/js/frontend/give-stripe-becs.js
=> fix: embedded credit card fields are styled consistently with Sequoia form template #4742

src/Form/LoadTemplate.php, src/Views/Form/Templates/Sequoia/assets/js/form.js
I notice that I was not able to donation receipt after payment and I found that reason was that the referer URL contains a trailing slash. To fix this issue I removed trailing slash from the referer and success page URL before comparison.
I also found a javascript related issues. a piece of code warning even if the donor was on donation form but we expect it to run only on that view. I added an update condition to fix the issue.
In this pr, I also removed WordPress default head related functions which we do not need.
I tested this pr by processing a donation.
=> show receipt after payment 

includes/country-functions.php
Resolves #4773 
I found that we do not have a country locale setting in `give_get_country_locale` function which causes of showing default state field. I added the `state` configuration for `Monaco` country to hide the default state field.
It will affect  array list in `give_get_country_locale` function.
As you can see screenshot we will not see state field as a required field in the donation form and we will able to process donation without any error.
=> update Monaco country state configuration to hide state as required field

includes/class-give-email-access.php, includes/class-give-session.php
Resolved #4729 
I found that we are not initializing sessions for authorized donors and for some reason donor was not able to see errors when authorized with WP user credential or email. I updated logic to start a donor session in both circumstances.
Main changes you can see in the following commits.
https://github.com/impress-org/givewp/commit/d6ba9f4eaf19e9ecb4b24b11dd072fefc7c3f3b2: starting donor session when donor authorized with email.
https://github.com/impress-org/givewp/commit/7d0916d2521ae7ee71bc5baccf81d8b0d9794f39: starting a donor session when donor authorized with WP user credentials.
I tested this pr with https://github.com/impress-org/give-recurring/pull/940 by updating the subscription amount.
=> authorized donor   able to see errors

src/Views/Form/Templates/Sequoia/assets/css/feerecovery.scss, src/Views/Form/Templates/Sequoia/assets/css/ffm.scss, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/css/newsletter.scss, src/Views/Form/Templates/Sequoia/assets/css/recurring.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4767 
This PR introduces a handful of style and functionality improvements to make Google Pay and Apple Pay gateways more compatible with the Sequoia form template. Previously, when a user selected these gateways, they would be shown both an Apple/Google pay link and the Donate Now button, which created confusion. This PR hides the Donate Now button when Apple or Google Pay gateways are open, so the user is only shown once button to process their donation. The PR also sets up brand icons for Google Pay and Apple Pay.
For testing purposes, a live demo of the changes introduced by this PR can be found here: https://livegive.wpsteward.com/donations/homeless-outreach-fund/
The PR primarily affects Sequoia form template assets (particularly form.js).
Enable/disable the Apple and …
=> fix: Apple/Google Pay gateways are now compatible with Sequoia form template

includes/admin/forms/class-metabox-form-data.php, src/Form/Template/LegacyFormSettingCompatibility.php
This pr add logic to migrate old form setting when someone opens old form edit admin page the first time.
issue detail: https://givewp.slack.com/archives/C0FAGC83C/p1592293217047400
I tested this by visiting the old donation form edit page.
=> migrate old form setting in favor of legacy from template

src/Views/Form/Templates/Sequoia/assets/js/form.js
Previously, when an admin setup different fee recovery options for specific gateways, the Fee Recovery checkbox loaded within each individual gateway. This hotfix ensures that every time a gateway is loaded, if a Fee Recovery checkbox is present, it is moved below the donation amount buttons in the "choose amount" step. Additionally, checked/unchecked status of the Fee Recovery option is persisted even as a user changes their selected gateway.
This PR affects how the Multi-Step form template is rendered, specifically moving the Fee Recovery opt-in checkbox so that it appears consistently beneath the Choose Amount step.
_The following conditions have been tested in my local install. Use this list for reference of known possible configurations this PR impacts._
With the Fee Recovery addon …
=> hotfix: Fee Recovery option consistently appears below donation amount buttons

src/Form/LoadTemplate.php
Resolves #4804 
This pr add logic to prevent styles and scripts from the theme in embedded form iframe.
This PR will affect the list of scripts and styles which load in form iframe.
=> do not load styles and scripts from theme in embedded form iframe

src/Form/LoadTemplate.php, src/Helpers/Form/Template/Utils/Frontend.php
Resolves #4805 
This PR fix issue related to donation form preview in preview mode.
This pr affect form rendering in preview mode (form set to draft) when form template set to multi-step form.
=> new form  preview  with Sequoia template render successfully

src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4810 
This PR improves styling of the donation amount, so that it is consistent regardless of whether the "custom amount" setting is enabled. The PR also introduces frontend logic to programmatically set the number of grid columns used to display amount buttons based on the total number of buttons. 
Previously, when an admin disabled the "custom amount" setting, the donation amount styling would break and was rendered with default GiveWP styles. This PR refactors the styles applied to the donation amount input field, so that they also apply to the donation amount div (when it is not an input). In testing this feature, it also became apparent that for the best user experience, the number of columns that buttons are rendered in should change based on the total number of buttons. …
=> fix: donation amount styles no longer break when the "custom amount" setting is disabled

includes/admin/forms/class-metabox-form-data.php, src/Form/Template/LegacyFormSettingCompatibility.php
This PR prevents PHP notice which occurs because of a lack of parameter existence validation.
This pr effect logic which helps to migrate old form setting  to make it compatible with a legacy form template.
=> prevent php notices on new form edit page

src/Views/Form/Templates/Sequoia/optionConfig.php, src/Views/Form/Templates/Sequoia/sections/introduction.php
Resolves #4812
I removed the default field value for the "Headline" field because we have a fallback in place should one not be provided.
=> Fixes the default headline value for the new form template in 2.7.0

assets/src/js/plugins/form-template/iframe-content.js, assets/src/js/plugins/form-template/parent-page.js, assets/src/js/plugins/form-template/utils.js, src/Views/Form/Templates/Sequoia/Actions.php, src/Views/Form/Templates/Sequoia/optionConfig.php
Resolves #4815 
This PR improves frontend logic so that the form template loader is only shown when a 'beforeunload' event originates form within the form template iframe. Previously, the form template loader was displayed anytime the 'beforeunload' event was fired, including when the fired by the parent iframe. This resulted in unexpected behavior, whereby the form template loader would appear when a user clicked on a link in the parent page. 
This PR affects the form template rendering logic, specifically logic around ensuring that the form loader is only displayed when a 'beforeunload' event is fired from within the form template iframe.
=> fix: Form Template loader now only appears when loading is triggered from within Form Template iframe

includes/gateways/stripe/includes/admin/admin-helpers.php
As you can see in the screenshot, this function used in multiple places in addons, so it will be a small quick fix to improve performance.
This pr changes only limited to `give_stripe_is_any_payment_method_active` function.
I think it is a minor change. By reading code you can guess that it will not break any existing functionality and also no need test.
=> get stripe payment method list outside of loop to improve performance

includes/install.php
Resolves #4825
I find out that plugin activation hooks fire before the initialization of embed form custom route which causes of custom route does not save in the database. I updated logic to setup route on plugin activate and fresh install.
This pr changes limited to `give_run_install` function which fires either on plugin activation or fresh install.
=> setup embed form custom route on fresh site

includes/gateways/stripe/includes/filters.php, includes/gateways/stripe/includes/give-stripe-helpers.php
Resolves #4820 
If no Stripe Account is connected we were causing a PHP Notice to display because `give_stripe_form_add_data_tag_keys()` is using `give_stripe_get_connected_account_id()` which was attempting to pass an non-existent array key.
- Fresh Installs
- Stripe
=> Fix PHP Notice on fresh install with 2.7.0

src/Views/Form/Templates/Sequoia/optionConfig.php, src/Views/Form/Templates/Sequoia/sections/introduction.php
This pr improve logic to assign default form heading for form modal. When discussing the issue with @henryholtgeerts I find out that I pointed him to the wrong file. Default heading logo must be updated in `src/Views/Form/Templates/Sequoia/optionConfig.php`
Related: https://github.com/impress-org/givewp/pull/4813
Discussion: https://givewp.slack.com/archives/C0FAGC83C/p1592421291031300
This PR affects default form heading logic which runs in WP Backed when creating a new form or editing an existing form.
=> improve default donation form heading logic

includes/admin/give-metabox-functions.php
Resolves #4824 
This PR replace `[ --> _` and `] --> {empty string}` symbols from `wp_editor` field id to suppress PHP warnings. 
Change is limited to `give_wysiwyg`. My only concern that if id change for a setting field then style or javascript code can be affected but I did not notice in our core codebase or addon any use of the `WYSIWYG` field with an id which contains `[ ]` bracket, so I think this change will not break any existing functionality.
=> prevent wp_editor related PHP notices when save or open form edit page

includes/admin/upgrades/upgrade-functions.php
@DevinWalker reported an issue about a PHP notice on a fresh install:
```
[18-Jun-2020 18:32:11 UTC] PHP Notice:  Undefined property: wpdb::$donationmeta in /Users/devinwalker/Local Sites/freshtest/app/public/wp-includes/wp-db.php on line 647
```
The automatic upgrade must not run on a fresh install but the system works like that only. To resolve the issue I added a condition to prevent code from running on fresh install which causes PHP warning.
Discussion: https://givewp.slack.com/archives/C0FAGC83C/p1592505352032600
Code changes limited to `give_v270_upgrades` function and it affects plugin fresh install and upgrade process.
=> prevent php notice on fresh install

src/Form/LoadTemplate.php
Resolves #4830
This PR ensures that the 'plupload-handlers' script is able to be enqueued in the Form Template iframe, so that forms using FFM upload fields are operational, and do not log any JS errors. Previously, when a form used FFM to add an upload field, it would log an error the JS console, and the upload button would not function. 
This PR affects the Form Template loading logic, specifically with regard to which scripts are able to be enqueued. 
WIth FFM enabled, create a new form with an upload field. Activate the Multi-Step form, and view the form from the frontend. Open the browser console.
=> fix: Form Template no longer logs plupload error

includes/forms/widget.php
Resolves #4840 
This patch adds a condition which prevents excerpt to print for non legacy forms.
This pr also fixes #4841. I already explained fix here: https://github.com/impress-org/givewp/issues/4841#issuecomment-646748741
Changes in this patch are limited to `Give_Forms_Widget::widget`.
=> show excerpt in widget only for non legacy form

src/Views/Form/Templates/Sequoia/Sequoia.php, src/Views/Form/Templates/Sequoia/assets/css/feerecovery.scss, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/css/newsletter.scss, src/Views/Form/Templates/Sequoia/assets/css/recurring.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4838 
This PR introduces styles for the Terms and Conditions agremeent checkbox, and moves the checkbox below all payment gateways. Previously, when the term and conditions setting was enabled on a form using the Multi-Step form template, the checkbox was unstyled and loaded inside each individual payment gateway. 
This PR affects frontend styles and form rendering logic of the Multi-Step form tempalte, specifically regarding the presentation of the "Terms and Conditions" checkbox.
Enable Terms and Conditions for a form using the Multi-Step form template.
=> fix: terms and conditions checkbox is now styled in Multi-Step form template

src/API/Endpoints/Reports/AverageDonation.php, src/API/Endpoints/Reports/FormPerformance.php, src/API/Endpoints/Reports/Income.php, src/API/Endpoints/Reports/IncomeBreakdown.php, src/API/Endpoints/Reports/TopDonors.php, src/API/Endpoints/Reports/TotalDonors.php, src/API/Endpoints/Reports/TotalIncome.php, src/API/Endpoints/Reports/TotalRefunds.php, src/Form/LoadTemplate.php
Resolves #4826 
This PR resolves an incorrect variable reference in the AverageDonations endpoint class that caused PHP errors to be logged every time a user visited the Reports page. Additionally, this PR refactors other endpoints to ensure consistent naming conventions and remove redundant code.
This PR affects Report generating logic, specifically how the AverageDonation endpoint processes payment objects to determine average donations for a period. The PR also refactors a number of other endpoints to ensure that all endpoints use the consistent "paymentObjects" variable name, to avoid the type of mistake/oversight that caused this issue. In the process of updating varaible references, certain code also became redundant, and was removed.
=> fix: PHP errors no longer logged on Reports page

src/Form/Template.php, src/Views/Form/Templates/Sequoia/Sequoia.php, src/Views/Form/Templates/Sequoia/sections/introduction.php, src/Views/IframeView.php, templates/shortcode-form-grid.php
Resolved #4844 
This patch will add logic to show fallback values correctly for heading, description, and image in form grid.
Changes of this patch are limited to `Template`  class, `Sequoia` class, and default form grid template.
=> Form Grid Block handle heading, description and featured image correctly for any form template

includes/admin/payments/view-payment-details.php
Resolves #4714 
Donor Details meta box on the Donation detail screen
Create a test donation, then go to Donors screen and delete the donor without deleting all associated donations and records. Now go to Donations screen and view donation payment details. Donor name and email should be displayed.
=> fix: #4714 View payement detail of a deleted Donor

assets/src/js/plugins/form-template/utils.js
Resolves #4847 
This PR introduces frontend logic to ensure that when a donation is processed, the receipt page is scrolled into the viewport. Previously, when a donation processed, if the payment form was especially long (had multiple gateways or fields) it meant that a user would scroll down to the "donate" button, then have to manually scroll up to see the receipt when it loaded. This PR ensures that the viewport is autoscrolled when the receipt appears.
This PR affects the frontend javascript logic for frontend forms, specifically causing the viewport to scroll so that the top of the receipt is in view when it loads. 
Setup a form with multiple gateways/additional fields (eg enable "company" field).
=> fix: receipt now scrolls into view after processing donation

includes/admin/forms/class-metabox-form-data.php, src/Form/LoadTemplate.php, src/Helpers/Form/Template/Utils/Frontend.php, src/Helpers/Form/Utils.php, src/Route/Form.php, src/Views/IframeView.php
Resolves #4850 
In this pr, we added logic to disable `Donate Now` button when donation form renders in wp backed.
This pr mostly affects `iframeView.php`.
=> prevent live donation in WP backend

includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
Resolves #4855 
I find out that default value was not to `enabled` when accessing settings which cause of hiding other settings.
This pr will affect stripe setting registration code.
=> show  SEPA Mandate acceptance text setting on fresh install

includes/admin/class-give-welcome.php, includes/admin/settings/class-settings-gateways.php, includes/admin/settings/class-settings-general.php, includes/gateways/offline-donations.php, includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
Working through more of #4832 
The settings > general tab
the Settings > Payment Gateways tab
the Offline donation instructions.
Test visually in the settings page and check for grammar/typos.
=> Inline docs are better

src/Controller/Form.php, src/Helpers/Form/Utils.php, src/Route/Form.php
Resolves #4865 
I find out that `name` query var in custom rewrite URL was the cause to set `is_404` to `true`. I rename it to `url_prefix` to resolve the issue.
**Note: you have to reset permalink before testing this pr.**
This pr only rename query var `name --> url_prefix`.
=> resolve conflict with "All 404 Redirect to Homepage" plugin

src/Controller/Form.php, src/Views/Form/Templates/Sequoia/assets/css/form.scss
Resolves #4866 
I find out that `WeGlot` plugin starts an output buffer (as you can see in the screenshot) which prints output on the screen when WordPress ran a  [wp_ob_end_flush_all](https://github.com/WordPress/WordPress/blob/5a60d4b3b00e0a2406c709a0d798e201cb46f347/wp-includes/default-filters.php#L354) function on `shutdown` hook.
As per my research, I did not find the best way to resolve this conflict but I think it will be good to hide everything which is not output for Give donation form. As you can see in pr code I add a CSS to hide all DOM element in `body` whose `id/class` does not start with `give`
This pr affect donation form view.
=> resolve WeGlot conflict with new form template in 2.7

assets/src/js/admin/reports/components/mini-chart/index.js, assets/src/js/admin/reports/components/mini-chart/utils/index.js, src/API/Endpoints/Reports/AverageDonation.php, src/API/Endpoints/Reports/TotalDonors.php, src/API/Endpoints/Reports/TotalIncome.php, src/API/Endpoints/Reports/TotalRefunds.php
Resolves #4766
This PR introduces frontend logic to ensure that trend percentages are rounded appropriately, based on the size of the number and a maximum number of significant digits. Previously, when the server provided a large number as the potential trend percentage (sometimes in the thousands) it was still displayed with point values, despite adding little tangible value to users and further cluttering the mini charts at the top of the Reports page. Now, when a large value is returned, it will include no point values, while small values do maintain appropriate point values. This improvement draws on work from the GiveIO reports project to tackle the same problem, and utilizes the numberToDigits function. 
This PR impacts frontend rendering logic, specifically how trend percentages …
=> fix: trend percentage rounding is now based on significant digits

src/Views/Admin/DashboardWidgets/Reports.php
Discussion: https://givewp.slack.com/archives/C0FAGC83C/p1593484441049500
@JasonTheAdams  reported that the report widget is not loading correctly on dashboard in Give `2.7.0`. I find out that we did not update script versions which cause or load older script on a few hosts who cache script and style files. 
This pr update script and style version to plugin version which will auto burst cache on every plugin release.
This will only affect script registration logic.
=> set script version to plugin version to load fresh file on every plugin release

templates/shortcode-form-grid.php
Resolves #4877 
I find out we are using the default template `legacy` if form template meta missing from the old donation form. This pr update logic to handle form template default value.
This Pr affect from grid shortcode output.
=> fix: set default template to legacy if missing

give.php, src/PaymentGateways/PayPalCheckout/PayPalCheckout.php, src/PaymentGateways/PaymentGateway.php, src/ServiceProviders/PaymentGateways.php, src/ServiceProviders/ServiceProvider.php
This PR's ultimate goal is to register the PayPal Checkout payment gateways. It's pretty simple as that's all its goal is.
To do this, it also introduces a Service Provider framework within GiveWP. This introduces a means of registering services with the Service Container (i.e. the `Give` class). It also gives means of bootstrapping services efficiently. The gateways, for example, will only be instantiated and set up in the appropriate context, and the `PaymentGateways` provider handles this.
It's _super_ tempting to do more refactoring in `Give` to handle singletons better, but until it's necessary I will refrain. If it seems like it should happen, then we'll do it on the `develop` branch and merge that branch into this one (or another PR in this epic).
Resolves #4887 
Doesn't affect …
=> Add the PayPal Checkout payment gateway

src/Views/Form/Templates/Sequoia/assets/css/feerecovery.scss, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4882
This PR introduces some form rendering logic and styles for the Multi-Step form template to ensure that forms using a single gateway are displayed consistently with those using multiple gateway options. Previously, when an admin created a form with only one gateway option the fee recovery opt-in widht was wrong, spacing around the gateway fields was awkward, and the "Donate Now" button was aligned left, rather than centered. This PR resolves all these issues, while testing to make sure that forms displaying multiple gateways continue to work as expected.
This PR affects the frontend form rending logic of the Multi-Step form, specifically how payment step is displayed when only one gateway is enabled.
In a form using the Multi-Step form template, enable only one gateway. …
=> fix: single gateway styles are now consistent

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4879 
This PR improves frontend form rendering logic in the Multi-Step form template so that errors generated by the Give Stripe addon are handled correctly. Previously, when a set Google Pay or Apple Pay as the default payment gateway, an error inacureately appeared at the top of the form indicating to users that they did not have a Google/Apple pay account setup, and would not be able to donate - even when the donation would still process successfully. This issue was caused by JS in the Multi-Step form template, which moved errors to the top of the form (as expected), but did not move the wrapper around the errors (which the Give Stripe addon uses to identify and remove errors). This PR introduces a fix to ensure that wrappers associated with the Give Stripe addon are moved to …
=> fix: Stripe errors now hidden correctly for default gateways

includes/admin/upgrades/class-give-updates.php
Resolves https://github.com/impress-org/givewp/issues/4900
I find out that we are using `Give_Cache_Setting` class to get cache value which updates after any [whitelist options ](https://github.com/impress-org/givewp/blob/b2f77d5a096f13a47a3fabd95fed3310e123ab96/includes/class-give-cache-setting.php#L58) add/update/delete. I think a few servers hijack action fired inside this function and which cause of cache settings does not flush.  As per discussion with @JasonTheAdams and @DevinWalker It is good to use WordPress core function in this case to prevent any future conflict like this.
This pr affect admin redirect logic which setup after database upgrade completes in background and admin, was not on the database upgrade page.
We are unable to test it because only a few people get affected …
=> upgrading database will not break WP admin interface

src/Views/Form/Templates/Sequoia/assets/css/form.scss
Resolves #4899 
This PR introduces mobile breakpoint styles for the Terms and Conditions opt-in, so that the label and "Show Terms" button stack on mobile. Previously, when a user viewed a Multi-Step form with Terms and Conditions enabled, the Terms and Conditions opt-in was not responsive on mobile.
This PR affects frontend styles of the Multi-Step form template, specifically responsive styling of the Terms Agreement checkbox.
Enable Terms and Conditions for a form using the Multi-Step form template. Set the Terms and Conditions label to something longer than the default "Agree to Terms".
=> fix: terms and conditions agreement is now responsive

src/Views/Form/Templates/Sequoia/Sequoia.php, src/Views/Form/Templates/Sequoia/assets/css/form.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #4888 
This PR introduces frontend form rending logic and styles to the Multi-Step form template to ensure that the anonymous donation checkbox is visible when enabled. Previously, when an admin enabled anonymous donations for a form using the multi-step form template, the markup for the checkbox would render, but the field itself was not visible.
This PR affects form rending logic in the Multi-Step form, specifically regarding how the Anonymous Donation checkbox is displayed, when Anonymous Donations are enabled.
In a form using the Multi-Step form template, enable Anonymous Donations.
=> fix: anonymous donation opt-in is now visible in Multi-Step forms

src/Views/Form/Templates/Sequoia/optionConfig.php
Adds a link to the email tags doc. Resolves https://github.com/impress-org/givewp/issues/4906.
=> Add link to the email tags doc

src/Views/Form/Templates/Sequoia/optionConfig.php
Resolve #4909
This is minor fix to update `you --> your`
thank you page placeholder and default message.
=> fix typo in thank you page default message

assets/src/js/admin/onboarding-wizard/app/index.js, assets/src/js/admin/onboarding-wizard/app/style.scss, assets/src/js/admin/onboarding-wizard/index.js, includes/admin/class-give-welcome.php, includes/admin/settings/class-settings-advanced.php, includes/install.php, readme.txt, src/Views/Admin.php, src/Views/Admin/Pages/OnboardingWizard.php, src/Views/Admin/Pages/templates/onboarding-wizard-template.php, webpack.config.js
Resolves #4915 
This PR scaffolds the Onboarding Wizard page, which is now shown to users on first install, or at the admin url `wp-admin/?page=give-onboarding-wizard`. Previously, on a new install users were directed to the Welcome Page (at `wp-admin/?page=give-getting-started`). This PR instead directs users to the new Onboarding Wizard, and loads necessary styles/scripts.
This PR introduces the OnboardingWizard class in the src/Views/Admin/Pages namespace. Inline with other admin page view classes, the  OnboardingWizard class includes an init() method, which is called in the Admin views load_pages function. The init() method registers a dashboard page ('give-onboarding-wizard), outputs the wizard template, and enqueues necessary scripts/styles to load the onboarding wizard. …
=> Onboarding wizard is now scaffolded

src/API/Endpoints/Reports/AverageDonation.php, src/API/Endpoints/Reports/Endpoint.php, src/API/Endpoints/Reports/Income.php, src/API/Endpoints/Reports/IncomeBreakdown.php, src/API/Endpoints/Reports/TotalDonors.php, src/API/Endpoints/Reports/TotalIncome.php, src/API/Endpoints/Reports/TotalRefunds.php
Resolves #4883 
This PR improves the Reports Endpoint base class, and standardizes interval logic across Reports endpoints to ensure that payment objects are consistently queried across all endpoints. Previously, when a user visited the Reports page, it failed to consistently factor renewal donations into totals for the queried period. This PR resolves that issue, and ensures that all endpoints are using consistent logic to query intervals between the specified period range.
This PR affects Reports Endpoints querying logic, specifically with regards to how Endpoints pass start and end dates to the Give_Payments_Query object, and how Endpoints determine intervals to query within the greater specified period range.
Using an install of GiveWP with processed Renewal donations, visit the …
=> fix: renewal donations are now factored into Reports

src/API/Endpoints/Reports/AverageDonation.php, src/API/Endpoints/Reports/FormPerformance.php, src/API/Endpoints/Reports/Income.php, src/API/Endpoints/Reports/IncomeBreakdown.php, src/API/Endpoints/Reports/PaymentMethods.php, src/API/Endpoints/Reports/TopDonors.php, src/API/Endpoints/Reports/TotalIncome.php
Resolves #4574 
This PR improves functionality throughout various Reports endpoint to ensure that amounts which have already been sanitized are not being re-sanitized, causing frontend display errors when using ',' as the decimal separator. Additionally, the PR improves rounding logic in the Average Donation endpoint, to ensure that amounts are rounded to the decimal place specified in the currency settings.
Previously, when using a ',' as the decimal separator for a currency, it produces inconsistent errors in terms of decimal placement for totals displayed on the Reports page. Furthermore, using a ',' for the decimal separator resulted in consistent misplacement of the decimal in the Average Donations totals. This PR resolves both of these issues.
This PR affects currency formatting …
=> fix: prevent decimal issues when using ',' as decimal separator

includes/misc-functions.php
Resolves #4464
I updated the `give_get_meta` filter to pass the correct param rather than a duplicate of another one already passed.
=> don't pass $meta_value twice and pass $meta_type rather for use

assets/src/css/admin/setting-license.scss
Resolves #4383 
Adds simple `height: auto` to the "Download Add-on" button so its height isn't too large.
Settings > Licenses
=> style to ensure button size is correct

src/Helpers/Hooks.php
Resolves #4938 
The targeted purpose for this PR is to provide a more memory efficient means of using WordPress hooks that also helps to organize our code.
Right now, every class that has hooks that need to be applied needs to be instantiated in order to have its hooks set up. This would be like leaving your house with everything you own _just in case_ you need anything while you're out. This provides a means of specifying the class and method to be called _if_ the action/filter ends up being used. So if the hook isn't used, the class isn't instantiated — which uses less memory.
This also gives us the ability to better centralize our hooks. So instead of hooks being scattered through hundreds of classes, they can instead be primarily set up within the Service Providers. So this...
```php …
```
=> Add Hooks helper for creating auto-instantiated hooks

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5004
If you place a form on a page without the first step, the page auto-scrolls to the form location.
This PR solves this issue by disabling initial auto-focus on the page load only if the 1st step is disabled.
Multi-step form auto-focus
1. Add multi-step form
2. Disable the 1st step
3. Navigate to the donation page
4. Refresh the page couple of times ( CTRL/CMD + F5 )
=> fix: Multi-step forms without 1st step should not auto-focus on page load #5004

assets/src/js/admin/onboarding-wizard/components/donation-form/index.js
Resolves #4987
Programatically hides the Test Mode notice when the iframe is loaded. I took this approach assuming that the iframe didn't have context of its location and was better for the Wizard to know about the iFrame than for the iFrame to know about the Wizard.
Only effects the Onboarding Wizard Form Preview and not the public display of the form.
=> Onboarding form preview does not display Test Mode notice

src/PaymentGateways/PayPalCommerce/DonationProcessor.php, src/PaymentGateways/PayPalCommerce/Models/PayPalOrder.php
Resolves #4999 
I find out that PayPal order id is important to keep in database and can be help in the future to trace order details if the seller needs.
This PR affect donation meta and note. For the future purpose, we store order id to donation meta and attach order id to donation note with PayPal Payment id.
Process donation with a smart button or advanced card field. Check meta key `_give_order_id` in `wp_give_donationmeta` table and also review donation note on donation details page.
=> Store PayPal order id to donation meta

includes/forms/template.php
Give metadata (i.e. keys prefixed with `_give_`) is almost always read with `give_get_metadata`. That means if you need to modfiy any of this, you can do it all with the `give_get_meta` filter. There is one place where `_give_form_goal_achieved_message` is read with `get_post_meta` instead, which means you need another filter for just this one place. I've changed this to be consistent (because there doesn't seem to be a reason why it shouldn't be).
You can now modify `_give_form_goal_achieved_message` like other Give fields in the `give_get_meta` filter.
Define a `give_get_meta` filter like this:
```php
function test($meta_value, $id, $meta_key) {
if ($meta_key …
```
=> Use give_ function to read form metadata

assets/src/js/admin/onboarding-wizard/app/index.js, assets/src/js/admin/onboarding-wizard/utils/index.js, src/Onboarding/Helpers/FormatList.php, src/Onboarding/Wizard/Page.php, tests/src/Onboarding/Helpers/FormatListTest.php
Resolves #5040 
Selected Features and Add-ons are pre-loaded into the initial state when the Wizard is re-launched.
- Adds new util `getFeaturesEnabledDefault()`.
- Adds new util `getAddonsSelectedDefault()`.
- Extracts a higher-order function to extend the `FormatList` helper.
- Injects a `SettingsRepositoryFactory` into the `Wizard/Page` to `get` selected add-ons.
- Builds a `features` array from post meta.
-   [x] Tests included
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code …
=> Onboarding selected Features and Addons are now pre-loaded

assets/src/js/admin/onboarding-wizard/app/index.js, assets/src/js/admin/onboarding-wizard/app/steps/location/index.js, assets/src/js/admin/onboarding-wizard/app/store/actions.js, assets/src/js/admin/onboarding-wizard/app/store/reducer.js, assets/src/js/admin/onboarding-wizard/components/select-input/index.js, assets/src/js/admin/onboarding-wizard/utils/index.js
Resolves #4980 
This issue introduces a disabled loading state to the State/Province select input when it is fetching options from the API. Previously, when a user updated their country selection, there was no indication that the state/province options were being updated. Additionally, this PR implements logic that hides a SelectInput component if fewer than 2 options are available to it.
This PR affects frontend rendering logic for the SelectInput component in the Onboarding Wizard, and specifically introduces a loading state that is displayed on the State/Province input of the "Location" step.
-   [x] Keyboard accessible
-   [x] Screen reader accessible
-   [ ] Relevant `@since` tags included in …
=> State/Province input now uses loading state when fetching options from API

assets/src/js/admin/onboarding-wizard/app/steps/features/index.js
Resolves #
The `t` in `don't` was escaped instead of the apostrophe.
=> Fix typo in third step of wizard subtitle.

src/Onboarding/Setup/PageView.php, src/Onboarding/Setup/templates/index.html.php
#5015
If Stripe is configured, hides PayPal (and vica versa).
This is based on the assumption that the new user is only setting up one payment gateway, which is a decision made to focus and simplify the Setup Page.
=> Setup shows only the gateway being configured.

assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js, assets/src/js/admin/onboarding-wizard/app/steps/donation-form/style.scss, assets/src/js/admin/onboarding-wizard/components/button/style.scss, assets/src/js/admin/onboarding-wizard/components/donation-form/index.js, assets/src/js/admin/onboarding-wizard/components/donation-form/style.scss, assets/src/js/admin/onboarding-wizard/components/step-link/style.scss, assets/src/js/admin/onboarding-wizard/components/step-navigation/style.scss, assets/src/js/admin/onboarding-wizard/components/step/index.js, assets/src/js/admin/onboarding-wizard/components/step/style.scss, assets/src/js/admin/onboarding-wizard/components/wizard/style.scss, src/Onboarding/Wizard/templates/form-preview.php
Resolves #5045
This PR improves the responsive behavior of the Onboarding Wizard on smaller desktop displays. Notably, the PR fixes the navigation bar to the top of the screen, causes the entire step to scroll when squished, equips the DonationForm component to resize when the embedded form resizes, and fixes the Form Preview step content to the center of the screen.
This PR affects frontend rendering logic of various Onboarding Wizard components (primary Step, StepNavigation, Wizard and DonationForm), and adds JS to the form-preview.php template to pass updates about changes in body height to the DonationForm component.
Scrolling demo:
Line removed from step navigation after last step:
-   [x] …
=> Onboarding Wizard is now responsive for small desktop displays

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5017
If you click away from a donation form block in the Gutenberg editor, you can't access it again.
This PR solves the problem by adding an onClick event listener on the multi-step donation form which will dispatch an action ( Gutenberg state update - selected block ) when the user clicks on the form.
It might be that this PR is not the best solution, but I couldn't find anything related to this issue e.g. CSS prop pointer-events set to none.
Multi-step donation form block
1. Add a new page
2. Select donation form block
3. Click away from a donation form block.
4. Click again on a …
=> fix: make donation form block selectable in editor

includes/payments/class-payments-query.php
Resolves #4994 
Changing the comparison from `=` to `LIKE` will make the search show correct results when used multiple keywords.
The search functionality of donations.
**Before**
**After**
=> donations search now shows correct results with multiple keywords #4994

src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php, src/PaymentGateways/PayPalCommerce/RefreshToken.php, src/PaymentGateways/PayPalCommerce/Repositories/MerchantDetails.php, src/PaymentGateways/PayPalCommerce/ScriptLoader.php
Resolves #5061
I find out that client token plays a crucial role when load PayPal SDK on the frontend and client token expires when we reconnect PayPal account. To fix this issue I delete refresh token cron job and client token.
I added required param to get partner rest API query which required to process this request on connect server.
Steps to reproduce:
- Switch to the `epic` branch To test …
=> Donor will not see Resource ID notice when process donation with Advanced Card Fields

assets/src/js/admin/onboarding-wizard/components/wizard/index.js, assets/src/js/admin/onboarding-wizard/utils/index.js
Resolves #5072
Removes the `setStepFocus` utility so that the first element on each step is not auto-focused.
For each step, tabbing starts on the first element (which would have otherwise been auto-focused) - as expected.
=> Remove default selected state.

assets/src/js/admin/onboarding-wizard/app/steps/addons/index.js, assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js, assets/src/js/admin/onboarding-wizard/app/steps/donation-form/style.scss, assets/src/js/admin/onboarding-wizard/app/steps/features/index.js, assets/src/js/admin/onboarding-wizard/app/steps/introduction/index.js, assets/src/js/admin/onboarding-wizard/app/steps/introduction/style.scss, assets/src/js/admin/onboarding-wizard/app/steps/location/index.js, assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js, assets/src/js/admin/onboarding-wizard/app/style.scss, assets/src/js/admin/onboarding-wizard/components/button/style.scss, assets/src/js/admin/onboarding-wizard/components/card-input/style.scss, assets/src/js/admin/onboarding-wizard/components/card/style.scss, assets/src/js/admin/onboarding-wizard/components/dismiss-link/index.js, assets/src/js/admin/onboarding-wizard/components/dismiss-link/style.scss, assets/src/js/admin/onboarding-wizard/components/select-input/index.js, assets/src/js/admin/onboarding-wizard/components/step-link/style.scss, assets/src/js/admin/onboarding-wizard/components/step/style.scss, assets/src/js/admin/onboarding-wizard/components/wizard/index.js, assets/src/js/admin/onboarding-wizard/components/wizard/style.scss, assets/src/js/admin/onboarding-wizard/utils/index.js
Resolves #5068 
This PR addresses a punchlist of design loose ends associated with the Onboarding Wizard. See the affects and visuals sections below for a complete list, and representation of changes this PR covers.
Changes introduced in this PR:
- Consistent focus state for all inputs/elements (SelectInput, CardInput, Buttons, StepLinks, DismissLink)
- Focus state design improved to use dualtone green box-shadow (which ensures that focus state pops on Buttons)
- Focus state design improved to incorporate existing box shadows on Cards in CardInput
- Dismiss Setup Wizard link added to bottom of each step
- CardInput hover state modified to use a material inspired shadow to highligh, rather than setting border color
- HTML Entities in Country list are decoded
- Added padding below steps to …
=> Onboarding Wizard design loose ends are resolved

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5080
This issue resolves an error that surfaces when viewing the Multi-Step form from the Form Preview. Previously, when a form was loaded in the Form Preview step, it displayed all steps simultaneously. Now, it behaves as expected and without producing JS blocking errors.
This PR affects Multi Step form frontend rendering logic, specifically how it checks to see if it is being viewed from within the Gutenberg editor. Previously, it referenced the wp object, without first checking that the wp object is defined on the window.
-   [ ] Labels applied if …
=> Form Preview no longer renders all steps at once

assets/src/js/admin/onboarding-wizard/app/steps/addons/index.js, assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js, assets/src/js/admin/onboarding-wizard/app/steps/donation-form/style.scss, assets/src/js/admin/onboarding-wizard/app/steps/features/index.js, assets/src/js/admin/onboarding-wizard/app/steps/location/index.js, assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js
Resolves #5089 
This PR removes the Dismiss Link from all steps except the Introduction step, and clears up styles introduced to the Donation Form step meant specifically to style the Dismiss Link.
Step composition logic in the Onboarding Wizard app.
-   [x] Labels applied if docs are needed
=> Dismiss Link is now only present in the first step

assets/src/js/admin/onboarding-wizard/components/donation-form/index.js, src/Onboarding/Wizard/templates/form-preview.php
Resolves #5087
This PR introduces logic to hide the Social Sharing section of the receipt in the Form Preview. In order to do so, some additional logic was added to the Form Preview frontend template to send a message to the parent window whenever the Form's iframe is loaded, which occurs first when the form is loaded, then again when the receipt is loaded. Using PostMessage to send this event to the parent window enables the DonationForm component to hide the Social Sharing div when the receipt loads, and the test notice div when the form loads.
-   [ ] Labels …
=> Social sharing section is now hidden in Form Preview

src/Onboarding/Setup/Handlers/StripeConnectHandler.php
Related #4868
Suppresses the deprecated notice thrown by the Stripe SDK when connecting to Stripe from the Setup Page.
This does NOT address the issue when connecting to Stripe from the settings page.
=> Setup Page now connects to Stripe without a deprecated notice.

src/Helpers/Frontend/Shortcode.php
Resolves #5042
The current [method](https://github.com/impress-org/givewp/blob/3bb91d25819daf834d6f5212de48e9a1fe854810/src/Helpers/Frontend/Shortcode.php#L12) for extracting **give_receipt** shortcode from the post content, sometimes cannot extract the shortcode if the multiple shortcodes are being used ( i.e when using Divi page builder ). This PR solves this issue by using a regex pattern focused on **give_receipt** string which will be more efficient and possibly less prone to errors.
1. Install and activate Divi page builder plugin
2. Go to the Donation Success page and edit page with Divi …
=> fix: extract give_receipt shortcode from post content

src/Onboarding/Setup/Page.php
Resolves #5106 
This PR resolves a minor bug, whereby the Setup Page scripts were being loaded from the `src` directory, rather than the `dist` directory. This likely didn't show up in development, but in an actual build the `src` directory is removed - which caused errors on page load. This PR resolves those errors by enqueueing the script from the correct place.
Affects page rendering/script enqueueing logic for the Onboarding Setup Page.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code- …
=> Setup Page admin scripts now load from the dist directory

assets/src/js/admin/onboarding-wizard/components/wizard/index.js
Resolves #5074 
This PR prevents accidental unloading of the Onboarding Wizard (if a user accidentally backs out, presses refresh etc) by showing the user a browser modal alerted them that their changes may not be saved. The modal asks them to confirm their desire to navigate away from the Onboarding Wizard mid-setup.
The modal does not appear on the first or last steps. It does not appear on the first step because at this point users have not actually added any input to the Wizard. It does not appear on that last step because, at this point, all options have been configured. 
This PR affects frontend rendering logic of the Onboarding Wizard, specifically setting up window listeners that prevent unloading events from happening on all steps other than the first or last step.
-   [x] …
=> Users are now warned before accidentally leaving the Onboarding Wizard

includes/api/class-give-api-v2.php
Resolves #5114 
This PR resolves WP Errors which were logged for users when loading the block editor in WP 5.5. Specifically, the errors made reference to a failure on GiveWP's part to clarify a `permission_callback` when registering rest routes. These errors were first introduced in WP 5.5. In accordance with WP recommendations, these endpoints which are meant to be public now include `permission_callback`s which simply return true. 
This PR affects API route registration in the `Give_API_v2` class. In particular, it addresses the lack of a defined permission callback for a number of GiveWP core routes.
-   [ ] Relevant `@since` tags …
=> WP Errors are no longer logged when using the block editor

assets/src/js/admin/admin-setup.js, src/Onboarding/Setup/templates/index.html.php
Resolves #5124
The add-ons and getting-started row items were missing a class, which caused them to not be block linked by the JS script.
Also addresses console errors (unrelated) in the associated JS script.
=> Setup Page block links are fixed

assets/src/js/admin/onboarding-wizard/app/store/observers.js, assets/src/js/admin/onboarding-wizard/app/store/reducer.js
Resolves #5104
Sets the `body.style[ 'overflow-y' ]` to `scroll` to prevent shifting in viewport size when the preview form changes height.
I tried doing this for only the Preview step, but that created a shift when changing to and from the Preview step, which was actually more noticeable than the shifting that I was trying to address.
Note: This is applied on `GO_TO_STEP` after the introduction screen, because a visible scrollbar area in the introduction was very noticeable, so this isn't a simple CSS change.
Introduces `observeAction( action )`, which is used to act upon an action for side effects not directly related to state. My goal with this is to not clutter the reducer with non-state code, like DOM styling.
```js
// reducer.js
export const reducer = ( state, action ) => { …
```
=> Onboarding Wizard no longer changes width when the scrollbar is toggled.

CHANGELOG.md, assets/src/css/admin/forms.scss, assets/src/js/admin/admin-scripts.js, includes/admin/give-metabox-functions.php, src/Helpers/Form/Template/Utils/Admin.php
Resolves #5118
GiveWP's repeater fields toggle button didn't work in the latest version (5.5) of WordPress. 
The collapse feature didn't actually collapse the group anymore but rather the entire tabbed metabox.
Also, the metabox header was in another line. 
This issue is related to recent WP [changeset](https://core.trac.wordpress.org/changeset/48373) 
This PR solves the issue by changing the jQuery toggle selector name for the metabox toggle button and by re-adding removed button styles. 
Donation level repeater fields.
- …
=> fix: repeater fields in WP 5.5 should collapse and work like previous WP versions

assets/src/css/admin/setup.scss, src/Onboarding/Setup/templates/index.html.php, src/Onboarding/Setup/templates/sub-header.html
Resolves #5142
- Introduces a `sub-header` template for adding descriptive text to a section.
- Adds a sub-header for the Add-ons Section, to communicate that the list of add-ons is based on their selection from the Wizard.
- The sub-header renders conditionally, only if add-ons are selected.
Without any selected add-ons from the Wizard:
With add-on(s) selected from the Wizard:
=> Add sub header text for Add-ons Setup section.

src/Onboarding/Setup/templates/index.html.php
Resolves #5095
Add a note about testing Stripe and webhooks.
Related: https://github.com/impress-org/givewp/pull/5098#pullrequestreview-469620709
Note: There is a Stripe color change in a separate PR that isn't reflected here.
=> Configuring Stripe webhooks now has a note about test mode.

assets/src/js/admin/onboarding-wizard/utils/index.js
Resolves #5151
This issue addresses an error whereby HTML entities within state labels (in the State/Province input) were not being decoded. Using the decodeHTMLEntity utility already utilized to decode labels for other select inputs, this PR resolves the issue by decoding labels in both the default state list, and fetched state lists.
This PR affects state fetching logic associated with the State/Provinces input of the Onboarding Wizard.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-re …
=> HTML entities in State labels are now decoded

includes/install.php
Resolves #5155 
This PR ensures that during install, if the current version is already defined, the Setup Page and onboarding experience are disabled. On fresh installs, the Setup Page is still enabled by default.
This PR affects installation logic, in particular how non-fresh installs handle setting default values.
On an existing install of GiveWP, update to this PR. Check to see if Setup page is accessible via the Donations admin menu.
=> Setup Page is now disabled when updating GiveWP

includes/install.php
Resolves #5138
Removes Stripe as a default enabled gateway.
=> Stripe is no longer enabled by default.

CHANGELOG.md, includes/class-notices.php
Resolves #5181
The previously added admin notice animation has been removed.
~Note: This change re-exposes the admin notice flicker, but now the time to interactive is much shorter and reduces mis-clicks.~
Switching to `.show()` without a timeout covers the flicker with minimal disruption to the content.
Flicker (before before)
Animation (before) - content shift causing mis-clicks
**Show Toggle, All Forms** (after) - no flicker!
**Show Toggle, Add Form** (after) - Negligible content shift
=> Admin notices are no longer animated.

CHANGELOG.md, src/Onboarding/Wizard/FormPreview.php, src/Onboarding/Wizard/Page.php
Resolves #5187
Replaces `add_dashboard_page()` with `add_submenu_page()` which supports an "unattached" submenu item.
| --- | --- |
| ![empty-submenu](https://user-images.githubusercontent.com/10858303/91093861-037faa00-e628-11ea-8c77-1acabfcb1f19.png) | ![empty-submenu-fixed](https://user-images.githubusercontent.com/10858303/91093863-04184080-e628-11ea-825e-58090f226b8e.png) |
1. Checkout `develop`
1. Activate GiveWP plugin.
1. Hover over the "Dashboard" menu item
1. See empty space below "Updates" submenu item.
1. Switch to …
=> Onboaridng Wizard no longer shows empty submenu under Dashboard.

CHANGELOG.md, includes/gateways/stripe/includes/payment-methods/class-give-stripe-checkout.php
Resolves #5194
Trailing commas in function calls weren't added until PHP `7.3`, see [rfc/trailing-comma-function-calls](https://wiki.php.net/rfc/trailing-comma-function-calls).
This removes the trailing comma to support PHP `5.6`.
See #5194
=> Trailing comma in function call is removed for PHP 5.6 support

CHANGELOG.md, assets/src/js/plugins/give-api/notice.js
Resolves #5185
Implemented `wp.i18n.__` for translating common text in WordPress `>=5.5` with backwards compatibility for `commonL10n` for WordPress `<=5.4.2`.
Navigate to Donations -> Settings -> Licenses, add a license key and click "Activate License".
=> License activation is restored by resolving JS translation error.

src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php, src/PaymentGateways/PayPalCommerce/Repositories/PayPalAuth.php, src/PaymentGateways/PayPalCommerce/onBoardingRedirectHandler.php, src/ServiceProviders/PaymentGateways.php
~~PayPal has a known issue they're working on wherein an access token generated from the `authorization_code` grant type does not have the proper permissions to generate a Subscription. Unfortunately, this is the exact grant type used during the onboarding process.~~
~~This PR provides a workaround where it uses the client credentials retrieved during onboarding to replace the stored token details with a token generated from the `client_credentials` grant type. This token has the correct permissions.~~
After talking with Swati, it turns out that this is actually the _intended_ flow for gathering credentials. Apparently the token retrieved via the `authorization_code` grant is supposed to be limited to only retrieving the credentials. In fact, she was surprised we were able to use the …
=> Correct onboarding to store client credential authenticated token

CHANGELOG.md, assets/src/css/frontend/give-stripe.scss
Resolves #5206 
This PR resolves a minor style issue that occurred when admin opted to use the Stripe modal in Legacy Forms, on a site with German translation. Previously, when translated to German the "Cardholder Name" label was so long that it wrapped to a new line, which caused issues with the associated tooltip and looked bad. This PR increases the maximum width of the Stripe checkout modal to `425px` and sets a width of `90%`, to ensure that the modal is still responsive when viewed on mobile devices or inside a Multi-Step form iframe.
This PR affects styles for the Stripe Checkout modal. 
1. On 2.8.0 create a legacy form.
2. enable stripe checkout modal.
3. change the site language to German.
4. Ensure that the translations all download (Dashboard > Updates > Translations)
5. view …
=> On German installs, there is now enough room for all labels in the Stripe Checkout modal

CHANGELOG.md, src/Onboarding/Wizard/Page.php
Resolves #5210 
This PR resolves an issue whereby users who visited the Onboarding Wizard after previously dismissing the Setup Page (via the back button), were still being directed to the Setup Page despite it not being accessible to them. As a fix, this PR dynamically sets the setupUrl variable that is localized for the Onboarding Wizard to either send users to the Setup Page or to the All Forms page, depending on whether the Setup Page is enabled.
This PR affects localized variable logic for the Onboarding Wizard, specifically the url that users are directed to after completing or dismissing the Onboarding Wizard.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code …
=> If the Setup Page is disabled, Onboarding Wizard now directs users to the All Forms page

src/Controller/PayPalWebhooks.php, src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php, src/PaymentGateways/PayPalCommerce/Models/WebhookConfig.php, src/PaymentGateways/PayPalCommerce/PayPalCommerce.php, src/PaymentGateways/PayPalCommerce/Repositories/MerchantDetails.php, src/PaymentGateways/PayPalCommerce/Repositories/Traits/HasMode.php, src/PaymentGateways/PayPalCommerce/Repositories/Webhooks.php, src/PaymentGateways/PayPalCommerce/Webhooks/WebhookChecker.php, src/PaymentGateways/PayPalCommerce/Webhooks/WebhookRegister.php, src/PaymentGateways/PayPalCommerce/onBoardingRedirectHandler.php, src/ServiceProviders/PaymentGateways.php, src/ServiceProviders/Routes.php
Resolves #5176 
This PR greatly improves what it takes to extend the PayPal Commerce webhook and also adds checking to silently update the webhook with PayPal if what's registered ever changes (i.e. an add-on is installed that adds more events, or the return url changes).
For registration, a `WebhookRegister` class has been added and stored as a singleton within the Container. This allows for the following extensibility from any other theme or plugin:
```php
// Register a single event
give(WebhookRegister::class)->registerEventHandler('PAYMENT.SALES.COMPLETED', PaymentSalesCompleted::class);
// Register a bunch of events
give(WebhookRegister::class)->registerEventHandlers([
'PAYMENT.SALES.COMPLETED' => PaymentSalesCompleted::class,
]);
```
Setting up webhooks upon onboarding, …
=> Improve Webhook extensibility and PayPal updating

CHANGELOG.md, includes/post-types.php
Resolves #5207 
This PR resolves an issue whereby the users were met with a 404 notice when trying to view donation form archives via `mysite.com/donations/`. This PR resolves the issue by defaulting to `enabled` when checking for the `form_archives` site option in the `give_setup_post_types()` method. 
This PR affects how post types are registered and setup during initial installation of the plugin.
1. Fresh install at example.local
2. either go through the setup wizard to create a test form, or skip it and create a new form.
3. Navigate to example.local/donations/
=> On a fresh install, the `/donations/` form archive now works

src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5191
After changing the payment gateway, "Make this an anonymous donation" checkbox is not checkable anymore. 
This PR solves the problem by changing the way how the event handlers are attached to the checkbox.
Donation form checkboxes
1. Create a donation form 
2. Enable Anonymous Donations option
3. Enable Registration + Login option
4. Save form
5. View created Donation form in the browser incognito mode 
6. Check "Make this an anonymous donation" checkbox
7. Change payment gateway 
8. Try to check "Make this an anonymous donation" checkbox again
=> refactor: attaching events on dynamically created elements

CHANGELOG.md, includes/process-donation.php
Resolves #5199
The Stripe SDK is throwing PHP deprecation notices when `WP_DEBUG` is enabled, which breaks the receipt step of the multi-step form template.
This prevents the notices from breaking the display using an output buffer to control the output and prevent the notices from displaying.
- Enabled `WP_DEBUG`
- Connect to Stripe account
- Make a donation using a credit card (Stripe).
=> PHP Notices no longer break multi-step form receipt step.

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/css/ffm.scss, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5212 
This PR addresses an issue which caused FFM inputs in the Multi-Step form to render incorrectly. Previously, when you created a Multi-Step which included FFM inputs, but only enabled one payment gateway, the inputs were not visually reactive to selections you made. This PR resolves the bug by ensuring that `setupFFMInputs` is called on initialization of the Multi-Step form, and not only when a payment gateway is changed.
As another easy win, this PR improves FFM checkbox styles to ensure that labels are aligned correctly with the visual checkbox, and that checkmarks appear centered inside the checkbox.
This PR affects frontend logic of the Multi-Step form. Specifically, it affects the init method of the form itself, ensuring that `setupFFMInputs` is called there, as well …
=> FFM Inputs now works in Multi-Step forms with a one gateway

CHANGELOG.md, src/Milestones/Block.php, src/Milestones/Model.php, src/Milestones/resources/js/data/attributes.js, src/Milestones/resources/js/edit/inspector.js, src/Milestones/resources/views/milestone.php
Resolves #5231 
This PR introduces functionality for Milestones to support a basic custom goal. It registers the `goal` attributes which can be modified via the block inspector, and conditionally hides/shows the progress bar, adjusts the progress bar width, and updates the goal figure shown in the Milestone.
This PR affects Milestone block registration, frontend Milestone rendering logic and the Milestone model.
1. Add a new post or page
2. Add a Milestone block
3. Add forms which have already collected donations
4. Change the goal amount, check that it is reflected in …
=> Milestone now supports a custom goal

CHANGELOG.md, src/Milestones/Block.php, src/Milestones/Model.php, src/Milestones/resources/js/data/attributes.js, src/Milestones/resources/js/edit/inspector.js, src/Milestones/resources/views/milestone.php
Resolves #5238 
This PR introduces functionality for Milestones to support a `deadline` attribute, and display days remaining until that deadline. 
This PR affects Milestone block registration, frontend display logic for Milestones, and the Milestone model. 
1. Add a new page or post
2. Add a Milestone block
3. Change the deadline input
4. See that changes are reflected in the editor, and on the frontend
=> Milestone now supports a deadline

assets/src/js/frontend/paypal-commerce/AdvancedCardFields.js, assets/src/js/frontend/paypal-commerce/CustomCardFields.js, assets/src/js/frontend/paypal-commerce/DonationForm.js, assets/src/js/frontend/paypal-commerce/index.js
@JasonTheAdams comment https://github.com/impress-org/give-recurring/pull/982#pullrequestreview-481162902
I figure out that the custom card field does not show correctly when the donation form set to `Admin Defined` recurring donation and the default donation level set to non recurring level. I update the code to show the custom card fields correctly when the donor opted in for recurring donation by there choice or by admin.
Previously we are listening to change on the checkbox provided by a recurring add-on for the donor but that field does not show in all cases. To solve issue we now using `window.MutationObserver` to listen to changes on `input[name="_give_is_donation_recurring"]` which will give more accurate results.
-   [x] [Self …
=> Show custom card field for "Admin Defined" subscription

assets/src/js/frontend/paypal-commerce/AdvancedCardFields.js, assets/src/js/frontend/paypal-commerce/SmartButtons.js
Resolves javascript issue reported by @kevinwhoffman: https://github.com/impress-org/givewp/pull/5079#issuecomment-689881823
I figure out that a few javascript logic runs even PayPal Commerce payment gateway is not selected by the donor. I updated logic to setup card field height and calculate height only if PayPal Commerce payment gateway selected.
It does not affect donor donation flow.
- run `npm i && npm run dev` before testing this pr.
=> Prevent javascript notices which appears when default payment gateway (except paypal commerce) which does not need card field for payment

assets/src/js/frontend/paypal-commerce/AdvancedCardFields.js, assets/src/js/frontend/paypal-commerce/CustomCardFields.js, assets/src/js/frontend/paypal-commerce/DonationForm.js, assets/src/js/frontend/paypal-commerce/SmartButtons.js, assets/src/js/frontend/paypal-commerce/index.js, src/PaymentGateways/PayPalCommerce/ScriptLoader.php
Resolves #5255
If only PayPal smart buttons available for payment then the "Donate Now" button can confuse the donor. We decided to hide this button when only the smart button available for the "PayPal Donations" payment gateway.
This PR does not affect existing logic but implement additional logic to hide the "Donate Now" button.
- Run  `npm i && npm run dev` before testing.
=> Hide "Donate Now" button when only PayPal Smart Buttons available for paymant

CHANGELOG.md, src/Milestones/Block.php, src/Milestones/Model.php, src/Milestones/resources/js/data/attributes.js, src/Milestones/resources/js/edit/inspector.js, src/Milestones/resources/views/milestone.php
Resolves #5240 
This PR introduces logic to format special {} tags in Milestone title or description, so that admin can use dynamic information like {total_remaining} or {days_remaining} in their Milestone messaging. Additionally, the PR uses a `textarea` input in the block inspector to handle Milestone descriptions.
The special {} tags introduced in this PR are:
- {total}
- {total_goal}
- {total_remaining}
- {days_remaining}
A future issue should be opened to handle actually informing users about what specific tags are available to them, and what they do. Because this specific requirement relies on unspecified design decisions, I opted not to include it as part of this PR.
This PR affects the Milestone model, as well as frontend rendering logic for Milestones. …
=> Milestone title and description now support {} tags

CHANGELOG.md, includes/post-types.php, src/Milestones/Block.php, src/Milestones/Model.php, src/Milestones/resources/js/components/multi-select-control/index.js, src/Milestones/resources/js/data/attributes.js, src/Milestones/resources/js/data/utils.js, src/Milestones/resources/js/edit/inspector.js, src/Milestones/resources/views/milestone.php
Resolves #5243 
This PR introduces logic to support filter the forms that feed into a Milestone block by their tag and category. With MultiSelectControls, an admin can search registered form tags or categories and select which ones to filter forms that feed into the Milestone by. For example: If an admin selects no specific forms, but chooses a specific category, then all forms with that category will be factored into Milestone progress.
This PR also introduces metric selections beyond simply revenue. The metric dropdown was added to the inspector, which allows an admin to display progress according to revenue, donations, or donors. 
This PR affects Milestone block editor rendering logic, and how the Milestone model queries forms and aggregates data.
-   [x] Acceptance criteria satisfied …
=> Milestone now supports filtering forms by tag/category and displaying specific metrics

CHANGELOG.md, src/Milestones/Block.php, src/Milestones/Model.php, src/Milestones/resources/js/data/attributes.js, src/Milestones/resources/js/edit/inspector.js, src/Milestones/resources/views/milestone.php
Resolves #5241 
This PR introduces logic to support a custom Call To Action URL and text associated with the Milestone block. Admin can now customize link text and URL through the Milestone block inspector. 
This PR affects frontend Milestone rendering logic as well as admin block editing JS.
1. Create a new post or page
2. Add the Milestone block
3. Add a custom Call To Action URL
4. Change the Call To Action text
5. Check that these changes are reflected both in the block preview and on the frontend
=> Milestone now supports a custom link

includes/admin/tools/views/html-admin-page-system-info.php, src/Framework/Migrations/MigrationsRunner.php, src/Revenue/Migrations/CreateRevenueTable.php
Resolves #5272
`donation_id` and `form_id`  set as foreign key which reference to `wp_posts.ID`.
- I fixed a PHP error that generates on the system info page because of referencing old class.
- Update logic to prevent migration overwrite if has the same timestamp.
If you want to rerun Migration then make sure you complete below steps:
=> "donation_id" and "form_id" set as foreign key which reference to "wp_posts.ID"

CHANGELOG.md, src/Campaigns/config/give_campaigns.cpt.php, src/Campaigns/resources/editor-styles.scss
Resolves #5282
- Restores the post title UI for the Campaign post type.
- Updates the `<Heading />` Inner Block to differentiate from the post title.
-   [x] Keyboard accessible
- Set a post title
- Set a preview heading, different than the post title
=> Campaigns UI now differentiates title from preview heading

assets/src/css/admin/settings.scss, assets/src/js/admin/admin-settings.js, src/PaymentGateways/PayPalCommerce/AdminSettingFields.php, src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php, src/PaymentGateways/PayPalCommerce/PayPalCommerce.php, src/PaymentGateways/PayPalCommerce/Repositories/Settings.php, src/PaymentGateways/PayPalCommerce/onBoardingRedirectHandler.php
Resolves #5140 
The goal of this PR is to simplify the onboarding process such that it is no longer necessary to save the settings for the country code to be applied. Instead, pass the country code via ajax for the partner link.
Ultimately it should perform like the following:
- Display the country field
- Hide all other fields
- When the "Connect with PayPal" button is clicked, pass the country so it's not necessary to "save settings"
- Hide the country field
- Show other settings (when there are any)
- Show the connected account details
PayPal Commerce onboarding process
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-revi …
=> Improve country handling in onboarding

CHANGELOG.md, src/MultiFormGoals/resources/js/blocks/multi-form-goal/index.js
Resolves #5312
The Inner Media & Text block is pre-configured to fill the height of the block with the image by default.
- Add Multi-Form Block to page/post
- Upload an image to the Inner Media & Text
- Add content to change block height
=> Multi-Form Goal Block now defaults to image filling the height

CHANGELOG.md, src/MultiFormGoals/resources/js/blocks/progress-bar/edit/index.js, src/MultiFormGoals/resources/js/components/server-side-render-x/index.js
Resolves #5311 
This PR introduces the ServerSideRenderX component, which improves the Progress Bar editor UI by preserving block appearance until a new preview is loaded via SSR.
This PR affects the ProgressBar block, specifically replacing the use of WP core's ServerSideRender block with the community created ServerSideRenderX block.
=> Progress Bar block SSR is now improved

CHANGELOG.md, src/MultiFormGoals/resources/css/common.scss, src/MultiFormGoals/resources/css/editor.scss, src/MultiFormGoals/resources/views/multiformgoal.php
Resolves #5317 
This PR is focused on polishing styles for the Multi Form Goal as it is represented in the block editor, on the frontend, and in the shortcode. Additionally, it handles some specific edge cases with how the align tool can be used to ensure that frontend presentation is consistent with backend appearance.
This PR primarily affects common and editor styles for the Multi Form Goal feature.
As seen in the editor:
As seen on the front end:
1. Add a new page or post
2. Add the Multi Form Goal block
3. Add an image, and change some settings
4. Check that …
=> Multi Form Goal styles are now polished

src/MultiFormGoals/resources/css/common.scss
Resolves #5327 
This small PR defines the padding for content in the Media-Text block within the context of a Multi-Form Goal to be 16px. This padding is consistent with spacing around the content div represented in the Multi-Form Goal shortcode shortcode. 
This PR affects styles for the Multi-Form Goal block.
=> Space now exists between media area and text content in block editor

src/MultiFormGoals/resources/css/common.scss
Resolves #5325 
This PR makes minor changes to block styling so ensure that the Progress Bar focus outline is not cropped when selected in the block editor. 
Changes in the PR affect frontend and editor styles for the Multi-Form Goal block and Progress Bar block.
=> Progress bar inner block no longer crops focus outline

CHANGELOG.md, src/MultiFormGoals/resources/css/common.scss
Resolves #5328
Adds a `20px` bottom margin to the wrapper element.
=> Add bottom margin to Multi-Form Goal block.

src/MultiFormGoals/resources/js/blocks/progress-bar/edit/inspector.js, src/MultiFormGoals/resources/js/components/multi-select-control/index.js
Resolves #5326 
This PR makes minor tweaks to presentation of various Progress Bar block settings.
This PR affects rendering logic for various Progress Bar block controls and settings.
=> Block settings are now polished

CHANGELOG.md, src/MultiFormGoals/resources/js/blocks/progress-bar/index.js
Resolves #5337 
This PR defines the Multi-Form Goal block as a parent for the Progress Bar block. In doing so, the Progress Bar block is made inaccessible outside the context of a Multi-Form Goal block. This means an admin cannot add a standalone Progress Bar block to a page.
This PR affects block editor rendering logic related to the Progress Bar block. Specifically, it clarifies where the block can be added, and limits it to the Multi-Form Goal block.
=> Progress Bar block is no longer available outside of Multi-form Goal

assets/src/js/frontend/paypal-commerce/AdvancedCardFields.js, assets/src/js/frontend/paypal-commerce/CustomCardFields.js, assets/src/js/frontend/paypal-commerce/DonationForm.js, assets/src/js/frontend/paypal-commerce/PaymentMethod.js, assets/src/js/frontend/paypal-commerce/SmartButtons.js, assets/src/js/frontend/paypal-commerce/index.js, src/PaymentGateways/PayPalCommerce/ScriptLoader.php
Resolves https://github.com/impress-org/givewp/issues/5324
This pr adds a feature to process multiple currencies with donation form without reloading webpage.
**Note: I am still facing issues when passing `inte=subscription` in param SDK URL: https://github.com/paypal/paypal-sdk-client/issues/46#issuecomment-702881717. Currently onetime and subscription payment processing without any issue with `intent=capture`**
Javascript which renders PayPal payments refactored completed to the setup payment method on basis of donor choices.
-   [x] Labels applied if docs are needed
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) …
=> Add currency switcher support to paypal donation payment gateway

includes/admin/forms/class-metabox-form-data.php
Resolves #5276 
This PR solves the issue by adding "multicheck" type to the list of types for handling default properties.
1. Add this piece of code to `functions.php`
```php
add_filter( 'give_metabox_form_data_settings', function( $sections, $formId ) {
$fields = [
[
'id'            => 'give_multicheck_options_admin',
'name'          => 'Multiple checkbox test',
'default'       => 1,
'type'          => 'multicheck',
'wrapper_class' => 'give_multicheck_options_admin',
'options'       => [
'option1' => 'Multi checkbox option 1',
'option2' => 'Multi checkbox option 2',
'option3' => 'Multi checkbox …
```
=> Fix: Multi checkbox options handling

CHANGELOG.md, src/MultiFormGoals/resources/views/progressbar.php
Closes #5349
Checks the return value of `getMinutesRemaining()` to conditionally render the output.
- Add a Multi-Form Goal block
- Set an End Date in the future and see the "time to go" stat displayed
- Change an End Date in the past and see the "time to go" stat is **not** displayed
=> Multi-Form Goal Progress Bar only shows "time to go" if the end date has not passed

CHANGELOG.md, composer.json, composer.lock
The `composer.lock` file has locked in a number of dependencies at version which are not compatible with the lowest PHP version the plugin is supposed to be compatible with.
By setting `config -> platform` in the `composer.json` file, the PHP version referenced there will be used for the version negotiations, preventing these type of incompatibilities from happening in the future.
Using the `develop` branch:
- Set the PHP version used on the system to PHP 5.6 and try running `composer install`. It will fail.
Using this branch:
- Set the PHP version used on the system to PHP 5.6 and try running `composer install`. It will succeed.
- Set the PHP version used on the system to a higher PHP version and see it succeed again.
=> Composer: fix incompatible dependencies

CHANGELOG.md, src/MultiFormGoals/resources/js/blocks/multi-form-goal/edit/index.js, src/MultiFormGoals/resources/js/blocks/multi-form-goal/index.js, src/MultiFormGoals/resources/js/blocks/multi-form-goal/save/index.js
Resolves #5362 
This PR introduces logic to ensure that when a Multi-Form Goal block is inserted, the inner Progress Bar block is selected by default.
This PR solely affects rendering logic for the Multi-Form Goal block, as it appears in the block editor.
1. Add new page or post
2. Add Multi-Form Goal block
3. Check that the inner Progress Bar block is selected by default
=> Multi-Form Goal Blocks now auto-focus the Progress Bar on insert

CHANGELOG.md, assets/src/js/frontend/paypal-commerce/index.js, assets/src/js/plugins/give-api/form.js
Resolves #5376
In this PR logic has been updated to load PayPal SDK only on a page that has a donation form.
- Test this pr on pages with and without donation form and check `paypal.com/sdk` in Google Chrome `network` tab. The number of requests for PayPal SDK will be zero on-page which does not have a donation form and vice versa.
**Zero PayPal SDK request on page without donation form:**
**PayPal SDK request loads on page without donation form:**
=> Load PayPal sdk only on donation form page 

assets/src/css/frontend/processing-state-template.scss, assets/src/js/frontend/paypal-commerce/AdvancedCardFields.js, assets/src/js/frontend/paypal-commerce/SmartButtons.js, assets/src/js/plugins/give-api/form.js, assets/src/js/plugins/give-api/util.js, includes/class-give-scripts.php, src/PaymentGateways/PayPalCommerce/ScriptLoader.php
Resolves #5368
To resolve this issue I matched overlay background color to PayPal Model background and updated the message on the overlay [[Design](https://github.com/impress-org/givewp/issues/5368#issuecomment-707925693)]
- Update `Give.form.fn.showProcessingState` function to accept custom HTML.
- Updated default text overlay message ( Check screenshot in visual section).
- Overlay will appear for a recurring donation also. 
- Overlay function has been moved to `Give.util.fn` [`assets/src/js/plugins/give-api/util.js`]
**Overlay with default Message:**
**Overlay with custom Message:**
-   [x] [Self …
=> Improve donation processing UX for Paypal donation

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5380
This PR fixes the issue with tabbing through CC fields inside an iframe. The issue is fixed by wrapping up `setTabOrder` function with `setTimeOut` function to allow time for the loaded elements to appear in the DOM so that setTabOrder can add tabindex attribute to ajax loaded elements. 
All input form elements inside the Multi-step Donation form.
=> Fix Credit Card fields tabbing inside an iframe

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/css/receipt.scss
Resolves  #5388
This PR fixes the issue where the long text is overflowed outside container in the Donation receipt. The issue is fixed by changing the `white-space` CSS property value from `nowrap` to `pre-wrap.` 
Donation receipt UI. 
|   Before  |  After  |
|---|---|
| ![image](https://user-images.githubusercontent.com/4222590/96569640-af144600-12c9-11eb-9025-a70c1feae06b.png) |  ![image](https://user-images.githubusercontent.com/4222590/96569011-e46c6400-12c8-11eb-985a-b454a2c3a6c9.png) |
The easiest way to test …
=> Wrap long texts into multiple lines in Donation receipt UI

CHANGELOG.md, src/MultiFormGoals/ProgressBar/Model.php
Resolves #5392 
This PR address a bug which lead to inaccuracy in calculations of time remaining for a Multi-Form Goal.  Previously, the time remaining was calculated against GMT, and ignored WP options to handle any offset. This PR resolves the issue by ensuring that time remaining takes GMT offsets into account. Additionally, the PR addresses a minor error which caused minutes remaining to be rendered to the nearest decimal place, rather than rounded.
This PR primarily affects the Progress Bar model, specifically logic involved in determining the minutes remaining toward a goal.
-   [x] [Self …
=> Multi-Form Goal end date now reflects time zone

assets/src/js/admin/admin-settings.js, src/Onboarding/Setup/PageView.php, src/Onboarding/Setup/templates/index.html.php, src/PaymentGateways/PayPalCommerce/Repositories/Settings.php, src/PaymentGateways/PayPalCommerce/onBoardingRedirectHandler.php
Resolves #5391
This PR resolve issue by
- Reverting back button initial state after the PayPal model open
- Add log link in webhook setup failure notice
- Conditionally update PayPal gateway information on the tab on GiveWP Setup page
- Run`npm i && npm run dev` before testing this pr
- If you unable to reproduce the webhook setup issue then comment the `if` condition in this function and then connect PayPal account: https://github.com/impress-org/givewp/blob/163a038f4925218f345e7181d3d85515528b6dcc/src/PaymentGateways/ …
=> Improve PayPal Donations WP backend UX

CHANGELOG.md, includes/admin/import-functions.php
Resolves #5408 
This PR fixes the issue where imported donations were affecting the form amount suggestions.  The problem was in the code logic, where the check for Donation Level texts was made and if the Level Title column from the imported file is different than already defined form levels, it will add imported donation amount as another donation level. The issue is solved by removing the piece of code which was doing that.
Donations import.
1. Make a few donations.
2. …
=> Importing donations are not affecting form suggestions anymore

CHANGELOG.md, includes/admin/upgrades/upgrade-functions.php, src/PaymentGateways/PayPalStandard/Migrations/SetPayPalStandardGatewayId.php, src/PaymentGateways/PayPalStandard/PayPalStandard.php, src/ServiceProviders/PaymentGateways.php
Resolves https://feedback.givewp.com/bug-reports/p/paypal-standard-should-not-break-on-290
I find out that I renamed PayPal Standard payment gateway id to `paypal-standard` from `paypal` which cause of most of the issues with PayPal Standard payment gateway. To resolve the issue, I update the payment gateway id `paypal`.
We can not detect if PayPal Standard was enabled when GiveWP update to `2.9.0` that why we can not reenable it. IF admin catch this issue on their site then they have to reenable it to fix the issue on the site after that everything will work as before.
-   [x] Relevant @since tags included in DocBlocks
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review …
=> PayPal Standard functionality is now restored after breakage in 2.9.0

CHANGELOG.md, includes/admin/settings/class-settings-advanced.php, readme.txt, src/MultiFormGoals/ServiceProvider.php, src/ServiceProviders/Onboarding.php
Resolves #5415 
This PR prevents a fatal error related to GiveWP 2.9 which appeared on installs running WP 4.9.x. To resolve the error, the MultiForm Block ServiceProvider now checks for existance of the `register_block_type` function before attempting to add blocks.
This PR affects the Multi-Form Goal ServiceProvider, allowing it conditionally add hooks related to blocks only if the `register_block_type` function exists.
1. Setup a fresh install of WP 4.9.x
2. Install this …
=> GiveWP 2.9.0 is now compatible with WP 4.9.x

CHANGELOG.md, assets/src/js/frontend/give-stripe.js, src/Controller/Form.php, src/Helpers/Frontend/ConfirmDonation.php, src/PaymentGateways/Stripe/DonationFormElements.php, src/ServiceProviders/PaymentGateways.php
Resolves #5418 
The stripe checkout method allows us to process payment `onpage` and` offpage`. Admin has a setting to configure the payment method checkout type either `Modal` or `Redirect`. When checkout type set to `Modal` then javascript code run to setup stripe card fields which donor can use to process the payment `onpage`. This logic should not run when the checkout type set to `Redirect`. I update the code to fix this issue.
- Run npm run dev to compile the JS …
=> Prevent javascript error on donation form if stripe checkout payment method active

CHANGELOG.md, assets/src/js/frontend/give-stripe-elements.js
Resolves #5420 
I find out that there were coding-related issues that handle stripe payment method errors on the frontend. I find them to prevent javascript error.
- Run npm run dev to compile the JS changes
- Follow the Steps to Reproduce in the Issue
- Be sure to look through the Acceptance Criteria and test each scenario
=> Show donor error and restore donate now button when Stripe returns error when create payment method

CHANGELOG.md, includes/admin/misc-functions.php, includes/misc-functions.php
Resolves #4760 
This issue occurs because the list of premium addons that we get from `give_get_plugins` function is not accurate and logic fails in specific scenarios to identify premium addons. After research, I find out that the `Plugin URI` (in plugin header) of every premium addon points to `https://givewp.com/addons/{addonSlug}` which we can compare from premium addon list which we get from `give_get_premium_addons_url` function.
As you can see above image `Give - WePay` addon does not consider as a premium addon because it is deprecated but you can see license nag for `Give -Zapier` addon which is a premium addon.
-   [x] Acceptance criteria satisfied and marked in the related issue
-   [x] Changes logged to the `Unreleased` …
=> Free add-ons does not trigger GiveWP add-on license errors

CHANGELOG.md, includes/admin/misc-functions.php, includes/deprecated/deprecated-functions.php, includes/misc-functions.php, src/License/PremiumAddonsListManager.php
Resolves #4760 
The issue was already resolved in PR https://github.com/impress-org/givewp/issues/4760. In this PR, I am using [easy digital download plugin rest API endpoint](https://github.com/impress-org/givewp/issues/4760#issuecomment-720907346) to detect if the addon is premium or not. 
- Set `$is_required_days_past` value to `true` to see license warning if not any license activated: https://github.com/impress-org/givewp/blob/56ae547508a0b495e60e4f4b1c0f7a2d6e046015/includes/admin/admin-actions.php#L1415
- Use any type of license key: …
=> Use easy digital download rest api endpoint to confirm addon is premium or not

CHANGELOG.md, src/Form/Template.php, src/Views/Form/Templates/Sequoia/views/loading.php, src/Views/IframeView.php
Resolves #5435
IFrameView passes the `$formId` now so the loader can properly pull the color from template options.
Shortcodes / Embeds
=> Fix loader color when using shortcode or block #5435

CHANGELOG.md, src/MultiFormGoals/MultiFormGoal/Shortcode.php, tests/src/MultiFormGoals/MultiFormGoal/ShortcodeTest.php
Resolves #5431
Wraps the call to `shortcode_atts` to first parse attributes by type. Attributes provided an array as a default value will be parsed to convert a comma separated list into an array. 
1.Add the [give_multi_form_goal ids="513,509"] shortcode to a page.
1. The Multi-Form Goal includes all listed forms.
1. Repeat for `tags` and `categories` attributes.
=> MultForm Goal Shortcode now supports comma separated lists.

CHANGELOG.md, give.php, src/DonorProfiles/Block.php, src/DonorProfiles/Model.php, src/DonorProfiles/Routes/DonationHistoryRoute.php, src/DonorProfiles/ServiceProvider.php, src/DonorProfiles/Shortcode.php, src/DonorProfiles/resources/js/app/index.js, src/DonorProfiles/resources/js/block/data/attributes.js, src/DonorProfiles/resources/js/block/edit/index.js, src/DonorProfiles/resources/js/block/edit/inspector.js, src/DonorProfiles/resources/js/block/index.js, src/DonorProfiles/resources/js/block/logo/index.js, src/DonorProfiles/resources/js/components/app/index.js, src/DonorProfiles/resources/views/donorprofile.php, webpack.config.js
Resolves #5428 
This PR introduces logic to scaffold front-end donor profiles, including the block, shortcode and API routes necessary to support them. The newly created `DonorProfiles` domain in `src` contains all the new changes, including the resources necessary to load a simple frontend app where donor profiles are meant to go.
This PR makes a Donor Profile block available in the editor, and also introduces the new `give_donor_profile` shortcode. It registers an API endpoint, which currently returns dummy donation history data.
-   [x] [Self …
=> Front-end donor profiles are scaffolded

CHANGELOG.md, includes/gateways/stripe/includes/class-give-stripe-gateway.php, includes/gateways/stripe/includes/give-stripe-helpers.php
Resolves #5439
Stripe asks to send the amount in cents or the smallest unit of supported currency. For zero-based currency, we have sent the amount as is to Stripe. I find out that we send an amount in cents always for all currency. We use `give_stripe_dollars_to_cents` helper function to get the amount in cents, so I updated logic to return the amount based of currency type.
- Update `Give_Stripe_Gateway::format_amount` function to use `Money` class to return amount in currcies'smallest unit …
=> Covert donation amount to cent only if currency is non zero type when donation donated with Stripe payment gateway

CHANGELOG.md, src/Framework/Migrations/MigrationsRunner.php, tests/src/Framework/Migrations/MigrationsRunnerTest.php, tests/src/bootstrap.php
Resolves #5454 
A bug was introduced in 2.9.2 that throws an error on a fresh WP install or when upgrading from a version of GiveWP prior to the migrations framework. Simply, a default of an empty array was accidentally removed in 2.9.2, which has it default to `false`, which throws a warning. This PR replaces the default.
The migrations flow
Install a fresh version of WP with debugging enabled and visible, then activate GiveWP. If there are no warnings and all the tables …
=> Fix the MigationsRunner warning on fresh WP installs

CHANGELOG.md, assets/src/js/frontend/give-stripe.js, assets/src/js/plugins/give-api/form.js
Resolves #5458 
Errors were being thrown by Stripe for both Credit Cards and Checkout modal, both of which had the same root cause which this PR addresses:
A magic and all-powerful feature of JS is closures. A closure is created when a function is called that is defined in another function. The child function inherits the scope of the parent function _at the time the child function was created_. This last bit is super important, as it means that the closure variables in scope when the child function is called are _from the past_. This is a commonly confusing attribute of closures.
The `give-stripe.js` file has been accumulating over time and, frankly, it's just a difficult file to understand. It accounts for things happening a multiple points in time:
1. When the form loads
2. When the …
=> Fix Stripe CC and Checkout Modal donation errors

CHANGELOG.md, assets/src/js/frontend/give-stripe.js
Resolves #5466 
This PR adds a condition check that was omitted in 2.9.3 which mounts Stripe on the subscription update screen.
The subscription payment info update screen.
See the steps to reproduce in the issue. If you're able to update the card then it's working!
=> Fix issue with updating subscription card for Stripe

CHANGELOG.md, assets/src/js/frontend/give-stripe-elements.js
Resolves #5468 
This resolves a bug for the Stripe single input setting. The issue was that when the payment method was being created the JS was looking for a cardholder name field what only exists on the multi-input field setting. The fix is to add a check so the name field is only retrieved on the multi-input setting.
Stripe single and multi-input CC fields
Review the instructions to reproduce the problem in the Issue. Please review the Acceptance Criteria and test each …
=> Fix Stripe single card input field

CHANGELOG.md, src/Revenue/Listeners/DeleteRevenueWhenDonationDeleted.php, src/Revenue/RevenueServiceProvider.php
Resolves #5471 
I find that the second argument to `delete_post` action hook added in WP 5.5.0 and we are using second argument in our logic, so everyone we face this issue if they are using WP < 5.5.0. I update to logic to use on the first argument of this action hook.
- Use the steps to reproduce the issue as mentioned in the issue description. You should able to delete donations without any issue.
=> Prevent fatal error when delete donation on WP < 5.5.0

CHANGELOG.md, src/Revenue/Migrations/AddPastDonationsToRevenueTable.php, src/Revenue/Repositories/Revenue.php
Slack discussion: https://givewp.slack.com/archives/C0FAGC83C/p1605811530057900
After discussion with @JasonTheAdams , we find out that we do not know the actual cause of the `AddPastDonationsToRevenueTable` database upgrade failure. To give an idea to the admin which donation cause upgrade failure, I added donation id in the exception message.
Setup to reproduce this issue:
- You must have one donation with zero amount. You can directly edit the donation amount on the donation detail page.
- Clear upgrade from completed upgrade list. …
=> Donation id mentions in exception and log message when insert query for revenue table fails

CHANGELOG.md, src/DonorProfiles/resources/js/app/components/avatar-control/index.js, src/DonorProfiles/resources/js/app/components/avatar-control/style.scss, src/DonorProfiles/resources/js/app/components/button/index.js, src/DonorProfiles/resources/js/app/components/button/style.scss, src/DonorProfiles/resources/js/app/components/desktop-layout/style.scss, src/DonorProfiles/resources/js/app/components/divider/index.js, src/DonorProfiles/resources/js/app/components/divider/style.scss, src/DonorProfiles/resources/js/app/components/field-row/index.js, src/DonorProfiles/resources/js/app/components/field-row/style.scss, src/DonorProfiles/resources/js/app/components/heading/style.scss, src/DonorProfiles/resources/js/app/components/mobile-layout/style.scss, src/DonorProfiles/resources/js/app/components/mobile-menu/style.scss, src/DonorProfiles/resources/js/app/components/radio-control/index.js, src/DonorProfiles/resources/js/app/components/radio-control/style.scss, src/DonorProfiles/resources/js/app/components/select-control/index.js, src/DonorProfiles/resources/js/app/components/select-control/style.scss, src/DonorProfiles/resources/js/app/components/text-control/index.js, src/DonorProfiles/resources/js/app/components/text-control/style.scss, src/DonorProfiles/resources/js/app/tabs/edit-profile/content.js, src/DonorProfiles/resources/js/app/tabs/edit-profile/style.scss, src/DonorProfiles/resources/js/app/utils/index.js
Resolves #5456 
This PR implements React components necessary for rendering to Donor Profile editing UI. Specifically, the PR contains logic to power reuse-able select inputs (<SelectControl/>), text inputs (<TextControl/>), radio inputs (<RadioControl/>) and buttons (<Button/>). While this PR does not go so far as to actually implement functionality that would allow these controls to persist changes to the database, it is meant to lay the groundwork for that next step.
This PR affects the Edit Profile tab of the Donor Profiles application, and introduces additional UI components to the Donor Profile app.
-   [x] Changes logged to the `Unreleased` section of …
=> Edit Profile UI is now implemented

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/css/currencyswitcher.scss
Resolves #5452
The Currency Switcher `select` sets a `color` of `transparent` in order to hide the selected input value on the form. On a Windows machine it seems that `color: transparent` is being inherited by the `option` elements, which is not the same as OS X.
Tested via Browser Stack on https://kylej22.sg-host.com/donations/donation-form/
| Windows 10: Edge 86 | OS X Catalina: Safari 13.1 |
| --- | --- |
| ![Screenshot from 2020-11-16 10-34-58](https://user-images.githubusercontent.com/10858303/99274257-1bfefb00-27f8-11eb-8e69-7a3f57f63f47.png) | ![Screenshot from 2020-11-16 10-45-40](https://user-images.githubusercontent.com/10858303/99275105-1950d580-27f9-11eb-9a82-29756808f6d3.png) |
| iPhone 11 Pro: Safari | iPhone 11 Pro: Chrome | Samsung Galaxy S20: Firefox | Samsung Galaxy …
=> Currency Switcher options are visible in the dropdown on a windows machine

src/Framework/Database/DB.php
Resolves https://wordpress.org/support/topic/unable-to-install-45/
I find out that we are using `WP_Error::has_errors` function which introduced in `WP 5.1.1` which means revenue table migration will cause a fatal error on `WP < 5.1.1`. I added custom code to validate WP errors.
- Install, activate or upgrade plugin lastest GIveWP on WP < 5.1.1
- check errors
- GiveWP plugin should not cause a fatal error on WP < 5.1.1 and WP > 5.1.1
=> prevent WordPress  < 5.1.1 compatibility issue

CHANGELOG.md, src/Onboarding/LocaleCollection.php
Sync locale collection with WooCommerce locale-info, see https://github.com/woocommerce/woocommerce/commit/b58dc02183a7cc70b121fcb588b3fb5d16fb890c
I have a file watcher set on the WooCommerce `i18n/locale-info`, with which I manually sync the GiveWP locale collection for onboarding,
=> Onboarding locales now include Jamaica

assets/src/js/frontend/give-ajax.js
Give has a workaround for safari versions which don't support the `required` attribute on HTML5 forms. Safari supports this since late 2016:
https://webkit.org/blog/7093/release-notes-for-safari-technology-preview-19/
AFAICT the first release that included this was 10.1 from March 2017. There is no currently supported version of Safari that does not support `required`, so this workaround is not needed anymore, and it also can interfere with custom event listeners in integrations (which is how we found this)
All current Safari versions (which currently can't do proper HTML5 validation)
-   [x] [Self …
=> Remove outdated Safari workaround

CHANGELOG.md, assets/src/css/admin/stripe-admin.scss, includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
Resolves #5198
This change allows for Stripe accounts to be disconnected form a site while preserving GiveWP as an Authorized Application to prevent other connected sites from breaking.
Additionally, this change offers instructions for revoking GiveWP as an Authorized Application in an explicit manner.
**Note**: This does NOT change the behaviour of which Stripe accounts are listed with a Disconnect action. The behaviour is the same as `develop`.
- Disconnects a Stripe account using `give_stripe_disconnect_account`, which does not revoke GiveWP as an Authorized Application in Stripe.
- Adds a new `give_disconnect_connected_stripe_account` action with corresponding method callback.
- Adds a notice below the Stripe account list with instructions on revoking GiveWP as an Authorized …
=> Disconnecting a Stripe account no longer revokes GiveWP as an Authorized Application

CHANGELOG.md, give.php
Resolves #5492 
This uses an absolute path for loading the composer autoloader file, which should help on some systems that did not like a relative path being used there.
Just how the autoloader gets loaded... which is kind of everything. But it should either work completely or break everything, so that's good news.
Just pull the PR and activate GiveWP. If it's working then it's working.
=> Use absolute path for composer autoloader

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/css/feerecovery.scss, src/Views/Form/Templates/Sequoia/assets/css/recurring.scss
Resolves #5501 
There is a bug in the Chrome browser with border transitions. The transition effect is applied to the margin of a container as well which creates weird hover glitches. This PR is resolving this issue by removing the transition property completely. 
Fee recovery message box border transition effect on hover. 
|---|---|
|  ![deepin-screen-recorder_Select area_20201214133509](https://user-images.githubusercontent.com/4222590/102082058-8ca63100-3e11-11eb-9cd3-abd13390ebca.gif) | ![deepin-screen-recorder_Select area_20201214133643](https://user-images.githubusercontent.com/4222590/102082075-95970280-3e11-11eb-9ccb-9be9f5c7b5f2.gif)  |
-   [x] …
=> Hover glitches of Fee Recovery checkbox are now fixed

CHANGELOG.md, src/PaymentGateways/PayPalCommerce/PayPalCommerce.php, src/PaymentGateways/PayPalStandard/PayPalStandard.php, src/PaymentGateways/PaypalSettingPage.php
Resolves #5503 
The PayPal settings page is a group of PayPal payment methods. I added logic to filter each group. 
```
give_get_settings_paypal_paypal-commerce -> Setting filter for PayPal Donations
give_get_settings_paypal_paypal -> Setting filter for PayPal Standard
```
This change does not affect existing functionality.
- You should able to see all previous PayPal settings in each sub-group.
=> Add filter hook to filter PayPal settings

CHANGELOG.md, src/Onboarding/Wizard/templates/form-preview.php
Resolves #5509
This PR resolves a minor issue where some script tags for the Onboarding Form Preview template were being loaded outside the template's closing `body` tag. With these changes, all script tags are loaded inside either `head` or `body` tags.
This PR affects the template file for the Onboarding Wizards Form Preview (what is loaded inside the iframe).
Navigate to the Onboarding Wizard (by enabled the "Setup" page and clicking the arrow in the "First Time …
=> Onboarding Form Preview template now loads scripts inside of the closing body tag

CHANGELOG.md, src/MultiFormGoals/MultiFormGoal/Shortcode.php, src/MultiFormGoals/resources/css/common.scss
Resolves #5527 
This PR introduces styling improvements to ensure that image and text areas are stacked when needed inside Multi-Form Goal blocks that are added via shortcodes. Using CSS grid minmax and auto-fill, the image and text areas stack if there is less than enough space for each to be 200px wide.
The PR affects frontend styling of the Multi-Form Goal shortcode.
1. Add a new Multi-Form Goal via shortcode
2. Place the Multi-Form Goal inside a narrow column layout
3. …
=> Multi-Form Goals added via shortcode now stack image and text when needed

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5525
On touch devices, the click and touchend events are triggering the event handler twice for a given interaction. AS far as I can tell the handling of the touchend event is not specifcally needed, or it is no longer necessary.
- The Sequoia Template checkbox click handler
1. With touch enabled (physical device or simulated)
2. Enable Recurring Donations (Donor's choice, admin specifies period)
3. "Touch" the "Make this donation monthly" element.
4. The active …
=> Checkbox click handler does not double trigger for touch devices

includes/process-donation.php
Resolves #5534
In 2015, the Korean Government changed their postcodes from 6 digits to 5 digits. Therefore, I updated the regex expression to validate this new format.
1. Go to a donation form
2. Select "South Korea" as country
3. Fill "06316" in zipcode field.
4. Submit
=> Validate new korean zipcode format

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/css/form.scss
Resolves #5497
This PR introduces minor style improvements for the Multi-Step form as it is presented in Firefox and Safari. Specifically, it ensures that the amount input width is correct, and the spinning loader appears in the donate button.
This PR affects frontend styling of the Multi-Step form in Safari and Firefox.
1. Add a new Multi-Step form
2. View the form in Firefox and Safari
3. Check that the amount input width is correc
4. Check that the spinning loader appears …
=> Various Multi-Step form browser styling compatibility issues are now resolved

CHANGELOG.md, src/Controller/Form.php
Resolves #5530 
In the Multi-Step form template view, we render the donation form in an iframe. To render the correct donation form view we depends upon the referrer and query parameter. On the first redirect, the donor sees the donation form in an iframe because we detect it by referer but not in the second redirect. To detect whether we are viewing the donation forms in an iframe or not, we use the `giveDonationFormInIframe` query param. I added the same parameter in error redirect to redirect the donation form on error redirect.
-   [x] [Self …
=> Multiple error redirects does not break donation form view in Multi Step form template view

includes/country-functions.php
Resolves #5536
The status field is not required and not used for Korean addresses. In order to fix this, the "hidden" parameter should be set to "True" when South Korea is selected as country.
1. Select "South Korea" as country.
2. State field should be hidden.
=> Hide state field for South Korea

CHANGELOG.md, src/Framework/Database/DB.php, src/Framework/Migrations/Contracts/Migration.php, src/Revenue/Migrations/RemoveRevenueForeignKeys.php, src/Revenue/RevenueServiceProvider.php
Resolves #5539
Since foreign keys should no longer be used, this adds a migration to remove any foreign keys which may be left over from a previous migration.
It also extends the `DB` static facade to completely wrap the `WPDB` class so the query methods may be called with SQL error checking in place.
The wp_give_revenue table in the database
Try adding a foreign key to the revenue `form_id` and `donation_id` columns, then run the migration. The foreign keys should now be …
=> Add migration to remove revenue foreign keys

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5541
I find out that the personal information section re-render when donation switch gateway. The icon on the personal information input field adds by javascript which does not run after refreshing the personal information section. I update `refreshPaymentInformationSection` function logic to setup field icons.
We can merge this pr if input field icons show correctly on the initial donation form and when donor switch gateway.
=> show personal information field icons when payment gateway switch

.gitignore, CHANGELOG.md, package.json, tests/e2e/README.md
- Decouples `test:e2e` from `wp-env start`
- Renames `wp-env` command to generic `env`
- Updates documentation to reflect changes
=> Decouple test:e2e command from wp-env

CHANGELOG.md, assets/src/js/admin/onboarding-wizard/app/steps/introduction/index.js, assets/src/js/admin/onboarding-wizard/components/button/index.js, assets/src/js/admin/onboarding-wizard/components/continue-button/index.js, src/Onboarding/Setup/templates/index.html.php, src/Onboarding/Setup/templates/row-item.html, tests/e2e/integration/onboarding/onboarding_wizard_spec.js, tests/e2e/integration/onboarding/setup_page_options_spec.js, tests/e2e/integration/onboarding/setup_page_spec.js, tests/e2e/support/commands.js
Resolves # N/A
This PR introduces some onboarding e2e tests (and additional supporting test functions), to demonstrate e2e testing implementation. Notably, it adds specs for testing the setup page and onboarding wizard, as well as support for a `data-givewp-test` attribute used to target specific elements for testing. To query those targets, tests can make use of the `cy.getTest( "id" )` command. 
This PR affects some frontend rendering logic for the setup page and onboarding wizard, and introducing new testing specs to the tests/e2e/onboarding directory.
-   [x] [Self …
=> Sample onboarding tests are now implemented

CHANGELOG.md, assets/src/js/admin/onboarding-wizard/app/steps/addons/index.js, assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js, assets/src/js/admin/onboarding-wizard/app/steps/features/index.js, assets/src/js/admin/onboarding-wizard/app/steps/introduction/index.js, assets/src/js/admin/onboarding-wizard/app/steps/location/index.js, assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js, assets/src/js/admin/onboarding-wizard/components/card-input/index.js, assets/src/js/admin/onboarding-wizard/components/dismiss-link/index.js, assets/src/js/admin/onboarding-wizard/components/donation-form/index.js, assets/src/js/admin/onboarding-wizard/components/select-input/index.js, assets/src/js/admin/onboarding-wizard/components/step-link/index.js, tests/e2e/integration/onboarding/onboarding_wizard_spec.js, tests/e2e/integration/onboarding/setup_page_spec.js
Resolves #5546 
This PR expands upon the existing Onboarding Wizard e2e test spec to cover various additional functionality including dynamic select options, top navigation, preview form loading, and more.
This PR affects some frontend logic for the Onboarding Wizard (introducing `data-givewp-test` attributes to a handful of interactive components), but primarily changes the Onboarding Wizard spec, found in the e2e tests directory.
1. Start the testing environment (`npm run …
=> Onboarding wizard e2e tests are now implemented

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/css/form.scss
Resolves #5548
This PR resolves the issue where the Gift Aid popup was not showing up when using the multi-step form. The issue is solved by updating the CSS selector which was hiding all the elements that don't belong to the GiveWP. The Gift Aid popup was not displaying correctly because it was affected by this [rule-set](https://github.com/impress-org/givewp/blob/da50ffe5de7276bd5734f329beb372a200501cc3/src/Views/Form/Templates/Sequoia/assets/css/form.scss#L1409) from the core plugin. 
Gift Aid popup.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review …
=> Give Aid add-on description popup is now working when using multi-step form

CHANGELOG.md, src/MultiFormGoals/MultiFormGoal/Shortcode.php
Resolves #5564
This PR resolves the issue where the Multi Form Goal shortcode was producing errors and warnings when used as a Divi module. The issue is fixed by checking if the array key exists before trying to use it. 
Multi Form Goal Shortcode.
1. Download and install the Give Divi add-on
2. Add a new page using Divi editor
3. Insert the Give Multi Form Goal  module
4. Save the page and exit Divi builder
5. Test module on the front-end
=> Multi Form Goal is not producing errors and warnings when used as a Divi module

CHANGELOG.md, src/Onboarding/Setup/PageView.php, src/Onboarding/Setup/templates/index.html.php, tests/unit/README.md, tests/unit/tests/Onboarding/Setup/PageViewTest.php
Resolves #5575
Adding the `testId` tag created a situation where two unmerged were being scrubbed as one large unmerged tag.
Example:
```
id="{{ id }}" class="setup-item" testId="{{ testId }}" 
```
was being interpreted as a a single tag:
id="`{{ id }}" class="setup-item" testId="{{ testId }}`"
which, when scrubbed, results in:
```
id=""
```
See: https://github.com/impress-org/givewp/issues/5575#issuecomment-770950149
- Updates the un-merged tag regex to be more accurate.
=> Setup Page gateway links now render styles correctly

CHANGELOG.md, src/DonorProfiles/Factories/DonorFactory.php, src/DonorProfiles/Pipeline/DonorProfilePipeline.php, src/DonorProfiles/Profile.php, src/DonorProfiles/Repositories/Donations.php, src/DonorProfiles/Routes/DonationsRoute.php, src/DonorProfiles/Routes/LocationRoute.php, src/DonorProfiles/Routes/ProfileRoute.php, src/DonorProfiles/resources/js/app/components/dashboard-content/index.js, src/DonorProfiles/resources/js/app/components/donation-receipt/index.js, src/DonorProfiles/resources/js/app/components/donation-table/donation-row/index.js, src/DonorProfiles/resources/js/app/components/donation-table/index.js, src/DonorProfiles/resources/js/app/components/donation-table/style.scss, src/DonorProfiles/resources/js/app/components/tab-link/index.js, src/DonorProfiles/resources/js/app/tabs/donation-history/content.js, src/DonorProfiles/resources/js/app/tabs/donation-history/style.scss
Resolves #5562 
This PR introduces style improvements to the Donor History UI components (visible in donation tables and donation receipt pages of the Donor Profile).
This PR primarily affects frontend styling and some backend logic related to displaying donation history in Donor Profiles.
1. Add a Donor Profile block to a new page
2. On the frontend, check that the donation history displayed in Donor Profile matches currently logged in Donor's donaiton history
3. Check that …
=> Donation History UI is now polished

CHANGELOG.md, composer.json, composer.lock
Adds the `kjohnson/since-unreleased` package to update `@unreleased` tags with version numbers.
- Run `composer install`
- Add `@unreleased` tag to a dockblock (php and/or js)
- Run `composer run unreleased 3.0.0`
- Tag(s) should be updated from `@unreleased` to `@since 3.0.0`
=> Add since-unreleased script for updating @unreleased docblocks

src/Form/LegacyConsumer/Commands/SetupFieldValidation.php, src/Form/LegacyConsumer/Commands/SetupNewTemplateHook.php, src/Form/LegacyConsumer/ServiceProvider.php, src/Form/LegacyConsumer/templates/checkbox.html.php, src/Form/LegacyConsumer/templates/select.html.php, src/Form/LegacyConsumer/templates/text.html.php, src/Form/LegacyConsumer/templates/textarea.html.php
Resolves #5596
- Adds a hook to register required fields.
- Updates required attributes in templates.
Add a custom field using the new Fields API and set the field as `required`.
The form JS will validate, so you'll need to edit the DOM to manually remove the required attribute so that the form will submit - and then trip server side validation. (You can also inspect the network request and resend the POST without the custom field value).
```php
/**
* Plugin Name: Give Custom …
```
=> Form Consumer implements Server Side Validation

CHANGELOG.md, src/DonorProfiles/Repositories/Donations.php, src/DonorProfiles/resources/js/app/components/annual-receipt-table/annual-receipt-row/index.js, src/DonorProfiles/resources/js/app/components/annual-receipt-table/index.js, src/DonorProfiles/resources/js/app/components/annual-receipt-table/style.scss, src/DonorProfiles/resources/js/app/tabs/annual-receipts/content.js, src/DonorProfiles/resources/js/app/tabs/annual-receipts/hooks/index.js, src/DonorProfiles/resources/js/app/tabs/annual-receipts/store/actions.js, src/DonorProfiles/resources/js/app/tabs/annual-receipts/store/index.js, src/DonorProfiles/resources/js/app/tabs/annual-receipts/store/initialState.js, src/DonorProfiles/resources/js/app/tabs/annual-receipts/store/reducer.js, src/DonorProfiles/resources/js/app/tabs/annual-receipts/utils/index.js
**_NOTE: This PR is dependent up work done in this Give Annual Receipts PR: https://github.com/impress-org/give-annual-receipts/pull/89_**
Resolves #5603
This PR introduces improvements to the Annual Receipts tab UI, so that it can dynamically populate the Annual Receipts table using data fetched from the Annual Receipts addon. 
This PR primarily affects frontend rendering of the Donor Profiles application, and specifically the Annual Receipts tab.
=> Annual Receipts UI now connects to addon

CHANGELOG.md, src/DonorProfiles/Repositories/Donations.php, src/DonorProfiles/resources/js/app/components/button/index.js, src/DonorProfiles/resources/js/app/tabs/donation-history/content.js, src/DonorProfiles/resources/js/app/tabs/donation-history/style.scss
Resolves #5604 
This PR makes the Donor Profile application aware of PDF receipts, so that a "Download Receipt" button is added to the Donation Receipt page when the PDF Receipt addon is activated.
This PR affects frontend rendering logic of the Donor Profile application, and the Donations repository.
=> PDF Receipts are now available from Donation Receipt pages

src/Framework/FieldsAPI/FieldCollection.php, src/Framework/FieldsAPI/FieldCollection/Exception/NameCollisionException.php, src/Framework/FieldsAPI/FieldCollection/InsertNode.php, src/Framework/FieldsAPI/FieldCollection/NameCollision.php, tests/unit/tests/Framework/FieldsAPI/FieldCollection/NameCollisionTest.php
Resolves #5594
Adds name collision detection to `FieldsAPI\FieldCollection`.
Updated `insertBefore()` and `insertAfter()` to first check for name collisions.
=> Field API enforces unique names

CHANGELOG.md, src/Framework/FieldsAPI/FieldCollection/Exception/ReferenceNodeNotFoundException.php, src/Framework/FieldsAPI/FieldCollection/InsertNode.php, tests/unit/tests/Framework/FieldsAPI/FieldCollection/InsertNodeTest.php, tests/unit/tests/Framework/FieldsAPI/FieldCollectionTest.php
Resolves #5635
- Adds the `ReferenceNodeNotFoundException` exception, which is thrown when inserting before or after a node that does not exist.
- Optimizes `InsertNode` methods `insertBefore` and `insertAfter` by avoiding unecessary name collision checks on each nesting level, since the collision check is already recursive.
- Moves `InsertNode` trait tests to a separate `InsertNodeTest` test file.
Testing instructions are outlined in …
=> Fields API throws an exception when inserting relative to a node that does not exist

src/API/Endpoints/Migrations/GetMigrations.php, src/Framework/Migrations/Contracts/Migration.php, src/Log/Migrations/CreateNewLogTable.php, src/Log/Migrations/DeleteOldLogTables.php, src/Log/Migrations/MigrateExistingLogs.php, src/MigrationLog/Admin/Migrations/index.js, src/MigrationLog/Migrations/CreateMigrationsTable.php, src/MigrationLog/Migrations/MigrateCompletedMigrations.php
Resolves #5631
This PR adds support for the Migration title and source columns. The `Migration` class is extended and 2 static methods, title and source, were added. 
Migrations list table.
`Migration` class
Navigate to  `Donations -> Tools -> Data`
=> Support for the Migration title and Source column is now implemented

src/API/Endpoints/Reports/Endpoint.php
Resolves #4920
Declare property `$schema` into src/API/Endpoints/Reports/Endpoint.php It prevents PHP notices.
Install WooCommerce: `wp plugin install woocommerce --activate`
Try to run few wp-cli commands.
I've tried `wp cache flush` on few installations and without this PR I see PHP notices.
=> Reports endpoints no longer throw an error due to missing $schema property

assets/src/js/frontend/give-donations.js
Resolves #5626 
The state parameter in toggleClass function should be inverted. If the zipcode is required, then it should return "false" instead of "true" so it can properly display or hide the required indicator.
1. Go to a donation form
2. Select a country where the zipcode is required
3. Scroll down to zipcode field
4. Required indicator is displayed
=> Zip Code required field indicator now toggles correctly for the Legacy Form template

includes/admin/settings/class-settings-advanced.php, src/DonorProfiles/resources/js/app/tabs/edit-profile/address-controls/index.js, src/DonorProfiles/resources/js/app/tabs/edit-profile/content.js
Resolves #5656 
All user- and public-facing contextual docs in 2.10 have been reviewed.
The Advanced settings page at Donations > Settings > Advanced
One small typo on the front end of the new Donor Profile on the edit screen.
=> Contextual docs are to brand standards

src/Form/LegacyConsumer/Commands/SetupFieldPersistance.php, src/Framework/FieldsAPI/FormField.php, src/Framework/FieldsAPI/FormField/FieldStoreAsMeta.php, tests/unit/tests/Framework/FieldsAPI/FormField/FieldStoreAsMetaTest.php
Resolves #5625
- Custom fields can be stored as donor meta with the fluent API method `storeAsDonorMeta()`.
- Custom fields can be stored as donation meta with the fluent API method `storeAsDonationMeta()`.
```php
add_action( 'give_fields_after_donation_levels', function( $fieldCollection, $formID ) {
$fieldCollection->append(
give_field( 'text', 'my-custom-field' )
->label( 'My Custom Field' )
->required()
->storeAsDonorMeta()
);
}, 10, 2 );
```
=> Form Consumer now persists custom field value as donor and/or donation meta.

CHANGELOG.md, assets/src/css/admin/give-admin.scss, assets/src/css/admin/settings.scss, assets/src/js/admin/admin.js, includes/install.php, src/DonorProfiles/Admin/Settings.php, src/DonorProfiles/Admin/SuccessNotice.php, src/DonorProfiles/Admin/UpgradeNotice.php, src/DonorProfiles/RequestHandler.php, src/DonorProfiles/ServiceProvider.php, src/DonorProfiles/resources/js/admin/index.js, src/DonorProfiles/resources/styles/upgradenotice.scss, src/DonorProfiles/resources/views/successnotice.php, src/DonorProfiles/resources/views/upgradenotice.php
Resolves #5638 
Resolves #5630 
This PR introduces logic to display an upgrade notice to explain the Donor Profiles feature to admin who have an existing GiveWP install. Additionally, it introduces logic to generate and setup a Donor Profile page when requested.
This PR affects the admin interface, specifically pages with GiveWP related controls.
On an existing GiveWP install:
1) Check that the new Donor Profiles notice appears on GiveWP related admin pages
2) Click "Setup …
=> Admin are now shown Donor Profiles upgrade notice and Donor Profile page is generated on new installs

CHANGELOG.md, src/Form/LegacyConsumer/Commands/SetupFieldConfirmation.php, src/Form/LegacyConsumer/Commands/SetupFieldReciept.php, src/Form/LegacyConsumer/ServiceProvider.php, src/Framework/FieldsAPI/FormField.php, src/Framework/FieldsAPI/FormField/FieldReceipt.php
Resolves #5624
Depends on #5652
Custom field values now show in the Donation Receipt for the Sequoia form template.
NOTE: Custom fields must be stored as donor and/or donation meta in order to be added to the receipt.
Donation Receipt
Donation Confirmation
```php
add_action( 'give_fields_after_donation_levels', function( $fieldCollection, $formID ) {
$fieldCollection->append(
give_field( 'text', 'my-custom-field' )
->label( 'My Custom Field' )
->required()
->storeAsDonorMeta() …
```
=> Custom field values now show in Donation Receipt and Donation Confirmation

CHANGELOG.md, src/Form/LegacyConsumer/TemplateHooks.php, src/Views/Form/Templates/Sequoia/assets/css/form.scss
Resolves #5668
Updates the alignment of custom fields to match the default fields in the Sequoia template.
- Adds new CSS to the Sequoia template styles.
Here is a snippet for adding custom fields to each template hook:
```php
add_action( 'init', function() {
give( \Give\Form\LegacyConsumer\TemplateHooks::class )->walk( function( $hook ) {
add_action( "give_fields_$hook", function( $fieldCollection, $formID ) use ( $hook ) {
$fieldCollection->append(
give_field( 'text', 'my-custom-field-' . uniqid() )
->label( "$hook" )
);
$fieldCollection->append(
give_field( 'textarea', 'my-custom-field-' . uniqid() )
->label( "$hook" )
);
$fieldCollection->append(
give_field( 'select', 'my-custom-field-' . uniqid() )
->label( "$hook" )
->options([
'' => "$hook",
])
);
$fieldCollection->append( …
```
=> Custom Fields on the Sequoia template now match alignment

CHANGELOG.md, src/DonorProfiles/Repositories/Donations.php, src/DonorProfiles/resources/js/app/components/auth-modal/index.js, src/DonorProfiles/resources/js/app/components/donation-receipt/index.js, src/DonorProfiles/resources/js/app/tabs/donation-history/content.js
Resolves #5639 
This PR introduces logic to ensure that the Donation receipt presented inside Donor Profiles matches the donation receipt shown to donors during the donation process. This includes dynamic donation-specific line items like processing fees, subscription information, and custom field information.
This PR affects the Donation Receipt view of Donor Profiles, and the Donations repository logic used to retrieve and describe a donor's donation history.
1. Make a donation with dynamic receipt line items (custom fields, subscription, fee recovery, etc).
2. Note the line items shown in your donation receipt during the donation process.
2. From the Donor Profile, view the receipt for that donation.
3. Check that the receipt line items shown inside Donor Profiles match the receipt you …
=> Donor Profile receipt content should match receipt displayed during donation

src/MigrationLog/Admin/Migrations/index.js, src/Views/Components/PeriodSelector/style.module.scss
Resolves #5659
This PR adds minor tweaks to CSS styles to fix the issue with elements that are not displaying correctly on smaller screens.
And the text of the migration run button has been updated. 
Elements that were not displaying correctly:
- Period selector
- Migration title
Migrations list table.
| Migrations list table | Logs list table |
|---|---|
| ![image](https://user-images.githubusercontent.com/4222590/109619397-090aff00-7b39-11eb-9395-58d686c50ed6.png) | ![image](https://user-images.githubusercontent.com/4222590/109619898-91899f80-7b39-11eb-87db-18fce51accbe.png) |
-   [x] [Self …
=> Migrations and Logs UI is now polished

src/Log/Helpers/LegacyLogsTable.php, src/Log/LogServiceProvider.php, src/Log/Migrations/DeleteOldLogTables.php, src/Log/Migrations/MigrateExistingLogs.php
Resolves #5671
This PR resolves the issue with Legacy log migrations failing on fresh installs. The issue is resolved by adding a check for the legacy logs table. If the table exists, the migrations for handling legacy logs will be registered. Otherwise, they won't show up in the legacy table.
LogServiceProvider
1. Install this branch on fresh WP install
2. Navigate to `Donations -> Tools -> Data`
There shouldn't be any failed migrations responsible for migrating legacy logs
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-re …
=> Legacy log migrations are not failing on fresh install now

CHANGELOG.md, src/Tracking/TrackingServiceProvider.php
Resolves https://github.com/impress-org/givewp/issues/5678
Usage tracking job scheduler will run only in WP Backend.
This considers as working if you should able to optin to usage tracking on the live website.
**Usage tracking optin only appears on live sites in WP Backed. Once you accept optin then let me know I will review the data on the telemetry server.**
=> Schedule tracking job only if admin accessing website

CHANGELOG.md, assets/src/js/plugins/form-template/utils.js, src/DonorProfiles/resources/js/app/hooks/index.js
Resolves #5688
This PR fixes the issue where the Donor Dashboard didn't resize when the parent window resizes. The issue is fixed by attaching a `resize` event to the topmost window instance and on the iframe itself. 
The `resize` event for the iframe was already set with `iframe-resizer` library, but for some reason that didn't work for Donor Dashboard. The easiest solution was to attach another resize event to the iframe itself and handle iframe width directly as "fixing" the `iframe-resizer` library is not an option.
Donor Dashboard iframe
Donation Form iframe
Go to the Donor Dashboard page and resize your browser window. The DOnor Dashboard iframe should resize when the browser window resizes. 
Make sure you check the Donation form as well because these changes affect the multi-step …
=>   Donor Dashboard iframe now resize when the parent window resizes

.github/workflows/wordpress.yml, CHANGELOG.md, src/DonorProfiles/Repositories/Donations.php
Resolves #5702 
This PR addresses a bug which prevented donors who accessed the Donor Dashboard via an email access link from seeing their donation history or giving stats. Previously, the Donor Dashboard would load the correct profile, but a "No Donations" message would appear, despite the donor having made a donation by that point in time. 
Ultimately, the bug was determined to be caused by a sql query which checked donor ID against post author id. Because of this, the Donation history functionality (specifically the getDonationIds method) was only functional for donors who's donations were also associated with a WordPress account. To remedy the problem, the getDonationIds method was updated to mirror the sql logic found in the getDonationAggregate method, which checks against the …
=> Email access now gives donor access to my donor dashboard

CHANGELOG.md, src/DonorProfiles/Admin/Settings.php, src/DonorProfiles/resources/js/app/components/auth-modal/index.js
Resolves #5703 
This PR address a few select typos and tense issues in notices and contextual docs related to the Donor Dashboard feature domain. 
This PR affects frontend rendering of the unassociated donor notice (in Donor Dashboard login area), and the context docs for the Donor Dashboard page setting (in General Settings).
=> Donor Dashboard feature domain no longer has typos

CHANGELOG.md, src/DonorProfiles/Helpers.php
Resolves #5700 
This PR resolves an issue which prevented donors without a WP account from viewing their donation dashboard. Now, donors are able to see their donor dashboard while they are in the same session (clicking link in email receipt, or navigating to the Donor Dashboard page directly from the donation form).
This PR affects logic in the Helpers::getCurrentDonorId method. This impacts how the current donor ID is determined, and not ensures that the existing history session logic is taken into account.
N/A
1. Make a donation (without an account)
2. Navigate to the donor dashboard
3. See that the Donor Dashboard loads correctly
-   [x] Changes logged to the …
=> While in the same session, donors are now able to see their donor dashboard

CHANGELOG.md, includes/admin/add-ons/actions.php
Resolves https://github.com/impress-org/givewp/issues/5692
We have a helper function `give_get_plugins` which returns plugin data with extra data related to givewp. We show an inline update notice to licensed addon on the plugin listing page. To do that first we verify the add-on license. We are getting PHP notice because some of the plugin data does not return correctly from `Give_License::get_plugin_by_slug( $plugin['slug'] )`. I update the condition to verify empty plugin data too.
It does not affect existing functionality.
Install `Give - Donation Modules for Divi` plugin. You should not be getting PHP notice on the plugin listing page and licensed givewp addons to update inline notice show correctly (if any).
-   [x] …
=> Prevent PHP notices on plugin listing page

CHANGELOG.md, src/DonorProfiles/resources/js/app/components/button/index.js
Resolves #5713 
This PR introduces changes to resolve a big which caused the Donor Dashboard to reload when the Download Receipt button was clicked. Previously, the button relied on an unnecessary ternery operator to check for an "onClick" function, which is not applicable when an href has already been provided.
This PR affects frontend rendering logic for the PDF receipts addon.
N/A
1. Go to Donor Dashboard
2. Click on Donation History > View Receipt > Download Receipt
3. Notice that PDF download correctly and the Donor Dashboard app is unaffected
-   [x] [Self …
=> The spinner should go away when the PDF Receipt is generated on the Donor Dashboard

CHANGELOG.md, src/MultiFormGoals/MultiFormGoal/Shortcode.php
Resolves #5711
This PR fixes the issue where the empty shortcode attributes were not being passed correctly which lead to displaying the incorrect data for the Multi Form Goal shortcode. The issue is resolved by checking if the value is empty before splitting it by comma. The reason why we need this check is if you split the empty string with the explode function, the returned result will look like this `[ 0 => '' ]` and if you check that later with the `empty` function, which `Give\MultiFormGoals\ProgressBar\Model` does,  the result will be `true` and the returned result will be wrong.
Multi Form Goal Shortcode class
1. Add a new page and for content add this shortcode `[give_multi_form_goal ids="ID"]`
**ID** represents the form that has associated revenue. 
2. Save and View the page. …
=>  Multi Form Goal Shortcode class is handleing the empty attributes correctly now

src/PaymentGateways/Stripe/ApplicationFee.php, tests/unit/tests/PaymentGateways/Stripe/ApplicationFeeTest.php
Related to https://github.com/impress-org/givewp/pull/5709
This refactor encapsulates the individual logical checks involved in deciding whether or not to charge an application fee.
Additionally, this adds unit tests for each of the individual tests.
=> Stripe application fee checks are encapsulated

CHANGELOG.md, src/DonorProfiles/Repositories/Donations.php
Resolves #5714 
This PR introduces logic to ensure that all donation statuses are included in querying for the Donation History tab of Donor Dashboard. Along the way, another bug was resolved which sometimes lead to formatting issues in the Giving Stats section when no completed donations where found.
This PR affects backend logic for the Donation History tab and dashboard content of the Donor Dashboard.
1. Go to Donor Dashboard
2. Select Donation History tab
3. Notice that donations of all donation statuses appear
4. 
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-rev …
=> Donor Dashboard history now includes pending donations

CHANGELOG.md, includes/class-give-donor.php, src/DonorProfiles/Pipeline/Stages/UpdateDonorAddresses.php, src/DonorProfiles/resources/js/app/tabs/edit-profile/address-fields/index.js, src/DonorProfiles/resources/js/app/tabs/edit-profile/content.js
Resolves #5715 
This PR resolves a bug which prevented the "Make Primary Address" button from working correctly in the Donor Dashboard. Previously, when the button was pressed, nothing happened. Now, when you click the button, the Primary Address is set correctly, and when you hit "Update" it is persisted correctly in the database.
This PR affects frontend logic for the address controls of the Donor Dashboard, and backend logic used to persist addresses via the Donor Dashboard.
N/A
1. Navigate to Donor Dashboard and add a secondary address and Save.
2. Click on "Make Primary" and see that the primary addresses is swapped with the selected additional address
3. Hit update, and refresh page to ensure that changes persisted correctly
4. Delete additional addresses, and hit update
5. Refresh …
=> "Make Primary" address link for multiple addresses now works in Donor Dashboard

CHANGELOG.md, includes/gateways/stripe/includes/class-give-stripe-checkout-session.php, includes/gateways/stripe/includes/class-give-stripe-gateway.php, includes/gateways/stripe/includes/class-give-stripe-payment-intent.php, src/PaymentGateways/Stripe/ApplicationFee.php
Resolves #5555
Added logic to add Stripe application fee when applicable. I applied the rule written in [this comment](https://github.com/impress-org/givewp/issues/5555#issuecomment-759596226).
Stripe application fee should not apply to one time donations when
- Stripe pro addon active.
- Stripe pro addon install.
- Stripe single license active.
- All access pass license active (includes Stripe addons)
=> Apply Stripe fee when applicable

CHANGELOG.md, src/DonorDashboards/resources/js/app/components/currency-control/index.js, src/DonorDashboards/resources/js/app/components/subscription-manager/index.js, src/DonorDashboards/resources/js/app/components/subscription-manager/payment-method-control/card-control/style.scss, src/DonorDashboards/resources/js/app/components/subscription-manager/payment-method-control/stripe-control/stripe-card-control/style.scss, src/DonorDashboards/resources/js/app/components/subscription-manager/style.scss, src/DonorDashboards/resources/js/app/components/subscription-manager/utils/index.js
Resolves #5734 
This PR addresses a minor bug which caused custom amounts to render as "NaN" in the subscription manager when a donor cleared the field. Now, when a donor clears the field, it is set to it's minimum allowed amount. Additionally, this PR includes some minor polish for the recurring donation manager view, aimed at making the "Update Subscription" button UX mirror that of the Edit Profile tab.
This PR affects frontend rendering logic for the recurring donations subscription manager in the Donor Dashboard.
N/A
1. Navigate to the donor dashboard and edit a recurring donation
2. Erase the donation amount and check that the minimum amount appears (instead of NaN) …
=> Editing the recurring donation amount no longer displays "NaN"

CHANGELOG.md, src/Framework/Migrations/MigrationsRunner.php, src/Log/Log.php, src/MigrationLog/MigrationLogModel.php, src/MigrationLog/Migrations/CreateMigrationsTable.php
Resolves #5736
This PR resolves the issues with creation of the give_migrations table that was failing on some systems. The problem was in the `id` column key length, which was set to `255`. But on some systems, that key length is causing a fatal error, depending on what MySQL engine and what encoding is being used. The issue is resolved by setting the key length to `180`. 
Additionally, the `MigrationLogRepository::save` method is wrapped up with a try-catch block in order to keep the site functional even if the migration system fails. 
Migration system
- …
=> Creation of the give_migrations table is not producuing errors anymore

CHANGELOG.md, src/Views/Form/Templates/Sequoia/optionConfig.php
Resolves #5746
I add a double quote around the link in `href` tag to fix ixxue.
This fix does not affect existing functionality.
Review description in donation form meta box. You can easily find the field setting by searching text visible in screenshot.
=> Fix broken link by correctly closing href tag

src/Form/LegacyConsumer/README.md
Updates the README for the Public Fields API (Legacy Form Consumer) to include additional examples as used in the snippet documentation.
=> Public fields api README now has more examples.

CHANGELOG.md, src/MigrationLog/Helpers/MigrationHelper.php
Resolves #5756 
This resolves an issue wherein migrations were being queried even when unnecessary, causing a fatal error to be thrown unnecessarily in other contexts. This PR makes sure the migrations are only queried at the proper time, so if there is a problem with migrations it won't show up in other contexts.
The migrations API and, hopefully, the page/post edit screen such that they work if the migrations are broken.
1. Delete the `give_migrations` table
2. Try to create a page
3. Creating a page should still work
-   [ ] [Self …
=> Migrations are retrieved only when necessary

CHANGELOG.md, includes/admin/donors/class-donor-table.php
Resolves #5750
The value of the search parameter was bring escaped prior to checking that the parameter was set.
- An empty search parameter does not show an undefined index notice.
- The value of the search is escaped to prevent XSS
- A value of the search that does not match any donors returns an empty set.
- A value of the search that does match donors returns the matching donors.
- Visit the donor table without a search parameter and no notice should be shows.
=> Donor search no longer shows undefined index notice.

CHANGELOG.md, composer.json, composer.lock
Resolves #5753
- Updates `kjohnson/since-unreleased` to use `1.0.0`, instead of `dev-master`.
- Updates `kjohnson/format-object-list` to use `0.1.0`, instead of `dev-master`.
run `composer install --prefer-dist`.
Inspect packages for `.git` (hidden) sub-directory:
`ls -la vendor/kjohnson/since-unreleased`
`ls -la vendor/kjohnson/format-object-list`
=> Composer dependencies now reference releases instead of branches

CHANGELOG.md, src/DonorDashboards/App.php, src/DonorDashboards/resources/js/app/components/auth-modal/utils/index.js, src/DonorDashboards/resources/js/app/components/logout-modal/utils/index.js, src/DonorDashboards/resources/js/app/components/subscription-cancel-modal/utils/index.js, src/DonorDashboards/resources/js/app/components/subscription-manager/utils/index.js, src/DonorDashboards/resources/js/app/tabs/annual-receipts/utils/index.js, src/DonorDashboards/resources/js/app/tabs/donation-history/utils/index.js, src/DonorDashboards/resources/js/app/tabs/edit-profile/utils/index.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/index.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/utils/index.js
Resolves #5764 
This PR resolved the issues faced on hosts with aggressive page caching by ensuring that the WP API nonce is not required in order to access the donor dashboard, and ensuring that query params are passed to the iframe which contains the Donor Dashboard application.
This PR affects some API query logic for the Donor Dashboard frontend, and some iframe markup output logic in the backend.
N/A
On a WP Engine install:
1. Make a donation with an email not associated with a WP acct
2. Go to Donor Dashboard
3. Request email verification
4. See that the email is sent successfully, and that you can access the Donor Dashboard using the link in the email
-   [x] …
=> Donors are now able to log into Donor Dashboard on hosts with page caching

CHANGELOG.md, src/DonorDashboards/RequestHandler.php
Resolves #5767 
This PR ensures dashboard pages are only generated by users with the correct capabilities.
This PR affects the request handler class for Donor Dashboards.
=> The Donor Dashboard are now only be generated in admin-side pages

CHANGELOG.md, src/MigrationLog/MigrationLogRepository.php, src/MigrationLog/Migrations/CreateMigrationsTable.php
Resolves #5758 
This PR resolves the issue with the migration log table creation process which was failing on older MySQL versions. Table creation was failing because the default value for the `last_run` column was set to `CURRENT_TIMESTAMP` which is not supported for the `DATETIME` column type in MySQL versions <= 5.6. The issue is resolved by changing the column type to `TIMESTAMP`.
Create migration table SQL. 
Install Give on a server that has MySQL version <= 5.6
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#se …
=>  GiveWP Database management tools are now backward compatible with MySQL 5.6

CHANGELOG.md, src/Log/LogFactory.php, src/Log/LogModel.php, src/Log/LogRepository.php, src/Log/Migrations/CreateNewLogTable.php
Resolves #5775
This PR resolves the issue with the logs table creation process which was failing on older MySQL versions. Table creation was failing because the default value for the `date` column was set to `CURRENT_TIMESTAMP` which is not supported for the `DATETIME` column type in MySQL versions <= 5.6. The issue is resolved by removing the default value and by setting the date with PHP.
Create `give_logs` table SQL.
Install GiveWP 2.10.1 on a server that has MySQL version <= 5.6
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github …
=> Logs table creation is now backward compatible with MySQL 5.6

CHANGELOG.md, src/DonorDashboards/Admin/Settings.php
Resolves #5783 
This PR introduces a check to ensure that new Donor Dashboards are only generated if one does not already exist (published or unpublished).
This fix affects logic in the generateDonroDashboardPage method, which can be called manually (from the admin settings page), or automatically on new installs.
N/A
On an install of GiveWP with a Donor Dashboard already created and setup:
1. Deactivate GiveWP
2. Remove the plugin
3. Reinstall GiveWP
4. Activate GiveWP
5. Check that a new Donor Dashboard page was not created
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/c …
=> Donor Dashboard page is now only generated if one does not already exist

CHANGELOG.md, includes/class-give-logging.php, src/Log/Log.php
Resolves #5786 
The new `Log` facade does not allow unhandled exceptions, but the legacy system still does as it's using the `LegacyFactory` directly. We should just have the various systems use the facade unless they have a specific reason to generate the log (such as the migration runner which handles the exception itself).
The legacy migration system
Add a line to throw an exception in the new logging repository and then trigger the legacy logging system to insert a log.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-rev …
=> Prevent legacy logging from throwing unhandled exceptions

CHANGELOG.md, src/DonorDashboards/Repositories/Donations.php, src/DonorDashboards/Tabs/Contracts/Route.php, src/DonorDashboards/Tabs/DonationHistoryTab/DonationsRoute.php, src/DonorDashboards/resources/js/app/store/actions.js, src/DonorDashboards/resources/js/app/tabs/annual-receipts/content.js, src/DonorDashboards/resources/js/app/tabs/annual-receipts/store/actions.js, src/DonorDashboards/resources/js/app/tabs/annual-receipts/store/initialState.js, src/DonorDashboards/resources/js/app/tabs/annual-receipts/store/reducer.js, src/DonorDashboards/resources/js/app/tabs/annual-receipts/utils/index.js, src/DonorDashboards/resources/js/app/tabs/donation-history/content.js, src/DonorDashboards/resources/js/app/tabs/donation-history/dashboard-content.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/content.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/store/actions.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/store/initialState.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/store/reducer.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/utils/index.js
Resolves #5780 
This PR prevents donors from every being shown donations that do not belong to them.. Previously, in certain caching settings, if the system was unable to identify the current donor ID, then all donations would be returned on the Donations endpoint.
This PR affects backend logic for the Donations endpoint of the Donor Dashboard.
N/A
This is a very difficult bug to test. I have so far been unable to replicate the issue.
=> Donors can no longer see other donors donations (on certain hosts)

includes/forms/functions.php
Resolves #
This pull request fixes a small problem, whenever a donation happen there's a function calling to record the donation info in the log in this line:
https://github.com/impress-org/givewp/blob/develop/includes/forms/functions.php#L378
but the log description is storing as "Something went wrong" although there's no any error so this description confusing the people like what happened to me.
So this PR just add a more clear description to prevent confusing via adding "log_content" to the log data to prevent the default text "Something went wrong" when there's no "log_content" as that exist in this line:
https://github.com/impress-org/givewp/blob/develop/includes/class-give-logging.php#L106
This is the log in the logs list page:
This is the log info:
-   [ ] Acceptance criteria …
=> Add a log_content for the donation log to prevent the log_content to be "Something went wrong"

src/DonorDashboards/ServiceProvider.php
This PR introduces a minor fix to ensure that admin are able to use a snippet to modify Donor Dashboard styles on their site. Given the solution's incredibly small footprint, and the niche audience this fix is for, a quick PR without an issue seems appropriate.
The issues is addressed by setting a priority on the give_embed_head add action (now priority 2) in the Donor Dashboard ServiceProvider, so that Donor Dashboard assets are enqueued before the “wp_print_styles” action is called (priority 8).
This PR affects asset loading for the Donor Dashboards app.
N/A
1. Use this snippet to load custom styles into the Donor Dashboard (replacing "give-sequoia-template-css" with "give-donor-dashboards-app": https://github.com/impress-org/givewp-snippet-library/blob/master/form-customizations/css-cus …
=> Admin can now customize Donor Dashboard styles with a snippet

CHANGELOG.md, src/DonorDashboards/resources/js/app/components/tab-content/index.js, src/DonorDashboards/resources/js/app/store/actions.js, src/DonorDashboards/resources/js/app/store/initialState.js, src/DonorDashboards/resources/js/app/store/reducer.js, src/DonorDashboards/resources/js/app/tabs/annual-receipts/utils/index.js, src/DonorDashboards/resources/js/app/tabs/donation-history/utils/index.js, src/DonorDashboards/resources/js/app/tabs/edit-profile/utils/index.js, src/DonorDashboards/resources/js/app/tabs/recurring-donations/utils/index.js, src/DonorDashboards/resources/js/app/utils/index.js
Resolves #5795 
This PR implements logic to ensure that requests made via the Donor Dashboard application use WP API nonces for enhanced security and improved donor identification. Additionally, this PR introduces application level error handling for the Donor Dashboard frontend so that when an invalid nonce response is encountered, it displays an informative error notice across all Donor Dashboard tabs.
This PR affects frontend request and rendering logic of the Donor Dashboard tabs. 
To test invalid nonce error handling, alter line 149 in DonorDashboards/App.php. Instead of using the wp_create_nonce() method, pass any string (ex: '1234').
Otherwise, test that Donor Dashboards functionality continues to work as expected.
- …
=> Donor Dashboard now uses WP API nonces for enhanced security

CHANGELOG.md, includes/class-give-session.php, src/DonorDashboards/Routes/LogoutRoute.php
Resolves #5794 
This PR implements logic to ensure that the Give Session reliably reflects the currently logged in WP user. This is done by setting the 'give-email' cookie whenever a donor is logged in, and ensuring that the session is destroyed properly when the donor logs out.
This PR affects Give Session logic, specifically related to setting up sessions with a user logs in with a WP account.
N/A
In an incognito window (to avoid affects of existing cookies):
1. Log into the WP admin area with an account known to have an associated GIve Donor ID. Now
2. Visit the donor dashboard page
3. Check that the correct account and donor information is displayed
-   [x] Changes …
=> Give Session now reliably reflects currently logged in WP user

CHANGELOG.md, src/DonorDashboards/resources/js/app/components/subscription-table/index.js
Resolves #5792 
This PR resolves a minor bug causing the SubscriptionsTable component to produce a console error related to an undefined Key prop. To fix the issue, the  subscription's array index is now passed to the SubscriptionRow as a Key prop. 
This PR affects frontend rendering logic of the Subscriptions Table. Previously, when in development, the SubscriptionsTable component would produce a console error related to a missing Key prop. Now, it does not produce any errors.
N/A
On an account with multiple recurring donations
1. Start a development build of GiveWP with `npm run dev` (or `npm run watch`)
2. Go to the Donor Dashboard, and navigate to the Recurring Donations tab
3. Open browser console, notice that no errors were logged
-   [x] Acceptance criteria satisfied and marked in …
=> SubscriptionsTable component no longer produces console error 

CHANGELOG.md, includes/class-give-session.php, src/DonorDashboards/Routes/LogoutRoute.php, src/DonorDashboards/resources/js/app/components/logout-modal/index.js, src/DonorDashboards/resources/js/app/components/logout-modal/utils/index.js
Resolves #5799 
This PR introduces logic to ensure that the current Give Session is consistently destroyed when a Donor clicks the "Logout" button in the Donor Dashboard. Previously, the current Give Session was only destroyed for Donors logged in as WP users, now the Give Session is destroyed even when a donor is not logged in as a WP user.
This PR affects logout route logic for the Donor Dashboard.
N/A
1. Create a donation under a new email (without an associated WP account)
2. Navigate to the Donor Dashboard page
3. See that the Donor Dashboard loads as expected
4. Click "Logout"
5. Notice that the dashboard logs out correctly
-   [x] Changes logged to the `Unreleased` …
=> Donor Dashboard Logout now works while in the same session

CHANGELOG.md, src/DonorDashboards/resources/js/app/components/donation-row/index.js
Resolves #5802
This PR increases the specificity used in conditionally rendering the Test Donation badge for donations display in the Donor Dashboard.
This PR affects frontend rendering of the Donor Dashboard.
N/A
On a donor account with Renewals:
1. Go to the Donor Dashboard
2. View Donation History
3. Notice that all renewals are no longer marked with the Test Donation badge
=> Test Donation badge now only appears on test donations in Donor Dashboard

includes/template-functions.php
Resolves #5801
Updates the `is_give_form()` conditional logic to use the correct plural used by the registered post type.
As recorded in the [original issue](https://github.com/impress-org/givewp/issues/5801#issuecomment-827030500), this has always been wrong and is not used in GiveWP or any of the add-ons.
https://github.com/impress-org/givewp/issues/5801#issuecomment-824591461
=> Conditional check for is_give_form() now uses correct post type slug

CHANGELOG.md, assets/src/css/admin/settings.scss, assets/src/js/admin/admin-settings.js
Resolves #5824
I made the following changes to fix the issue:
1. Set the cursor to default to prevent confusion. Admin understands that it is not clickable.
2. Fix javascript issue.
You should not able to reproduce the issue when following the steps mention in the issue description.
=> Prevent javascript error when click on lock icon on email listing page

CHANGELOG.md, includes/admin/admin-actions.php
Resolves #5828 
I find out that we are not decoding url before parsing and sanitizing url values and donor address was loosing formatting because this logic. I added fix for this.
This only affect donor profile  page address edit or add logic.
You should not able to reproduce issue if you follow steps as mentioned in issue.
=> Store donor address with formatting from donor profile

CHANGELOG.md, assets/src/js/plugins/give-api/api.js, src/Views/Form/Templates/Sequoia/Actions.php, src/Views/Form/Templates/Sequoia/assets/js/form.js, src/Views/Form/Templates/Sequoia/optionConfig.php
Resolves #5815
This PR adds an option in the Donation Form Options section for the site admin to enable or disable decimal amounts when the Multi-step template is used. This option is disabled by default. 
Multi-step form donation amount input field and donation level amounts.
| Option Location | Donation form - Option Disabled | Donation form - Option Enabled |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/4222590/118002757-3a2d5a00-b348-11eb-94b4-8dcdb5c71c0b.png) | ![image](https://user-images.githubusercontent.com/4222590/118001991-7e6c2a80-b347-11eb-9bc8-41eb419adc8c.png) | ![image](https://user-images.githubusercontent.com/4222590/118001837-6399b600-b347-11eb-8f5f-b3ea488991b2.png) |
1. Create a new donation form that uses multi-step form template
2. …
=> Support for the decimal amounts is now implemented

CHANGELOG.md, src/Onboarding/LocaleCollection.php
Resolves #5830
In maintaining parity with the upstream WooCommerce woocommerce/18n/locale-info for locale/currency information, the Onboarding LocaleCollection now includes KR locale info, see woocommerce/woocommerce@0656ad5#diff-122b62121f7a3deb664f05d12fb2af1c40cf819712b5f2db935017ce4a4c45cb
- Updates `Give\Onboarding\LocaleCollection::$localeInfo`
=> Onboarding LocaleCollection has parity with WooCommerce

CHANGELOG.md, src/Onboarding/Setup/templates/section.html
Resolves #5834
The GiveWP Setup Guide’s UI had 4 extra `main` elements in its template. I replaced these with `div` elements since there didn’t really need to be any new semantics introduced in place of the incorrect ones. I double checked [the related stylesheet](https://github.com/impress-org/givewp/blob/0fe4d3ded43bf47fb5131a9396f3e5ff2e4c5899/assets/src/css/admin/setup.scss) to confirm that the `main` elements weren’t used as a selector and they were not, so there were no CSS changes which needed to be made. I tested it in the WordPress admin as well to confirm there were no side effects.
- GiveWP Setup Guide
1. First of all, get yourself to the GiveWP Setup Guide. Then if you want to test with VoiceOver for macOS, you can activate it by pressing <kbd>command ⌘</kbd> <kbd>F5</kbd> …
=> Replace `main` elements with `div` elements in GiveWP Setup Guide

.phpstorm.meta.php, give.php
Resolves #5806
This follows the work done in https://github.com/the-events-calendar/tribe-common/pull/1579 which implements this for our containers in Tribe Common, thought this would be handy for Give since you also use containers!
Allow PHPStorm Editor to resolve the different types when using the container to get an instance to an object, this works only when the container is called with a string that is either the full qualified class of the object or when the name is used on the container such as:
```php
give( Object_Type::class )->resolves_names_of_method_or_properties();
give( 'Object_Type' )->resolves_names_of_method_or_properties();
```
Dev-only improvements for those using PhpStorm to contribute.
1. Type `give( The_Class::class )->` in PhpStorm IDE
2. It should start to show the …
=> Add context to PhpStorm to resolve objects to their proper class types

CHANGELOG.md, includes/gateways/stripe/includes/class-give-stripe-customer.php
I caught this issue while working on https://github.com/impress-org/give-recurring/pull/1058#issuecomment-840600168.
Donation processing with Stripe Plaid causes generating two PHP notices. I find out that we were accessing the nonexisting property (`card`) from Stripe response object and these notices log by Stripe library. I update the code to prevent these notices.
```
[13-May-2021 13:38:43 UTC] Stripe Notice: Undefined property of Stripe\Token instance: card
[13-May-2021 13:38:44 UTC] Stripe Notice: Undefined property of Stripe\BankAccount instance: card
```
You should not get PHP notice if processing recurring donations with Stripe Plaid.
-   [x] Changes logged to …
=> Donation processing does not throw PHP notices when process payment with Strip Plaid

CHANGELOG.md, includes/admin/plugins.php, src/Framework/Exceptions/UncaughtExceptionLogger.php, uninstall.php
Resolves #5845 
This fix removes a hook during uninstalling which is used to check for addon updates. Obviously, when uninstalling we don't care if there are any updates. Just uninstall.
This also sneaks in a fix wherein uncaught errors in PHP 7 could be an Error instead of an Exception, so typing the class is a problem.
Uninstallation flow
1. Install GiveWP
2. Uninstall GiveWP
Try installing both with and without add-ons present.
=> Uninstalling no longer checks for updates (which throws exception)

CHANGELOG.md, src/Framework/Exceptions/Contracts/LoggableException.php
I was getting the following warning when the exception occurred on PHP 5.6. I removed the code that causes this warning.
```
[16-Jun-2021 13:52:02 UTC] PHP Warning:  Unsupported declare 'strict_types' in /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Exceptions/Contracts/LoggableException.php on line 3
```
- throw an uncaught exception in givewp and exception must implements `LoggableException`.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX …
=> Fix PHP warning Unsupported declare 'strict_types'

CHANGELOG.md, src/Framework/Exceptions/UncaughtExceptionLogger.php, src/Framework/FieldsAPI/Factory/Exception/TypeNotSupported.php, tests/unit/tests/Framework/Exceptions/UncaughtExceptionLoggerTest.php
Resolves #5860 
This resolves the issue wherein handled exceptions weren't being passed to the system for display (or whatever else), resulting in a demoralizing white screen.
A couple things to consider in this solution:
1. It seems that Errors (not Exceptions) work differently. Regardless of whether they're handled, they still get passed along and, in this case, are rendered in the browser. That's why I'm checking to see if the variable is, in fact, an Exception.
2. The solution seems to be to just throw the error. PHP is apparently smart enough to recognize the exception is being thrown within the handler, so it doesn't create a loop.
3. I figure if there's another handler in place, we can let them determine whether it should be re-thrown or not. This _may_ be problematic if multiple …
=> Exception Handler passes along exceptions and errors

give.php, includes/misc-functions.php, src/License/LicenseServiceProvider.php, src/License/PremiumAddonsListManager.php, src/Tracking/TrackingData/PluginsData.php
Resolves #5862 
This PR tackles the problem that givewp.com going down can bring down other sites, as they're making requests to get EDD product data in order to determine whether add-ons are premium.
A couple layers of caching are applied:
1. The request times out after 3 seconds
2. If the request returns invalid for any reason, an empty array is cached for an hour
3. Multiple checks in the same request (i.e. multiple add-ons) will only query or check the cache one time.
With this in place, there should be only one possible query per hour to givewp.com that can hang up a single request for 3 seconds. Also, in any case, multiple queries to wp_options (transient) are reduced to 1, no matter how many add-ons are installed.
Checking whether a given add-on is premium or not.
1. Make a local …
=> Pulling product data from givewp.com can no longer break site

CHANGELOG.md, assets/src/css/admin/settings.scss
Resolves https://feedback.givewp.com/text-to-give/p/settings-missing-top-margin
@DevinWalker  discovered that when the subsetting section does not define then the setting group does not have a top margin. I added the default top margin to a group setting.
This pull request affect group setting section like Strip payment gateway setting page, text to give setting page
Run `npm run dev` before testing this pull request.
=> Improve  setting group page style

CHANGELOG.md, includes/payments/functions.php, tests/unit/tests/Helpers/DonationFormVariablePricesDropdownTest.php
Admin can disable custom amount on donation form with form settings. If that donation already has a donation with a 'custom' price id then the admin will not see the correct donation level on the donation detail page because of the missing `Custom` choice from the select field.
This pull request resolves the above issue by inserting a 'Custom' donation level choice./
Note: in the Text To Give addon we create donation with the custom amount (mostly) even `custom amount` disabled in the donation form.
This pull request affect donation detail page view and `give_get_form_variable_price_dropdown` function output.
Enable custom donation amount.  Create a donation with a custom amount.
-   [x] Relevant `@since` tags included in …
=> Add custom donation level choice to select field if donation donated with custom amount

CHANGELOG.md, assets/src/css/admin/forms.scss, assets/src/css/admin/settings.scss, assets/src/css/admin/upsells.scss
In the current release the Field Descriptions vary formatting between the Global Settings and Form Settings screens. This PR standardized the descriptions so they are the same color, font size, line-height, and font weight.
Note: there is no issue for this.
Settings screens' field descriptions.
- Removed italics text and darkened text
- Improved spacing and text styles
=> Quick style updates to field descriptions styles so they are more standardized and accessible

CHANGELOG.md, includes/admin/payments/payments-history.php, includes/forms/functions.php, includes/payments/functions.php, src/Container/Container.php
Resolves #5871
GiveWP is not causing deprecation warnings on PHP8 anymore. The issue has been resolved by refactoring the code which was throwing deprecation warning on PHP 8.
1.  Enable WP_DEBUG
2. Change PHP version to 8.0
3. Go to GiveWP admin dashboard
=> GiveWP is not causing deprecation warnings on PHP8 anymore

CHANGELOG.md, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5867
Prevent a race condition between the error container and the relocated error node.
Adds a 1 millisecond timeout to prevent a race condition between the `.donation-errors` element being appended to the form and relocation of the specific error message node to that created element.
- Enable Stripe Credit Card in **live** mode.
- Create a Donation Form with the Multi-Step Template (Sequoia)
- Attempt to make a donation with an _invalid_ card number, ie `4242 4242 4242 4244`
- Submitting the payment will should show a related error message.
-   [x] …
=> Card declines on multi-step form now display an error message on first click

CHANGELOG.md, src/Form/LegacyConsumer/Commands/SetupFieldConfirmation.php, src/Form/LegacyConsumer/Commands/SetupFieldReceipt.php, src/Form/LegacyConsumer/Commands/SetupPaymentDetailsDisplay.php
This fixes an issue where some Legacy Consumer commands were walking more than just fields. This updates the commands to use `walkFields` method instead of `walk`.
=> Only walk fields for commands that deal with fields

includes/forms/template.php, src/Views/Form/Templates/Sequoia/assets/js/form.js
Resolves #5876 
This tackles the problem that tooltips weren't being escaped properly, allowing in side-effects. The issue was that the tooltip being rendered was simply grabbing the node text without escaping it, and applying it directly to the attribute as a string.
Now, the node element is created and constructed using the DOM functions, which handle escaping and such properly.
Donation tooltip options
Set the following as the Text for a Donation Option: `"onmouseover=alert(/OOPS/)//`, then hover over that donation option in the form. It **should now** open an alert.
-   [ ] Includes unit and/or …
=> Donation tooltips are now escaped properly

CHANGELOG.md, src/Framework/FieldsAPI/Checkbox.php, src/Framework/FieldsAPI/Concerns/ValidationRules.php, src/Framework/FieldsAPI/Date.php, src/Framework/FieldsAPI/Element.php, src/Framework/FieldsAPI/Email.php, src/Framework/FieldsAPI/Factory.php, src/Framework/FieldsAPI/Field.php, src/Framework/FieldsAPI/Form.php, src/Framework/FieldsAPI/Hidden.php, src/Framework/FieldsAPI/Option.php, src/Framework/FieldsAPI/Phone.php, src/Framework/FieldsAPI/Radio.php, src/Framework/FieldsAPI/Select.php, src/Framework/FieldsAPI/Text.php, src/Framework/FieldsAPI/Textarea.php, src/Framework/FieldsAPI/Types.php, src/Framework/FieldsAPI/Url.php
Works towards resolving #5880
This PR is a catch all for all missing `@unreleased` tags for the new Fields API
changes.
Just docblocks.
=> Fields API: add missing `@unreleased` tags
