includes/payments/class-give-payment.php

This PR will fix https://github.com/impress-org/give/issues/3718

fix: update donation gmt date when update donation date

---

includes/admin/donors/donor-actions.php

This PR will fix https://github.com/impress-org/give/issues/3719

fix: resolve error on pagination of Donor back end pages

---

includes/admin/donors/donor-actions.php

This PR will fix https://github.com/impress-org/give/issues/3729

fix: resolved undefined ID notice when bulk delete

---

includes/admin/tools/views/html-admin-page-system-info.php

This PR will fix #3736 
- Manually tested as per Acceptance Criteria

fix: ensure Give add-ons appear together in System Info #3736

---

includes/process-donation.php

This PR will fix #3563 
https://www.useloom.com/share/ba4f97d02009476aa58ff743878aa6fe

feat: allow login with email address wordpress does

---

includes/admin/tools/export/class-give-export-donations.php
includes/admin/tools/export/give-export-donations-exporter.php
includes/admin/tools/export/give-export-donations-functions.php

Adds a "Donor's Comment" export option for donations. 
Resolves #3743 
- Manually
- New feature for exporter

feat: export donor comments with donations

---

includes/currency-functions.php

This PR is to support https://github.com/impress-org/give-stripe/issues/359 
I've tested this PR by processing donation with Stripe Checkout for zero decimal currencies and currency switcher add-on

fix: donation amount not display correctly on stripe checkout #359

---

includes/class-give-scripts.php

refactor: remove duplicate `ajaxurl` from front-end

---

includes/admin/payments/class-payments-table.php
includes/admin/payments/view-payment-details.php
includes/admin/tools/export/class-give-export-donations.php
includes/admin/tools/views/html-admin-page-exports.php

This PR will fix https://github.com/impress-org/give/issues/3757

fix: date fields should have same placeholders through out admin panel

---

assets/src/js/frontend/give-ajax.js
assets/src/js/plugins/give-api/form.js

fix: prevent nonce verification error during login #3740

---

includes/admin/tools/data/class-give-tools-delete-test-donors.php
includes/admin/tools/data/class-give-tools-delete-test-transactions.php

This PR will fix #2473 
https://www.useloom.com/share/0fe76b785ae542d790126aa183fb135f

fix: improve deletion of test data

---

includes/install.php

This PR will fix https://github.com/impress-org/give/issues/3790

fix: delete all custom tables when subsite deleted from multisite

---

assets/src/css/admin/donors.scss
assets/src/js/admin/admin-scripts.js
includes/admin/donors/class-donor-table.php
includes/admin/donors/donors.php

This PR will fix #3777 
https://www.useloom.com/share/05387f1c4bcf4116be28f19690b6ebfa

feat: add gravatar support to the admin donors screens

---

includes/admin/shortcodes/shortcode-give-donation-grid.php
includes/shortcodes.php

This PR will fix #3792 
https://www.useloom.com/share/ee4db6eb0a0f4d25b54036d1c1cca034

feat: provide option that controls the order of forms in the form grid

---

includes/admin/settings/class-settings-advanced.php
includes/class-give-scripts.php
includes/install.php

This PR will fix #3658 
https://www.useloom.com/share/ec2705f768bf41e4a5fedd6209bfc83f

feat: add option to disable babel polyfill js

---

assets/src/js/frontend/give-ajax.js
includes/class-give-scripts.php
includes/class-give-session.php

This PR resolves #3819 
I've tested this PR on Pantheon to make sure donation processing is working properly. Please check the attached video link for more information.
**Video Link:** https://www.useloom.com/share/b82135a68b7949f0adecf83ad79b0220

fix: give session cookie prefix #3819

---

includes/admin/shortcodes/shortcode-give-donor-wall.php
includes/donors/class-give-donor-wall.php

This PR will fix #3816 
https://www.useloom.com/share/c3e78d83d3cb4d0085fff630e00e3857

feat: improve ordering of donor wall

---

assets/src/css/admin/settings.scss
includes/admin/emails/class-email-notification-table.php
includes/admin/settings/class-settings-email.php

This PR will fix #3817 
https://www.useloom.com/share/268288b8101540c29e4ae36d02db3709

fix: improve organization of emails table

---

includes/admin/settings/class-settings-email.php

fix: improve order for email settings in give donations

---

assets/src/css/frontend/donation-history.scss
templates/history-donations.php

This PR will fix #3829 
https://www.useloom.com/share/4e1450be04ca48b0a5a68bc155872529

fix: ensure mobile-only text in `[donation_history]` is displayed correctly

---

includes/admin/donors/class-donor-table.php

This PR will fix #3832 
https://www.useloom.com/share/8ce9bb2f55a94b7dabd6fb09fae9a135

fix: prevent nonce error when deleting a donor from the donors screen

---

includes/forms/functions.php

This PR will fix #3818 
https://www.useloom.com/share/1b624cc16973448aacb33670f89364c7

fix: update meta key for donation display group

---

assets/src/js/frontend/give-ajax.js
assets/src/js/frontend/give.js
assets/src/js/plugins/give-api/api.js
assets/src/js/plugins/give-api/donor.js
assets/src/js/plugins/give-api/form.js
includes/admin/tools/views/html-admin-page-system-info.php
includes/ajax-functions.php
includes/forms/template.php

This PR will fix #3820
@DevinWalker This commit is not related to this pr: https://github.com/impress-org/give/commit/99b9647a48036a795e161e2a01543578cf29673a
But find it useful, let me know if you want me to revert it back from this pr.
https://www.useloom.com/share/ae393fa302ce440189647895342857af
https://www.useloom.com/share/77e585c7a6c543e9bfb6280f9b164e52

fix: nonce verification error when logging in/out between donations #3820

---

includes/class-give-db-donors.php
includes/misc-functions.php
includes/shortcodes.php

This PR is to support https://github.com/impress-org/give-gift-aid/issues/131
I've tested this PR with the PR of issue https://github.com/impress-org/give-gift-aid/issues/131

fix: patch security issue that allows generation of any declaration form with a URL string #131

---

includes/shortcodes.php

Adds filter for Grid Shortcode query arguments
Adds a single filter allowing for modification of query arguments used when retrieving forms that will be output in the Grid Shortcode

Adds filter for Grid Shortcode query arguments

---

includes/admin/dashboard-widgets.php

This pr will resolve #3929 
Test with DB which has 3000+ donations

feat: load dashboard widget with ajax

---

includes/admin/tools/export/give-export-donations-functions.php
includes/class-give-background-updater.php

This PR resolves #3919 
I've tested this issue manually with PHP 7.2.

fix: review Liquid Web's PHP 7.2 compatibility report #3919

---

includes/emails/class-give-email-tags.php
tests/unit-tests/tests-email-tags.php

This PR will fix https://github.com/impress-org/give/issues/3922

fix:support {payment_total} tag in email subject

---

assets/src/js/frontend/give-misc.js

This PR will fix https://github.com/impress-org/give/issues/3905

fix: snippet added for make compatible X theme and Cornerstone plugin

---

includes/emails/class-give-email-tags.php

This PR will fix https://github.com/impress-org/give/issues/3943

fix: email tag description changed as per suggestion

---

includes/process-donation.php

fix: add server side validation to check for empty credit card fields #3948

---

includes/admin/tools/export/class-batch-export-donors.php

This Pr will fix https://github.com/impress-org/give/issues/3864

fix: prevent error when exporting CSV between two dates

---

includes/admin/admin-actions.php
includes/class-give-donor.php

This PR will fix https://github.com/impress-org/give/issues/3961

fix: prevent PHP notice when edit donor address 

---

includes/user-functions.php

This PR will fix https://github.com/impress-org/give/issues/3971
I have prepared video of my testing and in that I have mentioned the actual reason.
https://www.useloom.com/share/18b7728364f3421c9518f19052e5cedd

fix: ensure donor mailing addresses match when exporting to csv

---

includes/user-functions.php

Revert "fix: ensure donor mailing addresses match when exporting to csv"

---

includes/donors/backward-compatibility.php
includes/forms/template.php
includes/user-functions.php

this PR will resolve #3917 
1) Get address on basis of donor and user id
2) Exporting donor CSV

fix: ensure donor mailing addresses match when exporting to csv #3971

---

includes/class-give-email-access.php

This PR is to support https://github.com/impress-org/give-recurring-donations/issues/806
I've tested this PR with https://github.com/impress-org/give-recurring-donations/pull/808 to ensure that the issue is not reproduced as per the steps to reproduce

fix: allow user to access subscriptions directly from the email link #806

---

includes/admin/tools/export/class-batch-export.php

This pr will fix #4006 
https://www.useloom.com/share/8754500fcb244040994bf7c72a4afdc1

fix: complete all possible export process steps #4006

---

includes/admin/tools/export/give-export-donations-exporter.php
includes/admin/tools/export/give-export-donations-functions.php

This PR will fix #3979 
https://www.useloom.com/share/dc95ae7c01a8476eb7a5f34fc5081d78
[ Please ignore background nocies]

feat: add donation notes to fields to be exported in donation export tool #3979

---

includes/misc-functions.php

fix: correctly display license status in system info #3975

---

includes/class-give-donate-form.php
tests/unit-tests/tests-donate-form-class.php

This PR will fix #4020 
Running PHPUnit test

fix: improve return value of `Give_Donate_Form::get_goal()` #4020

---

includes/deprecated/deprecated-functions.php
includes/misc-functions.php

Refactored `give_get_host()` to include additional hosts found: https://github.com/mathetos/Whos-My-Host/blob/master/whos-my-host.php#L210-L220
I also deprecated the unused function `give_is_host()`.
Resolves #3356 
- Manually
- Refactor function

fix: improve web host detection in System Info#3356

---

assets/src/js/admin/admin-scripts.js

This PR will resolve #3351 
https://www.useloom.com/share/d4ad7bdca527481b9f384eaf4363e8ea

fix: prevent multiple Ajax query on search in chosen #3351

---

includes/admin/upgrades/class-give-updates.php
includes/admin/upgrades/upgrade-functions.php
includes/class-give-background-updater.php
includes/class-give-cache-setting.php
includes/class-give-license-handler.php
includes/install.php
includes/setting-functions.php

This PR will fix #3872 
Running PHPUnit test

feat: auto load Give options in Give_Cache to prevent frequent multiple queries #3872

---

includes/process-donation.php

This PR will resolve #4025 
https://www.useloom.com/share/9899f6cba3404459bea5b65addfb1d94

fix: make the email check case-insensitive #4025

---

assets/src/js/admin/admin-settings.js
includes/admin/settings/class-settings-general.php

fix: update currency format to match selected currency #3187

---

includes/payments/class-give-payment.php

Alternative to #4017 #4016 
I imported the donation CSV successfully because we are using this filter in that functionality.
ref: https://github.com/impress-org/give/blob/b35a8084a7a3f2348774c369cd9ad8aa63028afa/includes/admin/import-functions.php#L837

refactor: update give_update_donor_information filter  position

---

package-lock.json
webpack.config.js

Updates `webpack.config.js` to prevent the following errors when running `npm run production`:
The custom`UglifyJsPlugin` settings were causing errors for unknown reasons, likely an incompatibility in versions regarding webpack/Babel/UglifyJS. After testing the webpack 4 defaults (without explicitly setting `optimization` in the webpack config) I found the results to be adequate for our purposes and decided to move forward using the webpack 4 defaults. 
`wp-pot` was encountering an error when parsing TCPDF directories, so a globbing pattern was added to exclude those directories since they would not contain any strings that need translated anyways.
Manually tested the following:
- `npm run dev` works with sourcemaps for JS/CSS
- `npm run production` works with webpack 4 optimizations for …

chore: ensure production script runs smoothly

---

includes/admin/shortcodes/abstract-shortcode-generator.php
includes/admin/shortcodes/shortcode-give-donation-grid.php
includes/admin/shortcodes/shortcode-give-donation-history.php
includes/admin/shortcodes/shortcode-give-form.php
includes/admin/shortcodes/shortcode-give-goal.php
includes/admin/shortcodes/shortcode-give-login.php
includes/admin/shortcodes/shortcode-give-profile-editor.php
includes/admin/shortcodes/shortcode-give-receipt.php
includes/admin/shortcodes/shortcode-give-register.php
includes/admin/shortcodes/shortcode-give-totals.php

This PR will resolve #3233 
Tested by visiting shortcode panel for each shortcode on shortcode builder.

feat: add documentation links to shortcode builder #3233

---

includes/process-donation.php

This PR will fix #4039 
Passed all Acceptance Criteria

fix: ensure logged-in users without donor accounts can donate #4039

---

.babelrc
assets/src/js/frontend/give-donor-wall.js
package.json

This PR will resolve #4048 
https://www.useloom.com/share/9134c7b3c3b543f5ac8e9605b3b02ae2

fix: make multilevel forms work on IE10 and IE11 #4048

---

.babelrc
assets/src/js/frontend/give-donor-wall.js
give.php
includes/admin/emails/abstract-email-notification.php
includes/admin/emails/class-email-notifications.php
includes/class-give-donate-form.php
includes/class-give-scripts.php
includes/emails/class-give-email-tags.php
languages/give.pot
package-lock.json
package.json
readme.txt

`release/2.4.4` was checkout from `release/2.5.0` which cause of inclusion of `Give 2.5.0` features/commits into `master`.
To quickly remove unwanted commits from `master`, we can rewrite `master` branch history.
**Note: before merging this pr into `master`, we have to reset it to tag `2.4.3`.**
`git reset --hard 76928daa5a835798bd6413a3eb073ee83d0ab86f`.
I took a back of the current `master` branch here: https://github.com/ravinderk/Give/commits/backup/master
I checked Travis unit test result and all test is passing on this: https://travis-ci.org/impress-org/give/branches

Merge fixup for master

---

includes/admin/class-admin-settings.php
includes/admin/emails/abstract-email-notification.php
includes/admin/emails/class-email-notifications.php

This pr will resolve #3989
https://www.useloom.com/share/2dc94d18d73145a89fec80a18c3284a4
Note: I create issue branch from `master` which I have on my local because I saw that we need to resolve extra commit related issue in `release/2.4.4` and `master`.

fix compatibility with iThemes Sync #3989

---

tests/e2e/specs/shortcode-give-form-multiple-forms.test.js
tests/e2e/specs/shortcode-give-form-same-form-twice.test.js
tests/e2e/specs/test-utility.js

fix: increase jest test timeout to prevent frequent test failure #4060 #4067

---

includes/api/class-give-api.php

This PR will resolve #4071
I am successfully able to run the query as mentioned in #4071.

fix: getting unexpected JSON result from API #4071

---

includes/class-give-background-updater.php

This pr will resolve #4065 
Ran DB update successfully on GvieWP database as well as on multisite

fix: make db upgrade background process compatible with multisite #4065

---

includes/admin/tools/export/class-batch-export-donors.php
includes/admin/tools/export/give-export-donations-exporter.php

This pr will fix #4078 #4079
https://www.loom.com/share/89338d93fc934b71a041f443e6058e94

fix: prevent exporting donors and donations from failing #4078 #4079

---

tests/e2e/specs/test-utility.js

This pr will resolve #4087
All test passing without any issue: https://travis-ci.org/impress-org/give/builds/527724471

fix: prevent frequently failing form grid jest test #4087

---

includes/admin/tools/export/give-export-donations-functions.php

This pr will resolve #4085 
https://www.loom.com/share/4719dca0be2646bd96f909a20e782e04

fix: resolve exporter not respecting category or tag filters #4085

---

assets/src/css/frontend/forms.scss

Added an `@media` responsive style to fix width of the title "Mr, Mrs" wrap.
Resolves #3571 
- Manually
- Style Bug Fix

style: fix width of title field for mobile resolutions 

---

includes/forms/functions.php
includes/misc-functions.php
templates/shortcode-goal.php

This PR will resolve #4100
https://www.loom.com/share/267206c705704b2cb69ca7a43cbf81fe

fix: add a thousand separator to goal when displaying number of donors and number of donations #4100

---

includes/actions.php
includes/admin/donors/class-donor-table.php
includes/admin/emails/class-donor-register-email.php
includes/admin/emails/class-email-notifications.php
includes/admin/emails/class-new-donor-register-email.php
includes/class-give-async-process.php
includes/class-notices.php
includes/emails/template.php
includes/formatting.php
includes/forms/functions.php
includes/gateways/actions.php
includes/payments/functions.php
includes/process-donation.php

This PR will resolve #3857 #3327 
**Note: I created helper function as per https://github.com/impress-org/give/issues/3857 and refactor code as we described here https://github.com/impress-org/give/issues/3327. I create a sperate issue to refactor whole core code:https://github.com/impress-org/give/issues/4103**
Process donation and PHPUnit tests.

refactor: remove repetitive sanitization of post variables #3327

---

assets/src/css/admin/util.scss
includes/admin/tools/export/class-give-export-donations.php
includes/admin/tools/views/html-admin-page-exports.php

fix: long form title in chosen select box breaks styling of page #4099

---

includes/admin/admin-actions.php
includes/admin/donors/donor-actions.php
includes/admin/donors/donor-functions.php
includes/emails/functions.php
includes/shortcodes.php

This PR resolves #4113 
Please check the testing video https://www.loom.com/share/f72a54e55fb5451bbfd81f41aca7fda6

fix: improve logic for donor and user profile disconnection #4113

---

includes/donors/class-give-donor-wall.php

This PR is to resolve and immune to SQL inject for donor wall functionality.
Please check the testing video: https://www.loom.com/share/7ea3e5164539455baf88f863a95e4471

fix: ensure that sql injection doesn't work for donor wall

---

includes/admin/admin-actions.php
includes/admin/plugins.php
includes/admin/shortcodes/class-shortcode-button.php
includes/admin/tools/export/give-export-donations-functions.php
includes/ajax-functions.php
includes/deprecated/deprecated-filters.php
includes/deprecated/deprecated-functions.php
includes/forms/template.php
includes/misc-functions.php
includes/process-donation.php
includes/shortcodes.php
includes/template-functions.php
templates/email-login-form.php
templates/history-donations.php
templates/payment-processing.php
templates/shortcode-login.php
templates/shortcode-receipt.php

This PR contains a few code improvement changes.

code improvement

---

includes/forms/functions.php

This Pr will fix #4132 
https://www.loom.com/share/2316d236ca9d46abb012857c96e47c9b

fix: make give_send_back_to_checkout() work in multisite install #4132

---

README.md
assets/src/css/admin/setting-license.scss
assets/src/css/admin/settings.scss

Fixes #4127 by increasing color contrast to the settings descriptions for accessibility and readability reasons. 
Visiual confirmation after running `npm run dev`
CSS changes to admin settings description color only.

fix: increase text contrast for better accessibility and legibility on licensing screen #4127

---

includes/actions.php
includes/admin/add-ons/actions.php
includes/admin/admin-actions.php
includes/admin/donors/class-donor-table.php
includes/admin/emails/class-donor-register-email.php
includes/admin/emails/class-email-notifications.php
includes/admin/emails/class-new-donor-register-email.php
includes/class-give-async-process.php
includes/class-notices.php
includes/emails/template.php
includes/formatting.php
includes/forms/functions.php
includes/gateways/actions.php
includes/gateways/stripe/includes/admin/admin-actions.php
includes/gateways/stripe/includes/class-give-stripe-customer.php
includes/gateways/stripe/includes/class-give-stripe-invoice.php
includes/gateways/stripe/includes/give-stripe-helpers.php
includes/gateways/stripe/includes/payment-methods/class-give-stripe-card.php
includes/payments/functions.php
includes/process-donation.php

This issue will resolve #4103 
Running the PHPunit test.

fix: remove give_get_super_global function from Give 2.5.0

---

includes/payments/class-payments-query.php
tests/unit-tests/tests-payments-query.php

This PR will fix #1893
Running PHPUnit test on local

Add PHPUnit test for Give_Payments_Query #1893

---

includes/admin/admin-actions.php
includes/class-give-license-handler.php

This PR resolves #4154 
I've tested this PR as per the testing video and the acceptance criteria on the issue.
**Video Link:** https://www.loom.com/share/ffd16bbdb5de4d588bf5cb779806ac3e

feat: improve license nag workflow #4154

---

assets/src/js/admin/stripe-admin.js
includes/gateways/stripe/includes/admin/admin-actions.php
includes/gateways/stripe/includes/give-stripe-helpers.php

fix: ensure that Stripe connect banner is loaded via Give notices #4157

---

assets/src/js/admin/admin-add-ons.js
includes/admin/settings/class-settings-license.php
includes/class-give-license-handler.php

This PR will resolve #4172 
Tested all `Acceptance Criteria`

fix: polish user workflow license functionality issues #4172

---

includes/misc-functions.php

This PR will resolve #4176
Checked with `Acceptance Criteria`.

fix: prevent fatal error when refresh licenses #4176

---

includes/class-give-cache.php

This PR will resolve #4187
Tested with DB as mentioned in https://secure.helpscout.net/conversation/877510722/41643/

fix: prevent webpage crash when edit form #4187

---

assets/src/js/frontend/give-stripe.js
includes/gateways/stripe/includes/class-give-stripe-webhooks.php

This PR resolves https://github.com/impress-org/give-recurring-donations/pull/868

fix: ensure donors can update their subscription amount without problems #867

---

includes/admin/give-metabox-functions.php

This PR will resolve #3141
Tested by updating/editing form settings.

refactor: replace deprecated give_get_custom_attributes fn with give_get_attribute_str #3141

---

assets/src/js/frontend/give-donations.js
includes/forms/template.php

Description
As well, displays properly on page load and switching countries.
Resolves #4201 and #4191 
- Manually
- Bug fix

fix: ensure that required state field properly adds and removes required attributes #4201

---

includes/formatting.php
templates/shortcode-goal.php

This PR resolves https://github.com/impress-org/give-currency-switcher/issues/236
Please check the currency switcher PR https://github.com/impress-org/give-currency-switcher/pull/238 for more information.

fix: correctly support human readable large formatting #236

---

README.md

The `readme.md` file wasn't very clear about how to get started on developing within our plugin. I made changes to make it more clear on how to get started.
- Removed WP.org readme fluff
- Added emojis 
- Reviewed with @ravinderk 	
- Multiple devs have reviewed
- doc update

optimize the github readme for developers looking to contribute

---

assets/src/js/frontend/give-stripe.js

This PR resolves https://github.com/impress-org/give-stripe/issues/413
Please check PR description for more information about testing: https://github.com/impress-org/give-stripe/pull/415

fix: resolve errors when selecting Apple Pay or Google Pay as the default payment method #413

---

README.md

There was a couple of typos in the Readme, I just cleaned them up a bit. The only true change was the 'npm run dev' should have been 'npm run watch' if I'm not mistaken.
I have looked over the readme and all seems good.

Typo fixes on README

---

includes/forms/template.php

As a developer, I want to be able to progmatically edit the submit button text only. A filter exists to edit the HTML but it becomes difficult to just change the text. A simple filter could help with this.
I added a filter and was able to successfully change the text.

Add filter give_donation_form_submit_button_text to update button text

---

includes/gateways/stripe/includes/actions.php

fix: show stripe credit card fields after update #4274

---

README.md
assets/src/css/admin/stripe-admin.scss
give.php
includes/forms/template.php
includes/gateways/stripe/class-give-stripe.php
includes/gateways/stripe/includes/actions.php
includes/gateways/stripe/includes/admin/admin-actions.php
includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
languages/give.pot
readme.txt

- Resolves conflicts with Stripe edge case issues.
- Minor typo fixes
- One new filter
- Manually
- Bug fixes largely

release 2.5.9

---

includes/gateways/stripe/includes/payment-methods/class-give-stripe-checkout.php

This PR resolves #4281 
I've tested this PR as per the acceptance criteria on the issue description

fix: make stripe checkout donation with featured image #4281

---

includes/gateways/stripe/includes/class-give-stripe-customer.php
includes/gateways/stripe/includes/class-give-stripe-payment-method.php

fix: update card in Stripe on expiration date change #4280

---

includes/gateways/stripe/includes/class-give-stripe-checkout-session.php
includes/gateways/stripe/includes/payment-methods/class-give-stripe-checkout.php

fix: don't charge 2% application fee for Stripe Checkout 2.0 payments #4287

---

includes/admin/add-ons/add-ons.php

This Pr will fix #4307 
Locally tested.

fix: correct Give website URL in add-ons header

---

assets/src/css/admin/chosen.scss
assets/src/css/admin/forms.scss
assets/src/css/admin/give-admin-global.scss
assets/src/css/admin/give-admin.scss
assets/src/css/admin/settings.scss
assets/src/css/frontend/theme-compatibility.scss
includes/class-give-scripts.php
webpack.config.js

1. Audited styles for WP 5.3+ and resolved container issue with 2020 Theme
2. Resolved styling issue with amount fields
3. Resolved styling issue for Stripe Connect banner
Resolves #4305 
- Manually cross-browser
- Style fixes

style: resolve TwentyTwenty conflicts, WP 5.3+ and Stripe Connect banner

---

includes/admin/upgrades/upgrade-functions.php
includes/class-give-roles.php
includes/database/class-give-db-donors.php
tests/unit-tests/tests-donors-db.php
tests/unit-tests/tests-roles.php

This Pr will resolve #4221 
This is tested locally with [Members](https://wordpress.org/plugins/members/) plugin
Bugfix (non-breaking change which fixes an issue

 refactor: meta capabilities shouldn't be assigned to roles

---

includes/actions.php
includes/admin/add-ons/actions.php
includes/class-give-cron.php
includes/misc-functions.php

This PR will resolve #4318 
https://www.loom.com/share/5177f2ccb5b84f1aaef82cf570fb9877

fix: resolve updates not showing up without a refresh licenses

---

includes/gateways/stripe/includes/class-give-stripe-customer.php

This Pr will resolve #4328 
I tried the same steps to reproduce the issue ad mentioned in the issue description.
Each new card will be attached to the Stripe customer.

fix: Error with payment method in Stripe #4328

---

includes/gateways/stripe/includes/payment-methods/class-give-stripe-checkout.php

This PR will resolve #4329 
https://www.loom.com/share/44ef79fb7093406dac154be45489f172

fix: Stripe Checkout redirect loop

---

assets/src/js/admin/reports/components/list/index.js
assets/src/js/admin/reports/components/list/style.scss
assets/src/js/admin/reports/pages/overview-page/index.js
includes/reports/class-reports-admin.php
languages/give.pot
package.json

Resolves #4332 
Added list component for Reports UI. The component accepts children and an onScrollEnd prop which fires as a calllback function when the component is scrolled all the way to the bottom. 
Tested locally and with no errors logged in console.

feature: add list component

---

assets/src/js/admin/reports/components/donor-item/index.js
assets/src/js/admin/reports/components/donor-item/style.scss
assets/src/js/admin/reports/components/donor-item/utils/index.js
assets/src/js/admin/reports/pages/overview-page/index.js

Resolves #4334 
Added donor item component which accepts image, name, email, count and total as props.
Tested locally in browser and logged no errors to the console.

feature: add donor item component

---

includes/admin/admin-actions.php
includes/admin/class-blank-slate.php

This Pr will resolve #4365 
I tested this pr with recurring issue: https://github.com/impress-org/give-recurring/pull/910

refactor: make GiveBlank_Slate extendable

---

assets/src/js/admin/reports/components/location-item/index.js
assets/src/js/admin/reports/components/location-item/style.scss
assets/src/js/admin/reports/pages/overview-page/index.js

Resolves #4335 
Added LocationItem component for use inside List component. The LocaitonItem component accepts city, state, country, flag, count and total as props.
Tested locally and logged no errors in browser console.

feature: add simple location item

---

assets/src/js/admin/reports/components/chart/index.js
assets/src/js/admin/reports/components/chart/utils/index.js
assets/src/js/admin/reports/components/legend/index.js
assets/src/js/admin/reports/components/legend/style.scss
assets/src/js/admin/reports/components/legend/utils/index.js
assets/src/js/admin/reports/components/list/style.scss
assets/src/js/admin/reports/pages/overview-page/index.js

Resolves #4371 
Tested locally and throws no errors in browser.

feature: add optional legends to charts

---

includes/emails/actions.php

This Pr will resolve #4379 #4185 
https://www.loom.com/share/7b75e15b4131492681d7629844bd3af8

fix: No email notifications are sent for new donations

---

assets/src/js/admin/reports/app/pages/overview-page/index.js
src/API/API.php
src/API/Endpoints/Reports/PaymentMethods.php

Resolves #4398 
Adds new 'payment-methods' endpoints that uses existing logic to return data about earnings via different payment methods.
Tested locally and throws no errors in browser console. Passed all PHPUnit tests.
n/a

feature: add payment methods report endpoint

---

assets/src/js/admin/reports/app/pages/overview-page/index.js
assets/src/js/admin/reports/components/donor-item/index.js
assets/src/js/admin/reports/components/donor-item/style.scss
assets/src/js/admin/reports/components/rest-list/index.js
package-lock.json
package.json
src/API/Endpoints/Reports/TopDonors.php

Resolves #4415 
This PR creates a new 'top-donors' endpoint which uses the existing Give_Donors_Query class to aggregate top donor information for a given period. The endpoint returns the data in the correct shape for use in the RESTList component. The PR also address some issues with the RESTList component, and adds a new URL prop to the DonorItem component, making an item linking through to the appropriate donor overview page.
It has been tested locally and throws no errors in the browser console. Passed PHPUnit tests.

feature: add top donors endpoint

---

assets/src/js/admin/reports/app/pages/overview-page/index.js
assets/src/js/admin/reports/components/donor-item/index.js
assets/src/js/admin/reports/components/donor-item/style.scss
src/API/Endpoints/Reports/RecentDonations.php

Resolves #4427 
This PR solves issues raised by @ravinderk regarding the implementation of the recent donations endpoint, and styling concerns in the DonorItem component. 
Tested locally and throws no errors in the browser console. Passes PHPUnit tests. 
Long donor emails are now truncated with an ellipsis: 

fix: resolve recent donations endpoints issues

---

templates/form-styles/elegent/assets/css/form.scss
templates/form-styles/elegent/sections/introduction.php

feature: add style for amount section 

---

assets/src/js/admin/reports/app/pages/overview-page/index.js
assets/src/js/admin/reports/components/mini-chart/index.js
src/API/API.php
src/API/Endpoints/Reports/Donors.php

Resolves #4435
This PR adds the donors report endpoint, which uses the Give_Donors_Query class to return data on number of donors over time, as well as a count of the total number of donors for the selected period and the current trend in donors.
Tested locally and throws no errors in the browser console. Passed PHPUnit tests.

feature: scaffold donors endpoint

---

includes/admin/donors/class-donor-table.php
includes/donors/class-give-donors-query.php

This PR will resolve #4444 
I tested this change on database provided by @Benunc 

fix: prevent fatal error on donor list page

---

includes/forms/functions.php
includes/forms/template.php

Changes in PR does not resolve any issue but can prevent any future conflict with currency switcher.
Process donation with and without currency switcher

fix: pass currency to give_maybe_sanitize_amount to prevent conflict and minor code formatting

---

includes/admin/tools/views/html-admin-page-system-info.php

This PR resolves https://github.com/impress-org/give-square/issues/58
I've tested this with PR of issue https://github.com/impress-org/give-square/issues/58

fix: add new action hook for system info and auto format code

---

assets/src/css/admin/welcome.scss
includes/admin/class-give-welcome.php

I swapped out the old mailchimp form for the new activecampaign one created in AC:
Fixes #4492 
- Tested to ensure contacts are appearing in Active Campaign in the correct list
Screenshot displaying an entry that is properly populated in newsletter:
- Newsletter Refactor

refactor: swapped mailchimp form for activecampaign and styled

---

assets/src/js/admin/reports/app/style.scss
assets/src/js/admin/reports/components/card/style.scss
assets/src/js/admin/reports/components/chart/style.scss
assets/src/js/admin/reports/components/chart/utils/crosshair.js
assets/src/js/admin/reports/components/chart/utils/index.js
assets/src/js/admin/reports/components/donor-item/style.scss
assets/src/js/admin/reports/components/legend/style.scss
assets/src/js/admin/reports/components/list/style.scss
assets/src/js/admin/reports/components/mini-chart/index.js
assets/src/js/admin/reports/components/mini-chart/style.scss
assets/src/js/admin/reports/components/mini-chart/utils/index.js
assets/src/js/admin/reports/components/mini-period-selector/style.scss
assets/src/js/admin/reports/components/period-selector/style.scss
assets/src/js/admin/reports/components/rest-list/index.js
assets/src/js/admin/reports/components/rest-list/style.scss
assets/src/js/admin/reports/components/table/style.scss
assets/src/js/admin/reports/components/tooltip/index.js
assets/src/js/admin/reports/components/tooltip/style.scss
assets/src/js/admin/reports/widget/index.js
assets/src/js/admin/reports/widget/style.scss
src/API/Endpoints/Reports/AverageDonation.php
src/API/Endpoints/Reports/FormPerformance.php
src/API/Endpoints/Reports/TopDonors.php
src/API/Endpoints/Reports/TotalDonors.php
src/API/Endpoints/Reports/TotalIncome.php
src/API/Endpoints/Reports/TotalRefunds.php
src/Views/Admin/DashboardWidgets/Reports.php

Resolves #4495 
Tested locally and throws no errors in browser console. Passed PHPUnit tests.

fix: resolve specific outstanding ui issues

---

includes/admin/admin-pages.php

fix: donations menu link shouldn't appear to subscribers

---

assets/src/js/admin/stripe-admin.js
assets/src/js/frontend/give-stripe-sepa.js
includes/admin/give-metabox-functions.php
includes/gateways/stripe/class-give-stripe.php
includes/gateways/stripe/includes/admin/admin-actions.php
includes/gateways/stripe/includes/admin/admin-helpers.php
includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
includes/gateways/stripe/includes/give-stripe-helpers.php
includes/gateways/stripe/includes/give-stripe-scripts.php
includes/gateways/stripe/includes/payment-methods/class-give-stripe-sepa.php
webpack.config.js

This PR will resolve #4313
Locally

Stripe SEPA integration

---

includes/admin/class-give-welcome.php
includes/admin/welcome.php

Minor grammar fix on the Welcome pages.
Changes the text on the welcome page.

Fix minor grammar issue in welcome message

---

src/Views/Form/Templates/Sequoia/Sequoia.php
src/Views/Form/Templates/Sequoia/assets/css/form.scss
src/Views/Form/Templates/Sequoia/assets/css/recurring.scss
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #4665 
This PR introduces frontend styles for recurring donation inputs as they appear in the Sequoia form template.
This PR affects the Sequoia styles, and Sequoia template class. It introduces the recurring.scss file.
Test frontend appearance of the recurring donation inputs, both set to present duration and user defined. Are the options available as you'd expect?

feature: recurring donation input is now styled correctly in Sequoia form template

---

give.php
readme.txt

This PR includes all changes in `develop` with the addition to the version bump and change log update.

chore: add change log for 2.6.3 and bump version

---

includes/gateways/stripe/class-give-stripe.php
includes/gateways/stripe/includes/deprecated/deprecated-functions.php

This PR resolves https://github.com/impress-org/give-stripe/issues/448
Check files in the PR.
I have replicated the issue by following the steps to reproduce and after fixing verified that the issue is resolved. Check acceptance criteria on the issue description for more details.

fix: fatal error due to stripe when disabled and accessing donor profile page in admin #448

---

src/Views/Form/Templates/Sequoia/assets/js/form.js

This PR improves logic for setting up recurring and fee recovery opt-in checkboxes, so that if the box is checked by default, the highlighted border is present by default. The PR uses the existing setupCheckbox functionality to make sure these checkboxes function consistently with other prominent checkboxes in forms (newsletter checkboxes, etc). 
Previously, if an admin setup a checkbox to be checked by default, the checkbox would load in a checked state as expected, but lacking the highlighted border that should accompany the checkmark. Because the "active" class was not being applied on load, it also meant that when a user unchecked the box it would cause the highlighted border appear. 
This PR affects frontend logic related to rendering the form, specifically the fee recovery and …

fix: recurring optin border is now visible when set to checked by default

---

give.php
readme.txt
templates/shortcode-form-grid.php

This contains the hotfix for Form Grid and also fixes a few typos in the change log.

2.7.1 merging to master for release

---

src/Views/Form/Templates/Sequoia/Sequoia.php
src/Views/Form/Templates/Sequoia/assets/css/newsletter.scss
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #4932 
Adds the JS and CSS required for the checkbox to display like other subscription add-ons.

style: add support for the activecampaign checkbox for future add-on

---

assets/src/js/admin/onboarding-wizard/app/steps/fundraising-needs/index.js
assets/src/js/admin/onboarding-wizard/app/steps/fundraising-needs/style.scss
assets/src/js/admin/onboarding-wizard/app/steps/location/index.js
assets/src/js/admin/onboarding-wizard/app/steps/location/style.scss
assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js
assets/src/js/admin/onboarding-wizard/app/steps/your-cause/style.scss
assets/src/js/admin/onboarding-wizard/components/card/index.js
assets/src/js/admin/onboarding-wizard/components/card/style.scss

Resolves #4955 
Removes inline padding values from Card component implementation in favour of fixed sizes and flexbox content alignment.

Remove inline padding from Card component implementations.

---

src/Session/Accessor.php
src/Session/SessionDonation/SessionObjects/Donation.php
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #4959 
This resolves the issue with the anonymous checkbox not respecting the checked property value which resulted in anonymous donations being incorrectly marked as not anonymous for the multi-step form template.
-   [x] Manually tested

Fixes anonymous donations with the multi-step form template

---

assets/src/js/admin/onboarding-wizard/app/index.js
assets/src/js/admin/onboarding-wizard/app/steps/location/index.js
assets/src/js/admin/onboarding-wizard/app/store/actions.js
assets/src/js/admin/onboarding-wizard/app/store/reducer.js
assets/src/js/admin/onboarding-wizard/utils/index.js
composer.json
composer.lock
src/Onboarding/Helpers/FormatList.php
src/Onboarding/Routes/LocationRoute.php
src/Onboarding/Routes/SettingsRoute.php
src/Onboarding/Wizard/Page.php
src/ServiceProviders/Onboarding.php
tests/src/Onboarding/Helpers/FormatListTest.php
tests/src/bootstrap.php

Resolves #4970
-   [x] Tests included

Onboarding REST API is now scaffolded

---

assets/src/js/plugins/give-api/form.js
src/PaymentGateways/PayPalCommerce/AdvancedCardFields.php
src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php
src/PaymentGateways/PayPalCommerce/DonationProcessor.php
src/PaymentGateways/PayPalCommerce/Models/PayPalOrder.php
src/PaymentGateways/PayPalCommerce/Repositories/MerchantDetails.php
src/PaymentGateways/PayPalCommerce/ScriptLoader.php
src/PaymentGateways/PayPalCommerce/assets/css/advanced-card-fields.scss
src/PaymentGateways/PayPalCommerce/assets/css/index.scss
src/PaymentGateways/PayPalCommerce/assets/js/AdvancedCardFields.js
src/PaymentGateways/PayPalCommerce/assets/js/DonationForm.js
src/PaymentGateways/PayPalCommerce/assets/js/PaymentMethod.js
src/PaymentGateways/PayPalCommerce/assets/js/SmartButtons.js
src/PaymentGateways/PayPalCommerce/assets/js/index.js
webpack.config.js

Resolves #4891 
This pr adds a feature to process donation with PayPal advanced card fields.
This pr does not affect existing core functionality.
- Added new javascript class `PaymentMethod` for PayPalCommerce 
In this pr, you have to test the credit card fields as mentioned above screenshot.
You need a test credit card and you can create them on [`developer.paypal.com/developer/creditCardGenerator`](https://developer.paypal.com/developer/creditCardGenerator/)
To test negative results on payment, you can pass error code in the header which …

Donation can be process with PayPal Advanced Card fields

---

readme.txt
uninstall.php

Resolves #4981
The newly implemented Service Provider architecture is hooked into `plugins_loaded`, which does not run on uninstall.

Manually initialize the main Give class on uninstall.

---

readme.txt
src/Route/Form.php
src/Views/IframeView.php

Resolves #4952 
Updates the Form Template Route URL structure to use query strings instead of a rewrite so that all permalink configurations (or lack there of) are supported, including the default value of "plain".
| Permalink Setting | Form Template | Confirmation |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/89334071-f7757d80-d663-11ea-96d3-9a2d71d6712a.png) | ![image](https://user-images.githubusercontent.com/10858303/89334119-0a884d80-d664-11ea-8ec3-591b6956ed55.png) |![image](https://user-images.githubusercontent.com/10858303/89339980-0dd40700-d66d-11ea-991a-3522d7c44f6f.png) |
| ![image](https://user-images.githubusercontent.com/10858303/89334178-1e33b400-d664-11ea-8b00-536e27bc07bf.png) | …

Form Templates now support all permalink settings

---

assets/src/js/admin/onboarding-wizard/components/card-input/index.js
assets/src/js/admin/onboarding-wizard/components/card-input/selected.js
assets/src/js/admin/onboarding-wizard/components/card-input/style.scss
assets/src/js/admin/onboarding-wizard/components/checkmark/index.js

Resolves #4988
Re-purposes the outline as an active/focus state, as opposed to underlining the card title. The selected state is now represented with a checkmark.
- Adds a `<Selected />` sub-component to `<CardInput />` for selected state.
- Re-structures `<CardInput />` so that the card of a selected input can be targeted by CSS.
- Adds a prefix to the `id` attribute of the `<Checkmark />` component to avoid conflict with `<Selected />`.
Single select, focused and selected
Single select, focused and not selected
Multi-select, focused and selected
Multi-select, focused and not selected
-   [x] Keyboard accessible
- …

Onboarding Wizard Card Inputs are keyboard accessible

---

assets/src/js/admin/onboarding-wizard/app/steps/features/index.js

#530
Updated the title/subtitle of the Features Step to better communicate its purpose (and be unique compared to the Add-ons Step).
> Since we are actually reflecting the users choices in the next step, I'm more comfortable presenting this step as form configuration whereas previously we were tip-toeing around that concept with the add-ons in this step. @kevinwhoffman 

Onboarding Features step tite/subtitle better communicates purpose

---

assets/src/js/admin/onboarding-wizard/components/card/style.scss

#5030
The icons on the Your Cause step had extra spacing that didn't match the Features and Add-ons steps.
Card/Icon components on Your Case, Features, and Add-ons steps.

Onboarding Card Icon spacing is now normalized

---

assets/src/js/admin/onboarding-wizard/components/button/style.scss

#5030
Updated the border-radius of the `<Button />` components to match the buttons/elements in the donation form preview.

Onboarding buttons now match the donation form in the preview.

---

src/Onboarding/Setup/templates/index.html.php

Fix typo in PayPal card in the Setup Page.

---

src/Onboarding/Setup/Handlers/AdminNoticeHandler.php
src/ServiceProviders/Onboarding.php

Resolves #5064 
Hooks in an output buffer to remove admin notices.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/89960060-e8667080-dc0b-11ea-8b55-f99f082b2d39.png) | ![image](https://user-images.githubusercontent.com/10858303/89960044-db498180-dc0b-11ea-9514-906ac2789b03.png) |

Setup Page does not display admin notices.

---

assets/src/js/admin/onboarding-wizard/app/index.js

Onboarding Cause Type no longer has a default value.

---

assets/src/css/admin/setup.scss
assets/src/js/admin/admin-setup.js
src/Onboarding/Setup/PageView.php
src/Onboarding/Setup/templates/index.html.php
src/Onboarding/Setup/templates/row-item.html

Resolves #5085
- Removes "Webhooks Configured" button in favor of toggling the completed, crossed-out row item.

Setup Page Stripe UI is now updated

---

assets/src/js/admin/onboarding-wizard/app/steps/introduction/index.js
assets/src/js/admin/onboarding-wizard/components/continue-button/index.js
assets/src/js/admin/onboarding-wizard/utils/index.js
src/Onboarding/FormRepository.php
src/Onboarding/Routes/FormRoute.php
src/Onboarding/Setup/Page.php
src/Onboarding/Setup/PageView.php
src/Onboarding/Setup/templates/index.html.php
src/Onboarding/Wizard/Page.php
src/ServiceProviders/Onboarding.php

Onboarding Preview Form is now generated on Start Setup

---

composer.json
composer.lock

Resolves #5099
Downgraded the installed version of PHPUnit from ^9 to ^5 in order to support PHP5.6.

Installed version of PHPUnit now supports PHP5.6

---

includes/admin/settings/class-settings-display.php

Resolves #5109
This is a simple typo fix for a the Terms & Conditions field description.

Correct typo in terms & conditions field description

---

assets/src/css/admin/setup.scss
src/Onboarding/Setup/templates/index.html.php

Setup Page design updates

---

assets/src/js/admin/admin-setup.js
src/Onboarding/Setup/templates/index.html.php

Resolves #5130
No gateways connected:
Stripe connected, webhooks not configured:
Stripe webhooks configured:

Improve Stripe Setup completed state.

---

assets/src/js/admin/onboarding-wizard/components/card-input/style.scss
assets/src/js/admin/onboarding-wizard/components/continue-button/style.scss
assets/src/js/admin/onboarding-wizard/components/step-link/style.scss

Resolves #5123
Sets the cursor to `pointer` for clickable elements.

Set a pointer cursor for clickable elements in the wizard.

---

assets/src/css/admin/setup.scss
assets/src/js/admin/admin-setup.js

Resolves #5129
Adds text to the Stripe Webhooks button when polling the server to differentiate from a loading state (which appears stuck).

Add text to Stripe webhooks polling state.

---

assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js
assets/src/js/admin/onboarding-wizard/utils/index.js
src/Onboarding/Config/CauseTypes.php
src/Onboarding/Wizard/Page.php

Onboarding Cause Types are now updated

---

src/Onboarding/Setup/PageView.php
src/Onboarding/Setup/templates/index.html.php

Resolves #5144
Updates the gateway link, add-ons link, and Getting Started link.
- Removes the `Setup\PageView::give_link()` method, which is no longer necessary because the implemented short URLs include UTM.

Setup Page external links now use short URLs

---

CHANGELOG.md
assets/src/js/admin/onboarding-wizard/app/index.js
assets/src/js/admin/onboarding-wizard/utils/index.js
src/Onboarding/Wizard/Page.php

Resolves #5076
Localizes `give_settings` values for `base_country`, `base_state`, and `currency`, which are used as defaults for the Location step of the Onboarding Wizard.

Onboarding Wizard now defaults to already selected country, state, and currency.

---

CHANGELOG.md
includes/admin/admin-actions.php
includes/admin/admin-pages.php
includes/admin/forms/class-metabox-form-data.php
includes/admin/settings/class-settings-display.php
includes/class-give-license-handler.php
includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php

Resolves #5153
Links updated according to https://docs.google.com/spreadsheets/d/19dVgyqrWEqx1Cn9iilpZzDa6Cm4cWFfa094nUgpblD4/edit#gid=0

Plugin links now use short URLs

---

CHANGELOG.md
src/Views/Form/Templates/Sequoia/Sequoia.php
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #5112
Loops over text `input`s that are not required and appends `(optional)` the the placeholder.

Add function to denote non-required inputs as optional.

---

CHANGELOG.md
includes/admin/forms/class-metabox-form-data.php

Resolves #5119
Quick fix to help prevent card testing. 
New donation forms created post-update

Increase minimum donation amount default

---

CHANGELOG.md
assets/src/js/admin/onboarding-wizard/components/button/style.scss

Resolves #5164
Added hover styles to the Wizard button component to match that used by the form.
Note: The button sizes are different, made obvious by the screenshots below, but not sure this is an issue in the context of the Wizard.
| | Wizard | Form Preview |
| --- | --- | --- |
| | ![Screen Shot 2020-08-20 at 14 52 07](https://user-images.githubusercontent.com/10858303/90812933-db750b80-e2f4-11ea-8d07-d8821c8a3dd8.png) | ![Screen Shot 2020-08-20 at 14 51 51](https://user-images.githubusercontent.com/10858303/90812938-dc0da200-e2f4-11ea-9bf0-b0853925839f.png) |
| `:hover` | ![Screen Shot 2020-08-20 at 14 52 12](https://user-images.githubusercontent.com/10858303/90812928-dadc7500-e2f4-11ea-9680-75234db04d03.png) | ![Screen Shot 2020-08-20 at 14 52 …

Add Wizard button hover styles.

---

CHANGELOG.md
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #5160
Reduced the scope of marked optional fields in the Multi-Step template to the User Info fieldset.
Removes credit card fields from the scope of the optional label text.

Update query selector of optional field label text.

---

CHANGELOG.md
includes/admin/settings/class-settings-general.php
src/Onboarding/Helpers/LocationList.php
src/Onboarding/Routes/LocationRoute.php
src/Onboarding/Wizard/Page.php

Resolves #5162 
Extracts a `LocationList` helper class to decorate `give_get_country_list()` and `give_get_states()` into a consistent format.
Also sets a specific placeholder for the base country setting select, to avoid the incorrect fallback to "Select a form".
- Localized countries, states in the `Wizard\Page`.
- Location Endpoint for states.
Country does not have an empty option, with a default.
State does have an empty option, with no default.

Refactor country and state lists for normalized format.

---

CHANGELOG.md
assets/src/css/admin/setup.scss

Resolves #5166
Reduces the padding on the Setup Page container to better match the original design.
| --- | --- |
| ![Screenshot_2020-08-20 Setup GiveWP ‹ WordPress — WordPress(1)](https://user-images.githubusercontent.com/10858303/90812028-99979580-e2f3-11ea-8a3d-3d60d5f74198.png) | ![Screenshot_2020-08-20 Setup GiveWP ‹ WordPress — WordPress](https://user-images.githubusercontent.com/10858303/90812035-9a302c00-e2f3-11ea-9666-cd055dec27ca.png) |

Reduce padding on Setup Page container.

---

assets/src/css/frontend/forms.scss
src/Views/Form/Templates/Sequoia/Actions.php
src/Views/Form/Templates/Sequoia/assets/css/feerecovery.scss
src/Views/Form/Templates/Sequoia/assets/css/ffm.scss
src/Views/Form/Templates/Sequoia/assets/css/form.scss
src/Views/Form/Templates/Sequoia/assets/css/newsletter.scss
src/Views/Form/Templates/Sequoia/assets/css/receipt.scss
src/Views/Form/Templates/Sequoia/assets/css/recurring.scss
src/Views/Form/Templates/Sequoia/assets/css/tributes.scss
src/Views/Form/Templates/Sequoia/assets/js/form.js
src/Views/Form/Templates/Sequoia/sections/form-navigator.php

Resolves #5193
This PR adds RTL support to the Multi-step template.
Multi-step form template.
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/4222590/91188883-178fde00-e6f2-11ea-8695-02498b2e47c8.png)  | ![image](https://user-images.githubusercontent.com/4222590/91188983-2ffff880-e6f2-11ea-9123-5f8b6d2b816e.png)|
1. Change the site language to العربية المغربية in the settings at Settings > General
2. View a multistep form on the front end.
3. Click through to the payment gateway …

fix: multi-step forms should support RTL styles

---

CHANGELOG.md
includes/admin/admin-actions.php

Resolves #4800
The HTML output of our link was incorrect and breaking the avatar plugin's upload profile image field. Correcting it resolved the issue and did not have an side effects.
-   [x] Tests included

Fix html output of user profile field and resulting in a fix for the user avatar plugin

---

includes/admin/give-metabox-functions.php

Resolves #5268 
This PR  adds support for multi checkbox options on the Edit Form page ( Donation Form Options ).
Donation Form Options 
The easiest way to test it is by adding this block of code to the `functions.php` file.
```
add_filter( 'give_metabox_form_data_settings', function( $sections, $formId ) {
$fields = [
[
'id'            => 'give_multicheck_options_admin',
'name'          => 'Multiple checkbox test',
'default'       => 1,
'type'          => 'multicheck',
'wrapper_class' => 'give_multicheck_options_admin',
'options'       => [ …
```

feature: Add multi checkbox support for add-on settings

---

.storybook/main.js
give.php
package-lock.json
package.json
src/Campaigns/AdminPageView.php
src/Campaigns/ServiceProvider.php
src/Campaigns/functions.php
src/Campaigns/resources/js/app/components/CampaignCard.js
src/Campaigns/resources/js/app/components/CampaignCard.stories.js
src/Campaigns/resources/js/app/components/CampaignCardList.js
src/Campaigns/resources/js/app/components/ProgressBar.js
src/Campaigns/resources/js/app/components/ProgressBar.stories.js
src/Campaigns/resources/js/app/index.js
src/Campaigns/resources/templates/submenu.php
webpack.config.js

Resolves #5265  
Adds a new admin submenu for Campaigns, along with some React app scaffolding and components.

Campaigns are now accessible via the WordPress Admin

---

package-lock.json
src/Campaigns/ServiceProvider.php
src/Campaigns/blocks/CampaignPreview/index.js
src/Campaigns/blocks/FeaturedImage/index.js
src/Campaigns/blocks/index.js
src/Campaigns/config/give_campaigns.cpt.php
src/Campaigns/resources/editor-styles.scss

Resolves #5291
- Rename "Campaign Editor" to "Campaign Preview"
- Rename "Campaign Featured Image" to "Featured Image"

Campaign blocks are clearly named

---

src/Revenue/Migrations/CreateRevenueTable.php
src/Revenue/OnDonationHandler.php
src/Revenue/Repositories/Revenue.php
src/Revenue/RevenueServiceProvider.php

Resolves #5297 
Record revenue in give_reveneue table when inserting a new donation and delete it automatically when deleting donation.
- Added cascade delete rule to `give_revenue` table
Test this pr with https://github.com/impress-org/give-funds/pull/31
Complete following step before testing:

Update revenue data when change occur related to donation

---

src/Revenue/Repositories/Revenue.php

Resolves #5303 
This PR fixes a potential bug by validating the data after applying the filter. 

fix: validate revenue data after applying filter

---

includes/install.php
src/Revenue/Migrations/AddPastDonationsToRevenueTable.php
src/Revenue/Repositories/Revenue.php
src/Revenue/RevenueServiceProvider.php

Resolves #5288 
In this pr, I added data migration to create revenue from donations.
Test this pr by running database upgrade with or without fund addon.
Use this branch to test with give fund addon: https://github.com/impress-org/give-funds/pull/31

Add migration for past donations to create  revenue

---

CHANGELOG.md
src/MultiFormGoals/resources/js/blocks/multi-form-goal/index.js
src/MultiFormGoals/resources/views/multiformgoal.php

Closed #5313
Adds `supports`, `align` property to the block definition, which inherits alignment controls.
Moves the `<div />` wrapper inside of the InnerBlocks check `else` condition, so that the block's wrapper can control alignment.
> **_NOTE: The block's styles are not yet polished - the screenshots show container width._**
**Container Width _(default)_**
**Wide Width**
- Add a Multi-Form Goal block.
- Change the alignment control on the outer-most block.

Multi-Form Goal block now supports "wide" alignment

---

assets/src/js/frontend/paypal-commerce/AdvancedCardFields.js
assets/src/js/frontend/paypal-commerce/CustomCardFields.js
assets/src/js/frontend/paypal-commerce/DonationForm.js
assets/src/js/frontend/paypal-commerce/PaymentMethod.js
assets/src/js/frontend/paypal-commerce/SmartButtons.js
assets/src/js/frontend/paypal-commerce/index.js
package-lock.json
package.json
src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php
src/PaymentGateways/PayPalCommerce/ScriptLoader.php

In favor of https://github.com/impress-org/give-recurring/issues/984
This PR adds support to Paypal smart buttons to process the subscription.
This pr does not pr existing functionality.
Follow testing instructions mentioned in https://github.com/impress-org/give-recurring/pull/985

PayPal donations use paypal sdk to process subscription with smart buttons

---

give.php
src/Revenue/DonationHandler.php
src/Revenue/OnDonationHandler.php
src/Revenue/Repositories/Revenue.php
src/Revenue/RevenueServiceProvider.php

In favor of https://github.com/impress-org/give-funds/pull/40 https://github.com/impress-org/give-recurring/pull/987
This pr refactor revenue related code to make it accessible in the addon.

Refactor code in-favor of recurring and fund addon

---

CHANGELOG.md
src/MultiFormGoals/ProgressBar/Model.php
src/MultiFormGoals/ProgressBar/Query.php

Resolves #5343
This PR replaces the Give and WP APIs with optimized queries, which greatly decrease the processing time of calculating totals and counts.
| Data Size | `develop` | `chore/multi-form-goal-optimize-5343` | |
| --- | --- | --- | --- |
| 1 form, 1 donation | 0.016172885894775 |  0.0064060688018799 | 60.3901% decrease |
| 6 forms, 284 donations | 2.2876069545746 | 0.010143995285034 | 99.5566% decrease |
- Updates `Give\MultiFormGoals\ProgressBar\Model` `::getTotal()` and `::getDonationCount()`  with direct queries, as opposed to using the Give  or WP APIs.
- Refactors `getEarnings()` and `getTotal()` and  into a single `getTotal()` method.
-   [x] [Self …

chore: Refactor Multi-Form Goal metrics.

---

src/Revenue/Repositories/Revenue.php

In favor of fund feature for the fund and recurring addon.
This pr adds `give_revenue_insert_data` filter in `Revenue: insert` function.
It does not affect existing functionality.
-   [x] Labels applied if docs are needed
- Test this pr with the recurring addon pr: https://github.com/impress-org/give-recurring/pull/987

add filter before filter review data before inserting it to database table

---

CHANGELOG.md
src/MultiFormGoals/resources/css/common.scss

Resolves #5351
- Removes `overflow: hidden!important`
- Updates CSS selectors to apply a redundant `border-radius` on the media element directly.
Column width control un-obscured.
Border radius enforced on media.

Multi-Form Goal block no longer obscure column controls

---

CHANGELOG.md
assets/src/js/frontend/give-donations.js
give.php
readme.txt

Resolves #5354 
This fixes a typo in the class which prevented the state selector in the JS from finding the new state field. This, in turn, broke the donation flow as the element wasn't found.
When billing detail fields are displayed for non-US countries.
Follow the reproduction instructions on #5354. You should be able to successfully process a donation, now.

Donations now process for non-US countries using billing details

---

CHANGELOG.md
src/MultiFormGoals/resources/views/progressbar.php
webpack.config.js

Resolves #5347
Encapsulates progress bar HTML/CSS using the Shadow DOM. Styles are loaded via a `<style />` tag in the HTML which are carried over into the Shadow DOM.
**Note:** the Shadow DOM is only implemented at the time of render and not within the block editor.
- Adds a separate build for styles.
-   [x] Changelog updated\
- Enqueue extra styles on the page
- Progress Bar component should not inherit styles

Multi-Form Goal Progress Bar styles are encapsulated via a Shadow DOM

---

CHANGELOG.md
src/MultiFormGoals/ProgressBar/Model.php
src/MultiFormGoals/ProgressBar/Query.php

Closes #5356 
- Replaces the post/meta join with a post/revenue join.
- `Give\MultiFormGoals\ProgressBar/Model::getTotal()` now accounts for the amount as stored in the lowest unit of currency.
- Make a donation in USD (base currency).
- Make a donation in EUR.
- Create a Multi-Form Goal block.
- Total reflects the two donations in the base currency.

Multi-Form Goal Block uses the Revenue table to calculate progress towards a goal.

---

CHANGELOG.md
src/MultiFormGoals/ProgressBar/Model.php
src/MultiFormGoals/ProgressBar/Query.php

Closes #5358 
Includes revenue items for payments with a status of `publish` and `give_subscription`.
```sql
SELECT
sum( revenue.amount ) as total,
count( payment.ID ) as count
FROM wp_posts as payment
JOIN wp_give_revenue as revenue
ON revenue.donation_id = payment.ID
WHERE
payment.post_type = 'give_payment'
AND
payment.post_status IN ( 'publish', 'give_subscription' )
```
- Create a recurring donation.
- Manually trigger a renewal.
- Goal total should include both the donation and the renewal

Multi-Form Goal total now includes renewals

---

CHANGELOG.md
src/PaymentGateways/PayPalCommerce/AdminSettingFields.php
src/PaymentGateways/PayPalCommerce/ScriptLoader.php

Resolves #5369
To resolve issue , I removed recurring addon ad and list item from on success onboarding notice.
- Test recurring ad without recurring addon installed on website

Improve PayPal Donations payment gateway setting page UX

---

CHANGELOG.md
includes/admin/give-metabox-functions.php

Resolves #5383 
This PR adds support for multi-line radio options on the Edit Donation Form screen ( Donation Form Options section  ).
Donation Form Options section.
The easiest way to test it is by adding this block of code to the `functions.php` file.
```
add_filter( 'give_metabox_form_data_settings', function( $sections, $formId ) {
$fields = [
[
'name'          => esc_html__( 'Fund Display', 'give-funds' ),
'id'            => 'give_funds_form_choice',
'wrapper_class' => 'give_funds_options_choice',
'type' …
```

Add support for multi-line radio buttons on Edit Donation Form screen

---

CHANGELOG.md
assets/src/css/admin/forms.scss
assets/src/css/admin/reports.scss
assets/src/css/admin/settings.scss

Resolves #5393
- Updates description styles to match WordPress core in `color` and `font-style`.
- Updates radio setting description to align with the label, instead of the input.
- Form metabox settings
- Widget metabox settings
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/96614564-44193e00-12ce-11eb-98b3-a4ac9111d411.png) | ![image](https://user-images.githubusercontent.com/10858303/96614594-4f6c6980-12ce-11eb-82f7-d452fb1eafe8.png) |
| Form Settings | Widget |
| --- | --- |
| ![Screenshot_2020-10-20 Edit Donation Form ‹ WordPress — WordPress](https://user-images.githubusercontent.com/10858303/96614274-f270b380-12cd-11eb-8417-4e93ae8982ff.png) Note: Aligned with label | ![image](https://user-images.githubusercontent.com/10858303/96615711- …

Field description text is now accessible and aligned

---

readme.txt

Resolves #5386 
This takes the changes from #5411 and moves them to the `release/2.9.0` changes to avoid pulling upstream changes from `develop`. The scope is to simply update the readme.txt file for 2.9.0.

Update readme.txt for 2.9 updates

---

CHANGELOG.md
assets/src/css/frontend/give-stripe.scss
assets/src/js/frontend/give-stripe.js
src/PaymentGateways/Stripe/DonationFormElements.php
src/ServiceProviders/PaymentGateways.php

Resolves #5422
In PR https://github.com/impress-org/givewp/pull/5209, we updated tripe modal width logic to fix an issue that causes most of rendering related issues across devices. I updated logic to use `flex` to centralize modal which fixes most of the issues.
- I updated modal `max-width` with to `500px` which makes it compatible with most of the language. You can read more about this issue: https://github.com/impress-org/givewp/issues/5206
- In PR https://github.com/impress-org/givewp/pull/5419, to resolve the Stripe issue I added a hidden input field to the donation form to know which type of stripe checkout active and we are using this only on the frontend. I find out that the best way is to add a data attribute to the donation form, so I added a minor fix in this PR.
-   [x] …

Stripe Modal renders without any issue across all screens

---

CHANGELOG.md
src/Views/Form/Templates/Sequoia/assets/css/form.scss

Resolves #5437
Adds `-webkit-appearance: none;` to submit buttons to prevent iOS from messing with it.
- Multi-step form template
Steps to replicate: 
1. Create a multistep form
2. View it on iOS
3. click through to the final "donate now" button.

Prevent iOS from messing with our submit buttons

---

src/Tracking/TrackClient.php
src/Tracking/TrackingData/DonationFormsData.php
src/Tracking/TrackingData/PluginsData.php
src/Tracking/TrackingData/ThemeData.php

Resolves https://github.com/impress-org/givewp/issues/5487
I find out that on the `switch_theme` action hook, `is_child_theme` does not return correct output that why i add custom logic to detect child theme and add parent theme data.
**Without the parent theme:**
```
Array
(
[name] => Twenty Fifteen
[slug] => twentyfifteen
[url] => https://wordpress.org/themes/twentyfifteen/
[version] => 2.4
[author] => Array
(
[name] => the WordPress team
[url] => https://wordpress.org/
)
[server] => Array
(
[ip] => 127.0.0.1
[Hostname] => localhost
[os] => Darwin Ravinders-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
[PhpVersion] => 7.3.5
[CurlVersion] => Array
(
[version] => 7.54.0
[sslSupport] => 1
)
)
[website] => …
```

Include parent theme data into non-sensetive tracking data

---

CHANGELOG.md
src/Onboarding/Setup/templates/dismiss.html
src/Onboarding/Setup/templates/index.html.php
tests/e2e/integration/onboarding/setup_page_spec.js

Onboarding Setup Page is e2e tested

---

CHANGELOG.md
assets/src/js/admin/onboarding-wizard/app/steps/addons/index.js
assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js
assets/src/js/admin/onboarding-wizard/app/steps/features/index.js
assets/src/js/admin/onboarding-wizard/app/steps/introduction/index.js
assets/src/js/admin/onboarding-wizard/app/steps/location/index.js
assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js
assets/src/js/admin/onboarding-wizard/components/button/index.js
assets/src/js/admin/onboarding-wizard/components/card-input/index.js
assets/src/js/admin/onboarding-wizard/components/continue-button/index.js
assets/src/js/admin/onboarding-wizard/components/dismiss-link/index.js
assets/src/js/admin/onboarding-wizard/components/donation-form/index.js
assets/src/js/admin/onboarding-wizard/components/select-input/index.js
assets/src/js/admin/onboarding-wizard/components/step-link/index.js
src/Onboarding/Setup/templates/dismiss.html
src/Onboarding/Setup/templates/index.html.php
src/Onboarding/Setup/templates/row-item.html
tests/e2e/integration/onboarding/onboarding_wizard_spec.js
tests/e2e/integration/onboarding/setup_page_spec.js
tests/e2e/support/commands.js
tests/e2e/support/index.d.ts

Resolves #5546
Cypress e2e tests have been implemented for both the Setup Page and the Onboarding Wizard.
Details on what is tested are listed in the epic's issue, #5546.
See tests/e2e/README.md for setup instructions.

Onboarding is e2e tested

---

CHANGELOG.md
package-lock.json
package.json
src/DonorProfiles/resources/js/app/components/avatar-control/index.js
src/DonorProfiles/resources/js/components/app/index.js

Resolves #5556 
This PR replaces existing dropzone logic with the React Dropzone library, allowing for a more robust, easily maintained uploading experience.
This PR affects front-end rendering logic related to the AvatarControl component used in editing donor profiles.

Donor Profile edit UI now uses React Dropzone

---

CHANGELOG.md
composer.json
give.php
readme.txt
src/Framework/Migrations/MigrationsRegister.php
src/Framework/Migrations/MigrationsRunner.php
src/MigrationLog/MigrationLogFactory.php
src/MigrationLog/MigrationLogModel.php
src/MigrationLog/MigrationLogRepository.php
src/MigrationLog/MigrationLogServiceProvider.php
src/MigrationLog/MigrationLogStatus.php
src/MigrationLog/Migrations/CreateMigrationsTable.php
src/MultiFormGoals/MultiFormGoal/Shortcode.php

Resolves #5579
This PR implements the logic needed to create and use the new migrations table. 

Migrations table is now implemented

---

src/Form/LegacyConsumer/Commands/SetupFieldPersistance.php
src/Form/LegacyConsumer/ServiceProvider.php

Form Consumer persists custom field values as donation meta

---

CHANGELOG.md
src/Form/LegacyConsumer/FieldView.php
src/Form/LegacyConsumer/templates/checkbox.html.php
src/Form/LegacyConsumer/templates/select.html.php
src/Form/LegacyConsumer/templates/text.html.php
src/Form/LegacyConsumer/templates/textarea.html.php
src/Framework/FieldsAPI/FormField.php
src/Framework/FieldsAPI/FormField/FieldAttributes.php
tests/unit/tests/Form/LegacyConsumer/FieldViewTest.php
tests/unit/tests/Framework/FieldsAPI/FormField/FieldAttributesTest.php

Resolves #5622
- Introduces the `attributes()` and `getAttributes()` methods fields for custom attributes.
- Updates the `Form\LegacyConsumer` to inject custom attributes.
Testing instructions are outlined in the following files:
- `tests/unit/tests/Form/LegacyConsumer/FieldViewTest.php`
- `tests/unit/tests/Framework/FieldsAPI/FormField/FieldAttributesTest.php`

Custom fields now support arbitrary attributes

---

CHANGELOG.md
src/Form/LegacyConsumer/Commands/CommandFactory.php
src/Form/LegacyConsumer/Commands/SetupFieldPersistance.php
src/Form/LegacyConsumer/Commands/SetupPaymentDetailsDisplay.php
src/Form/LegacyConsumer/ServiceProvider.php

Resolves #5621 
- Adds a new metabox to the payment details screen for displaying custom field values.

Custom field values now display in payment details.

---

src/API/Endpoints/Logs/GetLogs.php
src/Log/Admin/Logs/index.js
src/Log/Assets.php
src/Log/ValueObjects/LogType.php
src/MigrationLog/Admin/Migrations/index.js
src/Views/Components/Modal/index.js
src/Views/Components/Modal/styles.module.scss
src/Views/Components/PeriodSelector/style.module.scss
src/Views/Components/Spinner/index.js
src/Views/Components/Spinner/style.module.scss
src/Views/Components/Table/index.js

Resolves #5646
This PR adds a variety of UI tweaks and fixes.  
Logs and Migrations list table; Modal window.
Navigate to `Donations -> Tools -> Logs` and `Donations -> Tools -> Data`

 Migrations and Logs UI is now polished

---

CHANGELOG.md
assets/src/css/frontend/forms.scss
src/Form/LegacyConsumer/FieldView.php
src/Form/LegacyConsumer/templates/checkbox.html.php
src/Views/Form/Templates/Sequoia/assets/css/form.scss
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #5587
- Adds custom data attributes for style selection.
- Updates the Sequoia JS to call `setupCheckbox` on custom checkbox fields.
- Updates the Sequoia CSS to handle input replacement for custom checkbox fields.
- Updates the Legacy CSS to align custom checkbox fields.
NOTE: The Sequoia template still needs some work with regards to spacing, but that will be addressed in another change. The spacing styles are more general than the checkbox field and apply to all custom fields based on template location. I'll need to inspect each section and tweak the styles. For example, placing the fields before the gateways doesn't need any tweaks, but the insert location for after donation amount is flush with the side.
- …

Form Templates now support custom checkbox fields

---

src/DonorProfiles/resources/js/app/components/auth-modal/index.js
src/Tracking/UsageTrackingOnBoarding.php

Resolves #5656
Clarifies more contextual docs
Donor Dashboard login screen
Admin notice for telemetry opt-in

Contextual docs are further clarified

---

tests/unit/tests/DonorProfiles/Repositories/DonationsTest.php

Asserts that the array returned by the Donations Repository contains the correct amount and user email of the donation.

Donor Profile tests that Receipt Info contains donation data

---

src/DonorProfiles/Admin/Settings.php

Resolve spelling mistake  Donations > Settings > General

---

CHANGELOG.md
src/DonorProfiles/Repositories/Donations.php
src/DonorProfiles/Tabs/DonationHistoryTab/DonationsRoute.php
src/DonorProfiles/resources/js/app/tabs/donation-history/content.js
src/DonorProfiles/resources/js/app/tabs/donation-history/dashboard-content.js

Resolves #5689
This PR adds a "No Donations" notice in Donor Dashboard for Donors with no donations.
Donor Dashboard 
- Dashboard
- Donation History
Delete all donations related to your user and then check the Donor Dashboard page.

Donors with no donations now see a "No Donations" notice in Donor Dashboard

---

CHANGELOG.md
src/DonorProfiles/Tabs/DonationHistoryTab/DonationsRoute.php
src/DonorProfiles/resources/js/app/tabs/donation-history/content.js
src/DonorProfiles/resources/js/app/tabs/donation-history/dashboard-content.js

Resolves #5701
This PR adds error logging to the Donor Dashboard. 
Donor Dashboard
|Donor Dashboard | Logs |
|---|---|
| ![image](https://user-images.githubusercontent.com/4222590/110826980-e80f8000-8295-11eb-901f-1a54d4083712.png) | ![image](https://user-images.githubusercontent.com/4222590/110827064-fe1d4080-8295-11eb-9f55-82eb7394b3e6.png) |
The easiest way to trigger an error would be to make changes to one of the SQL queries in `src/DonorProfiles/Repositories/Donations.php`, e.g changing the table name or table column name will throw an error for sure.  …

Donor Dashboard errors are now logged

---

CHANGELOG.md
src/Revenue/Migrations/AddPastDonationsToRevenueTable.php
src/Revenue/Repositories/Revenue.php

Resolves #5748
Use `DB::insert` function for better error reporting.
This will affect only revenue table queries.
I will discuss this with @alaca 

Stop revenue migration on error

---

.distignore
CHANGELOG.md
includes/admin/admin-actions.php
includes/admin/class-admin-settings.php
includes/admin/donors/class-donor-table.php
includes/admin/payments/class-payments-table.php
includes/admin/tools/views/html-admin-page-system-info.php
includes/gateways/stripe/includes/payment-methods/class-give-stripe-checkout.php

Resolves #5808 
This tackles a number of standard issues brought to us by the wp.org Plugin Reviews Team. Please see the Issue for a full list of items covered.
The tweaks are pretty sporadic. The most significant change is the File field type in the Settings API.
Please reach out to me for testing instructions.
-   [ ] ~Includes unit and/or end-to-end tests~

Adjustments are made to meet wp.org standards

---

includes/country-functions.php

Renamed Orissa to Odisha.

---

CHANGELOG.md
src/DonorDashboards/App.php
src/DonorDashboards/resources/js/app/components/annual-receipt-table/annual-receipt-row/index.js
src/DonorDashboards/resources/js/app/components/avatar-control/index.js
src/DonorDashboards/resources/js/app/components/currency-control/index.js
src/DonorDashboards/resources/js/app/components/donation-row/index.js
src/DonorDashboards/resources/js/app/components/select-control/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/index.js
src/DonorDashboards/resources/js/app/components/subscription-receipt/index.js
src/DonorDashboards/resources/js/app/components/subscription-row/index.js
src/DonorDashboards/resources/js/app/components/subscription-table/index.js
src/DonorDashboards/resources/js/app/components/tab-menu/index.js
src/DonorDashboards/resources/js/app/tabs/annual-receipts/content.js
src/DonorDashboards/resources/js/app/tabs/annual-receipts/index.js
src/DonorDashboards/resources/js/app/tabs/dashboard/index.js
src/DonorDashboards/resources/js/app/tabs/donation-history/content.js
src/DonorDashboards/resources/js/app/tabs/donation-history/dashboard-content.js
src/DonorDashboards/resources/js/app/tabs/donation-history/index.js
src/DonorDashboards/resources/js/app/tabs/donation-history/stats/index.js
src/DonorDashboards/resources/js/app/tabs/edit-profile/address-controls/index.js
src/DonorDashboards/resources/js/app/tabs/edit-profile/address-fields/index.js
src/DonorDashboards/resources/js/app/tabs/edit-profile/content.js
src/DonorDashboards/resources/js/app/tabs/edit-profile/email-controls/index.js
src/DonorDashboards/resources/js/app/tabs/edit-profile/index.js
src/DonorDashboards/resources/js/app/tabs/recurring-donations/content.js
src/DonorDashboards/resources/js/app/tabs/recurring-donations/index.js

Related #5818
Adds missing translatable strings and registers the translations with WordPress.
Also, cleans up some orphaned semicolons.

Donor Dashboard is now fully translatable

---

CHANGELOG.md
assets/src/js/admin/admin-importer.js

Resolves #5840 
I find out existing Dm ready bootstrap logic does not most of the time in Firefox, so I implemented `DOMContentLoaded` javascript event to bootstrap logic correctly on DOM ready.
This pull request only affects the import donations feature.
You should not able to reproduce the issue as mentioned in the issue description with widely-used browsers mentioned in `Acceptance Criteria`.

Use javascript core event to bootstrap import donations logic

---

.github/workflows/release.yml
CHANGELOG.md
composer.json
composer.lock
src/DonorDashboards/App.php
src/DonorDashboards/resources/js/app/components/donor-info/index.js
src/DonorDashboards/resources/js/app/index.js
src/DonorDashboards/resources/js/app/tabs/index.js
webpack.config.js

Resolves #5818
Updates the `@wordpress/i18n` dependency to use the "external" package, meaning that it will be sourced from `window.wp.i18n` instead of bundling the package.
This resolves the issue of manual translations using `wp.hooks.filters`.
- Adds a new "external" to the webpack config.
- Adds `wp-i18n` as a dependency to the Donor Dashboard script registration.
```js
wp.hooks.addFilter(
'i18n.gettext',
'myplugin/filter-gettext',
function( translation, text, domain ) {
return '{TRANSLATED}';
}
);
```
Here is a companion plugin for adding custom translations, see https://gist.github.com/kjohnson/6f3016737efc6e03f4071575e7d839f8
-   [x] Changes logged to the …

Donor Dashboard can now be translated using the `i18n.gettext` filter

---

CHANGELOG.md
src/Form/LegacyConsumer/templates/select.html.php

This just adds the `multiple` HTML attribute to the `<select>` when the field allows multiple in the Legacy Consumer’s `select` template.
- Legacy consumer `select` template

Legacy Consumer: support multi-select

---

CHANGELOG.md
src/Form/LegacyConsumer/FieldView.php
src/Form/LegacyConsumer/resources/js/conditinal-fields.js
src/Form/LegacyConsumer/templates/base.html.php
src/Form/LegacyConsumer/templates/checkbox.html.php
src/Form/LegacyConsumer/templates/file.html.php
src/Form/LegacyConsumer/templates/label.html.php
src/Form/LegacyConsumer/templates/radio.html.php
src/Form/LegacyConsumer/templates/select.html.php
src/Form/LegacyConsumer/templates/textarea.html.php
src/Framework/FieldsAPI/Checkbox.php
src/Framework/FieldsAPI/Concerns/HasOptions.php

This pull request implement the following:
- Add conditional visibility support to field type HTML in legacy consumer
- Add options support to the checkbox field.
- Update checkbox field template to render multiple checkboxes in legacy consumer.
- Make checkbox discoverable in visibility condition javascript.
This pull request affects legacy consumer checkbox field output.
Note: Use form field manager: https://github.com/impress-org/give-form-field-manager/pull/358 for testing
- Add custom checkbox field in form field manager
- Add visibility condition to field or define checkbox as visibility controller to another field.
-  Review
- Checkbox output in donation form (legacy and multi step form template )
- Conditional visibility (if any)
- Checkbox value on donation detail page in WP …

[field api] Add options support to checkbox field

---

CHANGELOG.md
src/Views/Form/Templates/Sequoia/Sequoia.php
src/Views/Form/Templates/Sequoia/optionConfig.php

Resolves #5984
This PR sanitizes the "thank-you" section description in accordance with the [allowed HTML of "post content"](https://developer.wordpress.org/reference/functions/wp_kses_post/).
```html
Your contribution means a lot and will be put to good use making a difference.
<p><small>What is in the mug? <a href="#">You decide!</a></small></p>
```
Update the description for step 4 of the Sequoia donation form template.

The "Thank You" section description now supports HTML content

---

src/Framework/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayRegisterAdapter.php
src/Framework/PaymentGateways/Contracts/PaymentGateway.php
src/Framework/PaymentGateways/Contracts/PaymentGatewayInterface.php
src/Framework/PaymentGateways/Contracts/SubscriptionModuleInterface.php
src/Framework/PaymentGateways/PaymentGatewayRegister.php
src/LegacyPaymentGateways/Actions/RegisterPaymentGatewaySettingsList.php
src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php
src/PaymentGateways/Actions/CreateSubscriptionAction.php
src/PaymentGateways/DataTransferObjects/FormData.php
src/PaymentGateways/DataTransferObjects/SubscriptionData.php
src/PaymentGateways/Gateways/TestGateway/TestGateway.php
src/PaymentGateways/ServiceProvider.php
src/Subscriptions/DataTransferObjects/SubscriptionArgs.php
src/Subscriptions/Models/LegacySubscriber.php
src/Subscriptions/Models/Subscriber.php

This introduces a new _subscription module_ concept that is intended to modularly add subscription/recurring support to a PaymentGateway.  This makes it so there is only one PaymentGateway with the flexibility to handle their own subscription logic or mount a subscription module to handle it.  For Give core this will mean our main PaymentGateway classes will live in core and they will each mount their respected subscription modules in the give-recurring add-on.  We will also work on limiting the scope of these modules to just the payment gateway processing for subscriptions.  The majority of core subscription logic will eventually be in give core.
**Add subscription module filter**
```
$testGatewayId = TestGateway::id();
add_filter( "give_gateway_{$testGatewayId}_subscription_module", …
```

New: Add give-recurring subscription module connection

---

src/DonationSummary/resources/css/summary.scss

Depends on #6061
This PR converts the responsive styles of the Donation Summary from "stacked" to "compact".
See https://github.com/impress-org/givewp/pull/6089#pullrequestreview-803039441
| | |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/141220567-637ec716-712f-41f1-97e4-070894b29a6c.png) | ![image](https://user-images.githubusercontent.com/10858303/141220504-7385cad3-ba86-4124-998a-1526b7a0bac7.png) |
| ![image](https://user-images.githubusercontent.com/10858303/141220918-ec835060-9e9f-4536-9160-2df55f8e90cd.png) | ![image](https://user-images.githubusercontent.com/10858303/141220957-476ff2e5-9c85-47c7-afdb-8c3b4c81d7d6.png) |
-   [ …

Refactor: Responsive styles are now "compact"

---

package.json

Quick fix with the `npm run watch` task. 
Simply removed the `--` flag.
See it works:

fix the watch task syntax

---

src/Views/Form/Templates/Classic/Classic.php
src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6085
In this PR the way how _section wrapping_ is done is refactored, and logic to move form submit button in its own section is added as well. 

New: Form submit button is now in its own section 

---

src/DonationSummary/SummaryView.php
src/Views/Form/Templates/Classic/Classic.php
src/Views/Form/Templates/Classic/optionConfig.php
src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6114 
This PR adds Donation Summary section to the Classic Donation template. 
Do not use existing forms for testing and add a new one instead, because some template option names are changed and you will get an error. 

New: Donation Summary section is added 

---

src/Views/Form/Templates/Classic/Classic.php
src/Views/Form/Templates/Classic/resources/css/_header.scss
src/Views/Form/Templates/Classic/resources/css/variables.php
src/Views/Form/Templates/Classic/resources/views/header.php

Resolves #6116
This PR adds support for Donation Goal stats.
Donation Goal stats
1. Create a new form and enable Donation goal
2. View form and make a few donations
3. Check the goal stats

New: Donation Goal stats works

---

src/Views/Form/Templates/Classic/Classic.php
src/Views/Form/Templates/Classic/resources/css/_currencyswitcher.scss
src/Views/Form/Templates/Classic/resources/css/_donate-now.scss
src/Views/Form/Templates/Classic/resources/css/_donation-amount.scss
src/Views/Form/Templates/Classic/resources/css/_donation-summary.scss
src/Views/Form/Templates/Classic/resources/css/_section.scss
src/Views/Form/Templates/Classic/resources/css/form.scss
src/Views/Form/Templates/Classic/resources/js/form.js
src/Views/Form/Templates/Classic/resources/js/not-jquery.js

This pull request implements styles for donation summary, fee recovery, and recurring. I decided to hold off on some other changes that I was going to include with this.
- Classic Template
https://user-images.githubusercontent.com/6908001/143951696-6ea8cf94-0f9a-42c9-9679-8aa87f5e3e07.mp4
_Note: I don’t know why the fees are showing up like `{fees}` here. We will need to follow up with that._
- Ensure that the Fee Recovery and Recurring addons are enabled and configured.
- Make sure you are using a newer form so that the donation summary is enabled.

Fee recovery, recurring, and donation summary for Classic Template

---

src/DonationSummary/resources/js/summary.js
src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6137
This PR resolves the issue where donation summary section was not showing the correct giving frequency info.
Donation summary - giving frequency info.
1. Install Recurring add-on
2. Enable recurring options - Donor's choice and test that
3. Enable recurring options - Admin defined and test that as well

New: Donation summary now displays the correct giving frequency info

---

CHANGELOG.md
includes/gateways/paypal/paypal-standard.php

I recently merge a pull request https://github.com/impress-org/givewp/pull/6057 which fixes the PayPal IPN verification issue in test mode. Although pull request resolves the issue[ it adds a few new necessary functions](https://github.com/impress-org/givewp/pull/6057#pullrequestreview-837048420). I noticed that issue can be resolved by simple trinary condition. this pulls request to address this.
Along with new changes, I updated `paypal-standard.php` file code formatting.

Fix: check for test mode to avoid PayPal IPN validation error

---

src/Framework/PaymentGateways/CommandHandlers/PaymentProcessingHandler.php
src/Framework/PaymentGateways/CommandHandlers/RespondToBrowserHandler.php
src/Framework/PaymentGateways/Commands/PaymentProcessing.php
src/Framework/PaymentGateways/Commands/RespondToBrowser.php
src/Framework/PaymentGateways/PaymentGateway.php
src/Framework/PaymentGateways/Traits/OffsiteGateway.php

New: add new gateway api commands and handlers

---

README.md
readme.txt

We shut down our old dev blog but were still linking to it. I removed the reference to that old site from the readme.md and also updated the readme.txt WP compatibility version to 5.9.
Readme.md
readme.txt
\

Update readme.md to remove old developer blog

---

src/Framework/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayRegisterAdapter.php
src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php
src/PaymentGateways/DataTransferObjects/FormData.php
src/PaymentGateways/ServiceProvider.php

Resolves https://github.com/impress-org/givewp/issues/6164
I replaced `Give_Recurring()->is_recurring ` with `Give_Recurring()->is_donation_recurring` to correctly detect recurring donations.
- I added `$legacyDonationData` to the `FormData` data transfer object which we will use internally to gracefully deprecate action and filter hooks. You can see the use of this property in https://github.com/impress-org/givewp/pull/6154 pull request.
You should not be able to reproduce the issue as per the instruction given in the issue description.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-re …

Use correct method to detect recurring donation in new  payment flow

---

includes/admin/forms/dashboard-columns.php
includes/admin/tools/import/class-give-import-core-settings.php
includes/forms/template.php

Resolves #6171 
This PR escapes the value output for the JSON input field, which is set based on user input via the URL.

Hotfix: Escape output attributes

---

src/DonationForms/resources/admin-donation-forms.tsx
src/DonationForms/resources/components/Pagination.js
src/DonationForms/resources/components/Pagination.module.css
src/DonationForms/resources/components/Pagination.module.scss

Part of #6175
This PR styles the pagination component for the All Forms admin page (with the current CSS reset solution) and cleans up some of its markup (since it no longer needs to conform to the standard WP table markup).
1. Create at least one Donation Form
2. Install GiveWP from this PR
3. Navigate to Donations -> All Forms in the admin
4. Verify that the pagination component works as expected and is properly styled
-   [X] Relevant `@unreleased` tags included in DocBlocks
-   [X] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

enhancement: style the pagination links and clean up their markup

---

src/Framework/PaymentGateways/PaymentGateway.php

Resolves #6182
This PR adds support for handling the `PaymentProcessing` gateway command.

Handle PaymentProcessing gateway command.

---

src/Framework/PaymentGateways/PaymentGateway.php
src/PaymentGateways/Gateways/PayPalStandard/PayPalStandard.php
src/PaymentGateways/Gateways/Stripe/Actions/CreatePaymentIntent.php
src/PaymentGateways/Gateways/Stripe/Traits/CheckoutInstructions.php

For the 2.19 release, these are the contextual docs and error message updates/changes.

Contextual docs changes

---

src/Views/Form/Templates/Sequoia/optionConfig.php

Resolves #6361 
This PR makes the Content input field in Step 2 of a Multi-Step form more intuitive. The input field did not follow the same behavior as the other inputs.  It was the only input with a placeholder and without a default value.
- Multi-step form
- Create a Multi-Step form
- Check Content section in Step 2 for a default value
- Edit value of Content section in Step 2
- View form
- Delete value of Content section in Step 2
- View form

feature: Add default value

---

includes/currencies-list.php

Resolves #4817
Since 2005 until present the currency symbol is RON.  This PR updates the admin symbol
- The romanian currency symbol
- It's really just visual so let's make sure this is accurate when using romanian currency.

Fix: update romanian currency symbol to RON

---

src/PaymentGateways/PayPalCommerce/PayPalCommerce.php
src/PaymentGateways/PayPalCommerce/ScriptLoader.php

Resolves #6386 
This PR enabled Venmo as a PayPal funding source.
- Enable Venmo for PayPal

New: Venmo payments via PayPal are now accepted

---

.github/config/mysql.cnf
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/wordpress.yml
includes/admin/import-functions.php
phpunit.xml
tests/unit/bin/install.sh

The required PHP version for GiveWP was recently bumped to >= 7.0. This PR updates the automated testing process to reflect that. After some discussion, we settled on three PHP versions to test: 7.0, 7.4, and 8.0.
Some notes:
- Testing for Wordpress 5.6 isn't included for PHP 7.4 or 8.0, since they are not compatible
- Testing for PHP 8.0 is currently marked as experimental, and failing 8.0 tests will not halt testing. One test is currently failing on 8.0, but I was unable to get it passing in a short amount of time, and getting this merged seems more important than having all tests passing.
- The release and pre-release workflows have been updated: the testing workflow has been made reusable, and the pre-/release workflows now load it from the file in the GiveWP repo. This should make …

Chore: Increase lower testing PHP version to 7.0 and fix MySQL

---

blocks/donation-form-grid/edit/inspector.js
blocks/donor-wall/edit/inspector.js
includes/admin/forms/class-metabox-form-data.php
src/Donations/Endpoints/Endpoint.php
src/PaymentGateways/PayPalCommerce/PayPalCommerce.php

This is an general polish of the contextual docs. No functionality should be affected. 
- Form Grid and Donor Wall block instructions/edit screen within the block editor,
- PayPal donations settings screen
- Form edit screen (Form Grid tab)
Load those page and make sure they still work. 

Chore: contextual doc audit

---

assets/src/css/admin/block-editor.scss
assets/src/css/frontend/form-grid.scss
assets/src/css/frontend/give-frontend.scss
includes/shortcodes.php
src/Views/Admin/Form/FormGrid-Settings.php
templates/shortcode-form-grid.php

Resolves #
This PR resolves the issue with overriding the Donate button text. Also, Donate button styles are updated, and the Form Grid CTA banner text was updated. 
Form Grid - Donate button. 
1. Create a donation form
2. Add custom donation button text in the Form Grid Section
3. Check that the Donation form renders the donation button with the custom text. 

Fix: Improve Form Grid button design

---

readme.txt

Chore: Add Venmo to Readme

---

src/Donations/Models/Donation.php
src/Donations/Models/DonationNote.php
src/Donations/Repositories/DonationNotesRepository.php
src/Donations/Repositories/DonationRepository.php
src/Donations/ServiceProvider.php
src/Donors/Models/Donor.php
src/Donors/Repositories/DonorRepository.php
src/Subscriptions/Models/Subscription.php
src/Subscriptions/Repositories/SubscriptionRepository.php
src/Subscriptions/ServiceProvider.php

As we continue to improve our codebase, new actions and filters are being created.  To prevent conflict with legacy hooks, the new prefix will be `givewp_` instead of `give_`.  This PR updates the recently added hooks in our model repositories to use this naming convention.
- Donor, Donation, and Subscription repository actions.
These hooks were just released to there is not much to test.  You can use the donation form to create some donations and make sure there's no issues.

Changed: new hooks will use givewp as a prefix

---

src/DonorDashboards/Helpers.php
src/DonorDashboards/Routes/Captcha/ProtectedRoute.php
src/DonorDashboards/Routes/LogoutRoute.php
src/DonorDashboards/Routes/VerifyEmailRoute.php
src/DonorDashboards/Tabs/Contracts/Route.php
src/DonorDashboards/resources/js/app/components/auth-modal/index.js

Resolves #6440
This pull request improves the donor dashboard auto-login feature. The donor will be not auto-login to the donor dashboard if processed a guest donation.
You should not able to replicate https://github.com/impress-org/givewp/issues/6440 issue.

Fix: validate donor before login to donor dashboard

---

src/Framework/PaymentGateways/PaymentGateway.php

Stripe checkout (redirect) process subscription payment on stripe hosted check page. This pull request implement support for the `RedirectOffsite` response for subscription donation.
You should be able to process subscriptions with stripe checkout (redirect).
Use latest recurring donation for testing: https://github.com/impress-org/give-recurring/pull/1119

feature: allow offsite redirect for recurring donations

---

src/Donations/DataTransferObjects/DonationQueryData.php
src/Donations/Factories/DonationFactory.php
src/Donations/Models/Donation.php
src/Donations/Repositories/DonationRepository.php
src/Framework/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayRegisterAdapter.php
src/PaymentGateways/DataTransferObjects/FormData.php
tests/unit/tests/Donations/Models/TestDonation.php
tests/unit/tests/Donations/Repositories/TestDonationRepository.php

Resolves #6523 
The company field is a GiveWP core concept of donation forms and donations.  This PR adds the company property to the Donation model and updates the legacy form implementation to account for the company field.
_Note: While working on this, the company field did not appear to be working properly on updated gateways. This might actually provide that missing functionality for gateways using the new gateway api._
The donation model, legacy gateway adapter, and updated gateways (support for the company field)
N/A
- Add the company field option to a donation form
- Submit the form using an updated gateway like Stripe to verify the field persists
-   [ ] …

Feature: Donation model now has company property

---

includes/user-functions.php
src/Onboarding/Setup/Page.php
tests/unit/framework/helpers/class-helper-form.php

Resolves #6529 
This fixes user-facing language that is grammatically incorrect.
Only affects text within strings, should not affect functionality at all.
-   [ X ] Acceptance criteria satisfied and marked in related issue
-   [ X ] Relevant `@unreleased` tags included in DocBlocks
-   [  ] Includes unit tests
-   [ X ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

Chore/grammar fix#6529

---

assets/src/css/admin/goals.scss
assets/src/css/frontend/form-grid.scss
assets/src/css/frontend/progress-bar.scss
src/Views/Form/Templates/Sequoia/assets/css/form.scss
templates/shortcode-goal.php

Resolves #6534
This pull request resolves the goal progress bar rendering issue.
I find out that this issue was introduced with https://github.com/impress-org/givewp/pull/6476.
**Additional changes**
- I also discovered that goal progress bar edges were not round in the form grid, Give goal shortcode and legacy form template
You should see a correct progress bar on multiple places (mentioned in the issue acceptance criteria)

Fix: goal progress bar rendering correctly

---

package-lock.json
package.json

In this pull request, I update npm packages with `npm audit fix`. this will help to reduce automated pull requests from [`dependabot`](https://github.com/impress-org/givewp/pulls/app%2Fdependabot).

Chore: update npm packages

---

src/Revenue/Listeners/UpdateRevenueWhenDonationAmountUpdated.php
src/Revenue/Repositories/Revenue.php
src/Revenue/RevenueServiceProvider.php
tests/Unit/Revenue/Listeners/UpdateRevenueWhenDonationAmountUpdatedTest.php

Resolves #6548 
Resolves impress-org/give-funds/issues/115
This PR hooks into donation edits to updated the related row in the Revenue table.
- Adds the `updateRevenueAmount()` method to the `Give\Revenue\Repositories\Revenue` class.
1. Manually create a donation.
2. Edit the above donation's amount.
3. The Revenue table should reflect the updated amount.

Revenue amount is now updated when the Donation is edited

---

assets/src/css/admin/settings.scss
includes/admin/emails/class-email-notification-table.php
includes/admin/emails/class-email-setting-field.php
includes/admin/give-metabox-functions.php

Resolves #6560
This PR makes it possible to extend the email sections on the settings page and also the recipient email field. For more details check the attached screenshots.

refactor: makes email sections on the settings page and also the recipient email field extensible/filterable

---

src/Donations/Repositories/DonationRepository.php
src/Donors/Repositories/DonorRepository.php
tests/Unit/Donations/LegacyListeners/DispatchGivePreInsertPaymentTest.php
tests/Unit/Donations/Models/TestDonation.php
tests/Unit/Donations/Models/TestDonationNote.php
tests/Unit/Donations/Repositories/TestDonationNoteRepository.php
tests/Unit/Donations/Repositories/TestDonationRepository.php
tests/Unit/Donors/Models/TestDonor.php
tests/Unit/Donors/Repositories/TestDonorRepository.php
tests/Unit/Subscriptions/Actions/TestGenerateNextRenewalForSubscription.php
tests/Unit/Subscriptions/Models/TestSubscription.php
tests/Unit/Subscriptions/Repositories/TestSubscriptionRepository.php

Resolves #6592
This PR makes the the `give()->donations->update()` method also update the "wp_give_donationmeta" entries
The donation repository update method.
1. Use [this zip file](https://github.com/impress-org/give-manual-donations/actions/runs/3328280639) of the manual donations addon to create a manual recurring donation
2. Check the `give_donationmeta` table and you'll see that the `subscription_id` meta key now is saved.
More details here: https://github.com/impress-org/give-manual-donations/pull/174#discussion_r1004440401
**!!!ATTENTION!!!** If you got a message like this: `Activation Error: You must have the Give core version 2.23.1+ for the Manual Donations add-on to activate.` when try to active the manual donations addon, add the following line in your wp-config.php file: …

Fix: donor/donation models now update missing meta

---

give.php
src/DonationForms/DataTransferObjects/DonationFormQueryData.php
src/DonationForms/DataTransferObjects/DonationFormsResponseData.php
src/DonationForms/Models/DonationForm.php
src/DonationForms/Properties/DonationFormLevel.php
src/DonationForms/Repositories/DonationFormsRepository.php
src/DonationForms/ServiceProvider.php
src/DonationForms/ValueObjects/DonationFormMetaKeys.php
src/DonationForms/ValueObjects/DonationFormStatus.php
src/Framework/Models/Contracts/ModelReadOnly.php
tests/Unit/DonationForms/DataTransferObjects/DonationFormQueryDataTest.php
tests/Unit/DonationForms/Models/DonationFormTest.php
tests/Unit/DonationForms/TestTraits/LegacyDonationFormAdapter.php

Add initial design for the DonationForm model class including DTO and repository to be used on the API endpoint for the Donation Forms List Table

Feature: add Donation Form model

---

readme.txt

Chore: Update story link in readme

---

composer.json
composer.lock

Resolves #6702
This PR adds the Symfony [Polyfill Ctype Component](https://symfony.com/components/Polyfill%20Ctype).
- Disable the ctype extension in `php.ini`.
- Make a donation using PayPal Standard.
---
- https://app.asana.com/0/0/1204035047465899

Include polyfill functions for missing ctype extension

---

assets/src/js/admin/admin-settings.js
includes/admin/admin-actions.php
includes/admin/settings/class-settings-advanced.php

This adds CSRF protection to the GiveWP advanced setting "Clear Cache" by adding and verifying a nonce.
The GiveWP advanced setting "Clear Cache" logic.
N/A
Reach out for further instructions.
---
- https://app.asana.com/0/0/1204090406106770

Fix: add nonce to give clear cache setting

---

includes/ajax-functions.php

Re: https://app.asana.com/0/0/1204069668576428/f
This PR patches a potential SSRF vulnerability in which a malicious user with elevated permissions (GiveWP Manager) can provide arbitrary URLs to be fetched by the server.
---
- https://app.asana.com/0/0/1204129686534554

Fix: Patch SSRF in add-on changelog

---

readme.txt

This is for the feature plugin release. The GiveWP core readme should be updated when the 3.0 feature plugin is live on .org.

Chore: Update readme for Next Gen discovery

---

.github/workflows/release-assets.yml
assets/src/js/admin/admin-importer.js
includes/admin/admin-actions.php
includes/class-give-scripts.php

This PR adds a nonce to the donation import feature.
---
- https://app.asana.com/0/0/1204209666734220

Hotfix: Add donation import nonce

---

src/Donations/DonationsAdminPage.php
src/Donations/ViewModels/DonationDetailsViewModel.php

This PR attaches the donation details data to the global GiveDonations object.
Admin Donation Details page
When viewing the details of a donation, open the console and type `GiveDonations.donationDetails`.

Feature: admin donation details data object

---

package-lock.json
package.json
src/Donations/resources/DonationDetails/app/components/DonorDetails/StyleConfig.ts
src/Donations/resources/DonationDetails/app/components/DonorDetails/index.tsx
src/Donations/resources/DonationDetails/app/components/FormTemplate/index.tsx
src/Donations/resources/DonationDetails/app/config/schema.ts
src/Donations/resources/DonationDetails/app/utilities/defaultFormValues.ts
src/Views/Components/AdminUI/ContainerLayout/index.tsx
src/Views/Components/AdminUI/ContainerLayout/style.module.scss
src/Views/Components/AdminUI/FormElements/index.tsx
src/Views/Components/AdminUI/FormElements/style.module.scss
src/Views/Components/AdminUI/SectionHeader/index.tsx
src/Views/Components/AdminUI/SectionHeader/style.module.scss
src/Views/Components/AdminUI/api.ts

This PR adds the components necessary to build out the UI of the Donor details section on the donation page & includes the components to organize the pages layout.
Admin donation details
https://user-images.githubusercontent.com/75056371/229216341-a727cf09-6cda-43e8-95c8-9ef240d8c7cf.mov
- Visit the admin donation details page of any donation.
- Click on the dropdown.

Feature: Admin donation page donor details

---

src/Donations/Endpoints/DonationUpdate.php
src/Donations/Endpoints/DonationUpdateAttributes/DonorIdAttribute.php
src/Donors/Endpoints/DonorsList.php
src/ServiceProviders/RestAPI.php
tests/Unit/Donations/Endpoints/TestDonationUpdate.php
tests/Unit/Donors/Endpoints/TestDonorsList.php

This pull request introduces a new `donorId` attribute to the Donation Update endpoint.
When a donorId attribute is received, the donation's `donorId` property is updated. Additionally, the donor's information is loaded, and the donation's `firstName`, `lastName`, and `email` properties are updated accordingly.

Feature: admin donation details api donor fields

---

src/Donations/DonationsAdminPage.php
src/Donations/Endpoints/DonationUpdate.php
src/Donations/Endpoints/DonationUpdateAttributes/Address1Attribute.php
src/Donations/Endpoints/DonationUpdateAttributes/Address2Attribute.php
src/Donations/Endpoints/DonationUpdateAttributes/CityAttribute.php
src/Donations/Endpoints/DonationUpdateAttributes/CountryAttribute.php
src/Donations/Endpoints/DonationUpdateAttributes/StateAttribute.php
src/Donations/Endpoints/DonationUpdateAttributes/ZipAttribute.php
tests/TestTraits/Faker.php
tests/Unit/Donations/Endpoints/TestDonationUpdate.php

This pull request introduces new attributes to the Donation Update endpoint, which enables updates to the billing address fields.

Feature: admin donation details api billing address fields

---

includes/admin/admin-actions.php

This PR updates how the main key is unserialized when importing donations.
---
- https://app.asana.com/0/0/1204316125792252

Fix: Update main key unserialization

---

.github/workflows/php-compatibility.yml
src/Framework/Support/Facades/Str.php

This PR implements the PHP Compatibility workflow for the GiveWP code base.
The workflow has already been added via https://github.com/impress-org/givewp-github-actions/pull/7.
Detected errors were resolved by https://github.com/impress-org/givewp/pull/6774.

Feature: Add PHP Compatibility workflow.

---

src/Framework/PaymentGateways/Actions/HandleGatewayPaymentCommand.php
src/Framework/PaymentGateways/Actions/HandleGatewaySubscriptionCommand.php
src/Framework/PaymentGateways/Controllers/GatewayPaymentController.php
src/Framework/PaymentGateways/Controllers/GatewaySubscriptionController.php
src/Framework/PaymentGateways/PaymentGateway.php
src/Framework/PaymentGateways/Traits/HandleHttpResponses.php
src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php
src/PaymentGateways/Actions/RegisterPaymentGateways.php
tests/Unit/PaymentGateways/Actions/HandleGatewayPaymentCommandTest.php
tests/Unit/PaymentGateways/Actions/HandleGatewaySubscriptionCommandTest.php
tests/Unit/PaymentGateways/CommandHandlers/PaymentCompleteHandlerTest.php
tests/Unit/PaymentGateways/CommandHandlers/PaymentProcessingHandlerTest.php
tests/Unit/PaymentGateways/CommandHandlers/RedirectOffsiteHandlerTest.php
tests/Unit/PaymentGateways/CommandHandlers/RespondToBrowserTest.php
tests/Unit/PaymentGateways/CommandHandlers/SubscriptionCompleteHandlerTest.php
tests/Unit/PaymentGateways/CommandHandlers/SubscriptionProcessingHandlerTest.php
tests/Unit/PaymentGateways/Controllers/GatewayPaymentControllerTest.php
tests/Unit/PaymentGateways/Controllers/GatewaySubscriptionControllerTest.php

This moves all the gateway _handle_ logic (as it relates to creating payments and subscriptions) into separate controllers.  This will significantly slim down the responsibility of the gateway class itself while giving us more control from the framework side.
The gateway api.
N/A
We need to make sure no gateways are affected.  Basically if one gateway using the gateway api works properly than they all should.
---
- To see the specific tasks where the Asana …

Feature: add gateway payment and subscription controllers 

---

src/PaymentGateways/PayPalCommerce/PayPalCommerce.php

This pull request will enable Venmo by default. Venmo payment method displays (if available for the country) with PayPal Donations the smart buttons.
This will affect payment method options in the donation form.
you should see Venmo payment method option with PayPal Donations smart buttons if available for a country.
---
- https://app.asana.com/0/0/1204621958568568

Enhancement: enable Venmo by default

---

src/Framework/FieldsAPI/Checkbox.php
src/Framework/FieldsAPI/Concerns/ShowInAdmin.php
src/Framework/FieldsAPI/Concerns/ShowInReceipt.php
src/Framework/FieldsAPI/Concerns/StoreAsMeta.php
src/Framework/FieldsAPI/Date.php
src/Framework/FieldsAPI/Email.php
src/Framework/FieldsAPI/Field.php
src/Framework/FieldsAPI/File.php
src/Framework/FieldsAPI/Hidden.php
src/Framework/FieldsAPI/Phone.php
src/Framework/FieldsAPI/Radio.php
src/Framework/FieldsAPI/Select.php
src/Framework/FieldsAPI/Text.php
src/Framework/FieldsAPI/Textarea.php
src/Framework/FieldsAPI/Url.php

This adds a new `ShowInAdmin` trait to the fields api.
```
$field->shouldShowInAdmin() // false;
$field->showInAdmin(true);
$field->shouldShowInAdmin() // true;
```
Existing fields
N/A
The only way to test would be programmatically using the fields api.

Feature: add ShowInAdmin trait to fields api

---

blocks/donation-form/edit/block.scss
blocks/utils/index.js
includes/shortcodes.php
src/Views/Form/Templates/Classic/Classic.php

This pull request adds the foundation needed to support version 3 forms on the legacy Donation Form block (added in a future PR). By itself, this pull request does not do anything clearly noticeable.
Donation Form (v2) block.

Refactor: change Donation Form block (v2) to support v3 forms

---

includes/class-notices.php
src/PaymentGateways/PayPalCommerce/ScriptLoader.php

Resolves https://wordpress.org/support/topic/fatal-error-when-givewp-is-active/
I found that we do not handle exceptions, for this reason, few users are seeing fatal errors if they have invalid SSL. A fatal error occurs only when the donor visits the donation form.
This pull request affects the donation form display.
- Edit code and return exception from `getClientToken` function
https://github.com/impress-org/givewp/blob/8580cb23d18e7a982eb4f402f9c5f33e865f19f8/src/PaymentGateways/PayPalCommerce/Repositories/MerchantDetails.php#L134
```php
throw new \Exception('Invalid SSL');
```
- You should see an error notice on the donation form instead of a fatal error.
-   [ ] …

Hotfix: handle exception gracefully

---

give.php
includes/admin/settings/class-settings-advanced.php
readme.txt

This PR sanitizes the donor default user role.
---
- https://app.asana.com/0/0/1205365442573930

Feature: Sanitize donor default user role

---

src/DonationForms/Routes/DonateRoute.php
src/DonationForms/Routes/ValidationRoute.php
src/DonationForms/ValueObjects/DonationFormErrorTypes.php
src/DonationForms/resources/registrars/templates/index.ts
src/DonationForms/resources/registrars/templates/layouts/Form.tsx
src/DonationForms/resources/registrars/templates/layouts/FormError.tsx
src/DonationForms/resources/registrars/templates/layouts/MultiStepForm.tsx
src/DonationForms/resources/styles/_pico.scss
src/DonationForms/resources/styles/base.scss
src/DonationForms/resources/styles/components/_form-errors.scss
src/Framework/PaymentGateways/Controllers/GatewayPaymentController.php
src/Framework/PaymentGateways/Controllers/GatewaySubscriptionController.php
src/Framework/PaymentGateways/Traits/HandleHttpResponses.php
src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php

This updates how we handle donation form errors on v3 forms and adds styles to the notice.
- Updates the error handing & styles on v3 forms.
- Moved the error handling for v2 forms closer to request.
---
- To test gateway exceptions you will need to programmatically / hardcode throwing an exception in a gateway like the Test Gateway.  This should be tested on both v2 and v3 forms.
- To just see the error styling on v3 forms, use the test gateway and put "error" as your first name.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) …

Fix: donation form errors

---

src/PaymentGateways/Migrations/CopyV2GatewaysSettingsToV3.php
src/PaymentGateways/ServiceProvider.php

This PR adds a new database migration copying the current payment gateways settings from v2 to v3:
```
gateways > gateways_v3
gateways_label > gateways_label_v3
default_gateway > default_gateway_v3
```
---
- https://app.asana.com/0/0/1205478875158267

Feature: Payment Gateways Settings migration

---

src/DonationForms/V2/resources/components/Onboarding/Dialogs/FeatureNoticeDialog.tsx

- Add missing period
- Update “Visual Donation Form Builder” (not “Visual Donation**s** Form Builder”)

chore: Update text in Feature Notice Dialog

---

src/FormBuilder/resources/js/form-builder/src/blocks/section/Edit.tsx

This PR sets a list of prioritized inserter blocks when adding a new block to a section.

Feature: Prioritized FFM blocks in block inserter

---

give.php
readme.txt
src/DonationForms/V2/ValueObjects/DonationFormStatus.php
src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php

This prevents donations for donation forms with a status of "trash".
v2 donation forms
N/A
N/A
---
- https://app.asana.com/0/0/1205524578029613

Fix: add validation for trash donation form status

---

src/FormBuilder/resources/js/form-builder/src/components/settings/PopoverContentWithTemplateTags/index.tsx
src/FormBuilder/resources/js/form-builder/src/components/settings/PopoverContentWithTemplateTags/styles.scss

This PR adjusts the position of the popover and restores the border styles for the rich text editor.
---
- https://app.asana.com/0/0/1205502083833589

Refactor: Update Donation Instructions popover

---

src/Promotions/WelcomeBanner/resources/js/app/components/Link/styles.scss
src/Promotions/WelcomeBanner/resources/js/app/components/Row/styles.scss
src/Promotions/WelcomeBanner/resources/js/app/components/Sections/styles.scss
src/Promotions/WelcomeBanner/resources/js/app/components/SpotLight/styles.scss
src/Promotions/WelcomeBanner/resources/js/app/components/VideoPlayer/styles.scss
src/Promotions/WelcomeBanner/resources/js/app/styles.scss

The PR addresses non functional changes & aims to improve the banner styling. The main changes include setting a height on the video container to account for the differing heights of the .mp4 videos, adjustments to spacing in the left section as well as improved responsiveness.
Welcome Banner
- View welcome banner

Refactor: improve welcome banner design

---

src/FormBuilder/resources/js/form-builder/src/components/onboarding/transfer/TransferNotice.tsx

- Check design specs for spacing, font size, color, etc.
- Remove the "Next Steps" badge
- Change copy to "Once you're happy with your new form, permanently transfer your existing donation data to this new form."
---
- https://app.asana.com/0/0/1205502083833560

Refactor: Update Transfer Notice design

---

src/DonationForms/V2/resources/components/Onboarding/Components/EditForm.tsx
src/DonationForms/V2/resources/components/Onboarding/style.module.scss

- Updates the color value of the CTA button and the SVG icon
| --- | --- |
| ![image](https://github.com/impress-org/givewp/assets/10858303/72dd53a1-3740-4812-b36f-6e6d9a423ce9) | ![image](https://github.com/impress-org/givewp/assets/10858303/5254b6fe-f2ff-4a8d-9808-708a9ff389b6) |
---
- https://app.asana.com/0/0/1205515364894529

Refactor: Update Migration Guide styles

---

src/PaymentGateways/PayPalCommerce/AdminSettingFields.php

This pull request updates PayPal donations setting page warning message about sandbox account connect. 
---
- https://app.asana.com/0/0/1205581898265071

Fix: update warning message

---

composer.json
src/Framework/Http/Response/Response.php
src/Framework/Http/Response/Traits/ResponseTrait.php
src/Framework/Http/Response/Types/JsonResponse.php
src/Framework/Http/Response/Types/RedirectResponse.php

Resolves #6373
This updates the `"symfony/http-foundation"` package to be loaded locally using Strauss.
This affects the our Response classes that use this package under the hood.  These are mainly being used in the donation form request cycle.
N/A
- Run composer install
- Make sure donations still work properly for v2 and v3 forms 
---
- …

Chore: load symphony http package with Strauss

---

includes/admin/admin-footer.php
includes/admin/settings/class-settings-advanced.php
includes/admin/tools/views/html-admin-page-system-info.php
includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
src/FormBuilder/resources/js/form-builder/src/settings/form-grid/index.tsx

This PR updates several external links in Give admin to use short links. 
Give admin external links
---
- https://app.asana.com/0/0/1205269709893084

Chore: Update documentation links

---

src/Donors/Models/DonorModelQueryBuilder.php
src/Framework/Models/ModelQueryBuilder.php

Resolves 
With adding some doc explanations, all will be OK
None

Chore: Add docblocks for necessary, but unused parameter

---

src/DonationForms/resources/registrars/templates/layouts/Goal.tsx

I noticed a couple bugs on the v3 form donation goal template.
1. The current amount was hardcoded as "0"
2. The raised amount was not formatted
The v3 form donation goal
**Before**
**After**
Make sure the donation goal template looks correct.

Fix: v3 form donation goal template formatting

---

src/DonationForms/V2/DonationFormsAdminPage.php
src/DonationForms/V2/Endpoints/ListDonationForms.php
src/DonationForms/V2/ServiceProvider.php
src/DonationForms/V2/resources/components/DonationFormsListTable.tsx
src/DonationForms/V2/resources/components/DonationFormsRowActions.tsx
src/DonationForms/V2/resources/components/Onboarding/Components/EditForm.tsx
src/DonationForms/V2/resources/components/Onboarding/Dialogs/FeatureNoticeDialog.tsx
src/DonationForms/V2/resources/components/Onboarding/style.module.scss
src/FormBuilder/resources/js/form-builder/src/components/onboarding/transfer/TransferDialog.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_transfer.scss
src/Views/Components/AdminUI/Button/index.tsx
src/Views/Components/AdminUI/Button/style.scss
src/Views/Components/AdminUI/Input/style.scss
src/Views/Components/AdminUI/ModalDialog/style.scss
src/Views/Components/ListTable/ListTablePage/ListTablePage.module.scss
src/Views/Components/ListTable/ListTableRows/index.tsx
tests/Unit/DonationForms/Endpoints/TestListDonationForms.php

This PR implements form migration design updates.
Form Builder
Donation forms list table
---
- https://app.asana.com/0/0/1205585333330832

Feature: form migration design updates

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/login/index.tsx

This PR updates the default value for the login notice of the User Login block.
---
- https://app.asana.com/0/0/1205076244101516

chore: Update default login notice

---

src/DonationForms/resources/app/utilities/getDefaultValuesFromSections.ts
src/Framework/FieldsAPI/Concerns/HasDefaultValue.php

When default values are set to empty strings, they are being added to the default values which affects the multi step validation.  This make sure not to add default values when they are null or empty strings.
Without this PR, custom fields that are required will break the flow of multi-step forms.
Technically this could be avoided by conditionally setting the defaultValue of a Fields api Field to null but that's easier said than done at this point considering its third party and ffm usage.
Donation form - specifically multi-step when custom field is required with no default value
N/A
- Create a v3 Form and set to multi step design
- Add a new second section with a custom text field - set to required (no default value)
- Make sure you can navigate through the multi step form.
- Repeat …

Fix: required fields in following steps no longer break multi-step

---

src/FormMigration/FormMetaDecorator.php

This fixes the form migration custom amount option.
Form migration custom amount option
N/A
- Create a v2 form with custom amount enabled
- Migrate to v3 and make sure custom amount is enabled.
---
- https://app.asana.com/0/0/1205718005328549

Fix: form migration custom amount option

---

readme.txt

This is the updated readme text for 3.0.
Resolves #

Chore: Update readme.txt for 3.0

---

give.php
readme.txt
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/Edit.tsx

This PR resolves the issue with title prefixes. The issue was that the title prefixes were numbers instead of strings like "Mr", "Ms", etc.
1. Create a new form
2. Enable title prefixes
3. Try to add/edit/reorder title prefixes
4. Save form 
5. Check that everything is fine on the frontend as well 
---
- https://app.asana.com/0/0/1205853501645956

Fix: Title prefixes

---

readme.txt

Fixes a small typo in the public changelog
n/a
n/a
n/a

Fix: WordPress typo in changelog

---

assets/src/js/admin/admin-scripts.js
assets/src/js/admin/admin-settings.js
includes/admin/settings/class-settings-display.php
src/FormBuilder/ViewModels/FormBuilderViewModel.php
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/terms-and-conditions/GlobalSettingsLink.tsx
src/FormBuilder/resources/js/form-builder/src/common/getWindowData.ts
tests/Unit/ViewModels/FormBuilderViewModelTest.php

The Title Prefixes options for the name block and the Label and Text options for the Terms and Conditions block have global settings that should be considered.
This PR implements a global settings link for the Name block and adds a few improvements for the Terms and Conditions block that already had it implemented.
This PR also implements a few minor changes in the settings page to display these content options all the time, this way we can ensure that they will not be hidden when the user accesses the settings page through the links from the visual form builder.
The name block and the terms and conditions block.
**Name block:**
**Terms and Conditions block:** 
1. Created a form with the visual form builder;
2. Add the Terms and Conditions Block and select the global options, the link …

Refactor: change the global settings link for the terms and conditions block and add it for name title prefixes on the name block 

---

src/DonationForms/V2/DonationFormsAdminPage.php
src/FormMigration/FormMetaDecorator.php
src/FormMigration/ServiceProvider.php
src/FormMigration/Steps/FundsAndDesignations.php
src/Revenue/Repositories/Revenue.php

Resolves [GIVE-11] [GIVE-183]
Related PR: https://github.com/impress-org/give-funds/pull/125
This PR adds the necessary logic to transfer data from the Funds and Designations addon settings to the migrated forms.
This PR also sets the Funds and Designations addon as supported by the visual form builder.
The migrated forms.
1. Install the Funds and Designations addon from this PR/branch: https://github.com/impress-org/give-funds/pull/125
2. Create a legacy form and set a few fund settings
3. Do the migration process, then check the Funds and Designations block added in the migrated form, you should see in the block settings the settings selected in the previous step. …

Feature: add Funds and Designations add-on to the form migration process

---

src/DonorDashboards/Tabs/EditProfileTab/PasswordRoute.php
src/DonorDashboards/Tabs/EditProfileTab/Tab.php
src/DonorDashboards/resources/js/app/tabs/edit-profile/content.js
src/DonorDashboards/resources/js/app/tabs/edit-profile/utils/index.js

This PR adds a password update form to the Donor Dashboard.

Feature: Add password update to donor dashboard

---

give.php

See Installing in WP multisite only if network admin #7119

Installing in WP multisite only if network admin

---

src/FormBuilder/BlockTypes/DonationAmountBlockType.php
src/Framework/Blocks/BlockType.php
src/Framework/Blocks/Contracts/BlockTypeInterface.php
tests/Unit/FormBuilder/BlockTypes/DonationAmountBlockType.php
tests/Unit/Framework/Blocks/TestBlockType.php

Fun: donation amount block type

---

src/EventTickets/Factories/EventTicketTypeFactory.php
src/EventTickets/Routes/GetEventsListTable.php
src/EventTickets/ServiceProvider.php
tests/Unit/EventTickets/Routes/GetEventsListTableTest.php

Feature: Add endpoint for Event List Table

---

src/FormMigration/FormMetaDecorator.php
src/FormMigration/ServiceProvider.php
tests/Feature/FormMigration/Controllers/TestMigrationController.php
tests/Feature/FormMigration/Steps/TestDonationGoal.php
tests/Feature/FormMigration/Steps/TestDonationOptions.php
tests/Feature/FormMigration/TestFormMetaDecorator.php
tests/Unit/DonationForms/TestTraits/LegacyDonationFormAdapter.php

Resolves [GIVE-248], [GIVE-130]
This is the start for adding all the missing unit tests for the form migration process.  There is much more to add and continue adding but this should give us a head start and set us up for subsequent work.
- Unit tests
- Minor update to funds step
N/A
Devs:
Run `composer test`
QA:
Zip: https://github.com/impress-org/givewp/actions/runs/7819649179
Just make sure form migrations work properly without (then with) the funds add-on installed.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and …

Tests: scaffold v2 to v3 donation form migration tests

---

src/EventTickets/Factories/EventFactory.php
src/EventTickets/Factories/EventTicketFactory.php
src/EventTickets/Factories/EventTicketTypeFactory.php
src/EventTickets/Migrations/CreateEventTicketTypesTable.php
src/EventTickets/Migrations/CreateEventTicketsTable.php
src/EventTickets/Migrations/CreateEventsTable.php
src/EventTickets/Models/Event.php
src/EventTickets/Models/EventTicket.php
src/EventTickets/Models/EventTicketType.php
src/EventTickets/Repositories/EventRepository.php
src/EventTickets/Repositories/EventTicketRepository.php
src/EventTickets/Repositories/EventTicketTypeRepository.php
src/EventTickets/Routes/GetEventsListTable.php

The main goal of this pull request is to convert entity properties to camel case.
Models, Repositories, Factories and Migrations of Event, EventTickets and EventTicketTypes

Refactor: Convert entity properties to camel case

---

composer.json
src/EventTickets/Actions/ConvertEventTicketsBlockToFieldsApi.php
src/EventTickets/Actions/EnqueueFormBuilderScripts.php
src/EventTickets/Fields/EventTickets.php
src/EventTickets/Hooks/DonationFormBlockRender.php
src/EventTickets/Models/EventTicketType.php
src/EventTickets/Repositories/EventRepository.php
src/EventTickets/Repositories/EventTicketRepository.php
src/EventTickets/Repositories/EventTicketTypeRepository.php
src/EventTickets/resources/blocks/EventTicketsBlock/Edit/BlockPlaceholder.tsx
src/EventTickets/resources/blocks/EventTicketsBlock/types.ts
src/EventTickets/resources/components/EventTicketsHeader.tsx
src/EventTickets/resources/components/EventTicketsList.tsx
src/EventTickets/resources/components/EventTicketsListItem.tsx
src/EventTickets/resources/components/types.ts
src/EventTickets/resources/templates/EventTickets/EventTicketsListHOC.tsx
src/EventTickets/resources/templates/EventTickets/index.tsx
src/EventTickets/resources/templates/EventTickets/types.ts

Resolves [GIVE-300]
Depends on https://github.com/impress-org/givewp/pull/7233 then on https://github.com/impress-org/givewp/pull/7235
Since most of the front-end work has been completed during the discovery cycle, this pull request mainly involves replacing hardcoded data in our block and field templates with actual data loaded from Models.
PS: This work will need to be modified slightly once the changes from https://github.com/impress-org/givewp/pull/7227 are merged into the core. A new pull request will be created to include the updates.
1. Add the new Event Tickets block to a page. Without any events into the database, a message including a link to add a new event must be displayed.
2.  Run the snippet bellow to add a sample Event.
```php
use Give\EventTickets\Models\Event;
use …
```

Refactor: Replace hard coded data

---

assets/src/js/frontend/paypal-commerce/SmartButtons.js
give.php
readme.txt
src/DonationForms/V2/DonationFormsAdminPage.php
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx
src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php
src/ServiceProviders/PaymentGateways.php

Resolves [GIVE-309]
The wrong amount is sent to PayPal if the donor changes the donation amount after filling in the credit card fields in PayPal's debit/credit smart button.
This PR fixes this problem and adds a new verification to check if the amount was changed. If yes, it updates the PayPal amount order before approving it as it's not possible to update the order after it gets approved - status set as COMPLETE.
**Note for reviewer:** The IDE auto-format applied our code style in the SmartButtons.js file that was using another code style, which makes it hard to review. So, to better understand, you can check for the `@unreleased` tags to see what was changed.
PayPal Donations
https://www.loom.com/share/da88c326f0414da889f0f2a6fec013af?sid=662ab813-00f2-41cb-a416-7a57697267e2
You can …

Fix: wrong donation amount sent to PayPal if donor changes amount

---

includes/process-donation.php

Resolves [GIVE-196]
Prevent donations to be processed if containing unexpected format.
Donations on v2 forms
Make sure donations on v2 forms still work as expected
Reach out to @pauloiankoski  for more details.
[GIVE-196]: https://stellarwp.atlassian.net/browse/GIVE-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: process donation validation

---

src/DonationForms/resources/propTypes.ts
src/DonationForms/resources/receipt/DonationConfirmationReceiptApp.tsx
src/DonationForms/resources/registrars/templates/layouts/DonationReceipt.tsx
src/DonationForms/resources/styles/components/_receipt.scss
src/EventTickets/Actions/ConvertEventTicketsBlockToFieldsApi.php
src/EventTickets/Actions/EnqueueFormBuilderScripts.php
src/EventTickets/DataTransferObjects/EventTicketTypeData.php
src/EventTickets/Factories/EventTicketTypeFactory.php
src/EventTickets/Models/EventTicket.php
src/EventTickets/Models/EventTicketType.php
src/EventTickets/Repositories/EventRepository.php
src/EventTickets/Repositories/EventTicketRepository.php
src/EventTickets/Repositories/EventTicketTypeRepository.php
src/EventTickets/resources/blocks/EventTicketsBlock/Edit/BlockPlaceholder.tsx
src/EventTickets/resources/components/EventTicketsHeader.tsx
src/EventTickets/resources/components/EventTicketsList.tsx
src/EventTickets/resources/components/EventTicketsListItem.tsx
src/EventTickets/resources/components/types.ts
src/EventTickets/resources/templates/EventTickets/EventTicketsListHOC.tsx
src/EventTickets/resources/templates/EventTickets/index.tsx
src/Framework/Receipts/Actions/GenerateConfirmationPageReceipt.php
src/Framework/Receipts/DonationReceipt.php
tests/Unit/Framework/Receipts/TestDonationReceipt.php
tests/Unit/Framework/Receipts/TestDonationReceiptBuilder.php
tests/Unit/Framework/Receipts/TestGenerateConfirmationPageReceipt.php

Resolves [GIVE-355]
This pull-request updates the block placeholder and the field template, alongside all data being passed to those with the recently changed names, and updates the confirmation page to display Event Tickets info, when applicable.
Event block placeholder, Event field template and Donation Confirmation Page
[GIVE-355]: https://stellarwp.atlassian.net/browse/GIVE-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

Refactor: update event tickets template and confirmation page

---

assets/src/js/admin/admin-importer.js
includes/admin/admin-actions.php

Resolves [GIVE-245]
This PR implements a better way to validate data to ensure better code quality and prevent duplications.
[GIVE-245]: https://stellarwp.atlassian.net/browse/GIVE-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhancement: extract validation/unserialize logic to reuse it in other places

---

src/EventTickets/Routes/UpdateEventTicketType.php
src/EventTickets/ServiceProvider.php
tests/Unit/EventTickets/Routes/UpdateEventTicketTypeTest.php

Resolves [GIVE-367](https://stellarwp.atlassian.net/browse/GIVE-367)
This PR adds the `events-tickets/ticket-type/(?P<ticket_type_id>\d+)` endpoint for updating a ticket type by ID.
[GIVE-367]: https://stellarwp.atlassian.net/browse/GIVE-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add endpoint for updating a ticket type

---

src/EventTickets/Actions/ConvertEventTicketsBlockToFieldsApi.php
src/ServiceProviders/LegacyServiceProvider.php

Resolves [GIVE-419](https://stellarwp.atlassian.net/browse/GIVE-419)
This PR update the amount of the donation to include the cost of purchased tickets.
Note: This runs **after** the donation object is created and **before** the payment gateway charges the payment method.
[GIVE-419]: https://stellarwp.atlassian.net/browse/GIVE-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Update donation amount to include ticket cost

---

assets/src/css/admin/settings.scss
src/BetaFeatures/Actions/RegisterSettings.php
src/BetaFeatures/ServiceProvider.php

Resolves [GIVE-439]
This updates the beta features page with an informational message.
The beta features page
- Build scripts (for styles) and visit the beta features page
[GIVE-439]: https://stellarwp.atlassian.net/browse/GIVE-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Beta features page message

---

src/BetaFeatures/ServiceProvider.php

This updates the beta features messaging with suggestion from @angelablake ✏️ 
The beta feature messaging
Open the beta features settings page tab

Refactor: update beta features message

---

includes/class-notices.php
includes/donors/class-give-donor-wall.php
includes/login-register.php
includes/shortcodes.php
src/MultiFormGoals/MultiFormGoal/Shortcode.php
src/Views/IframeView.php

Resolves [GIVE-561]
This PR implements sanitizing and escaping good practices intended to improve code quality.
Shortcodes.
[GIVE-561]: https://stellarwp.atlassian.net/browse/GIVE-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhancement: implements development good practices to give form shortcode

---

tests/Unit/FormBuilder/BlockTypes/TestDonationAmountBlockType.php

Update `testDefaultBlockModelAttributesMatchBlockTypeProperties` to match the latest changes applied to levels schema.
Tests

Test: Update test to reflect latest changes

---

src/Donations/resources/components/DonationsListTable.tsx

Fix: Made string translatable in DonationsListTable.tsx file

Fix: Made string translatable in DonationsListTable.tsx file

---

blocks/donation-form-grid/edit/inspector.js

Fix: Made string translatable in inspector.js file

Fix: Made string translatable in inspector.js file

---

src/Promotions/InPluginUpsells/resources/views/payment-gateway.php

Fix: Made string translatable in payment-gateway.php file

Fix: Made string translatable in payment-gateway.php file

---

src/DonationForms/V2/DonationFormsAdminPage.php
src/Donors/DonorsAdminPage.php
src/Subscriptions/SubscriptionsAdminPage.php

Fix: Made the string "Switch to New View" translatable in three PHP files

Fix: Made the string "Switch to New View" translatable in three PHP files

---

src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php
src/FormBuilder/ServiceProvider.php
src/FormBuilder/resources/js/form-builder/src/components/DatePicker/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/donation-goal/index.tsx

This PR adds a dismissible notice for the custom goal progress option. 

Feature: Custom goal progress notice

---

src/FormBuilder/resources/js/form-builder/src/components/DatePicker/index.tsx

This PR resolves the issue with goal date settings. 

Fix: goal date settings

---

src/API/Endpoints/Logs/GetLogs.php
src/Log/LogModel.php

Resolves [GIVE-728]
This PR adds a way for developers to filter the "source" column from the Give logs to allow display values greater than 64 characters. 
The Log source view.
For more context and test instructions, check out this related PR: https://github.com/impress-org/give-webhooks/pull/20
[GIVE-728]: https://stellarwp.atlassian.net/browse/GIVE-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: add log source filter

---

src/EventTickets/Routes/UpdateEvent.php
src/EventTickets/Routes/UpdateEventTicketType.php

Resolves [GIVE-982]
This PR updates the event ticket endpoint permission callback. 
Event ticket endpoints
[GIVE-982]: https://stellarwp.atlassian.net/browse/GIVE-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: event tickets permission callback check

---

src/DonationForms/DataTransferObjects/DonateFormRouteData.php
src/DonationForms/Exceptions/DonationFormForbidden.php
src/DonationForms/Routes/DonateRoute.php
tests/Unit/DataTransferObjects/DonateFormRouteDataTest.php

Resolves [GIVE-1012]
This adds additional donation form status validation to the donate request.
Donation form processing
TBD
[GIVE-1012]: https://stellarwp.atlassian.net/browse/GIVE-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: form request status validation

---

includes/process-donation.php

Resolves [GIVE-654], [GIVE-980]
This adds `give-form-title` & `give_title` to serialized fields check
v2 form processing
N/A
ZIP: https://github.com/impress-org/givewp/actions/runs/10144972557
[GIVE-654]: https://stellarwp.atlassian.net/browse/GIVE-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GIVE-980]: https://stellarwp.atlassian.net/browse/GIVE-980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

Fix: add give-form-title and give_title to serialized fields check

---

src/DonorDashboards/Helpers.php

Resolves [GIVE-1118]
This updates the donor dashboard to include the "Give Subscriber" role in permissions check.
The donor dashboard aceess
- Create a donor/subscriber with Give Subscriber role
- Access the donor dashboard and make sure you can view donation history
[GIVE-1118]: https://stellarwp.atlassian.net/browse/GIVE-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: update donor dashboard user role check to include give_subscriber

---

give.php
src/DonationForms/DataTransferObjects/DonateFormRouteData.php
src/DonationForms/Routes/DonateRoute.php
src/DonationSpam/Akismet/API.php
src/DonationSpam/Akismet/Actions/ValidateDonation.php
src/DonationSpam/Akismet/DataTransferObjects/CommentCheckArgs.php
src/DonationSpam/Akismet/DataTransferObjects/SpamContext.php
src/DonationSpam/EmailAddressWhiteList.php
src/DonationSpam/Exceptions/SpamDonationException.php
src/DonationSpam/ServiceProvider.php
tests/Unit/DonationSpam/Akismet/Actions/ValidateDonationTest.php
tests/Unit/DonationSpam/EmailAddressWhiteListTest.php

Resolves [GIVE-1050]
This PR adds support for Akismet spam checks to the v3 donation forms.
Adds the `givewp_donate_form_data_validated` action to `DonateRoute` where a hook can disrupt the donation process by throwing an `Exception`.
| Donation Flagged as SPAM |
| --- |
| ![image](https://github.com/user-attachments/assets/d7a0f680-6933-4bf1-8cc4-1e5f37f14c35) |
| SPAM Log |
| --- |
| ![image](https://github.com/user-attachments/assets/cf18dc09-5795-4495-aa7a-5a803a7d9631) |
- Install and activate the Akismet plugin
- Register a personal, free Akismet license
- Configure Akismet with the API key
- Enable "Akismet SPAM Protected" in the Give settings
- Donate with the email akismet-guaranteed-spam@example.com
-   [x] …

Feature: Add akismet support to v3 forms

---

src/FormMigration/ServiceProvider.php
src/FormMigration/Steps/FormTaxonomies.php
tests/Unit/FormMigration/Steps/FormTaxonomiesTest.php

Resolves [GIVE-1119]
This PR adds a new `FormTaxonomies` step to the form migration process.
Form migrations.
Create a v2 form with form tags, categories.
Migrating the form to v3 should carry over the terms.
[GIVE-1119]: https://stellarwp.atlassian.net/browse/GIVE-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add migration step for Form Taxonomies

---

src/DonationForms/resources/app/form/MultiStepForm/components/Steps.tsx

Resolves [GIVE-886]
This PR updates the multi-step for to scroll to the top when the step changes.
Adds an effect when the current step changes.
Add a multi-step (v3) form to a page.
Scroll down and go to the next step.
[GIVE-886]: https://stellarwp.atlassian.net/browse/GIVE-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Add scroll on step change

---

src/DonationForms/V2/resources/components/DonationFormsListTable.tsx
src/Subscriptions/resources/components/SubscriptionsListTable.tsx

Fix: Made string translatable in two .tsx files

Fix: Made string translatable in two .tsx files

---

src/FormBuilder/resources/js/form-builder/src/components/EmbedForm/index.tsx

Fix: Made strings translatable in index.tsx

Fix: Made strings translatable in index.tsx

---

src/FormBuilder/resources/js/form-builder/src/settings/group-general/form-summary/index.jsx

Fix: Made strings translatable in index.jsx

Fix: Made strings translatable in index.jsx

---

src/FormBuilder/resources/js/form-builder/src/settings/group-email-settings/email/template-options/settings.tsx

Fix: Text domain in settings.tsx

Fix: Text domain in settings.tsx

---

src/FormBuilder/resources/js/form-builder/src/settings/group-email-settings/general/index.tsx

Fix: Text domain in index.tsx

---

src/FormBuilder/resources/js/form-builder/src/promos/recurring-donations.tsx

Fix: Made strings translatable in recurring-donations.tsx

Fix: Made strings translatable in recurring-donations.tsx

---

composer.json
src/Donations/DonationsAdminPage.php
src/Donors/DonorsAdminPage.php
src/FormMigration/FormMetaDecorator.php
src/PaymentGateways/Gateways/ServiceProvider.php
src/PaymentGateways/Gateways/Stripe/LegacyStripeAdapter.php
src/Subscriptions/SubscriptionsAdminPage.php
tests/Feature/FormMigration/Steps/TestActiveCampaign.php
tests/Feature/FormMigration/Steps/TestConstantContact.php
tests/Feature/FormMigration/Steps/TestConvertKit.php
tests/Feature/FormMigration/Steps/TestDonationGoal.php
tests/Feature/FormMigration/Steps/TestDonationOptions.php
tests/Feature/FormMigration/Steps/TestDoubleTheDonation.php
tests/Feature/FormMigration/Steps/TestMailchimp.php
tests/Unit/FormMigration/TestTraits/FormMigrationProcessor.php
tests/Unit/PaymentGateways/Gateways/Stripe/LegacyStripeAdapterTest.php

Fix: 'Any' string made translatable in 3 php files

Fix: 'Any' string made translatable in 3 php files

---

src/FormBuilder/resources/js/form-builder/src/components/onboarding/steps/schema-steps.tsx

Resolves [GIVE-849]
This PR expands the highlighted area for the canvas step of the onboarding tour in the visual builder.
Updates a selector in the schema steps configuration.
Edit a form in the visual builder
Navigate to the "Build" section
Open the "Options" dropdown in the header
Click "Show Guided Tour" to launch onboarding
[GIVE-849]: https://stellarwp.atlassian.net/browse/GIVE-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

Chore: Expand highlighted area of the canvas during onboarding

---

src/FormBuilder/resources/js/form-builder/src/containers/BlockEditorInterfaceSkeletonContainer.tsx
src/FormBuilder/resources/js/form-builder/src/containers/HeaderContainer.tsx

Resolves [GIVE-804]
This PR adds tooltips to the icons in the header of the visual form builder.
Icon buttons in the header now have title and label attributes.
- Toggle block Inserter
- Form Field Overview
- Embed form
- View form
- Settings
- Options
Note that the overview title is capitalized to match the Block Editor "Document Overview" label.
Hover over the icon buttons in the header of the visual form builder.
[GIVE-804]: …

Feature: Add title, label to header icons in form builder

---

src/FormMigration/Steps/FormTaxonomies.php
tests/Unit/FormMigration/Steps/FormTaxonomiesTest.php

This PR updates the function used to fetch selected terms.

Fix: Update function for getting terms

---

src/DonorDashboards/resources/js/app/components/select-control/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/payment-method-control/authorize-control/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/payment-method-control/card-control/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/payment-method-control/square-control/index.js
src/DonorDashboards/resources/js/app/components/text-control/index.js
src/DonorDashboards/resources/js/block/color-control/index.js
src/MultiFormGoals/resources/js/components/color-control/index.js
src/MultiFormGoals/resources/js/components/date-time-control/index.js
src/MultiFormGoals/resources/js/components/image-control/index.js
src/MultiFormGoals/resources/js/components/multi-select-control/index.js
src/MultiFormGoals/resources/js/components/server-side-render-x/index.js
src/Views/Components/Card/index.js
src/Views/Components/ListTable/Pagination/index.tsx
src/Views/Components/Modal/index.js
src/Views/Components/Pagination/index.js
src/Views/Components/PeriodSelector/index.js
src/Views/Components/Spinner/index.js
src/Views/Components/Table/index.js

Resolves [GIVE-1109]
Replaces uses of `Component.defaultProps` with ES6 defaults.
Build and spot-check for errors.
[GIVE-1109]: https://stellarwp.atlassian.net/browse/GIVE-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Replace defaultProps with ES6 defaults

---

src/FormBuilder/resources/js/form-builder/src/components/onboarding/steps/filters/withButtons.tsx

Fix: Made string translatable in withButtons.tsx

Fix: Made string translatable in withButtons.tsx

---

includes/process-donation.php

Resolves: [GIVE-1246]
This adds an additional check for `stripslashes_deep` in our `give_donation_form_has_serialized_fields` function.
- v2 forms
N/A
Make sure v2 forms work as expected
[GIVE-1246]: https://stellarwp.atlassian.net/browse/GIVE-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhancement: add additional check for stripslashes_deep in serialized function

---

includes/donors/class-give-donors-query.php

Resolves [GIVE-1256]
This PR updates the `order` parameter used in the donor query.
[GIVE-1256]: https://stellarwp.atlassian.net/browse/GIVE-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: Update donor query order parameter

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats.tsx

This PR replaces the test data used in the Campaign Stats with real data returned by the API.

Chore: Replace test data from Campaign Stats

---

src/Campaigns/Repositories/CampaignRepository.php
tests/Unit/Campaigns/Repositories/CampaignRepositoryTest.php

Resolves [GIVE-1334]
This PR adds a new `updateDefaultCampaignForm()` method to the campaign repository and also a few missing unit tests for new methods added to this repository class on the last PRs. 
The CampaignRepository class.
Run the `composer test -- --filter CampaignRepositoryTest` command in your terminal.
[GIVE-1334]: https://stellarwp.atlassian.net/browse/GIVE-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

Feature: add update default form method and missing tests for new methods from campaign repository 

---

src/Campaigns/Actions/LoadCampaignDetailsAssets.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/DefaultForm.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/HeaderSubText.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/HeaderText.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/types.ts

Resolves [GIVE-1347]
This PR adds the "Default campaign form" widget to the Campaigns Overview page.
Additionally, it extracts the `<HeaderText/>` and `<HeaderSubText />` components for re-use in standalone components/widgets.
[GIVE-1347]: https://stellarwp.atlassian.net/browse/GIVE-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add campaign default form widget

---

src/Campaigns/Models/Campaign.php
src/Campaigns/Repositories/CampaignRepository.php
tests/Unit/Campaigns/Repositories/CampaignRepositoryTest.php

Resolves [GIVE-1404]
This PR implements the `Campaign::merge()` and `CampaignRepository::mergeCampaigns()` methods in the model and repository classes which allow us to inform the `$campaingsToMerge` and `$destinationCampaign` as parameters.
Also, a few unit tests to check different outcomes generated by the `CampaignRepository::mergeCampaigns()` method were implemented.
The campaign model and repository classes.
1. Run the `composer test -- --filter CampaignRepositoryTest` command in your terminal.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-revi …

Feature: add merge campaigns methods

---

src/Framework/Migrations/Controllers/ManualMigration.php

Resolves [GIVE-2042]
This adds sanitization to the migration url param in the admin.
The manual migration url
N/A
TBD
[GIVE-2042]: https://stellarwp.atlassian.net/browse/GIVE-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: sanitize migration param url

---

src/Campaigns/resources/admin/common/getCampaignDetailsWindowData.ts
src/Campaigns/resources/admin/common/index.ts
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/GoalProgressChart/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Settings.tsx
src/Campaigns/resources/admin/components/CampaignFormModal/index.tsx
src/Campaigns/resources/utils.ts

Resolves [GIVE-2153]
This removes the hardcoded USD currency and en-US locale values in favor of give & browser settings.
This ensures the give currency settings are being reflected in the visual representation of the data within the Campaigns details page.  This also ensures the correct locale is being used based on the browser of the admin so they understand the data in their language.
The campaign detail settings:
- Stats amounts
- Goal progress amount
- Field descriptions
- Create campaign modal
Zip: https://github.com/impress-org/givewp/actions/runs/13311525379 
Update the give settings to a currency other than USD. Make sure the campaign details is reflecting that currency everywhere.
-   [ ] Relevant `@unreleased` …

Refactor: update Campaign details to remove hardcoded USD and locale values in favor of give settings

---

src/Campaigns/resources/admin/components/CampaignsListTable/CampaignsRowActions.tsx
src/Campaigns/resources/admin/components/CampaignsListTable/index.tsx

Resolves [GIVE-2150]
This removes the option to delete a campaign from the campaign list table.
This ensures we avoid unexpected behaviour by deleting a campaign that we have not accounted for yet (ie. abandoned donations, donors, forms, etc.)
The campaign list table
ZIP: https://github.com/impress-org/givewp/actions/runs/13379005587
- Make sure you don't see an option to delete that campaign in list table including bulk actions …

Refactor: remove option to delete a campaign

---

src/Campaigns/Actions/CreateDefaultLayoutForCampaignPage.php
src/Campaigns/Repositories/CampaignPageRepository.php

Resolves GIVE-1386
This PR sets a default layout for the Campaign Page content using campaign specific blocks.

Feature: Campaign Page Default Layout

---

src/Log/Log.php

Fix: Update PHPDoc for Log Method

---

src/Campaigns/Actions/CreateDefaultLayoutForCampaignPage.php
src/Campaigns/Repositories/CampaignPageRepository.php
tests/Unit/Campaigns/Actions/CreateDefaultLayoutForCampaignPageTest.php

Resolves [GIVE-2249](https://stellarwp.atlassian.net/browse/GIVE-2249)
Resolves [GIVE-2259](https://stellarwp.atlassian.net/browse/GIVE-2259)
This PR adds the donation button and story (description) blocks to the Campaign Page default layout.
The story block requires the `shortDescription` of the Campaign, so the simple parser was updated to use merge tags instead of inline variables.
[GIVE-2249]: https://stellarwp.atlassian.net/browse/GIVE-2249?atlOrigin=eyJ …

Refactor: Add donate button, story blocks to Campaign Page

---

src/Campaigns/Repositories/CampaignRepository.php

There was an issue creating a campaign while going through onboarding.  It appears during campaign save were assuming a campaign start date that was not being assigned when initially null.
Campaign creationg
Issue this resolves:
- Create a new GiveWP site and go through onboarding.  
- Make sure campaign is created appropriately

Fix: assign missing campaign start date

---

includes/admin/reports/reports.php

Resolves [GIVE-2315]
This improves the visibility of give_reports_earnings by adding a permission check.
The give_reports_earnings function
N/A
N/A
[GIVE-2315]: https://stellarwp.atlassian.net/browse/GIVE-2315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: improve visibility of give_reports_earnings 

---

src/Campaigns/Actions/CampaignPageTemplate.php

Resolves: [GIVE-2307]
This updates the campaign page visibility with the following criteria:
1. Not visible if `campaignId` does not exist (draft posts resolves to null)
2. Not visible if enable campaign is disabled (regardless of user)
3. Not visible if logged in and campaign status is not active or draft
4. Not visible if not logged in and campaign status is not active
The rest should be controlled by the page's built-in post status
The campaign page visibility
N/A
Test the campaign page visibility:
1. Set Campaign to published and campaign page to draft. (Visible if logged in. Not visible if guest)
2. Set Campaign to draft (Visible if logged in. Not visible if guest)
3. Set enable campaign to disabled (Not visible)
-   [ …

FIx: update campaign page visibility

---

src/Campaigns/Blocks/CampaignGoal/icon.jsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Forms.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Overview.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Settings.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/index.tsx

This pull request focuses on improving code readability and maintainability by converting anonymous default export functions to named functions across several files in the context of Campaigns.
DX only

Refactor: Convert Anonymous Default Export Functions to Named Functions

---

src/API/Endpoints/Reports/Endpoint.php

Resolves [GIVE-2342]
This improves the visibility of the report endpoint by updating the permission check level.
Reporting endpoint
N/A
TBD
[GIVE-2342]: https://stellarwp.atlassian.net/browse/GIVE-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: improve visibility of report endpoint

---

src/Campaigns/Actions/CreateCampaignPage.php
src/Campaigns/Actions/CreateDefaultCampaignForm.php
src/Campaigns/Models/CampaignPage.php
src/Campaigns/Repositories/CampaignPageRepository.php
src/Campaigns/ValueObjects/CampaignPageStatus.php

Resolves [GIVE-2111]
This PR ensures that when a campaign is published, its associated form and page are automatically set to a published state, reducing manual steps for users. It also introduces the `CampaignPageStatus` value object to improve the management of campaign page statuses.
* [`src/Campaigns/ValueObjects/CampaignPageStatus.php`](diffhunk://#diff-8d7b0bbc4d5862f2382e4d1e589d55f8abf3a45c1e57acc09b804c6947e9f7d9R1-R36): Created the `CampaignPageStatus` class to encapsulate different statuses of a campaign page.
* [`src/Campaigns/Models/CampaignPage.php`](diffhunk://#diff-087af49cc12243665aba211c7f1f9f1e620d0abcc9673f9a10053c168fa5fa9cR7): Added the `CampaignPageStatus` property and updated the type definitions and methods to use the new value object.
* …

Refactor: Set Donation Form and Campaign Page as published on Campaign creation

---

src/Campaigns/Repositories/CampaignRepository.php

This PR resolves the issue with the campaigns list table. 
Campaigns list table

Fix: Campaigns list shouldn't break when P2P campaigns exist

---

src/Onboarding/FormRepository.php

Resolves [GIVE-2368]
This pull request simply updates the title of the Donation Form created during the onboarding process.
Onboarding
https://github.com/user-attachments/assets/da234ff2-9f2b-49dd-8fcc-df2f7d2327cc
In a fresh install, go through the Onboarding process. Once completed, confirm the recently created form is named as _Fundraising Campaign Form_.
[GIVE-2368]: https://stellarwp.atlassian.net/browse/GIVE-2368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

Refactor: Update title of Donation Form created by onboarding

---

src/DonationForms/resources/app/hooks/useFormData.ts
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-2178]
This PR refactored the `payPalCommerceGateway.tsx` file to make it use the new `useFormData` implemented previously on this other PR: https://github.com/impress-org/givewp/pull/7600
Also, it fixes the following error that was being thrown on the browser console: 
> Error: Do not pass both createSubscription and createOrder
The PayPal Donations gateway
**Testing cards:** https://developer.paypal.com/tools/sandbox/card-testing/
**Important:** Set up PayPal w/ advanced cards and auto setting
**v3 forms**
1. Make some test donations using the smart buttons (both one-time donations and recurring donations) and make sure everything keeps working as before
2. Make some test donations (only one-time donations) using the card fields and make sure everything keeps working as …

Refactor: replace useWatch hook with useFormData hook

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignDetailsErrorBoundary/Fallback.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignDetailsErrorBoundary/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignDetailsErrorBoundary/styles.module.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx

This adds a little error boundary around the campaign details page.
The campaign details page.
If an error is thrown the error boundary will be shown instead of a blank white page.

Feature: add error boundary to campaign details page

---

src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/CreateWebhook.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/DeleteWebhook.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/GenerateClientToken.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/GetAccessToken.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/UpdateWebhook.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/VerifyWebhookSignature.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalAuth.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php
src/PaymentGateways/PayPalCommerce/Repositories/Webhooks.php

Resolves [GIVE-1984]
This PR adds the PayPal-Partner-Attribution-Id header to all PayPal requests to make it easier for the PayPal team to identify requests coming from our integration.
The requests made to the PayPal API.
- Disconnect and Connect a PayPal account
- Create a test donation with PayPal
- Refund the donation created previously
- Make sure everything keeps working as expected
[GIVE-1984]: …

Feature: add PayPal-Partner-Attribution-Id header to all PayPal requests

---

src/Campaigns/ListTable/Columns/GoalColumn.php
tests/includes/legacy/tests-donors-db.php
tests/includes/legacy/tests-donors.php
tests/includes/legacy/tests-logging.php
tests/includes/legacy/tests-payments.php

This PR resolves the issue with the goal column in the campaigns list table.
Campaigns list table

Fix: Campaign goal column

---

includes/admin/settings/class-settings-gateways.php
readme.txt
src/Onboarding/Setup/templates/index.html.php
src/Onboarding/Setup/templates/stories/src/stripe.js
src/PaymentGateways/Stripe/Admin/AccountManagerSettingField.php

Resolves [GIVE-2379]
This Pull Request updates a copies containing mentions to Stripe fees, including the readme file, used on WP.org.
[GIVE-2379]: https://stellarwp.atlassian.net/browse/GIVE-2379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Remove mentions to Stripe fees

---

src/Campaigns/Blocks/CampaignDonations/render.php
src/Campaigns/Blocks/CampaignDonors/render.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/RevenueChart.tsx
src/DonationForms/AsyncData/Actions/GetAsyncFormDataForListView.php
src/DonationForms/AsyncData/AsyncDataHelpers.php
src/DonationForms/DataTransferObjects/DonationFormGoalData.php
src/DonationForms/V2/Actions/ConvertV2FormToV3Form.php
src/DonationForms/V2/ListTable/Columns/GoalColumn.php
src/DonationForms/V2/Models/DonationForm.php
src/DonationForms/ViewModels/DonationFormViewModel.php
tests/Unit/DonationForms/V2/Actions/TestConvertV2FormToV3Form.php

I discovered a few issues that this will resolve:
1. The donation forms list table was not respecting campaign goal values
2. The donation forms list was not getting accurate v2 form data
3. Donation form goal stats was not always representing the right count value
4. Top donors amount was not correct
5. Revenue graph was being rounded
- Donation forms list table goal/revenue values
- Donation form view goal stats
**2 donations: 25.50 + 26.06 (1.06 fees recovered) = 50.50**
- Set the form to inherit campaign 
- View the donation form list table and make sure the goal matches the campaign goal
- View the donation form view and make sure the stats are accurate (try using recurring goals)
-   [ ] Relevant …

Fix: Donation form goal values

---

includes/admin/payments/view-payment-details.php
src/API/REST/V3/Routes/Campaigns/GetCampaignComments.php
src/Campaigns/Blocks/CampaignDonations/render.php
src/Campaigns/Blocks/CampaignDonations/resources/views/render.php
src/Campaigns/Blocks/CampaignDonors/render.php
src/Campaigns/Blocks/CampaignDonors/resources/views/render.php

Resolves [GIVE-2527]
This ensures we do not display the donor name when they opted into being anymous.
Also, there was an old setting being checked in order to display anonymous value in donation details.  That was removed to always show the value.
The following blocks
- Campaign Donations
- Campaign Donors
- Campaign Comments
- Donation details screen
- Create donations using anonymous
- View the campaign page and make sure the name is redacted
- View donation details and make sure anonymous label is there
-   [ ] [Self …

Fix: redact donor name from campaign page lists when donation is anonymous

---

includes/admin/forms/class-metabox-form-data.php
includes/admin/shortcodes/shortcode-give-donation-grid.php
includes/admin/shortcodes/shortcode-give-donation-history.php
includes/admin/shortcodes/shortcode-give-donor-wall.php
includes/admin/shortcodes/shortcode-give-form.php
includes/admin/shortcodes/shortcode-give-goal.php
includes/admin/shortcodes/shortcode-give-login.php
includes/admin/shortcodes/shortcode-give-profile-editor.php
includes/admin/shortcodes/shortcode-give-receipt.php
includes/admin/shortcodes/shortcode-give-register.php
includes/admin/shortcodes/shortcode-give-totals.php
includes/class-give-cache-setting.php
includes/forms/widget.php
includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php
src/Promotions/ReportsWidgetBanner/ReportsWidgetBanner.php
src/Promotions/ServiceProvider.php

Resolves [GIVE-2555]
This resolves the WP 6.7/6.8 translations notice for GiveWP.  The problem is mainly in our legacy files where all the classes are being instantiated and using translation function in their constructor.  Simply wrapping the instantiation inside an `init` hook both resolves the notice and continues to work properly.
The following related files were touched:
- Old shortcode classes
- Stripe admin settings class
- Old form widget class
- Plugin banner script loading
This is the message that is to be resolved:
ZIP: https://github.com/impress-org/givewp/actions/runs/14929455986
- Make sure WP_DEBUG is enabled
- With this GiveWP installed, you should not see the notice anymore
- Make sure give shortcodes still work 
- Run through all legacy regression testing
-   [ ] …

Fix: Resolve WP 6.7/6.8 translations notice for GiveWP

---

src/Framework/Routes/Router.php
tests/Unit/Actions/GenerateDonateRouteUrlTest.php
tests/Unit/Actions/GenerateDonationFormPreviewRouteUrlTest.php
tests/Unit/Actions/GenerateDonationFormViewRouteUrlTest.php

Resolves [GIVE-2433]
This PR fixes the problem by using the `trailingslashit()` method in the base URL of our routes to ensure that a / always will be added to the end of the subdir portion of the URL.
The `url()` method of the `Give\Framework\Routes\Router` class.
1. Create a new LocalWP site using Apache
2. Move all content from the root directory to a subdirectory
3. Edit the `.htaccess` file by replacing the `RewriteBase /` line with `RewriteBase /your-subdir/`
4. Access the website database and update the URLs in the options table
5. Access the site admin area, go to the permalink settings page, and click on the save button
6. Create a new campaign
7. Access the form and create a test donation
8. Make sure everything works as expected
-   [ ] Acceptance criteria satisfied and marked …

Fix: sites in a subdirectory produce an error when donating via VFB forms

---

src/API/REST/V3/Routes/Donors/RegisterDonorRoutes.php
src/API/REST/V3/Routes/ServiceProvider.php
src/Donors/Actions/LoadDonorDetailsAssets.php
src/Donors/Actions/LoadDonorOptions.php
src/Donors/Actions/LoadDonorsListTableAssets.php
src/Donors/Actions/RegisterDonorEntity.php
src/Donors/DonorsAdminPage.php
src/Donors/ServiceProvider.php
src/Donors/resources/admin/components/DonorDetailsPage.tsx
src/Donors/resources/admin/donor-details.tsx
src/Donors/resources/admin/types.ts
src/Donors/resources/entity.ts
webpack.config.js

Resolves [GIVE-2577]
This pull request significantly refactors the `DonorsAdminPage` by extracting logic into dedicated action classes and introduces the foundational structure for the new Donor Details page. This refactoring aims to improve code organization, maintainability, and paves the way for a more modern and interactive Donor Details experience.
The new Donor Details page is accessible by replacing the `view` param in the URL with `donor-details`.
Donor's Admin Page
1. Access GiveWP > Donors
2. That page must remain looking the same
3. Access a donor in the list
4. You must see the current Donor Details page
5. Edit that URL, replacing `overview` with `donor-details` in the `view` attribute.
6. You must now see the app that will become the new Donor Details page.
-   [x] …

Feature: Register new Donor Details page

---

.cursor/rules/code-style-structure.mdc
.cursor/rules/css-standards.mdc
.cursor/rules/gateway-api.mdc
.cursor/rules/js-react-standards.mdc
.cursor/rules/models-repositories.mdc
.cursor/rules/models.mdc
.cursor/rules/php-standards.mdc
.distignore

An initial set of cursor rules!
N/A
N/A
N/A

chore: add cursor rules

---

src/Donations/resources/components/DonationsListTable.tsx
src/Views/Components/ListTable/ListTablePage/index.tsx

There was already endpoint logic to support filtering by donor id, first_name, or last_name.  This is a quick update that ensures it's possible to use that `&donor={id}` filter in the url.
The donations list table
Go to the donations list table and add `&donor={donor_id}` and make sure it filters by the donor.

Feature: add donor to donation list filter

---

src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php
src/FormBuilder/Routes/RegisterFormBuilderRestRoutes.php

Resolves [GIVE-2625], [GIVE-2628]
This ensures users with capabilities of editing a donation form can actually edit a donation form 😏 
- v3 form access
N/A
ZIP: https://github.com/impress-org/givewp/actions/runs/15478728470
- Login as a Give Worker role
- Make sure you can create and edit a v3 form
[GIVE-2625]: https://stellarwp.atlassian.net/browse/GIVE-2625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Fix: update vfb route user roles

---

src/DonationForms/resources/registrars/templates/fields/Gateways.tsx

Resolves [GIVE-2627]
Enhanced the donation form gateway selection to intelligently filter payment gateways based on donation type, specifically for recurring/subscription donations.
**Smart Gateway Filtering for Subscriptions**
- The component now detects when a donor selects a recurring donation type
- Automatically filters the available gateways to only show those that support subscription payments
- Uses the `supportsSubscriptions` property from gateway configurations to determine compatibility
1. **Detection**: Monitors the `donationType` form field and identifies subscription donations using `isDonationTypeSubscription()`
2. **Filtering**: Creates a filtered list (`gatewayOptionsWithSubscriptionSupport`) of gateways that support recurring payments
3. **Display**: When a subscription …

Feature: filter gateway options based on recurring support

---

src/API/REST/V3/Routes/Donations/DonationStatisticsController.php

This updates the hard-coded gateway links with the existing dynamic filter.
Ref: https://github.com/impress-org/givewp/pull/7985#issuecomment-3005577019
The gateway link in new donation details
- Make a donation with Stripe
- View the donation details
- Make sure the link is accurate

Refactor: add dynamic gateway link to donation details

---

src/API/REST/V3/Routes/Donations/DonationNotesController.php
src/API/REST/V3/Routes/ServiceProvider.php
src/Admin/components/PrivateNotes/index.tsx
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/index.tsx
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/styles.module.scss
src/Donors/resources/admin/components/DonorDetailsPage/Tabs/Overview.tsx
src/Views/Components/AdminDetailsPage/AdminDetailsPage.module.scss

This PR adds private notes functionality to the donation admin screen.

Feature: Donation notes

---

src/DonationForms/resources/registrars/templates/fields/Consent/createIframePortal.tsx

Resolves [GIVE-2281]
This PR fixes an issue where the terms and conditions modal was not working properly on Firefox. The problem was caused by the outdated React DOM render method and improper iframe initialization handling in Firefox.
Terms and conditions modal
https://github.com/user-attachments/assets/4289769c-ea8a-4f36-b9d2-987477fb377a
1. Open a donation form with terms and conditions block in Firefox
2. Click on the terms and conditions link to open the modal
3. Verify that the modal opens properly and displays the content
[GIVE-2281]: https://stellarwp.atlassian.net/browse/GIVE-2281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: terms and conditions modal not working on Firefox

---

src/API/REST/V3/Routes/Donations/DonationController.php
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Records/General/DonationDetails.tsx

This updates the donation details screen with the company and phone fields
New donation screen
Test out the new fields on the donation screen

Feature: add company and phone fields to donation screen

---

includes/admin/donors/donors.php
src/API/REST/V3/Routes/Donors/DonorNotesController.php

Resolves [GIVE-2710]
This updates the donor notes endpoint and legacy view.
Donor notes
N/A
See Jira
[GIVE-2710]: https://stellarwp.atlassian.net/browse/GIVE-2710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: update donor notes endpoint

---

src/LegacySubscriptions/includes/give-subscription.php

`strtotime()` doesn't work with "quarter". Ex:. `strtotime("+1 quarter")` is null.
I suggest to replace it by "3 months".

Renewal date not set if period is quarter

---

src/API/REST/V3/Routes/Donations/DonationNotesController.php
src/API/REST/V3/Routes/Donors/DonorController.php
src/API/REST/V3/Routes/Donors/DonorNotesController.php

This updates the remainder of our string args with a proper format for sanitization.
- Donor Endpoint
- Donor Notes Endpoint
- Donation Notes Endpoint
N/A
- Make sure text fields are sanitized and everything still works properly

Fix: add additional format to REST args 

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementGateway.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementRepository.php

Resolves [GIVE-2720]
This PR implements the `PaymentGatewayRefundable` interface for the **Stripe Element** gateway, which enables the Refund option in the new donations details admin screen.
Stripe Element
1. Create a test donation with the `Stripe Element` gateway and make sure the status gets updated to _"Completed"_.
2. Go to the new donation details screen, click on the three dots menu, and choose the **"Refund"** option;
3. Go to the Stripe dashboard and make sure the donation status is _"Refunded"_.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/co …

Feature: add refund option to Stripe Element gateway

---

src/Donations/Actions/LoadDonationAdminOptions.php
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/DonationSummaryGrid/index.tsx
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Records/General/AssociatedDonor.tsx
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Records/General/index.tsx

Resolves [GIVE-2792]
The associated donor dropdown on the new donation details page was not planned correctly.  The UI will need an enhancement to support large datasets and the implementation will need to rely on the REST API.  Until we have a better solution this feature it will be removed.
- The donation admin screen
N/A
ZIP: https://github.com/impress-org/givewp/actions/runs/16883853478
- Make sure there is no more associated donor setting on the donation records screen
- Make sure there are no regression issues on the donation details page
-   [ ] [Self …

Refactor: temporarily remove associated donor setting 

---

src/FormMigration/FormMetaDecorator.php

Added Text Domain for 3 strings in FormMetaDecorator.php

Added Text Domain for 3 strings in FormMetaDecorator.php

---

src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php

Added Text Domain for one string in RegisterFormBuilderPageRoute.php

Added Text Domain for one string in RegisterFormBuilderPageRoute.php

---

src/Framework/FieldsAPI/Concerns/IsRequired.php

Fixed String Translation in IsRequired.php

Fixed String Translation in IsRequired.php

---

src/Framework/ListTable/ListTable.php

Fixed String Translation in ListTable.php

Fixed String Translation in ListTable.php
