CHANGELOG.md
includes/forms/template.php
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #5893
There are two things going on here.
First, a class is conditionally added if the text is "short" (less than 50 characters) - otherwise the value is an empty string.. This is done with a ternary inside of `classList.add()`. When passing an empty class `classList` throws an error. Instead, this PR conditionally adds the class as a separate statement.
Second, the Recurring Donations add-on (or any use of the `give_form_level_text` that included HTML would show escaped HTML in the rendered text. This PR strips HTML tags when outputting the text.
Note: While originally reported as a conflict with the Recurring Donation add-on, the issue is replicated with a simple filter of the level text. Therefor all changes are made in GiveWP.
| --- | --- |
| ![Screenshot …

Filtered donation level text no longer breaks form HTML

---

CHANGELOG.md
src/Framework/FieldsAPI/Group.php

Adds the missing `TYPE` constant to the `Group` node type.
`Give\Framework\FieldsAPI\Group` and by effect `Give\Framework\FieldsAPI\Types` once #5891 is merged.

Fields API: add missing type to `Group`

---

CHANGELOG.md
src/Framework/FieldsAPI/Types.php

I just noticed that this file was incomplete so I added the missing types. This could prevent bugs if the class was being used as an exhaustive reference for all the node types (the `Factory` class is doing this).
`Give\Framework\FieldsAPI\Types` and anything that uses it.

Fields API: add missing types to `Types` class

---

CHANGELOG.md
src/Framework/FieldsAPI/File.php

The custom validation rules set in `File` were not updated to use the `ValidationRules $validationRules` property on the `Field` class. This PR updates them to do that. This is important since otherwise the rules will appear top-level instead of with all the validation rules during serialization.
`Give\Framework\FieldsAPI\File`

Fields API: set `File` validation rules using `ValidationRules`

---

src/Form/LegacyConsumer/templates/checkbox.html.php

the `placeholder` attribute does not have any effect on checkboxes. But if you happen to use HTML in your label, rendering it can lead to display errors, so remove it.
Also the `for` attribute of the label has to correspond to the `id` attribute of the checkbox, otherwise clicking the label will not affect the checkbox
Labels on checkboxes are now clickable again and HTML labels don't break rendering

Fixes for checkbox template

---

CHANGELOG.md
src/Form/LegacyConsumer/FieldView.php
src/Form/LegacyConsumer/templates/html.html.php
src/Framework/FieldsAPI/Html.php
src/Framework/FieldsAPI/Types.php

As a part of updating the Form Field Manager addon to use the new Fields API, we need to support some of its types which are not all desirable to add to core. In the last cycle, we created an `Html` type which was a sort of back door for us to allow creating some of these types. It was also this particular type which helped us realize the helpful distinction between fields and non-fields in a form.
This is an `Element` type of `Node`. This means that it is a non-`Field` which means that can be filtered out of a collection when appropriate (e.g. registering "required" fields — this wouldn’t make sense for a non-field).
- Adds `Html` class to `Give\Framework\FieldsAPI`.
- Adds `HTML` constant to `Give\Framework\FieldsAPI\Types`.
This is no manual testing required for this PR (other than …

Fields API: add Html node type

---

CHANGELOG.md
src/DonorDashboards/Repositories/Donations.php
src/DonorDashboards/resources/js/app/tabs/donation-history/content.js
src/DonorDashboards/resources/js/app/tabs/donation-history/dashboard-content.js

Resolves #5907 
This PR makes sure that when an admin deletes a donor's donations, and that donor logs in, that donor does not see others donations. It was a very simple fix, as a null check was being done on an empty array, but it's an important fix.
Donor Dashboard donation details
1. Make a donation as a new donor
2. Log in as an admin
3. Delete that donor's donation(s)
4. View the Donor Dashboard as that donor
5. There should be no donations
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code …

Donors without donations no longer see others

---

CHANGELOG.md
assets/src/js/frontend/give.js
assets/src/js/plugins/give-api/form.js
includes/forms/functions.php

Resolves #5912
This PR adds a flag when the page is loaded for reference to prevent a race condition when adding an event listener.
Intentionally triggering a payment error, ie card declined, should restore the user selected donation amount after the donation is attempted.

Payment errors no longer revert to the default donation amount

---

CHANGELOG.md
src/Form/LegacyConsumer/templates/textarea.html.php

This removes an variable that was previously defined from being used in the textarea template. Right now the error doesn’t show up since it is being echo’d into the class attribute on the `<textarea>` elements.
Textareas rendered by the legacy consumer.
Check that textareas rendered by the legacy consumer don’t have a class attribute anymore.

Legacy Consumer: remove undefined variable in Textarea template

---

CHANGELOG.md
src/Form/LegacyConsumer/templates/label-content.html.php
src/Form/LegacyConsumer/templates/radio.html.php

Add missing help text support to Legacy Consumer’s label content and radio templates

---

CHANGELOG.md
package-lock.json
package.json
webpack.config.js

Resolves #5926
The Stripe UI updates added Lodash as an NPM dependency (and removed Lodash from the webpack externals). Since WordPress ships with Lodash we are creating a version conflict by bundling our own copy of Lodash.

Lodash is now an external dependency

---

CHANGELOG.md
src/Form/LegacyConsumer/Commands/SetupNewTemplateHook.php
src/Form/LegacyConsumer/FieldView.php

Resolves #5916
Since the Fields API does not support setting class names, we decided that consumers should use hooks for this instead. This pull request adds a hook/filter for setting a custom class name on the root element for a field.
The hook name is `give_form_{ID}_field_classes_{fieldName}`.
Legacy consumer renderer
Try the filter out when registering fields.

Legacy Consumer: allow custom class name on root element

---

CHANGELOG.md
src/DonorDashboards/Repositories/Donations.php
src/DonorDashboards/Tabs/Contracts/Route.php
src/Onboarding/DefaultFormFactory.php
src/Onboarding/Migrations/SetFormDonationLevelsToStrings.php
src/ServiceProviders/Onboarding.php

Resolves #5940
Converted donation level id and amount value to string in `DefaultFormFactory::getDonationLevels` function which we use to get value for `_give_donation_levels` meta key.
Donate with donation form generated in onboarding process. Donation level and donation amount should store correctely in dopnation meta table and revenue table.

Donation level id and amount value store as string for donation form generate in on-boarding process

---

CHANGELOG.md
assets/src/js/plugins/give-api/form.js

Resolves #5942
I updated logic to set focus on donation amount input field when donor click on "Custom" donation level button.
Multi Step Donation Form Template:
Legacy Donation Form Template (Show all fields)
- You should not able to reproduce issue as mentioned in video added in Rick's comment https://feedback.givewp.com/bug-reports/p/custom-amount-button-does-not-work-well Rick's comment.
- You should not able reproduce issue https://github.com/impress-org/givewp/issues/5912
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code …

Set focus on donation amount field when click on "Custom" donation level id

---

CHANGELOG.md
src/Framework/FieldsAPI/Concerns/HasMaxLength.php
src/Framework/FieldsAPI/Concerns/HasMinLength.php
src/Framework/FieldsAPI/Email.php
src/Framework/FieldsAPI/Phone.php
src/Framework/FieldsAPI/Text.php
src/Framework/FieldsAPI/Url.php
tests/unit/tests/Framework/FieldsAPI/Concerns/HasMaxLengthTest.php
tests/unit/tests/Framework/FieldsAPI/Concerns/HasMinLengthTest.php

Resolves #5947
We discovered that we needed to add validation rules for min/max length for Fields API text types in FFM. This PR implement these as traits (`HasMaxLength`, `HasMinLength`) and adds using them in `Text`, `Email`, `Phone`, and `Url`.
`Text`, `Email`, `Phone`, and `Url` in the Fields API.
Run the tests and try this code out in the root of the repo.
```php
<?php
namespace Give\Framework\FieldsAPI; // Cheating — do not do this for real.
require __DIR__ . '/vendor/autoload.php';
// Too bad if your name isn't Jason or Devin or Matt
Text::make('firstName')->maxLength(5)->minLength(4);
// Try switching out `Phone`, `Email`, and `Url`.
```

Add min/max-length validation to text Fields API node types

---

CHANGELOG.md
src/Form/LegacyConsumer/Commands/SetupFieldConfirmation.php
src/Form/LegacyConsumer/Commands/SetupFieldEmailTag.php
src/Form/LegacyConsumer/Commands/SetupFieldPersistence.php
src/Form/LegacyConsumer/Commands/SetupFieldValidation.php
src/Form/LegacyConsumer/Commands/SetupNewTemplateHook.php
src/Form/LegacyConsumer/FieldView.php
src/Framework/FieldsAPI/Types.php
tests/unit/tests/Framework/FieldsAPI/TypesTest.php

I and @knowler add three filter which support rendering, validating and saving for custom field.
You can test this pull request with FFM: https://github.com/impress-org/give-form-field-manager/pull/352

Add hooks to legacy consumer to handle rendering, validating and saving for custom fields

---

CHANGELOG.md
src/Onboarding/Migrations/SetFormDonationLevelsToStrings.php

Resolves #5949 
This resolves the issue of removing extra donation level data by updating the specific level elements in the original array, preserving any additional data.
The `SetFormDonationLevelsToStrings` migration
1. Use GiveWP 2.13.2 on a fresh install
2. Create a form through the onboarding flow
3. Update to this PR and run the migration
4. The donation level fields should be cast to strings
1. Use GiveWP 2.13.2 on a fresh install
2. Create a form through the onboarding flow
3. Update the donation form levels in the Form to include additional data
3. Update to this PR and run the migration
4. The donation level fields should be cast to strings and the additional data should still exist
-   [x] Relevant `@since` tags …

Fix form donation level migration to honor existing meta

---

CHANGELOG.md
src/Form/LegacyConsumer/Commands/SetupFieldValidation.php
src/Form/LegacyConsumer/templates/base.html.php
src/Form/LegacyConsumer/templates/textarea.html.php
src/Framework/FieldsAPI/Textarea.php

I add maximum field value validation and also add support for mix/max length to texture field.
**Note: I did not add validation for min length.**

Validate input and textarea field value maxlength in field api

---

CHANGELOG.md
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #5956
I find out that a javascript logic was adding additional currency symbol in button title when decimal enabled in multi-step form template.
Try to reproduce the issue as direction given in issue.
Note: run `npm run dev` before testing.

Formatting button display correctly when decimals enabled in Multi-Step Form

---

CHANGELOG.md
includes/admin/emails/abstract-email-notification.php
includes/emails/template.php

Resolves #5962 
This corrects the Payment ID in email previews by using the sequenced ID rather than the table ID. This is in consistency with how real emails actually work.
I also adjusted a query to load the `Give_Payment` objects and reduce the number of necessary queries.
Email previews
1. Go to Donations > Settings > Emails > Donation Receipts
2. Click Preview Email
3. Select a donation
4. Check that the Payment ID matches the sequence, not the table ID
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review …

Display sequential number as payment_id in email preview

---

CHANGELOG.md
assets/src/js/plugins/give-api/share.js
src/Views/Form/Templates/Sequoia/views/social-sharing.php

Resolves #5963
This PR resolves the issue where users were not able to use the share functionality after donating because all data needed for sharing was not encoded.  The issue has been resolved by encoding all the required data ( URL and message ).  
1. Make a donation
2. Share that on Twitter or Facebook. 

Social sharing is now fixed

---

CHANGELOG.md
src/DonorDashboards/Repositories/Donations.php
src/DonorDashboards/resources/js/app/components/donation-receipt/style.scss
src/Receipt/DonationReceipt.php

Resolves #5874
This PR resolves the issue where the Donor billing address was not spaced out. The reason for that is we used `<br>` tags to separate the address details instead of spaces. The issue has been resolved by simply replacing the `<br>` tags with spaces. 
Donation receipt
|---|---|
| ![image](https://user-images.githubusercontent.com/4222590/133242201-0983231a-9b85-4120-8a0f-d1801d1a826f.png) | ![image](https://user-images.githubusercontent.com/4222590/133242083-55ff3884-1390-4bc9-8142-8c3f346bcb03.png) |
-   [x] [Self …

Donor addressed is now spaced out on the Donor Dashboard receipt

---

CHANGELOG.md
assets/src/js/frontend/give.js
src/Form/LegacyConsumer/resources/js/conditinal-fields.js
src/Form/LegacyConsumer/templates/base.html.php
src/Form/LegacyConsumer/templates/checkbox.html.php
src/Form/LegacyConsumer/templates/conditional-visibility-attribute.html.php
src/Form/LegacyConsumer/templates/file.html.php
src/Form/LegacyConsumer/templates/radio.html.php
src/Form/LegacyConsumer/templates/select.html.php
src/Form/LegacyConsumer/templates/textarea.html.php
src/Views/Form/Templates/Sequoia/assets/css/form.scss
src/Views/Form/Templates/Sequoia/assets/css/legacy-consumer.scss
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #5965 
Field API already have logic to define conditional visibility settings for field. This pull request adds support for conditional visibility setting support in Legacy Consumer.
This pull request also has a styling fix for the radio and a checkbox for the multi-step form template. I find out that the hidden checkbox and radio button renders on the label which interrupts the label click, to prevent clitch i moved them away from view.
Either you can define your custom field with visibility conditions or [you can test with the Form field manager addon](https://github.com/impress-org/give-form-field-manager/pull/351).
-   [x] Changes logged to the `Unreleased` …

Implement conditional visibility in legacy consumer

---

CHANGELOG.md
composer.json
composer.lock

Resolves #5873
This PR resolves the issue where connecting to Stripe using PHP 8 on the server was causing errors. The workaround was to downgrade the version of PHP to PHP 7.4. 
The issue is resolved by using the latest version of the `stripe/stripe-php` package.
Tested on a server with various PHP versions:
- PHP 5.6.39
- PHP 7.3.5
- PHP 8
1. Make sure you are using `PHP 8` on your server and that `WP_DEBUG` is enabled
2. Connect the stripe account
3. Make a donation
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews# …

Errors when connecting to Stripe using PHP 8 are now resolved 

---

CHANGELOG.md
src/TestData/Addons/ManualDonations/ManualDonations.php

I was getting a fatal error when run in the wp CLI command on PHP > 7.0.
```
[23-Sep-2021 06:21:37 UTC] PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/TestData/Addons/ManualDonations/ManualDonations.php on line 14
```
I updated the code to maintain compatibility with PHP 5.6.
Test WP CLI command on PHP 5.6 and PHP >= 7.0
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code …

PHP 5.6 compatibility issue when run any WP cli command

---

CHANGELOG.md
includes/class-give-cache-setting.php
includes/forms/template.php
includes/gateways/functions.php
src/Receipt/DonationReceipt.php

Resolves #5979
I find out that we were not replacing the gateways checkout labels with admin-defined labels. I update the code to set the payment checkout label.
this pull request will affect:
- `{payment_method} ` email tag output
- Payment method checkout label in the donation form
Rename payment gateway and
- Donation with gateway and check receipt email
- Check payment gateway label in the donation form

Show admin defined checkout payment gateway label

---

CHANGELOG.md
includes/admin/admin-pages.php

Resolves #5970 
I find out that we are suppressing `array_map` errors with `@` but this does not work in PHP8.0. I fixed the issue by taking care of logic in the anonymous function.
You should be able to update the donation status on PHP8.0

Convert only strings to lowercase

---

CHANGELOG.md
src/DonorDashboards/Repositories/Donations.php

Resolves #5974
I update logic to display time format in WP time format setting in donor dashboard in donation history and dashboard.
Change time format in `Settings -> General -> Time Format` and review time format in donor dashboard.

Use WP time format in donor dashboard

---

CHANGELOG.md
includes/admin/admin-actions.php
includes/admin/emails/abstract-email-notification.php
includes/admin/emails/class-email-setting-field.php
includes/admin/emails/filters.php

Resolves #5989 
This PR updates the preview emails to send to the currently authenticated user's email address, as opposed to determining the recipient based on the settings.
This does change 2 existing translatable strings.
The description for sending a preview email shows the recipient email address.
Sending a preview email hows the recipient email address in the success notice.
Switch to a user with admin access, but that isn't the super admin and send a preview email.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-revie …

Preview Emails are now sent to the authenticated user

---

CHANGELOG.md
assets/src/js/admin/admin-scripts.js

Resolves #5991
This PR adds a hidden input to identify the `donor_id` of the donor that is being deleted.
Note: The custom feedback suggests that this is specifically related to PHP 8, but I was able to also replicate the issue using PHP 7.4.
This specifically applies to deleting a single donor via the donors table, as opposed to the bulk delete donors or deleting from Edit Donor screen.
In the "donors" submenu, click "delete" action item inline of a donor. Confirm that the donor should be deleted and click the "delete" button.
-   [x] [Self …

Single donors can now be deleted via the donors table

---

CHANGELOG.md
src/DonorDashboards/Repositories/Donations.php

Resolves #5997
I find out that we are not passing currency `give_format_amount`. I updated logic to format aggregate on basis of currency.
Try to reproduce the issue with the instructions given in the issue description.

Format amount correctly in 'Lifetime Donations' and 'Average Donation' in donation dashboard

---

CHANGELOG.md
src/TestData/Addons/CurrencySwitcher/CurrencySwitcher.php
src/TestData/Addons/FeeRecovery/FeeRecovery.php
src/TestData/Addons/Funds/FundCommand.php
src/TestData/Addons/RecurringDonations/RecurringDonations.php
src/TestData/Commands/DonationSeedCommand.php
src/TestData/Commands/FormSeedCommand.php

I left a few instances of `Throwable` in code while cleanup in pull request https://github.com/impress-org/givewp/pull/5981
Test WP CLI command on PHP 5.6 and PHP >= 7.0

PHP 5.6 compatibility issue when run any WP cli command 

---

CHANGELOG.md
includes/admin/forms/class-metabox-form-data.php
includes/admin/settings/class-settings-display.php
includes/class-give-scripts.php
includes/misc-functions.php
includes/process-donation.php

Resolves #5994
This PR adds an option to make Donor Last Name filed required. The option is added as a _global option_ in the `Settings > Default Options > Form Fields` screen, and per donation form as well.
Donor Last Name filed
| Global | Donation Form |
|---|---|
| ![image](https://user-images.githubusercontent.com/4222590/135421943-955f455a-7e6d-4550-adc8-811c354752df.png) | ![image](https://user-images.githubusercontent.com/4222590/135422011-45a3aef2-173f-4fa6-9cee-b5df8ff6b77e.png) |
1. Make the Last Name field required ( global option or per donation form option ) 
2. Try to make donation without entering the last name
-   [x] Changes logged to the `Unreleased` …

Option to make Donor Last Name filed required is now implemented

---

CHANGELOG.md
src/Form/LegacyConsumer/resources/js/conditinal-fields.js

Recently we added multi-checkbox support in field API. I find out that condition visibility on the client-side is not working as expected. I find out that the change event does not add to multi checkbox options because of mane contains `[]`. I updated the code to handle the use case
Test whether or not visibility conditions work with simple and array(`[]`) name.

[Field API] Add change event to multi checkbox options

---

CHANGELOG.md
src/DonorDashboards/Routes/VerifyEmailRoute.php

Resolves #5993
This PR updates the response messages which are displayed to the user after he tries to log in to the Donor Dashboard with an email. Both "success" and "failed" messages are now the same in order to prevent malicious users/bots to reveal anything about the user accounts.

Donor dashboard response messages are now updated

---

CHANGELOG.md
includes/class-give-cache-setting.php
includes/gateways/functions.php
src/Views/Form/Templates/Sequoia/Actions.php
src/Views/Form/Templates/Sequoia/assets/css/legacy-consumer.scss

Resolves #5979
I find out that we were not replacing the gateways checkout labels with admin-defined labels. I update the code to set the payment checkout label.
this pull request will affect:
- `{payment_method} ` email tag output
- Payment method checkout label in the donation form
Rename payment gateway and
- Donation with gateway and check receipt email
- Check the payment gateway label in the donation form
- Check payment gateway label on the donation detail page
- Check payment gateway label on gateway listing setting page
-   [x] [Self …

Show custom payment gateway label in donation form

---

CHANGELOG.md
src/DonorDashboards/Routes/VerifyEmailRoute.php
src/Views/Form/Templates/Sequoia/assets/css/form.scss
src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #6010
I refactored multi-step form template javascript to handle radio and checkbox correctly.
- I also added support for FFM restores state from browser session logic.
- I keep the radio and checkbox visible which makes testing easy. I will reset styling once the pull request is approved by the reviewer.
- Test before listing with legacy and multi-step form template.
- Existing checkbox renders within label or outside of the label. I added a test to test both scenarios. [Checkboxes List](https://github.com/impress-org/givewp/blob/07da09593530e8a353b483055e88c98b9839f7c7/src/Views/Form/Templates/Sequoia/assets/js/form.js#L256).
- Radio and Checkbox added by field API should correct state
- when default value set
- when ffm restore the previous state
- "Agree to Terms?" checkbox …

Multi checkbox work fine in Multi Step Form template generated with field api

---

CHANGELOG.md
assets/src/css/frontend/forms.scss

I find out that the `display` property does not set to important which makes it easy to overwrite as we can see conflict in the Multi-step form template. Now DOM element does not display in the form if has `give-hidden` class.
- Create a custom field with FFM form editor and make display when `First Name (give_first)` field set to a specific value.
- Field show or hide on basis of the field value.

Dom element do not display in donation form if has give-hidden class

---

assets/src/js/frontend/give-ajax.js
src/DonationSummary/ServiceProvider.php
src/DonationSummary/resources/js/summary.js
src/DonationSummary/resources/views/summary.php
src/Views/Form/Templates/Sequoia/assets/js/form.js

Depends on #6061
This PR addresses an issue where changing the payment method removed the Donation Summary from the DOM. This was because changing the payment triggers an AJAX request that re-renders part of the form, which in this case included the Donation Summary.
Below are the important parts of this PR (which is chained off of #6061):
Re-render the Donation Summary along with the AJAX request to render the payment method fields.
```php
// Include the summary when changing payment gateways.
if( wp_doing_ajax() ) {
add_action('give_donation_form', function ($formID) {
$summary = new SummaryView();
$summary->__invoke($formID);
$summary->render();
});
}
```
After the gateway is re-rendered, re-position the Donation Summary to the correct location.
```js
/**
* Hack: Changing gateways …
```

Fix: Donation summary accounts for gateway change

---

src/Views/Form/Templates/Sequoia/Actions.php

Resolves #6068
This PR removes a trailing comma from a function parameter list, which isn't supported as of PHP7.2
The Multi-Step form should now load without throwing an error.

fix: Remove trailing comma in function parameters.

---

assets/src/css/icons/fa/_variables.scss

Resolves #6078
This just corrects the path to the Font Awesome icons. We were doing something a bit hacky prior where we were going up an extra directory. Since we’re doing stuff right, we can just go up a level instead of two.
Font Awesome icons in the admin area.
Create a donation form and check the icons are showing up.

Fix: set correct path for Font Awesome icons

---

src/Onboarding/DefaultFormFactory.php

Resolves #6080 
Turns out the warnings were occurring because new settings were introduced (or moved, I couldn't quite tell) in 2.16.0 to the multi-step form. The settings were not added to the onboarding form defaults, so the generated form didn't contain all the necessary data.
While this does fix the immediate problem, I am worried about future issues of the same kind. There's no tie between the settings and the defaults introduced, so it's up to whomever is modifying settings to simply know to update the onboarding defaults.
Onboarding form creation
1. Create a fresh GiveWP install
2. Turn on `WP_DEBUG` and `WP_DEBUG_DISPLAY`
3. Activate GiveWP
4. Go through the onboarding until the page that displays the new form
5. There should be no warnings, just a happy form! ☀️
-   [x] …

Fix: creating a form during onboarding no longer throws warnings

---

src/Controller/Form.php
src/Form/Templates.php

Resolves #6060
When filtering the `lostpassword_url` - for whatever reason - a Give template functions was being called on a page that did not contain a form. The resulting `false` value caused a fatal error.
This PR adds a default value of `legacy` for when the value of `false` is being passed instead of a string representing a template.
The default value is set as `legacy`, which matches a related issue, see https://github.com/impress-org/givewp/pull/4878
From what I can tell this shouldn't cause any issues, but @ravinderk would know better.
- Create a Multi-Step Form
- Enable "login" for the Registration form field setting
- Filter the `loastpassword_url`
- View the form and click "Reset Password"
```php
add_filter( 'lostpassword_url', function() {
return site_url('/donor-login/');
}, …
```

fix: Filtering the lost password URL no longer causes a Fatal Error

---

src/Form/LegacyConsumer/templates/checkbox.html.php

Resolves #6066
https://github.com/impress-org/givewp/blob/12a05ad7ed814e160e53dcacdd628ce5275879b8/src/Form/LegacyConsumer/templates/checkbox.html.php#L34
Above code left unchanged when i refactor code in #6024. Previously visibility conditions were stored in the input field but now there stored in the input field container. 
Removing this line of code will resolve the issue.
- Register a single checkbox and visit donation form with multi step for template.

Fix: prevent PHP notice "Missing template conditional-visibility-attribute.html.php"

---

src/PaymentGateways/PayPalCommerce/PayPalCommerce.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php
src/PaymentGateways/PayPalCommerce/Repositories/Settings.php

Resolves #6083
I updated the PayPal payment request to submit the order as a Donation.
Note:
- "Order Details" section will be added on the transaction details page. These details also appear on the checkbox modal when paying with smart buttons.
- New entries will be added to "Payment Details" section on the transaction details page.
- Create one time donation with smart buttons
- Create one time donation with an advance card field ( I was not able to test because testing cards were not working for me. I am getting authentication error)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-rev …

Fix: update PayPal Commerce payment request data to create order for donation

---

src/Framework/PaymentGateways/Contracts/PaymentGateway.php
src/Framework/PaymentGateways/Contracts/PaymentGatewayInterface.php
src/Framework/PaymentGateways/Contracts/SubscriptionModuleInterface.php
src/Framework/PaymentGateways/PaymentGatewayRegister.php
src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php
src/PaymentGateways/Actions/CreatePaymentAction.php
src/PaymentGateways/Actions/CreateSubscriptionAction.php
src/PaymentGateways/Actions/RegisterPaymentGateways.php
src/PaymentGateways/DataTransferObjects/FormData.php
src/PaymentGateways/DataTransferObjects/GatewayPaymentData.php
src/PaymentGateways/DataTransferObjects/GatewaySubscriptionData.php
src/PaymentGateways/DataTransferObjects/GiveInsertPaymentData.php
src/PaymentGateways/DataTransferObjects/SubscriptionData.php
src/PaymentGateways/Gateways/TestGateway/TestGateway.php

One of the main goals of payment flow 2.0 is to simplify the responsibility of payment gateways.  Currently, the gateways are too aware of GiveWP and are being given all data from the form submission. This makes the gateways somewhat of a _free-for-all_ and unclear to what is actually required for the gateway.  Instead they should only receive data required to process payments.
This PR limits the scope and context of gateways by using common gateway terms for methods with single gateway specific DTOs as params.  All references of _Form_ and _Request_ have been removed from the gateway interface.
**New DTOs for gateways**
- `GatewayPaymentData`
- `GatewaySubscriptionData`
**PaymentGatewayInterface Scope and Context Limiting**
Replace `handleOneTimeRequest()` and …

New: Limit gateway context and scope

---

composer.json
composer.lock

This PR installs the `Yoast/PHPUnit-Polyfills` as a composer (dev) dependency in order to support the recent changes to the WordPress test suite, which is being used as a base for the GiveWP tests.
> **Changes to the WordPress Core PHP Test Suite**
>
> **What does this mean for plugins/themes running integration tests based on the WP Core test suite?**
>
> It is a known fact that there are a lot of plugins/themes which use the WordPress Core test framework as a basis for their integration tests.
>
> If your plugin/theme is one of them, these changes will impact you as well.
Source: https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/#impact-plugin-theme-integration-tests
https://github.com/impress-org/givewp/actions/runs/1451291808
-   [x] Acceptance …

Fix: Update dependencies to support recent test suite changes

---

assets/src/css/frontend/fonts.scss

Resolves #6100
When we switched to Laravel Mix, we needed to change how assets were referenced in CSS to reflect their `dist` path. Not everything was updated. This PR fixes the issue for the icomoon fonts which are used in the legacy form template.
The legacy form template.
Test the legacy form.

Fix: set correct path for icomoon fonts

---

includes/process-donation.php

In BitPay addon pull request https://github.com/impress-org/give-bitpay/pull/10, @kjohnson added logic to process donation on ajax request. [`give_get_donation_form_user`](https://github.com/impress-org/givewp/blob/850362bad2d75b02a8d9544e32b80125bfaf42e7/includes/process-donation.php#L1149) does not perform its checks when donation form validation request runs on ajax but its checks do not run for all ajax requests. I update logic to run check on all ajax request except donation validation request as we are doing in [`give_process_form_login`](https://github.com/impress-org/givewp/blob/850362bad2d75b02a8d9544e32b80125bfaf42e7/includes/process-donation.php#L286) function.
This pull request donation processing.
Process one-time donation with BitPay and any other payment gateway.
-   [ ] …

Fix: check donation validation ajax request correctly

---

.phpstorm.meta.php
src/Helpers/Call.php
src/Helpers/Invokable.php

We all love invokable classes for their single responsibility and actionable nature.  The thing that's not so chill is always having to assign the class to a variable before calling it.  This is largely because PHP 5.6 does not support self-calling.  So to make our lives easier and code cleaner, here's a helper!
❌
```
/** @var Action $action */
$action = give(Action::class);
$action();
$action($args);
```
✅ 
```
Call::invoke(Action::class);
Call::invoke(Action::class, $args);
```
- Invoke an invokable class!
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code …

New: add invokable helper class

---

includes/admin/settings/class-settings-advanced.php
includes/class-give-scripts.php
src/DonorDashboards/RequestHandler.php
src/Form/LoadTemplate.php

Resolves #6077
We removed Babel polyfill when we switched to Laravel Mix initially by happenstance. We decided that we did not need it anymore and that users could add it themselves via a snippet if they needed it. We forgot to remove the enqueue and the admin setting for it. This pull request removes the enqueue and the admin setting.
- Admin settings.
- Every place that loads the frontend JS.
- Every addon that wants the polyfill.
- Load the a Give form and check the page’s console for errors (or the Network tab in devtools).

Fix: remove Babel polyfill enqueue and setting

---

src/Views/Form/Templates/Classic/Classic.php
src/Views/Form/Templates/Classic/resources/css/_currencyswitcher.scss
src/Views/Form/Templates/Classic/resources/css/_donation-amount.scss
src/Views/Form/Templates/Classic/resources/css/form.scss
src/Views/Form/Templates/Classic/resources/js/form.js
src/Views/Form/Templates/Classic/resources/js/not-jquery.js

Resolves #6119
Currency Switcher dropdown is now styled.
1. Install and setup the Currency Switcher add-on
2. View form

New: Currency Switcher dropdown is now styled

---

src/Views/Form/Templates/Classic/resources/css/_funds.scss
src/Views/Form/Templates/Classic/resources/css/_select-dropdown.scss
src/Views/Form/Templates/Classic/resources/css/_text-input.scss
src/Views/Form/Templates/Classic/resources/css/form.scss

Resolves #6125
This PR adds styling to the funds add-on select dropdown. 
Install and setup the Funds add-on.

New: Funds designation addon is now supported

---

src/Views/Form/Templates/Classic/resources/css/_select-dropdown.scss
src/Views/Form/Templates/Classic/resources/css/_text-input.scss
src/Views/Form/Templates/Classic/resources/css/form.scss

Resolves #6127
This PR adds styles to the Stripe gateway inputs. Other gateways like PayPal are affected by this change as well. 
Gateway content, text input styles.
| Stripe PG | Receipt |
|---|---|
|![image](https://user-images.githubusercontent.com/4222590/143844793-4e34a87e-5efb-42df-baed-1384eb97532a.png)|![image](https://user-images.githubusercontent.com/4222590/143845648-f37edf4b-c88f-4069-8ce1-abe46eaccb93.png)|

New: Stripe gateway works

---

src/Views/Form/Templates/Classic/resources/css/_select-dropdown.scss
src/Views/Form/Templates/Classic/resources/css/_text-input.scss
src/Views/Form/Templates/Classic/resources/css/_tributes.scss
src/Views/Form/Templates/Classic/resources/css/form.scss
src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6129
This PR adds support and styles for the Tribute add-on in the Classic Donation Form.
Install and setup tributes add-on
Try every _Tributes Section Location_ where tributes markup can show up in form. 

New: Tributes add-on is now supported

---

src/DonationSummary/resources/views/summary.php

I noticed while developing the Classic template that when I pressed these buttons the browser would focus the wrong input. It took me a while, but I realized it was because the form was submitting and it was focuing a required field that I had left empty. The default value of the `type` attribute for a `<button>` element is `submit` and when in a `<form>` element context, pressing a button will cause it to submit the form. We should set the `type` to `button` to avoid this.
- Donation summary
- No visual change.
Use a donation form with the summary and change that the form doesn’t submit when pressing one of the edit buttons in the donation summary.

Fix: use `type=button` for buttons in donation summary

---

includes/admin/add-ons/actions.php
includes/class-give-license-handler.php

Resolves #6107
As mentioned in the issue description, we were not logging license api failed request information. I added logging logic in `Give_License:: request_license_api `. a log will be added to the system if the response status code is not `200`.
Test this pull request by activating the add-on license.
**Note: To test this pull request you have to mimic the response code ( other than `200` ) in `Give_License:: request_license_api ` function.**

Feature: log failed license api request information

---

includes/admin/forms/class-metabox-form-data.php

Resolves #6145 
This PR updates the default goal amount and the placeholder text to be a more realistic number of `10,000`.
- Default goal amount for donation forms
1. Create a new donation form
2. Enable a goal and see the default goal amount

fix: add default value and update placeholder amount to be 10000

---

src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves impress-org/give-currency-switcher#299
When using multi-step forms, the correct currency is shown in the currency switcher dropdown, but the donation level buttons display the site's default currency.
This resolves that by changing the multi-step form template JS to retrieve the currency symbol/position from the form data instead of from the global vars.
(thank you, @ravinderk and @knowler !)
In my testing, this doesn't cause any unexpected problems with auto-switched currencies, but maybe check that just to be sure.
1. Install GiveWP and the Currency Switcher addon
2. Use USD as global default currency
3. Create a new multi-step form with multiple donation levels
4. Define GBP as your form currency under Currency Switcher
5. Make a test donation. GBP should be displayed as the …

fix: display correct currency for multi-step form donation levels when currency switched

---

src/DonationSummary/resources/js/summary.js

Resolves #6165 
This fixes the donation summary when using give-recurring form settings to accurately display the frequency.
- Added another observer for give-recurring and admin-defined settings.
Go to donation form settings
Set "Donation Option" = "Set Donation"
Set "Recurring Donations" = "Yes - Admin Defined"
Publish form & donate to see accurate summary
Make sure to try other form settings as well.

Fixed: Admin defined recurring donation summary

---

src/Framework/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayRegisterAdapter.php
src/Framework/LegacyPaymentGateways/Contracts/LegacyPaymentGatewayInterface.php
src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php
src/PaymentGateways/Gateways/TestGateway/TestGateway.php
src/PaymentGateways/Gateways/TestGateway/TestGatewayOffsite.php
tests/unit/tests/PaymentGateways/PaymentGatewaysRegisterTest.php

The `give_{$gateway}_cc_form` action passes three parameters: `$formId`, `$args`, and `$echo`.
In the first iteration of the `LegacyPaymentGatewayAdapter` only the `$formId` is being passed along to the gateway.
While migrating the Stripe gateway I realized that the `$args` parameter is necessary for rendering the legacy form field markup. In the case of Stripe, the `$args['id_prefix']` is used to target input fields for mounting the Stripe Elements.
Additionally, there are backwards compatibility considerations. At least for Stripe, the `$args` parameter is passed along to action hooks within the rendering of the HTML.
- …

Add $args parameter for legacy form field markup.

---

assets/src/js/admin/plugin-deactivation-survey.js
assets/src/js/plugins/modal.js

Resolves #6190 
This PR adds a new config option to our modal config. Sometimes you don't want links to open in a new window, as is the case with the plugin deactivation survey.
By default, links will open in a new window. This is because this is likely the preferred behavior for modals, and we don't want to adversely effect other modals currently using the link config option.
The Give modal config.
Try creating a modal or using the deactivation modal. 

Add new option to adjust whether modal links open in a new window or self

---

give.php
readme.txt
src/Views/Form/Templates/Classic/resources/css/_payment-details.scss
src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6202 
The Classic template, up to this point, moved the default payment fields into the payment gateway selection area when the form renders. The problem with this is that the gateway selection area has a `display: none` applied to it when rendered on the server. An option was to simply remove this for Classic, but it looks odd to be prompted as to how to pay when there's only one payment option.
This patch makes moving the fields around conditional, and moves the test notice into view as well. It also brings over the CSS necessary to style things properly when in the new area.
Classic template
See the Issue for instructions on reproducing the issue. It should look _and work_ fine with this PR in place. Be sure to also test multiple gateways, to avoid regression issues.
-   [x] …

Hot Fix: Classic template displays payment fields when there is only one active gateway

---

src/Framework/Database/DB.php
src/Framework/QueryBuilder/Concerns/CRUD.php
src/Framework/QueryBuilder/QueryBuilder.php
src/Framework/QueryBuilder/README.md
tests/unit/tests/Framework/QueryBuilder/CRUDTest.php
tests/unit/tests/Framework/QueryBuilder/CRUD_Test.php

Resolves #6205
To have a more consistent API, Query Builder now includes `insert`, `update`, and `delete` functionality. 
```php
DB::table('posts')
->insert([
'post_title'   => 'Post Title',
'post_author'  => 1,
'post_content' => 'Post Content'
]);
```
```php
DB::table('posts')
->where('post_author', 1)
->update([
'post_title'   => 'Post Title 2',
'post_content' => 'Post Content 2'
]);
```
```php
DB::table('posts')
->where('post_author', 1)
->delete();
```

New: Query Builder now includes insert, update and delete functionality 

---

src/Views/Form/Templates/Classic/Classic.php

Resolves https://github.com/impress-org/givewp/issues/6194
I find out that we were using `Coalesce operator` in a trinary condition which is not compatible with PHP 5.6. I updated the code to make it compatible with PHP 5.6
You should not able to reproduce the issue when following the steps given in the issue description.

Prevent PHP notice on donation form edit screen

---

src/PaymentGateways/DataTransferObjects/FormData.php

I am getting the following error when a donor donates:
```log
[04-Feb-2022 17:08:40 UTC] PHP Notice:  Undefined index: give-logged-in-only in /Users/ravinderkumar/ValetSites/givewp/wp-content/plugins/give/src/PaymentGateways/DataTransferObjects/FormData.php on line 138
```
I find out that this `give-logged-in-only` param add by recurring addon, so I removed it from `FormData` DTO.

Refactor: remove  add-on FormData from Data transfer object

---

includes/class-give-donate-form.php
includes/forms/functions.php
tests/unit/legacy/tests-donate-form-class.php

Resolves #6044
Although it is not possible to enable a goal without a non-zero goal if somehow that happens then the admin should be able to edit the goal set on the donation form screen to fix the issue. I update the default goal amount to `0`.
This pull request also fixes divided by zero issue in `give_admin_form_goal_stats` function. 
|You should not be able to reproduce the issue when following the [steps given in the issue](https://github.com/impress-org/givewp/issues/6044#issuecomment-1041898391).
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX …

Fix: prevent fatal error when goal set to empty string or null

---

assets/src/js/admin/admin-scripts.js
includes/admin/give-metabox-functions.php

Resolves https://github.com/impress-org/give-funds/issues/112
When merging this PR, the https://github.com/impress-org/give-funds/pull/114 should be merged also.
This PR adds support for admins to rearrange the order of funds on the Edit Form screen.
`multiselect` field type
In order to test this, you should be on the [feature/reorder-funds-112](https://github.com/impress-org/give-funds/tree/feature/reorder-funds-112) branch for Funds add-on.
1. Add 3 or more funds
2. Add a donation form
3. Navigate to the `Fund Options` tab and select `Donor's choice`
4. Select all funds in reverse order, or whatever order you like, and hit `Save`
5. The order of the selected funds should be persistent
6. Now preview the Donation Form on the frontend and check the order of funds in the dropdown.
7. The …

New: Admin can now rearrange the order of funds for donor's choice

---

src/DonationSummary/resources/views/summary.php

Resolves #6247
This PR resolves the issue where some files were using an incorrect text domain (`givewp`) for translation strings. The issue is resolved by using the correct text domain - `give`.

Fix: Translation strings are now using the same textdomain across all files

---

src/DonorDashboards/App.php
src/Views/Admin/DashboardWidgets/Reports.php
src/Views/Admin/Pages/Reports.php

Resolves #6243
This PR fixes the issue where GiveWP was referencing missing CSS files `admin-reports-widget.css` and `admin-reports.css`. The issue is resolved by removing the `wp_enqueue_script` function calls that were enqueueing the files. By removing `wp_enqueue_script` calls, everything will continue to function normally because these styles are already included in the `give-admin.css` file. 
Update: 
`wp_enqueue_style` function call for nonexistent file` donor-dashboards-app.css` is also removed
- Install and activate the latest version of GiveWP (2.17.1)
- Visit WordPress dashboard page and check the error console.
- Visit the Reports page and check console too. …

Fix: remove references to missing CSS files

---

src/Views/Form/Templates/Classic/resources/css/_radio.scss
src/Views/Form/Templates/Sequoia/Sequoia.php
src/Views/Form/Templates/Sequoia/assets/css/tributes.scss

Related to impress-org/give-tributes#303
This PR updates the style in GiveWP that relate to the Tributes add-on.
Specifically, updating the selected state when using buttons (instead of radios) caused some layout/overlap issues.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/153660616-f8528d4b-47f3-49d0-9f4c-3489b6fd8725.png) | ![Screenshot 2022-02-11 at 11-20-06 Donation Form with Tributes – WordPress](https://user-images.githubusercontent.com/10858303/153658824-bad0efe9-da06-45d2-b761-41917587a028.png) |
With the Tributes add-on installed and active:
- Create a donation form
- Add multiple tribute options, ie "In honor of"
- Update the tributes display style to "buttons"
- …

Tributes display styles are updated

---

src/DonationForms/Endpoints/ListForms.php

On local site I was getting PHP warnings:
```
[23-Feb-2022 11:42:10 UTC] PHP Warning:  timezone_open(): Unknown or bad timezone (0) in /Users/ravinderkumar/ValetSites/givewp/wp-content/plugins/give/src/DonationForms/Endpoints/ListForms.php on line 153
[23-Feb-2022 11:42:10 UTC] PHP Stack trace:
[23-Feb-2022 11:42:10 UTC] PHP   1. {main}() /Users/ravinderkumar/.composer/vendor/laravel/valet/server.php:0
[23-Feb-2022 11:42:10 UTC] PHP   2. require() /Users/ravinderkumar/.composer/vendor/laravel/valet/server.php:234
[23-Feb-2022 11:42:10 UTC] PHP   3. require() /Users/ravinderkumar/ValetSites/givewp/index.php:17
[23-Feb-2022 11:42:10 UTC] PHP   4. wp($query_vars = *uninitialized*) /Users/ravinderkumar/ValetSites/givewp/wp-blog-header.php:16
[23-Feb-2022 11:42:10 UTC] PHP   5. …
```

Refactor: simplify human readable date logic to prevent php warnings

---

src/Promotions/FreeAddonModal/Controllers/EnqueueModal.php
src/Promotions/sharedResources/hooks/useFreeAddonSubscription.js

Resolves #6259 
When using plain permalink structure, the Free Addon modal would have to be dismissed every time a user opened an admin page. This was happening because the API request that fires after the modal is dismissed was not being sent to the correct URL. The `wpApiSettings`  global only exists when permalinks are not plain, so this PR sets a nonce and API URL whenever the modal would show and fetches based on that.
N/A
1. Go to the admin area
2. Go to Settings -> Permalinks
3. Set the permalink setting to 'Plain Permalinks' and update the settings
4. Install GiveWP
5. If you haven't already dismissed the Free Addon modal, it will show up on any admin page
6. If you have dismissed it, you can make it display again by going to the `wp_options` table in your database (using a tool …

Fix: Dismiss Free Addon modal on plain permalinks

---

src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6263
This PR resolves the issue where the Payment Amount section was not updated when the donor manually changes the donation amount. The issue is resolved by adding an event listener to update the Payment Amount section when manually entering a donation amount.
Classic Template - Donation summary
1. Create a Donation form that uses the Classic template
2. View Donation form on front-end
3. Manually change the donation amount
The Payment Amount section should display the correct donation amount.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and …

Fix: Payment Amount section is now reflecting the Donation amount when the amount changes

---

src/PaymentGateways/Gateways/Stripe/Migrations/AddStatementDescriptorToStripeAccounts.php
src/PaymentGateways/Stripe/Models/AccountDetail.php
src/PaymentGateways/Stripe/Traits/HasStripeStatementDescriptorText.php

Resolves #6270
This pull request is created to address @kjohnson feedback provided in https://github.com/impress-org/givewp/pull/6269
I find out that we do not need to validate the old statement descriptor instead of that we need to filter it, so I created a function in trait to filter text. I am using old stripe statement descriptor requirements which are backward compatible on stripe. Check filter logic in [`give_stripe_get_statement_descriptor`](https://github.com/impress-org/givewp/pull/6226/files#diff-4e5fad63a0905ce3b8f79970fa6ddc84a16407c5151a035cc4b7e2dd2ccd1444) function.
-   [x] [Self …

Fix: resolve stalled statement descriptor migration

---

includes/admin/tools/views/html-admin-page-system-info.php

Resolves #6256 
I fixed `Active GiveWP Add-ons` listing logic. Free addon mark as ` Free addon` in listing.

Fix: do not show free add-on as unlicensed on system info page

---

src/Framework/Migrations/MigrationsRunner.php

Resolves #6274 
This PR resolves the issue where Migration Runner was attempting to re-run failed migrations on each page load.  
The problem was that we were stoping Migration Runner before we stored information about the failed migration. That information is important because it is used by Migration Runner to determine if there are migrations to run. Since this data was missing, the Migration Runner was attempting to re-run failed migration on each page load. 
Migration Runner
1. Download [TestMigrationRunner.zip](https://github.com/impress-org/givewp/files/8159953/TestMigrationRunner.zip) and paste it into `src/` directory. 
2. Add `Give\TestMigrationRunner\ServiceProvider::class` to ServiceProviders list.
3. Navigate to `Tools > Data > Database updates` and check the migrations list - …

Fix: Migration Runner is not attempting to re-run failed migrations on each page load anymore

---

give.php
includes/gateways/stripe/includes/give-stripe-helpers.php
readme.txt

Resolves https://github.com/impress-org/givewp/issues/6278
I find out that `give_stripe_get_connected_account_options()` function return empty string for donation form Stripe account which connected with API keys. [This type of account does not have an account id](https://github.com/impress-org/give-stripe/blob/6da468cbc3885f62d0b7fd4da98071d83933764c/src/Settings/DataTransferObjects/AddStripeAccountApiKeysDto.php#L79). I updated logic to handle this case. If the stripe account does not have an account id then we can use an account slug to get account details.
The donor should be able to donate with a connected stripe account and stripe API key account.
Testing Give File: [give.zip](https://github.com/impress-org/givewp/files/8172239/give.zip)
-   [x] Acceptance criteria satisfied and …

fix: get correct donation form stripe account to process donation

---

src/PaymentGateways/Gateways/PayPalStandard/Actions/CreatePayPalStandardPaymentURL.php
src/PaymentGateways/Gateways/PayPalStandard/Controllers/PayPalStandardWebhook.php
src/PaymentGateways/Gateways/PayPalStandard/Webhooks/WebhookValidator.php

Resolves https://github.com/impress-org/givewp/issues/6280 https://github.com/impress-org/givewp/issues/6281
I updated the webhook handler to respond with `200` HTTP status to unsuccessful PayPal IPN. I log will be added upon failure. Donors will also be able to donate the amount in thousands.
Log Entry on PayPal Standard IPN Error:
- Visit `{home-url}/?give-listener=IPN` and `{home-url}/?give-listener=give-gateway&give-gateway-id=paypal&give-gateway-method=handleIpnNotification` in browser.
- A log will be created because we will be not able to verify IPN.
- You will respond with `200` HTTP status.
- Send IPN from Paypal Iopn simulator to above URLs
- A log will be created.
- You will respond with `200` HTTP status and Paypal will inform you that handshake was successful.
Test GiveWP Zip …

Fix: improve Paypal ipn webhook handling

---

give.php
readme.txt
src/LegacySubscriptions/includes/give-subscription.php
src/PaymentGateways/Gateways/PayPalStandard/Actions/CreatePayPalStandardPaymentURL.php
src/PaymentGateways/Gateways/PayPalStandard/Controllers/PayPalStandardWebhook.php
src/PaymentGateways/Gateways/PayPalStandard/Webhooks/WebhookValidator.php

When creating the Subscription object, the bill_times column was being assigned as a string from the database.  Throughout the codebase we will typically cast the value to an integer.  There was an edge case where this did not happen and caused a type conditional to return true when it should have returned false - resulting in completing Stripe subscriptions.
To fix this upstream, bill_times will be set as an integer from `setup_subscription()` in `Give_Subscription`
- `Give_Subscription`
Follow testing steps from this canny report.
https://feedback.givewp.com/bug-reports/p/stripe-renewal-payments-are-cancelling-the-subscription-at-stripe
-   [ ] Includes unit and/or …

Fix: cast bill_times to an integer in subscription class

---

src/DonationForms/resources/components/DonationFormsTable.tsx
src/DonationForms/resources/components/DonationFormsTableRows.tsx
src/Framework/QueryBuilder/Concerns/TablePrefix.php

Resolves #6282 
When Give's database is prefixed with give_, the Donation Forms page doesn't load, infinitely displaying the loading message.
After some digging, it appears this was happening because of a Query Builder issue. The call to `attach_meta()` in the Donation Forms repository was stripping all of the instances of the prefix from the table name before prefixing it, so `give_give_formmeta` became `give_formmeta`. After some discussion, it was determined the best solution was to keep Query Builder from stripping the prefix altogether.
Before, Query Builder methods would either accept the prefixed or unprefixed table name. After this PR, Query Builder methods will only work with unprefixed table names. The raw SQL methods (i.e. `joinRaw', `selectRaw`) will still use the full …

Fix: don't strip table prefixes in Query Builder

---

src/PaymentGateways/Gateways/PayPalStandard/PayPalStandard.php

Resolves #6294 
We noticed a race condition between donor redirect from PayPal Standard and PayPal Ipn cause donation status issue. Because of this completed donations are set to pending. I update the logic to prevent this issue. From now only pending PayPal Standard donations will be set to processing
PayPal standard donations will have correct donation status and this race condition will never occur.
[give.zip](https://github.com/impress-org/givewp/files/8221167/give.zip)

Fix: set only pending PayPal Standard donation set to processing

---

src/PaymentGateways/Gateways/PayPalStandard/Views/PayPalStandardBillingFields.php

Resolves #6292 
I updated PayPal standard's logo location path to access it correctly. 
Multi-Step form template's donor information for PayPal Standard payment.  
You will see PayPal Standard logo in a multi-step form template.

Fix: access Paypal Standard logo from correct location

---

src/Framework/QueryBuilder/Concerns/WhereClause.php
tests/unit/tests/Framework/QueryBuilder/WhereTest.php

Resolves #6288
This PR adds support for having an `%` wild card in the Query Builder's `whereLike*` functions on both sides of the `WHERE` condition value which will help us to write more optimized SQL queries. 
Note: This is not a breaking change and all the previous usages of the `whereLike* `functions are working just fine.  
Query Builder's `whereLike*` functions
To have a sense of performance impact with this _small_ change:
1. Generate donors by using WP CLI  
`wp give test-donors --count=1000`
3. Now login to MySQL console  
`mysql -u yourusername -p yourpassword` 
4. Run explain command for unoptimized query  
`explain select meta_key from wp_give_donormeta where meta_key like '%donor%'`
5. Now repeat that for the optimized version  
`explain select meta_key from wp_give_donormeta …

New: Query Builder now supports having the % wild card in whereLike* functions

---

src/Framework/QueryBuilder/Concerns/GroupByStatement.php
src/Framework/QueryBuilder/Concerns/MetaQuery.php
src/Framework/QueryBuilder/README.md
tests/unit/tests/Framework/QueryBuilder/AttachMetaTest.php

Resolves #6272 
This PR adds additional functionality to the Query Builder's `attachMeta` function. Now is possible to fetch multiple instances of the same meta key using `attachMeta` and by setting the third parameter of the meta column definition to `true`. 
Fetching all instances is accomplished by using the MySQL `GROUP_CONCAT` aggregate function. All instances of the same meta key will be concatenated into JSON array string. For example, `additionalEmails` value would be `["email1","email2","email3"]`
```php
DB::table('give_donors')
->select(
'id',
['user_id', 'userId'],
'email',
'name',
['purchase_value', 'purchaseValue'],
['purchase_count', 'purchaseCount'],
['payment_ids', 'paymentIds'],
['date_created', 'createdAt'],
'token',
['verify_key', 'verifyKey'],
['verify_throttle', …
```

New: Query Builder's attachMeta now supports fetching multiple instances of the same meta key

---

src/DonationForms/resources/components/AdminDonationFormsPage.module.scss
src/DonationForms/resources/components/AdminDonationFormsPage.tsx

On the Donation Forms admin page, notices were displaying above the contents of the rest of the page, which looked messy. The JS that moves the admin notices places it after the element with the `wp-header-end` class, so I included a hidden element with that class in the header. It seemed cleaner than applying that class to an existing element and negating its styling with CSS.
N/A
Before:
After:
1. Install GiveWP
2. Navigate to the donation forms page (Donations -> All Forms)
3. If there are Give notices visible, verify that they display in the header consistently with other Give admin pages
4. If there are no Give notices visible, you can trigger one by installing Gift Aid and setting the currency to something other than "Pounds Sterling (£)" in Donations -> Settings -> General -> …

Fix: Make Give admin notices display inline with Donation Forms admin page header

---

src/Donations/Models/Donation.php
src/Donations/Repositories/DonationRepository.php
src/Donors/Models/Donor.php
src/Donors/Repositories/DonorRepository.php
src/Framework/Models/Contracts/ModelCrud.php
src/Framework/Models/ModelQueryBuilder.php
src/Subscriptions/Models/Subscription.php
src/Subscriptions/Repositories/SubscriptionRepository.php

The existing `ModelQueryBuilder` required a return union type with every single type of Model, which then meant the IDE would autocomplete _every_ method and property for a given model, as it didn't know which one it is.
Using generics, we can inform the instance which Model class it represents. PHP doesn't actually have generics, but PhpStorm recently added support for inferring generics from docblocks. As you can see, this cleans things up quite a bit.
As a note, the `prepareQuery` return type is needed, for example `@return ModelQueryBuilder<Donation>`. The reason is PhpStorm doesn't _yet_ support [inferring the type from the `class-string<>` parameter](https://youtrack.jetbrains.com/issue/WI-65811).
Existing model repositories
Just make the repositories still work and that …

Refactor: use generics for the ModelQueryBuilder

---

src/Framework/PaymentGateways/Log/PaymentGatewayLog.php

Resolves https://github.com/impress-org/givewp/issues/6310
Donor `CardInfo` was getting logged when an a payment gateway error was thrown. This PR ensures that whenever someone is logging data with `PaymentGatewayLog` the instances of `CardInfo` are removed.
- Option 1: Within a gateway, log the `PaymentGatewayLog` with the entire `$gatewayPaymentData` as a property and make sure the `CardInfo` is not in there when donating with that gateway.
- Option 2: throw a gateway exception in a gateway and make sure the `CardInfo` is not in there when donating with that gateway.
-   [x] [Self …

Refactor: remove cardInfo from PaymentGatewayLog

---

src/Views/Form/Templates/Sequoia/Sequoia.php

Resolves #6318
This PR updates the multi-step template and what is returned from the `Sequoia::getFormExcerpt` function. Before this PR, the default value was the description from Step 1 of the multi-step template, now that's changed to the form excerpt. Description from Step 1 is still used for backward compatibility, but excerpt now has precedence over it. 
`Sequoia::getFormExcerpt` 
1. Create a donation form that use multi-step template
2. Insert some text into the Excerpt field and hit save
3. Create a new WP page and insert Form Grid block
4. Save and preview the page
Text entered into the excerpt field should display as form description 
-   [ ] Includes unit …

Changed:  Form Grid now display excerpts for multi-step forms

---

includes/gateways/paypal/paypal-standard.php
src/Framework/PaymentGateways/Log/PaymentGatewayLog.php
src/PaymentGateways/Gateways/PayPalStandard/PayPalStandard.php

Resolves #6294
I find out that Paypal standard donations remain `processing` because of race condition conflict between PayPal payment redirect after completing payment and  Paypal ipn notification.
I find out that in old logic
- We keep donations to pending mode till we get ipn from Paypal.
- Donor sees receipt after [9 seconds](https://github.com/impress-org/givewp/blob/a3e29a5f385757b96d73f4f1c4231afa39d4ce8b/templates/payment-processing.php#L21) (legacy template)/ [5 seconds](https://github.com/impress-org/givewp/blob/a3e29a5f385757b96d73f4f1c4231afa39d4ce8b/src/Views/Form/defaultFormDonationProcessing.php#L21) (classic & multi step form template) if PayPal ipn did not receive.
I updated the logic to reflect that with the new payment gateway api logic.
This pull request affects Paypal …

Fix: Paypal Standard donations are set to complete

---

give.php
readme.txt
src/PaymentGateways/Gateways/Stripe/BECSGateway.php
src/PaymentGateways/Gateways/Stripe/CheckoutGateway.php
src/PaymentGateways/Gateways/Stripe/CreditCardGateway.php
src/PaymentGateways/Gateways/Stripe/SEPAGateway.php
src/PaymentGateways/Gateways/Stripe/Traits/HandlePaymentIntentStatus.php
src/PaymentGateways/PayPalCommerce/Migrations/RemoveLogWithCardInfo.php

Resolves #6346 
During a recent hotfix #6330 the method used throughout all Stripe gateways `handlePaymentIntentStatus()` was changed to add an additional argument.  The problem was only 1 instance was updated instead of all 4.  This PR reduces that additional `GatewayPaymentData` argument to a simple `donationId` passed as the second param - while updating _all_ the instances of that method.
- All Stripe Gateways have been affected by this PR
Test all Stripe gateways
**Confirm these gateways …

Fix: fatal Stripe gateway errors from missing handlePaymentIntentStatus args

---

includes/gateways/stripe/includes/give-stripe-helpers.php

The maximum number of [Stripe metadata](https://stripe.com/docs/api/metadata) fields as been increased from 20 to 50.
Affect should be limited. More metadata fields will be pushed into Stripe. Otherwise, behavior unchanged. 
I cannot find any documentation if old Stripe api versions support more metadata fields.
NA
Add more than 20 metadata field to a [Stripe payment](https://github.com/impress-org/givewp-snippet-library/blob/master/gateway-customizations/stripe-pass-custom-meta-for-payments.php) using a metadata hook. Create test payments, verify more than 20, but not more than 50, metadata key/value pairs are pushed into stripe.
-   [ ] Includes unit and/or …

Fix: Update stripe meta data count

---

includes/admin/class-blank-slate.php
includes/admin/dashboard-widgets.php
includes/admin/upgrades/upgrade-functions.php
src/DonationForms/DonationFormsAdminPage.php
src/DonationForms/ServiceProvider.php
src/Onboarding/Setup/Page.php
src/Onboarding/Wizard/Page.php

Resolves #6362 
This pull request adds logic to show the new donation form listing page when the admin clicks on the `Donations` menu item.
I also updated  are places that are linked to the legacy form listing page:
-  `Dismiss Setup Page` link on the setup page.
- CTA button link on the donor, donation, and form listing blank slate display.
- In the `At a Glance` dashboard widget
Admin should see a new form listing page when clicking on the `Donations` menu item. Also, check the places I mentioned in the `Affects` section.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-rev …

Fix: show new donation form listing page on `Donations` menu item

---

src/Promotions/InPluginUpsells/resources/js/components/FreeAddOnTab.js

Resolves #6367
I find out that we are not adding the `key` attribute to the` jsx` tag which is required when you print in the loop. I added it to resolve the issue.
Run npm run dev before starting testing.
You should not able to reproduce the issue as mentioned in the issue description.

Fix: react javascript warning on add-on page

---

src/PaymentGateways/Gateways/Stripe/Traits/HandlePaymentIntentStatus.php
tests/unit/tests/PaymentGateways/Gateways/Stripe/CreditCardGatewayTest.php

Resolves #6369 
I find out that we were updating donation status to `processing` even if payment_intent succeeded.  Even though the donation completes with stripe webhook notification but it is nice to give immediate feedback about payment to the donor. I updated logic to complete donation if payment_intent succeeded.
Confirm these gateways are fully functional

Fix: complete stripe payment if payment_intent succeeded

---

assets/src/css/admin/block-editor.scss
assets/src/css/admin/give-admin.scss
blocks/donation-form-grid/edit/inspector.js

This PR updates the Image Size option of the Form Grid block, instead of a regular Text Input field where the user had to enter the image size manually, now we have a Select dropdown field with all image size options registered in WordPress. Also, the frontend form styles are imported into the backend styles so that  Donate buttons inside the Form Grid block look nicer.  
Form Grid Block

New: Form Grid block enhancements

---

src/Form/LegacyConsumer/resources/js/conditinal-fields.js

Resolves #6267
I find out that we are comparing the donation amount numeric value to the expected donation amount string value. I converted the donation amount's actual value to a numeric type to prevent issues.
It will only affect FFM custom field visibility on basis of donation amount field.

Fix: convert amount value to string before comparison with expected string value

---

includes/misc-functions.php

Resolves # 6380
On the Admin Donation Form page, if a user set their goal to display as a percentage, it displayed a dollar amount instead.
Admin donation form page
1. Edit/Create a form
2. Select Donation Goal under Donation Form Options
3. Enable Donation Goal
4. Set Goal Format to “Percentage Raised” 
5. Set Goal amount 
6. Process a donation 
7. View Donations > All Forms

fix Define percentage for actual goal

---

assets/src/css/frontend/donation-history.scss
assets/src/css/frontend/give-frontend.scss
includes/shortcodes.php
templates/history-donations.php

Resolves https://github.com/impress-org/givewp/issues/6358
This PR updates the View Receipt links on a Legacy Donation History page.
If the Donor Dashboard is enabled it will be assigned as the default Donation History page. When a user views a Legacy Donation History page and clicks a View Receipt link, they are redirected to the Donor Dashboard.
- View Receipt links on a Legacy Donation History Page.
- Install GiveWP.
- Enable Override Legacy Donation Management Pages in admin Settings -> General.
- Create  a Legacy Donation History page via [donation_history] shortcode.
- Go to the Donations sidebar > Donations and change the status of several donations to pending, processing, refunded, revoked, failed and pre-approved.
- View the Legacy Donation History page.
- Click View Receipt.
- …

Fix: legacy history page receipt links 6358

---

src/PaymentGateways/PayPalCommerce/ScriptLoader.php

Since the addition of #6388 we have a new param for PayPal called `enable-funding`.  Without enabling this option PayPal was throwing a js error and causing a conflict with the donation form.  This is the error below:
This PR makes sure we are only passing this param to PayPal if a value exists to prevent any errors.
Paypal donations
Disable Venmo and make sure paypal donations work correctly.

Fix: only add enable-funding param to PayPal donations if value exists

---

src/Framework/Models/Model.php
tests/unit/tests/Framework/Models/TestModel.php

Consider the following:
```php
$donation->donor->firstName = 'Jason';
$donation->donor->lastName = 'Adams';
```
Presently, this will actually trigger two implicit queries. When the `donor` property is accessed it queries the donor under the hood. This means that in both cases when the donor is accessed it's querying the model. This is bad for a few reasons:
1. It's really counterintuitive
2. It's an easy performance sink
3. The object returned changes every time, so the second line is actually done to a different model
This PR adds a very light caching layer that stores relations after the first query. This allows for things like the example to happen and perform as one would intuit.
Model relationships
Grab a donation and then retrieve the donor twice. The two objects should be the …

Feature: cache model relations

---

includes/emails/class-give-email-tags.php
includes/gateways/offline-donations.php

Resolves #4671
When using form specific tags in the offline donations instruction global content like `{form_title}`, the form does not render anything when offline is selected.  This is because these tags are looking for a `payment_id` which doesn't exist.  We just needed to pass along the `form_id` we already have.
- The underlying class is `Give_Email_Template_Tags` which is used for email rendering and apparently other things like offline donation content rendering on a form
Use `{form_title}` in your global offline instructions content and make sure the correct title is displayed on your form when selecting offline donation.
-   [ ] Includes unit and/or …

Fix: update offline donation instruction tags to resolve when used globally in a form

---

includes/admin/settings/class-settings-advanced.php

Resolves #4930
Unless the give-setup page is enabled, it just returns a 403.   I think this because the page doesn't actually exist until it's enabled.  So for a quick fix we can just conditionally enable the link depending on the settings. 
The advanced settings page.
- enable and disable the option 

Fix: disable give-setup link in settings when page does not exist

---

src/Views/Form/Templates/Classic/resources/css/form.scss
webpack.mix.js

Resolves #6408 
There are some visual issues when using the PayPal Donations gateway in the Classic template, as documented in the Issue. Unfortunately, the button width issue is a limitation of the PayPal styles that we don't have control over and can't target — since the elements are inside an iFrame.
This does fix the "Or pay with card" section, though, which is arguably the worse of the two.
PayPal Donations in the Classic template
Use the PayPal Donations gateway in a Classic template form.
-   [x] ~Relevant `@unreleased` tags included in DocBlocks~
-   [x] ~Includes unit and/or end-to-end tests~
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX …

Fix: correct visual PayPal Donations issues in Classic template

---

includes/install.php
src/MigrationLog/Migrations/CreateMigrationsTable.php

I notice a WordPress database error on a fresh install because the migration table installs to the database during migration, so few queries fail to migrate the table We have fallback logic to this but the log generates for error.
You will not see database errors under the `Run Tests` section.

Fix: prevent WordPress database error notice on fresh install

---

includes/admin/tools/views/html-admin-page-system-info.php

I find out that we were not showing migration and log table installation status in system info (`Donations > Tools  > System Info`). This pull request adds these tables to the system information page.
this pull request affects only the system information page.
You should able to see migration and log table on system information page.

fix: show migration and log table in system info

---

src/Framework/Database/DB.php
src/Framework/Database/Exceptions/DatabaseQueryException.php
src/Framework/Exceptions/Contracts/LoggableException.php
src/Framework/Exceptions/Traits/Loggable.php
src/Revenue/Repositories/Revenue.php
tests/unit/tests/Framework/Exceptions/UncaughtExceptionLoggerTest.php

The `DatabaseQueryException` was created before the uncaught exception logging was created, as such it's extending the base `Exception`, instead of the GiveWP primitive. This PR remedies this and adds the methods to best log the broken query.
I also cleaned up a couple minor, related things.
Specifically, how uncaught query exceptions are handled. But it does broadly touch all queries.
Throw a `DatabaseQueryException` without catching it, then check the logs to make sure it's there.

Improvement: update DatabaseQueryException to log when uncaught

---

src/Log/Log.php

Resolves https://github.com/impress-org/givewp/issues/6410
I find out that `array_diff` generates a warning for multi-dimensional arrays, so I replace it with. `array_diff_key` to prevent PHP from warning. We were using `array_diff` to remove log config keys from `context`, we can achieve same result with `array_diff_key`.
It only affects `Log`.
You should not able to reproduce issue when follow `Steps to reproduce`.

Log does not generate PHP warnings

---

assets/src/js/admin/reports/app/index.js
includes/admin/views/html-admin-settings.php

Resolves #6365
By default Wordpress will place admin notices directly after the first H-tag element. This was causing various notices to be placed inside our header component. This PR corrects that issue in the Reports & Settings pages by introducing a hidden element "wp-header-end". The admin notices now display beneath the header and are structured the same as the other pages.
1. Donations > Settings
2. Donations > Reports

Fix: admin notice's correctly display beneath the header

---

includes/admin/admin-actions.php
src/DonationForms/DonationFormsAdminPage.php
src/DonationForms/ServiceProvider.php
src/Donors/DonorsAdminPage.php
src/Donors/ServiceProvider.php

Resolves #6419 
In 2.20.0 we introduced new admin UI list pages — donors and donations. On these pages you can switch and from the new view to the old one. Unfortunately, if the user switched to the legacy view the button they were given to return to the new view would show up all over the admin dashboard, not just on the list view pages they make sense on. Oops.
This PR fixes that. It also makes a minor correction to some inconsistent wording in the buttons that returned to the new view.
The new admin list views, and in a way all the pages that the buttons were incorrectly showing up on before.
1. Switch the form, donation, and donor list screens to the legacy view
2. Check the plugins page, edit form page, and anywhere else to make sure the buttons don't show up
3. Switch back to the …

Fix: Prevent "switch view" buttons from showing up incorrectly

---

includes/forms/functions.php
src/Framework/PaymentGateways/CommandHandlers/PaymentProcessingHandler.php

Resolves #
- I was getting an error on PHP8.1 when processing donations with SEPA.
```
[20-May-2022 14:52:46 UTC] PHP Fatal error:  Declaration of Give\Framework\PaymentGateways\CommandHandlers\PaymentProcessingHandler::getPaymentStatus() must be compatible with Give\Framework\PaymentGateways\CommandHandlers\PaymentHandler::getPaymentStatus(): Give\Donations\ValueObjects\DonationStatus in /Users/ravinderkumar/ValetSites/givewp/wp-content/plugins/give/src/Framework/PaymentGateways/CommandHandlers/PaymentProcessingHandler.php on line 21
```
2. Payment method does not auto-select when donor redirects back to donation form error on error. 
https://github.com/impress-org/givewp/blob/143c526e508d208b2e322b5f086591871ed49a66/src/Framework/PaymentGateways/PaymentGateway.php#L310
I fixed both …

Fix: php 8.1 compatibility issue

---

src/Framework/Database/DB.php
src/Framework/Database/Exceptions/DatabaseQueryException.php

Recently I added the errors to be included in the `DatabaseQueryException`, and set it up for auto-logging. I did not, however, include the failed log within the query. Frankly, I didn't know this was so easily doable until the illustrious @ravinderk pointed it out to me.
This PR adds the query to the exception to make it even easier to troubleshoot! 🪄✨
Failed database queries
1. Make some failed query (syntax, or whatever)
2. Check the exception to include the failed query
3. Check the log to include the failed query
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) …

Enhancement: Query is now caught and logged in failed queries

---

give.php

WordPress 5.5 handles plugin PHP version requirements. Suppose the plugin added PHP version in the plugin header and readme.txt file that is sufficient for WordPress to validate PHP compatibility before installing or activating the plugin. I think it is safe to remove the custom minimum PHP version compatibility validation logic.
I discussed it with @JasonTheAdams  and he agrees that it is safe to remove.
Change the PHP version to `9.0` or anything greater than your PHP version in the plugin header after that try to install and activate the plugin. On WordPress 5.5, you should not able to install/activate the plugin if the PHP version is lesser than the required version.
-   [x] Relevant `@unreleased` tags included in …

Fix: remove php dependency validation logic

---

src/PaymentGateways/Actions/RegisterPaymentGateways.php

Since merging https://github.com/impress-org/givewp/pull/6427 there are still some _new_ hooks that need to be converted to use the givewp prefix for their actions.  This PR notably changes the `give_register_payment_gateway` and `give_unregister_payment_gateway` to `givewp_register_payment_gateway` and `givewp_unregister_payment_gateway`.
Please note this is a _breaking change_ since some internal gateways are using this hook.  Since this api is not documented yet for the public, we should safely be able to update our internal gateways with these.
External gateway registration
Register a gateway with this hook
-   [x] …

Changed: use givewp prefix for gateway registration actions

---

src/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayAdapter.php

Resolves #6434
This pull request adds the missing donation meta for the initial subscription donation.
You should have `_give_subscription_payment ` in the subscription initial donation. `subscription_id ` meta key value is also set to subscription id instead of zero.

Fix: add legacy subscription data to initial donation meta

---

src/Framework/PaymentGateways/Log/PaymentGatewayLog.php
src/PaymentGateways/Gateways/Stripe/Actions/CreateCheckoutSession.php
src/PaymentGateways/PayPalCommerce/PayPalCommerce.php
tests/unit/tests/PaymentGateways/PaymentGatewaysRegisterTest.php

`GatewayPaymentData` class has been removed from the GiveWP core. I find out about this class at a few places in code. In this pull request, I removed them.
I also added logic to change log `source` to the payment gateway name when the log generates from `PaymentGatewayLog`. this help to quickly catch the source of the log.
Generate the `PaymentGatewayLog` log. You should see the payment gateway name in the `source` column in the log listing table.
```php
PaymentGatewayLog::error(
'{Error Message}',
[
'Payment Gateway' => $this->getId(),
'Donation' => $donation,
]
);
```
-   [x] [Self …

Refactor: remove GatewayPaymentData class reference from code

---

templates/shortcode-goal.php

https://github.com/impress-org/givewp/commit/16e564b22272d326ddc12fccbaa162e49cdbe43b removed support for the filtered income value `$goal_progress_stats['raw_actual']` and this just makes that filterable again. It does this in a generalized way that lets anyone filter the income OR goal values in the context of this goal shortcode.
An added bonus here in this PR is that it passes the `$args` so that it can support even more complex queries for customization at the shortcode level for custom shortcode args like date ranges, etc.
Customizing the current goal so that it's based on a date range. For instance, fundraising for specific versions of a free plugin so that once the fundraiser is over, the next version can have it's own separate income/goal without creating totally separate forms. …

Fix/Changed: Bring back filter support for income goal stats

---

includes/class-give-readme-parser.php
tests/unit/legacy/test-addon-readme-parser.php

This pulls updated regex to extract the Give core minimum version from the add-on readme.txt file. It support `Requires Give` and `Requires GiveWP` readme.txt header tag.
I created this pull request for: 
It will affect the plugin's updated process.
Replace 'Requires Give' with  'Requires GiveWP' and set the version number to `2.25.0` in any add-on readme.txt and use a custom snippet to find out version.
```php
require_once GIVE_PLUGIN_DIR . 'includes/class-give-readme-parser.php';
$readmeParser = new Give_Readme_Parser(WP_PLUGIN_URL . '/give-square/readme.txt');
$readmeParser->requires_at_least(); // output value of "Requires GiveWP" or "Requires Give"
```
-   [x] …

New: allow add-on to use 'Requires GiveWP' to define dependency

---

src/Framework/PaymentGateways/PaymentGateway.php

I find out that we are not catching all exceptions when processing one-time or recurring donations. The `try…catch` should catch the PHP Exception, not our own primitive.
You should redirect back to the donation form page with an error when throwing a custom PHP Exception.

fix: catch all exceptions when process one time or recurring donation

---

includes/gateways/stripe/class-give-stripe.php
includes/gateways/stripe/includes/payment-methods/class-give-stripe-card.php

Resolves:
https://feedback.givewp.com/admin/feedback/bug-reports/p/editing-stripe-credit-card-for-recurring-subscriptions-should-work-properly-usin?boards=bug-reports
While recently updating the Stripe gateway to use the new gateway api, some legacy files were removed.  One of those being `Give_Stripe_Card` which was still being used by give-recurring.  This was preventing subscription updates on the legacy donor dashboard.  This PR adds back the necessary file with just what is currently needed.
- Stripe give-recurring subscription updates
- Create a page with the [give_subscriptions] shortcode at [example.com/legacy-subs](http://example.com/legacy-subs)
- Create a form that creates a WP user for all donors (disable guest donations and add registration/login fields
- Disable email access …

Hot Fix: Restore ability to change subscriptions via legacy subscription shortcode

---

assets/src/css/admin/settings.scss
src/Views/Components/ListTable/ListTablePage.module.scss

Resolves #6426
In ListTablePage.module.scss the default padding of #wpbody is removed. This is necessary to avoid odd spacing in "All Forms", "Donations" & "Donors". This style however will be applied to any page that contains the ListTable component. Both the Log & Data tab use this component. As a result it will have the default padding removed & uneven styles across the tool tabs.  This PR corrects this issue by reintroducing the same amount of padding to the specific tabs that are affected.
Donations > Tools > Log & Data tabs
1. View Donations > Tools > Log & Data tabs
2. Check that all tabs are spaced/styled the same
3. Check that Donations > All Forms, Donations & Donors are unaffected
4. Collapse Side Navigation and ensure spacing works as intended …

Fix: Tool tabs display correctly

---

includes/api/class-give-api-v2.php

Resolves #6374
Related #6375
This PR removes the endpoint `give-api/v2/donor-wall` from the REST API.
It was determined that this endpoint is not in use, so instead of patching the endpoint with a nonce we decided to remove it all together.
Making a request to `/wp-json/give-api/v2/donor-wall` should return a `404 Not Found`.

refactor: Remove Donor Wall REST API endpoint

---

src/Form/LegacyConsumer/Actions/DetermineVisibilityForRequest.php
src/Form/LegacyConsumer/Commands/SetupFieldValidation.php
tests/unit/tests/Form/LegacyConsumer/Actions/DetermineVisibilityForRequestTest.php

Resolves impress-org/give-form-field-manager#389
This PR implements a visibility check on fields before validating each field as required. This is in addition to the client-side validation that was previously solely responsible for considering visibility for required validation.
The issue in impress-org/give-form-field-manager#389 manifested as an issue with checkboxes because an unchecked checkbox does not submit with the form.
Additionally, this PR updates the required check to check for empty values. Previously it just checked that the value was seet in the `$_POST` array, but that would allow empty values to pass validation on the server.
<sup>1</sup> Previously, required validation for textboxes was only checked by the browser (HTML5 validation), but the server did not validate …

feature: Check visibility before validating required.

---

src/Framework/Exceptions/Traits/Loggable.php
tests/unit/tests/Framework/Exceptions/Traits/LoggableTest.php

I am periodically fatal errors because of logging logic for uncaught exceptions. It happened because we are hiding confidential data  (present in context). Exception object contains debug backtrace data which causes an infinite loop (few times).
I updated logic to log only meaning for data instead of an object.
ref: https://github.com/impress-org/givewp/blob/d54be4c35c8e3342cc6d928697b6868419aa259c/src/Framework/Exceptions/Traits/Loggable.php#L35

feature: update default context for loggable exception

---

src/Donations/Controllers/DonationsRequestController.php
src/Donations/DataTransferObjects/DonationResponseData.php

Resolves #6461
The donations table was not recognizing renewals and instead saying they were "one time" donations within the payment type column.  This PR fixes that and improves the stability of the query utilizing the `DonationMetaKeys` helper.
The Donations list table.
Make sure you have a mix of donations, subscriptions, and renewals in your site and view the donations list table.  The Payment types should all make sense and specifically renewals have a renewal payment type.

Fix: renewals now display the correct payment type

---

src/DonorDashboards/resources/js/app/components/subscription-cancel-modal/utils/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/utils/index.js

I find out that the donor dashboard does not perform subscription actions like update subsection and cancel subscriptions for logged donors (with WP user account, email access disabled). I update logic to add authentication nonce to the rest API query to prevent request failure issues.
-  Disable email access
-  Create a subscription with Stripe credit card
-  Login to donor dashboard with WP user
- Perform cancel subscription or modify subscription action.
Donors should be able to update credit cards, recurring donation amounts, and cancel subscriptions for stripe credit card payment methods when donors logged in with WordPress user accounts.
-   [ ] Includes unit …

Fix: LoggedIn donor can perform authorized actions in donor dashboard

---

includes/admin/upgrades/upgrade-functions.php
src/Log/LogServiceProvider.php
src/Log/Migrations/CompleteRemovedLegacyLogMigration.php
src/Log/Migrations/MigrateExistingLogs.php

Migration should complete when the plugin users upgrade from GiveWP <=2.0.  Rick provided me with a database that has an issue and after investigation, I find out that the migration process was blocked by a migration that has a dependency migration that was removed earlier. I added a fix to complete the migration.
Slack discussion: https://lw.slack.com/archives/C02PQ6F648P/p1654813134457039
You will find out that database dump in the slack channel. You should be able to complete the migration.

Fix: prevent stalled migration issue

---

src/Views/Form/Templates/Classic/optionConfig.php

Resolves #6452
This PR adds visibility attribute to header background color on Classic form templates. This is used to either display or hide the header options when enabled/disabled.  Previously it was always visible, leaving the impression that you can somehow change the color of a header that doesn't show up on the donation form.
z
Classic Form templates
https://user-images.githubusercontent.com/75056371/173668742-b2a2f7ec-f34d-4ac3-ad52-b01ce8d501c0.mov
1. Create a form using the Classic form template.
2. Form Template - Visual Appearance - Display Header
3. Enable & Disable
4. Ensure header options properly display and work when enabled & are hidden when disabled …

Fix: header background color properly displays when enabled

---

includes/shortcodes.php

The green that was implemented here is not the official GiveWP green. It should instead be: `#69b868`

Use GiveWP brand colors for Form Grid defaults

---

assets/src/css/frontend/_components.donor.scss
includes/donors/class-give-donor-wall.php
includes/gateways/manual.php
templates/shortcode-donor-wall.php

Resolves #6477
This PR includes several fixes for the Donor Wall. It fixes two Php warnings/errors from within the Donor Wall, includes some style updates for the block and improves the functionality that displays comments. 
We found that the test donation gateway was not saving  anonymous donations to the database.  This caused an error for donations marked as anonymous on the front end. 
We also found that if the comment length set by the inspector control was higher than the actual length of the comment, it would not display.
- Undefined variable $donor has been corrected by being properly passed to the template.
- Undefined index ['_give_anonymous_donation'] has been corrected by being properly saved to the database.
- Donation amounts will no longer wrap to the next line.
- Comments …

Fix: Php errors from enabled comments inside the Donor Wall have been corrected

---

src/Views/Form/Templates/Sequoia/assets/js/form.js

Resolves #4944
This pull request adds logic to reflect the required field in the donation form in the Multi-step form template instead of the optional field. The asterisk (*) will be added to the required field placeholder.
This pull request affects the donation form required field placeholders in the Multi step form template.
All required field placeholders should contain the `*` asterisk symbol in the placeholder.
Test this pull request in user cases where a new field will be added to donation for like:
- Tributes addon adds fields to the donation form
- The gift Aid add-on adds fields to the donation form
- You can enable a few fields like address fields, donor comment, company name, name title prefix, etc.
Make sure the field should mark correctly when a few donation fields appear …

Feature: reflect required field in donation form

---

includes/admin/tools/export/class-export-earnings.php
includes/admin/tools/views/html-admin-page-exports.php
src/Donations/Repositories/DonationRepository.php

Resolves #
While exporting revenue and donation stats, the start year and end year should be in the valid year range. The year value should be in the first donation and last donation year range. I update the business logic to revoke exporting process if the year is invalid.
- throw an exception if any date param missing from request
- throw an exception upon an invalid year. it should be in the valid year range. the first year of donation to last year of donation is a valid donation year range.
-  show valid year choices in the year dropdown.
It will affect `Export Revenue and Donation Stats` feature.
Exported data should remain the same when compared with the latest GivewP release.
-   [x] Relevant `@unreleased` tags …

Security: protect against invalid export dates

---

includes/donors/class-give-donor-wall.php
templates/shortcode-form-grid.php

Resolves #6499
From within the Form Grid the  function give_goal_progress_stats() was being used to retrieve data for the goal section. It was being called regardless of the Donation Goal form options being enabled. This was causing a warning to be displayed by the goal section on the Form Grid with Fee Recovery enabled and Donation Goals disabled. This PR adds a check for the settings to be enabled before continuing.
1. Form Grid
https://user-images.githubusercontent.com/75056371/176282418-3cf44adc-aaf6-4df6-a4aa-357e7eb520e0.mov
1. Enable define( 'WP_DEBUG_DISPLAY', true );
2. Create a form
3. Enabled Fee Recovery
4. Disable Donation Goals
5. View FormGrid - make sure Show_Goal is toggled on in the inspector controls 
6. View page for warnings
7. Enable Donation Goals from form settings …

Fix: Honor form goal settings in form grid

---

includes/gateways/stripe/includes/class-give-stripe-webhooks.php
src/PaymentGateways/Gateways/Stripe/Webhooks/StripeEventListener.php

Plugin users can set different Stripe accounts for donation processing within the donation form. Although donation completes but Stripe webhooks are getting `400` HTTP responses. This issue happens because fetching stripe webhook event details with the wrong stripe account. (`Give\PaymentGateways\Gateways\Stripe\Webhooks\StripeEventListener`) Event Listener base class has logic to fetch stripe event detail from Stripe, so there is not any requirement for this logic, and can be removed without side effects. 
Slack discussion:
- https://lw.slack.com/archives/C02PQ6F648P/p1656518031239759
- https://lw.slack.com/archives/C02PQ6F648P/p1656612107795789
This will affect  Stripe webhook handling logic to one-time and recurring donations.
Stripe webhook should get `200` HTTP response if a donation …

Hotfix: prevent 400 HTTP error for Stripe webhook event

---

includes/admin/emails/class-donor-register-email.php
includes/admin/emails/class-new-donor-register-email.php
includes/admin/emails/filters.php
includes/emails/template.php

Resolves #6502 
We've been adding a lot of `esc_url` throughout the codebase to protect against XSS attacks. In some cases, however, the function is too aggressive and `esc_url_raw` should be used. One such affected place was when previewing an email for a specific donation. This PR uses the raw function to prevent those URLs from breaking.
Previewing an email for a specific donation
1. Go to Settings > Emails
2. Choose an email(e.g. Donation Receipt) and click Preview
3. Select a donation to preview
4. Should work! ✨
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) …

Fix: resolve broken email previews for specific donations

---

includes/admin/tools/export/class-export-earnings.php

This is a follow up to #6482. That prevented invalid dates, but didn't cover the edge case wherein the site has no donations. This covers that scenario by simply forcing the export to the current month and year. It doesn't matter as there aren't any donations, and it's not worth a bunch of UI effort as having zero donations is an incredibly unlikely scenario in GiveWP — much less someone trying to export statistics for such a site.
The donation stats exporter
1. Delete all donations
2. Run the exporter with some crazy dates
3. Check that the resulting file just reflects the current month/year and is empty
-   [ ] [Self …

Fix: limit date range to current year/month when no donations

---

includes/donors/actions.php
includes/gateways/manual.php
src/LegacySubscriptions/includes/give-subscription.php
tests/unit/tests/Donations/Models/TestDonation.php

Resolves #1131
At some point we removed legacy code that updated the anonymous donation meta. This PR adds back support to update the `_give_anonymous_donation` meta that will cover one-time donations using legacy gateways, subscription initial donations, and renewals (legacy subscriptions).  
One-time donations (legacy gateways), New subscriptions (initial donation) and renewals (legacy subscriptions)
- Create a subscription with anonymous donation enabled & make sure the subscription _Initial Donation_ reflects this.
- Create a renewal and make sure it's anonymous donation is enabled.
- Check the donor wall for a visual.
- Try donating one-time with "Test Gateway" or any other legacy gateway to make sure anonymous is working.
-   [x] Acceptance criteria satisfied and marked in related …

Hot Fix: anonymous donations are now supported across donation types

---

includes/currency-functions.php
src/Onboarding/Routes/CurrencyRoute.php

This cleans up an admin vulnerability wherein an admin could, through some real effort, set the currency symbol to something crazy. The `give_currency_symbol` function would then load it into random places as-is, creating a vulnerability. A big note here is that it must be a user with admin access to exploit the vulnerability.
I patched the issue in two places:
1. The endpoint that opened up the vulnerability now validates the incoming value such that it can only be a 2-letter value, anything else will be rejected.
2. The `give_currency_symbol` function now escapes HTML so XSS scripts and such should be prevented from doing anything.
The endpoint for setting a currency symbol and the function used to retrieve said symbols.
Contact me for testing instructions. …

Hot Fix: prevent XSS vulnerability in currency symbol

---

assets/src/css/admin/_components.admin-header.scss
src/Donors/resources/components/DonorsRowActions.module.scss
src/Views/Components/ListTable/ListTablePage.module.scss
src/Views/Components/ListTable/ListTableRows.module.scss

Resolves #6504
The padding and margin styling were affecting how the List Table components were being aligned within certain pages.
This PR removes and simplifies styling so that the List Table Components are also symmetrically aligned everywhere the component is used without affecting the other pages that it is not used on. This PR also slightly lowers the gap in between the actionable buttons on each Table row within the List Tables.
- All Give Subscription tabs
- Tools > Logs Tab
- Tools > Data Tab
https://user-images.githubusercontent.com/75056371/177422215-bc0a47b7-ce01-4436-98c9-6964ae08ee3e.mov
- View "Donations" [Top Level admin Tab]
- View all subscription tabs for the correct spacing on the header and content.
- View Donation Forms for slimmer spacing between "edit, view ,trash …

Fix: List table page styling consistencies

---

includes/admin/tools/export/class-export.php
includes/admin/tools/views/html-admin-page-exports.php

To help prevent against CSRF attacks, a nonce has been added to the donation stats exporter.
Donation stats exporter
Make sure that the stats still work. Otherwise, try triggering an export without the nonce and it should block you.

Security: add nonce to donation stats export

---

give.php
includes/admin/tools/export/class-export-earnings.php
includes/admin/tools/export/class-export.php
readme.txt

#6511 adds a nonce to the donation stats export to prevent CSRF attacks. Unfortunately, we missed that the check for the nonce was being applied to the parent class, affecting all exporters. They don't have the nonce, so they broke. This limits the nonce check to _only_ the stats exporter.
Exporters
Make sure the nonce is required for the stats exporter, and make sure all other exporters still work.

Hot Fix: Resolve nonce issue on exporters

---

includes/forms/template.php

To further proactively improve security in GiveWP, this PR adds a bunch more escaping to the form rendering template. We haven't had any reported exploits, but the additional escaping will help make sure no injection is possible within forms — arguably the most critical part of GiveWP.
As escaping goes, this shouldn't break any existing proper functionality, but doing things like setting the currency symbol to contain html, or setting the legacy template modal button caption to include markup, and things like that, should now just show up as text in the front-end — it should not allow for new DOM elements or, especially, JavaScript.
How the amount field render, and also the modal display button in the legacy template.
Primarily we just need to test that everything still work as expected. …

Fix: add additional escaping to the legacy form rendering

---

.github/workflows/close-stale-issues.yml

Related: https://github.com/impress-org/givewp-github-actions/commit/de33e10b5cb9734495deeb97734cfe2f8086dbef
This PR adds a new workflow for marking stale issues and automatically closing stalled issues.
Note: This workflow is initially configured in debug mode and will result only in a dry-run so that we can test the configuration without altering any issues incorrectly.
Note: For the full configuration, see [impress-org/givewp-github-actions/.github/workflows/close-stale-issues.yml](https://github.com/impress-org/givewp-github-actions/blob/master/.github/workflows/close-stale-issues.yml)
```yml
days-before-issue-stale: 45 # ~6 weeks accounts for cycle length
days-before-pr-stale: 45 # ~6 weeks accounts for cycle length
days-before-issue-close: 14 # 2 weeks accounts for cool-down …
```

chore: Add automation for closing stale issues

---

includes/admin/misc-functions.php
includes/admin/settings/class-settings-email.php
includes/admin/settings/class-settings-general.php

Resolves #6229 
This PR adds the ability to automatically download the SendWP plugin, register and attempt to activate the plugin. It includes a description of what SendWP is, when Give recommends it, and why you should use it.
GiveWP Email Settings page
- This can only be tested from a publicly available URL (not local) as the process of connecting & disconnecting requires redirects back to the site.

New: Adds SendWP integration to email settings admin page.

---

src/Framework/FieldsAPI/Concerns/TapNode.php
src/Framework/FieldsAPI/Element.php
src/Framework/FieldsAPI/Field.php
src/Framework/FieldsAPI/Group.php
tests/unit/tests/Framework/FieldsAPI/Concerns/TapNodeTest.php

This PR introduces a tap method to `Element`, `Field`, and `Group` nodes. Tapping a node allows for that node to be updated without breaking the fluent syntax of the Fields API.
```php
$field = Field::make( 'my-field' )
->label( 'My Field' )
->tap(function( $node ) {
// Custom code here
})
->isRequired();
```
For group, child nodes can be tapped using the fluent syntax of the Fields API.
```php
// Tap a nested node by name.
$group->getNodeByName( 'child' )->tap( ... );
```
Create a node and call the tap function. Changes to that node should be reflected and the fluent syntax should not be broken.
-   [x]  Includes unit tests …

Nodes in the Fields API can now be tapped

---

give.php
src/Framework/Database/Actions/EnableBigSqlSelects.php
src/Framework/Database/DB.php
src/Framework/Database/ServiceProvider.php

Resolves #6527
This adds an action `givewp_db_pre_query` to our DB class for optimizing mysql before running data retrieval queries.
There is also an easy way to set mysql big selects using the DB class `DB::enableBigSelects()`.
With this action people can do things like this:
```
add_action('givewp_db_pre_query', function() {
static $bigSelects = false;
if (!$bigSelects) {
global $wpdb;
$wpdb->query('SET SESSION SQL_BIG_SELECTS=1;');
$bigSelects = true;
}
});
```
or with our helper
```
add_action('givewp_db_pre_query', function() {
\Give\Framework\Database\DB::enableBigSelects();
});
```
or target more specific queries
```
use Give\Framework\Database\DB;
use Give\Framework\Support\Facades\Str;
add_action('givewp_db_pre_query', function($sql) {
if (Str::contains($sql, 'LEFT JOIN')){ …
```

Fix: prevent MAX_JOIN_SIZE limit from occurring and blocking queries

---

src/Framework/FieldsAPI/Group.php
tests/unit/tests/Framework/FieldsAPI/GroupTest.php

This PR introduces a `tapNode()` method to the `Group` node type. Similar to the `tap()` method, except that `tapNode()` will return the group node.
```php
$group = Group::make('my-group')->append(
$node = Text::make('my-text')
)->tapNode('my-text', function( $tappedNode ) {
//
}); // returns $group
``` 
Create a group with a nested node and call the `tapNode()` method on the group, specifying the nested node by name. Changes to that node should be reflected and the fluent syntax should not be broken.

Nodes in a Group can now be tapped

---

includes/admin/plugins.php

When a user deactivates GiveWP they have the option to fill out a survey which lets us know why they deactivated. This has been around a long time. One problem, however, is that if the survey server is down for some reason, the deactivation will fail. This should just not be. Whether or not our server receives the survey data, the user should always be able to deactivate.
Plugin deactivation
1. Go to includes/admin/plugins.php line 614 and change the URL to some invalid address
2. Deactivate the plugin and fill out the survey
-   [ ] [Self …

Fix: failing to send deactivation survey data should not block deactivation

---

src/DonorDashboards/Block.php

Resolves #6553 
Gutenberg edit mode activates when clicking event fires on block container children (DOM elements) or focus set to block container. I find out that clicking on an element in the iframe does not bubble the element in the parent window.
I added logic to set focus to block containers when the admin clicks iframe elements.
https://user-images.githubusercontent.com/1784821/186596276-d22f55c6-0cc9-452d-a1ef-0c7ff8db5b60.mov
You should be able to edit the donor dashboard Gutenberg block and settings should display when clicking on the donor dashboard interface.
-   [x] [Self …

Fix: activate donor dashboard Gutenberg edit mode when admin clicks on interface

---

src/DonorDashboards/resources/views/donordashboard.php
src/Views/Form/Templates/Classic/resources/views/receipt.php
src/Views/Form/Templates/Sequoia/views/receipt.php
src/Views/Form/defaultFormReceiptTemplate.php
src/Views/Form/defaultFormTemplate.php
src/Views/IframeContentView.php

Resolves #6550
This PR adds the second parameter of `the_title` filter in the iframe content view to prevent a fatal error from being generated when another plugin or theme uses this same filter with the [two available parameters](https://developer.wordpress.org/reference/hooks/the_title/#parameters) - **$title** and **$id** - but without setting a default value for the second one.
- IframeContentView
1. Create a form and add it to a page
2. In the **/wp-content/mu-plugins/** folder add a **test.php** file with the following content:
```
<?php
add_filter( 'the_title', function ( $title, $id ) {
return '$id = ' . $id . ' | ' . $title;
}, 10, 2 );
```
3. Access the form's page and now it should load without generating any error or delay
-   [x] Acceptance criteria satisfied and marked in …

Fix: iframe forms now are loaded when other plugins or themes hook a function to the 'the_title' filter

---

assets/src/css/frontend/form-grid.scss
blocks/donation-form-grid/class-give-donation-form-grid-block.php
blocks/donation-form-grid/data/attributes.js
blocks/donation-form-grid/edit/inspector.js
includes/shortcodes.php
templates/shortcode-form-grid.php

Resolves #6533
This PR removes the [show_bar] attribtue for the FormGrid block/shortcode.The Progressbar will now display properly for all users who use the FormGrid Shortcode. The [show_goal] attribute is now the determining factor for displaying all goal statistics. It also includes the proper background for the progressbar within the FormGrid.
- FormGrid
https://user-images.githubusercontent.com/75056371/184986681-78d62561-4978-4499-a9cf-48c6bf6a0f99.mov
- Create a page and use the FormGrid shortcode [give_form_grid]. View the page and Verify the FormGrid displays with the progressbar. The default value is true.
- Use the FormGrid shortcode again with attribute "show_goal" = false [give_form_grid show_goal=false]. Verify the goal section of the FormGrid is hidden.
- Use the FormGrid …

Fix: shortcode `give_form_grid` now only uses `show_goal` to display progress bar

---

assets/src/css/admin/paypal-commerce.scss
assets/src/js/plugins/dynamicListener.js
src/PaymentGateways/PayPalCommerce/AdminSettingFields.php

Resolves #6566 
This is another stab after #6567 didn't resolve the problem. The true problem is the fact that when a user translates a page using Chrome the browser swaps out the disconnect anchor and doesn't move over its event listeners properly, as well as adding font tags which does more strangeness. This is not a problem in Safari, for example.
This PR changes the anchor to a button for two reasons:
1. An anchor with a "#" href is semantically incorrect. It doesn't go anywhere, so it's not an anchor — it's a button (that looks like text).
2. Buttons handle what is inside them differently, so the translated tags inside aren't an issue. Buttons assume everything inside of them belong to themselves. Anchors are more flexible as folks put all sorts of stuff in anchors, so they're less …

Fix: Disconnecting from PayPal works correctly when translated in Chrome

---

give.php
readme.txt
src/Donations/LegacyListeners/DispatchGiveInsertPayment.php

Resolves #6570
This PR sets the correct WP user id instead of the donor id in the `give_insert_payment` hook.
All the gateways that use the Gateway API as PayPal and Stripe for example.
Just follow the same instruction describe here: https://github.com/impress-org/givewp/issues/6570

Hot Fix: send new user email notifications with correct user data when using the gateway API

---

includes/admin/upgrades/upgrade-functions.php
includes/class-give-cache.php
includes/class-give-cli-commands.php
includes/class-give-donor.php
includes/filters.php
src/Framework/QueryBuilder/Concerns/WhereClause.php
src/LegacySubscriptions/includes/give-subscriptions-db.php
tests/includes/legacy/tests-cache.php
uninstall.php

Resolves #6572
Related to https://github.com/impress-org/give-recurring/pull/1139
This PR updates the use of wildcard placeholders when calling `WPDB::prepare()`.
When using a substitution argument in conjunction with a prepared `LIKE` clause, the wildcard placeholders should be passed as a part of the argument and not concatenated in the query.
While this did not previously result in a syntax error, the recent changes in 6.1 highlight this issue.
> Literal percentage signs (%) in the query string must be written as %%. Percentage wildcards (for example, to use in LIKE syntax) must be passed via a substitution argument containing the complete LIKE string, these cannot be inserted directly in the query string.
See https://developer.wordpress.org/reference/classes/wpdb/prepare/
- Update …

Fix: Percentage wildcards are now passed via a substitution argument containing the complete LIKE string

---

assets/src/js/frontend/give-donations.js

Resolves #6580 
On mobile, when scrolling the page while touching a donation level button is triggering the event to set the donation amount. This PR removes the `touchend` even listener as the `click` event listener remains and it's properly triggered when intended.
Donation level buttons on touch screens.
https://user-images.githubusercontent.com/3921017/196291288-26b97a9a-893c-477f-a360-bc03227f9bc6.mp4
Create a multi-step form with multiple donation levels.
On mobile, scroll down the form page while touching one of the donation levels, after you scroll, the donation amount must remain the same. …

Fix: Prevent amount selection when scrolling on mobile

---

assets/src/js/frontend/give-ajax.js
src/Views/Form/Templates/Classic/resources/css/_errors-notices.scss

Resolves #6584
Errors messages are not being displayed on forms using the Classic template. This PR fixes the selector being used to print the ajax response data when on a Classic template form and adds margins when multiple errors are displayed at the same time.
Classic template
1. Create a form using the Classic template
2. Go to the page with that form
3. Enter "123" as the first name
4. An error must be displayed

Fix: Display error messages on Classic template

---

includes/shortcodes.php
templates/shortcode-form-grid.php

Resolves #6590
This PR updates the default value for the `donate_button_text_color` property of the `give_form_grid` shortcode to inherit the text color to match the surrounding elements.
The `give_form_grid` shortcode used directly uses the `donate_button_text_color`, where as the newer Block wrapper for the shortcode always specifies a text color, thus the default is not used.
| Shortcode used directly |
| :---: |
| `[give_form_grid show_donate_button=true]` |
| ![Screen Shot 2022-10-20 at 15 57 26](https://user-images.githubusercontent.com/10858303/197045640-7ed250e6-4c14-4fff-9d67-483e5b5211b6.png) |
| Block wrapping the shortcode |
| --- |
| ![Screen Shot 2022-10-20 at 15 57 56](https://user-images.githubusercontent.com/10858303/197045792-4135bc62-1de2-480a-9c89-143090fc626d.png) | …

Form Grid donate button text color now defaults to black

---

src/Donations/Repositories/DonationRepository.php

Resolves #
give()->donations->getLatestDonation() gave the first donation and vice versa.
solve : invert sort order DESC <--> ASC
this was the easiest method to get the job done
give()->donations->getLatestDonation()->id 
must be greather than 
give()->donations->getFirstDonation()->id

Fix: fix the sort order to get the expected result

---

src/Exports/DonorsExport.php

Resolves: #6597
In class-batch-export.php, it's important to have the same order for column names and data. Otherwise, in the export file, ZIP and country are reversed.
First the print_csv_cols() function prepares the column names in the order in which they are defined.
Then the print_csv_rows() function prepares the data, regardless of column slug,in the order in which it is defined.
---
- To see the specific tasks where the Asana app for GitHub is being …

Fix: ZIP and country corrected for donor exports

---

tests/Config/Config.php
tests/Config/Local.php
tests/Config/Workflow.php
tests/Framework/Addons/Bootstrap.php
tests/Framework/TestHooks.php
tests/bootstrap.php

Introducing a new way of bootstrapping our test suite in GiveWP add-ons: `GiveTests\Framework\Addons\Bootstrap`. 
**Imaginary Give Addon**
```
give-addon
- give-addon.php
- tests
- bootstrap.php
```
**bootstrap.php file**
```
<?php
use GiveTests\Framework\Addons\Bootstrap;
require __DIR__ . '/../../give/vendor/autoload.php';
(new Bootstrap(__DIR__ . '/../give-addon.php'))
->load();
```
Notice all we need to do is
1. Pull in the main give autoload file
2. Instantiate the `Bootstrap` class with the path to our main add-on file and call `->load()`
Under the hood, we are using the path to load our add-on using the WP test filter `'muplugins_loaded'` - then loading the GiveWP bootstrap file.
This does not directly affect anything until used.  
There's one minor update in our main GiveWP …

Tests: Introducing api for add-on test suite bootstrapping

---

src/Promotions/InPluginUpsells/SaleBanners.php

This PR adds the banner for the upcoming Giving Tuesday sale. I also made some minor code improvements.
Please make sure the messaging and go link are all correct.
View on Loom: https://www.loom.com/share/3419c207833145b390eaf59fb7ac3954
The banner should show up in the settings and add-ons page.
Clicking the "x" should hide the banner for that user, including reloading the page.

Feature: Giving Tuesday 2022 Banner

---

includes/class-give-donor.php
includes/deprecated/deprecated-functions.php
includes/formatting.php

Resolves #6606
I found out that a few functions have the first function argument optional but the second required which caused PHP deprecated notices. I made these arguments required.
You should not get PHP deprecation notices on php8.0 when processing a donation.
-   [] Relevant `@unreleased` tags included in DocBlocks

Fix: prevent php deprecation notices on php8

---

src/Form/LegacyConsumer/templates/base.html.php

This PR prevents a fatal error when using the base template in the Legacy Consumer for a date field. There is no specific template for the date field, so the base template is being used. However, the base template assumes that the field type uses `HasMaxLength`, which the date field does not. This will additionally prevent a fatal error for any field type that uses the base template but does not support a max length property.
```diff
<?php
-    echo ($maxLength = $field->getMaxLength()) ? "maxlength=\"$maxLength\"" : ''; ?>
+    if( method_exists( $field, 'getMaxLength' ) ) {
+        echo ($maxLength = $field->getMaxLength()) ? "maxlength=\"$maxLength\"" : '';
+    }
+    ?>
```
Register a custom date field on a donation form and check that no uncaught `BadMethodCallException` is thrown. …

Fix: Add check before calling getMaxLength

---

src/Subscriptions/ListTable/Columns/StatusColumn.php

Resolves #6624
- Adds wordpress _n function to determine if a limited recurring donation amount has one or several donations left and uses the correct noun to represent the sentence.
- Also includes a strong tag to bolden the word failed on the failing subscription tool tip. 
-Subscription Table
- Create a limited subscription with only one donation left,
- Create a limited subscription with several donations left.
- View the subscriptions table.
- Hover over the limited subscriptions to view the tooltip and verify the sentences have either a singular or a plural noun for the word donation/donations.
- View A failing subscription to verify the word failed is now bold. …

Fix: Limited subscription tooltip messages use correct nouns.

---

src/Donations/DonationsAdminPage.php
src/Donations/resources/components/DonationsListTable.tsx

Resolves #6637
- Donations Table 
- Install & activate manual donations add-on.
- Visit donations table and use the new donation button at the top.
- deactivate manual donations add-on.
- Verify new donation button is removed.

Fix: New Donation table button added for users with the Manual Donations Add-on

---

src/Views/Components/ListTable/ListTable/ListTable.module.scss
src/Views/Components/ListTable/ListTable/index.tsx

Resolves #6648
The loading spinner on the react tables are set to display directly in the middle of the table. This styling works well when the table has a limited amount of items to display. As items are added, the page becomes scrollable and the table extends downward causing the animation to display farther down. The spinner is not immediately visible to most users without scrolling downward because most of the table actions that cause the animation reside at the top of the table. I propose adding conditional styling to detect if the documents body is scrollable. If it is scrollable apply a fixed styling to the spinner. This will display a fixed spinner when scrollable and will keep the original styling position in the middle of the table when not. 
React list table …

Fix: Loading animations are immediately visible regardless of page height

---

src/Donations/LegacyListeners/DispatchGiveInsertPayment.php
src/Donations/Migrations/AddMissingDonorIdToDonationComment.php
src/Donations/Migrations/AddMissingDonorIdToDonationComments.php
src/Donations/ServiceProvider.php
src/PaymentGateways/DataTransferObjects/GiveInsertPaymentData.php

Resolves #6646
I find out that `donor_id` is required to add a donation comment, and the legacy adapter does not set it in `user_info`.
https://github.com/impress-org/givewp/blob/bdb780a9124eb3586796612f654bd2a7c09d5900/includes/donors/actions.php#L25
https://github.com/impress-org/givewp/blob/bdb780a9124eb3586796612f654bd2a7c09d5900/src/Donations/LegacyListeners/DispatchGiveInsertPayment.php#L38
I updated the logic set missing user information: `address` and `donor_id`. A correct format of `user_info` is required for most of the legacy code.
I also added a data migration to set the missing donor id in donation comments.
Donor Comments should appear in donor wall ( if enabled) when processing donations the following:
- Stripe
- Paypal donations
- Test Donation
Note: previous donor …

Show donor donation comment in donor wall when donate with Stripe credit card

---

src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6652
This PR updates the tool tips aria label to use the parent nodes label as its own value. This is allowing it to update properly while switching between multiple currencies. Previously the passed nodes innerHTML property was being used to set the label and consisted of an HTML element.
Classic Form donation level tool tip.
https://user-images.githubusercontent.com/75056371/209094029-03979249-c587-4142-893b-091b1a1b02dd.mov
- Install Currency Switcher.
- Create and visit a Classic form.
- Switch currencies and hover over a donation level.
- Verify tooltips label updates accordingly.
-  …

Fix: Classic form template's donation level tooltip now displays with the labels

---

includes/api/class-give-api.php

Resolves #6465
This PR wraps the description text "Generate API Key" with a `<label/>` so that the checkbox can be toggled by clicking on the label.
- Go to `wp-admin/profile.php`.
- Scroll to the setting "GiveWP API Keys".
- Toggle the "Generate API Key" by clicking on the label.

Fix: Add missing label to checkbox input

---

src/DonationForms/resources/components/DonationFormsListTable.tsx

Related https://github.com/impress-org/givewp-next-gen/pull/112
This PR checks for a registered Next Gen Form URL and conditionally renders a button.
I tried to keep this simple. The Next Gen feature plugin will register the URL on the window.
Install and enable the Next Gen plugin, using https://github.com/impress-org/givewp-next-gen/pull/112, and the "Add Next Gen Form" button should render.

chore: Integrate next gen form button

---

src/MultiFormGoals/MultiFormGoal/Model.php
src/MultiFormGoals/ProgressBar/Model.php
src/MultiFormGoals/resources/js/blocks/multi-form-goal/edit/index.js
src/MultiFormGoals/resources/views/multiformgoal.php
src/MultiFormGoals/resources/views/progressbar.php

It was brought to our attention that the `give_multi_form_goal` shortcode was missing proper data esacping for it's attributes during render.  This PR updates the view and related progress view to escape all dynamic content.
The `give_multi_form_goal` shortcode
N/A
**Vulnerability**
Pull the branch and make sure this doesn't trigger an alert: `[give_multi_form_goal image='" onerror="alert(/XSS/)"']`
**General**
Make sure the shortcode and block still work properly
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX …

Fix: `give_multi_form_goal` shortcode escapes rendering properly

---

includes/donors/class-give-donor-wall.php

This adds more on top of https://github.com/impress-org/givewp/pull/6668
The limit and offset are currently being directly injected. This forces the values into an absolute integer before being injected. The reporter mentioned they weren't able to actually exploit anything, but this should be done anyway.
The donor wall query
Reach out to me for instructions.

Fix: Sanitize the donor wall limits

---

src/DonationForms/DataTransferObjects/DonationFormQueryData.php
src/DonationForms/ListTable/Columns/LevelsColumn.php
src/Framework/ListTable/ListTable.php
tests/Unit/DonationForms/DataTransferObjects/DonationFormQueryDataTest.php

Resolves #6674
This PR prevents a fatal error caused by donation forms missing the Price Option meta (`_give_price_option`).
Previously, `\Give\DonationForms\DataTransferObjects\DonationFormQueryData::getDonationFormLevels()` would throw a fatal error when the Price Option was `null` because it assumed a non-`mulit` value for the Price Option was the value of `simple` which results in a `TypeError` in `Give\DonationForms\Properties\DonationFormLevel::fromPrice()`.
1. Checkout `develop`.
2. Delete the `_give_price_option` meta value for a donation form.
3. Navigate to `/wp-admin/admin.php?page=give-forms`
---
- https://app.asana.com/0/0/1203776617039851

Fix: Prevent fatal error for null price option in the Forms Table

---

src/Framework/LegacyPaymentGateways/Adapters/LegacyPaymentGatewayRegisterAdapter.php

Related: https://github.com/impress-org/givewp-next-gen/pull/115
As we start connecting exiting gateways to our next gen forms, we need a way to know if the gateway supports legacy.  Some gateways like Stripe payment element will only be available in next gen - so they should not be displaying in legacy forms. 
Note: At first the plan was to use the `LegacyPaymentGatewayInterface` to determine if a gateway supports legacy forms.  Unfortunately at the moment, that is tucked away in our main `PaymentGateway` class and would be too much effort to pull it right now.
This PR is a simple & safe solution to accomplish what we need for the time being.
Will only affect next gen forms being displayed on legacy forms.
N/A
Just make sure gateways are displaying properly on a form. …

Feature: add `is_visible` param to legacy adapter gateways list

---

includes/admin/settings/class-settings-general.php
src/Donations/Migrations/SetAutomaticFormattingOption.php
src/Donations/ServiceProvider.php
src/Framework/Support/Facades/CurrencyFacade.php

Since 2.24.0 we're having issues with customers whose servers are running PHP without the intl extension installed. This is currently used for formatting currency amounts in the list tables. While we'd like to improve internationalization and make auto-formatting of currencies happen, we need to give folks time to upgrade their systems. Truth is, most folks won't really even notice the difference (especially admin-side).
This PR does the following:
1. Adds a new Currency setting to allow customers to opt in or out
2. Adds a migration which sets the initial value based on whether they have the intl extension
3. Provides a failsafe so, no matter what, the intl classes won't be used if not available
**Note:** This intentionally does not affect auto-formatting when it occurs in the browser — …

feature: add setting for automatic formatting

---

includes/forms/template.php

With esc_url() escaping the redirect URL, special characters like &#038; as preserved, and the modal window is not open. As for preview messages, I suggest using esc_url_raw().
Resolves #

Fix Modal is not open after an error

---

composer.json

I was experiencing an `sh` error when the `strauss.phar` file check was done using the `[[` syntax, which resulted in `strauss.phar` being downloaded every time that I ran `composer install` or `composer update`. This changeset switches to using the `test` command instead.
I ran a test with this `test` check in place on a fresh clone of this repo and the `.phar` file was downloaded and run successfully the first time. The second run of `composer install` avoided downloading the `.phar` and, again, it executed successfully. :man_dancing:
This will impact the fetching and execution of `strauss.phar`.
```bash
rm -rf vendor/vendor-prefixed
composer install
ls vendor/vendor-prefixed/stellarwp/validation/src
```
-   [ ] Relevant …

Fix: Switch the check for strauss.phar for better compatibility

---

src/Framework/PaymentGateways/DonationSummary.php

Both functions getSummary() and getSummaryWithDonor() apply the same filter. As getSummaryWithDonor() calls getSummary(), the filter is applied twice. As a result, additional data is added twice.
Here I remove the filter for getSummaryWithDonor() , another solution is to use a different filter or add another parameter to the filter.
Resolves #

Fix: Prevent donation summary with donor from filtering twice

---

src/Framework/PaymentGateways/PaymentGateway.php

If subscription logic was added to a gateway directly (without a subscription module) - there was a fatal error from an exception being thrown for not having a `gatewayDashboardSubscriptionUrl()` method implemented.  This is something that should really be optional based on the gateway.  Therefore ,the logic for determining if the url exists checks if it's implemented by the child gateway class - otherwise return false and don't create a link. 
The subscription details page.
N/A
- Test a subscription using stripe and make sure the subscription link exists on the details page.
- Then test using test gateway and make sure there are no fatal errors & the subscription profile ID on the details page is just a string / not a link …

Fix: gateway api subscription dashboard link

---

assets/src/css/frontend/_mixins.scss
assets/src/css/frontend/forms.scss
assets/src/js/frontend/give-donations.js
includes/forms/template.php
src/Views/Form/Templates/Classic/resources/css/_personal-info.scss
src/Views/Form/Templates/Sequoia/assets/css/form.scss
src/Views/Form/Templates/Sequoia/assets/css/tributes.scss

This PR is necessary to resolve the major issue of https://github.com/impress-org/give-gift-aid/issues/168.
The current PR implements a new field in the Personal Info section that controls the visibility of the Company field whenever it's not required. Users will now be able to clearly see when the field is not required.
Company field on donation forms.
1. Make sure the Company field is optional on GiveWP Settings > Default Options
2. Open a donation form
3. See the radio list
4. Switch to Yes
5. The company field is shown
6. Change form settings or global settings to make the Company field required
7. Open the donation form
8. The radio list should not be visible but only the Company field
-   [] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` …

Feature: Add conditional to company name field

---

src/Views/Form/Templates/Classic/resources/css/_modal.scss
src/Views/Form/Templates/Classic/resources/css/_payment-details.scss
src/Views/Form/Templates/Classic/resources/css/form.scss

Resolves #6700 
This PR adds styles for the modals importing the legacy stylesheets into the classic template SCSS.
Modals on classic template
1. Go to a donation form using the classic template and have some content using an addon (Gift Aid, for instance)
2. Search for a link that opens the modal
3 . Clicking on that link, the modal must be shown with the content.

Fix: Style modals on classic template

---

src/Views/Form/Templates/Sequoia/assets/css/receipt.scss
src/Views/Form/Templates/Sequoia/views/receipt.php

Resolves #6692 
This PR adds dynamic classes to sections and rows on the multi-form receipt page so we can style them individually then it fixes margins between paragraphs in the Additional Information section.
Multi-form receipt page
1. Donate using an addon that includes additional information on the receipt page. Eg: Gift Aid, Tributes etc.
2. See the content in that section.

Fix: Style additional information section on multi-form receipt page

---

src/Views/Form/Templates/Classic/resources/js/form.js

Resolves #6707
This PR fixes the related issue by changing the way how we clone the children nodes from the `#give_purchase_form_wrap` in the `moveDefaultGatewayDataIntoActiveGatewaySection()` method. Now instead of selecting just `fieldset` nodes, we select all nodes, except the `.give-donation-submit` element.
But why does this fix the problem? Because now, we also include the `script` nodes that are necessary to load the Accept.js library required by the Authorize.Net gateway. 
As a note, this problem wasn't happening in situations where Authorize.Net isn't the default gateway because in these cases, the details are loaded through an AJAX call that already was properly loading everything.
Classic Template. 
1. Create a form using the classic template
2. Enable the Authorize.Net gateway …

Hotfix: make donations get finished when Authorize.Net is the default gateway in sites with more than one gateway enabled.

---

src/Views/Form/Templates/Sequoia/views/receipt.php

Resolves #6711 
I found that in the [receipt template](https://github.com/impress-org/givewp/blob/develop/src/Views/Form/Templates/Sequoia/views/receipt.php), in line 91, there is an issue between the operation and the operand types. It's trying to use the '+' operation on 2 strings. In older PHP versions (<= 7.0) this will work, in some v7 versions (>7.0, <8.0) it will throw a warning, but in newer versions (>= 8.0) this will fail. You can try this with a [PHP sandbox tools](https://onlinephp.io/). Therefore, to fix it it's enough to change the operation to concatenate strings from "+", to the PHP common of ".".
The receipt view when doing an offline donation while using PHP8+.
-   [ ] Relevant `@unreleased` tags included …

Fix: Unsupported operand types in PHP v8+ for receipt template 

---

includes/admin/tools/export/give-export-donations-exporter.php

Re: https://app.asana.com/0/0/1204069668576421/f
This PR patches a potential CSV Injection vulnerability by escaping (or 'neutralizing') formula expressions in cells. Cells starting with `=`, `+`, `-`, or `@` are formula expressions in spreadsheets, which may be executed is protections are disabled when opening the file.
- `Give_Export_Donations_CSV`
---
- https://app.asana.com/0/0/1204129686534550

Fix: Patch CSV injection in donation export

---

templates/shortcode-form-grid.php

This adds extra escaping to the form grid shortcode attribute rendering to prevent XSS.
The form grid shortcode
N/A
Make sure the form grid shortcode works as expected.
---
- https://app.asana.com/0/0/1204137775197143

Fix: add extra escaping to form grid shortcode attributes

---

includes/admin/tools/import/class-give-import-donations.php

This adds extra escaping and a nonce check during the donation import settings.
The GiveWP settings for `tools -> import -> import csv`.
N/A
Make sure importing donations works as expected.
---
- https://app.asana.com/0/0/1204137560913017

Fix: add escaping and nonce check to donation import settings

---

src/Framework/PaymentGateways/PaymentGateway.php

This adds support for using the `RespondToBrowser` command in the gateway api when using `createSubscription()`
The gateway api 
N/A
Would need to use a gateway that supports recurring and returns the `RespondToBrowser` during `createSubscription()`

Feature: handle `RespondToBrowser` command for subscriptions

---

give.php
package-lock.json
package.json
src/Framework/DesignSystem/Actions/RegisterDesignSystemStyles.php
src/Framework/DesignSystem/DesignSystemServiceProvider.php
webpack.mix.js

This PR integrates the [GiveWP Design System](https://www.npmjs.com/package/@givewp/design-system-foundation) by registering the script into WP as `givewp-design-system-foundation`. So whenever someone needs to load the design system, they just need to enqueue that handle!
I also got a little clever and store the package version when webpack runs. This version is then used when registering the style, so if the package is ever updated in the future, the version will automatically change and bust the cache. 🪄 
Otherwise, this is pretty simple!
Shouldn't affect any existing code!
Just add `wp_enqueue_style('givewp-design-system-foundation')` to some page (admin or front-end), and then check the JS console to make sure the CSS variables are loaded!
-   [x] Relevant `@unreleased` tags included …

Feature: add design system style registration

---

tests/ApiTestCase.php
tests/RestApiTestCase.php
tests/TestTraits/HasDefaultGiveWPUsers.php
tests/TestTraits/HasDefaultWordPressUsers.php

This Pull Request adds a new `RestApiTestCase` class. The class provides specific methods and helper functions to be used in API tests. This will make it easier and faster to write tests for the Give REST API.
To use the `RestApiTestCase` class, you just need to extend your test from it instead of the standard `TestCase` class. The `RestApiTestCase` class initializes the REST server, creates user accounts for API authentication, provides wrapper functions for creating and dispatching requests, and includes an assertion method for checking WP error responses.
The reason for extending a class instead of using a trait is to keep the codebase clean and avoid duplication of logic. If we were to use a trait, we would need to implement duplicate logic in the standard `TestCase` class and prefix …

Feature: REST API Test Case

---

assets/src/js/frontend/give-donations.js

Resolves #6729 
Conditional field visibility javascript tracks field change events by their field name. As we can see issue occurs with the amount field in the donation form because when the custom amount setting is disabled then, we use a hidden field to store the amount value and span the HTML tag to display the amount, which means the change event does not trigger. Donation form logic triggers a change event on for amount by classes. For this reason, the field does not display.
I trigger a change event on the amount hidden field to resolve the issue.
This pull request affects the donation form the front end and conditional field visibility with the FFM add-on.
- …

Fix: trigger change event on hidden amount field

---

src/PaymentGateways/Gateways/Stripe/Webhooks/Listeners/ChargeRefunded.php
src/PaymentGateways/Gateways/Stripe/Webhooks/Listeners/CheckoutSessionCompleted.php
src/PaymentGateways/Gateways/Stripe/Webhooks/Listeners/PaymentIntentPaymentFailed.php
src/PaymentGateways/Gateways/Stripe/Webhooks/Listeners/PaymentIntentSucceeded.php

Related: https://github.com/impress-org/givewp-next-gen/pull/141
This adds `give_stripe_processing_{stripe_event}` actions to our stripe webhook listeners.  This will specifically give the Next Gen Stripe gateway the opportunity and flexibility of modifying the listener's event processing logic for it's own use cases while not affecting the existing functionality.
Actions added:
- `give_stripe_processing_payment_intent_succeeded`
- `give_stripe_processing_payment_intent_failed`
- `give_stripe_processing_checkout_session_completed`
- `give_stripe_processing_charge_refunded`
Note: we are not using the `givewp` prefix for these because they are still considered legacy at the moment.
Technically the stripe webhook listeners, although they are just added actions so nothing should be affected …

Feature: add processing actions to stripe webhook listeners

---

includes/admin/import-functions.php
includes/misc-functions.php
src/LegacySubscriptions/includes/give-subscriptions-db.php
tests/includes/legacy/importer/tests-donations.php

Resolves #6753
As a replacement for the deprecated `get_page_by_title` function, this PRs adds our own version of that using `WP_Query`. 
Import donations tool

Fix: replace deprecated get page by title function

---

src/DonorDashboards/Tabs/Contracts/Route.php
src/DonorDashboards/resources/js/app/components/subscription-cancel-modal/index.js
src/DonorDashboards/resources/js/app/components/subscription-cancel-modal/utils/index.js

I recently discovered there is a lack of error handling in the donor dashboard.  This adds error handling to the endpoint request and the UI for cancelling a subscription.
The donor dashboard - cancel subscription functionality.
You will need something to go wrong with the gateway while cancelling to test this out.
---
- https://app.asana.com/0/0/1204309736724098

Fix: add error handling for canceling a subscription in donor dashboard

---

includes/gateways/stripe/includes/admin/admin-helpers.php
tests/Unit/PaymentGateways/Stripe/Filters/LegacyStripeFiltersTest.php

Related: https://github.com/impress-org/givewp-next-gen/pull/159
Currently all the stripe gateway id's are hardcoded into a list that gets checked for all things Stripe (like including stripe webhooks).  In Next Gen we need a way to add a new Stripe gateway without hardcoding the id in core.  This filter will allow us to extend this list.
The `give_stripe_supported_payment_methods()` function
N/A
- Make sure existing Stripe gateways load properly

Feature: add filter for `give_stripe_supported_payment_methods`

---

composer.json
composer.lock
src/Framework/Support/Facades/Str.php

Resolves #6772
This PR requires the `symphony/polyfill-mbstring` package, which resolves a PHP version compatibility issue related to `Str::reverse()`.
The GiveWP plugin should not pass the PHP Compatibility check for `7.0`.
---
- https://app.asana.com/0/0/1204442996207314

Fix: Add polyfill for the Mbstring extension

---

src/DonorDashboards/resources/js/app/components/subscription-cancel-modal/index.js

Resolves https://lw.slack.com/archives/C04SLRDD9CK/p1682958076271749
On the donor dashboard, I found that the subscription cancellation modal froze because of a javascript error.
This issue occurs because `CancelSubscriptionRoute` returns `void` while the javascript request handler expects a response in a specific format: `response?.data?.code.includes('error')`
As discussed with @jonwaldstein I made the `code` object key optional to fix the issue.

fix: prevent javascript error on subscription cancellation from donor dashboard

---

src/PaymentGateways/PayPalCommerce/ScriptLoader.php

Resolves #6790
Errors occurred when locale information being sent through Paypals SDK query parameters do not match the expected Paypal format. Per Paypals recommendation this PR removes the local parameter from being sent so that Paypal can automatically set this information.
Reference: https://developer.paypal.com/sdk/js/configuration/#link-queryparameters
Paypal Donations
---
- To see the specific tasks where the Asana app for GitHub is being used, see …

Fix: Remove locale from PayPal SDK query parameters

---

includes/gateways/stripe/includes/class-give-stripe-payment-intent.php
src/PaymentGateways/Gateways/Stripe/Traits/HandlePaymentIntentStatus.php

Resolves #6786
This pull request adds more user-friendly error messages for Stripe payments. When a user faces an error during the payment process, the new error messages provide more context about the issue, which will help them to take appropriate actions to resolve the issue.
Stripe Payments
- Create a form and setup Stripe as a payment option.
- Make a donation that would generally cause a user-facing error. For example, you can use a test card with no balance. The card number is 4000 0000 0000 9995.
- View new error messages.
-   [x] [Self …

Fix: Add user-friendly error messages for Stripe payments

---

webpack.mix.js

Resolves  #6808
Previously, an error occurred due to a missing payment-gateway.js file, which caused issues with the application's functionality. To resolve this problem, the payment-gateway.ts file has been added to the webpack configuration. Now, when the application is built using webpack, the necessary dependencies and modules from payment-gateway.ts are properly bundled, ensuring the application functions correctly.
This fix addresses the missing JS file error.
Settings > Payment Gateway
- Navigate to Donations -> Settings -> Payment Gateways
- Observe that no missing JS files are thrown.
-   [ ] Reviewed by the designer (if follows a …

Hotfix: Include payment-gateway.ts in Webpack

---

.github/workflows/generate-zip.yml
package.json

This tweaks the `generate-zip.yml` workflow so that it passes along some extra values to the `givewp-github-actions` zip workflow that enable versioned builds and Slack communication.
To support the versioned builds, a tweak to `package.json` is necessary so that we can read/write version number data in plugin files.
This should not impact anything beyond giving the `generate-zip.yml` more values to use.
Run the `Generate Zip` workflow and ensure it continues to build and upload a zip artifact to the workflow.
* https://github.com/impress-org/givewp-github-actions/pull/8

New: Support Slack-bot-based zip packaging requests

---

src/Promotions/InPluginUpsells/resources/js/payment-gateway.ts

This pull request resolves the issue of console warnings related to the product recommendation notice on the Settings page. The warning message "Uncaught TypeError: Failed to execute 'insertAdjacentElement' on 'Element': parameter 2 is not of type 'Element'" was appearing because a method was being applied to an element that had been removed from the DOM (product recommendation notice). To fix this, the method and variables targeting the elements necessary for managing the notices have been encapsulated inside an if statement.
Settings page
- Visit the Payment Gateway tab in the Settings page. If the product notice is displayed close it out.
- Check the console for no warnings.
-   [ ] Relevant `@unreleased` tags included …

Fix: Improve error handling for fee recovery product recommendation on Settings page

---

assets/src/js/frontend/paypal-commerce/SmartButtons.js

Resolves #6804
The problem lies in the fact that the function was trying to display errors using the Give.form.fn interface. When looking at Give.form.fn.addErrors, we see that it first looks for an element of id="give-purchase-submit" (see full query) in order to inject the error messages before that element in the DOM. On classic forms, no such element exists to match this query. Errors never get displayed.
Since the handler mentioned in issued #6804 is part of the Smart Buttons frontend code, we can use the DonationForm interface to add the buttons - that is much more appropriate.
Classic form front-end, displaying errors on form.
- Navigate to classic form with committed changes of SmartButtons.js
- Enter incomplete user information (first name, e-mail), or an invalid email
- Click …

Fix: Display errors for PayPal Smart Buttons

---

src/Donations/Endpoints/DonationUpdate.php
src/Donations/Endpoints/DonationUpdateAttributes/CommentAttribute.php
src/Donations/ViewModels/DonationDetailsViewModel.php
tests/Unit/Donations/Endpoints/TestDonationUpdate.php

Blocked by https://github.com/impress-org/givewp/pull/6765
This pull request introduces a new `comment` attribute to the Donation Update endpoint.

Feature: admin donation details api comment field

---

.github/workflows/release.yml

Resolves #
The `php-actions/composer` action is a wrapper around the `composer`, with the default command being `composer install`.
Further, it default to no interaction, no progress (output).
By default it does install dev dependencies, but we disable that by passing `dev: no`.

Chore: Remove redundent composer install

---

give.php
readme.txt
src/Form/LegacyConsumer/Actions/DetermineVisibilityForRequest.php

Resolves #6833
This PR solves the problem by checking if the field used in the condition is present in the form submitted data. If not, we return `false` because if the current field depends on this missing field, it means that the current field can't be visible. If we do not do that, the API will try to access this missing field and throw a fatal error exactly because it is not present in the request.
Form Field Manager Addon
- Create a form with the following FFM fields: a checkbox OR a radio field with ONLY one option;
- Another field that will show conditionally based on the above;
- Make a donation with the checkbox or radio option empty;
- The donation should be submitted successfully. 
-   [ ] Relevant `@unreleased` …

Hotfix: make donation get submitted even when a radio or checkbox with conditional visibility based on another field is present

---

blocks/donation-form/index.js

This PR updates the donation form block's title to include the suffix (v2)
Donation form block
- add legacy donation form block
- Verify title is updated and block works as expected

Refactor: Update legacy donation form block title with (v2) suffix

---

includes/ajax-functions.php

Related: https://github.com/impress-org/givewp-next-gen/pull/204
This adds `state_label` and `states` to the `give_get_states()` ajax function for use in the new BillingAddress block from [this](https://github.com/impress-org/givewp-next-gen/pull/204) PR.
Technically the `give_get_states()` but is only adding new keys, not modifying existing functionality.
N/A
- `state_label` should return the state label based on the country
- `states` should return an array of states based on the country
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-r …

Feature: add state_label and states keys to give_get_states ajax function

---

assets/src/css/admin/summer-sales-banner.scss
src/Promotions/InPluginUpsells/SummerSalesBanner.php
src/Promotions/InPluginUpsells/resources/views/summer-sales-banner.php
src/Promotions/ServiceProvider.php
webpack.mix.js

This PR adds a summer sales banner to the plugin page. There are two different banners designs which can be viewed [here](https://www.figma.com/file/QJRUKnl10E8eFsvSaW5cI4/Stellar%3A-Sale-'23?node-id=1482%3A429&mode=dev). 
The banner populated is determined by the active licenses the user currently has. The licenses being checked for are the add ons listed below : 
- Recurring donations
- Form field manager
-  Fee recovery
-  Manual donations
-  P2P
- The banners has a start date of 07-24-23 and an expiration date of 07-31-23.
- When closed with the icon at the top right. The banner remains closed.
- In mobile view the secondary message is removed from display and the abstract pattern design is moved downward.
The Give links will not be active until day of display.
Plugins Page
Will …

Feature: Add summer sales banner to plugin page

---

blocks/donation-form-grid/edit/inspector.js
blocks/donation-form-grid/edit/style.scss
blocks/donor-wall/edit/inspector.js
blocks/donor-wall/edit/style.scss

Resolves #6843
This PR adds new wrapping CSS class names in order to increase specificity when visually hiding the label of the `<FormTokenField />` component.
- Donor Wall block
- Donation Form Grid block
- Add a Donor Wall block and view the Filter setting (under Wall Settings)
- Add a Donation Form Grid block and view the Filter setting (under Grid Settings)
- Add a Query Loop block and add a new filter (taxonomies, Authors, or Keyword)
The label of the form token input should be hidden only for the Donor Wall and the Donation Form Grid settings.
---
- https://app.asana.com/0/0/1204971508292132

Fix: Increase specificity when hiding the Form Token Field label

---

src/Framework/PaymentGateways/Traits/HandleHttpResponses.php

This adds check for `application/json` in the headers accept in handleHttpResponses.
In v3 forms we will explicitly set the accept header as `application/json` in order to tell the server we want it to respond as json.
This is being used in the gateway api and the v3 forms donation related controllers.
N/A
This does not affect any existing functionality.  A related PR that used form-data will rely on this so can be tested alongside.

Feature: add check for application/json in headers accept

---

includes/shortcodes.php
src/DonationForms/V2/Endpoints/ListDonationForms.php
tests/Unit/DonationForms/Endpoints/TestListDonationForms.php

This PR implements the `give_redirect_form_id()` function in each of the relevant `add_shortcode` callback render functions.
Additionally, this covers the Donation Form (v2) block and the Donation Form Grid, which each use the `give_form_shortcode()` function for server-side rendering. 
- `[give_form]`
- `[give_goal]`
- `[give_totals]`
- `[give_form_grid]`
Note: The "Donation Form (v2)" block uses the `give_form` shortcode under the hood.
- Add a v2 form shortcode to a page
- Redirect that v2 form to a v3 form
- View the rendered shortcode - should show the v3 form

Feature: Implement shortcode, block redirects

---

src/Framework/FieldsAPI/Concerns/NameCollision.php
src/Framework/FieldsAPI/Exceptions/NameCollisionException.php

Related: https://github.com/impress-org/givewp-next-gen/pull/243
This adds a `$nodeNameCollision` property on `NameCollisionException` for flexibility in throwing exception messages.
- The `NameCollisionException` exception
```
try {
$form->schema();
} catch (NameCollisionException $e) {
return rest_ensure_response(
new WP_Error(
400,
sprintf(
__("A field name with meta key '%s' already exists. Please try a new one.", 'give'),
$e->getNodeNameCollision()
)
)
);
}
```
This would have to be done programatically.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github …

Feature: add `$nodeNameCollision` property on `NameCollisionException`

---

includes/admin/tools/views/html-admin-page-system-info.php

Resolves #6869
This PR addresses a broken link which appears in System Info when viewed from a site with less than 64MB of memory available to WordPress.
It updates the link target to the most current and most relevant URL which replaces the documentation that previously existed in the WordPress Codex. I chose this URL to help users navigate to the needed information, as any user following the "This page was moved to..." link on the deprecated Codex article will end up in a Documentation area that does not address their needs. Users will then be forced to search for relevant information.
System Info 
1. From a WordPress install with WP memory less than 64MB, go to Donations -> Tools -> System Info
2. Scroll down to WP Memory Limit
3. Click "Increasing memory allocated to PHP"
4. View the …

fix: update broken link to WP codex article on PHP memory

---

src/DonationForms/resources/styles/components/_amount.scss

If the amount block is moved into a new section, that sections background color is seen through the custom amount input which makes its background inconsistent. This PR adds a white background to the input.
- Move the amount section down a section and view design on classic template. The custom amount input will now not contain the background of the section but only display var(--givewp-shades-white)

Fix: Use solid background color for custom amount input

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/Edit.tsx

Updates the Last name text control placeholder value to use the correct default value from  'First name' to 'Last name'.
- Add a v3 form 
- Verify the correct placeholder value for the Last name text control
- 

Fix: Update Last name placeholder

---

give.php
src/FormMigration/functions.php
tests/Unit/FormMigration/FunctionsTest.php

This PR automatically deactivates the Visual Donation Form Builder feature plugin when GiveWP v3 is installed and shows an admin notice with an explanation.
Note: Two other notices are shown which are not controlled by the core plugin and thus cannot be removed by this change.
Renames the `FormMigration` functions to avoid a fatal error conflict with the autoloaded functions in the feature plugin.
Note: These renamed functions are not yet in use, but are included in https://github.com/impress-org/givewp/pull/6832.
- Activate the `Give - Donation Plugin` plugin.
- Activate the `Give - Visual Donation Form Builder` plugin.
- Checkout the `feature/deactivate-feature-plugin` branch.
- Refresh the page.

Feature: Auto-deactivate the feature plugin

---

src/DonationForms/DataTransferObjects/DonateFormRouteData.php
src/PaymentGateways/Actions/GetGatewayDataFromRequest.php

The gateway data request was specifically checking for certain content types and json.  This was problematic with our new use of multipart/form-data.  Now this request supports all native content types by simply checking the super global first, then json.
This also fixes a bug related to forms being rendered outside of an iframe and their respected redirects.
- v3 gateways that use the `$gatewayData` will now work properly
N/A
- The easiest way to test this is make sure Stripe Payment Element is working properly.
-   [ ] [Self …

Fix: `$gatewayData` request supports all native content types

---

src/FormBuilder/resources/js/form-builder/src/supports/field-settings/FieldSettingsHOC.tsx

This PR fixes a bug that changes the meta key (and tag email) of a custom field when we update the form, even if we not changing anything on the custom field.
For example, if we create a custom field called "Favorite Color", the `meta_donor_favorite_color` displayed on the screen is saved on DB as `favorite_color` the first time. 
After that, when we update the form, the `favorite_color_1` is used instead of the `favorite_color` meta key
But if we use the `meta_donor_favorite_color` as an email tag, the first value set on the `favorite_color` meta key will always be displayed, and the updates stored on `favorite_color_1` will never be displayed on the emails.
For example, if I set my favorite color as BLACK on donation 1, I'll get an email with BLACK in the body message, but if I set my …

Fix: keep the same meta key and email tag for custom fields after updating the form

---

src/DonationForms/resources/app/utilities/convertValuesToFormData.ts

When we pass values to the backend using a `FormData` structure, the ability to send arrays/objects is lost because they are converted to strings. This pull request resolves that issue by preserving arrays/objects in their original form when they are sent to the backend.
_before_
_after_
- Add a MultiSelect field from FFM to your form
- Open that form on the client side
- Select one or two options in that MultiSelect dropdown
- When you submit the form, you must be able to see the selected options in the receipt page.
```php
add_action('givewp_donation_form_schema', static function (DonationForm $form) {
$field = MultiSelect::make('custom_multiselect')
->fieldType('dropdown')
->required(true)
->showInAdmin(true)
->showInReceipt(true)
->label('Custom MultiSelect')
->rules(new …
```

Fix: form data converter

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Actions/EnqueueStripeFormBuilderScripts.php

This PR enforces a trailing slash on `GIVE_PLUGIN_DIR` instead of adding a leading slash to the relative file path.

Fix: Update asset file path

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/terms-and-conditions/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/terms-and-conditions/StyledPopover.tsx

I noticed the StyledPopover component was not working as expected. It did not open and contained an error. To fix the error we moved the useEffect hook above the conditional check. I also noticed the original Modal was still in the block file. That has been removed as well.
StyledPopover component / terms and conditions block
Error:
With PR fix:
https://github.com/impress-org/givewp/assets/75056371/f29367cf-f54a-4789-a020-432cc551e8ef
- Add terms and conditions block;
- Open agreement text modal;
---
- https://app.asana.com/0/0/1205399260808640

Fix: Address StyledPopover component error

---

src/DonationForms/FormDesigns/ClassicFormDesign/css/_inputs.scss
src/DonationForms/resources/app/utilities/ConvertFieldAPIRulesToJoi.ts
src/DonationForms/resources/app/utilities/convertValuesToFormData.ts
src/DonationForms/resources/propTypes.ts
src/DonationForms/resources/registrars/templates/fields/File.tsx
src/DonationForms/resources/styles/elements/_fields.scss
src/Framework/FieldsAPI/File.php
src/Framework/ValidationRules/Rules/File.php

This pull request modifies the file upload field to address the issue of it being incorrectly marked as "required" even when a file is selected. It also introduces the "allowed" prop for the file input, which enables filtering of selectable files and applying styles to the file upload input.

Fix: file upload field

---

blocks/donation-form-grid/class-give-donation-form-grid-block.php
blocks/donation-form/class-give-donation-form-block.php
blocks/donor-wall/class-give-donor-wall.php
includes/donors/class-give-donor-wall.php
includes/shortcodes.php
src/FormMigration/Commands/TransferCommand.php
src/FormMigration/Controllers/TransferController.php
src/FormMigration/DataTransferObjects/TransferOptions.php
src/FormMigration/functions.php
src/MultiFormGoals/MultiFormGoal/Shortcode.php
src/MultiFormGoals/ProgressBar/Block.php
tests/Unit/FormMigration/FunctionsTest.php

This PR "redirects" v2 form IDs to the respective transferred v3 form ID for shortcode and block attributes.
- Updates form ID(s) in block attributes in the render callback.
- Updates form ID(s) in shortcode attributes in the shortcode callback.
Additionally, updates the transfer options to reflect the new workflow.
- Create a v2 form.
- Add the v2 form to a page via a shortcode.
- Migrate the form to a v3 form.
- Transfer the v2 form to the v3 form.
- View the page with the shortcode.

Chore: Redirect transferred form IDs in shortcodes, blocks

---

src/Framework/FieldsAPI/Actions/CreateValidatorFromForm.php
src/Framework/FieldsAPI/Actions/CreateValidatorFromFormFields.php
src/Framework/FieldsAPI/Actions/UpdateValidationRulesWithOptionalAsDefault.php
tests/Unit/Framework/FieldsAPI/Actions/UpdateValidationRulesWithOptionalAsDefaultTest.php

This updates all the field validation rules used in our donation form with the "optional" rule as the default rule.  This rule will get prepended only if the field is not required.
Form field validation rules
N/A
Currently would have to test this programmatically, make sure this does not validate if empty.
```
add_action('givewp_donation_form_schema', static function (DonationForm $form) {
$field = \Give\Framework\FieldsAPI\Email::make('custom_email')
->showInAdmin()
->showInReceipt()
->label('Custom Email')
->rules('email');
$form->insertAfter('email', $field);
});
```
-   [ ] [Self …

Feature: update form field validation rules with optional as default 

---

src/DonationForms/Repositories/DonationFormRepository.php
src/FormBuilder/ViewModels/FormBuilderViewModel.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Actions/AddStripeAttributesToNewForms.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Actions/EnqueueStripeFormBuilderScripts.php

This adds a fallback empty array when getting the give option `gateways_v3` to avoid type errors when return false or empty.  
Resolves https://github.com/impress-org/givewp/pull/6923/files#r1321690679
The form builder when the option is null or not set yet.
N/A
Remove the `gateway_v3` option from give settings and make sure you can add a new v3 form.

Fix: add fallback array to option gateways_v3

---

src/FormBuilder/resources/js/form-builder/src/components/sidebar/Secondary.tsx

This PR includes the conditional check needed on the frontend to ensure that the FFM promo panel will only display when FFM is not active.
https://github.com/impress-org/givewp/assets/75056371/6f7926e8-34fb-41f1-ba25-5beebe3583ce
- Visit Formbuilder - select a block
- open primary block list - view FFM promo panel
- Install and activate FFM
- Visit Formbuilder - verify the promo no longer displays

Fix: only display promo panel when FFM is not active

---

src/Promotions/WelcomeBanner/resources/js/app/components/Link/styles.scss
src/Promotions/WelcomeBanner/resources/js/app/components/Sections/RightContentSection.tsx

This PR includes the design mode video into our assets for display on the 3.0 welcome banner. We have also added hover states to the links on the banner.
3.0 welcome banner
https://github.com/impress-org/givewp/assets/75056371/392e0466-84ec-4ecc-a8ae-ce235e0d39f4
If you have previously dismissed the banner, it will reappear by deleting "givewp_welcome_banner_dismiss" from the options table in the database.
- Verify the new design mode video displays.
- Hover over the links to verify hover effects.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-review …

Fix: add design mode video and hover states to the welcome banner

---

src/DonationForms/resources/registrars/templates/fields/MultiSelect.tsx
src/DonationForms/resources/styles/elements/_fields.scss

This PR introduces two main changes to the multi-select field template. The issue with `defaultValue` not being applied when using the checkbox template has been fixed by utilizing the field value from `useWatch`. Additionally, the checkboxes now have the styles applied, which are shared with the radio buttons list.

Refactor: Update multi-select field template with useWatch hook

---

src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php

This simply hides the v3 beta menu item. This will no longer be a way to add forms.
The GiveWP submenu and, in a way, how the form builder page is registered.
Just make sure that the "add v3 form" menu item does not show up, but opening up the form builder via the new button (or by editing an existing v3 form) still works.

Feature: hide beta menu item

---

src/FormBuilder/resources/js/form-builder/src/blocks/elements/paragraph/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/elements/paragraph/settings.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss

Resolves #6930
This PR replaces the pseudo outline with the native outline property (coupled with outline-offset) to restore focusability of the rich text content editable.
Additionally, a new inspector control was added for a fallback method to edit the content attribute.
---
- https://app.asana.com/0/0/1205338142988520
- https://app.asana.com/0/0/1205470381066812

Fix: Restore focusability of paragraph block/element

---

src/DonationForms/resources/registrars/templates/elements/Paragraph.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/elements/paragraph/settings.tsx

Blocked/requires: https://github.com/impress-org/givewp/pull/6931
This PR updates the Paragraph template to use the Markup component from Interweave to safely render html, within the Paragraph block. It also adds a short description to the block.
Paragraph block/template
https://github.com/impress-org/givewp/assets/75056371/60b32469-980e-4bb9-91d1-61817b2ea468
- Add a paragraph block 
- Format the text
- View in design mode for formatted changes
- View on page for formatted changes
---
- https://app.asana.com/0/0/1205483145140328

Fix: paragraph block safely renders html

---

includes/gateways/functions.php
src/DonationForms/Repositories/DonationFormRepository.php
src/PaymentGateways/Migrations/CopyV2GatewaysSettingsToV3.php

This PR fix an issue where a migration was updating data when they were already saved.
During the installation of GiveWP, the options `gateways_v3` and `default_gateway_v3` are saved. However, a migration process occurred that incorrectly updated these options. In the future, this migration will only run if the options have not been saved yet.
Additionally, recently added types have been removed from legacy functions.
---
- To see the specific tasks where …

Fix: Change the migration to update gateways settings only when data doesn't exist.

---

src/DonationForms/V2/resources/components/Onboarding/Dialogs/FeatureNoticeDialog.tsx
src/DonationForms/V2/resources/components/Onboarding/style.module.scss
src/Views/Components/AdminUI/ModalDialog/style.scss

This PR replaces the "read more" link with the actual value. Additionally, it wraps the text in a paragraph tag to allow for the application of margins. Previously, the text would collapse into the button when there were no addons or gateways to list.

Fix: set read more link and wrap text in a p tag on Feature Notice modal

---

src/DonationForms/Properties/FormSettings.php
tests/Unit/DonationForms/Properties/FormSettingsTest.php

This PR escapes the nested array properties for `FormSettings::$emailTemplateOptions` when converting the form settings to JSON.
1. Create a v2 form
1. Migrate the form to v3
1. Try to load design mode

Fix: Escape double quotes in emailTemplateOptions

---

src/FormBuilder/resources/js/form-builder/src/settings/form-summary/page-slug.js

This fixes the page slug setting in the form builder to properly clean the permalink before updating the value. 
The page slug settings in the form builder
N/A
- Create a new or open an existing form
- Go to the page slug setting and type in something with spaces like `My Awesome Donation Form!`
- Save the form and make sure the slug is properly adjusted like `my-awesome-donation-form`

Fix: form builder page slug setting

---

src/FormBuilder/resources/js/form-builder/src/supports/field-settings/FieldSettingsHOC.tsx
src/FormBuilder/resources/js/form-builder/src/supports/field-settings/updateBlockTypes.ts

This PR fixes the issue of duplicate meta keys when duplicating a block. We introduced a `metaUUID` attribute to store the current `clientId` value. This allows us to identify when a block is duplicated and generate a new meta key for it.
https://github.com/impress-org/givewp/assets/3921017/aab848b8-bab8-452e-8b61-8d76b96f2ccc
- Add a custom field block
- Change its label
- Check the current meta key under the Advanced panel
- Duplicate that block
- Confirm the new block has an unique meta key
- Add a new custom field block
- Give it the same label from the previous ones
- Confirm it also has an unique meta key
-   [ ] Reviewed by the …

Fix: prevent meta key conflict on block duplication

---

src/PaymentGateways/Gateways/Stripe/LegacyStripeAdapter.php

This updates the Stripe Payment Element gateway to use the `gateway_v3` option when deciding if it needs to load the existing stripe webhooks.
Stripe Payment Element - webhooks
N/A
- Connect to Stripe (including webhook) and enable Stripe Elements on the site/form.
- Create v3 form
- Create donation.
- The webhook should respond correctly and mark the donation as complete
---
- To see the specific tasks where the Asana app for GitHub is being used, see …

Fix: update gateways option key in Stripe adapter for Payment Element Gateway

---

src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss

This PR prevents the Editor Skeleton Header component from disappearing.
The underlying issue seems to be that the Editor Skeleton Body has a `min-height` of `100vh`, which was causing the Header to be hidden under certain circumstances.
This remove the `min-height` CSS property from the Editor Skeleton Body.
1. Set terms and conditions to show in modal.
1. Go to Design tab and click the Show terms link.
1. When the terms and conditions modal opens, the top bar of the builder **should not** disappear.
---
- https://app.asana.com/0/0/1205502083833595
- https://app.asana.com/0/0/1205524417076814

Fix: Prevent header from disapearing

---

blocks/donation-form-grid/class-give-donation-form-grid-block.php
blocks/donor-wall/class-give-donor-wall.php
includes/shortcodes.php
src/MultiFormGoals/MultiFormGoal/Shortcode.php
src/MultiFormGoals/ProgressBar/Block.php

This PR updates every use of `array_walk` when redirecting Form IDs to avoid fatal errors.
In some cases the `array_walk` was being used incorrectly because arrays were being imploded as comma separated strings.
Using PHP 8+ add the Form Grid block to a page
---
- https://app.asana.com/0/0/1205502083833544
- https://app.asana.com/0/0/1205534412601309

fix: Prevent fatal errors when redirecting form IDs

---

src/FormBuilder/resources/js/form-builder/src/blocks/section/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/section/settings.tsx
src/FormBuilder/resources/js/form-builder/src/common/registerBlocks.ts
src/FormBuilder/resources/js/form-builder/src/components/sidebar/Secondary.tsx
src/FormBuilder/resources/js/form-builder/src/containers/BlockEditorContainer.tsx

This PR enables field and element blocks to be inserted between sections - in which case the block will be wrapped in a new section. This supports the quick inserter, drag-and-drop, and moving blocks.
The `dispatchFormBlocks` callback now modifies block data to enforce the `form > section > field/element` hierarchy.
Insert blocks all over the place - no restrictions :sunglasses:
---
- https://app.asana.com/0/0/1203980971550726
- https://app.asana.com/0/0/1205550233964873

Refactor: Allow blocks to move freely about the form builder

---

includes/payments/class-give-sequential-donation-number.php

This pull request addresses a race condition issue occurring in the `testCreateShouldInsertDonation` unit test. The issue originated when creating a new donation. The creation process triggers a method related to sequential order id (`Give_Sequential_Donation_Number->__save_donation_title()`). This method used the `wp_update_post` function to update the `post_title` and `post_name` fields of the donation, which had the side effect of altering the `post_modified` column in the original donation post. This unintended change led to mismatches during unit testing.
- Replaced the `wp_update_post` function with `DB::update` in the `Give_Sequential_Donation_Number->__save_donation_title()` method.
- Manually cleared the WordPress cache for the donation, ensuring other parts of the code recognize …

Fix: correct race condition when unit testing donations

---

src/FormMigration/Steps/DonationOptions.php

This PR explicitly sets the `customAmount` setting during the form migration. Previously only `customAmountMin` and `customAmountMax` were being set - with `customAmount` defaulting to enabled.
- Create a v2 form with Custom Amount disabled.
- Migrate the form.
- Custom Amount should be disabled.
---
- https://app.asana.com/0/0/1205502083833541
- https://app.asana.com/0/0/1205557954247356

Fix: Explicitly set customAmount setting during form migration

---

src/FormBuilder/resources/js/form-builder/src/components/canvas/DesignPreview.tsx
src/FormBuilder/resources/js/form-builder/src/components/canvas/DesignPreviewLoading/index.scss
src/FormBuilder/resources/js/form-builder/src/components/canvas/DesignPreviewLoading/index.tsx
src/FormBuilder/resources/js/form-builder/src/components/canvas/DesignPreviewLoading/placeholders/Classic.tsx
src/FormBuilder/resources/js/form-builder/src/components/canvas/DesignPreviewLoading/placeholders/MultiStep.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_root.scss

This PR adds a loading state placeholder for multi-step and classic templates. 
Design Mode
1. Go to edit form page and enter design mode
2. Make changes to form like switch template, etc. 
---
- https://app.asana.com/0/0/1205367015152177

Add loading states to Design Mode

---

src/DonationForms/resources/registrars/templates/fields/Gateways.tsx

This PR implements a simple change that only renders (on the JS side) the gateway fields of a gateway when it gets selected by the user. This approach improves performance and the initial form load.
After these changes, I did test donations without problems using the following gateways:
- Stripe Element
- PayPal Donations
- PayPal Standard
- Square Credit Card
- Authorize Credit Card
- Authorize eCheck
All compatible gateways with v3 forms.
1. Active all gateways compatible with v3 forms;
2. Make sure the Test Donation is the default gateway;
3. Create test donations using all gateways and make sure everything is working as expected.
-   [ …

Refactor: render gateway fields only when it's active

---

give.php
readme.txt

This PR addresses an error in the installation process of GiveWP on multisite setups. Previously, only the main site was installed, resulting in fatal errors on existing subsites.
Upon investigating the codebase, it was discovered that the installation method for GiveWP had a conditional check for `is_multisite()` and a `$network_wide` parameter. However, this parameter was never set to `true`, causing improper installation on WP multisite.
In this PR, we enable the parameter when the plugin is activated for the first time, ensuring proper installation of GiveWP on all existing subsites.
GiveWP install process
1. Fresh WordPress install with Multiste enabled
2. Create one subsite at My Sites > Network Admin > Add New
3. Navigate to My Sites > Network Admin > Plugins, install GiveWP, and …

Fix: correct install routine when activating in a WordPress multisite.

---

src/FormBuilder/resources/js/form-builder/src/containers/BlockEditorInterfaceSkeletonContainer.tsx
src/FormBuilder/resources/js/form-builder/src/containers/HeaderContainer.tsx

This PR adds logic to display a correct snackbar message when saving the form. On form publish it will show "Form published", and on form update, it will show "Form updated" notice.
Form builder snackbar notice message
1. create form
2. update the form
3. publish the form
4. edit form and hit update
---
- https://app.asana.com/0/0/1205606769216054

Feature: Show correct notice message on post publish/update

---

give.php
includes/admin/misc-functions.php
includes/admin/settings/class-settings-email.php
includes/gateways/stripe/includes/admin/admin-actions.php
readme.txt

This adds nonces to old sendwp functions.  It also removes an unused stripe disconnect function.
Make sure sendwp buttons and stripe disconnect buttons work properly.

Fix: add nonces to sendwp functions

---

src/DonationForms/ServiceProvider.php

This PR resolves the error which was introduced when we added the new post status `upgraded`. The problem with custom statuses in WP is that they have to be registered in order to function properly. The error is resolved by registering the new post status. 
1. Create form
2. Upgrade form
3. Go back to the original form
---
- https://app.asana.com/0/0/1205629954321417

Fix: post status error

---

src/FormMigration/Controllers/TransferController.php
src/FormMigration/DataTransferObjects/FormMigrationPayload.php

This PR sets the form status of new forms to be `draft` when first migrated and `publish` once transferred.
1. Migrate a form
2. New form should be draft
3. Transfer the form
4. Form should be publish
---
- https://app.asana.com/0/0/1205635546000698

Fix: Migrated forms now have a draft status until transferred

---

src/DonationForms/Actions/ConvertDonationFormBlocksToFieldsApi.php
src/DonationForms/resources/propTypes.ts
src/DonationForms/resources/registrars/templates/fields/Text.tsx
src/DonationForms/resources/registrars/templates/fields/TextArea.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/text/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/text/settings.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_blocks.scss
src/Framework/FieldsAPI/Text.php
src/Framework/FieldsAPI/Textarea.php
tests/Unit/DonationForms/Actions/TestConvertDonationFormBlocksToFieldsApi.php
tests/Unit/DonationForms/Repositories/TestDonationFormRepository.php

In the `FieldsAPI`, we had a `Textarea` field and a corresponding template, but they were unused. This pull request adds the `rows` attribute to the field and updates the template to include this attribute in the `textarea` tag. Additionally, support for field description has been added (likewise for `Text` field and template), carrying over from v2 forms.
Textarea and Text fields and templates
```php
add_action('_givewp_donation_form_schema', static function (DonationForm $form) {
$field = Text::make('custom_text')
->label('Custom Text')
->placeholder('Write something here')
->defaultValue('This is the default content');
$form->insertAfter('email');
​
$field = Textarea::make('custom_textarea')
->label('Custom Textarea')
->placeholder('Write something here')
->defaultValue('This is the …
```

Refactor: update Text/Textarea field and template

---

includes/admin/settings/class-settings-gateways.php

I found that we recently implemented a new feature in GiveWP 3.0.0: https://github.com/impress-org/givewp/pull/6923, which caused a side effect. Payment gateway like Razorpay which registers will legacy payment gateway API, is not displaying in the list. This means plugin users can not toggle legacy payment gateways. This pull request resolves this issue and includes legacy payment gateways under `Enabled Gateways > Option-Based Form Editor`.
This pull request affects the `Enabled Gateways` setting page display.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/git …

Fix: display legacy payment gateway with v2 donation forms

---

src/FormMigration/Steps/FormTitle.php

This PR removes the suffix from the migrated form title.

Refactor: Remove migrated form title suffix

---

src/FormBuilder/resources/js/form-builder/src/blocks/section/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/section/EmptyBlockInserter.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/section/styles.scss
src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss

This PR resolves two problems:
1. There was no way to drag-n-drop a block onto an empty section. Erm. 😬
2. Empty sections were boring and provided no guidance to the user.
This adds a clickable area that the user can also drag blocks into. Check it the video below!
Sections that have no child blocks
https://www.loom.com/share/712bb84378544f35ad5f81e01d97a77a?sid=04c3f4fa-eff8-4401-9785-719e8088e9a1
---
- https://app.asana.com/0/0/1205681939046621

Feature: Add a starter for new or empty sections

---

src/FormBuilder/resources/js/form-builder/src/blocks/elements/paragraph/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/elements/paragraph/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/billing-address/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/company/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/email/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/login/index.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/payment-gateways/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/settings/index.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/terms-and-conditions/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/text/settings.tsx

This replaces all `'custom-block-editor'` text domains with `'give'`
text domains in blocks
N/A
Make sure blocks work

Refactor: replace custom block editor text domain with give

---

give.php
includes/gateways/stripe/includes/give-stripe-helpers.php
includes/misc-functions.php
readme.txt
src/PaymentGateways/Gateways/Stripe/BECSGateway.php
src/PaymentGateways/Gateways/Stripe/SEPAGateway.php

Resolves #7015
This PR prevents the donations from failing making sure that the `give_get_ip()` function will return only a single IP by default. 
So, even if the `$_SERVER['HTTP_X_FORWARDED_FOR']` returns more than one IP split by commas, it will get the first one related to the client and ignore the other ones related to the proxy services.
For reference, check out this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax
This PR also adds new `$single` and `$header_type` params to the `'give_get_ip'` filter
Sites that use proxy services like Cloudflare and gateways that require the original IP address.
1. Setup Cloudflare and Stripe + Plaid in a test site
2. Try to do a test donation and check it will work as expected
3. The test donation should NOT fail
- …

Hot Fix: prevent failed donations in sites that use proxy services like Cloudflare and gateways that require the original IP address

---

src/FormBuilder/resources/js/form-builder/src/App.tsx

This PR adds a workaround for the "stuck" draggable cursor when adding blocks to the form.
In the WordPress Block Editor this doesn't seem to be an issue because the Inserter sidebar is closed on block drop.
Looking at the Gutenberg code base the `draggable` component uses a body class to style the cursor when dragging a block. This should be reset on "cleanup", but does not seem to be working.
See https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/draggable/index.tsx#L230
Drag and drop a new block/field into the form.
---
- https://app.asana.com/0/0/1205681679114246

Fix: Workaround to reset the draggable cursor

---

src/Donors/resources/components/DonorsListTable.tsx
src/Donors/resources/components/DonorsRowActions.tsx

Resolves https://feedback.givewp.com/bug-reports/p/donors-list-table-should-account-for-sub-directory-installs
This PR updates the URL of the Edit Row Action to use the localize `admin_url()` to build the URL.
This is similar to #6488, but addresses the Donor List Table.
On site with a sub-directory install of WordPress the donor edit link results in a 404 Not Found error.
The donor edit link does not account for the sub-directory in the generated URL.
The workaround is to use the legacy view.

Fix: Donor List edit link now supports sub-directory installs

---

src/FormBuilder/resources/js/form-builder/src/containers/HeaderContainer.tsx

This PR resolves the issue with the notice message on post publish/update. 
Form builder snackbar notice message
1. create form
2. update the form
3. publish the form
4. edit form and hit update
5. save draft
---
- https://app.asana.com/0/0/1205606769216054

Fix: notice message on post publish/update

---

includes/gateways/stripe/includes/admin/admin-helpers.php
includes/gateways/stripe/includes/filters.php

If you enable Stripe gateway for V3 forms and disable it for v2 forms, then try to make donations using legacy forms/templates, you will notice a few strange behaviors that prevent the donations from getting completed. This PR fixes this bug.
Legacy Forms - V2
https://www.loom.com/share/e59231ccf187498da75048cd57751cb9
To replicate the bug, you need to follow these steps:
1. In the `Option-Based Form Editor` tab on the gateway settings, disable all Stripe gateways.
2. In the `Visual Form Builder` tab on the gateway settings, enable the Stripe - Payment Element gateway.
3. Try to make a donation with a legacy form using all 3 templates, you'll see that all of them throw exceptions in the console log and the Classic and the Multi-Steps templates do not let you finish the donation.
To test …

Fix: errors on the legacy forms/templates when Strip is enabled for v3 forms but not for v2 forms

---

src/FormMigration/Steps/FormMeta.php

While fixing migration bugs, I noticed that the serialized form meta data was being re-serialized during migration, causing fatal errors due to changes in the data structure.
Initially, I considered unserializing the data before inserting it into the database and then serializing it again. However, after discussing it, we decided to completely revamp the way we migrate form metas.
In this Pull Request, we have replaced the previous approach of using a for-loop to store all data in memory and then performing individual insertions. Instead, we now use a single `INSERT INTO` query to streamline the data insertion process, improving both the accuracy and speed of the migration.
Form Migration
-   [ ] Relevant `@unreleased` tags …

Refactor: optimize form meta migration query

---

src/FormMigration/Steps/DonationOptions.php
src/FormMigration/Steps/EmailSettings.php
src/FormMigration/Steps/PdfSettings.php

During the testing of Form Migrations, we encountered errors caused by minor code details. This pull request aims to resolve those issues and ensure smooth Form Migrations.
This is a summary of the changes:
- Previously, if the attributes `customAmountMin` and `customAmountMax` were empty, they were saved as `0.0` post rounding implementation. Now, a validity check is performed on these attributes before rounding and saving them to ensure accurate data storage.
- Identified an issue where email notifications in P2P contained open-quotes, which interfered with form settings while extracting JSON content. This has been resolved by replacing open-quotes with double-quotes before setting the notifications in the migrated form.
- Noticed a migration step that saved the form prematurely before …

Fix: address minor form migration issues that could result in fatal errors

---

src/FormMigration/FormMetaDecorator.php
src/FormMigration/ServiceProvider.php
src/FormMigration/Steps/FeeRecovery.php

In this pull request, we add a new step to move Fee Recovery settings from a v2 form to the new  v3 form.
Form Migrations
1. Create v2 forms
2. Set Fee Recovery in many different combinations
3. Migrate those forms
4. Confirm your choices in v2 are reflected in the recently created v3 form
---
- https://app.asana.com/0/0/1205703084943466

Feature: add migration step for Fee Recovery settings

---

src/DonationForms/Actions/ConvertDonationFormBlocksToFieldsApi.php

This conditionally checks sets the donation form's default value for `gatewayId` - making sure it's only set if not empty. 
The donation form
- Step through a multi step form without a default gateway
- You should be able to get to the end but not actually submit.

Fix: conditionally set gateway id default value

---

src/DonationForms/Actions/ConvertDonationFormBlocksToFieldsApi.php
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/components/OptionsPanel/OptionsItem.tsx
src/FormBuilder/resources/js/form-builder/src/components/OptionsPanel/OptionsList.tsx
src/FormBuilder/resources/js/form-builder/src/components/OptionsPanel/index.tsx
src/FormBuilder/resources/js/form-builder/src/components/OptionsPanel/types.ts

This PR changes the way how Donor title prefixes are handled. Instead of using `FormTokenField` component, we now use the `Options` component used by donation levels. This adds flexibility for the site admin to easily add, remove, and reorder the donor title prefixes. Also, this PR resolves the error where the title prefix options UI didn't work at all. 
Form Builder -> Donor Name block
1. Select donor name block
2. Enable title prefixes
3. Add, remove, edit title prefixes
4. Save form and preview the form on frontend
-   [x] [Self …

Feature: Reorder donor title prefixes

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/text/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss

This makes the required asterisk show up for custom text blocks
Custom text block
- Add a custom field
- Enable required
- Make sure asterisk shows up
---
- https://app.asana.com/0/0/1205713285814722

Fix: text block required asterisk

---

assets/src/js/frontend/give-ajax.js
includes/class-notices.php

The donation form validates on the Ajax request before submission to give immediate feedback to the donor. Client-side code either expects `success` in response or error HTML code. I found that the previous pull request https://github.com/impress-org/givewp/pull/6845 causes a side effect, and the error does not render on v2 donation forms.
https://github.com/impress-org/givewp/blob/e957cbc673bd3bd37297006b556d944316a77755/assets/src/js/frontend/give-ajax.js#L266
[We recently discovered an issue related to this](https://feedback.givewp.com/bug-reports/p/razorpay-should-work-when-requesting-billing-address). I create confusion when the donor does see an error on the v2 donation form.
This pull request resolves this issue.
This pull request affects the V2 donation form. …

Fix: display errors on donation form when checkout validation fails for v2 forms

---

src/Donors/Endpoints/DeleteDonor.php

In the new List Table for Donors, we discovered an issue preventing the deletion of donors. Upon investigation, it was found that the capability being checked to authorize this action was incorrect.
This pull request fix this by aligning the capability validation with that of the legacy view, inclusive of the filter hook. This correction ensures that users who presently have the requisite permissions to delete donors retain this ability.
Donors list table
1. Open the Donors list
2. Try to delete a donor either individually or in bulk
3. The donors must be deleted (removed from the list)
-   [ ] Reviewed by the designer (if follows a …

Fix: update donor deletion functionality in donor list table

---

composer.json
give.php
readme.txt
src/Framework/Models/Factories/ModelFactory.php
src/TestData/Framework/Factory.php
src/TestData/Framework/Provider/RandomProvider.php
src/TestData/ServiceProvider.php
tests/Unit/PaymentGateways/Stripe/StripePaymentElementGateway/Actions/UpdateStripeFormBuilderSettingsMetaTest.php

GiveWP 3.0 updated the Faker package, which in turn updated the Psr/Container package. The container interface then conflicts with the [Matomo plugin](https://wordpress.org/plugins/matomo/).
This PR adds Faker to the Strauss list, so it and it's sub-dependencies are prefixed, avoiding conflicts.
In adding Faker to Strauss, I found that the `symfony/deprecation-contracts` package was having issues, as it's a single auto-loaded file. Strauss wasn't updating the file path, so composer was throwing a problem. Since the file is a root-level, conditionally loaded, single function, I decided it was simpler to just have that package excluded from Strauss. That fixed the issue.
Faker, which is used by our model factories.
The unit tests should really catch everything here. But we can also use `wp …

Fix: Resolve Matomo compatibility

---

src/FormBuilder/resources/js/form-builder/src/components/sidebar/Primary/index.tsx

Resolves Asana Task: [Remove Donation Goal from Form Settings](https://app.asana.com/0/1205428662243164/1205722351216728/f)
Donation Goal should only be available in Design, where people can see the changes as they make them. Currently, Donation Goal is included in both Design and the Form Settings tab of the builder. 
This could potentially cause confusion with users who may wonder which setting actually controls the goal, if they conflict, or if the goal setting appearing in both locations is some kind of bug. 
This PR removes the Donation Goal setting from the Form tab sidebar.
Primary Sidebar.
https://github.com/impress-org/givewp/assets/75056371/c2d56096-e936-46d0-b2d3-85b81a0d9bae
- Create or edit a v3 form
- Verify the Donation Goal settings is accessible while in design mode but …

Refactor: remove donation goal setting from form mode

---

src/FormBuilder/resources/js/form-builder/src/blocks/elements/paragraph/Edit.tsx

This PR removes the "content" setting inspector control for the paragraph element block.
---
- https://app.asana.com/0/0/1205502083833606
- https://app.asana.com/0/0/1205722351216731
- https://app.asana.com/0/0/1205740516183534

Refactor: Remove paragraph content from inspector

---

give.php
readme.txt
src/FormMigration/FormMetaDecorator.php

Currently, when an user migrates a form with Fee Recovery custom settings and has the per-gateway settings option enabled, Stripe options were not being migrated properly.
We have found that the migration script contains an error when mapping gateway ids from v2 to v3: the gateway id for v3 was being used to retrieve the form settings, which obviously will not be found in a v2 form.
This pull request fixes that issue by using the original gateway id to retrieve the settings while using the updated gateway id to set the settings onto the v3 form.
Fee Recovery migration
1. Add a v2 form with Fee Recovery
2. Set it to use per-gateway settings
3. Edit Stripe values
4. Migrate the form
5. Confirm that Stripe values were properly migrated to the Fee Recovey block in v3. …

Fix: set correct gatewayId when migrating Fee Recovery settings for Stripe

---

give.php
includes/admin/settings/class-settings-gateways.php
includes/forms/template.php
includes/gateways/functions.php
readme.txt

After splitting the gateways based on whether they support v2 or v3 forms, we found that it was not possible to get a complete list of all active gateways in Give. This complete list is important for other features, like setting Fee Recovery options for each gateway.
When we made this split, we chose to make sure the `$version` parameter defaults to `2`. This was done to maintain compatibility with older v2 code, ensuring that it would continue to work seamlessly. However, we recently realized that this might not be the best solution. This is because, aside from the donation forms themselves, most other settings require access to the complete list of gateways.
In this pull request, we've changed the default value of the `$version` parameter to `null`. This allows us to combine the lists …

Refactor: add support to get all gateways on the gateways functions

---

give.php
readme.txt
src/DonationForms/FormPage/TemplateHandler.php
src/DonationForms/Repositories/DonationFormRepository.php
src/FormBuilder/Routes/EditFormRoute.php

Resolves #7057
In some places of our codebase, we are assuming that a form is v2 when the `post_content` is empty and v3 when the `post_content` isn't empty. 
The problem is that some users use page editors like Elementor to edit the content (the `post_content` column) of v2 forms. So after doing that a fatal error is thrown and the form doesn't get more rendered in the frontend, and no more can't be edited in the WP admin area.  
This PR fixes this problem!
Legacy forms with `post_content` populated.
**To replicate the problem:**
1. install GiveWP 3.0 + Elementor
2. create a new legacy form and make sure the Display Content option is enabled
3. Enable Elementor editing for donation forms under Elementor > Settings
4. go back to the form and click on Edit with Elementor
5. add a new …

Hot Fix: Prevent fatal errors on legacy forms (v2) when it has 'post_content' populated

---

give.php
readme.txt
src/MultiFormGoals/MultiFormGoal/Shortcode.php
src/MultiFormGoals/ProgressBar/Model.php

Resolves #7060
We are getting a fatal error when users try to use the multi-form shortcode with the ids attribute. 
Something like this: `[give_multi_form_goal ids="31,39] `
This PR fixes this bug - by returning the proper data type in the `getForms()` method - and allows users to use the ids attribute without throwing any fatal error.
The give_multi_form_goal shortcode.
1. Add the Multi-Form Goal Shortcode to a page or post and include the "ids" parameter to only include one or more forms. Example: `[give_multi_form_goal ids="31,39]`
2. Click on "Update"
3. No fatal errors should be thrown and the form should get updated without problems. …

Hot Fix: Prevent fatal error on save posts or pages with [give_multi_form_goal] shortcode

---

src/FormBuilder/resources/js/form-builder/src/containers/HeaderContainer.tsx
src/FormBuilder/resources/js/form-builder/src/settings/form-summary/index.js
src/FormBuilder/resources/js/form-builder/src/settings/form-summary/page-slug.js

Resolves Asana task: https://app.asana.com/0/1205428662243164/1205735215345414/f
This PR saves the form title as the page slug when a form first publishes. After a form has been published the page slug can still be edited, however it is not respective of the form title on any subsequent change.
If the form title is not updated on the first publish the page slug will continue to to work as it previously did, generating the slug trailing with a new number.
I had looked into a central way of dispatching this in the onSave function call - however had inconsistent state changes and the page slug was being overwritten on refresh.  Due to this I've opted to include conditional dispatch call's for the page slug on both form title controls.
Re: …

Feature: save title as pageslug on publish

---

src/DonationForms/Routes/AuthenticationRoute.php
src/DonationForms/resources/registrars/templates/groups/Authentication.tsx
src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php
src/FormBuilder/resources/js/form-builder/src/blocks/fields/login/index.tsx
src/FormBuilder/resources/js/form-builder/src/components/editor/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/email/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/email/logo-upload/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/email/template-options/components/copy-to-clipboard-button.tsx
src/FormBuilder/resources/js/form-builder/src/settings/email/template-options/components/send-preview-email.tsx
src/FormBuilder/resources/js/form-builder/src/settings/email/template-options/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/email/template-options/settings.tsx
src/FormBuilder/resources/js/form-builder/src/settings/styles/index.tsx
src/FormBuilder/resources/js/form-builder/src/supports/field-settings/FieldSettingsHOC.tsx
src/FormMigration/ServiceProvider.php
src/Framework/FieldsAPI/Authentication.php
src/PaymentGateways/Gateways/PayPalCommerce/PayPalCommerceGateway.php
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx
src/PaymentGateways/Gateways/PayPalStandard/PayPalStandard.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementGateway.php
src/PaymentGateways/Gateways/TestOffsiteGateway/TestOffsiteGateway.php
src/Promotions/WelcomeBanner/resources/js/app/app.tsx
src/Promotions/WelcomeBanner/resources/js/app/components/Sections/LeftContentSection.tsx
src/Promotions/WelcomeBanner/resources/js/app/components/Sections/RightContentSection.tsx

Related: https://github.com/impress-org/givewp/issues/7035#issuecomment-1771434420
This sets all core gateways and form builder script handles for translation.
This also fixes a typo in the textdomain for various string from `'givewp'` to `'give'`
Sets translation for following scripts:
- Form Builder Registrars (blocks)
- Form Builder App
- PayPal standard
- PayPal commerce
- Stripe Payment Element
- Test Offsite gateway
In Italiano
**Form Builder**
Using a different language than english (ex: italiano has a lot of give support) view the form builder:
You should notice the form builder settings / labels are translated
**Gateways**
The easiest one to test would be PayPal Standard as there are no fields, just text.
-   [ ] …

Fix: add translation to all gateways, form builder scripts, and fix text domain typo

---

src/FormBuilder/Actions/GenerateDefaultDonationFormBlockCollection.php
src/FormBuilder/Routes/CreateFormRoute.php
src/Framework/Blocks/BlockModel.php
tests/Unit/Actions/GenerateDefaultDonationFormBlockCollectionTest.php

Resolves: #7035
Previously we have been generating new forms using our static `blocks.json` file.  This was problematic with translation because we are simply storing english words in the database.  WordPress translation only works with static strings, so once you store your strings in the database - they will remain untranslated until translated manually.
This updates the generation of a new form to use block models instead of the static `blocks.json` file.  This is necessary to include translatable strings during the initial form creation as all user-facing strings are wrapped in translation functions.  
Of course this isn't perfect, the strings would need to be pre-translated before creating a new form so the translated words are stored in the database.  Yet, this is a good start as at …

Refactor: create new forms using block models for translatable strings

---

assets/src/css/frontend/progress-bar.scss
includes/class-give-scripts.php
includes/shortcodes.php
webpack.mix.js
wordpress-scripts-webpack.config.js

Initially, I added [these lines](https://github.com/impress-org/givewp/blob/develop/webpack.mix.js#L85-L88) in the webpack settings file to solve [this other bug](https://github.com/impress-org/givewp/pull/7069) and I didn't notice that it prevent the Donor Dashboard to get loaded.
So, to fix the initial problem and keep the Donor Dashboard working, it was necessary to compile the scripts used in the Gutenberg blocks with WP Scripts.
- Multi-Form Goal Block > Progress Bar > Filters
- Donor Dashboard
1. Create a new page;
2. Add the multi-form goal block;
3. Click on the progress bar;
4. On the right side, click on Filters and Filter by form;
5. No more errors should be displayed.
6. Access the Donor Dashboard, it should load without problems.
-   [ ] Acceptance criteria satisfied and …

Refactor: use wp scripts to compile Gutenberg blocks

---

includes/admin/tools/views/html-admin-page-system-info.php

WordPress has held backwards compatibility for the MySQL PHP extension for a long time, and provided the `$wpdb->use_mysqli` property as a way of checking if a WP instance is using the old extension, or the new(er) mysqli extension.
In WP 6.4, support for the [old extension is being dropped](https://core.trac.wordpress.org/ticket/59118), due to the fact that the extension doesn't exist in PHP 7.0, which is the new minimum required version of WordPress. With this, WP is also dropping the `$wpdb->use_mysqli` property because it's meaningless.
Our code was using both that property _and_, conditionally, the function the used the old extension. Since we don't support <PHP 7.2, we can also drop the use of that function and WP property.
The MySQL portion of the system info page
Make sure that …

Fix: mysql information displays properly in WP 6.4

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/ChargeRefunded.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/CustomerSubscriptionCreated.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/CustomerSubscriptionDeleted.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/InvoicePaymentFailed.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/InvoicePaymentSucceeded.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/PaymentIntentPaymentFailed.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/PaymentIntentSucceeded.php

Resolves #7076
The webhook events used by the Stripe Element were using the exit in the wrong place and it was preventing the events from the legacy codebase from running.
This PR fixes this problem.
Stripe renewals in donations/subscriptions created with v2 forms.
1. Using the latest version of GiveWP and the Recurring Donations add-on, make a recurring donation on a V2 form
2. Spoof a renewal in Stripe by resetting the billing cycle: https://somup.com/c06tcOBP02
3. The renewals should be recorded on the Give side.
-   [ ] [Self …

Hot Fix: properly record the Stripe renewals on the Give side

---

includes/shortcodes.php
templates/shortcode-donor-wall.php

Resolves https://app.asana.com/0/1205428662243164/1205836070799020
This PR addresses the following warning 
`Warning: _give_redirect_form_id(): Argument #2 must be passed by reference, value given in /Users/joshuadinh/Local Sites/givewpdeveloper/app/public/wp-content/plugins/givewp/includes/shortcodes.php on line 634 from this line         array_walk($form_ids, '_give_redirect_form_id');
`
- Add totals shortccode to a page.
- Verify no warning displays.
- Example shortcode : `[give_totals ids="1460" message="Thanks to you, we’ve raised {total} across all our congregations combined! Let's keep it up!" progress_bar="true"]` …

Fix: pass form id by reference in totals shortcode to avoid PHP warning

---

src/FormBuilder/resources/js/form-builder/src/supports/field-settings/FieldSettingsHOC.tsx

This PR restore the supports feature namespace to `givewp`.
The namespace for the supports feature is `givewp,` but was updated to `give` during a recent update of text domains for translations.
This effects the Text Field and other custom fields provided by Form Field Manager.
See [https://github.com/impress-org/givewp/commit/e63e340f4af1525e22c3d4467668b4fe717d1188#diff-0c9fff56298afb7f25c7be3f[…]d99ddf3c2cfe0890d4db5f5ff83L28](https://github.com/impress-org/givewp/commit/e63e340f4af1525e22c3d4467668b4fe717d1188#diff-0c9fff56298afb7f25c7be3fbba6479227010d99ddf3c2cfe0890d4db5f5ff83L28)
```diff
const fieldSettings: FieldSettings = useMemo(() => {
// @ts-ignore
-          const giveSupports = getBlockSupport(name, 'givewp') as GiveWPSupports;
+          const giveSupports = …
```

fix: Restore givewp namespace for supports feature

---

includes/database/class-give-db-meta.php

Resolves https://github.com/impress-org/givewp/discussions/6798
https://github.com/impress-org/givewp/blob/33cffa1cc6a2d64f820411eac1d0b65058d4ed85/includes/database/class-give-db-meta.php#L153
I found that `Give_DB_Meta::get_meta` returns an empty `string` when `$single` is set to `false` and metadata does not exist in the database, but the expected value is empty `array.` This triggers a fatal error on PHP `7.4` if this value passes to a function that expects an `array` like: `count`.
To resolve the issue, this function returns `string|array` on the basis of `$single` value.
This change affects GiveWP core metadata-related queries which use the `get_post_meta` function.
```php
$donation_meta = get_post_meta( 236, 'foo' );
$post_meta = get_post_meta( 1, 'foo' );
```
-   [x] Acceptance …

Fix: return get_post_metadata compatible result from custom filter hook

---

src/Framework/Receipts/Actions/GenerateConfirmationPageReceipt.php

Resolves #7084
This updates the confirmation page "Payment Method" label to display as the gateway checkout label as defined in gateway settings.
The donation confirmation page
- Go to gateway settings and update the checkout label to something different
- Enable the gateway and donate with it using a v3 form
- The confirmation page should display the defined checkout label from settings in the "payment method" line item
---
- To see the specific tasks where …

Fix: use custom gateway label for confirmation page payment method

---

give.php
readme.txt
src/DonationForms/Shortcodes/GiveFormShortcode.php

Resolves #7086
This ensures embedded v3 forms redirect to the confirmation page.  
More specifically, this adds a static instance counter to the shortcode action to simulate the `blockId` attribute that v3 form blocks use (which is philosophically the same). When the page is redirecting with the intention of displaying the confirmation inline, the embed ID needs to exist on the page so it knows where to place an inline redirect.  Previously this was using a `uniqueId()` which means the embed Id was never found.  
- v3 Forms rendered from a shortcode (or existing v2 form block).
- Create a v3 form 
- Create a new page
- Add 2 or more forms to a page using the give form shortcode and/or donation form block
- Use stripe payment element test mode and submit a form
- The page should refresh …

Fix: ensure embedded v3 forms redirect to confirmation page

---

src/DonationForms/Controllers/DonateController.php
src/DonationForms/Properties/FormSettings.php
src/Donors/Actions/CreateUserFromDonor.php
src/Donors/Actions/SendDonorUserRegistrationNotification.php
src/Donors/Exceptions/FailedDonorUserCreationException.php
src/Donors/ServiceProvider.php

Fixes [[GIVE-20]](https://stellarwp.atlassian.net/browse/GIVE-20?atlOrigin=eyJpIjoiN2UxMTJmZDgzOTZjNDM0YTk4MTJiMGUzZWU1YWRlZWQiLCJwIjoiaiJ9)
This PR implements the feature that all donors created by v3 forms have a registered WordPress user.
Additionally, the form can be configured to send a New User Registration email when a WordPress user is created.
Note: The New User Registration Email can be disabled globally. In order to be sent by a v3 form the email must be enabled globally AND the notification must be enabled in the v3 form.
- Adds a new `do_action` hook to the Donate Controller when a donor is created.
- New donors should have an associated WordPress user.
- If enabled, new donors should receive a New User Registration Email.
[GIVE-20]: …

Feature: All donors are registered as users (only applies to v3 forms)

---

src/Donations/DataTransferObjects/DonationQueryData.php
src/Donations/Endpoints/ListDonations.php

Resolves #7096 [GIVE-27]
This resolves an issue where in some cases the donation mode was not stored in the database and the donation model query was causing an error from expecting a value.  This is most notable on the admin list table.  The simplest way to resolve this is to have a static fallback which was updated in this PR.  
Typically we would create a migration for missing data that is expected, but this is unique in that we would have no way of knowing what the actual donation mode was at the time of creation.  Furthermore, in terms of backwards compatibility - this could be a persistent issue from a third party add-on that intercepts or modifies the donation.  So the safest and simplest option is just to have a static fallback value of "live" as that is always the assumption …

Fix: provide fallback for donation mode during model queries

---

src/DonationForms/V2/Endpoints/ListDonationForms.php

Resolves [GIVE-109]
This adds the SQL distinct statement to the donation forms list query to prevent duplicate results.
The donation forms list table results
- Create a few forms and view the donation forms list
- Make sure there are not duplicate results
- Try searching for a title or ID and make sure there are not duplicate results
[GIVE-109]: https://stellarwp.atlassian.net/browse/GIVE-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

Fix: add distinct to donation forms list query to prevent duplicate results

---

src/PaymentGateways/PayPalCommerce/ScriptLoader.php

Resolves [GIVE-114]
The PayPal donations script does not load if the donation form is added to post content as a shortcode. For this reason, the payment method is not rendered in the donation form. I implemented a logic to resolve this.
PayPal donations payment method in a donation form with a legacy form template.
There are a few known issues that I will resolve in a separate pull request:
- Display style setting does not work with legacy format template in donation form shortcode.
- Advanced card field style is not good if payment method options are not visible initially with legacy form templates like modal, button, and reveal display style.
- Donation form does not render correctly if added using the widget.
-   [x] …

Hotfix: PayPal Donations payment methods should render in donation form

---

includes/forms/functions.php

Resolves #7132, [GIVE-145]
Related: https://github.com/impress-org/givewp/pull/7134
This PR removes the default argument supplied to the give form shortcode. Legacy templates rely on this value being empty. When no value is present the Legacy template can use the default values stored in the form meta for display.
Donation Form shortcode/block
https://github.com/impress-org/givewp/assets/75056371/5863829b-f50b-4118-822a-7d005043f29a
https://github.com/impress-org/givewp/assets/75056371/3ac8d923-e871-484a-bfaa-4c6b7a0a4f81
- Create a v2 Legacy template form
- Edit the form & select a form display option
- Create a shortcode and do not use the display style attribute in the shortcode.
- Example: [give_form id=100]
- View page verify the shortcode displays the form with the proper display …

Hotfix: remove default display argument on `[give_form]` to support legacy form meta

---

src/DonationForms/V2/DonationFormsAdminPage.php
src/Promotions/InPluginUpsells/LegacyFormEditor.php

Resolves #7092, [GIVE-1]
Replaced logic for checking if editing v2 forms to be `give_forms` post_type specific to avoid showing up on unrelated WordPress pages.
- v2 donation form admin page editing conditional
N/A
- As an admin, go to `/wp-admin/nav-menus.php` to edit menus (make sure you have WP_DEBUG set to true)
- You should _not_ get this visual error:
[GIVE-1]: https://stellarwp.atlassian.net/browse/GIVE-1?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

Fix: narrow scope of checking if editing v2 forms 

---

src/DonationForms/Blocks/DonationFormBlock/resources/editor/Edit.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/editor/components/DonationFormBlockControls.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/editor/components/DonationFormBlockPreview.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/editor/components/DonationFormSelector.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/editor/hooks/useFormOptions.ts
src/DonationForms/Blocks/DonationFormBlock/resources/editor/hooks/usePostState.ts

Resolves [GIVE-147]
- This prevents the donation form block to render an error when v2 forms are included in the list of forms.
- This also fixes the block inspector form selector to persist the correct form id value
The donation form block.
N/A
- Create a mix of v2 and v3 forms
- Add a new page with donation form block
- Select a v2 form
- Refresh the page
- You should not get an error.
- Now select a new form using the block inspector settings and save
- Refresh the page
- You should see the form preview of the form you selected
-   [ ] [Self …

Fix: prevent donation form block from causing error on edit page load.

---

includes/class-give-donate-form.php
src/DonationForms/Migrations/RemoveDuplicateMeta.php
src/DonationForms/ServiceProvider.php
src/FormMigration/Actions/TransferDonations.php

Resolves [GIVE-137]
This PR resolves the issue of duplicate donation forms. The problem was in the logic of the `get_earnings` method combined with the donation transfer logic which resulted in the meta key being duplicated on every page load. That also affected the donation forms list table which was displaying duplicated results. 
The issue is resolved by using `update_post_meta` instead of `add_post_meta` function, and by adding a migration for deleting duplicated meta keys (`_give_form_earnings`, `_give_form_sales`) and setting the correct values for  `_give_form_earnings` is added. 
Donation Forms list table
Donation Form data transfer
The best way to test this is on an existing site that has this problem.
Create a new site by using Local or something similar.
Install All-In-On WP …

Fix: duplicate meta keys

---

includes/forms/functions.php
src/DonationForms/Blocks/DonationFormBlock/Controllers/BlockRenderController.php
src/DonationForms/Blocks/DonationFormBlock/DataTransferObjects/BlockAttributes.php

Resolves #7150  / [GIVE-145]
This PR removes the static default value for `continue_button_title` in the shortcode args, so that form meta can be used as the default for legacy forms. We still require a default value for v3 forms, so one has been added to the `BlockAttributes` class.
Also I found a duplicate line for `$formUrl` in the `BlockRenderController` that I removed. It was an oversight while merging [Feature: include shortcode & block control support for v3 forms #7082](https://github.com/impress-org/givewp/pull/7082/files#diff-6afdb6343e85db42452a2debf534303d64d06709fd43e3119b0670f89a2fabae)  and [Feature: Embed Donation Form button #7080 ](https://github.com/impress-org/givewp/pull/7080)
Legacy Forms, shortcode, block
https://github.com/impress-org/givewp/assets/75056371/e38b77da …

Fix: Remove default value for `continue_button_title` - [GIVE-145]

---

src/Donors/CustomFields/Controllers/DonorDetailsController.php

Resolves #7130, [GIVE-146]
This fixes an error on the donor details page when the donor has no donations.
- Donor details page
Test for Donors with and without donations
- Create a donor with donations
- Create a donor without donations
- View both donor details pages
[GIVE-146]: https://stellarwp.atlassian.net/browse/GIVE-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: resolve donor details page error when they have no donations

---

src/Exports/DonorsExport.php

This PR resolves the issue with donor export where filtering donors by donation form was not working. The issue is resolved by adding additional logic that allows filtering donors by donation form ID. 
Donors export
Create a few donation forms and make donations
Make sure you make donations with different donors on each form
Export donors
Export donors using a donation form filter

Fix: Export donors - filter by donation form

---

give.php
includes/admin/abstract-admin-settings-page.php
includes/class-give-donate-form.php
includes/class-give-donor.php
src/Donors/Repositories/DonorRepositoryProxy.php
src/Framework/FieldsAPI/Option.php
src/Framework/QueryBuilder/Clauses/From.php
src/Framework/QueryBuilder/Clauses/Join.php
src/Framework/QueryBuilder/Clauses/Select.php

Resolves #7141
This PR adds PHP 8.2 compatibility to Give Core, but it fails to do that 100% since we use packages that we can't update without bumping the min required PHP version for Give Core.
Packages that require updates:
**moneyphp/money**
Currently, we use v3.3.1 which throws notices running on servers that use PHP 8.2
To fix this we have to update this package to v4.0.0. The problem is that this version requires PHP ^8.0
**myclabs/php-enum**
Currently, we use v1.6 which throws notices running on servers that use PHP 8.2
To fix this we have to update this package to ^1.8.0. The problem is that this version requires PHP ^7.3
Give Core
Install Give on server that runs PHP 8.2
Enable `WP_DEBUG` and `WP_DEBUG_LOG`
Add donation forms
Make donations
Edit donors
Preview forms on frontend …

PHP 8.2 compatibility 

---

src/DonorDashboards/Routes/PasswordResetRoute.php
src/DonorDashboards/ServiceProvider.php
src/DonorDashboards/resources/js/app/components/auth-modal/index.js
src/DonorDashboards/resources/js/app/components/auth-modal/utils/index.js

This PR adds a Password Reset feature to the Donor Dashboard login modal.

Feature: Allow donors to update or reset their password

---

src/DonationForms/resources/registrars/templates/groups/BillingAddress.tsx

Fix necessary for [GIVE-12]
While working on Gift Aid 3.0 compatibility, we encountered an issue with the `State` field (referred to as `County` for Gift Aid in the United Kingdom). The problem is that users are unable to enter any text in this field. In the case of countries like the USA, the state field is a dropdown menu with available options and it works correctly. However, for countries like the UK, it should be a text input, and that's where the error occurs.
Upon further investigation, I discovered that the text input had a fixed value of `''` and did not update when typing.
This pull request resolves the issue by making the value of the field dynamic, updating according to the current value of the `state` state.
Billing Address block
|![CleanShot 2023-12-26 at 18 09 …

Fix: allow users to type into the state/county field input

---

src/DonationForms/FormDesigns/TwoColumnFormDesign/TwoColumnFormDesign.php
src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/TwoPanelStepsFormLayout.php
src/DonationForms/ServiceProvider.php
wordpress-scripts-webpack.config.js

Resolves [GIVE-153]
This adds a new "Two Panel (steps)" option to the form layout dropdown list.  Currently this does not include any styles, just the option and is equivalent to multi-step.
- Form design dropdown
- Try selecting "Two Panel (steps)" from the form design list.
[GIVE-153]: https://stellarwp.atlassian.net/browse/GIVE-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: add Two Panel (steps) option to Form design drop-down

---

src/DonationForms/Properties/FormSettings.php
src/DonationForms/ValueObjects/DesignSettingsTextFieldStyle.php
src/DonationForms/ViewModels/DonationFormViewModel.php
src/DonationForms/resources/styles/base.scss
src/DonationForms/resources/styles/design-settings/text-field.scss
src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/layout/index.tsx
src/FormBuilder/resources/js/form-builder/src/types/formSettings.ts

This PR introduces the text field control settings into the General `FormDesignControls`.
1. Box (inner-label)
2. Line (inner-label)
https://github.com/impress-org/givewp/assets/75056371/fe1af4e2-514a-41b2-8aae-af33b0929d5d
- Test both of the TextField settings from within the General Setting controls. (View Visuals for instructions)

Feature: add text field styles to `FormDesignSettings`

---

src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/css/_container.scss
src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/css/_header.scss
src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/css/_sections.scss
src/DonationForms/resources/app/form/MultiStepForm/components/StepsWrapper.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss
src/FormBuilder/resources/js/form-builder/src/styles/_onboarding.scss

This pull request adjusts styles related to the addition of the new Two-Panel (Steps) layout.
- the width of the header section in the Two-Panel (Steps) layout. The width is increased to 42.5rem, with a breakpoint at 71.5rem resizing it to 35rem, like what happens in the design preview tab;
- it resolves a glitch where the header appeared narrower when the description section was disabled;
- the design selector modal was changed, having header texts centered and its button right aligned.
Two-Panel (Steps) layout and Design Selector modal
-   [x] [Self …

Fix: adjust styles for Two-Panel (Steps) and Design Selector modal

---

src/PaymentGateways/Gateways/PayPalStandard/Migrations/SetPayPalStandardGatewayId.php

If GiveWP is activated on a new site, there is a fatal error:  Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/wordpress/wp-content/plugins/give/src/PaymentGateways/Gateways/PayPalStandard/Migrations/SetPayPalStandardGatewayId.php:30 Stack trace: #0 
For a new site, no gateway is defined, and $gateways is null.

Avoid a fatal error when activating GiveWP for a new site

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementGateway.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/stripePaymentElementGateway.tsx
tests/Feature/Gateways/Stripe/StripePaymentElement/TestStripePaymentElementGateway.php

The only way to modify the appearance of the Stripe Elements gateway fields is through a JS script. There's currently no way to do this as the Stripe options are hard-coded.
This PR adds a filter to add appearance options to the Stripe options. I started with a more general filter, but decided to limit the scope as that's all I really need, and we want to be careful about folks messing with the options otherwise.
This also doesn't provide a non-programmatic way of adjusting the fields. Especially since Stripe provides themes, I think it makes sense to surface this in the Design Settings in the future, but it's more than I need now and these two options aren't mutually exclusive.
The Stripe Elements fields as rendered in v3 forms
I used the following PHP snippet to test it out:
```php …
```

Feature: add filter to add stripe elements appearance options

---

give.php
readme.txt
src/FormMigration/FormMetaDecorator.php

Resolves [GIVE-243]
After version 3.3.0, form migrations began to fail with a fatal error. Upon investigation, I discovered that under certain conditions, the conditionals for executing the Funds & Designations step were attempting to count the elements of a nullable variable, resulting in the fatal error.
This pull request resolves the issue by replacing the `count` function with an `!empty` check. This fix will work for both nullable variables (returning false) and arrays.
Form Migrations
1. Create a v2 form
2. Migrate it
-   [x] [Self …

Fix: prevent fatal error during form migration

---

give.php
includes/install.php
src/PaymentGateways/Gateways/PayPalStandard/Migrations/SetPayPalStandardGatewayId.php

Resolves [GIVE-119]
This epic fixes errors reported by @Genevieve-K when adding/removing sub-sites in a WP multisite install.
Include the following PRs:
- https://github.com/impress-org/givewp/pull/7113
- https://github.com/impress-org/givewp/pull/7120
- https://github.com/impress-org/givewp/pull/7162
WP Multisite installs
1. Create a new multisite install
2. Add a new sub-site
3. Enable Give for the entire network
4. Confirm Give tables were properly created for all sites
5. Remove the recently created sub-site
6. Confirm all Give tables for that sub-site were removed
7. Create a new sub-site
8. Confirm Give tables were properly created for this new sub-site
9. Confirm no fatal errors happened
-   [x] Relevant …

Fix: avoid errors on add/remove a sub-site in a WP multisite

---

src/DonationForms/Blocks/DonationFormBlock/Controllers/BlockRenderController.php
src/DonationForms/Blocks/DonationFormBlock/resources/app/Components/ModalForm.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/app/index.tsx

Resolves [GIVE-258]
This ensures when using an offsite gateway and the modal display for donation form blocks using v3 forms - the confirmation page is displayed in place of the modal form when returning to the website origin.
The modal form
- Enable paypal standard & stripe payment element
- Create a page with the donation form block
- Select "modal" from display settings
- Go through donation form inside modal using paypal standard and then stripe payment element
- It should redirect back to the page when complete showing the confirmation receipt inside the model
- When you close the modal you should be able to click the donate button again and get a fresh form
- (note) refreshing the page will result in the confirmation page showing up again. …

Fix: modal form redirect compatibility with offsite gateways

---

includes/admin/tools/views/html-admin-page-system-info.php

On PHP >= 8.0, when `allow_url_fopen` is `0`, a critical error blocks the rest of the page loading on the System Info page after the TLS values.
On Tools > System Info:
"TSL Connection" shows "Connection uses" (blank)
"TLS Rating" shows "There has been a critical error on this website..."
If the config value is false, `$tls_check` remains false, and then `json_decode()` fails, returning `null`. Then `property_exists()` is called with the null value, which triggers the critical error.
I've simply added checks to see if `$tls_check` is false, and if so, display text prompting the user to enable `allow_url_fopen` instead of attempting to decode the non-existent body text.
I considered attempting to use cURL as a fallback if the user has it enabled but figured this may be overkill. Also I …

Fix: Remove superfluous allow_url_fopen check to avoid critical error from falsy value

---

src/Framework/FieldsAPI/Field.php
src/Framework/Receipts/Actions/GenerateConfirmationPageReceipt.php
tests/Unit/Framework/Receipts/TestGenerateConfirmationPageReceipt.php

Resolves [GIVE-279]
- The v3 confirmation page should respect when custom fields use `->metaKey()` in conjunction with `->showInReceipt()` to display their value.
- Fields that use both `->metaKey()` and `->showInReceipt()`.
zip: https://github.com/impress-org/givewp/actions/runs/7742785302
- You can use the following code snippet
- After donating, the confirmation page should display the above screenshot
```
add_action('givewp_donation_form_schema', static function (Give\Framework\FieldsAPI\DonationForm $form) {
$field = Give\Framework\FieldsAPI\Text::make('favoriteColor')
->label('Your favorite color:')
->defaultValue('Blue')
->metaKey('_favorite_color')
->showInReceipt();
$form->insertAfter('email', $field);
});
```
- …

Fix: ensure `showInReceipt` is compatible with all fields including use of `metaKey`

---

src/DonationForms/resources/registrars/templates/layouts/DonationReceipt.tsx

Resolves: [GIVE-291]
This will allow html to be added to the confirmation page for more flexibility.
- Confirmation page detail values will be rendered properly if supplied a string of html.
Zip: https://github.com/impress-org/givewp/actions/runs/7733974060
Programmatically return an html value for receipt:
```
add_action('givewp_donation_form_schema', static function (Give\Framework\FieldsAPI\DonationForm $form) {
$field = Give\Framework\FieldsAPI\Text::make('favoriteColor')
->label('Your favorite color:')
->defaultValue('Blue')
->metaKey('_favorite_color')
->showInReceipt()
->receiptValue(function (Give\Framework\FieldsAPI\Text $field, Give\Donations\Models\Donation $donation) {
$favoriteColor = give_get_meta($donation->id,'_favorite_color', true);
return sprintf('<strong style="color: …
```

Feature: update confirmation page detail values to allow html

---

includes/admin/payments/class-payments-table.php

As an administrator, I would like to update donations with a bulk action. The result is:  
`We're unable to recognize your session. Please refresh the screen to try again; otherwise contact your website administrator for assistance. `
The nonce verification failed.
In class-wp-list-table.php, the nonce is created from `'bulk-' . $this->_args['plural']`. In French this plural is "formulaires". And the verification uses `'bulk-forms'`.
Test bulk actions  in other languages as English

Fix: Update nonce validation to match when translated

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/payment-gateways/Edit.tsx
src/FormMigration/Steps/PerFormGateways.php

Resolves [GIVE-251]
This PR adds a new filter to the payment gateway block which allows us to set if a specific gateway is enabled or not in the list of gateways displayed in the form builder.
It's useful for addons that need to handle the items of the gateway list like the Per Form Gateways addon which uses this new filter here: https://github.com/impress-org/give-per-form-gateways/pull/12
The Payment Gateway block.
Follow the instructions of this PR: https://github.com/impress-org/give-per-form-gateways/pull/12
-   [ ] [Self …

Refactor: control items visibility in the gateways block trough a new filter

---

src/DonationForms/Blocks/DonationFormBlock/resources/app/Components/ModalForm.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/editor/styles/index.scss
src/DonationForms/FormDesigns/ClassicFormDesign/css/_layouts.scss
src/DonationForms/resources/styles/_pico.scss
src/DonationForms/resources/styles/elements/_multi-step-form.scss

This PR focuses on making styling improvements to the form modal display option. Most notably, the position of the dialog is no longer relative, but is instead fixed. This makes sure the modal is in the center of the page, regardless of the scroll position.
From there:
- the backdrop of the modal was too light, 10% opacity black, and has been increased to 50% opacity
- the background color for the modal was made transparent
- the box shadowing and bordering of the form have been corrected to the design (per Jeffrey's guidance)
- moved the close button outside of the form to not clash with various form background colors
The form modal display mode styling
1. Make a form
2. Embed the form on a page
3. Change the display mode to "modal"
4. Check out the form on the page and make sure it …

Feature: fix form modal to page (and other styling)

---

src/PaymentGateways/Stripe/Controllers/NewStripeAccountOnBoardingController.php
tests/Feature/Controllers/NewStripeAccountOnBoardingControllerTest.php

Based on the query param, we are handling the Stripe redirect from the connect gateway server. We should limit handling to specific pages to prevent conflict.

Handle the Stripe connect redirect on specific pages

---

src/EventTickets/Actions/ConvertEventTicketsBlockToFieldsApi.php
src/EventTickets/Fields/EventTickets.php
src/EventTickets/Hooks/DonationFormBlockRender.php
src/EventTickets/ServiceProvider.php

This pull-request adds a initial structure for the EventTickets Field and a converter with hardcoded values, allowing us to start testing the field template and how it integrates with the donation form.
Use the following snippet to programmatically add a EventTickets field to the form.
```php
add_action('givewp_donation_form_schema', static function (DonationForm $form) {
$field = \Give\EventTickets\Fields\EventTickets::make('event_tickets');
$form->insertAfter('email', $field);
});
```
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-revi …

Feature: Scaffold Field and Converter

---

give.php
readme.txt
src/DonationForms/Actions/ConvertDonationFormBlocksToFieldsApi.php
src/FormBuilder/resources/js/form-builder/src/blocks/fields/email/settings.tsx
tests/Unit/DonationForms/Actions/TestConvertDonationFormBlocksToFieldsApi.php

Resolves [GIVE-330]
The mapping of generic block attributes was overriding the intentional use of the core email required rule.  This guided me toward making sure if a field is specifying a required rule up front, we do not want to let the generic attributes override them. 
- The core email field (always visually & functionally required now)
- Minor updates to the block conversation process as it relates to mapping generic block attributes
Zip: https://github.com/impress-org/givewp/actions/runs/7890132090
- Remove the default email block
- Add a new core email block
- Make sure it appears to be required
- Publish form and test it out to make sure its required.
-   [x] Relevant `@unreleased` tags included …

Fix: prevent generic block attributes from overriding intentional required rule

---

src/Framework/Models/EagerLoader.php
tests/Unit/Framework/Models/TestEagerLoader.php

This PR introduces a Eager Loader to support loading a models relationship with a single additional query (as opposed to an additional query per model).
Example:
```php
// Given 1 event this runs 2 queries.
// Given 10 events this runs 11 queries.
// Given 100 events this runs 101 queries.
$events = Event::query()->getAll();
foreach($events as $event);
$events->tickets; // Additional query for each event
}
```
```php
// Given 1 events this runs 2 queries.
// Given 10 events this runs 2 queries
// Given 100 events  this runs 2 queries.
$events = Event::withTickets()->getAll();
foreach($events as $event);
$events->tickets; // No additional query - already cached
}
```
The existing `ModelQueryBuilder` is not affected. Instead the `EagerLoader` class decorates the underlying query builder …

Feature: Add eager loading of related models

---

src/DonationForms/FormDesigns/MultiStepFormDesign/css/_header.scss
src/DonationForms/resources/registrars/templates/layouts/Header.tsx
src/DonationForms/resources/styles/design-settings/image.scss
src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/multi-step/index.tsx

This PR reintroduces the HeaderImage to the visual form builder for the Multistep Header template & moves the Header setting control above the Button control.  
Some of the HeaderImage styles require changes to the title and description color, as well as the padding applied to the header. To accommodate this Ive removed the color from theMultistepFormDesign stylesheet so that It can be updated by the HeaderImage styling. For multistep I removed the padding from `.givewp-donation-form__steps-body` so that the appropriate padding could be applied to each `.givewp-layouts-header__templates-ms` modifier. Because this also removes it from the other steps of the form it has also been reapplied to `.givewp-layouts-multiStepForm`. The Donate button is affected too, so changes were applied to …

Feature: add `HeaderImage` to multistep template

---

src/FormMigration/FormMetaDecorator.php
src/FormMigration/ServiceProvider.php
src/FormMigration/Steps/FormFeaturedImage.php
tests/Feature/FormMigration/TestFormMetaDecorator.php

Resolves [GIVE-348]
This PR adds header image migrations for the v2 form templates. Each template uses different data as the headerImage based on the available settings. The default behavior of the designSettingsImageStyle is set to background when an image supplied, so setting an image style is not necessary unless you want to update it.
- Uses the featured image as the default
- Uses the `introduction` image as the default
- Uses the featured image from the WP default setting as a fallback 
- Sets the image style to `center` as this most closely resembles the current way it is displayed on v2 forms
- Uses the `headerBackgroundImage` as the default
- It does NOT use the featured image from the WP default setting as a fallback 
All 3 form templates during the migration process.
In the …

Feature: add form featured image migration step

---

src/EventTickets/Routes/CreateEvent.php
src/EventTickets/ServiceProvider.php

Resolves [GIVE-356](https://stellarwp.atlassian.net/browse/GIVE-356?atlOrigin=eyJpIjoiYTI5YjhlOWNmODU3NDMyNDg5NDg1ZmJmY2Y2Y2MwMDAiLCJwIjoiaiJ9)
This PR adds a new WP Rest Route for creating a new event as a POST request.
Make a POST request to `/wp-json/give-api/v2/events-tickets/events` passing the `title` (string) and `startDateTime` (string as date-time, see RFC3339) and confirm a `201 Created` response.
[GIVE-356]: https://stellarwp.atlassian.net/browse/GIVE-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add endpoint for creating an event

---

src/EventTickets/Repositories/EventRepository.php
src/EventTickets/Routes/UpdateEvent.php
tests/Unit/EventTickets/Routes/UpdateEventTest.php

Resolves GIVE-359
This PR adds a new WP Rest Route for updating an event as a POST, PUT, or PATCH request.
Note: This also resolves a small bug with the `title`, `endDateTime`, and `ticketCloseDateTime` properties when updating an Event.

Feature: Add endpoint for updating an event 

---

src/EventTickets/DataTransferObjects/EventTicketTypeData.php
src/EventTickets/Repositories/EventTicketTypeRepository.php
src/EventTickets/Routes/CreateEventTicketType.php
src/EventTickets/ServiceProvider.php

Resolves [GIVE-365](https://stellarwp.atlassian.net/browse/GIVE-365)
This PR adds a new WP Rest Route for creating a new ticket type for an event as a POST request.
Note: This also resolves a small bug with the `created_at` and `updated_at` timestamps when creating a Ticket Type.
Make a POST request to `/wp-json/give-api/v2/events-tickets/event/{event_id}/ticket-types` passing the `label` (string), `description` (string), `price` (int), and `capacity` (int) and confirm a `201 Created` response.
[GIVE-365]: https://stellarwp.atlassian.net/browse/GIVE-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add endpoint for creating a ticket type for an event

---

src/EventTickets/Routes/GetEventForms.php
src/EventTickets/ServiceProvider.php
tests/Unit/EventTickets/Routes/GetEventFormsTest.php

Resolves [GIVE-363](https://stellarwp.atlassian.net/browse/GIVE-363)
This PR adds a new WP Rest Route for listing forms related to an event as a GET request.
Note: A event related form is identified by the contents of the JSON `formBuilderFields` column. JSON related MySQL functionality is not introduced until `MySQL 5.7`, but GiveWP supports back to `MySQL 5.5`. For this reason, this endpoint uses `whereLike` queries to determine if a form contains an event block.
[GIVE-363]: https://stellarwp.atlassian.net/browse/GIVE-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add endpoint for event forms

---

assets/src/js/frontend/paypal-commerce/index.js

Resolves [GIVE-352]
This resolves the PayPal Donations and Legacy donation form template modal view compatibility issue.
[GIVE-352]: https://stellarwp.atlassian.net/browse/GIVE-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Display PayPal Donations methods in legacy form template in modal view

---

src/EventTickets/Actions/EnqueueEventDetailsScripts.php
src/EventTickets/Actions/EnqueueListTableScripts.php
src/EventTickets/Actions/RegisterEventsMenuItem.php
src/EventTickets/ServiceProvider.php

This PR co-locates submenu scripts with the render method.
The benefit here is that the logic of which script is getting enqueued is in a single place with the render of the submenu, which is where you would look to debug an issue - as opposed to having multiple enqueue actions that may or may not enqueue a script.
This also greatly simplifies the `isShowing()` logic, since most of the check is no longer necessary. 
And the enqueue actions themselves are now only responsible for enqueuing scripts and styles - and not responsible for determining if the script should or should not be enqueued.

Refactor: Co-location submenu scripts with render

---

src/EventTickets/Actions/EnqueueFormBuilderScripts.php
src/EventTickets/resources/admin/components/CreateEventModal/index.tsx
src/EventTickets/resources/admin/components/EventTicketsListTable/index.tsx
src/EventTickets/resources/admin/event-details.tsx

This pull request updates our code to include recent changes made to the query parameters. The deep link to automatically trigger the create event modal is now `edit.php?post_type=give_forms&page=give-event-tickets&new=event`.

Refactor: Update deep link for create event modal

---

includes/gateways/stripe/includes/give-stripe-helpers.php
src/PaymentGateways/Gateways/Stripe/Actions/CreatePaymentIntent.php

Stripe made changes to how statement descriptors are used in Payment Intents for cards: https://support.stripe.com/questions/use-of-the-statement-descriptor-parameter-on-paymentintents-for-card-charges 
This breaking change affects new Stripe accounts, but prevents donations from working, as such it’s high priority.
Note: I did not change the descriptor for anything other than Payment Intents with `card` as the `payment_method_types` as that's the only scenario affected by the change.
Donations processing a credit card using Stripe
1. Test a v2 form using a credit card with Stripe
2. Test a v3 form using a credit card with Stripe
In both cases, check the descriptor in the Stripe dashboard to make sure it's present and looks good.
- …

Fix: Update Stripe statement descriptor usage per API changes

---

includes/admin/donors/class-donor-table.php

Resolves [GIVE-244]
This PR implements escape good practices intended to improve code quality.
[GIVE-244]: https://stellarwp.atlassian.net/browse/GIVE-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhancement: escape later

---

src/EventTickets/Actions/EnqueueEventDetailsScripts.php
src/EventTickets/resources/admin/components/EventDetailsPage/DonationFormsSection/index.tsx
src/EventTickets/resources/admin/components/EventDetailsPage/EventDetailsPage.module.scss
src/EventTickets/resources/admin/components/EventDetailsPage/EventSection/EventSection.module.scss
src/EventTickets/resources/admin/components/EventDetailsPage/EventSection/EventSectionRowActions.tsx
src/EventTickets/resources/admin/components/EventDetailsPage/EventSection/index.tsx
src/EventTickets/resources/admin/components/EventDetailsPage/TicketTypesSection/index.tsx
src/EventTickets/resources/admin/components/EventDetailsPage/index.tsx
src/EventTickets/resources/admin/components/EventDetailsPage/types.ts
src/EventTickets/resources/admin/components/EventTicketsListTable/index.tsx
src/EventTickets/resources/admin/components/EventTicketsListTable/types.ts
src/EventTickets/resources/admin/event-details.tsx
src/EventTickets/resources/date-fns-locale.ts

Resolves [GIVE-360]
This pull-request adds the basic structure for the Event Details page, including the event card and initial scaffold for the other sections.
- The Delete Confirmation Modal is currently part of the List Table and requires to be re-implemented here so to speed up development, I'm temporarily replacing it with a native `confirm` prompt.
- Ability to edit an event will be part of another PR.
- Global notifications area still to be implemented.
- Loader while processing an AJAX request still to be implemented.
-   [x] [Self …

Feature: Add Event Details page with Event Card

---

src/EventTickets/Actions/AttachAttendeeNamesToTicketData.php
src/EventTickets/Routes/GetEventTickets.php
tests/Unit/EventTickets/Routes/GetEventTicketsTest.php

Resolves [GIVE-395](https://stellarwp.atlassian.net/browse/GIVE-395)
This PR adds the attendee name to tickets returned by the `events-tickets/event/{event_id}/tickets` endpoint.
Attendee names are donor names of the donation associated with tickets.
[GIVE-395]: https://stellarwp.atlassian.net/browse/GIVE-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Add attendee name to ticket endpoint

---

src/EventTickets/resources/templates/EventTickets/EventTicketsListHOC.tsx

This PR adds a `null` check before accessing a property of the Currency Settings, which may not be defined when Currency Switcher is disabled.
| Before |
| --- |
| ![image](https://github.com/impress-org/givewp/assets/10858303/50fbabfe-8f5f-407d-b579-fd68d2ce9ba4) |
| After |
| --- |
| ![image](https://github.com/impress-org/givewp/assets/10858303/972a2f9f-8b98-4f37-9df0-1f3ee937e0e0) |
Disable Currency Switcher and load the donation form.

Fix: Prevent error in Event Field when Currency Switcher is disabled

---

src/EventTickets/Models/Event.php
src/EventTickets/ViewModels/EventDetails.php
tests/Unit/EventTickets/ViewModels/EventDetailsTest.php

Resolves [GIVE-404](https://stellarwp.atlassian.net/browse/GIVE-404)
This PR adds the `EventDetails` View Model for formatting data to be localized to the event details page.
Additionally, a new `forms` relationship has been added to the `Event` model.
```php
class EnqueueEventDetailsScripts
{
public function __invoke(Event $event)
{
$eventDetails = new EventDetails($event);
$data = [
//
'event' => $eventDetails->exports(),
];
}
}
```
[GIVE-404]: https://stellarwp.atlassian.net/browse/GIVE-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add event details view model

---

src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/css/_container.scss
src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/css/_header.scss
src/DonationForms/resources/app/form/Header.tsx
src/DonationForms/resources/propTypes.ts
src/DonationForms/resources/registrars/templates/layouts/Header.tsx
src/DonationForms/resources/styles/design-settings/image.scss

Resolves [GIVE-150]
This PR includes the necessary changes to accommodate the header image while using the 2-panel layout.
Additional changes include:
- Remove margin from container that was clipping the border-radius on the form.
- Remove media max-width on the header panel as it was applying in the canvas but not on the frontend resulting in inconsistent views.
- Replace border-radius in design settings stylesheet with `--givewp-rounded-8`
HeaderImage design setting
https://github.com/impress-org/givewp/assets/75056371/51874de2-7377-46ce-9ed7-253db0e6c016
- Create a form in the visual form builder
- Set layout to two-panel
- Upload a header image
-  Test all 3 image styles
- Toggle the various header settings to ensure the layout does not break
- Verify previous layouts do not break
- …

refactor: accommodate header image for 2-panel layout

---

src/ServiceProviders/LegacyServiceProvider.php

This has apparently been here for a while, but hasn't caused an issue because it is only declared in a `use` statement. But for some reason, an Event Tickets PR is starting to throw an error during static analysis.

Fix: Remove prefixed phpstan class

---

src/EventTickets/resources/templates/EventTickets/EventTicketsListHOC.tsx

Resolves [GIVE-436]
This PR adds the quantity per ticket type to the string shown in the Donation Summary.
[GIVE-436]: https://stellarwp.atlassian.net/browse/GIVE-436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: show quantity per ticket type in the donation summary

---

src/EventTickets/resources/admin/components/EventDetailsPage/EventSection/EventSection.module.scss
src/EventTickets/resources/admin/components/EventDetailsPage/EventSection/index.tsx

Resolves [GIVE-265]
This PR implements a CSS to keep row actions always visible in the Event details table.
Tables on the Event details page
[GIVE-265]: https://stellarwp.atlassian.net/browse/GIVE-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Ensure event details row actions are always visible.

---

src/EventTickets/ListTable/Columns/SalesAmountColumn.php
src/EventTickets/ListTable/Columns/SalesCountColumn.php
src/EventTickets/Routes/DeleteEventsListTable.php
src/EventTickets/resources/admin/components/EventTicketsListTable/EventTicketsRowActions.tsx

Resolves [GIVE-422]
This PR adds an initial implementation for preventing events that has tickets generated from being deleted. Two main actions has been taken: (1) Added an alert when clicking the delete button and (2) added a validation to the API route to ignore those events with tickets.
In the future, add an informative modal to explain why the event cannot be deleted.
[GIVE-422]: https://stellarwp.atlassian.net/browse/GIVE-422?atlOrigin=eyJpIjoiNWRkNTlj …

Feature: prevent some events from being deleted

---

src/EventTickets/Actions/EnqueueFormBuilderScripts.php
src/EventTickets/Routes/DeleteEventTicketType.php
src/EventTickets/ServiceProvider.php
src/EventTickets/resources/admin/components/EventDetailsPage/TicketTypesSection/TicketTypesRowActions.tsx
src/EventTickets/resources/admin/components/EventDetailsPage/TicketTypesSection/index.tsx
src/EventTickets/resources/admin/components/api.ts

Resolves [GIVE-441]
This PR implements the ability to delete ticket types from the event details page unless they have tickets generated from them.
In the future, add an informative modal to explain why the event cannot be deleted.
[GIVE-441]: https://stellarwp.atlassian.net/browse/GIVE-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: add ability to delete ticket types

---

src/EventTickets/resources/admin/components/EventDetailsPage/TicketTypesSection/index.tsx
src/EventTickets/resources/admin/components/TicketTypeFormModal/index.tsx
src/EventTickets/resources/components/EventTicketsListItem.tsx
src/EventTickets/resources/templates/EventTickets/styles.scss

Resolves [GIVE-435]
This PR changes the capacity field on Event Ticket Types to be required. This is necessary while we don't fully introduce the concept of _Unlimited_ capacity.
[GIVE-435]: https://stellarwp.atlassian.net/browse/GIVE-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: change capacity field to be required

---

changelog.txt
give.php
readme.txt
src/DonationForms/Blocks/DonationFormBlock/resources/app/Components/ModalForm.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/common/FormModal/index.tsx
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-290]
This PR fixes the problem by submitting the `'give-cs-form-currency'` value when creating a PayPal order through a v3 form, this is necessary because the Currency Switcher add-on relies on this information to apply the proper currency.
The PayPal Donations gateway.
Before testing the fix, I suggest to reproduce the error like in this demo video: https://www.loom.com/share/24c00e60c1c3472d9c8126ff424ef66d?sid=2f0e1fed-38e2-4e80-b07b-83c973a466eb
Then, pull this branch and follow this instructions:
1. Create a V3 form with the Currency Switcher add-on enabled.
2. Select a different currency from the base one.
3. Create a test donation with PayPal Donations.
4. On the PayPal side, make sure that the proper currency (selected in step 2) is applied. …

Fix: PayPal Donations does not work with switch currency on V3 Forms

---

assets/src/css/admin/settings.scss

Resolves [GIVE-470]
This pull request fixes some issues related to margins and alignments in the Beta Features tab.
Beta Features tab
| Before |
| ------ |
| ![Before Image](https://github.com/impress-org/givewp/assets/3921017/3946f13a-1987-445b-baa4-f88ea4a89f4a) |
| After |
| ------ |
| ![CleanShot 2024-03-13 at 18 59 04](https://github.com/impress-org/givewp/assets/3921017/93e7bcb5-4902-4ccf-bc08-bdd0789dc1e8) |
[GIVE-470]: …

Fix: enhance margins and alignments on Beta Features tab

---

src/EventTickets/resources/templates/EventTickets/styles.scss

Resolves [GIVE-460]
This pull request resolves an issue where long descriptions for ticket types caused the quantity input to overflow the box. The problem stemmed from setting the `flex-basis` property to `auto`, which expands to accommodate content. To fix this, the `flex-basis` property was changed to `0`, and a gap was introduced between the description text and the quantity input.
| Before |
| ------ |
| ![CleanShot 2024-03-21 at 20 20 26](https://github.com/impress-org/givewp/assets/3921017/8aa0c2eb-518f-403e-a215-217832118d7d) |
| After |
| ------ |
| ![CleanShot 2024-03-21 at 20 13 20](https://github.com/impress-org/givewp/assets/3921017/86027786-25f9-42bd-a5ba-acc4168c7ac8) |
-   [ ] Relevant `@unreleased` tags …

Fix: Quantity input overflow in Ticket Types with long descriptions

---

assets/src/css/admin/settings.scss
src/EventTickets/resources/admin/components/EventFormModal/index.tsx

Resolves [GIVE-399]
This PR adds a placeholder to the event description field in the Event Form Modal to help users understand its purpose.
Create/Edit event modal
[GIVE-399]: https://stellarwp.atlassian.net/browse/GIVE-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Add placeholder to event description field

---

src/EventTickets/Actions/ConvertEventTicketsBlockToFieldsApi.php
src/EventTickets/Fields/EventTickets.php
src/EventTickets/resources/blocks/EventTicketsBlock/Edit/BlockPlaceholder.tsx
src/EventTickets/resources/blocks/EventTicketsBlock/Edit/styles.scss
src/EventTickets/resources/blocks/EventTicketsBlock/types.ts
src/EventTickets/resources/components/EventTicketsHeader.tsx
src/EventTickets/resources/components/EventTicketsListItem.tsx
src/EventTickets/resources/components/types.ts
src/EventTickets/resources/templates/EventTickets/index.tsx
src/EventTickets/resources/templates/EventTickets/styles.scss
tests/Unit/EventTickets/Actions/ConvertEventTicketsBlockToFieldsApiTest.php

Resolves [GIVE-353]
This pull request adds some badges to the EventTickets template. The <kbd>**Sold Out**</kbd> badge appears on each line for tickets when none are available. The <kbd>**ENDED**</kbd> badge is displayed in the header once the event end date has passed. Under these conditions, no tickets are shown for sale.
EventTickets template
[GIVE-353]: https://stellarwp.atlassian.net/browse/GIVE-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

Feature: add badges to field template

---

src/EventTickets/ListTable/Columns/DescriptionColumn.php
src/EventTickets/resources/admin/components/EventDetailsPage/SectionTable/SectionTable.module.scss
src/EventTickets/resources/admin/components/EventTicketsListTable/EventTicketsListTable.module.scss
src/EventTickets/resources/admin/components/EventTicketsListTable/index.tsx

Resolves [GIVE-465]
This pull request truncates long event descriptions in the events list table by using the still new `line-clamp` property in CSS to restrict them to 2 lines. Additionally, a maximum of 200 characters is set as a fallback to ensure the description length is limited.
Event List Table
[GIVE-465]: https://stellarwp.atlassian.net/browse/GIVE-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: truncate event description on events list table

---

src/FormMigration/FormMetaDecorator.php
src/FormMigration/Steps/Mailchimp.php
tests/Feature/FormMigration/Steps/TestMailchimp.php

Resolves # [GIVE-447]
This PR includes unit tests on the form migration process for the Mailchimp add-on. Three tests were added that check when migrating a form that uses the global settings, migrating a form that has per-form settings & migrating a form without meta.
The tests revealed some areas of improvement within the Mailchimp migration process & adjustments were made to accommodate them.
- The double optin setting is limited to global settings through`give_mailchimp_double_opt_in`. The method checking the form meta for this option in the decorator has been removed.
- In the decorator the meta key for `_give_mailchimp_send_donation` has been updated to `_give_mailchimp_send_donation_data`
- Previously an array was used as the default for subscriber tags. The subscriber tag setting …

Feature: add mailchimp form migration unit tests

---

src/FormBuilder/resources/js/form-builder/src/components/sidebar/Secondary.tsx
src/FormBuilder/resources/js/form-builder/src/containers/BlockEditorInterfaceSkeletonContainer.tsx

Resolves # [GIVE-536]
When opening the build section of the visual form builder we want the left sidebar menu set to open automatically as a way to ensure users can easily find new blocks to add. 
The state that manages which sidebar is open can be found as `selectedSecondarySidebar` in the BlockEditorInterfaceSkeletonContainer component. This state manages both the list view and the block menu.
This PR applies the name of the sidebar `add` as a default for the open state that manages the secondary sidebar which will ensure that the block menu is open when selecting the build preview section.
Additionally an unused import was removed.
- Visual Form Builder
- Sidebars
https://github.com/impress-org/givewp/assets/75056371/d6c98520-2726-476c-9fb9-ee2081ae15e2
- Select the …

Refactor: automatically open sidebar block menu on build preview

---

includes/admin/donors/donor-actions.php
includes/admin/donors/donors.php
includes/misc-functions.php
src/Donors/Actions/UpdateAdminDonorDetails.php
src/Donors/DataTransferObjects/DonorQueryData.php
src/Donors/Factories/DonorFactory.php
src/Donors/Migrations/AddPhoneColumn.php
src/Donors/Migrations/addPhoneColumn.php
src/Donors/Models/Donor.php
src/Donors/Repositories/DonorRepository.php
src/Donors/ServiceProvider.php
tests/Unit/Donors/Models/TestDonor.php
tests/Unit/Donors/Repositories/TestDonorRepository.php

Resolves [GIVE-531]
This PR adds a phone input to the donor profile page. The [International Telephone Input JS library (sponsored by Twilio)](https://github.com/jackocnr/intl-tel-input) was used to make sure that the numbers were stored in the proper format regardless of the donor country.
The big advantage of using this JS library is that we can validate the numbers for all countries before submitting the form and store the donor phone number using the international format - which can be useful in the future if we decide to implement some kind of integration with 3rd party software to send SMS to donors because services like that (For example Twilio) require numbers in the international format.
The whole functionality was encapsulated in the `give_get_intl_tel_input()` function, this …

Feature: add phone number to donor profile

---

src/FormBuilder/Routes/EditFormRoute.php

This PR resolves the issue that happens when using edit bulk action to edit WP posts or pages. The problem was that our action to get the v3 form edit URL was also triggered by the WP edit bulk action. Since WP sends an array of IDs for edit bulk action and we don't need that, the issue is resolved by adding a conditional check where we check if the `$_GET['post']` variable is an array.
WP edit bulk action for posts, pages, etc.
Go to posts or pages, select them all, and try to edit them using the edit bulk action. Everything should work as expected. Also, keep an eye on the error log. Servers that run PHP8 will throw an error, so make sure you test this on a server that runs PHP8. 
-   [x] [Self …

Fix: WP edit bulk action

---

give.php
readme.txt
src/FormBuilder/resources/js/form-builder/src/containers/BlockEditorContainer.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss

Resolves [GIVE-583]
This pull request introduces a hotfix for an incompatibility issue between Visual Form Builder and WordPress 6.5. Previously, any modification to a block resulted in a re-render. Upon investigation, I discovered this was caused by a function designed to ensure all blocks reside within a section block. However, this function was triggering a change to the form state on every modification. This pull request now verifies whether a change causes a block to be placed outside of a section block; if not, it simply ignores the remainder of the function.
Visual Form Builder
1. Create/Open a form in the VFB
2. Edit any block attribute
3. Confirm the block remains selected
4. Move a block to be placed outside of a section block
5. Confirm a section block is automatically created …

Hotfix: Resolve incompatibility issue with WP 6.5

---

src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss

Resolves [GIVE-600]
The form builder sidebar tabs have been visually compromised after updated to WP 6.5. This PR preserves the backwards compatible styles.  
For context, it appears the new version of Gutenberg updated some styles which affected this.  To preserve those styles I went back a version to grab what we were relying on and updated our own stylesheet.
The form builder sidebar tab styles
**WP 6.5**
**WP 6.4**
**WP 6.3**
- Install WP 6.5
- Use this branch / [zip](https://github.com/impress-org/givewp/actions/runs/8572917571) to check the form builder sidebar tabs
- Check on a couple previous WP versions as well.
-   [ ] Reviewed …

Fix: form builder sidebar tabs for WP 6.5 compatibility

---

src/EventTickets/Routes/CreateEvent.php
src/EventTickets/Routes/CreateEventTicketType.php
src/EventTickets/Routes/DeleteEventTicketType.php
src/EventTickets/Routes/DeleteEventsListTable.php
src/EventTickets/Routes/GetEventForms.php
src/EventTickets/Routes/GetEventTicketTypeTickets.php
src/EventTickets/Routes/GetEventTicketTypes.php
src/EventTickets/Routes/GetEventTickets.php
src/EventTickets/Routes/GetEvents.php
src/EventTickets/Routes/GetEventsListTable.php
src/EventTickets/Routes/UpdateEvent.php
src/EventTickets/Routes/UpdateEventTicketType.php
tests/Unit/EventTickets/Routes/CreateEventTest.php
tests/Unit/EventTickets/Routes/CreateEventTicketTypeTest.php
tests/Unit/EventTickets/Routes/DeleteEventTicketTypeTest.php
tests/Unit/EventTickets/Routes/DeleteEventsListTableTest.php
tests/Unit/EventTickets/Routes/UpdateEventTest.php
tests/Unit/EventTickets/Routes/UpdateEventTicketTypeTest.php

Resolves [GIVE-371]
This pull request improves Event Tickets API routes by enhancing permission checks and validations to prevent invalid requests from reaching the handler. Additionally, it includes unit tests that cover various edge cases, that ran through the actual API system with the `RestApiTestCase`.
Event Tickets API routes
[GIVE-371]: https://stellarwp.atlassian.net/browse/GIVE-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

Refactor: Improve Event Tickets API validations

---

src/DonationForms/Blocks/DonationFormBlock/resources/editor/hooks/useFormOptions.ts

Resolves [GIVE-487]
The Donation Form block currently displays only the last 10 donation forms. This pull request increases the limit to 100, aiming to cover most cases effectively.
[Read more](https://lw.slack.com/archives/C04SLRDD9CK/p1712000947705309)
Donation Form block
[GIVE-487]: https://stellarwp.atlassian.net/browse/GIVE-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Enhance Donation Form block to display up to 100 forms

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/inspector/index.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/settings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/types.ts

Resolves: https://stellarwp.atlassian.net/jira/software/c/projects/GIVE/boards/382?selectedIssue=GIVE-620
- Add descriptions to amount block attributes
- Add type for descriptions
- Pass new data to the OptionsPanel component.
https://github.com/impress-org/form-builder-library/pull/7
Donation Amount Block Settings

Feature: update amount block settings with descriptions

---

src/DonationForms/V2/DonationFormsAdminPage.php
src/FormMigration/FormMetaDecorator.php
src/FormMigration/ServiceProvider.php
src/FormMigration/Steps/DoubleTheDonation.php
tests/Feature/FormMigration/Steps/TestDoubleTheDonation.php
tests/Feature/FormMigration/TestFormMetaDecorator.php

Resolves: [GIVE-497]
This PR adds the Double The Donation migration step.
Form migration
Create a V2 form with Company Matching enabled
Upgrade form to V3
DTD block should be added to V3 from
Now repeat the process with the Company Matching disabled
DTD block should not be added to V3 from
[GIVE-497]: https://stellarwp.atlassian.net/browse/GIVE-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add Double The Donation migration step

---

src/EventTickets/Actions/AddEventTicketsToDonationConfirmationPageDonationTotal.php
src/EventTickets/Actions/GenerateTicketsFromPurchaseData.php
src/EventTickets/Factories/EventTicketFactory.php
src/EventTickets/ListTable/Columns/SalesAmountColumn.php
src/EventTickets/Migrations/AddAmountColumnToEventTicketsTable.php
src/EventTickets/Models/EventTicket.php
src/EventTickets/Repositories/EventTicketRepository.php
src/EventTickets/ServiceProvider.php

Resolves [GIVE-475]
We were relying on the ticket type prices as the ticket amount but then realized they could change, affecting calculations. This pull request refactors the ticket entity by adding a new `amount` property.
Changes made:
-  Added a migration to include the amount column in the `give_event_tickets` table.
-  Added a migration to transfer price values to the new column.
-  Updated `EventTickets` model, repository, and factory to accommodate the amount property.
-  Updated `AddEventTicketsToDonationConfirmationPageDonationTotal` action to use the amount property.
-  Updated `GenerateTicketsFromPurchasedData` action to save the ticket price as the amount for the new ticket.
-  Updated the `SalesAmount` column in the `EventTicketsListTable` to calculate from the amount …

Refactor: Store ticket type price in the generated ticket

---

src/EventTickets/Routes/UpdateEvent.php
src/EventTickets/resources/admin/components/EventDetailsPage/TicketTypesSection/TicketTypesRowActions.tsx
src/EventTickets/resources/admin/components/EventDetailsPage/TicketTypesSection/index.tsx
src/EventTickets/resources/admin/components/TicketTypeFormModal/index.tsx
src/EventTickets/resources/admin/components/TicketTypeFormModal/parseValueFromLocale.ts
src/EventTickets/resources/admin/components/TicketTypeFormModal/types.ts

Resolves [GIVE-463]
This pull request enhances Event Tickets creation/edition by replacing the default number input with a custom component designed for handling currency values.
Event Ticket create/edit modal
[GIVE-463]: https://stellarwp.atlassian.net/browse/GIVE-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Replace ticket price input with a currency input

---

src/DonationForms/Actions/ConvertDonationAmountBlockToFieldsApi.php
src/FormBuilder/Actions/GenerateDefaultDonationFormBlockCollection.php
src/FormBuilder/BlockModels/DonationAmountBlockModel.php
src/Framework/FieldsAPI/Amount.php
tests/Unit/Actions/GenerateDefaultDonationFormBlockCollectionTest.php

Resolves: [GIVE-644]
This PR updates the DonationAmount block model & node conversion so that both the descriptions & descriptionsEnabled attributes can be used in the UI
Block Model
Node Conversion
[GIVE-644]: https://stellarwp.atlassian.net/browse/GIVE-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: update amount node conversion with descriptions & descriptionsEnabled

---

src/FormMigration/Steps/DonationOptions.php
tests/Feature/FormMigration/Steps/TestDonationOptions.php

Resolves [GIVE-668]
Update the DonationOptions step in Form Migrations to align with the new donation levels schema, and migrate the level description accordingly.
DonationOptions migration from v2 to v3 forms
https://github.com/impress-org/givewp/assets/3921017/20380bde-83c7-4311-afe0-05bb79a3c043
1. Create a v2 form using donation levels.
2. Migrate that form to v3.
3. Confirm that levels have been migrated properly.
[GIVE-668]: …

Refactor: Change v2 to v3 migration to include level descriptions

---

src/DonationForms/resources/registrars/templates/fields/Amount/DonationAmountLevels.tsx
src/DonationForms/resources/registrars/templates/fields/Amount/index.tsx
src/DonationForms/resources/styles/components/_amount.scss
src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/types.ts

Resolves [GIVE-626]
Update the `DonationAmountLevels` component to include levels with descriptions. Display a group of levels with descriptions first, followed by the remaining ones.
If no levels have descriptions, show all options in a grid. If at least one level has a description, present the flexible interface below.
It is important to note that these groups respect the order set in the admin, but within each group.
Donation Amount Levels template
https://github.com/impress-org/givewp/assets/3921017/0c2ea793-1f4b-4d39-bce7-d70971d92a16
_Variations with 4, 3, 2, 1 and 0 remaining options with no description_
_Same options from above but after disabling descriptions_
1. Enable Donation Levels in VFB.
2. Ensure the Donation Form resembles the current design.
3. Return to VFB, activate …

Refactor: Update DonationAmountLevels template to support descriptions

---

src/FormBuilder/resources/js/form-builder/src/styles/_components.scss

Resolves [GIVE-645]
This pull-request fixes a visual issue with the recurring labels in the VFB. After the recent WordPress updates, they were no longer filling all the available space.
Recurring labels on VFB
| --- | --- |
| ![CleanShot 2024-04-22 at 11 03 59](https://github.com/impress-org/givewp/assets/3921017/50ae89c4-0d96-436d-be05-4ba5cc645fc3) | ![CleanShot 2024-04-22 at 11 09 03](https://github.com/impress-org/givewp/assets/3921017/dc2f98d4-5316-4aee-b8fc-33b053afed7a) |
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-review …

Fix: Set recurring labels width on VFB

---

src/PaymentGateways/PayPalCommerce/AdminSettingFields.php

Resolves [GIVE-575]
This pull-request updates the support phone number shown in error message where there are connectivity issues.
PayPal error messages
Go to PayPal settings, click to connect to PayPal Live, select one option, then click the Confirm button. Once PayPal page is loading, close it. The error must now be shown for you with the updated phone number.
[GIVE-575]: https://stellarwp.atlassian.net/browse/GIVE-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

Refactor: Update phone number for contact.

---

src/DonationForms/resources/propTypes.ts
src/DonationForms/resources/registrars/templates/fields/Amount/getAmountLevelsWithCurrencySettings.tsx
src/DonationForms/resources/registrars/templates/fields/Amount/index.tsx
src/DonationForms/resources/registrars/templates/fields/Amount/withCurrencySettings.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/inspector/index.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/types.ts

This pull request updates the integration for Donation Amount Levels with Currency Switcher. The schema has been changed from an array of numbers to an array of objects. It also updates some remaining prop types.
Currency Switcher on Amount Levels
https://github.com/impress-org/givewp/assets/3921017/cebbc381-7990-4cbf-b788-55e6bc2d5a85
1. Configure Currency Switcher and Donation Levels
2. Make sure they still work as expected.

Fix: Update Currency Switcher integration

---

src/DonationForms/resources/styles/components/_amount.scss
src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/inspector/index.tsx

Resolves [GIVE-700]
This pull request sets a limit for level descriptions to 120 characters. Additionally, levels are now styled in a way that for long descriptions, their buttons are top-aligned.
FYI: In this PR, we are only setting the max length. All related code has been added to the `OptionsPanel` component as that's the responsible for controlling that.
Amount level descriptions
[GIVE-700]: https://stellarwp.atlassian.net/browse/GIVE-700?atlOrigin=eyJpI …

Refactor: limit description length to 120 chars and re-style them

---

includes/class-give-donate-form.php
includes/forms/template.php

This PR adds sanitization to give_form shortcode args.
Legacy form template
Install and activate plugin Give
Admin create at least 1 Form with the type "Legacy Form"
Create new Post and add shortcode 
`[give_form id="13721" display_style='abcdef"onmouseover=alert(123) b=']`
Replace id by your form id
Open post and move mouse on button

Fix: sanitize give_form shortcode args

---

src/Views/Admin/DashboardWidgets/Reports.php

Fix: The **Reports Dashboard Widget** was not displayed translated
Before (Language set to Italian)
After (Language set to Italian)

Fix: The Reports Dashboard Widget was not displayed translated

---

src/Promotions/WelcomeBanner/WelcomeBanner.php

Fix: The "**Welcome Banner**" was not displayed translated
Before (Language set to Italian)
After (Language set to Italian)

Fix: The "Welcome Banner" was not displayed translated

---

src/DonorDashboards/Block.php

Fix: The "**Donor Dashboard**" block was not displayed translated
Before (Language set to Italian)
After (Language set to Italian)

Fix: The "Donor Dashboard" block was not displayed translated

---

src/DonationForms/DataTransferObjects/DonationFormGoalData.php
src/DonationForms/DonationQuery.php
src/DonationForms/Repositories/DonationFormRepository.php
src/DonationForms/ViewModels/DonationFormViewModel.php

Resolves GIVE-677
This PR updates the donation goal and the donation stats for the Donation Form to use a new `DonationQuery`, which supports a date range and accounts for recovered fees.
- Adds a new `DonationQuery` class to account for recovered fees.
- Adds new goal settings to the `DonationFormGoalData` DTO.
- Updates the `getTotalRevenue` method with the `DonationQuery`.
- Adds a new `getTotalRevenueForDateRange` method to the repository.
- Updates the `getTotalNumberOfDonations` method with the `DonationQuery`.
- Adds a new `getTotalNumberOfDonationsForDateRange` method to the repository.
- Updates the `formStatsData` array to use the `DonationQuery`.

Refactor: Update goal/stats to use Donation Query

---

includes/class-give-donate-form.php

This PR is an addition to https://github.com/impress-org/givewp/pull/7375
In the previous PR, sanitization is added to input args only, but that won't be enough if the malicious code is already saved in the database. To fix this, sanitization of the data before output is also added.
`give_form` shortcode
Install and activate Give
Create a form using  "Legacy Form" template
Create a new Post and add a shortcode
`[give_form id="13721" display_style='abcdef"onmouseover=alert(123) b=']`
Replace id with form id
Open the post and move the mouse on the button

Fix: sanitize shortcode atts

---

includes/shortcodes.php
src/DonationForms/DonationQuery.php
src/MultiFormGoals/ProgressBar/Model.php
templates/shortcode-goal.php

This PR updates all form goal blocks/shortcodes to respect the new v3 fields/queries. 
`[give_goal]` shortcode is updated and now it supports two new arguments `start_date` and `end_date` where the user can set a date range for the goal. 
- Multi-Form Goal block
- [give_goal]
- [give_multi_form_goal]
- [give_totals]

Feature: Update all form goal blocks/shortcodes to respect the new v3 fields/queries

---

src/DonationForms/DataTransferObjects/DonationFormGoalData.php
src/DonationForms/DonationQuery.php
src/DonationForms/Repositories/DonationFormRepository.php
src/DonationForms/SubscriptionQuery.php

Instead of supporting new repository methods, this PR simplifies the goal data to use the new `DonationQuery` directly.
I noticed that each update required a check for all-time vs custom and then an additional `*ForDateRange()` method. This instantiates the query and conditionally sets the start/end values.
Each type of value then completes the query.
`GoalType::DONATIONS()` calls `$query->count()`.
`GoalType::DONORS()` calls `$query->countDonors()`.
`GoalType::AMOUNT()` calls `$query->sumIntendedAmount()`.

Refactor: Simplify goal data to use query builder directly

---

includes/shortcodes.php
src/DonationForms/DataTransferObjects/DonationFormGoalData.php
src/DonationForms/DonationQuery.php
src/DonationForms/Properties/FormSettings.php
src/DonationForms/Repositories/DonationFormRepository.php
src/DonationForms/SubscriptionQuery.php
src/DonationForms/ValueObjects/GoalProgressType.php
src/DonationForms/ViewModels/DonationFormViewModel.php
src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php
src/FormBuilder/ServiceProvider.php
src/FormBuilder/ViewModels/FormBuilderViewModel.php
src/FormBuilder/resources/js/form-builder/src/common/getWindowData.ts
src/FormBuilder/resources/js/form-builder/src/components/DatePicker/index.tsx
src/FormBuilder/resources/js/form-builder/src/components/DatePicker/styles.scss
src/FormBuilder/resources/js/form-builder/src/components/canvas/DesignPreview.tsx
src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/donation-goal/index.tsx
src/FormBuilder/resources/js/form-builder/src/types/formSettings.ts
src/MultiFormGoals/ProgressBar/Model.php
templates/shortcode-goal.php
tests/Unit/ViewModels/FormBuilderViewModelTest.php

This PR introduces time based form goals for the Visual Donation Form Builder, which includes a new "custom" settings (as opposed to "all time") with support for amount goals, donor goals, and donation goals with support for recurring donations.
Query results for all goal types have been updated, including Amount Raised, Donation Count, Donor Count, Subscription Initial Amount, Subscription Count, and Subscriber Count.
The new time-based settings are implemented using a new `DonationQuery` (and related `SubscriptionQuery`. These new query classes are opinionated extensions of the `QueryBuilder` with a fluid syntax designed for goal settings.
Notably, the `DonationQuery` supports calculating a sum of the _intended amount_, which takes into account support for fee recovery and calculates …

Feature: Time Based Form Goals

---

includes/admin/tools/export/export-functions.php
includes/admin/tools/export/give-export-donations-exporter.php
includes/admin/tools/export/give-export-donations-functions.php
src/Exports/DonorsExport.php

Resolves [GIVE-771]
These changes update the donation and donor exports with a "Donor Phone Number" column.
1. Donor exports will export the donors phone number which can be viewed and edited through the Donor admin screen.
Saved in `give_donor` under `phone`
2. Donation exports will export the Donor Phone Number field made on a donation and can be found in the Donation admin screen under Donor Details. Saved in `give_donationmeta` under `_give_payment_donor_phone`
Reference: https://github.com/impress-org/givewp/pull/7340
Donation & Donor exports
https://github.com/impress-org/givewp/assets/75056371/e0fa1b05-95ff-449f-95e1-b0fdeab6c15b
https://github.com/impress-org/givewp/assets/75056371/743ac9f7-b8d2-4db0-b901-af9798a538cc
- Add Donor Phone Field block
- Process a …

feature: add donor phone number exports

---

src/PaymentGateways/Gateways/Stripe/Traits/CheckoutRedirect.php

Resolves [GIVE-720]
This adds additional escaping to our stripe onboarding
The stripe settings onboarding
N/A
[GIVE-720]: https://stellarwp.atlassian.net/browse/GIVE-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: add additional escaping to stripe onboarding

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementGateway.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/stripePaymentElementGateway.tsx
tests/Feature/Gateways/Stripe/StripePaymentElement/TestStripePaymentElementGateway.php

Resolves: [GIVE-831]
Related (Recurring): https://github.com/impress-org/give-recurring/pull/1205
This updates the Stripe Payment Element gateway to send the billing address details (supplied by the billing address block) to Stripe.
Also note that Stripe recommends using their [address element](https://docs.stripe.com/elements/address-element) that we can also explore
Stripe payment element gateways
- Setup and enable Stripe Payment Element for v3 forms
- Create a v3 form with a billing address block
- Submit donation with Stripe and make sure billing address is supplied to Stripe.
- …

Fix: return donation billing address in Stripe Payment Element Gateway

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/stripePaymentElementGateway.tsx

Resolves [GIVE-345]
This PR fixes the error message that was being displayed in certain cases as `[object Object]` when a donation made with Stripe Element gateway was submitted. Now we are displaying a proper string to indicate the error instead of an object.
The Stripe Element gateway
**Credit Card:**
1. Create a donation and miss any of CC #, expiry, or CVV and press Donate;
2. The new friendly error message will show above the Donate button.
**Google Pay:**
1. Enable Google Pay in your Stripe Dashboard;
2. Create a donation and press Donate, a modal should be opened;
3. Close the Google modal;
4. The new friendly error message will show above the Donate button.
To set up Google Pay in your Chrome for Desktop, check out this link: …

Fix: throw error message instead of the error object when submitting an donation made with Stripe Element gateway

---

src/EventTickets/Actions/ConvertEventTicketsBlockToFieldsApi.php
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-853]
This PR implements a fix for the bug that sends only the donation amount to PayPal and ignores the value of the event tickets associated with the donation. 
**Important:** The fix is exclusive for one-time donations made with PayPal Donations. A subsequent PR in the recurring add-on repository will be necessary for recurring donations made with this same gateway.
One-time donations made with the PayPal Donations gateway.
I recorded a video to discuss a possible fix for it in the recurring donations and in the first minutes I demonstrated the fix implemented by this PR as well. 
Here is the link:
https://www.loom.com/share/8822471d6c5f46429a20a16aafef0627?sid=d5d128aa-d172-47f1-b28a-8074d8083285
1. Connect PayPal Donations;
2. Create an event and attach it to a form;
3. …

Fix: missing event tickets amount for PayPal one-time donations

---

give.php
readme.txt
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-895]
This PR fixes a bug introduced in #7405 which prevents PayPal donations from getting finished when there is no Billing Address block added in the form.
To accomplish that, all we need to do is check if the country field is set, otherwise, we ignore the validations for city, state, and zip fields.
The PayPal Donations
1. Enable PayPal donations
2. Create a V3 form without an address block
3. Create a test donation using the PP smart buttons and make sure it works.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) …

Hot Fix: don't prevent PayPal donations from getting finished when there is no Billing Address block in the form

---

src/FormMigration/FormMetaDecorator.php
src/FormMigration/ServiceProvider.php
src/FormMigration/Steps/CurrencySwitcher.php
tests/Feature/FormMigration/Steps/TestCurrencySwitcher.php
tests/Feature/FormMigration/TestFormMetaDecorator.php
tests/Unit/FormMigration/Steps/CurrencySwitcherTest.php

Resolves [GIVE-679]
This pull request adds a new FormMigration step that migrates Currency Switcher settings from v2 forms to v3.
Form Migration
1. Create a v2 form
2. Customize Currency Switcher settings
3. Migrate that form to v3
4. Ensure the settings have been migrated properly
[GIVE-679]: https://stellarwp.atlassian.net/browse/GIVE-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add migration step for Currency Switcher

---

assets/src/js/admin/reports/widget/index.js
src/Promotions/InPluginUpsells/Endpoints/HideSaleBannerRoute.php
src/Promotions/ReportsWidgetBanner/ReportsWidgetBanner.php
src/Promotions/ReportsWidgetBanner/components/WidgetBanner/index.tsx
src/Promotions/ReportsWidgetBanner/components/WidgetBanner/styles.scss
src/Promotions/ReportsWidgetBanner/hooks/useBannerVisibility.ts
src/Promotions/ReportsWidgetBanner/window/widgetWindow.ts
src/Promotions/ServiceProvider.php

Resolves: [GIVE-866]
This update includes the necessary changes to extend our admin banners to the Reports widget. Similar to the admin banner, it should adhere to similar requirements. The main difference will be that it should only show a single banner to be displayed at a time and does not alternate between options.
URL for report widget: https://go.givewp.com/40sale24
Date range the banner is displayed: July 23rd through July 30th.
Reports Widget
https://github.com/impress-org/givewp/assets/75056371/2cae3700-f04b-44bc-9c9c-aa4358ccddb9
- Visit the WP dashboard.
- Locate the GiveWP widget on the page.
- Verify the banner is displayed and the link takes you to the appropriate page.
- Try closing the banner, it should remain closed.
-   [x] Acceptance criteria satisfied and marked in …

Feature: add Reports widget banner

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/stripePaymentElementGateway.tsx

Resolves [GIVE-843]
This PR fixes the bug that prevents the Stripe Element gateway from working in setups using the API keys connection method. 
Now we are using only `stripeKey` to load the Stripe script (when `stripeConnectedAccountId` is missing) to prevent errors when the account is connected through API keys.
The Stripe Element Gateway
1. In the settings page, connect your Stripe Account using the API key method.
2. Load a V3 form with the Stripe Element gateway and make sure it is loaded and working.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/co …

Fix: make Stripe Element gateway work with the API keys connection method

---

src/DonationForms/resources/styles/_base-overrides.scss

Resolves: [GIVE-815]
The Donor Comment Block had a slightly different `::focus` color around its border when selected. When it should reflect the primary color of the form. The reason for the incorrect color was from a style implemented in the Pico base styles which was overriding its box shadow. To address this I've included the --box-shadow variable required in our base-overrides to ensure the proper color is being used across all forms with high priority.
Donor Comment Block
Text fields
Base styles
- Add the donor comment block and click to focus the element.
- The ::focus border should reflect the primary color, just as the other text fields.
-   [ ] Includes …

refactor: include element focus color in base-overrides

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/terms-and-conditions/GlobalSettingsLink.tsx

Resolves: [GIVE-813]
Some v3 block settings have the option to use global settings for the block. When global settings have been chosen, a link that navigates the user to the blocks settings page is shown. clicking this link can be frustrating if you are editing a form as it will navigate you from the builder to the settings page & you will lose any changes in progress.
The terms & conditions block + the donor name block both have this global setting link. This PR updates the anchor tags target and rel attributes to ensure they open the settings in a new tab. We also update the text within the link to capitalize the g in Global. 
Donor Name Block
Terms & Conditions Block
https://www.loom.com/share/197392b48ef341ae81b0f0535b18461c?sid=9af685c8-f528-43ee-a32c-a6f5f9653e12 …

refactor: ensure global setting links open in a new tab

---

assets/src/css/admin/sale-banners.scss
assets/src/js/admin/reports/widget/index.js
src/Promotions/InPluginUpsells/Endpoints/HideSaleBannerRoute.php
src/Promotions/InPluginUpsells/SaleBanners.php
src/Promotions/InPluginUpsells/StellarSaleBanners.php
src/Promotions/InPluginUpsells/resources/css/stellarwp-sales-banner.scss
src/Promotions/InPluginUpsells/resources/js/sale-banner.js
src/Promotions/InPluginUpsells/resources/views/stellarwp-sale-banner.php
src/Promotions/ReportsWidgetBanner/ReportsWidgetBanner.php
src/Promotions/ReportsWidgetBanner/components/WidgetBanner/index.tsx
src/Promotions/ReportsWidgetBanner/components/WidgetBanner/styles.scss
src/Promotions/ReportsWidgetBanner/hooks/useBannerVisibility.ts
src/Promotions/ReportsWidgetBanner/window/widgetWindow.ts
src/Promotions/ServiceProvider.php
src/Views/Components/ListTable/ProductRecommendations/style.module.scss
webpack.mix.js

Resolves: [GIVE-867]
This includes the Stellar2024 admin banners.
[Feature: add initial banner #7408
](https://github.com/impress-org/givewp/pull/7408)
[Feature: add alternating banners by pricing tier #7412
](https://github.com/impress-org/givewp/pull/7412)
[Feature: add Reports widget banner #7418
](https://github.com/impress-org/givewp/pull/7418)
- Donations, Donors, Reports page.
- Reports widget
- Clear cookies/history in the browser you intend to use. (IMPORTANT)
- Create a new test site & install/activate GiveWP or use a local server.
- Add New Plugin > Upload Plugin > upload the attached file or activate the give plugin.
- Click through the Donations, Donors, and Reports pages.
- Verify the banners alternate between: GiveWP Plus plan & Peer-to-Peer.
- Add a Basic license.
- Click …

Feature: add Stellar2024 banners

---

assets/src/css/plugins/modal.scss
assets/src/js/admin/paypal-commerce/index.js
src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php
src/PaymentGateways/PayPalCommerce/ScriptLoader.php

Resolves [GIVE-854]
This PR adds an option to keep the PayPal webhooks config when disconnecting an account, this way we can keep receiving webhook events, including subscription renewals, from the old account. 
PayPal donations, especially the recurring donations.
Demo video: https://www.loom.com/share/4bd1ad7a2ecc48d4b875f797425ee30e?sid=258ede42-918b-4342-991a-3f989ed22ff1
1. Connect your PayPal sandbox account;
2. Check if the `give_paypal_commerce_sandbox_webhook_config` is present in your DB
3. Disconnect your PayPal sandbox account;
4. Make sure the `give_paypal_commerce_sandbox_webhook_config` keeps present in your DB
To check if the `give_paypal_commerce_sandbox_webhook_config` is present in your DB, use the following query: 
```
SELECT * FROM `wp_options` WHERE `option_name` = …
```

Feature: add a checkbox option to keep the PayPal webhooks after disconnect the account

---

src/DonationForms/resources/styles/elements/_fields.scss
src/FormBuilder/resources/js/form-builder/src/blocks/fields/anonymous/styles.scss

Resolves: [GIVE-814]
This PR introduces style changes to align the description of the anonymous donation checkbox with its label. I've also updated the color and size to match between the Build & Design previews.
Anonymous Donation Checkbox
- add an anonymous donation checkbox to a v3 form.
- check both build & design previews to verify that the bottom description is now aligned with the top label.
[GIVE-814]: …

refactor: improve the styling of the anonymous donation checkbox description

---

includes/admin/tools/views/html-admin-page-system-info.php

Fix: Made strings translatable in html-admin-page-system-info.php file

Fix: Made strings translatable in html-admin-page-system-info.php file

---

src/FormBuilder/resources/js/form-builder/src/blocks/section/styles.scss

Resolves [GIVE-537]
This Main purpose of this PR is to address an issue where the block insertion point indicator is inside of a block.
Block Preview in VFB forms
https://github.com/impress-org/givewp/assets/75056371/74356445-1c3b-4318-9426-e8fd6ef1db5a
- On the build preview select some blocks in the visual form builder.
- Open the left sidebar block inserter menu.
- Hover over a block in the menu.
- Verify the insertion indicator does not display inside of any block.
- Should be tested on the last 3 versions of WordPress, be sure to try all the blocks in the preview.
-   [x] [Self …

Fix: improve block insertion point indicator's position when inserting from the block menu

---

src/DonationForms/resources/styles/components/_gateways.scss

Resolves [GIVE-545]
Currently, even when there is only one payment gateway option in the donation form, the radio button is shown. This does not make much sense in that situation since you cannot switch to any other method.
This pull request adds CSS styles to hide the radio button when the payment gateway is the only one in the list.
Gateways list
_Before_
_After_
_After but having more than 1 option_
1.	Configure more than one payment method in Settings.
2.	Open a form and confirm that all options have radio buttons.
3.	Re-configure the payment methods to have only one active.
4.	Open the form and confirm that when there is only one option, no radio button is shown. …

Refactor: Remove radio button for single active gateway

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/Edit.tsx

Resolves [GIVE-822]
Under certain conditions, due to a combination of Give Recurring settings, a notice is shown below the Amount block in the VFB, representing the same message users will see in the Donation Form. This notice informs that the donation will repeat every X periods. Currently, that message always uses the first option label. This pull request changes that behavior to use the selected default period as the source for the period label. With that, was necessary to add an extra conditional to not show the notice when the default option is set to "One-time".
Recurring settings in the Amount block
https://github.com/impress-org/givewp/assets/3921017/71a1945d-60e2-40b6-aa28-0a266a7d0144
Make sure the recurring message is still being displayed correctly in both VFB and Donation …

Refactor: Change to use the selected default period in notice

---

src/DonationForms/resources/registrars/templates/groups/Authentication.tsx
src/DonationForms/resources/registrars/templates/styles.module.scss
src/FormBuilder/resources/js/form-builder/src/blocks/fields/login/index.tsx
src/Framework/FieldsAPI/Authentication.php

Resolves [GIVE-809]
This pull request re-style the Login block to match the new designs. This includes reorder of the settings in the sidebar, with the addition of helper texts.
Login block
_Already have an account button on Form Builder_
_Login form on the Form Builder_
_Already have an account button on Donation Form_
_Login form on the Donation Form_
Make sure the login form keep working just like before.
[GIVE-809]: …

Refactor: Re-style Login block

---

src/DonationForms/FormDesigns/ClassicFormDesign/css/_inputs.scss
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss

Resolves [GIVE-812]
Some issues were identified related to the Donor Title Prefix field and its settings. The field’s padding did not match with other inputs. Additionally, in its settings, there was some odd extra spacing when toggling certain options.
This pull request fixes these issues by standardizing the padding for the select field to match other inputs and adjusting the wrappers in the settings so that the correct margins are applied.
Donor Title Prefix
_Donor Title Prefix field in the Donation Form_
_Donor Title Prefix field in the Form Builder_
_Switching settings in the Form Builder_
1. Open a form
2. Enable Donor Title Prefix
3. Switch between the variety of options available
4. Confirm them all look and work well
-   [ ] Acceptance criteria satisfied and marked in related …

Refactor: Improve Donor Title Prefix field styles

---

src/FormBuilder/resources/js/form-builder/src/blocks/section/Edit.tsx

Resolves [GIVE-816]
When adding a long title in a section block, it does not look good. This pull request increases its line-height to match the style in the donation form and sets a top margin for the following paragraph element, reducing the spacing between these elements.
Section block title
_Before_
_After_
_Donation Form_
[GIVE-816]: https://stellarwp.atlassian.net/browse/GIVE-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …

Refactor: Set line-height to Section block in the VFB

---

src/DonationForms/FormDesigns/ClassicFormDesign/css/_inputs.scss
src/DonationForms/resources/app/form/MultiStepForm/components/StepsWrapper.tsx
src/DonationForms/resources/styles/elements/_multi-step-form.scss

Resolves [GIVE-811]
Currently, the form footer does not match the intended design. In the Classic design, the hover state of the Donate button is unique, differentiating it from other buttons. However, in the Multi-Step design, there is no hover state for the Donate button.
This pull request fixes these issues by adding the same hover state to the Donate button in both designs. Additionally, it also corrects the content and design of the secure notice badge present in the Multi-Step footer.
Classic and multi-step form footer
_Hover state on Classic design_
_Hover state on Multi-Step design_
_Secure notice badge on Multi-Step design_
- …

Refactor: Improve form footer style

---

src/DonationForms/resources/registrars/templates/fields/File.tsx

Resolves [GIVE-820]
The File Upload template is entirely clickable, triggering the file selection modal. This issue is caused by a label element wrapping the entire component. This pull request changes it by unwrapping the label element, keeping it only around the label text while still allowing it to trigger the file selection modal. The difference is that now, clicking the description text will not activate the modal, making this template consistent with how other fields behave.
File input template
https://github.com/impress-org/givewp/assets/3921017/2e66c450-23a0-448c-99b1-df4b175dd8b0
_Clicking the input, then the label, the description_
Make sure the input field works just like before, except it will not trigger the file selection modal when clicking on the description text.
-   [ ] …

Refactor: Prevent File Upload description from triggering file selection modal

---

src/Exports/DonorsExport.php

Resolves: [GIVE-923](https://stellarwp.atlassian.net/browse/GIVE-923)
https://github.com/impress-org/givewp/discussions/7398
This pull request enables the filtering of the donor export csv columns. In the past, users could introduce custom columns via the `give_export_donors_get_default_columns` filter in the previous Donor export class. This filter was utilized in two methods:
- Displaying Custom Columns on the Tools Page: One method would display the custom columns on the donor export section of the tools page to be checked. 
- Merging Custom Columns with Export Data: A second method, which incorporated custom columns into the export data.
By reintroducing this functionality in the new Donor export class, users can once again add custom donor information to the csv exports.
Donor Column …

Fix: enable custom donor columns in csv export

---

src/DonationForms/resources/styles/_base-overrides.scss

Resolves: [GIVE-818]
This change ensures all inputs in the visual form builder are standardized with the primary color applied to the border. This is necessary for some of the blocks in our addons which display a grey border with high specificity.
VFB inputs
https://github.com/impress-org/givewp/assets/75056371/50586ae2-cefe-4922-ace8-e4709868b040
- Install FFM, add a checkbox block.
- View design mode and click on the checkbox.
- Click away from the checkbox on the form verify the border color is not grey.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/c …

Refactor: standardize primary color on VFB input borders

---

src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/css/_container.scss
src/FormBuilder/resources/js/form-builder/src/components/onboarding/steps/schema-steps.tsx
src/FormBuilder/resources/js/form-builder/src/styles/_block-editor.scss
src/FormBuilder/resources/js/form-builder/src/styles/_form-builder.scss

Resolves [GIVE-268]
This pull request (PR) introduces enhancements to achieve a width-responsive preview in the form builder by removing the sidebars from their fixed positioning. This creates a more similar experience as the WP block editor.
Changes include:
`interface-interface-skeleton__content`
- Set height to allow content to be scrolled
- Set overflow-y to allow content to scroll
`.interface-interface-skeleton__body`
- Hide overflow so entire body does not scroll
`.givewp-next-gen-sidebar`
- remove fixed positioning
The visual form builder sidebars
https://github.com/impress-org/givewp/assets/75056371/e9903e49-b03f-4da5-a965-738c5cd7838a
- Toggle the sidebars on each form builder section'Build', 'Design' & 'Settings', the content section should expand and retract accordingly.
- Each …

Refactor: create responsive previews in the form builder

---

src/DonationForms/resources/registrars/templates/fields/Consent/ConsentModal.tsx
src/DonationForms/resources/registrars/templates/fields/Consent/createIframePortal.tsx
src/DonationForms/resources/registrars/templates/fields/Consent/styles.scss
src/FormBuilder/resources/js/form-builder/src/blocks/fields/terms-and-conditions/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/terms-and-conditions/settings.tsx

Resolves: [GIVE-810]
This PR addresses the issues related to the Consent field modal rendering within different contexts on the donation forms. 
Originally the modal was rendered with `react.createPortal('document.body)`. This limits the modal to its own  iframe.  Depending on how to the donation form is being viewed the modal placement will have different positions. To help with this concern our original implementation had scrolled to the middle of the form and rendered the modal. However this was not the modal ideal UI/UX.
To further address the issue we have implemented the following changes:
`react.createPortal('window.top.document.body)` ensures that the modal is inserted at the Top-Level document above all other Iframes. While displayed in either a donation-form-block, the Frontend, …

Fix: Modal rendering across different Iframe contexts

---

includes/admin/tools/export/give-export-donations-exporter.php

The meta 'razorpay_donation_response' is an array. Must be serialized to avoid a fatal error: 
`TypeError: Uncaught TypeError: substr(): Argument #1 ($string) must be of type string, array given in /var/www/html/wordpress/wp-content/plugins/give/includes/admin/tools/export/give-export-donations-exporter.php:684`
To test:
- activate give-razorpay
- export donations
- choose a donation form
- select the custom field column razorpay_donation_response

Fix fatal error in give-export-donations-exporter.php

---

src/FormMigration/FormMetaDecorator.php
src/FormMigration/ServiceProvider.php
src/FormMigration/Steps/RazorpayPerFormSettings.php
tests/Feature/FormMigration/Steps/TestRazorpayPerFormSettings.php

Resolves [GIVE-934]
Related PR: https://github.com/impress-org/give-razorpay/pull/84
This PR adds a new form migration step to ensure that the Razorpay per-form settings will be migrated to new V3 forms.
The form migration process.
1. Set up a v2 form and setup Razorpay per-form settings;
2. Migrate the form created in the previous step to a v3 form;
3. Make sure the settings from step 1 were migrated and available in the Payment Gateways block settings. …

Feature: add Razorpay per-form settings migration step

---

assets/src/js/admin/onboarding-wizard/app/steps/addons/index.js
assets/src/js/admin/onboarding-wizard/app/steps/addons/style.scss
assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js
assets/src/js/admin/onboarding-wizard/app/steps/donation-form/style.scss
assets/src/js/admin/onboarding-wizard/app/steps/features/index.js
assets/src/js/admin/onboarding-wizard/app/steps/features/style.scss
assets/src/js/admin/onboarding-wizard/app/steps/introduction/index.js
assets/src/js/admin/onboarding-wizard/app/steps/location/index.js
assets/src/js/admin/onboarding-wizard/app/steps/location/style.scss
assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js
assets/src/js/admin/onboarding-wizard/app/steps/your-cause/style.scss
assets/src/js/admin/onboarding-wizard/components/card-input/style.scss
assets/src/js/admin/onboarding-wizard/components/card/style.scss

Resolves [GIVE-969]
This pull request update content presented in the onboarding wizard. Additionally, it also brings some styling enhancements.
- Set description to:
> Get started quickly with our Onboarding Wizard and begin accepting donations on your website in minutes.
- Set title to:
> 👋 Hi there! Tell us about your cause.
- Set description to:
> This information will be used to set up your donation form experience.
- Set description to:
> Select the features you need. These can always be changed later.
- Add description to Donation Goal card as:
> Show the donation goal progress on the form.
- Add description to Donation Comments card as:
> Allow donors to add comments to their donations.
- Add description to Terms & Conditions card as:
> Require donors to accept terms and …

Refactor: Update content on onboarding wizard

---

assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js
assets/src/js/admin/onboarding-wizard/app/steps/donation-form/style.scss
assets/src/js/admin/onboarding-wizard/components/icons/bullet/index.js

Resolves [GIVE-968]
This PR replaces the carets in the Preview step of the onboarding wizard with bullets, as the carets give the impression that those items are expandable.
List in the Preview step of the Onboarding Wizard
_Before_
_After_
[GIVE-968]: https://stellarwp.atlassian.net/browse/GIVE-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Replace carets with bullets in the onboarding wizard

---

includes/admin/forms/dashboard-columns.php
includes/class-give-donate-form.php
includes/forms/functions.php
includes/misc-functions.php
includes/shortcodes.php
src/DonationForms/DonationQuery.php
src/DonationForms/V2/ListTable/Columns/DonationCountColumn.php
src/DonationForms/V2/ListTable/Columns/GoalColumn.php
src/MultiFormGoals/ProgressBar/Query.php
src/Views/Form/Templates/Classic/Classic.php
src/Views/Form/Templates/Sequoia/sections/income-stats.php
templates/shortcode-form-grid.php

Resolves [GIVE-876]
This PR fixes two bugs related to the `[give_totals]` and `[give_goal]` Shortcodes, and the **Multi-Form Goal** and **Donation Form Grid** blocks. 
The first bug was making these shortcodes and blocks display the wrong total amount collected and/or the donations count because the query had a problem related to how we are retrieving the information from DB - more details in the video linked in the _"Visuals"_ section. Now we are querying the the data properly.
The second bug also was related to how we were querying the donations, we were querying donations without checking the status (that should be 'publish' or 'give_subscription') and using both modes (test and live) together instead of considering only the current site mode. Now we are considering the allowed status …

Fix: make blocks and shortcodes display the right collected amount and make queries considering the proper donation statuses and mode

---

src/Onboarding/Wizard/Page.php

Resolves [GIVE-981]
This PR adds a user capability check for the Onboarding page.
Onboarding page
[GIVE-981]: https://stellarwp.atlassian.net/browse/GIVE-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: add user capability check for Onboarding

---

src/DonorDashboards/Helpers.php

Resolves [GIVE-983]
This PR resolves the issue where any registered user like a subscriber was able to upload attachments using donor dashboard endpoints. The issue is resolved by adding a user capability and user role check. 
Donor dashboard endpoints
[GIVE-983]: https://stellarwp.atlassian.net/browse/GIVE-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: add user capability and user role check for Donor dashboard endpoint

---

src/FormBuilder/resources/js/form-builder/src/styles/_form-builder.scss

Resolves [GIVE-1021]
This hides the new block inserter tabs introduced in WP 6.6 from our form builder block inserter sidebar.
The block inserter in the form builder
Before:
After:
- Instal WP 6.6
- View the v3 form block inserter
- There should be no extra tabs and it should work as expected
[GIVE-1021]: https://stellarwp.atlassian.net/browse/GIVE-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: hide block inserter tabs introduced in WP 6.6

---

src/DonationForms/V2/Endpoints/Endpoint.php
src/DonationForms/V2/Endpoints/FormActions.php

Resolves [GIVE-979]
This PR resolves the issue where users with `edit_give_forms` capabilities like the `give_worker` role could delete any post or page. The problem is resolved by checking if the user has the right capability for handling posts. 
[GIVE-979]: https://stellarwp.atlassian.net/browse/GIVE-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIx: use capabilities check

---

assets/src/js/admin/onboarding-wizard/app/index.js
assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js
assets/src/js/admin/onboarding-wizard/app/steps/donation-form/style.scss
assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js
assets/src/js/admin/onboarding-wizard/app/steps/your-cause/style.scss
assets/src/js/admin/onboarding-wizard/app/store/actions.js
assets/src/js/admin/onboarding-wizard/app/store/reducer.js
assets/src/js/admin/onboarding-wizard/components/checkbox-input/index.js
assets/src/js/admin/onboarding-wizard/components/checkbox-input/style.scss

Resolves [GIVE-966]]
Currently, we have a single route for users to accept or decline both sharing data for telemetry and subscribing to our newsletter. This pull request addresses that by adding separate checkboxes for these distinct cases. The telemetry opt-in is still in the Cause step, while the newsletter subscription is now in the Preview step.
Opt-in in the Onboarding Wizard
_Cause_ step with Telemetry opt-in
_Preview_ step with Newsletter opt-in …

Refactor: Separate Checkboxes for Telemetry and Newsletter Subscription in Onboarding Wizard

---

includes/shortcodes.php

Resolves: [GIVE-1049]
This resolves a SQL query error by moving the instantiation of the query outside the loop to prevent continuous query statements being added to the original query.
The give_totals shortcode
N/A
Zip: https://github.com/impress-org/givewp/actions/runs/10048657226
Use the give_totals shortcode with multiple form ids
[GIVE-1049]: https://stellarwp.atlassian.net/browse/GIVE-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

Fix: resolve give_totals fatal error when using multiple form IDs

---

src/DonationForms/V2/DonationFormsAdminPage.php
src/DonationForms/V2/resources/components/DonationFormsListTable.tsx
src/DonationForms/V2/resources/components/Onboarding/Components/FormBuilderButton.tsx
src/DonationForms/V2/resources/components/Onboarding/index.tsx

Resolves [GIVE-964]
These changes remove the Try the form builder button and the related banner from displaying on the Donations Form page.
The button is still visible on all v2 form adding/editing pages as well as the DonationForm page legacy view. This buttons text has also been updated to "Use the new visual form builder."
Donations Form page
https://github.com/user-attachments/assets/331d45c6-f533-4078-8f0b-d8ebacc5f99a
- Verify the try the form builder button is removed and does NOT display on the Donations Form page, unless in "Legacy view".
- Verify the try the form builder banner is removed and does NOT display on the Donations Form page.
- Verify the try the form builder button is still visible on all v2 Donation Form editing & adding pages.
-   [x] Acceptance criteria satisfied …

Refactor: Remove try the form builder messages on the Donations Form page

---

src/FormBuilder/resources/js/form-builder/src/settings/design/style-controls/color/index.tsx

Resolves: https://stellarwp.atlassian.net/browse/GIVE-807
This PR includes a temporary fix for the PanelColorSettings default color list. The original default colors included "White" which could not be seen on the form. It along with the rest of the default colors to choose from have been updated. In the future we will look into integrating theme.json for the Visual Form Builder to handle presets.
Visual Form Builder
- In the Visual Form Builder, open the Styles sidebar in Design mode
- 	Select both color controls and verify the new default color list.
- 
-   [x] [Self …

refactor: update default colors in PanelColorSettings

---

src/DonationForms/DonationFormsAdminPage.php
src/DonationForms/ServiceProvider.php

Resolves [GIVE-998]
This PR replaces the default _"Add Form"_ link [added by the WP Core](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/post-new.php#L36-L51) for custom post types with a new link that uses the visual form builder as default editor. 
As we don't have any filter to change this value, the `global $submenu;` var was used to accomplish that.
The "Add Form" admin menu link.
Here is a sample of how the `global $submenu;` var looks like:
1. Open the WP Admin area;
2. Click on the "Add Form" submenu from Give;
3. A new form using the Visual Form Builder should be created.
-   [ ] Reviewed by the designer …

Feature: add new link for the "Add Form" admin menu to create forms with the new visual form builder

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/billing-address/Edit.tsx

Resolves [GIVE-808]
This PR collapses by default the multiple panel bodies of the Billing Address inspector controls, with the exception of the first.
This change is isolated to the Billing Address inspector settings.
Add a Billing Address block to the donation form and view the inspector settings.
[GIVE-808]: https://stellarwp.atlassian.net/browse/GIVE-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: Collapse panel bodies by default

---

src/DonorDashboards/Pipeline/Stages/UpdateDonorAvatar.php
src/DonorDashboards/Profile.php
src/DonorDashboards/Tabs/EditProfileTab/AvatarRoute.php
tests/Unit/DonorDashboards/Repositories/TestProfile.php

Resolves [GIVE-983]
This updates the avatar route to check the author of attachment before deleting.
The avatar image upload functionality within the donor dashboard.
N/A
Zip: https://github.com/impress-org/givewp/actions/runs/10254847235
Instructions are in Jira.
[GIVE-983]: https://stellarwp.atlassian.net/browse/GIVE-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: update avatar route to check author of attachment

---

src/Donations/Repositories/DonationRepository.php
src/Framework/PaymentGateways/Webhooks/EventHandlers/SubscriptionRenewalDonationCreated.php
tests/Unit/Framework/PaymentGateways/Webhooks/EventHandlers/SubscriptionRenewalDonationCreatedTest.php

Resolves [GIVE-1078]
This PR implements a defensive approach to prevent duplicated renewal donations in cases where the `SubscriptionRenewalDonationCreated` class is used in the wrong context.
For example:
1. The donor creates a new subscription and it gets the gateway transaction ID for the first transaction immediately;
2. Even so the gateway sends a webhook notification related to this first transaction;
3. We receive this webhook notification and we don't check if the notification is related to the first transaction or if it's a renewal;
4. The `SubscriptionRenewalDonationCreated` class is used to handle the first transaction instead of the `SubscriptionFirstDonationCompleted` class;
5. As a result a new transaction is created with the same gateway transaction ID from the first …

Refactor: prevent subscription renewals with gateway transaction IDs already used previously

---

src/DonationForms/V2/resources/components/DonationFormsRowActions.tsx
src/DonationForms/V2/resources/components/Migration/index.tsx

Resolves [GIVE-1023]
This PR adds a new row action for v2 form in the forms table to upgrade a v2 form to a v3 form.
A new row action is added to the forms table.
| Form Edit Screen | Forms Table Screen |
| --- | ---- |
| ![image](https://github.com/user-attachments/assets/e84da130-d356-47d4-ae2a-8566a4a660c0) | ![image](https://github.com/user-attachments/assets/f062ff3a-3144-4a38-bf5d-eef27eb4be45) |
Create a v2 form.
Click the upgrade row action. …

Feature: Add form table upgrade row action

---

src/PaymentGateways/Gateways/ServiceProvider.php
src/PaymentGateways/Gateways/Stripe/LegacyStripeAdapter.php
tests/Unit/PaymentGateways/Gateways/Stripe/LegacyStripeAdapterTest.php

Resolves [GIVE-1096]
This PR validates that the card fields have been filled when using the Stripe gateway on a "legacy" donation form.
Adds a new hook in the legacy gateway adapter.
See [GIVE-1096] for replication steps.
[GIVE-1096]: https://stellarwp.atlassian.net/browse/GIVE-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GIVE-1096]: https://stellarwp.atlassian.net/browse/GIVE-1096?atlOrigin=eyJpIjoiNWRkNT …

Fix: Validate Stripe card info in legacy adapter

---

src/DonationSpam/EmailAddressWhiteList.php
src/DonationSpam/ServiceProvider.php
tests/Unit/DonationSpam/ServiceProviderTest.php

Resolves [GIVE-1153]
This PR prevents non-array values from causing an error when validating against whitelisted email addresses.
Adds a type hint when constructing the whitelist.
Adds a type cast when resolving the whitelist from the container.
1. In a new site install and active Akismet and GiveWP.
2. Do NOT touch the Akismet settings in GiveWP.
3. Try to make a donation on a V3 form with the Test Donation gateway
[GIVE-1153]: https://stellarwp.atlassian.net/browse/GIVE-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

Fix: Prevent error with unsaved or malformed email whitelist

---

src/Campaigns/CampaignsAdminPage.php
src/Campaigns/ServiceProvider.php

Resolves [GIVE-1122]
This PR adds a submenu item under the Give main menu and an initial empty page where the new campaigns list table will be loaded.
The Give admin menus/submenus.
1. In the admin area click on the new `Give > Campaigns` item;
2. Make sure a new empty page with the _"The campaigns list table will be loaded here..."_ temp text is loaded.
[GIVE-1122]: https://stellarwp.atlassian.net/browse/GIVE-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

Feature: add campaigns menu item and initial empty page

---

src/DonationForms/Actions/PrintFormMetaTags.php
src/DonationForms/ServiceProvider.php
src/Form/Template.php

This PR resolves the issue with the featured image not showing in the form grid for v3 forms. Also, a new action is added to print form meta tags (og:image) to show an image preview for shared links. 
Form grid
Donation form
Create v2 form and v3 form
Set featured/header image for both
Create a new page and add a Form Grid block
Verify that both forms show featured/header image

Feature: Header image should show in Form Grid and link previews

---

src/DonationForms/FormDesigns/ClassicFormDesign/css/_inputs.scss

Resolves [GIVE-824]
This PR reduces the spacing between the donation form inputs and their related error messages.
The bottom margin has been removed from the text and select inputs on the donation form.
| --- | --- |
| ![Screen Shot 2024-07-31 at 12 59 36](https://github.com/user-attachments/assets/751e2370-09c2-4164-a3fe-73c7980e6c8c) | ![Screen Shot 2024-07-31 at 12 58 39](https://github.com/user-attachments/assets/61ed5cae-3a85-4dbd-a574-565c13b6f306) |
| Donor Name Field |
| --- |
| ![Screen Shot 2024-07-31 at 13 00 42](https://github.com/user-attachments/assets/3dc0205d-e5d8-4052-bd61-c8830c933636) |
| ![Screen Shot 2024-07-31 at 12 53 24](https://github.com/user-attachments/assets/f81ded1c-00be-4121-8d42-6c71394808ef) |
| Select Input |
| --- |
| ![Screen Shot …

Refactor: Reduce spacing between form inputs and error messages

---

tests/Feature/FormMigration/Steps/TestEmailSettings.php
tests/Feature/FormMigration/Steps/TestFeeRecovery.php
tests/Feature/FormMigration/Steps/TestFormExcerpt.php
tests/Feature/FormMigration/Steps/TestFormFeaturedImage.php
tests/Feature/FormMigration/Steps/TestFormFields.php
tests/Feature/FormMigration/Steps/TestFormGrid.php
tests/Feature/FormMigration/Steps/TestFormMeta.php
tests/Feature/FormMigration/Steps/TestFormTitle.php
tests/Feature/FormMigration/Steps/TestMigrateMeta.php
tests/Feature/FormMigration/Steps/TestOfflineDonations.php
tests/Feature/FormMigration/Steps/TestPaymentGateways.php
tests/Feature/FormMigration/Steps/TestPdfSettings.php

Resolves [GIVE-926]
This PR adds tests for these `FormMigration` processes:
- EmailSettings
- FeeRecovery
- FormExcerpt
- FormFeaturedImage
- FormFields
- FormGrid
- FormMeta
- FormTitle
- MigrateMeta
- OfflineDonations
- PaymentGateways
- PdfSettings
[GIVE-926]: https://stellarwp.atlassian.net/browse/GIVE-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Test: Add new tests for form migration steps

---

assets/src/js/admin/admin-scripts.js

Resolves [GIVE-789]
This PR fixes a bug that prevents the _"Supported Gateways"_ field be saved on the settings of the _"Subscription Payment Failed"_ email. The problem was introduced in the following PR: https://github.com/impress-org/givewp/pull/6237
So, the solution was to change how to set the "selected" attribute of the select options to make it work in the same way as before the changes introduced in the PR mentioned above. 
The `multiselect` fields spread on the codebase.
https://www.loom.com/share/6eabb134dc0940ec8af9d893d079ac9c?sid=e68abf36-b943-40ed-b512-9ade95bbfa95
1. Go to Give > Settings > Emails > Subscription Payment Failed  page;
2. On the "Supported Gateways" field select a few gateways;
3. Save the changes and make sure the selected gateways are saved.
**Additional …

Fix: persists "Supported Gateways" field on the settings of the "Subscription Payment Failed" email 

---

assets/src/js/admin/paypal-commerce/index.js
src/PaymentGateways/PayPalCommerce/AdminSettingFields.php
src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php

Resolves [GIVE-1135]
This updates the paypal commerce disconnect button with a nonce.
The PayPal commerce disconnect button
N/A
- Make sure the disconnect button still works as expected.
[GIVE-1135]: https://stellarwp.atlassian.net/browse/GIVE-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: add nonce to paypal disconnect

---

give.php
includes/admin/settings/class-settings-advanced.php
readme.txt
src/DonationForms/V2/resources/components/DonationFormsListTable.tsx
src/DonationSpam/EmailAddressWhiteList.php
src/DonationSpam/ServiceProvider.php
src/Donations/DonationsAdminPage.php
src/Donors/DonorsAdminPage.php
src/FormBuilder/resources/js/form-builder/src/components/EmbedForm/index.tsx
src/FormBuilder/resources/js/form-builder/src/promos/recurring-donations.tsx
src/FormBuilder/resources/js/form-builder/src/settings/group-email-settings/email/template-options/settings.tsx
src/FormBuilder/resources/js/form-builder/src/settings/group-email-settings/general/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/group-general/form-summary/index.jsx
src/FormMigration/FormMetaDecorator.php
src/Subscriptions/SubscriptionsAdminPage.php
src/Subscriptions/resources/components/SubscriptionsListTable.tsx
tests/Feature/FormMigration/Steps/TestActiveCampaign.php
tests/Feature/FormMigration/Steps/TestConstantContact.php
tests/Feature/FormMigration/Steps/TestConvertKit.php
tests/Feature/FormMigration/Steps/TestDonationGoal.php
tests/Feature/FormMigration/Steps/TestDonationOptions.php
tests/Feature/FormMigration/Steps/TestDoubleTheDonation.php
tests/Feature/FormMigration/Steps/TestMailchimp.php
tests/Unit/DonationSpam/ServiceProviderTest.php
tests/Unit/FormMigration/TestTraits/FormMigrationProcessor.php

Resolves [GIVE-1159]
This includes all PR submissions from @DAnn2012 to update string translations
- #7496
- #7497
- #7498 
- #7499
- #7500
- #7501
- #7502
- #7513
Strings in following locations:
- Donation and Subscription list tables
- Form builder embed
- Form summary block
- Form builder email options
- GiveWP global advanced settings
- Recurring donations promo in form builder
N/A
- Run through automated tests
- Make sure affected pages work as expected …

Refactor: update strings translations (@DAnn2012)

---

src/PaymentGateways/Gateways/Offline/Actions/EnqueueOfflineFormBuilderScripts.php

Resolves [GIVE-1106]
The problem was happening because we were checking if the offline gateway for v2 forms was enabled instead of checking the offline gateway for v3 forms.
Now we changed it to check the v3 version and the problem is not happening anymore.
The Payment Gateways block.
1. Disable the offline gateway for v2 forms;
2. Enable the offline gateway for v3 forms;
3. Go to the form builder and make sure the "Offline donations" section is visible in the controls of the Payment Gateways block settings.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/ …

Fix: the "Offline donations" section in the controls of the Payment Gateways block should be visible when Offline gateway for v3 forms is enabled

---

src/Campaigns/Actions/LoadCampaignDetailsAssets.php
src/Campaigns/CampaignsAdminPage.php
src/Campaigns/Routes/CreateCampaign.php
src/Campaigns/ViewModels/CampaignDetails.php
src/Campaigns/ViewModels/CampaignDetailsPage.php
src/Campaigns/resources/admin/campaign-details.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/CampaignDetailsPage.module.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/types.ts
webpack.mix.js

Resolves [GIVE-1152]
This PR adds an initial campaign details page that loads a few data from the overview and settings tab and only displays on the screen in a raw format - the design should be implemented in subsequent PRs.
For reference about the information architecture, check this design prototype:
https://www.figma.com/design/KN4DmHaBWDylrq1EbVXw3n/Campaigns?node-id=299-10474&node-type=FRAME&t=7fGtZY2l39rnL5Ou-0
The campaign details page.
1. Go to `Give > Campaigns` page;
2. Create a new campaign or Edit a campaign created previously;
3. You should see a screen with details about the campaign and a link to edit the landing page;
4. Click on the `Edit Campaign Landing Page ⭷` link and a a new tab should be open.
-   [ …

Feature: add campaign details page

---

src/FormBuilder/resources/js/form-builder/src/styles/_onboarding.scss

Resolves: [GIVE-1229]
This PR sets the height of each design selector card to auto. It would seem the parent elements of the card do not have a set height and Safari is having trouble calculating what it should it be. This can be fixed by changing the parent grid to a flex system or setting the height to auto and allowing it to adjust it self. These changes introduce the latter.
Design Selector Card - new form template selecting modal
- Add a new form via VFB.
- Verify each form template card is an appropriate height on while using Safari.
-   [x] [Self …

Fix: Adjust design selector card height for Safari compatibility

---

src/Campaigns/CampaignDonationQuery.php
tests/Unit/Campaigns/CampaignDonationQueryTest.php

Related [GIVE-1221]
This PR adds a query builder for campaign donations, which are aggregated from campaign related donation forms.
```php
$query = new CampaignDonationQuery($campaign);
$query->sumIntendedAmount();
```
```php
$query = new CampaignDonationQuery($campaign);
$query->countDonations();
```
```php
$query = new CampaignDonationQuery($campaign);
$query->coundDonors();
```
[GIVE-1221]: https://stellarwp.atlassian.net/browse/GIVE-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature: Add query builder for Campaign Donations

---

includes/admin/class-admin-settings.php

Fix: Made the default Chosen placeholder translatable in class-admin-settings.php

Fix: Made the default Chosen placeholder translatable in class-admin-settings.php

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/anonymous/styles.scss

Resolves: [GIVE-1231]
In WordPress versions prior to 6.6.1, the help message for the Checkbox control was contained within a single `<p>` tag with the classname `.components-base-control__help`. This message required additional margin adjustments to align properly with the description of the control.
Starting from WordPress version 6.6.1, the html has been updated to include an additional `<span>` element within the `<p>` tag, with the necessary CSS applied to this `<span>` via classname `components-checkbox-control__help`.
To maintain consistent styling across both versions of WordPress, this PR introduces a fix that applies the required styles directly to the `<p>` element and removes the styling from the `<span>` element. This ensures that the styling is consistent and works with both …

Fix: Adjust Anonymous block styles for WP <= 6.6

---

src/Framework/PaymentGateways/Contracts/Subscription/SubscriptionPausable.php
src/Framework/PaymentGateways/Contracts/SubscriptionModuleInterface.php
src/Framework/PaymentGateways/PaymentGateway.php
src/Framework/PaymentGateways/SubscriptionModule.php
src/LegacySubscriptions/includes/give-subscription.php
src/Subscriptions/Repositories/SubscriptionRepository.php
src/Subscriptions/ValueObjects/SubscriptionStatus.php
src/Views/Components/ListTable/InterweaveSSR/styles.scss

Resolves [GIVE-1250]
This Pull Request adds supports for gateways to implement their solutions for pausing/resuming subscriptions. Within this PR we are:
- adding a new "paused" status to subscriptions;
- setting a color for the "paused" status in the subscriptions list table;
- adding a new `SubscriptionPausable` contract to be signed by gateways;
- adding a capability check as `can_pause` to gateways (false by default if not implemented);
- fixing the `SubscriptionRepository` to update the expiration date into the database;
- updating the subscription details screen to show the next renewal date for paused subscriptions as it does for active ones.
This PR is a foundational work that is required for the new implementations on Give Recurring.
Subscriptions
-   [ ] Acceptance criteria …

Feature: Add support for pausing/resuming subscriptions

---

src/Campaigns/CampaignDonationQuery.php
src/Campaigns/Routes/CampaignOverviewStatistics.php
src/Campaigns/ServiceProvider.php
src/Framework/Support/Facades/DateTime/Temporal.php
src/Framework/Support/Facades/DateTime/TemporalFacade.php
tests/Unit/Campaigns/Routes/CampaignOverviewStatisticsTest.php
tests/Unit/Framework/Support/Facades/DateTime/TemporalFacadeTest.php

Related [GIVE-1221]
Related [GIVE-1222]
This PR adds the `GET \give-api\v2\campaign-overview-statistics` endpoint for fetching campaign statistics, such as Amount Raised, Donation Count, and Donor Count.
If a range in days (`rangeInDays`) is provided then a pair of values are returned to include the previous period of the range.
- `Campaigns\CampaignDonationQuery` has been updated with support for immutability.
- `Framework\Support\Facades\DateTime\TemporalFacade` has been updated to include new helper methods `withStartOfDay` and `withEndOfDay`, which set the appropriate time for inclusively querying dates in a range. Additionally, the `immutableOrClone` method has been added to encapsulate support for immutability that accounts for either `DateTime` or `DateTimeImmutable`, both of which …

Feature: Add endpoint for Campaign Overview Statistics

---

includes/gateways/stripe/includes/admin/class-give-stripe-admin-settings.php

The Stripe recipient email setting is placed after the filter that designates the end of the [General] settings. This causes any new settings introduced by the filter `give_stripe_add_after_general_fields` to be placed prior to this setting. The filter should be placed below the last default setting so that additional settings introduced are inserted at the bottom.
Stripe Settings
- Donations->Settings->Paymentgateways->Stripe : Verify the new admin setting for pausing subscriptions is inserted at the bottom. This will require the latest version of Stripe in order for the new setting to be displayed. …

Refactor: move recipient email above general settings filter

---

includes/process-donation.php

Resolves [GIVE-1289]
This PR implements a defensive approach to always check if the name title prefix is enabled on the form before accepting its values on the form submission.
[GIVE-1286]: https://stellarwp.atlassian.net/browse/GIVE-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GIVE-1289]: https://stellarwp.atlassian.net/browse/GIVE-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

Enhancement: add additional validations for name title prefix field

---

includes/process-donation.php
tests/includes/legacy/tests-functions.php

Resolves [GIVE-1296]
- This updates our check for serialized input to inspect all incoming data.
- This also adds extra validation for the company field
V2 form processing
N/A
TBD
[GIVE-1296]: https://stellarwp.atlassian.net/browse/GIVE-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: disallow any serialized input in v2 forms

---

src/DonorDashboards/resources/js/app/components/mobile-menu/index.js

Resolves: [GIVE-1288]
This PR resolves an issue with the mobile navigation in the DonorDashboard where the hamburger menu was unresponsive, preventing donors from accessing other sections of the dashboard on mobile devices.
The problem stemmed from a handleClick function inside a useEffect hook, which unintentionally caused the menu to close immediately upon interaction, preventing it from staying open when clicked.
The DonorDashboard in mobile view.
https://github.com/user-attachments/assets/3bced2d3-1d95-4c69-8a1b-c28f3f56a255
- Open the donor dashboard in mobile view.
- Click the hamburger menu/icon to open the navigation items.
- Click outside the navigation links to verify the menu closes.
- Navigate to a new page to ensure the menu works properly. …

Fix: ensure DonorDashboard mobile navigation opens as expected

---

includes/process-donation.php

Resolves [GIVE-1306]
The problem was happening on PHP 8+ because the `ltrim()` method on those versions is more restrictive about which type of parameter is accepted. In previous versions, not-string values only threw wanings but in PHP 8+ version it threw a fatal error that prevented the donation workflow. 
So, the solution was to prevent the use of values different from a string on the `ltrim()` method.
Option-based forms with the Tributes add-on enabled.
1. Create a v2 form and enable Tributes;
2. Make a donation but do not opt-in for Tributes;
3. The donation should be finished without fatal errors. …

Hot Fix: prevent PHP 8+ fatal errors when Tributes add-on is enabled

---

give.php
src/DonationForms/Actions/AddHoneyPotFieldToDonationForms.php
src/DonationForms/ServiceProvider.php
src/Settings/Security/Actions/RegisterPage.php
src/Settings/Security/Actions/RegisterSection.php
src/Settings/Security/Actions/RegisterSettings.php
src/Settings/Security/SecuritySettingsPage.php
src/Settings/ServiceProvider.php
tests/Unit/DataTransferObjects/DonateFormDataTest.php
tests/Unit/DataTransferObjects/DonateFormRouteDataTest.php
tests/Unit/DonationForms/Actions/TestAddHoneyPotFieldToDonationForms.php
tests/Unit/DonationForms/Repositories/TestDonationFormRepository.php

Resolves [GIVE-1252]
This adds a global setting to enable the honeypot field for v3 forms. This introduces a new section to the "general" tab called _security_.
When this settings is enabled, it will affects v3 forms by programmatically adding a honeypot field.
Additional filter added for the honeypot field name:
```php
apply_filters('givewp_donation_forms_honeypot_field_name', $fieldName, $formId)
```
- Enable the new settings
- Interact with a v3 form …

Feature: add global settings for honeypot field

---

package-lock.json
package.json
src/DonationForms/Actions/ConvertDonationFormBlocksToFieldsApi.php
src/FormBuilder/ViewModels/FormBuilderViewModel.php
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/Edit.tsx
src/FormBuilder/resources/js/form-builder/src/blocks/fields/donor-name/settings.tsx
tests/Unit/ViewModels/FormBuilderViewModelTest.php

Resolves [GIVE-1292]
I noticed the honorific block was offering to "show values", except it didn't actually do anything with the values.  Since honorifics are both a value and label, also used in global settings I decided to remove the option for showing values.
Furthermore, extra field validation was added to only accept the available select options. 
The honorific block & field
**The problem discovery**
https://www.loom.com/share/1ae99a62f60a4e96b47d00f394de0681?sid=79a84b4c-427e-4b0d-9f99-44d684b6f0bb
**The fix**
https://www.loom.com/share/0bc214e053b64e458a4bea57a5454d0f?sid=28e23e37-1510-4f56-9edf-248cb884f2bf
- Interact with the honorific block & field
- Try submitting a value that is not in the listed options
-   [ ] …

Refactor: update Honorific block to only accept labels and add field validation

---

includes/admin/class-admin-settings.php
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-1097]
This PR addresses an issue where donors click the donation form’s submit button instead of PayPal’s “Pay Now” button when filling out credit card fields through PayPal Commerce. This causes an error, as PayPal cannot complete the transaction properly through the form’s submit button.
The solution hides the form’s submit button when PayPal Commerce is selected, ensuring donors interact only with PayPal’s button. The submit button is restored when switching to other gateways and PayPal Commerce fields component unmounts.
Visual Builder Forms
1.	Navigate to the donation form page.
2.	Select “Donate with Credit Card” (PayPal Commerce) as the payment gateway.
3.	Verify that the form’s submit button is hidden, ensuring only PayPal’s “Pay Now” button is available for …

Fix: Hide donation form submit button to prevent errors with PayPal Commerce payment flow

---

src/FormBuilder/resources/js/form-builder/src/blocks/fields/amount/inspector/index.tsx

Resolves [GIVE-1325]
We recently updated the form builder library in core which included an update to the option panel component with a prop for `showToggle` that was not explicitly added to the amount level/description option panel implementation. This adds the prop to show the toggle.
- V3 forms amount block level settings
- In form builder, Interact with the amount block and make sure the amount description work as expected
[GIVE-1325]: …

Fix: add showToggle to amount descriptions option panel

---

includes/admin/class-admin-settings.php
src/Settings/Security/Actions/RegisterSettings.php

Resolves [GIVE-1331]
During the [settings PR](https://github.com/impress-org/givewp/pull/7546) the honeypot field was added and used as enabled by default (without saving the settings).  However, the default state of the setting is disabled visually.  This makes sure the default state matches the default behavior.
For folks who updated to the version that includes the honeypot field, it will fallback to enabled because the setting has not been physically saved yet.
The honeypot setting UI
Make sure the honeypot field setting is visually enabled by default.
-   [ ] [Self …

Fix: update honeypot field setting to be enabled by default

---

src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/index.js
src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/style.scss

This PR addresses style changes that were made in the `Subscription Manager` page of the Donor Dashboard. By allowing the Select amount dropdown to expand full width when alone, but also split the `FieldRow` when the custom amount option is available.
Donor Dashboard Subscriptions

Fix: adjust Subscription Manager styles for custom amount

---

includes/admin/class-addon-activation-banner.php

Resolves [GIVE-1370]
This adds the $user_id property to the Give_Addon_Activation_Banner class to prevent the following php warning:
```
[24-Oct-2024 21:00:08 UTC] PHP Deprecated:  Creation of dynamic property Give_Addon_Activation_Banner::$user_id is deprecated in /Users/jonwaldstein/Herd/givewp/wp-content/plugins/give/includes/admin/class-addon-activation-banner.php on line 48
```
- The banner activation banner dismissing functionality (user_id)
N/A
- Make sure you can dismiss an addon banner activation
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/cod …

Fix: php dynamic property warning of $user_id in Give_Addon_Activation_Banner class

---

composer.json
composer.lock
src/Framework/Models/Factories/ModelFactory.php
src/TestData/Framework/Factory.php
src/TestData/Framework/Provider/RandomProvider.php
src/TestData/ServiceProvider.php
tests/Unit/PaymentGateways/Stripe/StripePaymentElementGateway/Actions/UpdateStripeFormBuilderSettingsMetaTest.php

Resolves: [GIVE-1357]
This PR moves the FakerPHP library from production. 
TestData
Model Factories
[GIVE-1357]: https://stellarwp.atlassian.net/browse/GIVE-1357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor: remove FakerPHP from production 

---

src/Campaigns/DataTransferObjects/CampaignGoalData.php
tests/Unit/Campaigns/DataTransferObjects/CampaignGoalDataTest.php

Resolves [GIVE-1428]
This PR checks for a campaign goal before calculating a goal progress as a percentage, which might attempt to divide by zero.
- Set the campaign goal to zero
- Load the Campaign List Table
[GIVE-1428]: https://stellarwp.atlassian.net/browse/GIVE-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Check for campaign goal before calculating percentage

---

includes/donors/class-give-donor-wall.php

When using the Donor Wall shortcode or block, filtering by `only_comments` returns no donations. 
The problem was that the donor comment was stored in the donation meta table, but we tried to fetch it from the `give_comments` table which resulted in no donations being returned. The issue is fixed by querying the correct table. 
Donor Wall block/shortcode
https://github.com/user-attachments/assets/0f124b72-76ee-4af5-8fa9-61ebc0c546c4
-  enable comments either on a per-form basis or at Donations >> Settings >> Default Options
- using GiveWP, create donations both with and without comments.
- use this shortcode [give_donor_wall only_comments="true"]
- or use the Donor Wall block and turn on the Only Comments at Display Elements >> Wall Attributes
-   [x] Relevant `@unreleased` tags included …

Fix: When using the Donor Wall shortcode or block, filtering by only_comments returns no donations

---

src/Framework/FieldsAPI/Properties/DonationForm/CurrencySwitcherSetting.php

This adds the ReturnTypeWillChange flag to supress this warning:
```php
PHP Deprecated:  Return type of Give\Framework\FieldsAPI\Properties\DonationForm\CurrencySwitcherSetting::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/jonwaldstein/Herd/givewp/wp-content/plugins/give/src/Framework/FieldsAPI/Properties/DonationForm/CurrencySwitcherSetting.php on line 47
```
php 8.1 compatibility with the CurrencySwitcherSetting class
N/A
Make sure the warning does not show up when interacting with the form & currency switcher.
-   [ ] …

Chore: fix php jsonSerialize warning for currency switcher setting

---

src/FormBuilder/resources/js/form-builder/src/styles/_form-builder.scss

Resolves [GIVE-1509]
WordPress 6.7 introduced some new css classnames to the sidebar we are using that are causing styling issues:
- `block-editor-tabbed-sidebar__tablist-and-close-button`
- `.block-editor-tabbed-sidebar`
This PR adds some specific css tweaks to these classes to prevent:
1. The sidebar tabs from showing (Blocks, Patterns, Media tab)
2. The sidebar width becoming fixed with a scrollbar
The from builder sidebar on WordPress 6.7
**Before**
https://github.com/user-attachments/assets/c412ca78-88f6-4103-8dff-279b617873f0
**After**
- Install WP 6.7-RC
- Make sure the form builder sidebar works as expected
-   [ ] Reviewed by the …

Fix: Update sidebar style for WordPress 6.7 compatibility

---

src/FormMigration/Controllers/MigrationController.php
src/FormMigration/Controllers/TransferController.php
tests/Feature/FormMigration/Controllers/TestMigrationController.php
tests/Unit/DonationForms/TestTraits/LegacyDonationFormAdapter.php

This PR updates the form migration process by associating the upgraded form with a campaign. 
Form migration
https://github.com/user-attachments/assets/1eec001a-104d-4f1e-ac25-2a740195e1b3
In Campaign context:
- Create a V2 form
- Upgrade the V2 form

Feature: Associate upgraded form to a campaign

---

src/Campaigns/resources/admin/components/CampaignFormModal/index.tsx

Resolves [GIVE-1339]
This PR removes the unnecessary validation and sets the goal input, in the same way, using the settings tab from the campaigns details page.
The creation of new campaigns.
1. In the modal for creating a new campaign select the "Amount raised" goal type option first;
2. Select any other option after the previous step;
3. Repeat the step `#1`;
4. Fill the input with the goal;
5. Click on the “Continue” button;
6. No error should be thrown next to the input.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of …

Fix: remove unnecessary error message when selecting the initial goal while creating a new campaign

---

src/Campaigns/resources/admin/components/CampaignFormModal/CampaignFormModal.module.scss
src/Campaigns/resources/admin/components/CampaignFormModal/index.tsx

Resolves [GIVE-1340]
This PR implements a few CSS tweaks to make the "previous" button from the Create Campaign modal match the design.
The creation of new campaigns.
**Demo video:** https://www.loom.com/share/175097c6f0e142388f37afcf23a904e6?sid=a3c9ec94-56ba-41f0-9561-2a9ec5040325
1. On the campaigns page click on the "Create Campaign" button;
2. Go to the second step of the form and make sure the "previous" button looks like on design.
[GIVE-1340]: …

Fix: goal creation modal should not highlight previous button

---

src/DonationForms/Blocks/DonationFormBlock/Controllers/BlockRenderController.php
src/DonationForms/Blocks/DonationFormBlock/resources/app/Components/ModalForm.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/app/index.tsx

Resolves [GIVE-1429]
This includes the `heightCalculation` prop on the Iframe-Resizer-react component for v3 forms. The taggedElement used can be found in the `DonationFormViewModel.php` class. The element can be found via `id="root-givewp-donation-form" `. taggedElements are denoted via `data-iframe-height`
I also noticed the parent page script for the  iframe-resizer JS package in `embed.ts` was enqueued for v3 forms. It is targeting an iframe via `iframe[data-givewp-embed]` which does not align with the iframe currently used to render v3 forms.
The iframe-resizer-react documents do not explicitly mention to load the parent page script. So I have removed the script from enqueuing. Reference: https://www.npmjs.com/package/iframe-resizer-react/v/1.1.0
- In an earlier `NextGen` version the …

Fix: Apply taggedElement to improve iframe height resizing in v3 forms

---

src/Campaigns/resources/admin/components/CampaignsListTable/index.tsx
src/Campaigns/resources/admin/components/CreateCampaignModal/index.tsx

Resolves [GIVE-1342]
This PR prevents a page refresh when clicking the Create Campaign button in the Campaign List Table.
The state for the Create Campaign Modal has been lifted to the `<CampaignsListTable />` parent component so that it can be shared by the `<ListTableBlankSlate />` and the `<CreateCampaignModal />` components.
With no campaigns created, from the campaign list table click the "create campaign" button within the table's empty state (as opposed to the header). …

Fix: Prevent page refresh when opening the Create Campaign Modal

---

templates/shortcode-donor-wall.php

The donor has had the ability to upload a profile image for years, since the Donor Dashboard was introduce. But the Donor Wall was never updated to make use of this — which is a bummer!
This PR has the Donor Wall check for an uploaded image and prioritizes it above the Gravatar image if available.
The donor dashboard shortcode template
**Uploaded in donor dashboard:**
**Showing in Donor wall:**
1. Go to the Donor Dashboard and upload an image
2. Save your profile
3. Go to a donor wall showing that user, and see if the image shows up
4. Double-check that removing the image doesn't break anything
-   [ ] Reviewed by the designer (if follows …

Feature: display uploaded donor avatar on donor wall

---

src/PaymentGateways/PayPalCommerce/AdminSettingFields.php

Resolves: [GIVE-1989]
This PR resolves the issue of users not being able to link their PayPal accounts. The problem was the incorrect callback set in the `data-paypal-onboard-complete` attribute, which is set dynamically [here](https://github.com/impress-org/givewp/blob/982ead3b3886557ccbb17058140be3728c1f23fa/assets/src/js/admin/paypal-commerce/index.js#L130). For some reason, dynamic attribute update did not work. The issue is resolved by removing the hardcoded data attribute from the button. 
PayPal connect account button
Connect PayPal sandbox/live account
[GIVE-1989]: https://stellarwp.atlassian.net/browse/GIVE-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

Fix: PayPal connect

---

src/Session/SessionDonation/SessionObjects/Donation.php
src/Session/SessionDonation/SessionObjects/FormEntry.php

Resolves: [GIVE-226]
This PR declares the dynamic properties in the `FormEntry` & `Donation` Session Object classes to handle depreciation warnings that arise from PHP@8.2. Dynamic properties will no longer be supported with the release of PHP@9.0.
Reference:
-  https://www.php.net/manual/en/migration82.deprecated.php
- https://php.watch/versions/8.2/dynamic-properties-deprecated
Deprecation Warnings in the admin screens.
- Install Give on server that runs PHP 8.2.
- Enable WP_DEBUG and WP_DEBUG_LOG.
- View admin settings for deprecation warnings.
-   [x] [Self …

Fix: Handle 8.2 depreciation warnings in the Donation `SessionObjects`

---

src/FormMigration/DataTransferObjects/FormMigrationPayload.php

Resolves [GIVE-2009]
https://lw.slack.com/archives/C02RH0J92HK/p1731953344285929 
related: https://github.com/impress-org/givewp/pull/7595
We have removed the faker dependency from production. The factory method should be removed from uses outside of testing.
Form migration process.
- Create a v2 form.
- Attempt to migrate to a v3 form.
[GIVE-2009]: https://stellarwp.atlassian.net/browse/GIVE-2009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: remove factory method from form migration process

---

includes/payments/functions.php

This PR resolves the issue with the wrong donation description in the confirmation email. The problem affects V3 forms only because there is a missing meta key (_give_payment_price_id) which is used to determine the donation level. The issue is resolved by checking if the donation form is a V3 form and then comparing the donation amount with the donation level amount set in form settings.
Donation receipt email
- Create a donation form with multiple donation levels.
- Give each donation level a different description.
- Donate to any level other than the first level.
- Check the donation description in the donation confirmation
-   [x] [Self …

Fix: Donation confirmation email - donation description 

---

give.php

Resolves [GIVE-2015]
This PR moves the loading of the `give` textdomain to the `init` action hook, which was previously being loaded during `plugins_loaded`.
The release of WordPress v6.7.0 added a new notice when a textdomain is loaded "too early", see https://github.com/WordPress/wordpress-develop/commit/d42d95856e9ae3f9e2ed0aad176c066d7f8e3229.
>  **Notice**: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the give domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in `/wp-includes/functions.php on line 6114`
Check that no …

Fix: Load textdomain on `init` action hook

---

src/DonorDashboards/App.php
src/DonorDashboards/resources/js/app/components/subscription-manager/index.tsx
src/DonorDashboards/resources/js/app/components/subscription-manager/payment-method-control/index.js
src/DonorDashboards/resources/js/app/components/subscription-row/index.tsx

Needed for https://github.com/impress-org/give-recurring/pull/1212 and https://github.com/impress-org/give-blink/pull/10/files
Blink Payments does not support updating a subscription amount, only the credit card number. For this reason, this Pull Request adds several WordPress filters that allow us to hide the Amount field on the Subscription Manager page. Additionally, it introduces a filter enabling third parties to enqueue custom scripts in the Donor Dashboard and allowing Blink to render its own `PaymentMethodControl` component.
Donor Dashboard
-   [x] [Self …

Feature: Add support for integrating Blink Payment with the Donor Dashboard

---

src/Campaigns/Routes/RegisterCampaignRoutes.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx

This PR updates the campaign status change action, hiding archived notifications when the campaign status is changed to draft. Also, a few minor changes were made to the JSON schema which caused issues with AJV. 
Campaign status change
Archive campaign - notification that the campaign is archived should appear
Go to the campaign dropdown menu and move the campaign to draft - archive notification should  disappear 

Refactor: Campaign status changes

---

includes/country-functions.php

ISO Code change for Odisha state (India) https://en.wikipedia.org/wiki/ISO_3166-2:IN (23 November 2023)

Fix: Update ISO Code for Odisha (India)

---

src/Framework/Models/Factories/ModelFactory.php
src/Framework/Models/Factories/README.md
tests/Unit/Framework/Models/Factories/TestModelFactory.php

This PR adds deferred resolution to model factory definitions, such as nested model factories, so that defaults can be overridden without instantiating unused model instances.
Updates `Give\Framework\Models\Factories\ModelFactory::makeInstance()` to support resolving attributes that are `callable`.
```php
public function definition(): array
{
return [
'title' => __('GiveWP Campaign', 'give'),
'formId' => DonationForm::factory()->createAndResolveTo('id'),
];
}
```
This feature is covered by unit tests and does not have a customer facing application.

Feature: Add deferred resolution to model factory definitions

---

src/DonationForms/resources/app/utilities/generateRequestErrors.ts
src/Framework/Migrations/Controllers/ManualMigration.php
src/PaymentGateways/Gateways/PayPalCommerce/PayPalCommerceGateway.php
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-2043]
This PR adds a request to validate the donation form on the server side when the donor clicks on the PayPal Donations smart buttons, this way we can prevent the creation of donations on the PayPal side if the form has some invalid data with custom validation rules that only can be triggered on the server side.
Also, it removes the work around implemented a while ago to validate the billing address block before creating the PayPal donation, this is not more necessary now that we have the validations being triggered on the server-side.
This change can potentially prevent any future problem related to validations not being triggered for the PayPal Donations gateway because now we can ensure that all validations on both sides (client and server) will always be triggered …

Feature: add support to server validations for PayPal Donations gateway

---

src/Campaigns/resources/admin/components/CampaignFormModal/CampaignFormModal.module.scss
src/Campaigns/resources/admin/components/CampaignFormModal/index.tsx
src/Campaigns/resources/admin/components/FormModal/FormModal.module.scss
src/Campaigns/resources/admin/components/MergeCampaign/Form/Form.module.scss
src/Campaigns/resources/admin/components/MergeCampaign/Form/index.tsx

Resolves [GIVE-2035]
This PR changes the font size of the input descriptions used inside the modals on the campaigns page.
- The "create campaign" modal
- The "merge campaign" modal
Open the "create campaign" and "merge campaign" modals and make sure the font size for the input descriptions is displayed in the proper size.
[GIVE-2035]: https://stellarwp.atlassian.net/browse/GIVE-2035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

Refactor: change font-size for modal input descriptions 

---

src/Campaigns/Migrations/MigrateFormsToCampaignForms.php
src/FormMigration/Controllers/MigrationController.php
src/FormMigration/Controllers/TransferController.php
tests/Unit/Campaigns/Migrations/MigrateFormsToCampaignFormsTest.php

Resolves [GIVE-2032]
This PR makes the migrations of Forms to Campaigns also consider V2 forms. It also fixed a problem that was preventing forms with the upgraded status from being associated with campaigns as not-default forms in certain scenarios.
The migrations of Forms to Campaigns.
https://www.loom.com/share/7bf0d4727f944c0da29fd0df9219d7bc?sid=2b9f341f-c61a-4f13-b088-b8600b09afab
1. In a fresh install create a few V2 and V3 forms;
2. Migrate some V2 forms to V3 forms;
3. Install the Give version of this branch;
4. The migration should convert V2 forms to Campaigns;
5. The migration should associate V2 upgraded forms to Campaigns as not-default forms.
-   [ ] …

Refactor: migrate v2 forms to campaigns and add upgraded forms as campaign not-default forms

---

includes/formatting.php
src/Helpers/Utils.php
tests/Unit/Helpers/UtilsTest.php

Resolves [GIVE-2063]
This PR changes the `give_clean()` function to prevent unserializing data by default, now we are unserializing only when the `$allow_serialized_data` is `true`, otherwise, we are returning an empty string when data is serialized.
This PR also improves the regex used in the `containsSerializedDataRegex()` to cover all data types instead of only arrays and objects.
As many places are using the `give_clean()` function, these changes affect the entire codebase, especially the submission of new donations.
V2 form error message:
V3 form error message:
1. Create a V2 and a V3 Donation Form;
2. Create a test donation using the V2 form and in the donor's first name add the following serialized data: `a:1:{s:4:"Test";s:15:"serialize here!";}`
3. Make sure the donation wasn't …

Enhancement: improve data validation for the give_clean() function

---

src/DonationForms/ViewModels/DonationFormViewModel.php

This humble PR adds a class to the root div of a v3 form with the Form Design ID. Something like: `givewp-donation-form-design--classic`. It's purpose is so that when folks add custom styles (especially globally via code) they can use CSS to apply styles to only certain form designs.
V3 form rendering
1. Make a form
2. View the form on the front-end
3. Check the root div for the Form Design class — it should correspond to your selected Form Design
4. Switch Form Designs and check again

Feature: adds a css class for the form design

---

src/Helpers/Utils.php
tests/Unit/Helpers/UtilsTest.php

Resolves [GIVE-2073]
This PR refactors the `containsSerializedDataRegex()` method to ensure it will work with strings containing special characters and encoded strings. It also adds a new sample string to the unit tests to ensure everything is working as expected.
[GIVE-2073]: https://stellarwp.atlassian.net/browse/GIVE-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enhancement: better input validation

---

src/Donors/ListTable/Columns/DonorInformationColumn.php

Resolves [GIVE-1165]
This PR change how we retrieve the donor avar URL in the Donor view, now instead of use the donor ID we are using the donor e-mail to make sure that the proper profile URL will be used.
As a note, the `get_avatar_url()` function, which is used under the hood, accepts the user e-mail or user id, so we were using it wrong before the changes implemented on this PR because the donor id is not the same one of the user id.
The donor's view.
1. Create a test donation using a donor's email that has a Gravatar account set up.
2. Go to the donor's view page and make sure the proper avatar image (the same one from Gravatar) is displayed there.
-   [ ] …

Fix: use email to get avatar URL

---

src/DonationForms/resources/styles/components/_amount.scss

Resolves: [GIVE-2072]
Reference: https://lw.slack.com/archives/C02Q714965S/p1734472242800619
This PR restores the native keyboard access to the radio field for the donation frequency. 
Previous Implementation:
The `Amount` stylesheet was applying `display: none` to the `input[type='radio']` because we have a custom radio button UI for Donation Frequencies in v3 forms. However, this approach inadvertently removed native keyboard accessibility.
Solution:
To restore keyboard accessibility, I’ve updated the implementation to keep the radio button in the DOM while visually hiding it from the HTML flow by positioning it below the form's z-index, allowing it to remain focusable and operable via the keyboard. 
Additional styles were included to better match the focus elements of the Donation …

Fix: Restore keyboard accessibility in donation amount template

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/DataTransferObjects/StripePaymentIntentData.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementRepository.php

Resolves: [GIVE-1948]
Related: https://github.com/impress-org/givewp/pull/7259
This removes the `statement_descriptor` from Stripe Payment Element Gateway.  This is the result of a Stripe api change to the attribute for card payments.  Since Payment Element is dynamic, the safest & simplest option is to remove the attribute and rely on the statement_descriptor set on the account level instead of the request.
https://support.stripe.com/questions/use-of-the-statement-descriptor-parameter-on-paymentintents-for-card-charges
Stripe payment element
N/A
Zip: https://github.com/impress-org/givewp/actions/runs/12715146778
- Donate using v3 forms and Stripe Payment Element w/ different payment methods including credit card and make sure everything works properly.
-   [ ] Acceptance criteria …

Refactor: remove statement_descriptor from Stripe Payment Element Gateway

---

composer.json

fix: 'vendor\stellarwp\validation\bin\set-domain' is not recognized as an internal or external command, operable program or batch file.
When I want to install the plugin on dev Windows setup, the `composer install` throws this issue :
```shell
> vendor/stellarwp/validation/bin/set-domain domain=give
'vendor\stellarwp\validation\bin\set-domain' is not recognized as an internal or external command, operable program or batch file.
```
Installation.
1. On Windows setup
2. `git clone git@github.com:impress-org/givewp.git give`
3. `cd give`
4. `composer install`

Fix: Explicitly execute script with PHP for Windows compatibility

---

src/EventTickets/Migrations/AddAmountColumnToEventTicketsTable.php

When running automated tests, database tables are truncated while preserving the effects of migrations. Recently, we introduced a migration that modifies the `give_event_tickets` table by adding a new `amount` column. However, since migrations are executed repeatedly after each database refresh (before most tests run), this led to an error when attempting to add the `amount` column multiple times.
To address this issue, this PR replaces the existing query execution method with a conditional check using `maybe_add_column`. This ensures the `ALTER TABLE` query is only executed if the column does not already exist, preventing redundant operations and errors.
Note: since a reformat operation has been performed in the file, note that the main change is located at the line 71.
Event Tickets …

Fix: Prevent duplicated column error in Event Tickets migration

---

src/Campaigns/Actions/RegisterCampaignBlocks.php
src/Campaigns/Actions/RegisterCampaignIdRestField.php
src/Campaigns/Blocks/CampaignTitleBlock/block.json
src/Campaigns/Blocks/CampaignTitleBlock/edit.tsx
src/Campaigns/Blocks/CampaignTitleBlock/editor.scss
src/Campaigns/Blocks/CampaignTitleBlock/index.ts
src/Campaigns/Blocks/CampaignTitleBlock/render.php
src/Campaigns/Blocks/blocks.ts
src/Campaigns/Blocks/shared/components/CampaignDropdown.tsx
src/Campaigns/Blocks/shared/components/CampaignSelector.tsx
src/Campaigns/Blocks/shared/hooks/useCampaign.ts
src/Campaigns/Blocks/shared/hooks/useCampaignId.ts
src/Campaigns/Blocks/shared/hooks/useCampaigns.ts
src/Campaigns/Blocks/shared/utils/init-block.ts
src/Campaigns/ServiceProvider.php
wordpress-scripts-webpack.config.js

Resolves [GIVE-1959]
This pull request lays the foundation for future Campaign-related blocks by introducing key structural elements. The updates in this PR include:
- **Dynamic Block Registration**: Registers blocks dynamically based on their block.json files.
- **Campaign Page REST API**: Adds `campaignId` as a field to the REST API response for the Campaign Page CPT.
- **Custom Hooks and Shared Components**: Introduces reusable hooks and components to simplify campaign selection or retrieval from context within campaign blocks.
- **Initial Campaign Title Block**: Adds a basic Campaign Title block to serve as a reference and model for upcoming blocks.
These changes establish a scalable and flexible structure for Campaign blocks, enabling more streamlined development of future features. …

Feature: Add campaign title block

---

src/Donations/Repositories/DonationRepository.php
src/Donors/Repositories/DonorRepository.php
tests/Unit/Donations/Repositories/TestDonationRepository.php
tests/Unit/Donors/Repositories/TestDonorRepository.php

Resolves [GIVE-2075](https://stellarwp.atlassian.net/browse/GIVE-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
This updates our donor and donation repositories to use the native WP meta functions for adding meta instead of directly inserting using SQL.  
Before this, we were innocently deviating from how WordPress stores meta values, effectively bypasses some of the extra filters/sanitization of values.  This resulted in problems downstream when retrieving the data.  
So the lesson learned here is to _always_ use the native WordPress api functions for storing and retrieving meta 😄.
- Creating new donations and donors (v2 and v3 forms)
_Make sure both v2 and v3 forms are working as expected._
- Create donation using v3 form and make sure …

Refactor: update meta persistence in donor and donation repositories

---

src/Donations/Properties/BillingAddress.php
src/Subscriptions/Models/Subscription.php
src/Subscriptions/Repositories/SubscriptionRepository.php
tests/Unit/Subscriptions/Models/TestSubscription.php
tests/Unit/Subscriptions/Repositories/TestSubscriptionRepository.php

This adds some quality of life methods to subscription model including:
- `createRenewal`
- `shouldCreateRenewal`
- `shouldEndSubscription`
The goal is to unify the way we are dealing with renewals across our gateways.
I noticed throughout different gateways, we are duplicating a lot of the same logic for handling the renewals and are not consistent with the properties being used in the creation of the donation model.  For example, sometimes we use the donor's first name vs the initial donation's billing first name, the billing address is not often accounted for, various properties are missing, etc..  With a unified api we can be consistent with the renewal values and which properties are being carried over from the subscription, initial donation, donor, invoice, etc.
This was largely …

Feature: add renewal methods to subscription model

---

src/EventTickets/Actions/EnqueueFormBuilderScripts.php
src/EventTickets/resources/blocks/EventTicketsBlock/Edit/BlockPlaceholder.tsx
src/EventTickets/resources/components/EventTicketsList.tsx
src/EventTickets/resources/components/types.ts
src/EventTickets/resources/templates/EventTickets/EventTicketsListHOC.tsx
src/EventTickets/resources/templates/EventTickets/index.tsx
src/EventTickets/resources/templates/EventTickets/types.ts

Resolves [GIVE-2112]
Per designs, we have a title above the ticket list in the Event Tickets template, but due to a mistake in its implementation, it was being  rendered as an empty tag. This pull request corrects this issue by directly setting its content in the template. As a consequence of this new implementation, all references to the `ticketLabel` as an attribute are being removed.
[GIVE-2112]: …

Fix: Set content for missing title in event tickets template

---

assets/src/js/frontend/give-misc.js

Resolves: [GIVE-931](https://stellarwp.atlassian.net/browse/GIVE-931)
`DonationFormBlock` Reference: https://github.com/impress-org/givewp/blob/develop/src/DonationForms/Blocks/DonationFormBlock/resources/app/Components/ModalForm.tsx
Problem:
The issue occurs when offline gateways (e.g., Stripe Payment Element) trigger a page refresh after a donation is processed. This refresh happens when the gateway redirects the user back to the initial page, causing any open modals (including the modal rendering the donation receipt) to close.
Solution:
To resolve this, the PR introduces the following approach:
An event listener that checks the redirect/donation completed status on page load via the URL search params was included. If the user is coming from a redirected gateway (e.g., after completing …

Fix: Display donation receipt in Form Grid modal after offline gateway redirect

---

src/Campaigns/Blocks/CampaignCover/Icon.tsx
src/Campaigns/Blocks/CampaignCover/block.json
src/Campaigns/Blocks/CampaignCover/edit.tsx
src/Campaigns/Blocks/CampaignCover/editor.scss
src/Campaigns/Blocks/CampaignCover/index.tsx
src/Campaigns/Blocks/CampaignCover/render.php
src/Campaigns/Blocks/blocks.ts
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Settings.tsx
src/Campaigns/resources/admin/components/CampaignFormModal/index.tsx
src/Campaigns/resources/admin/components/Inputs/Upload/index.tsx
src/Campaigns/resources/admin/components/Inputs/Upload/styles.scss

Resolves [GIVE-1505] /  [GIVE-1973]
- Removes references of video support on the  media `Uploader` from the campaign settings and creation modal. 
Slack conversation reference: https://lw.slack.com/archives/C04SLRDD9CK/p1738173558503109
- Improved styles on the `Uploader` components.
- Adds Campaign Cover Block to the block editor. This block's image can only be updated from the campaign settings.  A placeholder will be displayed if no image is set from the campaign settings. The image supports alignment, resizing & duotone.
Campaign settings & Campaign Cover Block
https://www.loom.com/share/b168317f31ef40ba9a3a1add7cea7b81?sid=70ad126a-bde3-476a-8b0f-31e9b76d5773
- Add the campaign cover block without an image, verify a placeholder is displayed.
- Add the campaign cover block with an …

Feature: add Campaign Cover Block

---

src/DonationForms/Actions/ConvertDonationFormBlocksToFieldsApi.php
src/FormBuilder/BlockTypes/TextBlockType.php
src/Framework/Blocks/BlockType.php
tests/Unit/FormBuilder/BlockTypes/TestDonationAmountBlockType.php
tests/Unit/FormBuilder/BlockTypes/TestTextBlockType.php
tests/Unit/Framework/Blocks/TestBlockType.php

Resolves [GIVE-2163]
This updates the text block conversion to use the first class `TextBlockType`.
This is the first in series approach to moving away from the untyped `$block->getAttribute()` and toward specific [block types](https://github.com/impress-org/givewp/pull/7195) with typed block attributes in the form of object properties.
This also caught and fixes an issue with the `BlockType` class so it will always cast values as intended.  So if you are expecting a boolean and for some reason the block does not have the attribute it will still return a boolean type instead of null.  This makes sure the block type property types are always valid types and can be confidently used in typed methods in the fields api.
- Custom text block fields in the VFB
N/A
- Make sure new and existing …

Refactor: update text block conversion to use text block type

---

composer.json
composer.lock
give.php
includes/class-give-license-handler.php
src/VendorOverrides/AdminNotices/AdminNoticesServiceProvider.php

Presently, when a customer purchases a plan or add-on license, they have to manually activate the license within the product after installing it. This hasn't been a major pain point, but it's certainly an extra step and may confuse some folks. Further, as we support cross-sells, it becomes a nuisance to receive the product and have to take extra steps.
This PR introduces support for add-ons to come bundled with a `GIVE_LICENSE.php` file that contains the license. If this file is found and hasn't been activated, then it's automatically activated.
https://www.loom.com/share/51c0a14786c044c8bb85aa35b5fbb733
The contents of the license file will be:
```php
<?php return 'license-hash-goes-here'
```
The reason this is a PHP file and not just a plan text file is because this allows the PHP …

Feature: automatically activates bundled add-on licenses

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/index.tsx

Resolves GIVE-2031
This PR updates the `<StatWidget>` component to prevent a `NaN` error while fetching data.
Additionally, a non-breaking space is used to prevent content shifting.
- Hard-reload the page (with cache disabled via browser tools)
- Toggle between tabs in the Overview screen

Fix: Prevent NaN error in Campaign Overview Stat Widget

---

src/Campaigns/Actions/RegisterCampaignBlocks.php
src/Campaigns/Blocks/CampaignDonations/resources/views/render.php
src/Campaigns/Blocks/CampaignDonors/resources/views/render.php
src/Campaigns/Blocks/DonateButton/render.php
src/Campaigns/Controllers/CampaignRequestController.php
src/Campaigns/Routes/RegisterCampaignRoutes.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/CampaignDetailsPage.module.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/ColorControl/Icons/CheckIcon.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/ColorControl/Icons/EditIcon.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/ColorControl/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/ColorControl/styles.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Settings.tsx

Resolves [GIVE-1385]
This Pull Request introduces new fields in Campaign Settings for setting Theme Colors, which will be used in related UI elements such as Campaign Donations, Campaign Donors, and Campaign Donate Button blocks.
It is important to note that colors must be applied individually to each block, as each block renders in a different Campaign context.
Campaign Settings page
_Theme Color Settings_
_Sample of color being applied to a campaign block_
- Go to the Campaign Settings tab
- Set theme colors for that campaign
- Edit the campaign page, adding some campaign specific blocks like Campaign Donors, Campaign Donations and Donate Button blocks
- See how those blocks follow the color selected in the Campaign Settings
-   [ ] Acceptance criteria satisfied and marked in related …

Feature: Register campaign theme color settings

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/DefaultForm/index.tsx

Resolves [GIVE-2126]
This Pull Request removes the Edit button from the Default Form widget in the Campaign Overview tab. Since the button’s functionality has not been fully implemented, we have decided to defer its development for now. Removing it prevents confusion and ensures a better user experience until the feature is properly implemented.
Campaign Overview tab
_Before_
_After_
Confirm that there is no Edit button in the Default Form widget in the Campaign Overview tab. …

Refactor: Remove Edit button from default form widget

---

src/Campaigns/Blocks/CampaignStats/Icon.tsx
src/Campaigns/Blocks/CampaignStats/app.tsx
src/Campaigns/Blocks/CampaignStats/block.json
src/Campaigns/Blocks/CampaignStats/edit.tsx
src/Campaigns/Blocks/CampaignStats/index.tsx
src/Campaigns/Blocks/CampaignStats/render.php
src/Campaigns/Blocks/CampaignStats/styles.scss
src/Campaigns/Blocks/blocks.ts
wordpress-scripts-webpack.config.js

Resolves: [GIVE-1987]
This add the Campaign Stats block. Users should be able to filter between "Top Donation" & "Average Donation" for the selected campaign.
https://github.com/user-attachments/assets/7cb1fdc1-050c-4e5b-b7b6-94319ba7e908
- Add the Campaign Stats block
- Filter between  "Top Donation" & "Average Donation" - verify the amounts and title change
- Verify changes on frontend & in admin
[GIVE-1987]: …

Feature: add campaign stats block

---

includes/class-give-license-handler.php

In #7709 I introduced the ability for licenses to come bundled with add-ons. As part of this the registered addons were stored as an instance of `Give_License` instead of just the plugin basename. To keep things backwards compatible, I updated the `Give_License::get_license_addons()` function to still return an array of basenames. I felt good.
Quietly, alas, I did something silly and was using `wp_list_pluck` to retrieve the basenames from the addons.  This is a no-no because `Give_License::$plugin_basename` is a private property, so a function can't grab that property and return it. 🤦‍♂️ 
This PR resolves the issue by retrieving the property within the context of the class, safely accessing the private property.
License updates
Make sure that refreshing licenses and updating plugins is …

Fix: resolves fatal error when updating plugins

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/GoalProgressChart/index.tsx

Resolves [GIVE-2174]
This updates the goal progress percentage calculation so we can goal progress is an integer and does not exceed 100.
The goal progress widget
Zip: https://github.com/impress-org/givewp/actions/runs/13374370469
- Create a campaign with a small goal of amount
- Make several donations with varying float amounts
- Make sure the goal progress percentage is a whole number and does not exceed 100
[GIVE-2174]: …

Fix: ensure campaign goal progress percentage is an integer and does not exceed 100

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx

Resolves GIVE-2143
This PR addresses a bug on initial publish of a campaign where the status update is not persisted due to a race condition with the `isDirty` check in the submit handler.
This is resolved by adding a fallback check for an updated status when `!isDirty`.
Create a new Campaign and click "Publish campaign".

Fix: Force campaign save on initial publish

---

src/Campaigns/Actions/RegisterCampaignPagePostType.php
src/Campaigns/Repositories/CampaignPageRepository.php
tests/Unit/Campaigns/Repositories/CampaignPageRepositoryTest.php

Resolves [GIVE-2141]
This PR enables `title` support for Campaign Pages, which default to the title of the related Campaign.
Create a new Campaign and edit the Campaign Page.
[GIVE-2141]: https://stellarwp.atlassian.net/browse/GIVE-2141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Campaign pages support titles

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Decorators/SubscriptionModelDecorator.php
tests/Feature/Gateways/Stripe/StripePaymentElement/Webhooks/Listeners/InvoicePaymentSucceededTest.php

Resolves [GIVE-2167]
This pull request includes changes to the `SubscriptionModelDecorator` class and its related tests to simplify the code and improve maintainability. The most important changes include the removal of unused imports, updating methods to use model methods, and refactoring the test cases.
Code simplification and maintainability improvements:
* [`src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Decorators/SubscriptionModelDecorator.php`](diffhunk://#diff-7046fcff8ed3257b07f95e6183405f4e095366411d17d33f4c11ae192be9cbf6L5-L7): Removed unused imports to clean up the code.
* [`src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Decorators/SubscriptionModelDecorator.php`](diffhunk://#diff-7046fcff8ed3257b07f95e6183405f4e095366411d17d3 …

Refactor: update Stripe subscription model decorator to use subscription model methods directly

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/RevenueChart.tsx

Resolves [GIVE-2146]
This PR sets a minimum value for the y-axis of the Campaign revenue chart to prevent the scale from dropping below 0.
| --- | --- |
| ![Screenshot from 2025-02-07 13-20-50](https://github.com/user-attachments/assets/ccda73a9-8ea0-496a-9924-2399d73ea4c3) | ![Screenshot from 2025-02-07 13-21-03](https://github.com/user-attachments/assets/d367fcd0-f706-451a-a262-690397336dde) |
Create a Campaign and make a couple of donations then view the revenue chart on the campaign overview screen.
-   [x] [Self …

Fix: Set a minimum for the y-axis of the Campaign revenue chart

---

src/DonationForms/V2/resources/components/DonationFormsRowActions.tsx

Resolves [GIVE-2184]
This hides the trash option on the campaign's donation form list table when hovering over a default form.
This is a simple preventative measure to avoid customers deleting a default form, which could have unexpected behaviours.
The campaign's donation forms list table
ZIP: https://github.com/impress-org/givewp/actions/runs/13372945883
- create a campaign
- go to donation forms table
- make sure you don't see a trash icon on the default form
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX …

Refactor: hide trash option for campaign default form

---

src/Campaigns/Repositories/CampaignRepository.php
tests/Unit/Campaigns/Repositories/CampaignRepositoryTest.php

We recently [made an update ](https://github.com/impress-org/givewp/pull/7730)to allow nullable end dates in campaigns.  However, we missed updating this in the campaign update functionality and this was preventing the campaign from being updated.  
This update ensures our end date can be null during campaign update.
The campaign update.
This is what was happening 😄 
- Update/publish the campaign
- You should not receive an error

Fix: conditionally update campaign end date

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx

This PR resolves the issue where the campaign status cannot be updated because the status change action triggered validation. The problem is resolved by removing the validation from the update status action.
Campaign settings
Create a campaign
Delete the value for the goal type and click Update
The validation should prevent campaign settings be saved
Now archive the campaign (campaign status should be updated)

Fix: Campaign status change - archive

---

package.json

Resolves [GIVE-2138]
Reference: https://github.com/impress-org/form-builder-library/pull/13
Update package.json to better handle certain currencies with the CurrencyInput component .
Donation Levels in the form builder
N/A
Create a VFB form.
Setting your Give currency to MXN peso from the currency settings.
Update your browser language to reflect generic Spanish.
Go to the build settings of your form -> update the donation level amounts and ensure that adding a number works properly. This includes adding or removing numbers, the UI of the input setting and the UI in the build preview.
Might be good to double check the frontend is not affected.
-   [ ] Includes unit …

Chore: update form-builder-library to 1.7.1

---

includes/payments/actions.php

- Skip recording a payment status change in the donation note if the status remains unchanged.
Updating donation status to Complete, but the donation status is already set as Complete. A donation note for payment status change still will be recorded.
Try updating the donation status programatically, example:
```
$donation_status = DonationStatus::COMPLETE(); // use current donation status, ie: complete
$donation = Donation::find(1);
$donation->status = $donation_status;
$donation->save();
```
No more redundant updates on payment status change.

Fix: Skip Recording Payment Status Change If No Modification

---

includes/gateways/stripe/includes/class-give-stripe-payment-intent.php

In the request https://givewp.featureos.app/p/more-context-for-stripe-declined-messages, I suggest two points. This is the first one.

Fix: Add a message for the donor when his card is declined

---

src/Campaigns/resources/admin/components/Inputs/Upload/index.tsx

Resolves [GIVE-2127]
Our `Uploader` component is configured to filter the library to display only images. However, when uploading a video, it could still be selected. This Pull Request adds an additional check for the selected attachment type, displaying an alert if it is not an image.
Media Uploader
1. Open a Campaign Settings page
2. Upload a video (eg.: mp4 file) to the Cover setting
3. Click the "Use this media" button
4. Confirm that an alert is received and the video is not selected
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-re …

Refactor: Remove cover video support

---

includes/class-give-license-handler.php

I noticed that when an auto activation licensing error occurs it doesn't look quite right. I realized that there was a typo in `isDmissibile()` — should be `dismissible()`, and auto-paragraph should be enabled.
It also provides a fallback reason for an error that might be null and wraps the license in `<code>` tags for readability.
Just the notices displayed when a bundled license error occurs.
Note, to test you will need an add-on with the `PLUGIN_LICENSE.php` file included in the root. Reach out to @JasonTheAdams  for one.
The easiest way to test this without setting up the GiveWP website locally is to:
* Add the following to `includes/class-give-license-handler.php` on line 348:
```php
$check_license_res['success'] = null;
```
This will simulate a server response failure
* Make sure …

Fix: corrects license handler notice dismissibility and UI

---

src/FormBuilder/resources/js/form-builder/src/components/onboarding/transfer/TransferDialog.tsx

Resolves [GIVE-2276]
It also replaces the _"Go back to your donation form list"_ old CTA with this new one: _"Go back to campaign form list"_
The transfer data "Completed" dialog.
Follow the steps of this video and make sure it's not redirecting to the "All Forms" page anymore: https://www.loom.com/share/b436a9fccb7b4d9dba13706b09325794?sid=989fa073-52aa-4cdb-99c7-29c7d44cb480
[GIVE-2276]: https://stellarwp.atlassian.net/browse/GIVE-2276?atlOrigin=eyJpIjoiNWR …

Fix: redirect user to the campaign form list after migrate data from v2 to v3 forms

---

src/Campaigns/Blocks/CampaignDonations/render.php
src/Campaigns/Blocks/CampaignDonors/render.php
src/Campaigns/Controllers/CampaignRequestController.php

Resolves [GIVE-2278]
This PR fixes a problem related to the wrong ordering of the donations by amount. It was happening because the `amountMeta.meta_value` is stored in a `longtext` column,  so all we needed to do to fix that was cast it to the proper type like this: `ORDER BY CAST(amountMeta.meta_value AS DECIMAL) DESC`
- Top donations block
- Top donors block
1. Create a new campaign;
2. Create between 3 and 5 donations using different donors (if you are logged in, it will be counted as a single donor);
3. Make sure the top donations and top donors are ordered by the amount in the proper order. Eg.: $100, $50, $10
**Important:** This bug didn't happen in all sites, but in new local websites using LocalWP I was open to reproducing it. More details here: …

Fix: donation amounts are not displayed in the proper order on the top donations block

---

src/Onboarding/Setup/templates/index.html.php

Resolves [GIVE-2266]
This pull request includes changes to the `src/Onboarding/Setup/templates/index.html.php` file to update the terminology and functionality related to donation forms and campaigns. The most important changes include replacing references to donation forms with campaigns and updating URLs accordingly.
Terminology and functionality updates:
* Removed the import statement for `DonationForm` as it is no longer needed.
* Changed the variable from `$form` to `$campaign` and updated the method to retrieve the campaign by form ID.
* Updated the URL for customizing the campaign, replacing the form-related URL with the campaign-related URL.
* Modified the title to refer to creating a campaign instead of a donation form.
* Updated the button text from "Customize form" to …

Refactor: Replace Form with Campaign in step 1 of Setup Guide

---

src/DonationForms/V2/resources/components/DonationFormsListTable.tsx
src/Views/Components/ListTable/ListTablePage/index.tsx

Resolves [GIVE-2280]
Although we have removed the inline option to delete a campaign’s default form, users are still able to do so through bulk actions. This pull request prevents that by:
1.	Adding support for a new `isIdSelectable` method, allowing each action to determine whether an ID should be included in the list of IDs to be processed.
2.	Implementing the `isIdSelectable` method in the `trash` action to filter out the default form ID if it has been selected.
If only the default form is selected, the behavior remains unchanged—it will not open the modal, as there are no valid selections. Ideally, we should provide more context to users in the future when this occurs. However, for now, this solution is sufficient, as the primary goal is to prevent users from deleting their campaign’s …

Fix: Prevent trashing a campaign default form through bulk actions

---

src/Campaigns/Blocks/CampaignCover/block.json
src/Campaigns/Blocks/CampaignCover/edit.tsx
src/Campaigns/Blocks/CampaignCover/render.php

There were issues with how the campaign cover block was being rendered in the block editor including the resize box and non functional style features.  This PR removed the resize box and non functional style features to simplify this block.  We can always add more features later.
The campaign cover block
**Before**
**After**
- Use the campaign cover block in various ways, making sure it works as expected.
- Also try out the image alignment like "wide"and make sure it doesn't go off the page.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self …

Refactor: simplify campaign cover block

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/RevenueChart.tsx

Resolves #
This PR fixes the revenue graph height.
Currently our revenue graph is set to a fix height which leaves a lot of whitespace beneath the parent container. I changed the height of the revenue graph from fix to fill(100%) where it takes up the space of the parent container.
Changes the height of the revenue graph
Before
After
Check the revenue graph of a campaign to make sure if it fills the height of the parent container.

Fix: campaign revenue graph height

---

includes/post-types.php
src/Campaigns/Actions/AddNewBadgeToAdminMenuItem.php
src/Campaigns/ServiceProvider.php
src/DonationForms/V2/DonationFormsAdminPage.php
tests/includes/legacy/tests-post-types.php

Resolves [GIVE-2288]
This updates our top level menu item to "GiveWP" and also adds a "New" menu badge.
It also removes the "All forms" menu item.
These updates will decrease confusion and draw the attention of existing users to campaigns.
The admin menu item
Zip: https://github.com/impress-org/givewp/actions/runs/13725656658
You should see the badge when:
- You are upgrading from a version before 4.0.0
You should not see the badge when:
- You install Give 4.0.0 or higher for the first time
- You are upgrading from a version after 4.0.0
- After you visit the campaign landing page
-   [ …

Feature: add "NEW" menu badge to GiveWP admin menu

---

src/Campaigns/CampaignDonationQuery.php
src/Campaigns/Routes/GetCampaignComments.php
src/Campaigns/Routes/GetCampaignRevenue.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/RevenueChart.tsx
src/DonationForms/DonationQuery.php
tests/Unit/Campaigns/CampaignDonationQueryTest.php
tests/Unit/Campaigns/Routes/GetCampaignRevenueTest.php
tests/Unit/Campaigns/Routes/GetCampaignStatisticsTest.php

Resolves [GIVE-2323]
This replaces the usage of `_give_completed_date` meta in our campaign/donations query to use the donation created date aka the `post_date`. The former meta is an older concept that is not reliable and is not the accurate date of a donation.  The donation created date is the only date we need to run our donation queries.  To test this out you can create a donation and change the date on donation details.  The campaign revenue graph should be reflected.
This also updates the campaign graph yAxis to format the values in currency/locale.
Finally, this fixes the issues where the campaign revenue request was hard-coding a date range of 7 days for the campaign revenue graph, resulting in data point skips when data exists beyond 7 days.
- The campaign overview stats/graph
- …

Refactor: improve campaign revenue graph formatting and request data

---

src/Campaigns/CampaignDonationQuery.php
src/Campaigns/CampaignSubscriptionQuery.php
src/Campaigns/DataTransferObjects/CampaignGoalData.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/GoalProgressChart/index.tsx
src/Campaigns/resources/admin/components/types.ts
src/Subscriptions/Factories/SubscriptionFactory.php
tests/Unit/Campaigns/CampaignSubscriptionQueryTest.php

Resolves [GIVE-2290]
This Pull Request enhances the Campaign Goal Progress Chart component by adding support for multiple goal types. Previously, the chart always displayed progress as “Amount Raised”, regardless of the selected goal type.
With this update:
- The widget correctly displays progress based on the selected goal type.
- Currency formatting is now applied only for `amount` and `amountFromSubscriptions` goal types.
Under the hood:
- Added a new `CampaignSubscriptionQuery` class.
- Replaced all instances of the `GoalType` enum from `DonationForms` in the `CampaignGoalData` class with the `CampaignGoalType` enum from `Campaigns`.
- Updated the `getActual` method in the `CampaignGoalData` class to implement distinct query builders depending on the selected campaign goal type …

Feature: Support Multiple Goal Types in Campaign Goal Progress Chart

---

src/Campaigns/Migrations/MigrateFormsToCampaignForms.php
tests/Unit/Campaigns/Migrations/MigrateFormsToCampaignFormsTest.php

The current form to campaign migration is settings the start and end dates as the form goal dates.  This is not correct as these are separate concepts.  The start date of a campaign should be when the form was created and there should be no end date (end date is not a concept yet).
This will ensure the lifespan of a form is migrated to a campaign and the revenue tracking will be accurate because it uses the same dates.
This also protects against potential type errors using arrap_map as results can return null.
- The Form to Campaign migration
N/A
- Migrate forms to campaigns and make sure the dates are correct.
-   [ ] Reviewed by the …

Fix: campaign migration dates

---

composer.json
composer.lock
src/Donations/CustomFields/Controllers/DonationDetailsController.php
src/Donors/CustomFields/Controllers/DonorDetailsController.php
src/FormBuilder/Routes/RegisterFormBuilderPageRoute.php

Resolves [GIVE-2279]
This fixes various php 8.4 warning when interacting with campaigns.
- Not much is affected.  The Money library was updated but only to a minor version that suppresses php warnings.
These warnings will be removed:
- Enabled `WP_DEBUG` and `WP_DEBUG_DISPLAY`
- Make sure no php warnings are showing in the admin
[GIVE-2279]: https://stellarwp.atlassian.net/browse/GIVE-2279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

Fix: php 8.4 warnings

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/DateRangeFilters.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/PercentChangePill.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/StatWidget.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/styles.module.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/CampaignStats/types.ts
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Overview.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx

The campaign overview was getting hard to manage and needed some UI improvements.  This PR cleans up the overview components for better maintainability and improves the widget data loading (with loading spinner), percentage calculations and some styling.
The campaign overview stat widgets.
- Create a campaign with donations over a period of time
- View the campaign overview page
- You should now see a loading spinner on the stat widgets
- The stat widget percentage styling is also improved
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-r …

Refactor: improve Campaign overview stats styling and loading

---

src/Campaigns/Repositories/CampaignRepository.php

This PR resolves the issue with the donation count for merged campaigns.  The problem was in donation meta not being updated with the correct campaign id after merge.
Campaign merge
Create a minimum of two campaign
Make donations to each of them
Merge campaigns
Verify that the donation count is correct

Fix: Merged campaigns donation count

---

src/DonorDashboards/resources/js/app/components/button/index.tsx

Resolves #7794
The issue mentioned that the text wasn't displaying in the "Download Receipt" button on the Donor Dashboard.
After some investigation, I determined that this was caused by the background generated via :before overlapping the button's content and obscuring it.  
I wanted to modify the CSS to assign a stronger z-index to the content than to the background.  
The problem: Pure text nodes can't be styled with CSS.
So, I had to wrap the button's content in an HTML tag to give it a z-index that would make it visible.
I wanted to use a \<div\> tag that would match the behavior of a \<button\>.
But I realized that the CSS was already written for content encapsulated in a \<span\>, and I followed the apparent intent of the code by using this tag, which is therefore already styled to …

Fix: content of Button should be contained in a span for z-index setting

---

includes/gateways/stripe/includes/class-give-stripe-payment-intent.php

When the payment intent cannot be create due to a Stripe error (Ex:  `Your card's security code is incorrect`.), there is an Exception.  Some functions as `handlePaymentIntentStatus()` cannot access to status/id, and a new exception is created. There is no point in going any further, and we can return directly to the checkout form as in `class-give-stripe-payment-method.php`.
Errors in log:
```
[19-Feb-2025 13:03:38 UTC] PHP Warning:  Attempt to read property "id" on bool in /wp/wp-content/plugins/give/src/PaymentGateways/Gateways/Stripe/ValueObjects/PaymentIntent.php on line 44
[19-Feb-2025 13:03:38 UTC] PHP Warning:  Attempt to read property "status" on bool in /wp/wp-content/plugins/give/src/PaymentGateways/Gateways/Stripe/ValueObjects/PaymentIntent.php on line 53
```
Message for the …

Return to the checkout form when the payment intent is created

---

src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-2265]
This ensures our donate button is not hidden when PayPal hosted fields are present. 
- PayPal donations
Notice the donate buttons (showing validation by default when hosted fields and smart buttons are present)
ZIP: https://github.com/impress-org/givewp/actions/runs/13910574470
- Connect to PayPal using [advanced card processing]( https://givewp.com/documentation/core/payment-gateways/paypal-donations/#standard-card-processing-vs-advanced-card-processing)
- Create a v3 form with PayPal donations enabled
- Make sure the donate button is present when hosted fields are being displayed.  Note: this is when it says "or pay with card" - not the button that shows Debit / Credit option.
- Make sure the donation goes through properly
- Make sure the donate button is hidden …

Fix: only hide donate button from PayPal if hosted fields are not present

---

src/Campaigns/Blocks/CampaignDonations/block.json

Resolves [GIVE-2302]
This pull request includes a change to the `src/Campaigns/Blocks/CampaignDonations/block.json` file to update the default sorting behavior for donations.
* [`src/Campaigns/Blocks/CampaignDonations/block.json`](diffhunk://#diff-8a19380a1b72c5c85eed4af65e6f0e18e8074d1452204529853088ffc2603f10L31-R31): Changed the default value of the `sortBy` property from "top-donations" to "recent-donations".
Campaign Donations block
- In a campaign page, add a Campaign Donations block.
- Confirm it defaults to Recent Donations in its Sort By attribute.
-   [x] [Self …

Refactor: Change Campaign Donations block sort by attribute to "Recent Donations"

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx

Resolves [GIVE-2297]
This pull request includes a minor change to the CampaignDetailsPage component. It prevents the default action when clicking the button to toggle the context menu, ensuring that the Settings form is not submitted.
* [`src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx`](diffhunk://#diff-461710b1cb6206c00012b28588b98d4b62b17ee4e12e3795909d58826cb0f860L234-R237): Added `e.preventDefault()` to the button click event handler to prevent the default action.
Campaign Settings page
Confirm that clicking the “More” button to open the context menu on the Campaign Settings page does not trigger the Update Campaign action.
-   [ ] …

Fix: Prevent the “More” button from triggering form submission

---

src/Campaigns/Blocks/CampaignDonations/resources/views/render.php
src/Campaigns/Blocks/CampaignDonors/resources/views/render.php
src/DonationForms/Blocks/DonationFormBlock/Controllers/BlockRenderController.php

Resolves [GIVE-2303]
This pull request includes several changes to improve the rendering logic and documentation in the `CampaignDonations` and `CampaignDonors` blocks and the `BlockRenderController` class. The most important changes include updating the `BlockRenderController` `render` method to return a mocked button when inside the editor.
Improvements to rendering logic:
* [`src/Campaigns/Blocks/CampaignDonations/resources/views/render.php`](diffhunk://#diff-576c57f1c9320d16476eeffb43f71d3b96b8416eb64502be47d386a8a6b24db6L35-R38): Updated the `BlockRenderController` call to directly pass the parameters instead of using an array.
* [`src/Campaigns/Blocks/CampaignDonors/resources/views/render.php`](diffhunk://#diff-b081880b048cae2c325b6cdbb7d649e95ca56872c896bc18392c3ae98338df82L35-R39): …

Fix: Render mocked button in Campaign blocks only in the editor

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Settings.tsx
src/Campaigns/resources/admin/components/CampaignFormModal/index.tsx
src/Campaigns/resources/admin/components/CampaignFormModal/types.ts
src/Campaigns/resources/admin/components/types.ts
src/Campaigns/resources/admin/constants/goalInputAttributes.ts
src/Campaigns/resources/types.ts

Resolves [GIVE-2298]
This pull request refactors the management of goal input attributes in the Campaigns module by centralizing the logic into a single utility function. This improves code maintainability and reduces redundancy.
The primary objective of this change is to fix an issue in the Campaign Settings page where goal labels were hardcoded and did not update when the goal type changed. To address this, the labels from the Create Campaign modal were moved to a utility file, enabling reuse in both the modal and the Campaign Settings page.
Refactoring goal input attributes:
* [`src/Campaigns/resources/admin/constants/goalInputAttributes.ts`](diffhunk://#diff-520c83f9b5895872f4cb285aca37c8f93b23b4c7d8396ad38bc7a3314f6c62d2R1-R58): Added a new utility function `getGoalInputAttributes` …

Refactor: Goal setting labels to update dynamically when Goal Type changes

---

src/Campaigns/Blocks/CampaignDonations/index.tsx
src/Campaigns/Blocks/CampaignDonors/index.tsx

Resolves [GIVE-2308]
This pull request updates the icon displayed in the Campaign Donations and the Campaign Donors blocks.
* [`src/Campaigns/Blocks/CampaignDonations/index.tsx`](diffhunk://#diff-29e916fdf58e1636bef0b4d787d6ac40675aebf445a1399904712192467fec56L1-R11): Renamed from `index.ts` and updated the icon to use `GiveIcon` with a grey color. Added a `save` function that returns `null`.
* [`src/Campaigns/Blocks/CampaignDonors/index.tsx`](diffhunk://#diff-29e916fdf58e1636bef0b4d787d6ac40675aebf445a1399904712192467fec56L1-R11): Renamed from `index.ts` and updated the icon to use `GiveIcon` with a grey color. Added a `save` function that returns `null`.
Campaign Donations and the Campaign Donors blocks
Confirm the icon has been replaced in the blocks and that nothing else has changed. …

Refactor: Replace campaign blocks icons with Give icon

---

src/Campaigns/Blocks/DonateButton/render.php

Resolves: [GIVE-2305]
This fix ensures that the "Donate" button on the campaign page is hidden when the associated donation form is not published. Previously, the button would render even while the donation form was in draft.
Campaign page
Donate button block
- Publish a campaign.
- Ensure the default form is in draft mode.
- View the campaign page -> the donate button should NOT render.
- Publish the default form.
- View the campaign page -> the donate button should render.
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code …

Fix: hide donate button from campaign page if form is not published

---

src/Campaigns/DataTransferObjects/CampaignGoalData.php
src/Campaigns/ListTable/Columns/GoalColumn.php
src/Campaigns/Routes/RegisterCampaignRoutes.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Settings.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx

Currently, campaigns require a goal.  However, forms do not.  So when an existing form is migrated to a campaign and a goal was not enabled, the campaign goal is defaulting to amount and setting value to 0.  This is a problem because we are currently requiring a goal value so in this scenario you would not be able to update the campaign until you update the goal value.
Ideally, we should have a setting for enabling campaign goals instead of requiring one.
This PR is a quick fix that allows a goal amount to be 0, prevents the goal amount input from displaying NaN, and sets react-hook-form to focus on error inputs.
Campaign goals
**Before**
**After**
Set a campaign goal amount to be 0 and make sure you can edit the campaign. …

Fix: migrated forms to campaigns allows goal amount to be 0

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/CampaignDetailsPage.module.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/ColorControl/index.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/ColorControl/styles.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/TextareaControl/styles.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Tabs/Settings.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx
src/Campaigns/resources/admin/components/Inputs/Upload/index.tsx
src/Campaigns/resources/admin/components/Inputs/Upload/styles.scss
src/Campaigns/resources/admin/components/Notifications/Notices.module.scss

Resolves [GIVE-2292]
This pull request improves the handling of the disabled state in Campaign Settings for archived campaigns by ensuring that all fields are disabled and properly styled.
🛠 Fixes
Ensured that the `ToggleControl` for `enableCampaignPage` correctly reflects the isDisabled state.
✨ Features
Styled Campaign Setting Fields to properly display the disabled state for:
- `input` and `select` elements (background, border, cursor, opacity, text shadow, and transform properties).
- `textarea` elements with appropriate styling for the disabled state.
🔧 Code Cleanup
- Removed an unused import for `campaignPageImage` in `Settings.tsx`.
Campaign Settings tab
_Enabled_
_Disabled_
In a Campaign Settings page, confirm that all fields are disabled (cannot be edited) and look like disabled …

Fix: Improve Campaign Page Disabled State Styling

---

src/Donations/DonationsAdminPage.php
src/Donations/Endpoints/ListDonations.php
src/Donations/resources/components/DonationsListTable.tsx

Resolves [GIVE-2343]
This updates the Donations list table window and list table route to handle campaign filtering as opposed to form filtering.
- DonationListTable window
- DonationListTable route (where-conditions &)
- DonationListTable filtering config
https://github.com/user-attachments/assets/1e9f0e77-438e-4aca-b342-2ec4de6bb1cc
- Create several campaigns and publish multiple forms.
- Create several donations through these campaigns/forms.
- Visit the donation table and use the filter to filter by campaign.
- Verify only donations from the given campaign are listed.
-   [x] [Self …

Refactor: replace donations table form filter with campaigns

---

src/DonationForms/resources/app/form/MultiStepForm/components/Steps.tsx

Resolves [GIVE-1300]
This PR prevents the iframe from scrolling into view on the initial step of MultiStep & Two-panel forms.
- Create a v3 Multi-Step form.
- Use the DonationForm block to render it on a page. Make sure to add content to the page so the form is pushed down far enough that you'd have to scroll down to view.
- View the page in safari & other common browsers to confirm that the form is not scrolled into view when visiting the page.
[GIVE-1300]: …

fix: prevent parent page scroll on initial step of multi-step forms

---

src/DonationForms/Actions/ValidateReceiptViewPermission.php
src/DonationForms/Controllers/DonationConfirmationReceiptViewController.php
src/DonationForms/ServiceProvider.php
src/Donations/Repositories/DonationRepository.php
tests/Unit/Actions/ValidateReceiptViewPermissionTest.php

Resolves [GIVE-2324]
Depends on https://github.com/impress-org/give-gift-aid/pull/192
This pull request addresses an issue where the GiftAid Declaration Form download link fails validation permissions right after a donation is made using a V3 form. This happens because, in V3, the donation is not set in the user session as in Legacy Donation Forms, which prevents the form from being downloaded immediately.
To fix this, the pull request hooks into the `give_can_view_receipt` filter and attempts to validate the current view for V3 forms. If it’s not a V3 form, it simply returns the original value provided by the filter.
* [`src/DonationForms/Actions/ValidateReceiptViewPermission.php`](diffhunk://#diff-50af02626f127e283e1ca6231318dbce7c63e2184a4f8ab8ca1e01881b230381R1-R40): Added a new …

Refactor: Enable GiftAid Form download immediately in V3 Confirmation Page

---

src/DonationForms/Blocks/DonationFormBlock/resources/app/Components/ModalForm.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/common/FormModal/index.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/common/FormModal/styles.scss
src/DonationForms/Blocks/DonationFormBlock/resources/editor/components/DonationFormBlockPreview.tsx

Our current form modal does not have a loading UI.  The experience is lack luster. This enhances the UX with an initial loading state.  This is meant to be improved even further in the future but at least it's a start 😄 
The form modal UI
https://github.com/user-attachments/assets/9884ecab-7bfc-4d12-b7dd-5869b5937b37
- Use the donation form block on a page set to modal
- Try different form designs

Feature: updated form modal with loading state UI

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/CampaignDetailsPage.module.scss
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/Notices/CampaignNotice.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/Notices/Notices.module.scss

This changes the default and hover state for the create campaign page button and updates the spacing for the tooltip component.
This affects the UI of the create campaign page button and tooltip.
Before
After
Check the tooltip for for campaign intros, and the default and hover state for the "create campaign page" button.

fix/update create campaignPage button and tooltip styles

---

src/Campaigns/CampaignsDataQuery.php
src/Campaigns/Controllers/CampaignRequestController.php
src/Campaigns/Routes/GetCampaignsListTable.php
tests/Feature/Controllers/CampaignsRequestControllerTest.php

Resolves [GIVE-2372]
This fixes an error on the the campaign list table when it's empty by adding an empty conditional to the campaign data query when there are no ids to be used in a WHER IN clause.
The campaign list able.
N/A
- Create a fresh install, dismiss onboarding and view campaign list table. There should be no errors
[GIVE-2372]: https://stellarwp.atlassian.net/browse/GIVE-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

Fix: campaign list table when empty

---

src/Campaigns/Actions/RedirectLegacyCreateFormToCreateCampaign.php
src/DonationForms/V2/Endpoints/ListDonationForms.php
src/FormBuilder/FormBuilderRouteBuilder.php

This PR resolves the issue with the redirect logic for campaign forms. The issue was that the `RedirectLegacyCreateFormToCreateCampaign` class was not accounting for the p2p campaign forms.

Fix: Edit Donation Form should not open campaign creation modal

---

src/Campaigns/ListTable/Columns/DonationsCountColumn.php
src/Campaigns/ListTable/Columns/RevenueColumn.php

Resolves #
The links for the `Donations` and `Revenue` columns were redirecting the users to pages that don't work to filter data related to Campaigns. This PR fixes that by removing the link for the donations count and replacing the link for the revenue table with a link to the campaigns overview tab.
The campaigns list table.
**Before:**
**After:**
Make sure the link for the Donations column doesn't exist anymore and the link for the revenue column is redirecting to the campaign overview tab.
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#s …

Fix: campaigns list table links

---

src/DonationForms/V2/ListTable/Columns/TitleColumn.php

Resolves [GIVE-2321]
This ensures the donation form title anchor tag opens in the same window to achieve parity with the edit anchor tag.
Donation Forms list table
https://github.com/user-attachments/assets/bd2c2732-a93c-4ed0-ae0e-751c3ff7e31c
- Visit the donation forms  list table. 
- Click on the title of the form.
- Verify the link opens in the same page as opposed to a new page.
[GIVE-2321]: https://stellarwp.atlassian.net/browse/GIVE-2321?atlOrigin=eyJpI …

Fix: remove target attribute from form title anchor tag

---

src/Campaigns/resources/admin/components/Inputs/Upload/styles.scss

Resolves [GIVE-2329]
This pull request includes changes such as modifying the aspect ratio of the Campaign Images setting and removing fixed height properties to allow for a more flexible and responsive design.
Styling improvements:
* Changed the aspect ratio of images within the media modal to 16:9 for better consistency and responsiveness.
* Removed fixed height properties from the media modal and its image elements to allow for more flexible layout and design. [[1]](diffhunk://#diff-9b8130e52ccd659df1924d2c78bd4270ce0e4fc9924f3f3fcde66103d71b6d61L53) [[2]](diffhunk://#diff-9b8130e52ccd659df1924d2c78bd4270ce0e4fc9924f3f3fcde66103d71b6d61L86)
Campaign Settings
1.	Go to a campaign’s settings page.
2.	Try adding images of different sizes to the campaign.
3.	Confirm they all respect the …

Refactor: Improve Campaign Image upload setting to enforce aspect ratio

---

assets/src/css/admin/_components.admin-header.scss
src/DonationForms/V2/DonationFormsAdminPage.php
src/DonationForms/V2/ServiceProvider.php

Resolves [GIVE-2357]
This PR fixes two problems:
1. It adds back the `Switch to New View` button on the legacy list tables for the _"Donors"_, _"Donations"_, and _"Subscriptions"_ pages.
2. Hides the `All Forms` menu item when using the legacy list table on the _"All Forms"_ page.
- The "Donors", "Donations", and "Subscriptions" legacy list tables
- The GiveWP sidebar menu
**Problem 1:**
1. Go to the _"Donors"_, _"Donations"_, and _"Subscriptions"_ pages and click on the `Switch to Legacy View` button for each one of them.
2. On the legacy views accessed on the previous step, make sure you can see the `Switch to New View` button.
**Problem 2:**
1. Access the "All Forms" page using a URL like this: `https://givewp.local/wp-admin/edit.php?post_type=give_forms&page=give-forms`
2. Click on …

Fix: displays missing switch buttons and hides "All Forms" menu item when using the legacy list table

---

src/Views/Components/ListTable/ListTablePage/ListTablePage.module.scss

This PR updates the default, hover and focus states for the add campaign form button.
Add campaign form button.
Before
After
Click on any campaign, go to the forms list page, check the add campaign form button.

fix: update add campaign form styles

---

src/Campaigns/ServiceProvider.php
src/DonationForms/AsyncData/resources/loadAsyncData.js
src/DonationForms/ServiceProvider.php

Resolves [GIVE-2356]
Previously, we implemented the async load feature for the `Goal`, `Donations`, and `Revenue` columns of the _"All Forms"_ list table on this PR: https://github.com/impress-org/givewp/pull/7483
Since the campaigns forms tab is using this same list table, this PR aims to enable this same feature on the campaign details page as well so we can prevent slow page loads in cases where a website has multiple forms/donations associated with a single campaign.
Right now, this feature is enabled by default, but after the campaigns release, we can work to optimize the queries like we did here: https://github.com/impress-org/givewp/pull/7819
So, this feature should soon be disabled by default.
The campaign forms list table
Go to the _"Forms"_ tab of a campaign and make sure the …

Refactor: enable async load for campaign forms list table

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx
src/DonationForms/V2/ListTable/Columns/TitleColumn.php
src/DonationForms/V2/ListTable/DonationFormsListTable.php
src/DonationForms/V2/resources/components/DonationFormsListTable.tsx
src/DonationForms/V2/resources/components/DonationFormsRowActions.tsx
src/Views/Components/ListTable/InterweaveSSR/styles.scss
src/Views/Components/ListTable/ListTable/ListTable.module.scss
src/Views/Components/ListTable/ListTablePage/ListTablePage.module.scss
src/Views/Components/ListTable/ListTableRows/ListTableRows.module.scss
src/Views/Components/ListTable/TableCell/TableCell.module.scss

Resolves [GIVE-2327]
This PR removes the donation levels column and introduces a default form pill to help indicate which form is marked as the default.
Additionally replaces the  shortcode column with a row action to copy the shortcode.
Donation form list table
https://github.com/user-attachments/assets/15901119-48d9-4177-b090-54d1ce04fb21
[GIVE-2327]: https://stellarwp.atlassian.net/browse/GIVE-2327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

Feature: add default form indicator to list table

---

includes/admin/class-admin-settings.php
includes/admin/settings/class-settings-advanced.php
src/DonationForms/ViewModels/DonationFormViewModel.php
src/Views/Form/Templates/Classic/Classic.php
src/Views/Form/Templates/Sequoia/Sequoia.php

Resolves [GIVE-2362]
This pull request adds a new global setting called “Custom Styles”, allowing admin users to define CSS rules that will be applied to all Donation Forms across the website.
To support this feature, we introduced a new admin setting type called `code_editor`, which renders a CodeMirror-powered editor. The `custom_form_styles` option is then enqueued as inline styles on the front end, with support for both legacy and VFB forms.
Admin Settings and Form styles
https://github.com/user-attachments/assets/217e3120-1674-4a6a-9f02-56432b54b792
1. Go to Settings > Advanced > Donation Forms
2. Add custom CSS to the editor and save it
3. Confirm those CSS rules are being applied to all your forms.
-   [x] Relevant …

Feature: Add global CSS editor for donation forms via “Custom Styles” setting

---

src/Campaigns/Actions/CreateDefaultCampaignForm.php
src/DonationForms/Properties/FormSettings.php
src/DonationForms/ViewModels/DonationFormViewModel.php
src/FormBuilder/Routes/CreateFormRoute.php
src/FormBuilder/ViewModels/FormBuilderViewModel.php
src/FormBuilder/resources/js/form-builder/src/common/getWindowData.ts
src/FormBuilder/resources/js/form-builder/src/settings/design/style-controls/color-inheritance-toggle/index.tsx
src/FormBuilder/resources/js/form-builder/src/settings/design/style-controls/color/index.tsx
src/FormBuilder/resources/js/form-builder/src/types/formSettings.ts
tests/Unit/ViewModels/FormBuilderViewModelTest.php

Resolves [GIVE-2309]
This pull request adds the ability for users to have form colors inherited from the campaign that the donation form belongs to.
Initially, only new forms will have this setting enabled by default. Existing forms will continue using their own custom colors, but users will have the option to switch back to using the campaign’s colors if they prefer.
Donation Forms colors
https://github.com/user-attachments/assets/2e64402e-262b-4a0a-a9d7-050c204a26d6
1.	Create a new campaign
•	Open the default form associated with the new campaign.
•	Go to the “Styles” settings tab in the sidebar.
•	Confirm that the “Inherit Campaign Colors” toggle is turned on by default.
2.	Create a new form under that campaign
•	Open the form’s settings.
•	Verify that the “Inherit Campaign Colors” …

Feature: Add support for Forms to inherit Campaign colors

---

src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/Notices/DraftCampaignPageNotice.tsx
src/Campaigns/resources/admin/components/CampaignDetailsPage/index.tsx
src/Campaigns/resources/admin/components/Notifications/Notices.module.scss

Resolves [GIVE-2366]
This includes a notice for users directing them to Publish their campaign landing page. The notice disappears once the page has been published and remains closed on all published pages. This notice will also be hidden when a campaign is archived.
Campaign Overview Page
https://github.com/user-attachments/assets/60660c33-c56d-4624-b890-98e0d5ad4f4a
- Create a new campaign - view the notice.
- Move the campaign to archived status - it should disappear.
- Move the campaign status back to draft - it should reappear
- Follow the directions on the notice.
- View the campaign overview page - verify the notice has been removed.
-   [ ] Includes unit …

Feature: add draft campaign page notice

---

src/Views/Components/AdminUI/ModalDialog/style.scss

Resolves [GIVE-2399]
This Pull Request fixes an issue where opening the Modal Dialog inside an iframe causes the iframe to resize to 0px height. In this PR, we address the problem by updating the CSS rule that locks the background when the Modal Dialog is open. The new rule keeps the background lock effective while also working properly inside iframes.
Modal DIalog component
1. Create a recurring donation with Stripe then open the Donor Dashboard.
2. Go to that recurring donation and click to pause or cancel that subscription.
3. The modal must open as expected.
4. Also, confirm this fix does not break other places that component is used like the Create Campaign modal. …

Fix: Prevent Modal backdrop lock conflict with iframe resizer

---

src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx
src/PaymentGateways/PayPalCommerce/PayPalCommerce.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php

Resolves [GIVE-2397]
This adds minimal support for 3d secure to the PayPal commerce gateway card fields api.
- PayPal Commerce using card fields
N/A
- In order to properly test will want to set the PayPal Order createOrder request param to `SCA_ALWAYS`
- Then use the test scenarios https://developer.paypal.com/docs/checkout/advanced/customize/3d-secure/test/
[GIVE-2397]: https://stellarwp.atlassian.net/browse/GIVE-2397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

Feature: add support for 3d secure to PayPal Commerce Gateway 

---

includes/admin/class-admin-settings.php
src/PaymentGateways/ServiceProvider.php

Resolves [GIVE-2325]
This PR hides the PayPal Standard admin option by default when the  `GiveWP > Settings > Payment Gateways > PayPal > PayPal Standard > PayPal Email` is not filled out.
If someone needs to force these options to be visible in the UI, they can add the `define('GIVE_ALWAYS_SHOW_PAYPAL_STANDARD_ADMIN_OPTIONS', true);` to the `wp-config.php` file.
- GiveWP > Settings > Payment Gateways > Gateways
- GiveWP > Settings > Payment Gateways > PayPal
**Important:** Before starting, check if you had the `GiveWP > Settings > Payment Gateways > PayPal > PayPal Standard > PayPal Email` filled out; If yes, make sure to remove it and save the settings.  
Then, pull the change from this branch and make sure that there are no PayPal Standard options available on these pages:
- GiveWP > …

Refactor: hide PayPal Standard admin options by default

---

src/DonationForms/Blocks/DonationFormBlock/Controllers/BlockRenderController.php
tests/Feature/Controllers/BlockRenderControllerTest.php

Resolves [GIVE-2407]
I discovered we are missing the necessary embed-id on some of our donation form blocks like the campaign donate buttons.  Since these blocks are sharing the original form block render controller, they are missing the embed-id that was originally received from the block's attributes using blockId.
The embed-id is especially useful for offsite gateways so when they come back to the site, we know which form to display the confirmation page and open a modal.
For the purpose of using this controller in a more general purpose way, it was updated with a fallback way of generating the embed-id if not coming from block attributes.
The donation form block rendering
N/A
- Setup a campaign using Stripe Payment Element
- Donate using the campaign landing page donate button
- Make …

Fix: add fallback embed id to donation form block render

---

src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/CreateWebhook.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/DeleteWebhook.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/GenerateClientToken.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/GetAccessToken.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/UpdateWebhook.php
src/PaymentGateways/PayPalCommerce/PayPalCheckoutSdk/Requests/VerifyWebhookSignature.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalAuth.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php
src/PaymentGateways/PayPalCommerce/Repositories/Webhooks.php

This is the epic for various PayPal refactoring including:
- Replace hosted fields with card fields api
- Update watched values with new useFormData hook
- PayPal commerce gateway
N/A
ZIP: https://github.com/impress-org/givewp/actions/runs/14386630005
- Test PayPal commerce gateway on v3 forms using card fields (new)
- Test PayPal commerce gateway on v3 forms using smart buttons (regression test)
- Test PayPal commerce gateway on v2 forms using smart buttons (regression test)
- Test PayPal commerce gateway on v2 forms using hosted fields (regression test)
-   [ ] [Self …

Epic: Update PayPal gateway to use card fields API

---

src/Helpers/ArrayDataSet.php

This pull request includes an update to the `ArrayDataSet` class in the `src/Helpers/ArrayDataSet.php` file. The main change introduces a check to ensure that the input is an array before attempting to rename its keys.
ArrayDataSet helper class

Fix: Add argument type check

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/stripePaymentElementGateway.tsx

Resolves [GIVE-2318]
This PR replaces the `useWatch` hook with the `useFormData` hook so we can retrieve the amount of the donation with the Fee Recovery already included. This way, we can prevent showing the donation amount without the fee recovery included in the model for Apple/Google Pay (Stripe).
The Stipe Element gateway
1. Create a VFB form
2. Add the Fee Recovery block with a fee
3. Enable the Stripe Payment Gateway
4. Ensure Apple/Google Pay is showing
5. Go through the donation process and click to add a fee
6. Select Apple or Google Pay
7. When submitting, there will be a modal with the **Donation Total** (including the fee recovery amount)
-   [ ] …

Refactor: replace useWatch with useFormData to show the Fee Recovery amount on the modal for Apple/Google Pay (Stripe)

---

src/DonationForms/resources/styles/components/_gateways.scss
src/DonationForms/resources/styles/elements/_fields.scss

Resolves [GIVE-2105]
This PR adds a CSS media query to adjust the padding for payment gateway fields on smaller screens - check the attached demo video for more context.
The Payment Gateways list on VFB forms
https://www.loom.com/share/0a1c8c83b6bf4619abc787d425fb3d62?sid=e8029878-8892-465e-abee-4b3e79c4f466
Follow the test instructions from this other related PR: https://github.com/impress-org/give-authorize-gateway/pull/127
[GIVE-2105]: …

Refactor: tweak gateway fields padding on mobile screens

---

src/Helpers/Utils.php

Resolves [GIVE-932]
In legacy forms, setting up a success or failure URL that contains both UTM tags and an anchor breaks Stripe payments. This pull request fixes the issue by removing the anchor and then re-adding it as a `request_anchor` argument in the URL. This way, we make sure the URLs never contain both tags and anchors at the same time.
Legacy Forms
1. Add the following sample hook to a functions file. It'll append sample UTM tags and an anchor to the current page URL that is used in success and failure URLs:
```php
<?php
/**
* Add sample UTM tags and an anchor to the current GiveWP page URL.
*
* @param string $url The original URL.
* @return string Modified URL with UTM tags and anchor.
*/
function add_utm_tags_and_anchor_to_give_url( $url ) {
// Add UTM parameters using …
```

Fix: Update legacy form URLs containing both UTM tags and anchors

---

src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

Resolves [GIVE-2518]
This ensures the donate button displays again after selecting a different payment method when previously hidden.
- PayPal donations
https://github.com/user-attachments/assets/32fc6c0a-7c98-4d41-bbe0-42ffa4b063b5
ZIP: https://github.com/impress-org/givewp/actions/runs/14619508044
- Setup PayPal donations set to smart buttons only
- Setup another gateway like stripe
- Select PayPal donations and make sure the donate button is hidden
- Select another gateway and make sure the donate button is not hidden
-   [ ] [Self …

Fix: Show donate button after PayPal donations is umounted

---

src/DonationForms/resources/app/hooks/useFormSubmitButton.ts
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx

This ensures the continue button is hidden on multistep forms when using PayPal smart buttons when not on the last step.
- PayPal donations (smart buttons) on multistep forms
https://www.loom.com/share/e69ac21b9ea9411c9b7709f696898854?sid=747dbd1e-8359-4422-9d3b-2f67d5aaf4e5
- Create a multistep form where the gateway are not on the last step
- Make sure when PayPal donations is selected (set to smart button only) the continue button is hidden
- Test for regression issues
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code …

Fix: Hide continue button on multistep forms when using PayPal smart buttons

---

src/Campaigns/Blocks/CampaignDonations/render.php
src/Campaigns/Blocks/CampaignDonors/render.php
src/Campaigns/Blocks/CampaignStats/render.php
src/Campaigns/CampaignDonationQuery.php
src/Campaigns/CampaignsDataQuery.php
src/DonationForms/DonationQuery.php
src/DonationForms/resources/app/form/Header.tsx
tests/Unit/Campaigns/CampaignDonationQueryTest.php
tests/Unit/Campaigns/CampaignsDataQueryTest.php
tests/Unit/Campaigns/Repositories/CampaignsDataRepositoryTest.php

The current campaign and donation queries are using the intended amount meta value from fee recovery.  This value is risky to use because it was calculated by fee recovery and is not a core concept of GiveWP.  Although it has been working (as far as we know) I don't find it reliable because it's controlled by an add-on who calculates this amount at the time of donation created.  This means, the value can get out of sync if the donation amount is changed.
The _core_ concept of GiveWP as defined in our [Donation model](https://github.com/impress-org/givewp/blob/400523ed9db4c22a84299dfbcf9a1d210aeecaa8/src/Donations/Models/Donation.php#L238) is the `amount` and `feeAmountRecovered`.   The `amount` is the total donation amount _including_  `feeAmountRecovered` and the `feeAmountRecovered` is …

Refactor: update sum queries to use donation fee amount instead of fee recovery intended amount

---

src/Donations/Migrations/RecalculateExchangeRate.php
src/Donations/ServiceProvider.php
src/Donations/ValueObjects/DonationMetaKeys.php
tests/Unit/Donations/Migrations/RecalculateExchangeRateTest.php

Resolves [GIVE-2516]
This PR implements a migration to update exchange rates for existing donations where the exchange rate was not properly stored. This is a follow-up to the fix implemented in #7888, which addressed the issue of exchange rates not being stored properly in donations made through legacy forms.
Donations' Exchange Rate
1. Using a previous version of GiveWP, create donations using legacy forms with Currency Switcher enabled and a different currency selected.
2. In the admin area, navigate to the Donation Details page and verify that the Exchange Rate is displayed as "1".
3. Update GiveWP to this version.
4. In GiveWP > Tools > Data > Database upgrades, confirm that the migration completed successfully without any errors.
5. Return to the Donation Details page and verify …

Feature: Add migration to recalculate exchange rates

---

src/Donations/LegacyListeners/UpdateDonationMetaWithLegacyFormCurrencySettings.php
src/Donations/Listeners/DonationCreated/UpdateDonationMetaWithCurrencySettings.php
src/Donations/Listeners/DonationCreated/UpdateDonorMetaWithLastDonatedCurrency.php
src/Donations/ServiceProvider.php
tests/Unit/Donations/Listeners/DonationCreated/TestUpdateDonationMetaWithCurrencySettings.php
tests/Unit/Donations/Listeners/DonationCreated/TestUpdateDonorMetaWithLastDonatedCurrency.php

Related: [GIVE-2516], [GIVE-859], https://github.com/impress-org/give-currency-switcher/pull/321
This moves the actions that handle updating currency meta into core.  Previously all this logic lived in the currency switcher add-on however, as more of the currency concepts actually live in core it makes sense for this logic to live there as well.  This will ensure that core will handle associating currency data to the donation, eventually leaving the currency switcher add-on to simply supply settings like exchange rates.
- creating donations with currency settings (currency switcher)
https://www.loom.com/share/01fb49c1491c483c97c559fb2c367421?sid=90566c00-457c-4422-b223-7f5c1d6f190f
ZIP: https://github.com/impress-org/givewp/actions/runs/14604325546
- create a campaign with both v2 and v3 …

Feature: add currency switcher listeners to core

---

src/DonationForms/ViewModels/DonationConfirmationReceiptViewModel.php
src/Donations/Models/Donation.php
src/Donations/Repositories/DonationRepository.php
src/Donations/ServiceProvider.php
src/Form/LegacyConsumer/Actions/AddCustomFieldsToLegacyReceipt.php
src/Form/LegacyConsumer/ServiceProvider.php
src/Framework/Receipts/Actions/GenerateConfirmationPageReceipt.php

Resolves: [GIVE-2444]
There is a difference between how v2 and v3 forms reference custom fields like the ones in FFM.  In some areas like the donor dashboard, the custom fields were not displaying because the logic for v3 forms was not in place.  This ensures we are displaying custom fields coming form v3 forms in the legacy receipt.  This was accomplished by running through the old `give_new_receipt` using the new receipt schema.
To make our lives easier, I added a simple method on the Donation model to generate the `DonationReceipt` instance.
```php
$donation->receipt();
```
- The confirmation page logic was updates slightly
- Legacy receipt in donor dashboard should show custom fields from v3 forms now
https://github.com/user-attachments/assets/54006577-2834-4fb6-85b8-c57e404e6a77
ZIP: …

Refactor: display v3 custom fields in donor dashboard and legacy receipts

---

src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Actions/UpdateStripeInvoiceMetaData.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Decorators/SubscriptionModelDecorator.php
src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/Webhooks/Listeners/InvoicePaymentSucceeded.php
tests/Feature/Gateways/Stripe/StripePaymentElement/Webhooks/Listeners/InvoicePaymentSucceededTest.php

Resolves [GIVE-318]
This PR adds metadata to Stripe transactions that belong to a Stripe subscription, so now users can have the same metadata info that they already have on the one-time donations.
Stripe recurring donations
1. Make sure your test site can receive webhook events from Stripe
2. Set up a VB form with the Stripe Element gateway enabled
3. Create a subscription with the Stripe Element gateway
4. Go to the Stripe dashboard and trigger a renewal
5. Make sure both the initial donation and the renewal donation have metadata added
-   [ ] [Self …

Feature: add metadata to stripe recurring donations

---

src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx
src/PaymentGateways/PayPalCommerce/AjaxRequestHandler.php
src/PaymentGateways/PayPalCommerce/PayPalCommerce.php
src/PaymentGateways/PayPalCommerce/Repositories/PayPalOrder.php

Resolves [GIVE-2559](https://stellarwp.atlassian.net/browse/GIVE-2559)
This PR resolves the following 2 bugs:
1. The global setting "Fee Opt-in" when set to "Forced Opt-in" is causing fee recovered amount to be added to the donation total twice for v3 forms. [[Ref 1](https://github.com/impress-org/give-fee-recovery/blob/4ebbb9b6a64a7d769fb15308083f88429919af17/src/ServiceProvider.php#L42), [Ref 2](https://github.com/impress-org/give-fee-recovery/blob/08dbad91f1ed7f30787063fec3b6747fe2b7be64/src/Service/AddFeeToDonationAmount.php#L60)]
2. When using Donation category and amount is being updated, the api request needs to include amount breakdown for v3 forms.
This ensures we are sending the correct request format to PayPal when updating an order that is expecting the DONATION category type. …

Fix: resolve PayPal commerce update order amount and fee recovery opt-in

---

src/DonationForms/resources/styles/elements/_header.scss

Resolves [GIVE-2465]
Previously, links added in the form header description lacked distinctive styling, making them appear as plain text. This could confuse users or prevent them from discovering important linked content.
This PR updates the styles for anchor (<a>) tags within the form header description to ensure they are visually recognizable as clickable links. These changes improve usability by helping sighted users identify interactive elements more easily.
Form Header Description 
https://github.com/user-attachments/assets/bd74fae3-3105-41fb-bb3e-09cb9128b1c7
- Create a form with an enabled header.
- Add a link in the header description.
- Verify it looks like a clickable link (text underline, hover styles etc)
- View in the editor & the frontend. …

Fix: style links in the header description

---

src/DonationForms/resources/app/utilities/registerFieldAndBuildProps.tsx
src/DonationForms/resources/registrars/templates/fields/Date.tsx
src/DonationForms/resources/registrars/templates/fields/File.tsx
src/DonationForms/resources/registrars/templates/groups/BillingAddress.tsx

Resolves [GIVE-2461]
This PR adds the `aria-required="true"` attribute to all required form fields. This ensures that assistive technologies can programmatically identify which fields are mandatory, improving accessibility compliance.
The` aria-required` attribute has been added in the inputProps returned by `registerFieldAndBuildProps`, so it is automatically applied to each visible input field based on its validation rules.
Exceptions & Special Cases:
- Fields like `Date` and `File` inputs, which use hidden elements to manage the actual submitted value, had the aria-required attribute manually applied to their visible counterparts to ensure correct accessibility behavior.
- Some fields, such as those used for honeypot, hidden, password or authentication, are intentionally excluded since …

Fix: include `aria-required` in all required fields

---

src/DonationForms/resources/registrars/templates/groups/Authentication.tsx
src/DonationForms/resources/registrars/templates/styles.module.scss

Resolves [GIVE-2440]
This PR ensures visible focus styles are applied to interactive elements within the User Login block — specifically addressing buttons like “Already have an account? Log in.”, "Reset", "Login". These updates improve keyboard navigation and accessibility by making it clear when elements are focused.
User Login block
https://github.com/user-attachments/assets/bdee2ae1-c954-489c-a8ff-a71791816cc9
- Create a form.
- Add the User Login block.
- View the form in incognito mode.
- Using keyboard navigation - navigate to the User Login block & verify there is a visible focus border.
- Press enter.
- Keyboard navigate to the "Forgot password" button  & Login to verify there is a visible focus border..
-   [ ] …

Fix: add visible focus to User Login block buttons

---

src/DonationForms/resources/registrars/templates/fields/Amount/DonationAmountLevels.tsx

Resolves [GIVE-2457]
This PR adds the proper `role` and `ARIA` attributes to the donation amount levels so the accessibility systems can understand it like a radio button, where the user needs to select just one option instead of a group of independent buttons.
The donation amount levels block.
1. Make sure the donations level block container is using the `radiogroup` role.
2. Make sure each item of the donations level block is using the `radio` role. …

Fix: add radio role for donation amount level buttons

---

includes/admin/payments/class-payments-table.php
src/Donations/ListTable/Columns/CampaignColumn.php
src/Donations/ListTable/DonationsListTable.php
tests/Unit/Donations/Endpoints/TestListDonations.php

This PR updates the donations list table to show the campaign title instead of the form title. 
Donations list table
Make a donation to a campaign
Visit donations list table and check the campaign column

Feature: Donations list table - show campaign title instead of the form title 

---

src/Campaigns/Actions/EnqueueCampaignPageEditorAssets.php
src/Campaigns/Actions/LoadCampaignDetailsAssets.php
src/Campaigns/Actions/LoadCampaignsListTableAssets.php
src/Campaigns/Actions/RegisterCampaignBlocks.php
src/Campaigns/Actions/RegisterCampaignEntity.php
src/Campaigns/Blocks/Campaign/CampaignShortcode.php
src/Campaigns/Blocks/CampaignForm/CampaignFormShortcode.php
src/Campaigns/Blocks/CampaignGrid/CampaignGridShortcode.php
src/Campaigns/resources/admin/components/CampaignDetailsPage/Components/RevenueChart.tsx
src/DonationForms/resources/styles/components/_amount.scss

Resolves [GIVE-2430]
This PR makes sure all strings for campaigns are available to be translated.
The campaign strings.
**Demo video:** https://www.loom.com/share/9697385ca9a8415d87086e6fb5470821?sid=cb3d8451-43d6-432c-894a-783683540e08
1. Go to the plugin root folder and run this command: `wp i18n make-pot . languages/give.pot` (**ignore this step if you are testing it using a zip file**)
2. Install [Loco Translate](https://br.wordpress.org/plugins/loco-translate/) and start a translation for a new target language
3. Copy a string from the campaigns overview page like `This chart shows your campaign goal progress` and paste it in the Loco Translate search box
4. Add some random thing to the translated string
5. Change the WP settings to use the target language (from step 2) and make sure …

Fix: campaigns missing translations

---

src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/header/index.tsx

Resolves [GIVE-2506]
This PR improves the contrast of white text over header background images by applying default values for the overlay color and opacity when a background image is selected.
The goal is to ensure that the form title and description have sufficient contrast with the image by default, improving accessibility and readability.
Since the overlay controls are located in the Styles tab, but may not be mounted immediately, the logic to apply these defaults was added to the General Settings panel (Header component). This ensures the defaults are applied even if the Styles tab is never opened.
Header image
Header image styles & settings
https://github.com/user-attachments/assets/26bf4e63-99b3-416c-a5c6-f0675045ed74
- Create a form with classic template.
- Add a header image …

Feature: Set default overlay settings when applying a header background image

---

src/DonationForms/Properties/FormSettings.php
src/DonationForms/resources/styles/components/_goal.scss
src/FormBuilder/resources/js/form-builder/src/settings/design/style-controls/color/index.tsx

Resolves [GIVE-2503]   [GIVE-2459]   [GIVE-2491] 
This PR aims to improve the color contrast in the forms text by updating the forms default primary color choice & updating the goal stats text color.
- Goal Stat Labels Contrast
Issue: Labels such as “Raised,” “Donations,” and “Goal” did not meet the minimum 4.5:1 contrast ratio against their background.
Fix: Updated text color from `Grey-400` to `Grey-500` to ensure sufficient contrast.
- Payment Gateway Focus Outline
Issue: The green focus outline on the payment gateway selector with the form's default green background failed to meet the required 3:1 contrast ratio.
Fix: Resolved by updating the form’s default primary color, which affects both the background and focus outline color.
-  White Text on Green Background
Issue: White text …

Fix: improve contrast on default form colors

---

src/DonationForms/FormDesigns/ClassicFormDesign/css/_inputs.scss
src/DonationForms/resources/registrars/templates/fields/Amount/CustomAmount.tsx
src/DonationForms/resources/registrars/templates/styles.module.scss

Resolves [GIVE-2458]
These changes help improve the color contrast of the placeholder text styles for our field inputs. Specifically the custom amount field placeholder which uses a currency-input had a different color than other fields. To ensure consistency and compliance I've updated the placeholder color of all fields to `var(--givewp-grey-400);`
- Input placeholders
- Visually view a couple of text placeholders to verify the colors are the same. …

Fix: Standardize input placeholder styles to improve color contrast

---

src/DonationForms/FormDesigns/MultiStepFormDesign/css/_sections.scss
src/DonationForms/FormDesigns/TwoPanelStepsFormLayout/css/_sections.scss
src/DonationForms/resources/app/form/MultiStepForm/components/StepsWrapper.tsx
src/DonationForms/resources/registrars/templates/layouts/Section.tsx
src/DonationForms/resources/styles/elements/_multi-step-form.scss
src/DonationForms/resources/styles/elements/_sections.scss

Resolves [GIVE-2455]
This PR ensures that each step title in the donation form is properly marked up using semantic HTML heading tags 
`<h3>` Previously, these titles were not tagged as headings, but rather nested in each `<fieldset>` -> `<legend>` element in classic forms. In multi-step forms they were represented as `<p>` elements.
- v3 forms all templates
https://github.com/user-attachments/assets/f95701ce-14a5-4b04-b1bc-22f3e53ab325
https://github.com/user-attachments/assets/b8e3b604-1561-4030-bea2-24e3ac8685da
- Create a form using each template.
- With Classic templates verify each form section has a proper heading tag.
- With Multistep templates verify each step title has a proper heading tag.
-   [x] Relevant …

Fix: update form sections with heading tags

---

src/DonationForms/DataTransferObjects/DonationFormGoalData.php
src/DonationForms/ViewModels/DonationFormViewModel.php

Resolves [GIVE-2573]
I noticed the donation form header stats were not displaying the revenue correctly.  That specific amount is meant to always show "amount raised" regardless of if the goal type is count.
Donation form view
**Before**
**After**
https://github.com/impress-org/givewp/actions/runs/15047590083
- Set a form goal, switching between options
- Make sure the "raised" amount is always in revenue
[GIVE-2573]: …

Fix: ensure donation form view stats always shows revenue amount

---

src/FormBuilder/resources/js/form-builder/src/settings/design/general-controls/layout/index.tsx

Resolves [GIVE-2558]
By default, new campaigns utilize a multi-step form template with the header disabled. Switching to the two-panel layout results in a form that visually mirrors the multi-step template, potentially confusing new users. Additionally, the classic template benefits from a visible header for improved aesthetics.
This update ensures the header is enabled when transitioning to either the two-panel or classic templates, providing a visually appealing experience across all form layouts.
- Form template settings
https://github.com/user-attachments/assets/a204dbb8-1cb2-4cc5-8136-c20e6176a6d0
- create a campaign and view the default form in the builder.
- Switch to classic it should reenable the header.
- Remove the header switch to two panel it should reenable the header.
- …

Fix: enable header when switching form templates

---

src/DonationForms/resources/registrars/templates/fields/Text.tsx

Resolves [GIVE-2504]
This PR ensures proper label and description association for the text field in the Donation Form by correctly setting the id on the input element and referencing it in the corresponding `<label>` using `htmlFor`. Additionally, it sets `aria-labelledby `and `aria-describedby` attributes to ensure that both the label and optional field description are properly announced by screen readers. Previously, the text field lacked a valid id, and screen readers were unable to associate the label or description with the input. This fix improves accessibility and ensures compliance with form labeling and description best practices.
Text field
https://github.com/user-attachments/assets/fdea8254-011d-4c34-9db9-791355822a94
1.	Using FFM, add a Text Field block to the Donation Form
2. …

Fix: Add Missing Label Association for Text Field

---

src/DonationForms/resources/registrars/templates/styles.module.scss

Resolves [GIVE-2448] 
This PR enhances accessibility by adding a visible focus outline to the multi-select field in the Donation Form. Previously, there was no clear visual indication when the field was focused, making it difficult for keyboard and screen reader users to navigate the form effectively.
Multi-select Field
https://github.com/user-attachments/assets/f4e1d44d-6b62-4905-9957-1fb863ef2319
1.	Using FFM, add a Multi-Select field to a Donation Form
2.	Publish or preview the Donation Form
3.	Navigate to the Multi-Select field using the keyboard (e.g., press Tab until it is focused)
4.	Confirm that a visible focus style is applied when the field receives focus (e.g., a colored outline or box-shadow)
[GIVE-2448]: https://stellarwp.atlassian.net/browse/GIVE-2448?atlOrigin=eyJpIjoiNWRkNT …

Fix: Add Focus Outline to Multi-Select Field for Improved Accessibility

---

src/DonationForms/resources/registrars/templates/elements/Html.tsx
src/DonationForms/resources/registrars/templates/styles.module.scss

Resolves [GIVE-2466]
This PR improves accessibility and visual consistency by ensuring that links within the HTML block of the Donation Form are properly styled. This update addresses an issue where links previously appeared as plain text with only a color difference, making them difficult to recognize, especially for users relying on visual cues.
HTML Field
https://github.com/user-attachments/assets/4d5eaaf5-3d53-4bcb-b4f2-8611098eb19c
1.	Using FFM, add an HTML block to a Donation Form
2.	Insert a paragraph containing one or more external links (e.g., using `<a href="https://example.com">Example</a>`)
3.	Publish or preview the Donation Form
4.	Confirm that the links:
•	Are visually distinct from surrounding text (e.g., underlined or styled differently)
•	Respond to hover and focus states …

Fix: Style Links in HTML Block to Improve Accessibility and Visual Consistency

---

src/Campaigns/Blocks/shared/components/ModalForm/index.tsx
src/DonationForms/Blocks/DonationFormBlock/resources/app/index.tsx

Resolves [GIVE-2502] & [GIVE-2462]
This update improves modal accessibility by implementing logical focus order and trapping focus inside the modal using the FocusScope component. It also includes an aria label for the new-tab setting so that screen-readers better understand the button action.
Key Fixes:
- Added FocusScope to trap focus within the modal and automatically focus the first element.
- Moved the Close button inside the Dialog element and made it keyboard focusable.
- Set role="dialog" and aria-modal="true" to explicitly define modal semantics.
- Ensured tabIndex={0} is applied where necessary to ensure focusability.
- Added restoreFocus to return focus to the triggering element once the modal is closed.
- ESC key support is assumed to be handled via existing …

Fix: improve accessibility across form modal & new tab display styles

---

src/Campaigns/Blocks/CampaignGoal/app/styles.scss
src/Campaigns/Blocks/CampaignGoal/render.php
src/Campaigns/Blocks/CampaignGrid/app/index.tsx
src/Campaigns/Blocks/CampaignGrid/app/styles.scss
src/Campaigns/Blocks/shared/components/CampaignCard/index.tsx
src/Campaigns/Blocks/shared/components/CampaignCard/styles.scss

Resolves [GIVE-2622]
The goal progress colors were being hard-coded, this updates them to use the campaign settings.
Also added a simple loading state to the campaign grid.
- The campaign grid
- The campaign page goal block
ZIP: https://github.com/impress-org/givewp/actions/runs/15419472325
- Create campaigns with different color settings
- Check the campaign grid and page(s) for accurate colors
[GIVE-2622]: …

Fix: use campaign colors for grid and block goal progress

---

src/DonationForms/resources/styles/components/_receipt.scss

Resolves [GIVE-2473]
This PR addresses an accessibility issue where the "Go to my Donor Dashboard" link lacked a visible focus indicator. This made it difficult for keyboard users to know when the link was focused, potentially blocking navigation and interaction.
Donor dashboard link in the donation confirmation page
https://github.com/user-attachments/assets/8502994d-3b74-4ea1-81f9-5a9ddbb8c203
- Complete a donation.
- On the Donation confirmation page use the tab key to navigate to the Donordashboard link.
- Verify a visible focus outline is shown around the button.
-   [x] [Self …

Feature: Add focus border to donation confirmation donor-dashboard link

---

src/DonationForms/resources/registrars/templates/layouts/DonationReceipt.tsx

Resolves [GIVE-2469]
GIVE-029 from the accessibility audit:
“The success message is visually displayed but not programmatically defined, so it’s not announced by screen readers.”
This PR ensures screen readers detect and announce the message when it appears, improving accessibility for visually impaired users.
Aria attributes:
- role="status"
- aria-live="polite"
Donation Confirmation page
Success badge
https://github.com/user-attachments/assets/fee35272-e055-405c-9440-d2c4dd7fbf2c
- Complete a donation
- Verify that the success message can be read by screen readers
-   [x] [Self …

feature: Add aria-support to donation confirmation secure badge

---

src/DonationForms/resources/registrars/templates/layouts/DonationReceipt.tsx

Resolves [GIVE-2468]
This PR updates the Details component to improve semantic HTML and accessibility compliance by replacing the inappropriate use of the <dl> (definition list) element. The original implementation caused screen readers to incorrectly announce the content as a list of definitions, which is misleading since the content represents labeled key-value pairs, not definitions.
Donation Confirmation lists.
- Create a donation.
- Verify the donation confirmation lists in the receipt continue to worlk. 
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/githu …

Refactor: Replace <dl> tags in donation confirmation field lists

---

src/DonorDashboards/Helpers.php

I ran into this issue during testing with Give memberships. If a user signs up for a membership, their role can be different from a Give donor role. I'm not entirely sure I understand why there is a check for role, but I'm hoping a solution like this PR or something like it can be found for users with other custom roles, or even a subscriber role can view their donor dashboard if they've donated.

If they are a donor and logged in give them access to donor dash

---

src/DonationForms/resources/registrars/templates/fields/Date.tsx
src/DonationForms/resources/registrars/templates/fields/File.tsx

Resolves [GIVE-2439]
This PR improves the accessibility of the `File` and `Date` input field by ensuring keyboard focus automatically moves to the field when an error is present. Previously, if there was an error, pressing Tab would skip the field entirely and jump to the page footer, making it difficult for keyboard and screen reader users to fix the issue.
This occurred because the registered ref for the field is spread across the hidden input, resulting in the error focus going to the hidden input instead of the visible one.
Date field
File field
https://github.com/user-attachments/assets/a2d14232-d272-4578-8a80-9aa7caa35b38
ZIP: https://github.com/impress-org/givewp/actions/runs/15476305685
- Create a donation form with the `File` & `Date` block.
- Make both blocks required.
- Attempt …

Fix: add error focus Date and File fields

---

src/Donors/resources/admin/components/DonorDetailsPage/README.md
src/Donors/resources/admin/components/DonorDetailsPage/Tabs/Profile/index.tsx
src/Donors/resources/admin/components/DonorDetailsPage/slots.ts
src/Views/Components/AdminDetailsPage/index.tsx

Resolves [GIVE-2581]
This PR introduces a comprehensive slot-fill system for the Donor Details page, enabling developers to extend the page with custom sections through WordPress's plugin registration system. The implementation provides access to form context hooks and shared admin components, allowing for seamless integration with the existing form state and UI patterns.
1. **Slot-Fill Architecture**: Implemented WordPress slot-fill pattern using `PluginArea` and `Fill` components to allow extensions to inject custom content into the Donor Details page.
2. **Shared Component Exposure**: Exposed `AdminSection` and `AdminSectionField` components globally via `window.givewp.admin.components` for consistent UI patterns across extensions.
3. **Form Context Integration**: Added global access …

feature: add Donor Details page slot-fill system

---

src/Framework/Exceptions/Primitives/HttpHeaderException.php
src/PaymentGateways/PayPalCommerce/DataTransferObjects/PayPalWebhookHeaders.php
tests/Unit/PaymentGateways/PayPalCommerce/DataTransferObjects/PayPalWebhookHeadersTest.php

Resolves [GIVE-2630]
Some users were experiencing the _"Missing PayPal webhook header"_ error due to inconsistent header formats in their server configurations. This was happening because different web servers (Apache, Nginx) and their configurations can modify HTTP headers in various ways:
1. Converting headers to uppercase (e.g., `PAYPAL-TRANSMISSION-ID`)
2. Replacing hyphens with underscores (e.g., `paypal_transmission_id`)
3. Using mixed case formats (e.g., `Paypal-Transmission-Id`)
Our code was only handling the standard lowercase format with (`Paypal-Transmission-Id`), causing the webhook validation to fail when receiving headers in different formats.
Although we already had fixed it partially here: https://github.com/impress-org/givewp/pull/5403
It wasn't enough to cover all …

Fix: normalize header keys to prevent "Missing PayPal webhook header" errors in servers that change the header keys

---

src/FormBuilder/ViewModels/FormBuilderViewModel.php
src/PaymentGateways/Gateways/PayPalCommerce/payPalCommerceGateway.tsx
tests/Unit/ViewModels/FormBuilderViewModelTest.php

Resolves [GIVE-2626]
This PR fixes a bug that was preventing the PayPal modal from opening when a custom field with the meta key "country" was added to a v3 form.
To accomplish that, the following was implemented:
1. Add the billing address fields (country, zip, etc.) to the disallowed list of custom field names.  This will ensure we don't get a conflicting unique field name. So is still possible to add a custom `country` field, but it will be like `country_1` instead of our `country` field.
2. Sanitize the country field value to ensure it matches the 2-digit code syntax we are expecting. This would just be a safeguard and dosen't have any validation if the country code is valid.
PayPal Donations on V3 forms
1. Add a custom text field to a V3 form and set the name to "country," then make …

Fix: PayPal closing modal when a custom country field is added to v3 forms

---

includes/admin/donors/class-donor-table.php
includes/admin/donors/donor-actions.php
includes/admin/donors/donor-functions.php
includes/admin/donors/donors.php
src/Donors/DonorsAdminPage.php
src/Donors/ListTable/Columns/DonorInformationColumn.php

Updated the new donor details view to be the default (existing) url.  To preserve backwards compatibility with the old view, a new `legacy-` prefix was added to old urls.
The donor details page
- Open a donor details screen by default you should see the new view
- Go to donors list and switch to legacy.  Then click on a donor and you should see old view
- Manually you can change `&page=overview` to `&page=legacy-overview`

Refactor: update default donor detail url and preserve legacy view

---

src/Campaigns/Blocks/DonateButton/render.php
src/Campaigns/Blocks/DonateButton/styles.scss

Resolves [GIVE-2435]
This updates the campaign donate button to support v2 forms by using `give_form_shortcode` which supports both form types.
The campaign donate button block
https://github.com/user-attachments/assets/bde80f74-f9f2-4eaf-b98b-8a54bf6f8340
ZIP: https://github.com/impress-org/givewp/actions/runs/15567129875
- Create a campaign with a v2 form
- Make the v2 form the default form
- Visit the campaign landing page and the button should still be there and work properly
- Now make sure campaigns with v3 forms still work as expected
-   [ ] [Self …

Fix: update campaign donate button block to support v2 forms

---

src/FormBuilder/Actions/ConvertLegacyNotificationToEmailNotificationData.php
src/FormBuilder/resources/js/form-builder/src/settings/group-email-settings/email/template-options/settings.tsx

Resolves [GIVE-2649]
The recurring emails in the form builder were causing a blank white page on selection.  This is because they use different field id mapping that core.  This does the proper field mapping and adds some conditionals when missing.
Form builder recurring emails settings
ZIP: https://github.com/impress-org/givewp/actions/runs/15634341320
- Install recurring and enable renewal emails
- Go to the form builder, settings, email and interact with recurring email templates
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) …

Fix: recurring email templates in form builder

---

src/API/REST/V3/Routes/Donations/DonationController.php
tests/Unit/API/REST/V3/Routes/Donations/DonationRouteUpdateTest.php

Resolves [GIVE-2672]
This PR adds editable and deletable REST API endpoints for donations in the V3 API. The implementation includes custom handlers for special fields that require specific processing logic when updating donation records through the admin interface.
The feature implements PUT/PATCH and DELETE endpoints for the  route with comprehensive validation and error handling. Special fields like billing details are handled through dedicated processors to ensure data integrity and proper business logic execution.
Donations V3 API
1. Test the PUT/PATCH endpoint: `PATCH /wp-json/givewp/v3/donations/{id}` with donation field updates
2. Confirm DELETE endpoint: `DELETE /wp-json/givewp/v3/donations/{id}` removes donations
[GIVE-2672]: …

Feature: Add editable donation endpoints

---

src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/DonationStats/index.tsx
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/index.tsx

Removes the unused details prop from the DonationStat component and passes the actual donation currency to ensure the correct currency symbol is shown, rather than defaulting to the global settings currency.
DonationStats
Problem - Donation made with Euros*
Solution
- Use Currency switcher to make a donation with a different currency.
- View the Donation Overview and ensure the correct symbol is shown.

Fix: use currency from donation in DonationStats

---

give.php
src/ThirdPartyCompatibility/Divi/DeregisterEntityScripts.php
src/ThirdPartyCompatibility/ServiceProvider.php

This PR resolves the issue with the Divi theme builder. The problem with the Divi theme builder is that it deregisters WP core scripts that are used by GiveWP entities. The issue is resolved by deregistering GiveWP entities on Divi theme builder pages. 
Make sure GiveWP 4.0 + and the Divi theme are installed.
In WP Admin, Go to Divi > Theme Builder.
In any template, click Add Global Body.
Click Build Global Body.

Fix: Divi compatibility issues

---

src/Helpers/Language.php

In a French receipt, texts are in English. These texts are displayed in Ajax, so `get_user_locale()` was used. Its value is `"site-default`" and we try to load` give-site-default.mo` as language pack.

Fix: language pack not loaded (Don't use get_user_locale() in Ajax)

---

readme.txt
src/Onboarding/Setup/templates/index.html.php
src/Onboarding/Setup/templates/stories/src/stripe.js
src/PaymentGateways/Stripe/Admin/AccountManagerSettingField.php

Resolves [GIVE-2692]
This PR adds information about Stripe fees in the WP readme file and in all places where it is possible to connect a Stripe account.
Stripe Copies
In the `readme.txt` file and in `GiveWP > Setup` page, make sure this copy is displayed:
> Additional fees may apply for free users. Read our [Stripe documentation](https://docs.givewp.com/stripe-fees) for more information.
In the `GiveWP > Settings > Payment Gateways > Stripe` page, make sure this copy is displayed:
> An additional 2% fee is applied to donations for free users (removed with any premium product license). Read our [Stripe documentation](https://docs.givewp.com/stripe-fees) for more information. …

Refactor: add information about Stripe fees

---

src/DonationForms/Properties/GoalSettings.php

Resolves https://lw.slack.com/archives/C072VS4FT1A/p1750798143514369
This PR fixes fatal errors that occur in PHP 8.1+ when using the GoalSettings class. The issue occurs when any of the expected keys are missing or null in the data array passed to the fromArray() method, because the strict types declared in the class will trigger a fatal error if invalid values are passed in.
**Root Cause**: PHP 8.1+ enforces stricter type checking, and when properties with strict type declarations receive null or undefined values, it causes fatal errors.
**Solution**: Added default values using the null coalescing operator to ensure all properties receive appropriate fallback values:
- goalSource: defaults to empty string
- enableDonationGoal: defaults to false
- goalType: defaults to GoalType::AMOUNT
- …

Fix: Add default values to GoalSettings for PHP 8.1+ compatibility

---

src/Settings/DonationForms/Actions/SanitizeCustomFormStyles.php
src/Settings/ServiceProvider.php

Resolves [GIVE-2589]
This PR fixes an issue where CSS selectors containing the `>` (direct descendant) symbol were being converted to `&gt;` when saved in the Custom Styles field (GiveWP > Settings > Advanced > Donation Forms). This happened because we were sanitizing that setting with `wp_kses_post()` which escapes unwanted HTML entities, breaking valid CSS selectors like `.parent > .child`.
The fix implements a custom sanitization method specifically for the `custom_form_styles` option that uses `wp_strip_all_tags()`. This allows CSS selectors to remain intact while still preventing malicious code injection by stripping HTML tags.
Global CSS settings
https://github.com/user-attachments/assets/efbe4d74-2384-4b78-9d8c-4ad783518742
1. Navigate to GiveWP > Settings > Advanced > Donation …

Fix: prevent CSS selector escaping in custom form styles

---

src/Donations/ViewModels/DonationViewModel.php

Resolves [GIVE-2616]
This adds a filter for the donation details custom fields.  Currently the filter is very simple, just an array of objects with label and value.  In the future we'll likely add field types but this is a good start.
Donation details
Hook into the filter and add new custom fields
```php
add_filter('givewp_donation_details_custom_fields', function ($customFields, $donationId) {
$customFields[] = [
'label' => 'Custom Field',
'value' => 'Custom Value',
];
return $customFields;
}, 10, 2);
```
Can also be used with FFM via https://github.com/impress-org/give-form-field-manager/pull/427 …

Feature: add filter for custom fields on donation details

---

src/DonationForms/V2/DataTransferObjects/DonationFormQueryData.php
tests/Unit/DonationForms/V2/DataTransferObjects/TestDonationFormQueryData.php

Resolves https://lw.slack.com/archives/C072VS4FT1A/p1751552838561639
Resolves https://lw.slack.com/archives/C072VS4FT1A/p1752259837570329?thread_ts=1751412176.419479&cid=C072VS4FT1A
This PR fixes this PHP 8.1+ error: 
`Uncaught TypeError: Give\DonationForms\V2\DataTransferObjects\DonationFormQueryData::convertGoalType(): Argument #1 ($type) must be of type string, null given`

Fix: cast $queryObject->goalFormat to string to prevent PHP 8.1+ error

---

src/DonationForms/resources/app/hooks/useFormData.ts

Resolves [GIVE-2705]
This PR fixes a bug that prevented the PayPal modal from opening when donations were made with Fee Recovery in currencies that do not support decimals. A browser console error was being thrown, saying that decimals are not supported.
PayPal Donations made with zero decimal currencies and Fee Recovery
1. Set a V3 form with PayPal and Fee Recovery enabled
2. Go to `GiveWP > Settings > General > Currency` and choose the `Japanese Yen (¥)` option
3. Create some test donations and make sure they get finished with the proper amounts
-   [ ] [Self …

Fix: PayPal donations with zero decimal currencies (like Japanese Yen) with Fee Recovery enabled are not working

---

includes/admin/settings/class-settings-email.php

Fix: This string is not formatted correctly for translation
Fix https://wordpress.org/support/topic/this-string-is-not-formatted-correctly-for-translation-8/

Fix: This string is not formatted correctly for translation

---

src/API/REST/V3/Routes/Subscriptions/SubscriptionNotesController.php
src/Subscriptions/DataTransferObjects/SubscriptionNoteQueryData.php
src/Subscriptions/Factories/SubscriptionNoteFactory.php
src/Subscriptions/Models/Subscription.php
src/Subscriptions/Models/SubscriptionNote.php
src/Subscriptions/Repositories/SubscriptionNotesRepository.php
src/Subscriptions/Repositories/SubscriptionRepository.php
src/Subscriptions/ServiceProvider.php
src/Subscriptions/ValueObjects/SubscriptionNoteMetaKeys.php
src/Subscriptions/ValueObjects/SubscriptionNoteType.php
tests/TestTraits/RefreshDatabase.php
tests/Unit/API/REST/V3/Routes/Subscriptions/SubscriptionNoteRouteTest.php
tests/Unit/Subscriptions/LegacyCompatibilityTest.php
tests/Unit/Subscriptions/Models/TestSubscriptionNote.php
tests/Unit/Subscriptions/Repositories/TestSubscriptionNoteRepository.php

Resolves GIVE-2679
This PR implements a new subscription notes endpoint for the Give API that provides comprehensive functionality for managing subscription-related notes. The implementation follows the existing model/repository pattern and extends the Give API V3 with new REST endpoints.
- **`SubscriptionNote` model** with structured data handling and validation  
- **`SubscriptionNoteRepository`** for persistence and retrieval logic  
- **`SubscriptionNoteController`** exposing a complete set of RESTful endpoints under `/givewp/v3/subscriptions/{id}/notes`  
- **Supporting infrastructure** including DTOs, ValueObjects, and Factory classes  
- **Improved legacy compatibility** to ensure seamless integration with existing recurring features  
As part of this update, we are deprecating …

Feature: Add subscription notes endpoint for GIVE API

---

src/Admin/components/Header/styles.module.scss
src/Admin/components/StatWidget/index.tsx
src/Admin/components/StatWidget/styles.module.scss
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/DonationStats/index.tsx
src/Donations/resources/utils.ts
src/Donors/resources/admin/components/DonorDetailsPage/Tabs/Overview/DonorStats/index.tsx
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Overview/SubscriptionStats/index.tsx
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Overview/SubscriptionStats/styles.module.scss
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Overview/index.tsx
src/Subscriptions/resources/hooks/index.ts
src/Subscriptions/resources/hooks/useDonationsBySubscription.ts

Resolves [GIVE-2699]
This PR introduces a SubscriptionStats component to the Subscription Details page Overview tab, displaying key metrics about a subscription's donations and payment progress. It also updates StatWidget to support additional value type.
Displays:
- Total contribution so far (sum of all donation amounts).
- Payments completed (completed installments out of total installments, or ∞ if ongoing).
Key Changes
- New Hook: useDonationsBySubscription. Retrieves donation records associated with a given subscription via useEntityRecords.
StatWidget Enhancements
- Supports value as number | string | React.ReactNode.
- Ensures numeric formatting by parsing values when applicable.
These changes improve the subscription management experience by giving administrators quick visibility …

Feature: Add Subscription stat cards to Overview

---

src/API/REST/V3/Routes/Donations/DonationController.php
src/API/REST/V3/Routes/Donations/DonationNotesController.php
src/API/REST/V3/Routes/Donors/DonorController.php
src/API/REST/V3/Routes/Donors/DonorNotesController.php
src/Donors/resources/entity.ts

This PR enhances our API endpoints to support custom REST fields following WP API standards. The implementation adds standardized custom field support across our REST API v3 endpoints, enabling better data extensibility and addon integration capabilities.
- **REST API v3 Custom Fields Support**: Enhanced donation, donation-note, donor and donor-note controllers to handle custom field operations (create, read, update)
- **WP API Standards Compliance**: Implemented custom field handling following WordPress REST API conventions
- **Improved Schema Definitions**: Updated endpoint schemas to include custom fields specifications
The changes primarily focus on the core REST API infrastructure, providing a foundation for add-ons to extend data models through standardized custom field mechanisms. …

Feature: Add support for custom REST fields

---

src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Overview/SubscriptionSummaryGrid/index.tsx

This PR updates the `SubscriptionSummaryGrid` components to use the `renewsAt` value for the "Next Payment" card date - as opposed to the `createdAt` date.
Subscription Summary Grid - Next Payment Card
- Create a daily subscription.
- View the Subscription from the Overview tab
- Verify the Next Payment Card reflects the following day/payment selected

Fix: Update SummaryGrid Next Payment Card date value

---

src/Campaigns/Actions/RenderDonateButton.php
src/Campaigns/Blocks/CampaignDonations/resources/views/render.php
src/Campaigns/Blocks/CampaignDonations/styles.scss
src/Campaigns/Blocks/CampaignDonors/resources/views/render.php
src/Campaigns/Blocks/CampaignDonors/styles.scss
src/Campaigns/ServiceProvider.php
src/DonationForms/Factories/DonationFormFactory.php
tests/GiveTests/Unit/Actions/RenderDonateButtonTest.php

Resolves [GIVE-2644]
This PR fixes an issue where Campaign blocks were not properly rendering v2 forms by replacing the `BlockRenderController` with the standard `give_form_shortcode` function. The `RenderDonateButton` action has been refactored to use the shortcode-based approach, which ensures better compatibility with v2 forms and provides consistent rendering behavior across the platform.
Campaign blocks rendering donate buttons (Campaign donation and donor blocks)
https://github.com/user-attachments/assets/7f1f5954-e122-4caa-b925-e0e3c69a1364
1. Create a Campaign with a v2 form
2. Add Campaign blocks (donations, donors, donate button) to a page
3. Verify that the donate button renders correctly and opens the form in modal
4. Test both editor preview and frontend display
5. Repeat the …

Fix: Update Campaign blocks to properly render v2 forms

---

src/ThirdPartySupport/Elementor/Actions/RegisterWidgetEditorScripts.php
src/ThirdPartySupport/Elementor/ServiceProvider.php
src/ThirdPartySupport/Elementor/Widgets/V1/GiveFormWidget.php
src/ThirdPartySupport/Elementor/Widgets/V1/resources/formWidget.jsx
webpack.config.js

Resolves [GIVE-2822]
This fixes the legacy form widget script preview in the editor by registering a necessary js script that is used in the editor for v3 forms.
The legacy form widget
ZIP: https://github.com/impress-org/givewp/actions/runs/17214314578
- Make sure the Elementor legacy form widget works properly with v3 and v2 forms (to match old add-on functionality)
- Make sure the GiveWP category shows up when the old add-on is not installed
- Make sure there no regression issues 
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) …

Fix: Elementor legacy form widget preview

---

src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Records/index.tsx
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Records/styles.module.scss

New Files Added:
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Records/styles.module.scss - Styling for the empty state component
Files Modified:
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Records/index.tsx - Added empty state logic and UI based on whether there are any slot fills available.
Subscription Records Tab
https://github.com/user-attachments/assets/94c112fc-e984-4c32-8da8-5a2f524f8faf
- Visit a Subscription through the edit button on the subscription list table
- Navigate to the Records tab - verify that the empty state displays.
- Install & Activate Give-Funds
- Revisit the Records tab & verify the empty state no longer displays & that the give-funds logic is visible and working
-   [x] Acceptance criteria satisfied and …

Refactor: add records empty slate

---

src/Donations/resources/components/DonationRowActions.tsx
src/Views/Components/ListTable/ListTablePage/ListTablePage.module.scss

Resolves https://lw.slack.com/archives/C04SLRDD9CK/p1756844747622119?thread_ts=1756843777.960549&cid=C04SLRDD9CK
This PR simply updates the z-index for the A11yDialog component so that the container covers not only the Subscriptions-Donation's tab header but also the WordPress sidebar.
It also removes the text context claiming that trash donations can be restored - since this has not yet been implemented.
All List Table Modal Contexts
https://github.com/user-attachments/assets/939b0ab0-3066-4998-9e0c-c94ab22d1522
- View the new Subscription screen and navigate to the Donations tab
- Select to trash a renewal
- Verify the blur container visually covers the entire UI
- …

Fix: update List Table Modal `A11YDialog`

---

src/Subscriptions/ViewModels/SubscriptionViewModel.php
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/index.tsx
tests/Unit/API/REST/V3/Routes/Subscriptions/SubscriptionRouteGetItemTest.php
tests/Unit/API/REST/V3/Routes/Subscriptions/SubscriptionRouteGetItemsTest.php

Resolves https://lw.slack.com/archives/C04SLRDD9CK/p1756908964317189?thread_ts=1756843777.960549&cid=C04SLRDD9CK
Remove the conditional check that would previously show the can sync button if there was no gateway available. This is incorrect though, the button should show only when the gateway allows syncing. 
Also updates the check for the current gateway to see if it has the capability to sync transactions - this will help avoid issues with legacy gateways performing there own sync function through the new UI by hiding the sync subscription button when working with a legacy gateway subscription.
Subscription Sync
-   [ ] Reviewed by the …

Fix: remove conditional on canSync variable

---

src/API/REST/V3/Routes/Donations/DonationController.php
src/Donations/Repositories/DonationRepository.php
src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/DonationSummaryGrid/index.tsx
src/Subscriptions/Repositories/SubscriptionRepository.php
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Overview/index.tsx
tests/Unit/API/REST/V3/Routes/Donations/DonationRouteCreateTest.php
tests/Unit/API/REST/V3/Routes/Donations/DonationRouteUpdateTest.php

Resolves [GIVE-2870]
This hotfix addresses an issue where a donation could not be updated through the details screen after the campaign field was changed. Changes in this PR include:
•	Removed `campaignId` from the `nonEditableFields` property in the donations API endpoint, allowing it to be updated.
•	Moved the fallback logic for `campaignId` assignment to `getCoreDonationMetaForDatabase` to centralize it, removing redundant logic from the `insert` method in the donations repository and the `createRenewal` method in the subscriptions repository.
Donation Details and Subscription Details
https://github.com/user-attachments/assets/bf6c936d-b3bb-4611-8efb-920f658a7b6b
_We can now update a donation after removing `campaignId` from the `nonEditableFields` list._ …

Hotfix: Ensure campaignId is saved in donation details

---

includes/admin/emails/class-new-offline-donation-email.php

When we preview the 'new-offline-donation' default message for admin, the 'new-donation' message is used. 
==> Use the correct function for the default message.

'new-offline-donation': preview the correct default message

---

src/Donations/resources/admin/components/DonationDetailsPage/Tabs/Overview/DonationSummaryGrid/index.tsx
src/Subscriptions/resources/admin/components/SubscriptionDetailsPage/Tabs/Overview/SubscriptionSummary/index.tsx

Resolves #
The subscription details form link was hard-coded to the visual form builder.  This did not account for v2 forms so the link was updated to the standard edit url which already has logic in place to redirect when it's a v3 form.
Also, _view details_ was changed to _view subscription_ in the donation details screen.
The subscription form link
N/A
- Create a subscription with a v2 form
- Create another one with a v3 form
- Make sure the link to the form works for both subscriptions
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-r …

Fix: subscription details form link

---

src/LegacySubscriptions/includes/give-subscription.php
src/LegacySubscriptions/includes/give-subscriptions-db.php
src/Subscriptions/DataTransferObjects/SubscriptionQueryData.php
src/Subscriptions/Migrations/AddCampaignId.php
src/Subscriptions/Migrations/AddCampaignIdColumn.php
src/Subscriptions/Models/Subscription.php
src/Subscriptions/Repositories/SubscriptionRepository.php
src/Subscriptions/ServiceProvider.php

This pull request introduces two new database migrations to support the addition of a `campaign_id` field to the `give_subscriptions` table, and setting the `campaign_id` for each subscription. 
`give_subscriptions` table

Feature: Add campaign ID to subscriptions
