includes/admin/reporting/class-form-reports-table.php
=> Check that categories are returned and are not a WP Error. #91

templates/shortcode-receipt.php
Please add new action - give_payment_receipt_before_table.
----
Similar as existing action - give_payment_receipt_after_table
=> New action - give_payment_receipt_before_table

includes/forms/template.php, templates/single-give-form/featured-image.php
Just contributing a few inline docs :) (More PRs to come!)
=> inline Docs for /forms/template.php and /single-give-form/featured-image.php

includes/admin/admin-notices.php, includes/emails/template.php
RE: https://github.com/WordImpress/Give/issues/102
=> Admin notice when test email sent 

CONTRIBUTING.md
=> Coding standards

composer.json
=> Decrease required PHP version in composer.json

README.md
=> Add CONTRIBUTING.md to README.md

includes/admin/customers/customer-functions.php, includes/admin/customers/customers.php
The Delete area of the Donor management system still had some Customer text laying around.  I converted to Donor.
=> Change rendered text Customer to Donor

includes/admin/register-settings.php, includes/scripts.php
=> New option to load scripts in the footer Fixes #209

includes/admin/forms/dashboard-columns.php, readme.txt
=> Check if form has goal for admin column

includes/gateways/offline-donations.php
=> Fixed issue with multiple gateways

includes/admin/class-addon-activation-banner.php
=> New activation banner

includes/admin/register-settings.php, readme.txt
When you save the Give Global Settings there is now a notice that displays Fixes #312
=> New settings_notices method for displaying the Updated message

.scrutinizer.yml, Gruntfile.js
=> 😷 Remove transifex references 💀

includes/forms/template.php, includes/shortcodes.php, readme.txt
=> Take into account shortcode show_goal option when outputting goal

includes/forms/template.php
=> Wrapped html5 required attributes with give_is_field_required #361

includes/admin/payments/class-payments-table.php, includes/class-give-db-customers.php
=> User link aka now "Donor" link now goes to donor's page #258

readme.txt
=> Fix the broken link to github repo link

includes/class-give-stats.php, includes/payments/class-payment-stats.php
=> Fixed missing earnings stats calculation

includes/class-give-db.php
=> Added table_exists method to Give_DB class

give.php, includes/class-give-cron.php, includes/payments/actions.php, readme.txt, uninstall.php
=> New Give_Cron class added

includes/shortcodes.php
=> Check for session purchase key before shortcode attribute

includes/admin/reporting/class-gateways-reports-table.php, includes/class-give-stats.php, includes/payments/class-payment-stats.php
Added "Total Donations" column to payments stats
#302
=> Modified get_earnings to filter by payment gateway in use

includes/emails/class-give-email-tags.php
=> Output URL if plain-text selected for email format

includes/admin/payments/class-payments-table.php, includes/post-types.php, tests/unit-tests/tests-post-types.php
Fixes #514 
@DevinWalker please review.
=> Show "cancelled" transactions on Transaction page

includes/gateways/functions.php
=> Check $_POST for enabled gateways before $give_options

give.php, includes/admin/plugins.php, readme.txt
=> New links on the plugin settings page Fixes #531

includes/misc-functions.php
=> Use trailingslashit to prevent homepage redirect #545

give.php, includes/plugin-compatibility.php
Fixed issue with Mandrill line-breaks messing up Give emails
#548
=> New plugin-compatibility.php file

includes/admin/system-info.php, readme.txt
=> Added a check for DOM and MBString PHP extensions in System Info tab

includes/class-give-email-access.php, readme.txt
Also prepend with @ to suppress any errors/warnings
Fixes #570
=> Set appropriate cookie path using constant COOKIE_PATH

includes/forms/template.php
=> Add the form ID to template action hooks

includes/admin/class-admin-notices.php
"This may causes issues with Give." => "This may cause issues with Give."
=> Fixes small typo in admin ajax notice

changelog.txt, readme.txt
=> New changelog.txt file and added dates #596

includes/misc-functions.php
Fix bug for https://github.com/WordImpress/Give/issues/622
=> Fix bug on current_url retrival

includes/process-purchase.php
This commit will prevent getting _undefined function_ fatal error.
=> Use funciton give_get_errors instead edd_get_errors

includes/admin/class-give-settings.php, includes/admin/customers/class-customer-table.php, includes/admin/reporting/class-gateway-error-logs-list-table.php, includes/emails/class-give-email-tags.php, includes/emails/template.php
Avoid using HTML tags in translation strings.
=> i18n Improvments

includes/admin/admin-footer.php, includes/admin/class-addon-activation-banner.php, includes/admin/class-give-settings.php, includes/admin/shortcodes/shortcode-give-form.php, includes/admin/shortcodes/shortcode-give-goal.php, includes/class-give-email-access.php, includes/class-give-license-handler.php, includes/emails/functions.php, includes/gateways/offline-donations.php, includes/process-purchase.php, templates/email-login-form.php
Like the previous pull request, this one has many more needed i18n fixes.
=> More i18n improvments

includes/forms/template.php
Proof-of-concept based on support ticket user feedback. https://secure.helpscout.net/conversation/224241808/2731/?folderId=672199
=> Adds "forgot password" link to login form.

includes/payments/class-give-payment.php
Related to https://github.com/WordImpress/Give/issues/726
=> Decrease stat if payment update from revoked/complete to cancelled

includes/admin/class-give-settings.php
=> Fix broken plugin welcome url

includes/admin/class-give-settings.php, includes/admin/customers/customers.php, includes/admin/payments/view-order-details.php, includes/admin/reporting/reports.php, includes/class-give-html-elements.php, includes/forms/template.php, includes/gateways/offline-donations.php, includes/login-register.php, includes/process-purchase.php
This time I'm fixing the _x(). Translations with context. Update context text in some places, remove context in other places, and few extra translation string updates.
=> Few more i18n improvments

includes/admin/class-give-settings.php, includes/admin/reporting/class-donor-reports-table.php, includes/admin/welcome.php, includes/api/class-give-api.php, includes/class-give-donate-form.php, includes/class-give-session.php, includes/class-give-template-loader.php, includes/formatting.php, includes/gateways/offline-donations.php, includes/payments/functions.php, includes/post-types.php, includes/user-functions.php, templates/shortcode-profile-editor.php, templates/single-give-form/featured-image.php, templates/single-give-form/sidebar.php, templates/single-give-form/title.php
Related to https://github.com/WordImpress/Give/issues/733
=> Remove @description tag from code documentation

includes/forms/template.php
fixes js conflict with multiple forms on a page. 
fixes #741
=> adds form id to terms link class

includes/admin/reporting/class-give-graph.php, includes/admin/reporting/graphing.php, includes/scripts.php
Related to issue: https://github.com/WordImpress/Give/issues/749
=> Reports Tooltip & Donation Counts Needs Proper Formatting

includes/emails/class-give-email-tags.php
=> strips the tags from the donation form

includes/formatting.php
Related to :  https://github.com/WordImpress/Give/issues/764
=> Fix smaller then million amount formatting issue

assets/js/admin/admin-scripts.js, includes/formatting.php, includes/scripts.php
Related to : https://github.com/WordImpress/Give/issues/778
=> Amount field not formatting on focus out & lingering tooltip issues

assets/scss/frontend/_mixins.scss, assets/scss/frontend/forms.scss, assets/scss/frontend/receipt.scss, assets/scss/frontend/rtl.scss, assets/scss/frontend/tables.scss
=> Give frontend RTL

includes/admin/reporting/pdf-reports.php, readme.txt
=> New filter for PDF export logo

includes/admin/class-api-keys-table.php
This pull request will fix #823
=> Auto select api key when click on input field

includes/api/class-give-api.php
This pull request will fix #821
=> Fix transient key name

give.php, includes/admin/upgrades/upgrade-functions.php, includes/class-give-customer.php, includes/class-give-db-customer-meta.php, includes/class-give-db-customers.php, includes/install.php, readme.txt, tests/unit-tests/tests-customer-meta.php, uninstall.php
=> New Customer Meta Class & Table

includes/template-functions.php
`is_give_form()`, `is_give_category()`, `is_give_tag()`, `is_give_taxonomy()`
=> Add Give conditional functions

includes/gateways/offline-donations.php, readme.txt
=> Fixes Admin Offline Donation Notification

includes/admin/shortcodes/abstract-shortcode-generator.php, readme.txt
=> Add check for ability to edit give forms

includes/admin/dashboard-widgets.php, includes/admin/payments/actions.php, includes/admin/reporting/class-export-earnings.php, includes/admin/reporting/tools/class-give-tools-recount-all-stats.php, includes/admin/reporting/tools/class-give-tools-recount-customer-stats.php, includes/admin/reporting/tools/class-give-tools-recount-form-stats.php, includes/admin/reporting/tools/class-give-tools-recount-income.php, includes/admin/reporting/tools/class-give-tools-recount-single-customer-stats.php, includes/class-give-donate-form.php, includes/payments/class-give-payment.php, includes/payments/functions.php
=> Form stats increase each time the payment status changes from revoked to complete 

includes/admin/reporting/class-form-reports-table.php, includes/post-types.php
Found a couple spots where "Downloads" are still referenced.
=> removes EDD language

includes/admin/payments/class-payments-table.php
Addresses issues with linking destinations and adds additional tooltips - Fixes #865 
Related to #813 and #814
=> Transaction column fixes and touch ups #865

includes/admin/forms/dashboard-columns.php, includes/admin/forms/metabox.php, templates/email-login-form.php, templates/shortcode-profile-editor.php
=> a11y - add 'for' attributes to labels

includes/forms/template.php, templates/shortcode-login.php
We already use the **Reset Password** string.
This PR replaces **Reset password?** and **Lost Password?** with **Reset Password**, merging those 3 similar translations strings into one.
=> Text Change - replace "Lost Password?" with "Reset Password"

includes/admin/payments/view-order-details.php
Resolving #887 .
Before:
After:
=> a11y: transaction page

includes/admin/add-ons.php, includes/admin/class-give-settings.php, includes/admin/customers/customers.php, includes/admin/payments/view-order-details.php, includes/admin/reporting/class-api-requests-logs-list-table.php, includes/admin/reporting/class-gateway-error-logs-list-table.php, includes/admin/welcome.php, includes/class-give-html-elements.php, includes/emails/template.php, includes/forms/template.php
=> a11y: remove "title" attributes for better accessibility

includes/admin/payments/view-order-details.php, includes/ajax-functions.php, includes/payments/actions.php, includes/payments/class-give-payment.php, includes/payments/class-payments-query.php, includes/payments/functions.php
I think I finished documenting all the action hooks.
=> Docs: document action hooks

includes/admin/customers/class-customer-table.php, includes/admin/payments/class-payments-table.php, includes/admin/reporting/class-api-requests-logs-list-table.php, includes/admin/reporting/class-donor-reports-table.php, includes/admin/reporting/class-give-graph.php, includes/admin/reporting/export/export-actions.php, includes/admin/reporting/export/export-functions.php, includes/admin/reporting/graphing.php, includes/admin/reporting/logs.php, includes/admin/reporting/reports.php, includes/admin/reporting/tools.php, includes/api/class-give-api.php, includes/class-give-db-customers.php, includes/class-give-db.php, includes/class-give-logging.php, includes/emails/class-give-email-tags.php, includes/emails/class-give-emails.php, includes/emails/functions.php, includes/emails/template.php, includes/forms/widget.php, includes/gateways/actions.php, includes/gateways/functions.php, includes/gateways/offline-donations.php, includes/gateways/paypal-standard.php
=> a11y: add role="search" for better accessibility

includes/admin/payments/class-payments-table.php
Resolving issue #866 .
See screenshots in the issue page.
=> Make transaction columns "Donation Form" and "Status" sortable

includes/actions.php, includes/admin/admin-actions.php
More docs, and implementing #897 .
I need to mention that the `init` uses `give_action` and the `admin_init` uses `give-action`. Mistake?
=> Document action hooks

includes/admin/class-give-settings.php, includes/admin/reporting/reports.php, includes/api/class-give-api.php, includes/class-give-db.php, includes/emails/class-give-emails.php, includes/forms/template.php, includes/gateways/functions.php, includes/gateways/paypal-standard.php, includes/template-functions.php
=> Dynamic action hooks structure

assets/scss/admin/payment-history.scss, includes/admin/payments/view-order-details.php
=> Transaction Details > Donor Details Metabox

includes/admin/class-give-settings.php
=> Issue/920 - check label focus

includes/admin/customers/customers.php
=> Issue/934 - add H1 heading to admin "Donor" screen

includes/admin/customers/customers.php, includes/admin/payments/class-payments-table.php, includes/admin/system-info.php, includes/emails/template.php, includes/payments/functions.php
=> Issue/918 - replace `title` attributes with `aria-label`

includes/admin/class-give-settings.php, includes/admin/customers/class-customer-table.php, includes/admin/payments/view-order-details.php, includes/admin/reporting/class-donor-reports-table.php, includes/admin/reporting/class-export-earnings.php, includes/admin/reporting/class-export.php, includes/admin/reporting/export/class-batch-export-customers.php, includes/admin/reporting/export/class-batch-export-forms.php, includes/admin/reporting/export/class-batch-export-payments.php, includes/admin/reporting/tools/class-give-tools-reset-stats.php, includes/emails/template.php, includes/formatting.php, includes/payments/class-give-payment.php
=> Dynamic filter hooks

templates/shortcode-goal.php
=> Issue/925 - progress bar accessibility

includes/admin/customers/customers.php, includes/admin/reporting/graphing.php, includes/admin/reporting/reports.php, includes/misc-functions.php, templates/history-donations.php, templates/shortcode-receipt.php
=> Issue/922 - table accessibility

includes/admin/class-give-settings.php, includes/emails/class-give-email-tags.php
=> Issue/581 - Add {receipt_link_url} email tag

includes/admin/class-give-settings.php
Part o issue #876
@mathetos please review the changes.
=> Issue/876 - Shorten description strings in Give Settings Screen

includes/gateways/offline-donations.php
=> Fix issue #981

includes/formatting.php
=> Use missing  parameter

includes/admin/class-give-settings.php, includes/forms/template.php
=> Override per form term and condition empty settings with global setting

includes/admin/class-give-settings.php, includes/admin/welcome.php, includes/misc-functions.php
Several updates:
* Shorten the IPN message (#876)
* Merge the two "newsletter intro" strings and move them into the `give_get_newsletter()` function (#879).
=> i18n Improvements

assets/scss/admin/rtl.scss, assets/scss/admin/welcome.scss, includes/admin/welcome.php
=> Issue/993 - Move CSS from `welcome.php` to `welcome.scss`

includes/admin/customers/customers.php, includes/admin/dashboard-widgets.php, includes/admin/forms/dashboard-columns.php, includes/admin/reporting/class-form-reports-table.php, includes/admin/reporting/class-sales-logs-list-table.php, includes/admin/reporting/pdf-reports.php, includes/admin/reporting/reports.php, includes/admin/reporting/tools.php, includes/class-give-gravatars.php, includes/class-give-html-elements.php, includes/emails/template.php, includes/forms/widget.php, includes/post-types.php, includes/scripts.php, tests/unit-tests/tests-post-types.php
=> Issue/1003 - Remove "Form Labels" functions from translation strings

includes/gateways/paypal-standard.php, readme.txt
=> PayPal first and last name support

includes/install.php, readme.txt
=> Default email receipt value upon install

includes/admin/add-ons.php, includes/admin/class-give-settings.php, includes/admin/customers/customers.php, includes/admin/payments/payments-history.php, includes/admin/reporting/reports.php, includes/admin/welcome.php
=> Issue/1028 - Start using `get_admin_page_title()` for sreen titles

includes/admin/customers/customer-actions.php, includes/admin/shortcodes/abstract-shortcode-generator.php, includes/admin/shortcodes/class-shortcode-button.php, includes/admin/shortcodes/shortcode-give-donation-history.php, includes/admin/shortcodes/shortcode-give-form.php, includes/admin/shortcodes/shortcode-give-goal.php, includes/admin/shortcodes/shortcode-give-login.php, includes/admin/shortcodes/shortcode-give-profile-editor.php, includes/admin/shortcodes/shortcode-give-receipt.php, includes/admin/shortcodes/shortcode-give-register.php, includes/admin/system-info.php, includes/class-give-donate-form.php, includes/class-give-email-access.php, includes/class-give-gravatars.php, includes/class-give-logging.php, includes/class-give-roles.php, includes/class-give-session.php, includes/class-give-template-loader.php, includes/forms/widget.php
=> Scrutinizer Comprehensibility

give.php, includes/admin/class-give-settings.php, includes/admin/system-info.php, includes/admin/upgrades/upgrade-functions.php, includes/admin/welcome.php, includes/class-give-gravatars.php, includes/class-give-license-handler.php, includes/country-functions.php, includes/forms/functions.php, includes/forms/template.php, includes/gateways/functions.php, includes/login-register.php, includes/scripts.php, tests/framework/class-give-unit-test-case.php, tests/framework/helpers/class-helper-payment.php, tests/unit-tests/tests-install.php
=> Issue/1024 - stop using `$give_options` global

includes/admin/class-addon-activation-banner.php
=> Issue/1031 - Addon alerts RTL issue

includes/class-give-db-customers.php, includes/class-give-logging.php, includes/class-give-session.php, includes/emails/class-give-email-tags.php, includes/error-tracking.php, includes/misc-functions.php, includes/payments/functions.php, includes/process-purchase.php, includes/user-functions.php
=> Scrutinizer Docs

includes/admin/plugins.php, includes/misc-functions.php
=> Plugin action links

includes/forms/widget.php
=> Convert float label widget setting to radio button

includes/admin/class-api-keys-table.php
This will fix bulk action issues.
=> Fix bulk action issue for api setting tab

readme.txt
Typo fix.
N/A
- Documentation typo fix.
=> Fix typo in change log

includes/post-types.php
Show different messages on form edit screen if form single view is disabled
Resolving #1049
Enabling and disabling the "**form single view**" in the settings page, and saving single form to check the message.
Tested. Working as expected.
=> Issue/1049 - conditional edit messages

includes/admin/class-give-settings.php, includes/forms/template.php
Please check pr https://github.com/WordImpress/Give/pull/980 for more information
=> Comment pr #980 code

includes/country-functions.php
=> Issue/1113 - Update spanish "Álava" state in give_get_spain_states_list()

includes/admin/class-admin-settings.php
1. A default value for multi check type field should be an empty array.
=> Minor Fixed

assets/scss/frontend/forms.scss, includes/forms/template.php
=> Issue/1179 - add <legend> to Terms <fieldset>

includes/forms/template.php
=> Issue/1178 - Use `aria-required=true` in required fields

includes/forms/template.php
Resolve #1186
This PR does not chance the look & feel, only the code structure.
=> Issue/1186 - Payments method radio buttons accessibility

templates/shortcode-login.php, templates/shortcode-profile-editor.php, templates/shortcode-register.php
=> Issue/1193 - Shortcodes required fields

includes/forms/template.php
=> Issue/1177 - Accessible terms display

includes/forms/template.php
=> Issue/1181 - displays terms fieldset before checkout fieldset, not inside

.github/PULL_REQUEST_TEMPLATE.md
=> Make type of changes suggestion comment in pr github template

includes/admin/payments/view-order-details.php
This pr will fix #1220 
By updating donation form of payment.
=> Update update_donation_details --> update_payment_details

tests/README.md, tests/unit-tests/tests-templates.php
Fixed unit tests and provided more instruction on how to setup, run, and write unit tests for Give. Fixes #1232 
Multiple PHPUnit runs.
`README.md` and fixed `test_get_donation_form`
=> Fixed unit tests and 

includes/payments/functions.php
=> Show multi level price if level title is not defined

includes/class-give-logging.php
This is generating a PHP notice.
=>  Minor fix: param is not need in delete_cache function

includes/forms/template.php
=> show global and default tern and agreement text conditionally

includes/class-give-cli-commands.php
=> Do not short array tag because we support PHP 5.3 >=

includes/admin/forms/dashboard-columns.php
=> Remove amount field from quick and bulk edit

includes/deprecated/deprecated-actions.php, includes/deprecated/deprecated-filters.php, includes/misc-functions.php
=> Add line and file name to error notice

includes/deprecated/deprecated-actions.php, includes/deprecated/deprecated-filters.php, includes/misc-functions.php
Reverts WordImpress/Give#1263 - #1259
=> Revert "Add line and file name to error notice"

includes/admin/payments/class-payments-table.php
=> Show default title in donation list

includes/forms/template.php
=> Do not render unpublish or transhed form

includes/class-give-donate-form.php, includes/formatting.php, includes/forms/template.php
Simple PHP doc block improvements. #675
=> Improving doc blocks / Scrutinizer #675

includes/admin/class-admin-settings.php
=> Filter wysiwyg setting field value

includes/forms/functions.php
Fix https://scrutinizer-ci.com/g/WordImpress/Give/inspections/58d9dabb-70d3-40a3-b9cc-f2ca63ec06cc/issues/files/includes/forms/functions.php?status=new&orderField=path&order=asc&honorSelectedPaths=0
=> Add missing  $low param

includes/admin/EDD_SL_Plugin_Updater.php, includes/admin/class-api-keys-table.php, includes/admin/customers/customer-actions.php, includes/admin/forms/dashboard-columns.php, includes/admin/payments/class-payments-table.php, includes/admin/reporting/class-api-requests-logs-list-table.php, includes/admin/reporting/class-sales-logs-list-table.php, includes/admin/reporting/export/class-batch-export-customers.php, includes/admin/reporting/tools/class-give-tools-reset-stats.php, includes/api/class-give-api.php, includes/class-give-cli-commands.php
=> Documentation

includes/payments/functions.php
Add`give_create_payment` filter.
=> Add give_create_payment filter

includes/forms/template.php
=> Do not render form if

includes/admin/forms/class-metabox-form-data.php, includes/admin/settings/class-settings-general.php
Minor update to #893 and fully resolves PR #1363
=> Set all docs urls to HTTP instead of HTTPS

includes/admin/class-i18n-module.php
Minor typo fix in translation notice - Fixes #1410
=> Fixed minor typo #1410

includes/admin/class-addon-activation-banner.php, includes/admin/class-admin-notices.php, includes/admin/class-give-settings.php, includes/admin/forms/class-metabox-form-data.php, includes/admin/settings/class-settings-advanced.php, includes/admin/settings/class-settings-display.php, includes/admin/settings/class-settings-email.php, includes/admin/settings/class-settings-gateways.php, includes/admin/settings/class-settings-general.php, includes/admin/tools/views/html-admin-page-system-info.php, includes/forms/widget.php, includes/gateways/offline-donations.php
Fixes #1405 
Updates all internal links to documentation to shortlinks.
=> Resolves #1405

includes/install.php
=> Setup default offline email content on plugin install

includes/forms/template.php
=> Do not always show form title for button display style

includes/admin/forms/class-metabox-form-data.php
=> makes the language less confusing

readme.txt
=> readme.txt updates fixed typos, improved language

includes/gateways/offline-donations.php
This PR will resolve #1479 and related to #1434 
=> Show offline payment gateway for new donation form

includes/login-register.php, templates/shortcode-login.php, templates/shortcode-register.php
=> Do not use global params

readme.txt
=> Implement shorturls to readme.txt

includes/admin/settings/class-settings-gateways.php, includes/gateways/offline-donations.php
Output supported email tags using `give_get_emails_tags_list()` for offline donations #1516
=> Output email template tags for offline donations gate #1516

includes/admin/reporting/class-gateway-error-logs-list-table.php
=> Show correct donation id and gateway name in log list

includes/admin/settings/class-settings-cmb2-backward-compatibility.php
=> Fix translation related cmb2 compability issue

includes/admin/EDD_SL_Plugin_Updater.php
Update EDD_SL_Plugin_Updater.php file to the latest version - First part of #1556
=> Update EDD_SL_Plugin_Updater.php file to the latest version #1556

includes/admin/upgrades/upgrade-functions.php
=> Fix: #1626

give.php
`give_init` action hook will be very helpful for addon development
=> Add give_init action hook

includes/actions.php, includes/admin/add-ons.php, includes/admin/admin-actions.php, includes/admin/class-api-keys-table.php, includes/admin/class-i18n-module.php, includes/admin/reporting/export/class-batch-export-customers.php, includes/admin/reporting/graphing.php, includes/admin/reporting/reports.php, includes/admin/reporting/tools/class-give-tools-delete-test-transactions.php, includes/admin/reporting/tools/class-give-tools-recount-income.php, includes/admin/reporting/tools/class-give-tools-reset-stats.php, includes/admin/upgrades/upgrade-functions.php, includes/admin/welcome.php, includes/ajax-functions.php, includes/api/class-give-api.php, includes/class-give-cache.php, includes/class-give-customer.php, includes/class-give-license-handler.php, includes/install.php, includes/misc-functions.php, includes/payments/actions.php, includes/payments/class-give-payment.php, includes/payments/functions.php, tests/framework/class-give-unit-test-case.php, tests/unit-tests/tests-cache.php, tests/unit-tests/tests-install.php, uninstall.php
=> Implement Give_Cache for all transients

includes/class-give-license-handler.php
notice typos and comment typos
ref #1638
=> typo fixes

includes/class-give-license-handler.php
=> Fix: #1659

includes/admin/payments/class-payments-table.php
=> Fix: #1674

includes/admin/upgrades/upgrade-functions.php, includes/class-give-roles.php
This PR is for #844. Added Capabilities to Give Worker user role for editing posts & pages and submitting it for review to admin.
Tested this feature after creating a user with Give Worker role and then creating and editing the posts and pages.
New feature (non-breaking change which adds functionality
=> Expanded Give Worker User Role - Issue/844

includes/formatting.php, tests/unit-tests/tests-formatting.php
Update `give_currency_filter` function to output text and html formatted amount with currency.
=> refactor give_currency_filter

includes/admin/forms/class-metabox-form-data.php
This PR is for #1698 
Tested the priority of Donation Form Options metabox with Yoast SEO. Also checked compatibility with ACF to make sure the change works fine with plugins which create dynamic metabox.
=> Fixed - Issue #1698

includes/deprecated/deprecated-filters.php, includes/payments/class-give-payment.php, includes/payments/functions.php, tests/unit-tests/tests-payment-class.php
Ongoing updated to terminology per #896 
- Verified manually and via unit tests.
- Code clarity improvements
=> Deprecated a bunch of *_store_* and *_customer_* filters

includes/misc-functions.php
Fire `give_get_meta` filter before setting default meta value.
=> Fix: add filter give_get_meta before setting default value

includes/install.php, includes/misc-functions.php
Fixes for the #1765 
- Tested on fresh WordPress 4.8 install. 
cc: @DevinWalker @ravinderk
=> fixed enabled donation form issue on nav menu.

includes/admin/EDD_SL_Plugin_Updater.php, includes/admin/donors/donors.php, includes/process-donation.php, languages/give.pot
=> Fix issue #1784

includes/api/class-give-api.php, tests/unit-tests/tests-api.php
Code updates by myself from https://github.com/WordImpress/Give/pull/1780
=> issue/1423 - With Code Updates from Devin Walker

includes/admin/payments/class-payments-table.php
Fixed issue #1803 
I have changed status from the donation details page to "Processing"
I have tested with WordPress 4.8
It will not affect to the other areas of the code.
=> Fixed #1803

CONTRIBUTING.md
I have suggested some minor text changes in CONTRIBUTING.md file.
Would you please check this PR?
=> Fix text changes in CONTRIBUTING.md file

includes/install.php
Prefixed `on_create_blog()` to reduce compatibility issues. #1809
=> Prefix on_create_blog() function

includes/emails/class-give-email-tags.php
This PR will resolve #1839 
This PR tested with Give addons.
=> Fix: load email tags earlier

includes/class-give-db-donors.php
=> Fix: # 1358

includes/admin/donors/donor-actions.php
I have change text domain "edit" to "give" and also change the syntax. This is my suggestion, you can close this PR if you have already done it in Future release 2.0.
=> Change text domain "edit" to "give"

includes/payments/class-payments-query.php
PR releted to issues #1888 
Manually test and also run the PHPUnit for it
=> Fix Database error #1888

includes/payments/class-payments-query.php
=> Fix: apply filters before give_pre_get_payments hook

includes/admin/payments/class-payments-table.php
=> Issues 1874

uninstall.php
=> Issues 1900

uninstall.php
This PR will fix issue appear after #1907 ( phpunit test failing )
Running PHPUnit test.
=> Fix phpunit fail cause

includes/payments/class-give-payment.php
This PR will prevent empty customer id SQL query from running.
Performance improvement
=> Query Improvement

assets/scss/frontend/modal.scss
Resolve iPhone iOS Safari scrolling issues. 
Using a iPhone and Safari
- Bug fix
=> Prevent scrolling background within iOS safari - Fixes #1866

includes/actions.php
=> Sanitizing donation level amounts before comparision

includes/admin/settings/class-settings-display.php, includes/admin/tools/views/html-admin-page-system-info.php, includes/user-functions.php, readme.txt
I've made some spelling corrections
This hasn't been tested as they're string changes.
Spelling Fix
=> Spelling Corrections

.scrutinizer.yml, .travis.yml, give.php, includes/admin/admin-actions.php, includes/gateways/paypal-standard.php, includes/payments/functions.php, tests/framework/helpers/class-helper-payment.php, tests/unit-tests/tests-errors.php, tests/unit-tests/tests-payments.php
Additional unit test for payments added.
=> Payments unit tests

includes/admin/tools/data/class-give-tools-delete-test-transactions.php
=> Fix delete log #1935

assets/js/frontend/give.js
You will need to run gulp after merging this fix
=> remove [type=“url”] from float-labels exclude option

includes/admin/tools/data/class-give-tools-delete-test-donors.php, includes/admin/tools/data/class-give-tools-delete-test-transactions.php
=> Issues 1954

includes/admin/upgrades/class-give-updates.php, includes/formatting.php
This PR will fix #1981 #1982 
Saving form settings.
=> Issues/1981 Issues/1982

includes/class-give-cron.php, includes/class-give-roles.php, includes/class-give-stats.php
=> add changes

includes/class-give-cli-commands.php
add exmple in class-give-cli-commands  for  wp give donors to list all donors
=> add wp give donors example to list all donors

includes/class-give-cli-commands.php
add wp give donors command in example
=> add command

includes/admin/donors/donor-actions.php, includes/admin/tools/data/class-give-tools-reset-stats.php, includes/class-give-db-donor-meta.php, includes/class-give-db-donors.php
PR related to issues #2028 
http://screencast-o-matic.com/watch/cbjwQNIn40
=> Issues 2028

includes/payments/functions.php, tests/unit-tests/tests-payments.php
This PR will fix #2042
I tested this with creating new donation with and without recurring add-on.
=> Return custom level id from give_get_price_id

includes/error-tracking.php
=> Fix notices #2049

includes/admin/admin-actions.php
=> Remove import donation link from donation single page #2052

assets/js/admin/admin-scripts.js, includes/scripts.php
Fix for give setting page data loss on page reload
PR for issues #1998 
See the video 
Video link http://screencast-o-matic.com/watch/cbQl3MI2uT
=> Fix for give setting page #1998

assets/js/admin/admin-scripts.js
=> Issues 2064

assets/js/admin/admin-scripts.js
=> Issues 2069

includes/user-functions.php
=> Output payment objects - Fixes #2118

includes/admin/tools/import/class-give-import-donations.php
Update description of Import CSV file screen.
Updated and confirmed that description was reflected on the screen correctly.
Just a text string change.
=> Fixes #2126

includes/admin/tools/class-settings-import.php
Fixes #2128 
Add docs link to the Importer page
=> Fixes #2128

assets/js/admin/admin-scripts.js, includes/admin/upgrades/views/upgrades.php, includes/scripts.php
=> Issues 1959

includes/admin/add-ons.php, includes/admin/admin-actions.php, includes/admin/donors/donors.php, includes/admin/payments/payments-history.php, includes/admin/payments/view-payment-details.php, includes/admin/upgrades/views/upgrades-complete.php, includes/admin/upgrades/views/upgrades.php, includes/admin/views/html-admin-settings.php
PR for issues #2140 
Tested  by add `&give-message=email_sent` on each menu and submenu of Give Core plugin 
Example: `http://SITENAME/wp-admin/edit.php?post_type=give_forms&page=give-settings&give-message=email_sent`
=> Issues 2140

includes/admin/tools/import/class-give-import-donations.php, includes/import-functions.php
PR for issues #2146 
http://recordit.co/mVpzuSvEx8
=> Fix Autofill already mapped CSV fields #2146

includes/admin/donors/donor-actions.php
PR for #2193 
- Followed steps mentioned in #2193 
Bug Fix
=> Pass default address value if not exists.

includes/import-functions.php
Fix for: https://github.com/WordImpress/Give/issues/2165
Change text for Form Title in dropdown
=> Fix - issue #2165

includes/class-give-html-elements.php
Change text
For : https://github.com/WordImpress/Give/issues/2192
=> Fix - issue #2192

includes/admin/class-addon-activation-banner.php, includes/admin/class-i18n-module.php
=> Smoothly render addon activation message

includes/payments/functions.php
Add new filter `give_pre_insert_payment`. We can pre process donation data before creating new donation.
=> Add new filter

includes/admin/tools/import/class-give-import-donations.php
=> Revert "Map postal code to zip during importing"

includes/admin/tools/import/class-give-import-donations.php, includes/import-functions.php
PR for issues #2164 
Tested by uploading the CSV which has postal code as column and it is auto selected as ZIP in the CSV mapping
=> Issues 2164

templates/email-login-form.php
This is a minor PR to replace `AS` with `as`
=> MinorFix/Replace 

includes/country-functions.php
https://givecommunity.slack.com/archives/C2P2NQVLK/p1509699412000105
Correct spelling of Philippines
It's a typo fix...
N/A
Typo fix
=> Correct spelling of Philippines

includes/admin/payments/view-payment-details.php
This PR will fix #2280
- This issue only occurs with PHP version 7.1.4
- Min PHP version 5.3.29
- Tested with Fee Recovery
- String value provide in json_encode which cause this issue.
=> Fix Unable to change donation level within donation details edit screen #2280

assets/scss/admin/settings.scss, includes/admin/abstract-admin-settings-page.php, includes/admin/class-admin-settings.php, includes/admin/plugins.php, includes/admin/reports/class-earnings-report.php, includes/admin/reports/class-form-reports-table.php, includes/admin/reports/class-forms-report.php, includes/admin/reports/class-gateways-report.php, includes/admin/reports/class-gateways-reports-table.php, includes/admin/reports/reports.php, includes/admin/settings/class-settings-cmb2-backward-compatibility.php, includes/admin/settings/class-settings-license.php, includes/admin/tools/class-settings-api.php, includes/admin/tools/class-settings-data.php, includes/admin/tools/class-settings-export.php, includes/admin/tools/class-settings-import.php, includes/admin/tools/class-settings-logs.php, includes/admin/tools/class-settings-system-info.php, includes/admin/views/html-admin-settings.php
PR for issues #2144 
Adding Images
=> Issues 2144

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
PR for issues #2310 
Manually Tested by add new issues and sending the PR 
PR template:
Issues Template:
=> Issues 2310

includes/admin/donors/donors.php, includes/class-give-donor.php, includes/user-functions.php, tests/unit-tests/tests-donors-db.php, tests/unit-tests/tests-donors.php, tests/unit-tests/tests-payment-class.php
Added filter when getting the donor's purchase value.
Status: In-progress.
- UnitTest
- Manually by adding the filter.
- Introduce new filter when getting purchase value.
=> Added filter when getting donor's purchase value.

includes/admin/tools/data/class-give-tools-recount-all-stats.php, includes/admin/tools/data/class-give-tools-recount-form-stats.php
The tool was broken due to this commit: https://github.com/WordImpress/Give/commit/165328f768ea8d001914c058b7a844e398849072
Apparently when you store an object using `wp_json_encode()` WP core sanitizes it like so:
**Code to see issue:**
```
$args = array(
'number'          => 30,
'status'          => 'publish',
'page'            => 1,
'output'          => 'payments',
);
$payments_query = new Give_Payments_Query( $args );
$payments       = $payments_query->get_payments();
$payments_json = wp_json_encode($payments);
echo '<pre>';
var_dump($payments);
var_dump($payments_json);
echo '</pre>';
```
**Output Before JSON Encoding:**
```
Array
(
[0] => Give_Payment Object
(
[ID] => 114
[_ID:protected] => 114
[new:protected] => 
[number:protected] => 114
[mode:protected] => test
[import:protected] …
```
=> Reset all form stats tool fix

includes/payments/functions.php
This PR is fix #2324 
Added new filter inside `give_get_earnings_by_date` function to modify the donation's earnings.
- Ran unit test
- Tested it with add-on.
=> Added filter when getting the donation's earnings between dates. give_get_earnings_by_date() function.

includes/actions.php, includes/admin/admin-actions.php, includes/admin/settings/class-settings-display.php
PR for issues #2291 
See the Video: http://youtu.be/GPmJsQfik-0?hd=1
=> Issues 2291

includes/formatting.php, tests/unit-tests/tests-payment-class.php
=> Issues 2258

includes/class-give-donate-form.php, tests/framework/helpers/class-helper-form.php, tests/unit-tests/tests-donate-form-class.php
This PR will fix #2337 
http://recordit.co/WbDAbF324n
=> Fix goal achieved message #2337

assets/js/frontend/give-donations.js
This PR will Resolve #2348 
http://recordit.co/Py9xCrE5Xj
=> Fix error when user focus out #2348

includes/forms/functions.php, includes/misc-functions.php, tests/framework/helpers/class-helper-form.php, tests/unit-tests/tests-misc-functions.php
See full description within https://github.com/WordImpress/Give/issues/2161
Resolves https://github.com/WordImpress/Give/issues/2161
- Unit test
- Manually
- UX improvement
=> Issue/2161 - Modified payment title content output for PayPal Standard and other gateways using 

.travis.yml
Modified travis build to prevent xDebug from running
Resolves #2381
=> Prevent xDebug on Travis-ci builds

includes/admin/dashboard-widgets.php
=> 1. Use give_get_total_earnings() for dashboard yearly stats

assets/js/admin/admin-scripts.js, includes/ajax-functions.php
PR to resolved #2377 
Manually test by updating the donation form in the donation single page
=> Issues 2377

includes/admin/donors/donor-actions.php
PR to fix #2371 issues
Video Added: http://screencast-o-matic.com/watch/cbX3op2OMU
=> Issues 2371

includes/payments/functions.php
This PR will fix #2393 
Manually tested with following steps defined in #2393.
=> Exit donation delete fn if payment does not exist

includes/admin/upgrades/upgrade-functions.php
PR for issues #2366 
Tested by updating the Give Database 
=> Issues 2366

includes/forms/functions.php
=> Fix PHP Warning #2466

includes/payments/class-payments-query.php
=> Fix variable checking #2468

assets/js/admin/admin-scripts.js, assets/js/frontend/give-ajax.js, includes/admin/settings/class-settings-general.php, includes/ajax-functions.php, includes/class-give-email-access.php, includes/login-register.php, includes/shortcodes.php, templates/email-login-form.php, templates/history-donations.php
I've addressed issues we've reviewed in https://github.com/WordImpress/Give/issues/2304 and improved the workflow.
1. Reworked requesting history access
2. reCaptcha works as expected
3. Moved functionality to new function 
4. Verified throttle works
5. Settings ironed out
Fixes #2304 #2474 
- UX improvement
- Code improvement
=> Email access improvements

includes/payments/class-payments-query.php, includes/payments/functions.php, readme.txt
@DevinWalker This PR will revert https://github.com/WordImpress/Give/pull/2399 changes .
Manually
=> Revert #2397

assets/js/admin/admin-scripts.js
PR to resolved #2475 
Manually Tested See the Video for more information: http://screencast-o-matic.com/watch/cbljXg25yh
=> Update drowdown on ajax completed #2475

includes/admin/tools/export/pdf-reports.php
=> Fix: Give PDF Report not output variable price. #2523

tests/unit-tests/tests-email-tags.php
This PR resolved #2483 
Minor Fix for failing unit tests in release 2.0
=> Minor Fix - Failing Unit Tests

includes/admin/upgrades/upgrade-functions.php, includes/class-give-roles.php, includes/install.php, includes/misc-functions.php, tests/unit-tests/tests-roles.php
1. Added new upgrade routine to clean up the Worker role caps
2. Rearranged upgrade routines to be in verion order
3. Added new upgrade routine and message to install.php
Resolves #2476
- Manually
- User caps cleanup
=> issue/2476 - Give Worker Role Cleanup

includes/admin/payments/class-payments-table.php
PR for issues https://github.com/WordImpress/Give-Recurring-Donations/issues/424
Pr for issues https://github.com/WordImpress/Give-Recurring-Donations/issues/424
=> Filter and action add

includes/admin/payments/class-payments-table.php
PR for issues https://github.com/WordImpress/Give-Recurring-Donations/issues/424
Pr for issues https://github.com/WordImpress/Give-Recurring-Donations/issues/424
=> Give recurring issues 424

includes/payments/backward-compatibility.php
PR to resolved #2556 
Manually test and also by adding the video
See the video: http://screencast-o-matic.com/watch/cblYFi2NJn
=> Add variable check #2556

includes/admin/emails/class-donor-register-email.php, includes/admin/emails/class-new-donor-register-email.php, includes/emails/template.php
This PR will fix #2596 
- Fix preview_id repeated in query string
- Fix user_id repeated in query string
- Tested all preview email From global or Per-Form.
=> Fix: preview_id and user_id repeated in query string when preview email #2596

includes/forms/template.php
=> grammar/clarity cleanup.

assets/scss/admin/settings.scss
Change style to map field correctly for end users on setting page by adding background colors and width CSS.
=> Issue #2507 Fix Hard to map a field to correct column on large screen

includes/forms/template.php
PR to fix #2661 and merge issues between the two PR
https://github.com/WordImpress/Give/pull/2665
https://github.com/WordImpress/Give/pull/2662
Manual Tested
=> Issues 2661 new

assets/js/admin/admin-settings.js, includes/admin/settings/class-settings-general.php
Fix #2667 
See the Video to check how I check 
Video Link: https://screencast-o-matic.com/watch/cFVFIroFIc
=> issues #2667 On currency change the currency place text symbol #2667

includes/admin/tools/import/class-give-import-core-settings.php
Resolves #2688 by clarifying the inline docs.
Tested locally
=> Issue #2688 — Add clarity to settings Importer docs

give.php, includes/admin/admin-filters.php, includes/admin/class-blank-slate.php, includes/admin/tools/import/class-give-import-donations.php, includes/api/class-give-api.php, includes/class-give-donate-form.php, includes/class-give-donor.php, includes/formatting.php, includes/forms/functions.php, includes/gateways/functions.php
Various PHPDoc changes to better reflect how the source code is actually used and has evolved.
PHPDocs don't have tests available.
PHPDocs touchups.
- [*] My code is tested.
- [*] My code follows the WordPress code style.
- [*] My code follows has proper inline documentation.
=> Phpdoc cleanup to help with Scrutinizer in #675

includes/import-functions.php
Donors are not customers. Plus I recall mentions about wordings in a ticket somewhere.
No tests available for variable name changes
Variable name changes.
- [*] My code is tested.
- [*] My code follows the WordPress code style.
- [*] My code follows has proper inline documentation.
=> rename "customer_id" variables to a better fit of "donor_id"

includes/admin/class-give-settings.php, includes/class-give-donor.php, includes/donors/class-give-donors-query.php, includes/misc-functions.php
Little bit more PHPDocs cleanup for y'all
=> update and clean up more phpdoc params

readme.txt
* Update correct date for 2.0.1
* Fix markdown link to 2.0.1 blog article
=> Fix changelog

blocks/donation-form/class-give-donation-form-block.php, blocks/donation-form/index.js, blocks/donation-form/style.scss, blocks/load-blocks.js, give.php, includes/class-give-scripts.php, package-lock.json, package.json
Initial PR for Gutenberg Donation Form Block #2456
http://recordit.co/C4nZXoLKra
=> Made PR #2724 compatible with feature/gutenberg-donation-form-block/ branch

includes/admin/donors/donors.php
Change the Donor single page title in dashboard Fix #2286 
Mannualy Tested
HTML Update
=> Change dashboard donor single page title

includes/import-functions.php
PR to fix #2725 
Tested by passing the donation status Name and also the Status Key
Adding Video: https://screencast-o-matic.com/watch/cFVUlaove6
=> Fix Status issues when importing donation #2725

.eslintrc, blocks/donation-form/class-give-donation-form-block.php, blocks/donation-form/index.js, package.json
Added React / JSX rules in ESLint. 
Uses some of the same rules as Gutenberg.
Overall linting error/warning fixes in `blocks/donation-form/index.js`.
=> Improve React / JSX linting and Form Preview

blocks/donation-form/class-give-donation-form-block.php
Right now Donation Form preview toggling **Goal** field on **Form Title** control instead of the **Form Goal** Control.
This PR aim to fix that bug.
=> Donation form preview fixes #2456

includes/forms/template.php
=> clarify language on login form

includes/admin/tools/data/class-give-tools-delete-import-donors.php, includes/admin/tools/data/class-give-tools-delete-test-donors.php, includes/admin/tools/data/class-give-tools-delete-test-transactions.php, includes/admin/tools/data/class-give-tools-recount-all-stats.php, includes/admin/tools/data/class-give-tools-recount-donor-stats.php, includes/admin/tools/data/class-give-tools-recount-form-stats.php, includes/admin/tools/data/class-give-tools-recount-income.php, includes/admin/tools/data/class-give-tools-recount-single-donor-stats.php, includes/admin/tools/data/class-give-tools-reset-stats.php, includes/class-give-db-donor-meta.php
PR to fix #2744 
Video Link: https://screencast-o-matic.com/watch/cFVvrpoxf2
=> Issues 2744

includes/import-functions.php
PR to fix #2737 
Manually tested. Please see the video to check how I have tested this out
Video Link: https://screencast-o-matic.com/watch/cFVwjvoxpN
=> Do not update meta when form is already being created #2737

assets/src/css/admin/logs.scss
=> issue-2210 Update CSS for donation export

includes/admin/tools/import/class-give-import-donations.php
PR to fix #2767 
Manually test by import the CSV and check the message
=> Fix plural and singular context of import completions message #2767

package-lock.json
Solved merge conflict present in `package-lock.json`
=> issue-2770 Remove merge conflict

includes/payments/actions.php
Pass payment ID to give_get_payment_gateway.
This PR will fix #2778
Manually
=> fix(donation-cron): pass valid parameter to fn

includes/forms/functions.php
This PR resolves #2586 
I've tested it with actual goal amount as well as total goal amount. Please check attached screenshot.
=> fix(formatting): formatting amount for goal column #2586

includes/admin/payments/class-payments-table.php
PR to fix #2785 
See the Video 
Video Link: https://screencast-o-matic.com/watch/cFnji4oCyR
=> Fix(donation-status): Remove text translation from attribute #2785

includes/template-functions.php
This pr will close #2577 
I tested with `shortcode-goal.php` by overriding it from the activated theme.
=> refactor(template): add helper give_get_locate_template fn #2577

includes/admin/shortcodes/class-shortcode-button.php
=> Uncomment script to localize script

includes/emails/functions.php
PR to resolved #2802 
Manual tested check the video for more on how I have tested this
https://screencast-o-matic.com/watch/cFnlYzoHEo
Remove deprecated function
=> fix(email): Remove deprecated functions #2802

includes/admin/shortcodes/abstract-shortcode-generator.php
This PR resolves #2259 
I've tested this PRe manually. Please check the below screenshots.
=> fix(shortcodes): display forms with publish status only

includes/forms/template.php
This PR is to support Issue https://github.com/WordImpress/Give-Form-Field-Manager/issues/198
=> fix(donate-button): add support for donate label

assets/src/js/frontend/give-misc.js, assets/src/js/frontend/give.js
This PR resolves #2762 
Manually tested to ensure that modal and reveal feature working fine and checked console for any errors.
=> fix(floatlabelsjs): Modal and Reveal feature not working #2762

.eslintrc, blocks/components/blank-slate/index.js, blocks/components/help-link/index.js, blocks/donation-form/data/attributes.js, blocks/donation-form/data/icon.js, blocks/donation-form/data/options.js, blocks/donation-form/edit/block.js, blocks/donation-form/edit/controls.js, blocks/donation-form/edit/inspector.js, package.json
- Adds"give_blocks_vars" to .eslintrc globals
- Adds"blocks" to scripts "lints:js"
- Fixes eslint errors
Manual 
N/A
Refactor
=> Eslint fix & config 

includes/class-give-db-donors.php, includes/class-give-db-logs.php, includes/class-give-db-meta.php, includes/class-give-db.php
This PR will close #2815
Manually by running code on the multisite setup.
Note: if the site does not have `Give` installed then you will get a notice for particular blog id, so it is better to add a condition to neglect those blog ids.
```
function wpravs_multisite_test() {
if( wp_doing_ajax() ) return;
$blogs_ids = get_sites();
$formIds = array( 4293, 958 );
foreach( $blogs_ids as $b ){
switch_to_blog( $b->blog_id );
$donations_obj = new Give_Payments_Query(
array(
'give_forms' => $formIds,  //all give-forms IDs
'number'     => 5,
'status'     => array( 'publish' ),
// 'start_date'  => date("Y-m-d H:i:s", $start_date),
// 'end_date'      => date("Y-m-d H:i:s", $end_date)
)
);
$donations = $donations_obj->get_payments();
error_log( print_r( wp_list_pluck( $donations, 'ID' ), true ) . …
```
=> fix(db): set correct table name for each blog on multisite #2815

includes/admin/shortcodes/abstract-shortcode-generator.php
This pr will fix #2830 
Manually by uploading files.
=> fix(media-uploads): upload file to correct folder #2830

includes/forms/template.php
PR to fix #2819 
Manual Tested, See the video to check on how I have tested this video
Video Link: https://screencast-o-matic.com/watch/cFn3jdoRyX
=> fix(donation): Fix minimum amount check in donation form #2819

blocks/README.md, blocks/components/blank-slate/README.md, blocks/components/help-link/README.md, blocks/donation-form/edit/controls.js
If applied will:
- Add documentation for blocks file structure
- Add documentation for components
- Add `edit donation form` control to donation form block 
Manual
- Documentation
- New feature non-breaking
=> Add documentation & form edit

includes/admin/plugins.php
Closes #2278 
Manually Tested by going to Give Menu in the plugin section. See the video to know more about how this PR is being tested.
Video Link: https://screencast-o-matic.com/watch/cFnt3gDfqx
=> feat(admin-plugin): Add Give menu in plugin menu section #2278

includes/class-give-cache.php, includes/misc-functions.php
This PR will close #2832.
Manually by performing donation.
=> fix(compat): resolve caching conflict with W3TC

includes/import-functions.php
This PR resolves #2851 
I've tested this PR by importing donations.
=> fix(admin-tool): getting php notice when importing donations.

blocks/donation-form/class-give-donation-form-block.php, blocks/donation-form/data/icon.js, blocks/donation-form/edit/block.js, blocks/donation-form/index.js, includes/post-types.php
- Change in plugin core to show "give_forms" in rest
- We are now using WordPress API endpoint to fetch forms
- We are now using native withAPIData higher order component for fetching available forms 
- Instead of fetching forms data again & again we are now fetching it once
- Block moved from "common" to "widgets" category this help us fix the Give block getting prominence in inserted bar
- Block icon changed to grayscale to be in sync with other block icons
- Code cleanup to remove unwanted code due to above changes
Manually
N/A
Refactor & Fix
=> Refactor & Fix (donation-block)

includes/class-notices.php
PR to fix #2857 
Manually Tested. See the Video on how I have tested this.
Video Link: https://screencast-o-matic.com/watch/cFnu0JDh9c
=> fix(donation): Updated hook for donation gateway error #2857

includes/class-give-donate-form.php
this function will give you following output:
1. `null` if the form is not `multi` type
2. empty array if the level does not found
successful response will content level information:
```
Array
(
[_give_id] => Array
(
[level_id] => 0
)
[_give_amount] => 10.000000
[_give_text] => 
[_give_default] => default
[_give_recurring] => yes
[_give_period] => year
[_give_times] => 10
)
```
=> add(function): helper fn Give_Donate_Form::get_level_info to get level info

.eslintrc, blocks/components/blank-slate/index.js, blocks/components/help-link/index.js, blocks/donation-form/data/attributes.js, blocks/donation-form/data/icon.js, blocks/donation-form/data/options.js, blocks/donation-form/edit/block.js, blocks/donation-form/edit/controls.js, blocks/donation-form/edit/form/none.js, blocks/donation-form/edit/form/preview.js, blocks/donation-form/edit/form/select.js, blocks/donation-form/edit/inspector.js, blocks/donation-form/index.js
- Fixes code inconsistency
- Following react concept of breaking down UI into components, GiveForm is further split into components
- Events for Inspector, Controls etc have been moved to respective files
- Strings updated to i18n strings
- Inline documentation & comments added
Manually
Refactor
=> Code Refactor:  Consistency, Improvement,  Documentations & Comments

includes/import-functions.php
PR to fix #2884 
I have tested this by importing the donation from the below mention CSV and then check the donation address fields box. See the Video for more information no how I have tested this out.
CSV link: https://docs.google.com/spreadsheets/d/1FZkxJDtvhAfUZYtL0HA2awfYvnuhOWbEcAK1egV0zxM/edit#gid=746278162
Video Link: https://screencast-o-matic.com/watch/cFejrjDoWN
=> fix(admin-tool): Fix billing address issues when importing donation from CSV #2884

includes/import-functions.php
PR to fix #2215 
Manually tested. See the Video for more information
Google Sheet: https://docs.google.com/spreadsheets/d/1FZkxJDtvhAfUZYtL0HA2awfYvnuhOWbEcAK1egV0zxM/edit#gid=1089390285
Video Link: https://screencast-o-matic.com/watch/cFejXpDoY7
=> feat(admin-donation): Add new dropdown option to select the currency #2215

includes/admin/class-give-settings.php, includes/filters.php, includes/gateways/actions.php, tests/unit-tests/tests-gateways.php
this PR will fix #2578 
Manually, by saving setting on the admin page and review donation form page.
=> fix(gateways): validate gateways after fetching from DB [#2578]

README.md, composer.json, composer.lock, package.json
Closes #2798 
Now, "npm install" will execute automatically after composer's install and update commands finish their execution.
=> build(composer): streamline local development setup #2798

README.md
Closes #2922 
Added correct local development instructions to the README file.
=> doc(composer): Update README after changes in streamline local development changes #2922

assets/src/js/admin/admin-scripts.js, includes/admin/class-admin-settings.php, includes/admin/settings/class-settings-general.php, includes/ajax-functions.php
Closes #2445 
Added AJAX-powered chosen.js to search pages easily
This has been manually tested.
=> WIP: feat(admin-setting): improve success/failed/history page settings #2445

assets/js/admin/admin-scripts.js
PR to fix #2932 
Manual tested by exporting the donation to CSV from Tools > Export and also by recounting the status from Tools > Data
=> fix(admin-tools): Fix JS error after exporting the donation to CSV #2932

includes/import-functions.php
PR to fix #2946 
Manually tested by Adding Company Name fields in CSV and then import that CSV 
<!-- New feature (non-breaking change which adds functionality)
=> feat(admin-importer): add company name filed in import donation import CSV #2946

includes/admin/donors/class-donor-table.php, includes/admin/donors/donors.php, includes/admin/payments/view-payment-details.php
=> fix(donation-detail-page): remove # from id for consistency

includes/admin/tools/export/class-batch-export-donors.php, includes/admin/tools/export/class-export.php, includes/admin/tools/views/html-admin-page-exports.php
PR to fix #2964 
Mannaul tested by exporting the donor CSV by selecting the Donation Form and without selecting the Donation Form
=> fix(admin-tool): clarifying  donor export settings

includes/admin/settings/class-settings-general.php, includes/payments/class-give-sequential-donation-number.php, tests/unit-tests/tests-emails.php
=> fix(admin-settings): sequential ordering settings duplicates donation id displayed #2991

assets/src/css/admin/give-admin.scss, includes/admin/shortcodes/class-shortcode-button.php, webpack.config.js
This Pr will fix #2980
Manually by visiting pages.
=> fix(compat): correctly display Give Shortcode generator on category archive editor. #2980

assets/src/css/admin/export.scss, assets/src/js/admin/admin-scripts.js, includes/admin/tools/export/class-give-export-donations.php
PR to fix #3009 
Manually tested by exportin donation and donor
<!--Bug fix (non-breaking change which fixes an issue)
=> fix(admin-tool): export donation history progress bar needs alignment with spacing #3009

includes/shortcodes.php
PR to fix #1945 
Video Link: https://screencast-o-matic.com/watch/cFfXDOD8Hg
=> fix(donor): adding Multiple Shortcodes on same page should not ask for login multiple times #1945 #3021

assets/src/js/frontend/give-misc.js
This PR will fix #3030 
Manually
=> fix(form): make JS fn global accessible

includes/currency-functions.php
This PR fix #3014 
- Manually.
=> fix(translation): used html entities for currency symbol for admin label.

assets/src/js/frontend/give-donations.js, includes/forms/template.php
=> fix(donation-form): do not output formatted min max value.

assets/src/js/admin/admin.js, includes/admin/reports/class-give-graph.php, package.json
=> feat(report): fixed graph js error on report page.

includes/install.php
This PR resolves #3074 
I've tested this with the fresh install.
=> fix(db-update): add missed update in install.php #3074

includes/payments/class-payments-query.php
This PR fix #3077 
- Tested using Query monitor for checking PHP warning.
=> fix(admin-report): check if orderby key is set or not.

includes/admin/abstract-admin-settings-page.php
**This PR is not related to an issue.** 
It adds a custom filter to modify the admin settings fields save logic depending on the section and settings screen.
By implementing a custom save function.
=> refactor(admin-setting): Add filter for custom save logic

give.php
Wrapped output in `wp_kses_post()` to sanitize HTML being delivered to user.
```
FILE: ./content/plugins/give/give.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AND 3 WARNINGS AFFECTING 6 LINES
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 | ERROR   | [ ] Class file names should be based on the class name with "class-" prepended. Expected class-give.php, but found give.php.
591 | WARNING | [ ] This comment is 50% valid code; is this commented out code?
634 | WARNING | [x] Equals sign not aligned with …
```
=> Fixing PHPCS output escaping and alignment issues.

includes/admin/tools/export/give-export-donations-exporter.php
PR to add some new hook that will help to add new columns and fields when exporting donations 
Manually tested by exporting the donation 
=> feat(admin-tool): add new hook for exporting donations

includes/admin/admin-footer.php
Fixing yoda conditional for PHPCS VIP Code Standards.
Ran PHPCS
Adding an extra `=` to make it a strict comparison.
=> PHPCS: Fixing yoda conditional in admin footer

assets/src/js/admin/admin-export.js, includes/admin/tools/export/give-export-donations-exporter.php
PR to fix #3049 
Notes: Befoering test this PR please merge the https://github.com/WordImpress/Give/pull/3066 PR first 
Manually tested by exporting donations 
Video Link: https://screencast-o-matic.com/watch/cFfZ1Xb6Fg
=> fix(admin-tool): exporting donation history progress bar keeps loading after 100% #3049

assets/src/css/admin/export.scss
=> style(admin-export): column alignment issue #3097

includes/class-give-license-handler.php, includes/misc-functions.php
Manually by visiting pages and running PHPUnit tests
=> perf(license): reduce license option query

includes/admin/class-addon-activation-banner.php, includes/misc-functions.php
This PR fix #3130 
- Manually by checking database values.
=> perf(license): reduce activation-banner option query

includes/class-give-email-access.php
Fixing sanitization of input
PHPCS resolved errors.
Fixing sanitization of input
=> PHPCS: Fixing sanitization of input

includes/forms/template.php
This PR is to support issue https://github.com/WordImpress/Give-Stripe/issues/167
I've tested this with the PR of issue https://github.com/WordImpress/Give-Stripe/issues/167 to ensure that it is working fine
=> fix(stripe): google/apple pay not working with multiple forms #167

includes/admin/tools/export/class-batch-export-donors.php, includes/admin/tools/export/class-export.php, includes/class-give-donor.php, includes/emails/class-give-email-tags.php, includes/filters.php, includes/misc-functions.php
=> fix(give): update since to 2.1

includes/admin/shortcodes/shortcode-give-donation-grid.php, includes/shortcodes.php, templates/shortcode-form-grid.php
=> Revert "fix(shortcode): fix form grid redirect issues"

includes/admin/tools/import/class-give-import-donations.php
PR to fix text translations as discussed with @DevinWalker over call
Manually tested by weppack
=> fix(admin-tool): fix text translations

includes/admin/shortcodes/abstract-shortcode-generator.php, includes/admin/shortcodes/shortcode-give-donation-grid.php
This pr will resolve #3166 
Manually by accessing form grid shortcode builder.
=> fix(shortcode): clarify Donation Form Grid shortcode generator #3166

includes/class-give-stats.php
This pr will resolve #3156 
By checking dashboard donation stats widget.
=> fix(admin-dashboard): correct weekly donation total in dashboard widget #3156

includes/misc-functions.php
This PR fix #3153 
- Tested it by activating single add-on.
- Tested it by activating multiple add-ons at the same time.
=> fix(activation-banner): display activation banner immediately.

assets/src/js/frontend/give-donations.js
ensure min / max notice stays persistent until value_n…ow is greater or less than max min
- Manually
- Bug fix
=> fix(donation): focusing out of amount fields remove error message 

includes/emails/class-give-email-tags.php
PR to fix get_the_date argument that was getting passed 
Function documentation https://codex.wordpress.org/Function_Reference/get_the_date 
Tested by manual making donation 
=> fix(admin-email): fix post date function argument 

assets/src/js/frontend/give-donations.js
PR to fix #3176 
Manually tested see the video to know more about how I have tested this PR
Video Link: https://screencast-o-matic.com/watch/cFhfr3bZhY
Issues link: https://github.com/WordImpress/Give/issues/3029 where we remove the formatting from PHP
Bug fix (non-breaking change which fixes an issue) /
=> fix(donation): ensure minimum donation is accurate with , separator #3176

assets/src/js/frontend/give-donations.js, includes/ajax-functions.php, includes/class-give-scripts.php, includes/emails/class-give-email-tags.php, templates/email-login-form.php, templates/history-donations.php
Not connected to any issues but this PR is to add support for https://github.com/WordImpress/Give-Recurring-Donations/issues/479
=> feat(shortcode): add hooks and hidden fields in email access form

includes/admin/tools/export/class-batch-export-donors.php, includes/class-give-donor.php, includes/forms/functions.php, includes/forms/template.php, includes/user-functions.php, templates/shortcode-profile-editor.php, tests/unit-tests/tests-donors.php
PR to fix #2935 
Tested Mannualy 
=> feat(donor): add get donor address method to Give_Donor Class #2935

includes/forms/template.php, includes/process-donation.php
This PR Fix #3203 
- By creating donation using Give-Currency-Switcher add-on.
=> fix(currency-switcher): amount should be formatted based on the currency I switched into.

includes/process-donation.php
This PR fix #3203 
- With Set, Multi-level donation.
=> fix(donation): return true if donation form has custom amount option disabled.

assets/src/js/frontend/give-donations.js, includes/class-give-html-elements.php
This is a quick fix. This is not related to any issue.
By changing the country on the donation form fields.
=> fix(donation): Add autocomplete to ajax generated fields

includes/admin/emails/abstract-email-notification.php, includes/admin/emails/class-email-notification-util.php
PR to fix https://github.com/WordImpress/Give-Email-Reports/issues/47
=> refactor(admin-email): update email class method

includes/admin/shortcodes/shortcode-give-donation-grid.php
Fixes #3235
Locally, only string changes
And:
String changes
=> fix(admin-form): Fix language on Form Grid modal

includes/admin/emails/abstract-email-notification.php, includes/admin/emails/class-donation-receipt-email.php, includes/admin/emails/class-donor-register-email.php, includes/admin/emails/class-email-access-email.php, includes/admin/emails/class-email-setting-field.php, includes/admin/emails/class-new-donation-email.php, includes/admin/emails/class-new-donor-register-email.php, includes/admin/emails/class-new-offline-donation-email.php, includes/admin/emails/class-offline-donation-instruction-email.php
Closes #3110 
This PR adds a new settings field called "Email Header".
Tested preview and send test email in the following:
- New Donation
- Donation Receipt
- New Offline Donation
- Offline Donation Instructions
- New User Registration
- User Registration Information
- Email Access
=> feat(admin-email): Add "Email Heading" as a customizable setting for all Emails #3110

includes/process-donation.php
This PR fix #3203 
- Tested it with the set donation
- Tested it with the multi-level donation
- Tested it with Currency Switcher.
- Tested all the above cases again by disabling the browser JS.
=> fix(donation): improved the logic of verifying min/max amount.

includes/admin/tools/export/give-export-donations-exporter.php
This is related to Give Recurring issue https://github.com/WordImpress/Give-Recurring-Donations/pull/630
The PR adds an action hook and a filter hook.
=> feat(admin-tool): Added a new action and filter

assets/src/js/admin/admin-scripts.js, includes/admin/admin-actions.php, includes/admin/donors/donor-actions.php, includes/admin/emails/class-donation-receipt-email.php, includes/admin/emails/filters.php, includes/admin/give-metabox-functions.php, includes/admin/payments/actions.php, includes/admin/payments/view-payment-details.php, includes/admin/reports/graphing.php, includes/api/class-give-api.php, includes/emails/functions.php, includes/emails/template.php, includes/misc-functions.php
=> feat(notices): add multiple message support to give-message #1936

includes/api/class-give-api.php
=> fix(give-api): Make Donations Types Respect Daterange as intended #3191

includes/import-functions.php
PR to resolve #2135 
Tested by exporting the donation and then importing it again 
=> fix(admin-tool): export and Import of Donations must be in sync without errors #2135

includes/admin/settings/class-settings-general.php
PR to fix #2423 
Test by search in the country dropdown list 
=> feat(ffm): add chosen dropdown to Country and State #2423

includes/payments/class-give-payment.php
Tested with this pr: https://github.com/WordImpress/Give-Fee-Recovery/pull/199
=> fix(donation): prevent donation amount from updating multiple times #3304

includes/payments/class-give-payment.php
=> Revert "fix(donation): prevent donation amount from updating multiple times #3304"

includes/forms/template.php, includes/misc-functions.php
This PR is to provide support as a minimum requirement for https://github.com/WordImpress/Give-Stripe/pull/225
I've tested this PR to ensure that there is no issue with Give Core version 2.1.4
=> fix(stripe): move google pay donate button to the bottom for consistent UX #223

assets/src/css/admin/settings.scss, includes/admin/abstract-admin-settings-page.php, includes/admin/settings/class-settings-cmb2-backward-compatibility.php
=> fix(plugin-conflict): wpml laguage submenu item adding into admin setting sub menu list #3314

includes/misc-functions.php
PR to fix #2322 
Test by sending mail from admin welcome screen
=> fix(admin-welcome): issues when sign up for the Give newsletter #2322

assets/src/css/frontend/alerts.scss, includes/class-notices.php
Closes #3337 
Refactored SCSS for alerts.
By testing all types of front-end notices.
=> fix(form): Be more specific with .notice-dismiss class #3337

includes/class-give-db-meta.php
PR to fix #3345 
Tested by activating the [qTranslate X](https://wordpress.org/plugins/qtranslate-x/) Plugin and without that add-on too 
Adding Video: https://screencast-o-matic.com/watch/cF1l6JFfJk
=> fix(compat): ensure Give doesn't conflict with qTranslate X #3345

includes/process-donation.php
This PR fix #3372 
- Tested it by switching the currency.
=> fix(donation-form): sanitize the donation amount based on the form's currency.

includes/formatting.php
This pr will resolve #3373 
I tested this pr with multiple currencies.
=> fix(Donation-goal): Goal amount should not change on re-saving the settings #3373

give.php, includes/admin/forms/class-give-clone-forms.php
Closes #3331
This PR adds a feature to clone Donation Forms.
By cloning donation forms.
=>  feat(admin-form): give users ability to clone forms #3331

includes/admin/tools/export/give-export-donations-exporter.php
PR to fix #3380 
Tested by exporting donation form `Donation Option`  ad `multi-level` and `Set Donation` both
Check the video to know more on how I have tested this issues 
Adding Video: https://screencast-o-matic.com/watch/cF1qlbFlUB
=> fix(admin-tool): ensure the level title in the exported CSV reads custom on custom donations #3380

includes/admin/payments/actions.php
PR to fix #3085 
Tested by creating a new donation form and then add a new donation into it and then update the donation amount from the donation dashboard 
Video Link: https://screencast-o-matic.com/watch/cF1YYxF2qE
=> fix(admin-donation): form earnings does not update when change donation amount #3085

includes/admin/tools/export/pdf-reports.php
This PR fix #3395 
- Tested it by following steps mentioned inside the issue.
=> fix(admin-tools): export the donation of current year only.

includes/class-give-scripts.php, package.json, webpack.config.js
This PR will resolve #3433
I've tested this with Stripe CC fields to ensure that there are no conflicts.
=> fix(compat): move `babel-polyfill` to Give core #3433

assets/src/css/frontend/modal.scss, assets/src/js/frontend/give-misc.js
Closes #3424 
This PR adds the `.give-modal` class to the modal popup in Form Grid.
By opening a popup on a form on a form grid page.
=> fix(compat): resolve modal background scrolling on iOS #3424

includes/admin/emails/filters.php, includes/admin/shortcodes/class-shortcode-button.php
=> Revert "fix(emails): Remove Give shortcode button from Emails Settings Page"

readme.txt
Fixed spelling of compatibility
It hasn't as it's a string change in readme
readme string change
=> Fixed spelling of compatibility

includes/admin/settings/class-settings-general.php, includes/gateways/offline-donations.php
=> fix(admin-plugins): replace tags on offline donation instructions

assets/src/js/frontend/give-ajax.js, assets/src/js/frontend/give-donations.js, assets/src/js/frontend/give-misc.js, includes/gateways/actions.php
this PR will resolve #3448
Tested with razorpay: https://github.com/WordImpress/Give-Razorpay/tree/fix/give-session
=> fix(donation): update all nonce when deprecated on cache donation form #3448

includes/forms/template.php, includes/gateways/actions.php
=> fix(donation): set unique create new user nonce for each form #3451

assets/src/css/frontend/give-frontend.scss, assets/src/js/frontend/give-ajax.js, includes/ajax-functions.php, includes/shortcodes.php, templates/receipt/placeholder.php
=> fix(receipt): load donation receipts via Ajax #3412

includes/admin/plugins.php
PR to fix #3438 
Tested by activating/deactivating the Add-on  from Give Menu tab page
=> fix(admin-plugins): fix on activation/deactivation of add-on plugin menu change #3438

includes/admin/class-admin-settings.php, includes/admin/forms/class-metabox-form-data.php, includes/admin/give-metabox-functions.php
Reverts WordImpress/Give#3475 as it is still in progress
=> Revert "fix(admin-form): 2.2 ensure name title prefixes can be removed once saved #3466"

assets/src/js/admin/plugin-deactivation-survey.js, includes/admin/plugins.php
PR to fix #3484 
Tested by activating the Give Core plugin and also by sending the server report 
=> fix(admin-plugin): fix PHP notices when deactivating the Give Core Add-on #3484

includes/admin/emails/class-donor-register-email.php, includes/user-functions.php
Closes #2997 
The code is updated with correct hooks for the email tags to work.
Registration new user
=> fix(emails): resolve malfunctioning email template tags #2997

includes/admin/donors/class-donor-table.php, includes/admin/donors/donors.php, includes/admin/forms/class-metabox-form-data.php, includes/admin/settings/class-settings-display.php, includes/admin/tools/export/give-export-donations-exporter.php, includes/admin/tools/export/give-export-donations-functions.php, includes/admin/tools/logs/class-sales-logs-list-table.php, includes/emails/functions.php, includes/misc-functions.php, includes/payments/class-give-payment.php, includes/user-functions.php, templates/shortcode-receipt.php
This PR resolves #3488 
I've tested this with all the possible scenarios as per the screenshots below.
**Donation Receipt**
**Admin Settings & Metabox Settings**
**Donation Detail Page**
**Donor Detail Page**
**Donor Listing Page**
**Donations Listing Page**
**Emails**
=> fix(form-settings): Ensure prefixes works as described #3488

includes/admin/upgrades/upgrade-functions.php
This pr will resolve #3525
By running updates
=> Increase donors table email column length #3525

includes/donors/class-give-donor-stats.php, includes/payments/functions.php
=> Donor Wall Issue(s) #3532

readme.txt
Fixes #3539 by updating the active install count, the release date, and updating the changelog with the currently closed items on the 2.2.1 release. Two issues are on the release that are not yet closed and have NOT been added to this changelog yet. See here:
=> Fixes #3539

includes/admin/tools/import/class-give-import-donations.php
PR to fix #3547 
Tested by importing donations in PHP version 5.3 and also in PHP version 7.2
=> fix(admin-tools): fix PHP notices when importing donation from CV #3547

README.md
=> Fix local development link

includes/forms/template.php
Closes #3566 
This PR uncomments the action hook.
=> fix(forms): Uncomment action hook #3566

assets/src/js/frontend/give-ajax.js
PR to fix #3562 
Tested by submitting the donation with proper data and without proper data 
=> fix(donation): prevent login button text from updating with wrong text #3562

includes/admin/class-admin-settings.php, includes/admin/emails/class-email-notifications.php
This PR will resolve #3541 
This PR tested with recurring addon: https://github.com/WordImpress/Give-Recurring-Donations/tree/hotfix/renewal-email
=> fix(admin-settings): refactor setting API to have custom save logic for setting sections #3541

includes/import-functions.php
Pr to fix #3592 
Testing by importing the donation from CSV
Also testing by making a donation from frontend 
=> fix(admin-tools): do not send mail when importing donations through CSV #3592

assets/src/js/admin/admin-export.js, assets/src/js/admin/admin-importer.js, assets/src/js/admin/admin-scripts.js, assets/src/js/admin/admin-settings.js, assets/src/js/admin/plugin-deactivation-survey.js, assets/src/js/frontend/give-ajax.js, assets/src/js/frontend/give-donations.js, assets/src/js/frontend/give-misc.js, assets/src/js/plugins/give-api/api.js, assets/src/js/plugins/give-api/form.js, assets/src/js/plugins/give-api/notice.js, assets/src/js/plugins/modal.js, includes/admin/shortcodes/admin-shortcodes.js
This PR will resolve #3599 
Testing continues....
=> fix(js-api): allow getGlobalVar function to extract value from localize param when use un admin #3599

assets/src/js/admin/admin-settings.js, includes/class-give-scripts.php
This will fix #3490  and removes `give.js` from front end.
By testing real-time formatting.
=> fix(admin-setting): Remove give.js from backend

assets/src/js/admin/admin-scripts.js
Closes #3597
This PR fixes the unwanted popup that occurs during pagination.
By entering a number in the pagination input field, hitting enter and then navigating to the desired page.
=> fix(admin-donations): remove unwanted js popup when view custom page #3597

assets/src/js/frontend/give-donor-wall.js
PR to fix #3599 
Test by click on load more button
Video Link: https://screencast-o-matic.com/watch/cFjviVqwG4
=> fix(js-api): replace give_vars and give_global vars with getGlobalVar

includes/admin/settings/class-settings-gateways.php, includes/gateways/paypal-standard.php, includes/process-donation.php
This PR will fix #3651 
- Manually tested with PayPal standard and Donation type and test with Recurring
- New feature (non-breaking change which adds functionality)
=> feat(paypal): send more actionable info to Paypal to differentiate transactions #3651

includes/admin/payments/actions.php, includes/admin/upgrades/upgrade-functions.php, includes/class-give-donor.php, includes/donors/actions.php, includes/donors/class-give-donor-stats.php, includes/donors/class-give-donor-wall.php, includes/install.php, templates/shortcode-donor-wall.php
This pr will resolve #3613 
https://www.useloom.com/share/f5229a2fcfc24019bdb3962c8e54565c
=> feat(donor-wall): allow to set donor as anonymous only per form basic

tests/e2e/README.md
Closes #3625 
Related #2350 
This PR contains the documentation for E2E frontend testing.
=> doc(jest): add UI testing instructions #3625

assets/src/js/frontend/give-donations.js, includes/ajax-functions.php, includes/country-functions.php, includes/forms/template.php, includes/process-donation.php
PR to fix #3669 
Tested by changing the Country fields
Video Link: https://screencast-o-matic.com/watch/cFQI6KqJ7P
New feature (non-breaking change which adds functionality )
=> feat(form): have requirement for City removed when Singapore is selected as country #3669

assets/src/js/admin/admin-scripts.js, includes/admin/tools/data/class-give-tools-delete-donations-only.php, includes/admin/tools/data/tools-actions.php, includes/admin/tools/views/html-admin-page-data.php, includes/class-give-scripts.php
Closes #3583 
This PR adds a feature which deletes donations only from a specified date range.
Tested by specifying/not specifying date range and deleting donations.
=> feat: add option to delete only donation data #3583

includes/forms/template.php
This PR will fix  https://github.com/impress-org/give/issues/3714
=> fix: replace `Card Name` with `Cardholder Name` #3714
